### ISSUE TITLE
Set up Class documentation framework

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#10]
Love this:
http://typedoc.io/api/

Can we get it?

**Comment by sebastianhaas** [comment]
Get this done before required changes cause too much workload.  (0.0.1-alpha.3)

**Comment by oliver-h** [comment]
Like it too, no objection from my side...

What overload?

**Comment by sebastianhaas** [comment]
> What overload? 

Hm?

**Comment by sebastianhaas** [comment]
I think we want to have our documentation MD-based on [Github Pages](https://pages.github.com/). It's free, can be enhanced by anyone using PRs and is easy to setup. 

The only question will be how to generate class documentation based on the inline comments of our typescript sources and get it into our page repo. Maybe it is possible to use typedoc with a Markdown output.

**Comment by oliver-h** [comment]
>> What overload?

>Hm?
Sorry, I meant why should the workload increase? Aren't these pages generated from standard javadoc? So as long as we use javadoc comments, the workload is independent of the doc generator...

**Comment by sebastianhaas** [comment]
Because, every documentation standard has it's own little differences :) 
E.g. the proposed typedoc creates inter-class links using  double brackets `[[MusicSheetReader]]`.

Afaik we don't use any of this atm, so the more stuff we write before our final doc format is decided, the more we have to change afterwards. It's not a big problem though. 🌹

**Comment by oliver-h** [comment]
do it! do it!

**Comment by sebastianhaas** [comment]
@bukaznik could you please get me a subdomain of opensheetmusicdisplay ready for the documentation?

**Comment by sebastianhaas** [comment]
See [feature/typedoc](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/tree/feature/typedoc).
I made a first run, added a grunt task etc. Looks promising, however, since opensheetmusicdisplay is not using the recommended module structure, the output is quite verbose and weird. On class-level its fine though.

![screenshot 2016-08-17 15 17 26](https://cloud.githubusercontent.com/assets/6751545/17737606/0f8c4d78-648e-11e6-8cec-6bef218a2699.png)

Ideas? Can we change the module structure? 🐵

**Comment by sebastianhaas** [comment]
Nvm, I found a way around it somehow.

@bukaznik I guess we can live with that URL anyway. I guess its a good solution, plus we can add different kind of documentation and examples as well!
https://opensheetmusicdisplay.github.io/

**Comment by sebastianhaas** [comment]
Fixed in #42
