### ISSUE TITLE
Wrong test description

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#1002]
![image](https://user-images.githubusercontent.com/2137569/113944240-9dbce880-97da-11eb-98a9-c17377045f56.png)

![image](https://user-images.githubusercontent.com/2137569/113944320-b927f380-97da-11eb-8aaf-db5a9c7dafec.png)

I'm not very good at theory, sorry if it is right. But I think this two are mismatching.

**Comment by sschmidTU** [comment]
No, this is correct. In this `majorMap`, -1 means a fifth downwards. -2 = 2 fifths downwards from C = Bb major.
In the second image, if you used "minor" instead of "major", it would be Bb minor, which has the same accidentals as Db major. (like A minor has the same as C major).

**Comment by sschmidTU** [comment]
See the circle of fifths.
![image](https://user-images.githubusercontent.com/33069673/113944750-5bf56780-9805-11eb-8286-31fb2093d562.png)
https://en.wikipedia.org/wiki/Circle_of_fifths

**Comment by conde2** [comment]
I'm trying to learn while making the transpose, I will read more about it before continuing, because I'm getting confused.
I'm using this map to get the correct key and then with the correct key I will use the circle of fifth to display a list of transpose options.

This is what I've got so far.

```typescript
    const majorMap: {[_: number]: string } = {
      "-1": "F", "-2": "Bb", "-3": "Eb", "-4": "Ab", "-5": "Db", "-6": "Gb", "-7": "Cb", "-8": "Fb",
      "0": "C", "1": "G", "2": "D", "3": "A", "4": "E", "5": "B", "6": "F#", "7": "C#", "8": "G#"
    };

    const minorMap: {[_: number]: string } = {
        "-1": "D", "-2": "G", "-3": "C", "-4": "F", "-5": "Bb", "-6": "Eb", "-7": "Ab", "-8": "Db",
        "0": "A", "1": "E", "2": "B", "3": "F#", "4": "C#", "5": "G#", "6": "D#", "7": "A#", "8": "E#"
    };

    const transposeCircle = [ 
      [ "C" ],
      [ "C#", "Db" ],
      [ "D", ],
      [ "D#", "Eb" ],
      [ "E" ],
      [ "F" ],
      [ "F#", "Gb" ],
      [ "G" ],
      [ "G#", "Ab" ],
      [ "A" ],
      [ "A#", "Bb" ],
      [ "B" ],
    ]

    const staffIndex = 0;
    const keyInstruction = this.osmd.Sheet.SourceMeasures[0].getKeyInstruction(staffIndex);

    //  if it's positive it's sharps, if negative it's flats, if 0 it's no accidentals (C major / a minor).
    const numberOfAccidentals = keyInstruction.Key;
    
    // Major or Minor (class KeyEnum)
    const mode = keyInstruction.Mode;
    
    let currentKey = "C";
    if (mode === KeyEnum.major) {
      currentKey = majorMap[numberOfAccidentals];

    } else if ( mode === KeyEnum.minor) {
      currentKey = minorMap[numberOfAccidentals];
    }   

```

**Comment by sschmidTU** [comment]
1 in the majorMap is a fifth, i.e. 7 semitones.
1 in `osmd.Sheet.Transpose` is 1 semitone.
To transpose from C to F, it's 7 semitones downwards, or 5 semitones upwards, it's your choice which way you want to transpose.
To transpose from any key to another, you need to find the amount of semitones upwards or downwards.
To find that, you can make a map { C: 0, C#: 1, D:2, ..., B: 11 } and add or subtract the difference of your keys for upwards or downwards.

**Comment by sschmidTU** [comment]
Oh, you're talking about Bb vs B major. Yes, that's a typo. Bb is just B in german, while B is H ;)
