### ISSUE TITLE
Cursor freeze 

### ISSUE THREAD

**Issue by lianusmusic** [opensheetmusicdisplay/opensheetmusicdisplay#1005]
Hello OSMD 
I am trying to freeze the cursor and show it by measure. Do you have any suggestion that  I could Use?

I arrived to the point I learned how to use the cursor.next() but I  still don't get how can I set the duration of each note, so every note has  the same duration. Because of this I thought that maybe was better to show the cursor by measure and give it a fixed time . Could you give me an idea of how to work. I leave my code where I just arrive to the use of the cursor.show () and hide in the measure 3 but that is not exactly what I am trying to do. 

1)Is there any way to show the cursor for the time of the measure duration and then jump to the next measure, avoiding passing through every note? (saying that the jump next would be the next measure. ) 
2) Or where could I find the info to apply to every note, each different durations related with the Beat. ?

Thanks, Liana
My code

In the .JS

`var intervalo;
var cantidadnotas = 0;
var firstplay = 0;
//toggle between playing and pausing on button click
const playBtn = audioPlayer.querySelector(".controls .toggle-play");
playBtn.addEventListener(
  "click",
  () => {
    $(".player").addClass("fixed");
    if (audio.paused) {
      playBtn.classList.remove("play");
      playBtn.classList.add("pause");
      audio.play();
      playing = 1;
      if(cantidadnotas ==0){        
        osmd.render();
        osmd.cursor.show();
        osmd.FollowCursor = true;
      }     
      if(firstplay == 0){
        setTimeout(function(){             
          intervalo = setInterval(avanzarcursor, velocidad);
        }, delay_inicio_audio);       
        firstplay = 1;
      }
      else{
        intervalo = setInterval(avanzarcursor, velocidad);        
      }   

    } else {
      playBtn.classList.remove("pause");
      playBtn.classList.add("play");
      audio.pause();
      playing = 0;
      clearInterval(intervalo);
    }
  },
  false
);

// hiding measure 3 - test
function avanzarcursor(){  
  console.log(osmd.cursor.iterator.currentMeasure.MeasureNumber)
  if(cantidadnotas <= topenotas){
    if(playing == 1){
        osmd.cursor.next();     
        if(osmd.cursor.iterator.currentMeasure.MeasureNumber ==3) {
          //osmd.cursor.hide();
          $("#cursorImg-0").attr("width","0")
        }
        else if(osmd.cursor.iterator.currentMeasure.MeasureNumber >3){
          //osmd.cursor.show();
          $("#cursorImg-0").attr("width","30")
        }
        cantidadnotas++
    }
  }
  else{
    clearInterval(intervalo);
  }
}`
``

In the HTML
        <script>
            //audio file          
            var audio = new Audio("media/B201b_Quick.mp3");    
            
            // Player variable
            var delay_inicio_audio = 800;
            var velocidad=286;  
            var compases = 8;
            // Las notas + 1
            var topenotas = 107;            
        </script>

**Comment by sschmidTU** [comment]
Hi, with the brand new OSMD 1.0.0 you can now add more cursor options and multiple cursors.
To use 1 cursor which highlights the current measure, set this:
```js
osmd.setOptions({
  cursorsOptions: [
    {type: 3, color: osmd.EngravingRules.DefaultColorCursor, alpha: 0.5, follow: true}
  ]
}
```

![image](https://user-images.githubusercontent.com/33069673/117383133-52345200-aee0-11eb-9378-a0a44496bfdc.png)

Advancing the cursor time-based or for one measure is currently not possible, you'd have to implement that yourself. It's part of our playback code, which is integrated in the OSMD Audio Player, which is currently only available in early access to [Github Sponsors](https://github.com/sponsors/opensheetmusicdisplay).
