### ISSUE TITLE
chord collision with notes

### ISSUE THREAD

**Issue by lianusmusic** [opensheetmusicdisplay/opensheetmusicdisplay#1007]
Hello. How could I fix this collision. Thanks!
Liana
![collision](https://user-images.githubusercontent.com/66888982/114450984-b34c5c80-9ba4-11eb-8989-d32e9fc49723.png)

**Comment by sschmidTU** [comment]
We're still working on ChordSymbol collision.
For now, as a workaround, you can e.g. set `osmd.rules.ChordSymbolYOffset = 3.0`.
