### ISSUE TITLE
Add repetition tags support.

### ISSUE THREAD

**Issue by ogomezm** [opensheetmusicdisplay/opensheetmusicdisplay#101]
Support for MusicXML files containing all the repetition set symbols and patterns.

There is already an idea of how implement it in some commented lines within the code of the MusicSheetReader.ts and InstrumentReader.ts.

**Comment by sebastianhaas** [comment]
Is this a feature request or would you be willing to help out on that?

Either way, I'll try to get an idea of how much work this actually is and let you know whether we have this on our agenda for the next weeks or not.

**Comment by ogomezm** [comment]
Hi Sebastian, 
Thanks for your quick response, I want to help on that.
Anyway I need help to define the right implementation for it.

**Comment by sebastianhaas** [comment]
Cool, I will gather some information on the topic and try to provide you with same basic groundwork and ideas to start from!

**Comment by ogomezm** [comment]
Ok, Thanks.

**Comment by ogomezm** [comment]
Hi Sebastian,

I have forked and created a test with a song I have found in:
[https://www.musicxml.com/music-in-musicxml/example-set/]

For the first iteration I want to be able to render Saltarella song.

I will let you know if there is something I get stuck with.

**Comment by sebastianhaas** [comment]
Hi Oscar

Having a discussion right now, and I think we can provide the xml parsing/converting repetition data into our own data objects for rendering part since we have already done it in another project.

I'll try to provide some hard facts asap. Btw, I created a gitter room for OSMD.

**Comment by ogomezm** [comment]
Cool!, I am working in reading the XML and creating the repetitionInstruction, but I have not tested the rendering part yet.

Ok, I will join gitter to join the room.

**Comment by sebastianhaas** [comment]
I just pushed a few changes to the `feature/Repetitions` branch and rebased it on the latest `develop` (dependecies updated etc.).

I will continue to improve the development workflow and tools over the next couple of weeks, but for now, in the repetitions branch, it should work like this: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Developing

It would be cool if you could make your changes on top of this branch. :)

**Comment by sebastianhaas** [comment]
As for the repetition stuff itself, please feel free to ask them here or at Gitter.

`RepetitionInstructionReader` parses and processes the MusicXML information with the help of `RepetitionCalculator`. It's not tested, but in theory you should get a bunch of [`RepetitionInstruction`](https://opensheetmusicdisplay.github.io/classes/repetitioninstruction.html)s in the measures, which has to be handed over to the vexflow rendering engine.

Oh, btw. I also added Saltarello to our standard set of MusicXML's so you should be able to select it from the dropdown.

**Comment by ogomezm** [comment]
Cool Sebastian, tomorrow I will read all the changes and I will start adding my code on top of that branch. 
Thank you so much.

**Comment by joaocc** [comment]
@ogomezm and @sebastianhaas 
Any update on merging this feature into the main branch? Is there anything we can help with?
Thanks

**Comment by matt-uib** [comment]
@ogomezm how are things going with the repetitions? Are you still on it - do you have already something coded? If not please let us know, so that maybe somebody else could jump in onto showing the repetitions.
