### ISSUE TITLE
How to add options for StaffHeight

### ISSUE THREAD

**Issue by impactcolor** [opensheetmusicdisplay/opensheetmusicdisplay#1013]
(I attempted to add this on SO but there is no tag for open sheet music display) sorry for posting here.
I currently set options for OSMD like so:

```
      var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdCanvas");
    	osmd.setOptions({
    		backend: "svg",
        drawTitle: true,
    		coloringEnabled: true,
    		coloringMode: 1,
    		colorStemsLikeNoteheads: true,
    		drawTimeSignatures: true,
    	})

```
I would like to control the StaffHeight as found in the Class VexFlowStaffLine documentation
I'm a little confused as to where I would add this:

```
    StaffHeight
    get StaffHeight(): number
    Inherited from VexFlowStaffLine.StaffHeight
```

I attempted to add it like so before osmd.render but no success as VexFlowStaffLine is undefined.

```
    var vex = new VexFlowStaffLine();
    vex.StaffHeight(50);

```
Any idea how I can achieve this?

**Comment by conde2** [comment]
```ts
    this.osmd.EngravingRules.StaffHeight = 50;
```

Note that you will need to re/render the score after that.

**Comment by impactcolor** [comment]
Awesome, thank you! @conde2
