### ISSUE TITLE
Attempting to set spacing between notes

### ISSUE THREAD

**Issue by impactcolor** [opensheetmusicdisplay/opensheetmusicdisplay#1015]
I'm attempting to set space between the notes.
I've tried:
`	osmd.setOptions({
		backend: "svg",
    drawTitle: true,
		spacingFactorSoftmax: 50
	})`

The above did not show any changes.
I also tried:
`osmd.EngravingRules.SoftmaxFactorVexFlow`

That also did not show any changes.  Any idea what I'm doing wrong or how I could accomplish this?

**Comment by conde2** [comment]
You can try this:

```ts
        this.rules.VoiceSpacingMultiplierVexflow = 0.65;
        this.rules.VoiceSpacingAddendVexflow = 2.0;
```

**Comment by sschmidTU** [comment]
Yes, the first two will make the notes more compact, though it can lead to collisions.
You can also try ̀`osmd.setOptions({drawingParameters: "compacttight"})`,
see `DrawingParameters.setForCompactTightMode()` for individual parameters you can adjust.

**Comment by sschmidTU** [comment]
Btw, Softmaxfactor only works with Vexflow 3.x, which has formatting issues.

**Comment by sschmidTU** [comment]
test
