### ISSUE TITLE
Cannot Access Private `rules` Member

### ISSUE THREAD

**Issue by loganknecht** [opensheetmusicdisplay/opensheetmusicdisplay#1017]
Hello!

# Gratitude

As always, I just want to say I love your team, and keep it up! You've helped make [Piano Gym](https://pianogym.com) such a great tool!
![iloveyou](https://user-images.githubusercontent.com/1308524/116835238-77d6f980-ab76-11eb-8546-7a684045172e.gif)

# Bugfix

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/660#issuecomment-767030765

In your previous post here you mentioned that the easiest way to retrieve a graphical note is to use the note and then call `osmd.rules.GNote()`. This is great!

The issue is that when I try to follow that guidance I can't access `rules` in my IDE because it's a private member and it yells about that.

So the result is I end up having to get the note by doing this.
```javascript
const graphical_note = (open_sheet_music_display_object as any).rules.GNote(note_to_find) as GraphicalNote;
```

Which isn't ideal, but it does work.

# Suggestion

Make rules publicly accessible through `Rules`. Or something else. :)

**Comment by sschmidTU** [comment]
`osmd.EngravingRules` is public :)
`osmd.rules` is a shortcut for javascript people who don't care about private/public ;)
