### ISSUE TITLE
Multiple instruments has wrong render

### ISSUE THREAD

**Issue by wuxq** [opensheetmusicdisplay/opensheetmusicdisplay#1022]
Hi there,
  I have a MusicXml which rendering ok in MuseScore
[my_country_and_I.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6440124/my_country_and_I.xml.zip)

![image](https://user-images.githubusercontent.com/1889069/117418625-38315880-af4e-11eb-990a-00214c41cc33.png)

 but wrong in OSMD
 
![image](https://user-images.githubusercontent.com/1889069/117419327-066cc180-af4f-11eb-8a6d-6a313d306b3e.png)

Then I need use "cursor next" to play the musicxml, the MuseScore rendering is a good way.

Cheers

**Comment by sschmidTU** [comment]
You could submit a pull request.

**Comment by sschmidTU** [comment]
Already fixed in #1062 (OSMD 1.3.1 or possibly before)
![image](https://user-images.githubusercontent.com/33069673/144418482-396aed88-1afb-4754-9ac1-4d07b0a91666.png)
