### ISSUE TITLE
Move to webpack

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#103]
### Why?
* More experience on the team with webpack than browserify
* Popular with Angular 2
* Real-time compilation makes for a smoother workflow
* More plugins and extension tooling

### How?
Take a look at the angularclass example repository and webpack's documentation and setup a basic infrastructure.

### Steps to complete
- [x] A basic build setup was introduced by @bneumann in #127.
- [x] Move configuration to a `webpack.config.js` to make it work without grunt.
- [ ] Extend setup with test/release configurations (builds that include/exclude tests)
- [ ] Remove browserify
- [ ] Remove grunt #156

**Comment by sebastianhaas** [comment]
- [x] A basic build setup was introduced by @bneumann in #127.
- [ ] Move configuration to a `webpack.config.js` to make it work without grunt.
- [ ] Extend setup with test/release configurations (builds that include/exclude tests)
- [ ] Remove browserify
- [ ] Remove grunt #156

**Comment by bneumann** [comment]
I moved the config to a file. Checkout the pull request #159. I would have a look to change the demo (or create a dev server implementation) for faster developing experience
