### ISSUE TITLE
Render Bug 6/4 First Measure Displays With 6th Note Drawn On Next Measure

### ISSUE THREAD

**Issue by loganknecht** [opensheetmusicdisplay/opensheetmusicdisplay#1030]
# Gratitude

Hello!

Thanks for your amazing library! I'm using it at https://pianogym.com and I just can't get enough of it!

# Issue

I have a piece of sheet music I created and the first measure is showing its final note being drawn in the second measure.

See here
![Screen Shot 0003-06-06 at 5 38 38 PM](https://user-images.githubusercontent.com/1308524/120945569-63929900-c6ee-11eb-93bc-12722b056c75.png)

In order to reproduce this, here is the xml file being used.
[03-28 The Swan.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6605228/03-28.The.Swan.zip)

**Comment by sschmidTU** [comment]
This looks like an issue with Vexflow's formatter, almost like the buggy 3.0.9 formatter. Maybe the 6/4 time signature?
Good news is that there have been recent formatter fixes in Vexflow, including the length of the measure and these overlaps. Maybe updating to the new Vexflow soon will fix this.
It's weird that this happens only in the first measure. It could be that we can fix something on our end here, but i'm not sure where to start looking.

**Comment by sschmidTU** [comment]
vexflow changes e.g. here:
https://github.com/0xfe/vexflow/issues/846#issuecomment-854335979
![image](https://user-images.githubusercontent.com/5438280/120742234-29da4c00-c4bc-11eb-8b5d-f47a047ba021.png)

**Comment by loganknecht** [comment]
Understood!

Fingers crossed this fix comes to `OSMD` soon ;)

**Comment by sschmidTU** [comment]
This has been solved by now.
<img width="455" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/afe45222-6753-494d-b063-9a12c93aa06a">
