### ISSUE TITLE
 Cursor handles repeated sections

### ISSUE THREAD

**Issue by rianlu** [opensheetmusicdisplay/opensheetmusicdisplay#1032]
![image](https://user-images.githubusercontent.com/42767582/121486785-08b9b400-ca04-11eb-82fa-55e32471a968.png)

I tried `osmd.sheet.repetitions`, but the result returned is `[]`, I can't find a way to deal with repetitions.

Idea: 

I have a way to determine the position of the repeating section by parsing the xml (`<repeat>`), but I also need to know how to set the cursor to start at the specified position.

For example:
`<repeat times="2" direction="forward"/>`
`<repeat times="2" direction="backward"/>`

Similar issue: #379

**Comment by sschmidTU** [comment]
Cursor repetition support is currently limited to our audio player, which is currently [sponsor-exclusive](https://github.com/sponsors/opensheetmusicdisplay).
Repetitions should be saved in `measure.FirstRepetitionInstructions` and `measure.LastRepetitionInstructions`, have you checked those?

**Comment by rianlu** [comment]
> Cursor repetition support is currently limited to our audio player, which is currently [sponsor-exclusive](https://github.com/sponsors/opensheetmusicdisplay).
> Repetitions should be saved in `measure.FirstRepetitionInstructions` and `measure.LastRepetitionInstructions`, have you checked those?

Thanks for your reply, I found some useful information in `measure.FirstRepetitionInstructions`. I have another question, does it currently support setting the cursor to start at any position?

**Comment by sschmidTU** [comment]
Yes, in the audio player, you can click on any location, and it will set the cursor and playback there.
