### ISSUE TITLE
Irregular measure note spacing too close

### ISSUE THREAD

**Issue by hugomiddeldorp** [opensheetmusicdisplay/opensheetmusicdisplay#1033]
Hi there,
I love the work you've been doing here it's awesome! I'm having an issue with displaying Bach chorales with some irregular bars, where the notes of that irregular bar are getting squished and sometimes even overlap the bar line itself. I've attached a few examples. I've set `newSystemFromXML: true` which helps for some of them, however some still remain.
I'm not entirely sure what the problem is. Thanks in advance and keep up the great work!
![Screenshot from 2021-06-11 18-48-18](https://user-images.githubusercontent.com/20556684/121643167-a0db9a00-cae5-11eb-9a81-ab8bd94126fd.png)
![Screenshot from 2021-06-11 18-43-40](https://user-images.githubusercontent.com/20556684/121643178-a33df400-cae5-11eb-8b72-90b9d3b33745.png)

**Comment by sschmidTU** [comment]
Ah, looks like the measure widths aren't set correctly for these 1-note bars.
We may need to widen the measure per note and accidental like we fixed it for pickup bars:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/938
But maybe the recent formatter fixes in Vexflow will also solve this. We should try the most recent Vexflow state soon, for an experiment.

**Comment by sschmidTU** [comment]
Could you share a musicxml sample for testing? it doesn't have to be a whole piece, but it should include some of these 1 beat measures. Ideally also one with 2 eights notes.
For a quick workaround we could simply add an option to treat 1-beat measures as pickup measures for spacing (or just add extra space).
The relevant code is in `VexFlowMusicSheetCalculator.calculateMeasureXLayout`.

**Comment by hugomiddeldorp** [comment]
Hi Simon, thanks for replying! I couldn't upload an xml file so I just uploaded a .txt file with all the content from it - I think that should work? It has 1 beat measures both for 1 quarter and 2 eighth notes (and even has some accidentals!)
I'll look into `VexFlowMusicSheetCalculator.calculateMeasureXLayout`

Thanks!
[221.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6659232/221.txt)

**Comment by sschmidTU** [comment]
By the way, you can also increase `osmd.EngravingRules.PickupMeasureWidthMultiplier` to alleviate the issue for now.

**Comment by sschmidTU** [comment]
Looks like this was mostly fixed, and also I can't find the problematic measure in the given sample.
You can also alleviate this issue for rare problematic scores like this with e.g. `osmd.EngravingRules.PickupMeasureWidthMultiplier = 1.5`

<img width="416" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/1f08118d-010c-483c-ab00-a5297915b752">
