### ISSUE TITLE
Support: Working with p5.js environment

### ISSUE THREAD

**Issue by scoresmexico** [opensheetmusicdisplay/opensheetmusicdisplay#1037]
Hello,
For practical purposes (algorithm, image processing, animation, etc.) I'm using the p5.js library and their editor.
I'm also working with a corpus of musicXML files and this library is great for dealing with this.
I've got VexFlow to work with p5.js but I cannot figure out to use OSMD with p5.js

Thank you!!

**Comment by sschmidTU** [comment]
what's the problem? does the import not work?

**Comment by scoresmexico** [comment]
It does not import the work. 
I offering myself to build a documentation for the connection but I'm a nooby and the methods and functions are hidden for me

**Comment by sschmidTU** [comment]
I'll need more information. What's the error message when you import? And do you mean importing OSMD or calling `osmd.load()` on a musicxml file?

**Comment by scoresmexico** [comment]
Ok,
I need to know which libraries to import into p5.js editor to do this1. load an musicXML 2. Show it on Canvas3. Parse it to get information.
If you tell me which libraries I need, and orient me on how to look for the functions an methods necessary to do those things, that'll be it.
Thank you Simon
    El sábado, 19 de junio de 2021 10:11:15 GMT-5, Simon ***@***.***> escribió:  
 
 


I'll need more information. What's the error message when you import? And do you mean importing OSMD or calling osmd.load() on a musicxml file?

**Comment by sschmidTU** [comment]
OSMD does all of that. See [our Wiki, especially Getting Started](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki).

**Comment by sschmidTU** [comment]
Here's instructions on how to include external libraries (like OSMD) in p5.js:
https://creative-coding.decontextualize.com/external-libraries/

**Comment by sschmidTU** [comment]
@scoresmexico have you seen the p5.js example project that one of our team members, bneumann, set up? It should show you how to integrate OSMD into p5.js.
https://editor.p5js.org/bneumann/sketches/CAaiEPjAo

Pasting the code here in case above link becomes unavailable:
index.html:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/addons/p5.sound.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/opensheetmusicdisplay@1.0.0/build/opensheetmusicdisplay.min.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="utf-8" />

  </head>
  <body>
    <div id="osmdCanvas" style="width: 100%"/>
    <script src="sketch.js"></script>
  </body>
</html>
```

sketch.js:
```js
function setup() {
  createCanvas(400, 400);
  var url= "helloworld.xml"
  var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdCanvas");
   osmd.load(url)
     .then(value => {
          console.log(value);
          osmd.render();
        }
      )
  .catch(err => {
     console.error(err);
   })
}

function draw() {
  background(220);
}
```

style.css:
```css
html, body {
  margin: 0;
  padding: 0;
}
canvas {
  display: block;
}
```

**Comment by scoresmexico** [comment]
Thank you Simon!!

Your library is the way.
Sorry to bother your crew so much. I'm a musician researcher and its difficult for me without documentation made for dummies. If it works I can do a tutorial or something to thank you all.

Best wishes


Patricio F. Calatayud

Facultad de Música
Posgrado UNAM
