### ISSUE TITLE
Move demo source code to src

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#104]
The demo source is currently located at `demo` at project root, while the compiled demo is copied to `build/demo`. This is very confusing and should be changed.

Write a few lines on demos for our docs.

**Comment by bneumann** [comment]
I am sometimes fiddling with the wepback script so I could do this the next time I change something.
But actually I like the demo code being outside the src folder so that it distinct from the actual implementation

**Comment by sebastianhaas** [comment]
Yeah that was the idea, but I forget about it all the time, and then there is also `build/demo` and I always mix them up. But alright, if you like it that way let's just keep it and have one pending issue less. Always in favor of that.
