### ISSUE TITLE
Guitar Tabs exported from GuitarPro are rendered without the E2 string

### ISSUE THREAD

**Issue by fheyen** [opensheetmusicdisplay/opensheetmusicdisplay#1041]
![osm_missing_string](https://user-images.githubusercontent.com/8384623/124772261-2b27ea00-df3c-11eb-8d56-d0dfddf8d09d.png)

This seems to be an issue with GuitarPro, as TuxGuitar tabs work...

I attached the MusicXML (as .txt so GitHub allows it):

[A min pent 120bpm.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6777757/A.min.pent.120bpm.txt)

**Comment by sschmidTU** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/33069673/124963848-9814b000-e020-11eb-93d4-af140aceb74b.png)

There were multiple `<staff-details>` nodes in this sample, and we were only reading one. GuitarPro exports `staff-details` for all staves (also the violin clef stave), which isn't necessary, so we didn't account for this possibility.

**Comment by fheyen** [comment]
Thanks a lot! The support is even greater then the library. I sponsored you a small amount, enjoy!
