### ISSUE TITLE
Should we make PRs in Vexflow for the files under VexFlowPatch

### ISSUE THREAD

**Issue by rvilarl** [opensheetmusicdisplay/opensheetmusicdisplay#1043]
@sschmidTU I made a build of my App using the latest stand of VexFlow and it seems that the output now good enough to replace 1.2.93. I will suggest @0xfe to make a formal build 4.0.0.

Would it make sense to include the changes of VexFlowPatch in VexFlow in order to avoid the patch?

**Comment by sschmidTU** [comment]
Yeah, i'm looking forward to testing a new Vexflow release, though i'm still skeptical it'll be ok for all our samples.
We'll make pull requests to Vexflow for the VexFlowPatch changes eventually, once we are actually using a current Vexflow version. Up to now it wasn't necessary, as we couldn't use the latest Vexflow version anyways.

**Comment by sschmidTU** [comment]
But in the worst case, we'll just adapt our Vexflow patch to the new version.

**Comment by infojunkie** [comment]
Related to #915

**Comment by rvilarl** [comment]
Issues open in Vexflow

**Comment by infojunkie** [comment]
Thanks! Would you mind linking here to the issues in VF ?

**Comment by sschmidTU** [comment]
https://github.com/0xfe/vexflow/issues?q=is%3Aissue+OSMD+VexflowPatch
