### ISSUE TITLE
Rendering errors on second voice

### ISSUE THREAD

**Issue by rvilarl** [opensheetmusicdisplay/opensheetmusicdisplay#1044]
@sschmidTU making a build using the latest VexFlow and comparing the outputs to those from Smoosic I realised that the second voice is not rendered properly, the notes are misaligned. Also with 1.2.93

**Comment by rvilarl** [comment]
**1.2.93**
![Captura de pantalla de 2021-07-10 14-06-38](https://user-images.githubusercontent.com/22865285/125162446-26f00c80-e188-11eb-8729-57eeacab485f.png)
**VexFlow current**
![Captura de pantalla de 2021-07-11 06-57-29](https://user-images.githubusercontent.com/22865285/125183266-6fa1d700-e215-11eb-89b2-723340d41e8a.png)
**Smoosic**
![image](https://user-images.githubusercontent.com/5438280/125170334-4846fd80-e174-11eb-84c8-5e11b4e0358b.png)
**The second rest under the upper staff is shifted to the left**

**Comment by rvilarl** [comment]
**1.2.93**
![Captura de pantalla de 2021-07-10 14-17-00](https://user-images.githubusercontent.com/22865285/125162671-8b5f9b80-e189-11eb-9969-e8fdfec6c903.png)
**VexFlow current**
![Captura de pantalla de 2021-07-11 07-04-36](https://user-images.githubusercontent.com/22865285/125183358-4a619880-e216-11eb-87a1-681f7a6e757a.png)
**Smoosic**
![Captura de pantalla de 2021-07-11 07-07-36](https://user-images.githubusercontent.com/22865285/125183400-b6dc9780-e216-11eb-814f-cba2acd64bd6.png)
**The Chords on the second voice of the first staff are also not well aligned.**

**Comment by sschmidTU** [comment]
We recently fixed a voice alignment issue in the sponsor build, will be in the upcoming public OSMD 1.1 release.
Hopefully this should fix this issue.
Could you send me this "The Open" sample so I can test it?

**Comment by rvilarl** [comment]
I will once I come home. As you can see the last version from Vexflow does quite well the job. I had to make a small fix to get it compatible with OSMD. I wil make a PR today I'm VexFlow.

Has the repeat feature been included in 1.0?

**Comment by sschmidTU** [comment]
which repeat feature?

**Comment by sschmidTU** [comment]
also, what exactly do you want to include in the Vexflow PR? It sounds good though, so thanks for doing that :)

**Comment by rvilarl** [comment]
> which repeat feature?

the cursor attending to the repeat bars in the scores.

**Comment by rvilarl** [comment]
This is the score

[M_Book_1_Part_1_The_Open_Well_Tempered_Clavier.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6796971/M_Book_1_Part_1_The_Open_Well_Tempered_Clavier.zip)

**Comment by rvilarl** [comment]
> also, what exactly do you want to include in the Vexflow PR? It sounds good though, so thanks for doing that :)

Two items that OSMD complains about when compiled using `npm link ../vexflow`
- one unused variable
- MakeException

Making these changes is how I compiled OSMD with the current vexflow.

**Comment by sschmidTU** [comment]
> the cursor attending to the repeat bars in the scores.

No, that's an audio player feature for now.
