### ISSUE TITLE
Handle Non-integer tempos

### ISSUE THREAD

**Issue by praisethemoon** [opensheetmusicdisplay/opensheetmusicdisplay#1045]
Hello folks 👋 

I have encountered few sheets where tempo feels off on my app compared to the playback in musescore.com/org. After further investigation, I have realised that the music sheet in question have a floating point value as tempo (in sound element).

```xml
<measure number="36" width="173.34">
    <direction placement="above">
        <direction-type>
            <metronome parentheses="no">
                <beat-unit>quarter</beat-unit>
                <beat-unit-dot/>
                <per-minute>95</per-minute>
            </metronome>
        </direction-type>
        <sound tempo="142.5"/>
    </direction>
      <note>
        <rest/>
        <duration>36</duration>
        <voice>1</voice>
    </note>
</measure>
```
Original score: https://musescore.com/user/19476021/scores/4554856. 

To my best knowldge, the MusicXML specification mentions that tempo's data type is a **non-negative-decimal**. 

OSMD respects the standard: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/fbb081eeb1a12493afbf78476a0e0d0eea58905c/src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts#L152

However, in MoonPiano I have noticed the playback BPM is being set to **95** at that specific measure. Which makes me think that *if the parsing of the floating point was failed, its value is set from the metronome beats informations*. As I have found here: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/3e657618a0ee9d8628edfe0e3371be86f9b546ac/src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts#L194

Since the unit is dotted, this results in a floating point BPM, but OSMD doesn't not consider this hint before assigning the parsed BPM value into the measure's BPM.

The fix should be easy, but before I create a PR I want to ask for your opinions and what is the best approach to solve this (IMO it should be fixed in both ways).

Cheers! 🌔 

[EDIT] Oh I just realized that it was me who added this feature in the first place and caused all this mess sorry about that 🤭 😂

**Comment by sschmidTU** [comment]
So, a non-negative decimal is a float. If that's what MusicXML describes, we parse it wrongly by parsing int.
If you can make a pull request that parses and saves a float, that sounds good.
I'll just have to check if our audio player can handle float BPM. But should be an easy adaptation anyways.

**Comment by sschmidTU** [comment]
@praisethemoon Fix is merged, can this be closed now?
