### ISSUE TITLE
Getting ending number from measure for multiple endings

### ISSUE THREAD

**Issue by clairehkc** [opensheetmusicdisplay/opensheetmusicdisplay#1048]
Is there a way to get the ending number from the measure in the case of multiple endings? Alternatively, is there a way to access the raw barline XML object?

**Comment by sschmidTU** [comment]
Do you mean repetitions, e.g. 2nd volta?
Have you looked at the `Repetition` class?
Judging from `VexFlowMeasure.addVolta()`, it should be something like `measure.Repetitions[0].endingIndices[0].` Maybe also `.EndingIndex`.

**Comment by clairehkc** [comment]
yes, thanks for the tip! It looks like `RepetitionInstruction` might have what I'm looking for
