### ISSUE TITLE
Type declaration setup

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#105]
Typings is more or less obsolete, so we should move to the official @types repository.

- [x] Move away from typings (done in dae5566fd3678320d0a8c9b0af13f3a1aea1de5b)
- [x] Add all required types from @types via npm (done in dae5566fd3678320d0a8c9b0af13f3a1aea1de5b)
- [X] Make sure the missing type declarations are available, if not, publish to @types

**Comment by bneumann** [comment]
@sebastianhaas please don't cry ;) I did it! After 2 years...

**Comment by sschmidTU** [comment]
Hooray! <3
