### ISSUE TITLE
Roman Numeral Analysis / Figured Bass

### ISSUE THREAD

**Issue by jekeough** [opensheetmusicdisplay/opensheetmusicdisplay#1050]
Hi,

I am wondering if there is a fix for displaying figured bass / inversions for roman numeral analysis.  What I am seeing is that when the figured bass is stacked (e.g., I6/4), the bottom number is replaced with a different symbol.  The top number seems to be fine by itself (e.g., I6). 

Below is an image of what it looks like in Sibelius:
<img width="803" alt="Roman Numeral : Figured Bass in Sibelius" src="https://user-images.githubusercontent.com/78770780/128086825-e57afe16-8abc-4e9f-a2d0-71fb034294ad.png">

Here is how it appears on osmd:
<img width="302" alt="Roman Numeral : Figured Bass in OSMD" src="https://user-images.githubusercontent.com/78770780/128086797-ce1ec8ff-4d3d-461a-ba3a-c0921904eea3.png">

I attached an xml of this file as well.
[Roman Numeral : Figured Bass Test.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6927107/Roman.Numeral.Figured.Bass.Test.xml.zip)

Thank you!

**Comment by sschmidTU** [comment]
Looks like this is just what the MusicXML says (`I6$`), probably not exported correctly.
<img width="494" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/e7c65b9c-542b-473c-92b3-e1f5cfac8fc2">
