### ISSUE TITLE
VerticalMeasureList is undefined

### ISSUE THREAD

**Issue by kaosbeat** [opensheetmusicdisplay/opensheetmusicdisplay#1051]
Hi,

On some musicXML files generated from my app I get a 
`uncaught TypeError: t.VerticalContainerParent.ParentMeasure.VerticalMeasureList is undefined`

Upon inspection of the XML, I cannot spot any errors on my side.
I had to rename the xmls to txt as github does not support xml attach

[qtmp0.mid.xml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6945752/qtmp0.mid.xml.txt)
[qtmp1.mid.xml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6945753/qtmp1.mid.xml.txt)

the qtmp0.mid.xml is loading fine in the demo
the qtmp1.mid.xml is not

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/128532312-562e911d-40cc-4317-b70f-7db70f74bfe9.png)

Note that OSMD may not display correctly for unrealistic scores like midi transcriptions with interlocked 24-tuplets and 96-tuplets, that's not what it's made for.

Also, just as a note, Musescore says qtmp1 is corrupted:
![image](https://user-images.githubusercontent.com/33069673/128531072-88031978-5a97-4d3d-9110-7b3418eb410c.png)
