### ISSUE TITLE
RepetitionInstruction x positioning

### ISSUE THREAD

**Issue by jnpdx** [opensheetmusicdisplay/opensheetmusicdisplay#1053]
I'm doing some work on DS/DC al Coda/Fine (which I think I can submit a PR for once it's done -- the current regex does some funny matching for DC al coda) and trying to figure out where the x positioning of `RepetitionInstruction` takes place.

Can anyone give me a hint where the layout is done for these? Right now, it seems that the instructions can get pushed off of the right side of the screen pretty easily.

**Comment by sschmidTU** [comment]
It's entirely handled by Vexflow, unfortunately.
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/920
Do you have a sample for the pushed off part?

**Comment by jnpdx** [comment]
I appreciate the quick response. Upon further investigation, I *believe* that this is the result of a mismatched merge that I had with the develop branch and the branch I had with our custom changes that did not include #920. Thank you for mentioning that in the issue -- otherwise, I wouldn't have seen it!

Going to close for now. Thanks again!
