### ISSUE TITLE
Backup note near end of measure rendered incorrectly

### ISSUE THREAD

**Issue by kenboy2304** [opensheetmusicdisplay/opensheetmusicdisplay#1060]
DISPLAY ON FINALE:
![image](https://user-images.githubusercontent.com/6213200/132619048-4b34b9ce-5fe8-498a-9dbd-2c469a2f5c8d.png)

ERROR IN OSMD
![image](https://user-images.githubusercontent.com/6213200/132618777-a0029c66-ae11-4339-a839-25e32ee8c3e2.png)

**Comment by kenboy2304** [comment]
FINALE DISPLAY:
![image](https://user-images.githubusercontent.com/6213200/132619655-3fcc13eb-8a2f-40c7-9395-9577336d1d5c.png)

ERROR IN OSMD:
![image](https://user-images.githubusercontent.com/6213200/132619716-2d6a4a2c-58fe-413f-ad5b-dc25814e721c.png)

**Comment by sschmidTU** [comment]
@kenboy2304 Can you please share MusicXML samples? You can share them as .zip or .txt.
Also, in your second comment, the Finale and OSMD images are from different measures.

**Comment by kenboy2304** [comment]
Thanks, I know. I just compared Finale so it's easy for you to find errors. This error only appears at the end of each measure. This is my MusicXML file.

[MusicXML.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7147423/MusicXML.zip)

**Comment by sschmidTU** [comment]
I don't see an error (anymore).
![image](https://user-images.githubusercontent.com/33069673/150351407-edfc29ea-cff9-4950-9882-cd667e45c461.png)
If there is still an error, please say exactly which measure the error is supposed to be in.

**Comment by kenboy2304** [comment]
Thanks. I think the error is automatically fixed when you update the code

Best Regards!
--
*Phạm Tú Quốc Việt. *
- Website Developer: C# ASP.net, PHP, CMS, Ecommerce
- Marketing Online: S.E.O, Ads Online
P: 0977395375                 E: ***@***.***           W: weho.vn




Vào Th 5, 20 thg 1, 2022 vào lúc 20:51 Simon ***@***.***>
đã viết:
