### ISSUE TITLE
How to set Lyric Center?

### ISSUE THREAD

**Issue by kenboy2304** [opensheetmusicdisplay/opensheetmusicdisplay#1065]
![image](https://user-images.githubusercontent.com/6213200/135552412-505cfd89-9748-4109-ad5e-a703e9eac489.png)

**Comment by kenboy2304** [comment]
![image](https://user-images.githubusercontent.com/6213200/135053269-e9a44f22-3d72-441d-b4a2-6ca0aa87ca77.png)

**Comment by sschmidTU** [comment]
Please edit your first post to be an image instead of an image string.

**Comment by sschmidTU** [comment]
Have you tried `osmd.EngravingRules.LyricsAlignmentStandard = TextAlignmentEnum.CenterBottom; // 5`?
Also, you can try setting it individually per GraphicalLabel (`graphicalLabel.label.textAlignment`)

**Comment by kenboy2304** [comment]
I was try  it's not working.
var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("sheet-content");
                osmd.setOptions({
                    backend: "svg",
                    drawTitle: false,
                    drawComposer: false,
                    drawLyricist: false,
                    drawMeasureNumbers: false,
                    defaultFontFamily: "Barlow Condensed",
                    defaultFontStyle: 1,
                    spacingFactorSoftmax: 100,
                    spacingBetweenTextLines: 20,
                    //stretchLastSystemLine: true,
                    drawingParameters: "leadsheet"
                    ////leadsheet,thumbnail,allon
                });
                osmd
                    .load(loadstream)
                    .then(
                        function () {
                            **osmd.EngravingRules.LyricsAlignmentStandard = 5;**
                            osmd.zoom = 0.75;
                            osmd.render();
                        }
                    );

but when i change function loadDefaultValues() in file opensheetmusicdisplay.min.js, it working.
![image](https://user-images.githubusercontent.com/6213200/135555597-6f5bd88a-daa5-466f-8518-dc01cecef1bb.png)

Can you set funtion LyricAlignment is Option? It's so good.

**Comment by sschmidTU** [comment]
Try setting the EngravingRules before load().

**Comment by kenboy2304** [comment]
Its working, thank you!

**Comment by sschmidTU** [comment]
Great! :)
