### ISSUE TITLE
Move wiki contents to github page

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#107]
- [x] Set up GitHub pages website (Jekyll?)
- [x] Move wiki contents to new page
- [ ] Adapt CI postbuild setup so that the latest docs and demo files will be published alongside the pages

**Comment by sebastianhaas** [comment]
New jekyll page is live as of today:

https://opensheetmusicdisplay.github.io/

**Comment by sebastianhaas** [comment]
Finished porting wiki pages.
Classdoc is built and published fine, we do have a problem with the demo though, it needs to be adapted to the new jekyll page and should use a minified version of the library.

**Comment by bneumann** [comment]
Done in the latest releases. Minified version is used. 
Build process might be influenced but will be checked on next release
