### ISSUE TITLE
Tie Collision

### ISSUE THREAD

**Issue by jekeough** [opensheetmusicdisplay/opensheetmusicdisplay#1072]
Hi,

I noticed a display issue where ties will collide with notes around them based on direction.  It seems that in most cases, if the tie direction is based on voices it would help(e.g. voice 2 curve downwards, voice 1 curve upwards).  

Here is an example how it looks in Sibelius:
<img width="945" alt="Screen Shot 2021-10-19 at 6 09 24 PM" src="https://user-images.githubusercontent.com/78770780/138007304-0c05887c-fdfd-4a77-bdd5-e02e7122d6b8.png">
Here is how it displays with OSMD:
<img width="517" alt="Screen Shot 2021-10-19 at 6 09 29 PM" src="https://user-images.githubusercontent.com/78770780/138007323-22f861b9-6fd3-43eb-a5c0-75a8af216455.png">

Thanks for looking,

Jack

**Comment by sschmidTU** [comment]
Can you share the musicxml sample? It also depends how the tie direction is exported to MusicXML.

**Comment by sschmidTU** [comment]
Unfortunately, Sibelius didn't export the tie directions into the xml, so there's not much we can do. We'd need to do collision checking, which could be very expensive (slow) for curves/ties. Also, the ties are still recognizable.
