### ISSUE TITLE
MusicXML file hangs renderer

### ISSUE THREAD

**Issue by infojunkie** [opensheetmusicdisplay/opensheetmusicdisplay#1073]
When I load [this valid MusicXML file](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7385613/worldswingmatrix.zip) to the OSMD demo, it seems to hang during rendering. The JS log didn't reveal much to me.

For comparison, the same file renders reasonably well in Musescore and [less so in Verovio](https://ethereum.karimratib.me:8082/).

**Comment by sschmidTU** [comment]
@infojunkie the infinite loop itself is now fixed, though not what caused it, and i'm not sure what's happening there exactly. Somehow, the vexflow ticks are calculated incorrectly, so the ticks (spacing) denominator is 0.
If anyone could look into it further, that would be great.

**Comment by infojunkie** [comment]
Thanks so much!! Yes, this is an especially challenging rhythmic piece. I hope to be diving deeper into microhythms, so I need to understand this part.

**Comment by sschmidTU** [comment]
You'll see what's wrong in my commit:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/a09f7028f564092b1cfedd9e216345302a817fa4
Apparently, if the denominator is 0 (which also doesn't make sense), vexflow loops infinitely in addTickable().
The ticks seem to be calculated in Vexflow's `note.js`, line 93:
`const initStruct = Flow.parseNoteStruct(noteStruct);`

You can see the source in node_modules/vexflow, and even edit them there, and they will be hot reloaded in the npm start demo.

**Comment by sschmidTU** [comment]
It's also weird that at some point the ticks are 1/2048 (numerator 1, denominator 2048) for an 8th note, you can see this in `tables.js` line 568:
`const ticks = Flow.durationToTicks.durations[duration];`
I initially thought the `<divisions>` and `<duration>` in the musicxml may be messed up, but they look fine to me.

**Comment by sschmidTU** [comment]
You can also debug into Vexflow via OSMD, though the breakpoints aren't easy to set. Your best bet is setting the breakpoint where OSMD calls Vexflow, then doing a "step into" debug step.
E.g. in `VexflowConverter.ts:1153`:
`(gve as VexFlowVoiceEntry).vfStaveNote = VexFlowConverter.StaveNote(gve);`
this may be where the ticks are set from the point of OSMD, if i remember my debug session correctly.

**Comment by sschmidTU** [comment]
Also to setup OSMD Debugging with VSCode, see here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Debugging-(VSCode)

**Comment by infojunkie** [comment]
I verified that the fix applied here prevents the hang, but does not render the score correctly. Attaching bothMuseScore rendering and OSMD 1.3.0 rendering. 

![musescore](https://user-images.githubusercontent.com/92977/141664336-4f61bc0b-dfa6-436b-b5cf-04faa0e24e72.png)
![osmd](https://user-images.githubusercontent.com/92977/141664338-f000711a-14bf-4447-856f-a4be0bae53b5.png)

**Comment by sschmidTU** [comment]
This is now fixed.

Another sample has appeared, for which the ticks denominator was set to 0 by vexflow (which doesn't make sense, as the result is infinite):
[test_note-ticks-0.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11847373/test_note-ticks-0.zip)

This sample still logs vexflow errors and doesn't render the group of 16ths correctly in OSMD 1.7.6.
<img width="190" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/9a1e9169-d6e8-4556-ac19-dc0379d900ce">
denominator is 0 for the last note of the 16ths, an F, which doesn't even show the notehead anymore here.

Fixed:
<img width="224" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/0f7a76f7-0580-4d4f-a7ab-b918512a8682">

No visual regressions.

The strange thing is that if I open this score in the same version of Musescore apparently used to create it (3.6.2) and re-export it to MusicXML, it loads fine.
[test_note-ticks-0_re-exported.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11847389/test_note-ticks-0_re-exported.zip)

(we should look at the diff of these 2 xmls)

[the original sample in this issue](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7385613/worldswingmatrix.zip) also seems to render correctly now.

<img width="827" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/b51000b4-09cc-42ff-b940-ad7e8f61a3fb">
