### ISSUE TITLE
Wrong accidental shown for implicit accidental

### ISSUE THREAD

**Issue by infojunkie** [opensheetmusicdisplay/opensheetmusicdisplay#1075]
As per [a previous ticket](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1074#issuecomment-948776999), the renderer may infer the wrong accidental when none is explicitly defined in the MusicXML file. This typically happens in situations where the same accidented note appears multiple times in a single measure: subsequent notes will NOT have the accidental explicitly added to the file. 

[In this example](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7391626/hamama-beida-rast.zip), the "A slash-flat" note appears twice in measure 1, but the second one is wrongly rendered as "A quarter-flat" because those 2 accidentals share the same `alter` value, thereby confusing the renderer.

**Comment by sschmidTU** [comment]
We'd also have to check which accidentals Vexflow supports, e.g. here:
https://www.vexflow.com/tests/
![image](https://user-images.githubusercontent.com/33069673/139488394-c9aa9019-6c5a-401d-aee9-3b70b7c71564.png)
It could be that not all supported accidentals are in these tests though.
