### ISSUE TITLE
"Hello World" sample from the MusicXML spec fails with "Bad Key signature"

### ISSUE THREAD

**Issue by rpbouman** [opensheetmusicdisplay/opensheetmusicdisplay#108]
The hello world example from here: 

http://www.musicxml.com/tutorial/hello-world/

fails in the demo with 

Error rendering sheet: [RuntimeError] BadKeySignature:Bad key signature spec: 'undefined'

If the tag &lt;mode&gt;major&lt;/mode&gt; is added after &lt;/fifths&gt; then the example will render. However, &lt;mode&gt; is an optional element according to the MusicXML 3.0 schema, so it should render without it.

**Comment by sebastianhaas** [comment]
Hi Roland

Thanks for bringing this to my attention, I will take a look and keep you posted.

**Comment by sebastianhaas** [comment]
I provided a fix in  	2210482. Will have to write a test case before I can merge this in though. Thanks again for pointing this out.

**Comment by rpbouman** [comment]
Thanks for the quick action and the update, I appreciate it a lot! 

Currently exploring the OSMD library - very cool stuff! I like it a lot :) Of all the abstractions I've seen on top of vexflow, this seems the best bet for a pet project I have been considering for quite a while. Thanks to OSMD I feel I am now finally in a position to start working on that. So, Thanks!

**Comment by sebastianhaas** [comment]
You're very welcome, please keep me updated with any issues occurring during your project work! We have many features in the backlog that need to be ported to OSMD, so if there's anything missing you require to achieve your goals, just let me know and I will see what we can do.

I'll leave this issue open until it's merged.

**Comment by sebastianhaas** [comment]
Closed in #113
