### ISSUE TITLE
Swing

### ISSUE THREAD

**Issue by urbansmash** [opensheetmusicdisplay/opensheetmusicdisplay#1095]
Congratulations with Open Sheet Music Display ✨🎹✨ I love this development and the potential it has.  I’m also a subscriber of Practice Bird via iPadOS which is my way of enjoying great music practice and supporting the work of PhonicScore. 

Question: Is there a swing functionality available or in development?  This is essential for practicing jazz and many other contempoary styles.  

I arrange music for steelpan (steel drums) and MusicXML and MIDI playback sound great on MuseScore with my custom SoundFont of my own personally sampled acoustic instrument.  However, one crucial aspect of arranging and practicing jazz, blues, reggae, calypso and more… is that it must have swing. 

Es bedeutet nichts, wenn es nicht jeden Schwung hat. Grundgestalt! 

“It don’t mean a thing, if it ain’t got that swing!” ~ Duke Ellington 

This seems to be a fairly standard feature of sheet music audio players today, so hopefully an easy open-source solution could be plugged-in or coded for OSMD and PracticeBird.  

Giving thanks for your work on this.  You have my continued support. 

Regards, 
Tony 

UrbanSmash 
Play it on Pan 

https://musescore.com/urbansmash

**Comment by sschmidTU** [comment]
Hey, first of all thank you for your kind remarks!
We hear you, but public OSMD currently doesn't have an audio player, so this seems to be not the right location for this issue. Did you mean to post it in the sponsor repository (osmd-extended, with the early access audio player)?
If you use a custom audio player with base OSMD, it looks like you will also have to implement Swing timings.

**Comment by urbansmash** [comment]
Hi @sschmidTU 

Thanks for your quick reply.  I'm a subscriber of PracticeBird. 

I would love a swing feature to be built into the app as it is in MuseScore.  

When I open my MuseScore arrangements in PracticeBird, they lose their swing settings.  

That means, until this feature is developed in PracticeBird, I'd have to re-write all my swing sheet music …or maybe I'll just have to wait for future development. 

Many thanks, 
Tony @urbansmash 

PS. I've just sent an email to support @ phonicscore . com

**Comment by sschmidTU** [comment]
Hey Tony, we'll respond via mail. For OSMD, this is not the right location for the issue, so i'll be closing this one. But we'd love to support Swing in our audio players! Let's see where we can fit it in in our roadmap.
