### ISSUE TITLE
Missing Tie

### ISSUE THREAD

**Issue by jekeough** [opensheetmusicdisplay/opensheetmusicdisplay#1097]
Hi,

I am noticing an issue where tie's won't display.  

Here is an example in osmd:
<img width="425" alt="Missing Tie OSMD" src="https://user-images.githubusercontent.com/78770780/142328624-896d83bf-d3a9-4c8b-9a10-2a0d9e0de6d5.png">

Here it is in Sibelius:
<img width="1011" alt="Missing Tie Sibelius" src="https://user-images.githubusercontent.com/78770780/142328516-dcd8b070-2a30-412d-bacf-b181b5a12af6.png">

Here is the xml file:
[Missing Tie Bug.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7558975/Missing.Tie.Bug.xml.zip)

Thank you

**Comment by rvilarl** [comment]
Musescore finds no problem:

![image](https://user-images.githubusercontent.com/22865285/148252073-72b38025-f81d-4633-a030-ea3976c1b803.png)

Results with VexFlow 4.0:
![The Groove_M 7 Missing Tie Bug xml_1](https://user-images.githubusercontent.com/22865285/148252173-8dcf9e37-ebe7-43fc-b597-04a187a8dcf1.png)

**Comment by rvilarl** [comment]
@sschmidTU how are the Notes and NoteHeads model in OSMD? How do you tell the Tie that it affects three heads in a note?

**Comment by sschmidTU** [comment]
@rvilarl Notes and Noteheads are irrelevant here, you just need to create the correct Ties with a startNote and endNote. I'm guessing the one tie here gets ignored because it also ended on the same note that it started again.

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/149566493-e299eb57-7104-40fe-ba0a-49cad4e35d0e.png)
