### ISSUE TITLE
Notes not Staggering

### ISSUE THREAD

**Issue by jekeough** [opensheetmusicdisplay/opensheetmusicdisplay#1098]
Hi,

I am noticing that occasionally notes don't stagger correctly, and cause overlap. 

Here is an example in osmd:
<img width="505" alt="Notes not staggering OSMD" src="https://user-images.githubusercontent.com/78770780/142331463-39fdabfc-79d9-4f32-929e-22ddaece6f41.png">
Here is an example in Sibelius:
<img width="1003" alt="Notes not staggering Sibelius" src="https://user-images.githubusercontent.com/78770780/142331538-d99464a6-9906-4de3-8b46-fe5f642273a9.png">
Here is the xml file:
[Notes not Staggering.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7558995/Notes.not.Staggering.xml.zip)

Thanks for looking

**Comment by rvilarl** [comment]
The file seems to be buggy, musescore complains:

_"Measure 1, staff 1, voice 2 too long. Expected: 4/4; Found: 7/4"_

This is the result using Vexflow 4.0, (@sschmidTU it avoids the overlap of the first two notes):

![Escape_M 15 Treble Clef G and A Notes not Offsetting Bug xml_1](https://user-images.githubusercontent.com/22865285/148250282-d1f9cac6-89cf-4882-b457-8fd8a1ad797f.png)

**Comment by eddycurrently** [comment]
I have had the same issue only worse because the notes are the same note but different type. I believe this is a valid file that will cause the issue.
https://drive.google.com/file/d/145HRs3uYI-igc0fDSIZOvbjCzk6ffmHh/view?usp=sharing

**Comment by sschmidTU** [comment]
Fixed in #1118.

![image](https://user-images.githubusercontent.com/33069673/148547033-437fa270-8aea-42dc-aaa9-0decd58061a5.png)
![image](https://user-images.githubusercontent.com/33069673/148547119-03765b71-bf81-4cfd-980b-9efb03313f76.png)

**Comment by sschmidTU** [comment]
CI build fixed in 471e893b07dece69d902d61180a54432fb82b793, the appveyor setup didn't know the `||=` operator.
