### ISSUE TITLE
Element <clef> does not respect <line> child element?

### ISSUE THREAD

**Issue by rpbouman** [opensheetmusicdisplay/opensheetmusicdisplay#110]
I have a clef using a non-standard line. This is the relevant MusicXML fragment:

&lt;clef&gt;
&lt;sign&gt;C&lt;/sign&gt;
&lt;line&gt;4&lt;/line&gt;
&lt;/clef&gt;

Problem is: the rendition does not respect the <line> setting. It always uses the default line.

**Comment by sebastianhaas** [comment]
Hey @rpbouman, I've just pushed a fix for your issue to #119. Pending since I didn't have time to write tests, but if you want, you could check out that branch and take a look if that is what you wanted to see :)
