### ISSUE TITLE
param singleHorizontalStaffline not working correctly

### ISSUE THREAD

**Issue by mauxion** [opensheetmusicdisplay/opensheetmusicdisplay#1101]
Steps to reproduce: 

1. download and run extended project
2. open in browser http://localhost:8000/?singleHorizontalStaffline=1
Expected: notes displays in 1 line with scroll
Actual: notes visible partually

![image](https://user-images.githubusercontent.com/3764909/142641823-0e35b948-9675-43d1-aecf-3576b4ba4edc.png)

And here is how it looks like in my project:
![image](https://user-images.githubusercontent.com/3764909/142642020-c8e08d45-babe-4a5d-8117-16a4a90e5e67.png)

Here how was the same page looks like with rawJs non-sponsors version:

![image](https://user-images.githubusercontent.com/3764909/142642322-d67ac0b8-fd9e-498e-b805-48ef0f141b7f.png)

**Comment by sschmidTU** [comment]
Fixed in extended repo, see issue there.
extended-only issues should be opened in the extended repo :)

**Comment by mauxion** [comment]
thank you!
