### ISSUE TITLE
How to change color chords?

### ISSUE THREAD

**Issue by kenboy2304** [opensheetmusicdisplay/opensheetmusicdisplay#1106]
I used defaultColorLabel option and both Chord and Lyric got changed. I just want to change the chord color.

**Comment by kenboy2304** [comment]
Thanks for the support, I will try with your suggestion and hope for the next release soon.

**Comment by sschmidTU** [comment]
Done, new EngravingRule `DefaultColorChordSymbol` added.
`osmd.rules.DefaultColorChordSymbol = "#7788FF"`
![image](https://user-images.githubusercontent.com/33069673/144424445-614baea0-64ae-4c08-a462-a180b991eb49.png)
Will be in the next release after OSMD 1.3.1.

**Comment by kenboy2304** [comment]
Great, Thank you!
