### ISSUE TITLE
Dynamic highlighting and coloring or notes?

### ISSUE THREAD

**Issue by chrisspen** [opensheetmusicdisplay/opensheetmusicdisplay#1108]
Is there a feature to dynamically set colors of specific notes, especially while the audio player is running?

I'm trying to use OSMD in an application that detects notes over a microphone, in sync with the playback, highlighting the color if the note is detected. But I don't see this feature in the API anywhere.

**Comment by sschmidTU** [comment]
Yes.
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo
Try the SVG version (`getSVGGElement()`) to not have to re-render.

**Comment by DavidQinqianWu** [comment]
@sschmidTU  hi thanks for the demo which helps me to render the note color dynamically. I have another question that how can I color note beam or find the beam by note in osmd instance (when the last note of the beam is colored and the beam element should be colored as well. ) mush appriciation

**Comment by sschmidTU** [comment]
Unfortunately, Vexflow doesn't assign an id or class to the stem or beam in the SVG, and there doesn't seem to be a way to do that either, with the API Vexflow is using.
What I would do is try to find the index of the stavenote element in the SVG, then find the next elements after it.
Within a measure, the order seems to be always notes (vf-stavenotes) first, then stems, then beams.

You can set the stemcolor of a VoiceEntry in OSMD, but you will need to call `render()` again to change it. If the stems of a beam have the same color, the beam will get that color too (if `osmd.EngravingRules.ColorBeams` is true, which it is by default).

**Comment by sschmidTU** [comment]
@chrisspen Actually I managed to patch it into vexflow.
Stems will now have the id of the note + "-stem".
Beams will have the id of the first note in the beam + "-beam".
![image](https://user-images.githubusercontent.com/33069673/149351126-49499eb7-6795-4f76-9a70-027409b82b76.png)

We'll have to patch/merge this into vexflow 4 as well once we transition.

**Comment by sschmidTU** [comment]
Note that getting a note's flag's SVG had already been possible by checking the subelements of the note SVG:
![image](https://user-images.githubusercontent.com/33069673/149496062-ac140794-d240-4c3d-9228-57a2f37981ff.png)
(check for the class "vf-flag")
