### ISSUE TITLE
Getting div size after render or getting render size

### ISSUE THREAD

**Issue by scoresmexico** [opensheetmusicdisplay/opensheetmusicdisplay#1109]
When I ask for the height of the div element in which the canvas is rendered it emits a weird number for height.
Am I doing something wrong?

```
function openSheet() {
  let osmdCnv,x,y;
  osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdCanvas");
  osmd.load(scare).then((value) => {
    //console.log(value);
    osmd.setOptions({
      drawTitle: false,
      drawCredits: false,
      drawComposer: false,
      drawMeasureNumbers: false,
      autoBeam: false,
      autoResize: false,
      drawFromMeasureNumber: ith,
      drawUpToMeasureNumber: ith,
      drawPartNames: false,
      //pageFormat: 'Endless',
      //backend: "Canvas",
    });
    osmd.zoom = 0.75;
    //osmd.getCanvasSize();
    osmd.render();
    x = document.getElementById("osmdCanvas").offsetWidth;
    y = document.getElementById("osmdCanvas").offsetHeight;
    print(x,y)
    //getBoundingClientRect())
    convert(x,y);  //THIS FUNCTION GOES THROUGH EVERY MEASURE OF PART
  });
}
```
The results may change but I always get a height that will double in the next iteration.

```
300 140
300 280
300 419
300 280
```

How can I get the canvas size of the render?

**Comment by sschmidTU** [comment]
I get the correct sizes with both offsetHeight and clientHeight, not sure what's happening on your end.
Maybe try clientHeight?
`document.getElementById("osmdCanvasPage1").clientHeight`
![image](https://user-images.githubusercontent.com/33069673/145716390-a790f561-6ec2-4c04-a26e-894dcc1c2906.png)
try it in the demo:
https://opensheetmusicdisplay.github.io/demo/
![image](https://user-images.githubusercontent.com/33069673/145716404-91d5b35a-84eb-46ca-a8cd-980009b0c221.png)

**Comment by scoresmexico** [comment]
Oh, so you are measuring osmdCanvasPage1 and not osmdCanvas
It changes the name of the div element when rendering?

Thank you!

**Comment by sschmidTU** [comment]
It worked for both osmdCanvas and osmdCanvasPage1 for me, but if for you it works only for one, i'd use that one ;)
