### ISSUE TITLE
Error when turning first instruement invisible 

### ISSUE THREAD

**Issue by TormodKv** [opensheetmusicdisplay/opensheetmusicdisplay#1114]
If i make the first instrument invisible like so:
`osmdInstance.Sheet.Instruments[1].Visible = false;`
I always get this render error:
`TypeError: Cannot read property 'SkyLine' of undefined` when calling the `osmdInstance.render();` method.

Calling `osmdInstance.updateGraphic();` before rendering doesn't make a difference either.
I am able to turn every instrument invisible except for the first.

I'm testing on this sheet:
https://raw.githubusercontent.com/opensheetmusicdisplay/opensheetmusicdisplay/develop/test/data/JohannSebastianBach_Air.xml

**Comment by sschmidTU** [comment]
It works for me on the Bach Air.
![image](https://user-images.githubusercontent.com/33069673/147170263-821f339a-1491-4248-80bf-c46cda1af5a8.png)
Try here:
https://opensheetmusicdisplay.github.io/demo/

Which settings did you change on your end? Maybe one of them in combination with this caused this error.

**Comment by TormodKv** [comment]
My bad, i meant `Instruments[0]`.
This might be an edge case, but it has something to to with the `updateGraphic()` method.
![image](https://user-images.githubusercontent.com/61188430/147258114-190556e3-dd9a-4bc9-a695-a4aeef1622d0.png)

**Comment by sschmidTU** [comment]
It also works with `Instruments[0]` for me.
![image](https://user-images.githubusercontent.com/33069673/147258548-e90ea392-4e75-4658-8215-c32117ccd541.png)

Why are you calling updateGraphic()? You don't have to call that yourself.

**Comment by sschmidTU** [comment]
updateGraphic is only called in osmd.load().

**Comment by sschmidTU** [comment]
In any case, there was a potential null reference issue here which I fixed, so it even works with updateGraphic() in between now.
