### ISSUE TITLE
Transpose single instrument

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#1115]
Let's assume we only want to transpose the clarinet in the Mozart Clarinet Quintet, here's the original:
![image](https://user-images.githubusercontent.com/33069673/147395293-c6401977-f8dd-4c9d-b329-97fe0f2eecd3.png)

transpose the clarinet (Instruments[0]) down 3 halftones, to written A major:
![image](https://user-images.githubusercontent.com/33069673/147395450-bdb0f359-aac8-4423-83e7-612944b96479.png)

```js
osmd.sheet.Instruments[0].Transpose = -3;
osmd.updateGraphic(); // this is necessary when using transposition
osmd.render()
```

**Comment by lucbonnin** [comment]
great for sax players !

**Comment by sschmidTU** [comment]
Yes, could be useful for a lot of transposing instruments, like saxophone, clarinet, french horn, etc. - e.g. when playing on a different instrument than notated.
