### ISSUE TITLE
Color whole score, dark mode (defaultColorMusic)

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#1125]
Partial fix for #507.

```js
osmd.setOptions({defaultColorMusic: "#000000"});
osmd.render();
```
![image](https://user-images.githubusercontent.com/33069673/149657307-edff2261-4daa-4f32-a2f9-6262b6b06366.png)
This can even be reset by simply setting the option and calling `render()` again.

This sets a dark mode:
```js
osmd.setOptions({defaultColorMusic: "#FFFFFF"});
osmd.EngravingRules.PageBackgroundColor = "#000000";
osmd.render();
```
![image](https://user-images.githubusercontent.com/33069673/149658477-8ea0dc93-c3b7-4de2-9064-d4812c7442bc.png)

Note that adding a background color will make the cursor more transparent. We need to shift it to a higher layer and add transparency, otherwise the cursor would be invisible (overwritten by the background color / notes).
When there is no background color (anymore), the cursor will be set to negative layers (again).

Also note that you can add transparency to the color values:
```js
"#FFFFFF80" // half transparent
```

**Comment by Matthew1172** [comment]
My stems are still not being colored with dark mode option set. Running OSMD 1.4.5-release.

**Comment by sschmidTU** [comment]
What do you mean? You mean they aren't white? Or you want dark mode, but some stems colored differently (not white)?

**Comment by Matthew1172** [comment]
Hi, thanks for getting back to me. I upgraded OSMD from 1.4.5 to 1.5.1, and set the darkMode option in the constructor.
```
let osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdCanvas", {
    backend: "canvas",
    drawingParameters: "compacttight",
    drawMeasureNumbers: false,
    drawFromMeasureNumber: 0,
    drawUpToMeasureNumber: Number.MAX_SAFE_INTEGER,
    darkMode: true
});
```
the render of the music has white notes, white sharp and flat decorations, and white stems of the notes. The bar-lines, and eighth note connections are black.[ You can check it out on my website](http://geoteci.engr.ccny.cuny.edu/~pec21/), just click the generate button, and you'll see what I mean.

Thanks,
Matthew Pecko

**Comment by sschmidTU** [comment]
Oh, dark mode doesn't work with canvas. You shouldn't use canvas anyways, it's deprecated. (at least in Vexflow)
