### ISSUE TITLE
Get midi array from .mxl file rendered onscreen

### ISSUE THREAD

**Issue by taerilan** [opensheetmusicdisplay/opensheetmusicdisplay#1130]
Hi there, really great library you've made there,

Wanted to ask if it's possible to get midiNote numbers, or noteLabels, for example: ['23', '45', '66'] or ['A4', 'B#4', 'C3'] of notes rendered on MusicStaff?

Was looking through code but wasn't able to figure that out

Thank you

**Comment by sschmidTU** [comment]
You should be able to create this array by going through all the notes and check their pitch, e.g. `osmd.cursor.NotesUnderCursor()[0].Pitch.ToString()`
![image](https://user-images.githubusercontent.com/33069673/150348818-266d975e-43e0-4143-b89b-905465804d71.png)

If you want to get e.g. 'Bb4` more concisely, try this:
```js
const pitchString = Pitch.getNoteEnumString(note.Pitch.FundamentalNote) + Pitch.accidentalVexflow(note.Pitch.Accidental);
```
(adapted from `Pitch.ToString()`)
