### ISSUE TITLE
cursor move.next() does not take repeat in consideration

### ISSUE THREAD

**Issue by litong01** [opensheetmusicdisplay/opensheetmusicdisplay#1133]
when a piece of music contains repeat, osmd.cursor.next() wont care the repeat notion, it will move right to the next measure the right behavior is to move to the cursor to the place where repeat should start.

**Comment by sschmidTU** [comment]
Cursor handling of repeats is a feature of the audio-player, which is sponsor-exclusive currently.
https://github.com/sponsors/opensheetmusicdisplay

**Comment by litong01** [comment]
I understand that you want to make money, but without such a basic function renders the open source pretty useless and most importantly doing things like sponsors (closed circles) basically loses the spirit of the open source. You've taken the project to a wrong direction.

**Comment by sschmidTU** [comment]
You can implement the feature yourself if you want. OSMD is a sheet music **display**, not an audio player, so cursor handling of repetitions is not really core to its purpose.
Also, you are free to work on your own open source project without earning any money from it, if you are in the financial position to do that.

**Comment by litong01** [comment]
@sschmidTU Simon, any idea where to start looking to add the feature to make it part of project or even a newly forked? does not seem to be so difficult given that all the information should be already available. I feel with this feature, the project can be really useful. Again, I understand money is always an issue, I am an open source developer most of my life.

**Comment by sschmidTU** [comment]
@litong01 Handling of repetitions requires thousands of lines of code. Good luck!
