### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JanVeb** [opensheetmusicdisplay/opensheetmusicdisplay#1136]
Hello there, we are developing an app for learning to play piano, learn to read sheet music, train the ear and so on, and app development is nearing publishing ready stage so I wanted to check with you about the licence we need to be able to use OSMD in our app.

While we aren't directly using this library, librarie that we use is using it. We use https://github.com/patikapusula/osmd-player-react, since there is no licence inside, I'm not sure if we are able to use it, I've noticed you are providing OSMD player to donors who pledge around 14€ per month to your project or more.

Since we aren't generating any money with our project at the moment and are not sure if our app will be able to generate some interest, and as well, we aren't employed at the moment, wanted to ask if you could recommend us how we should proceed.

If we needed to replace https://github.com/patikapusula/osmd-player-react library with OSMD official player, would there be lot of work to do so? Or would it be straight forward, since we noticed that that library might be directly related to your project.

Also wanted to ask, sound font they use in this library to play music is rather inconsistent, loudness level of notes recordings is varying from note to note, so we would like to replace sound font and wanted to ask is this possible.

Hope to get some constructive replay so we could continue planning with further app development/release.

Already few years back I started to develop a piano learning app in Flutter, though as I was junior developer back then and Flutter is missing good music sheet libraries, I stopped development and picked it up again, this time in JavaScript Capacitor framework, as I've found your project and realised with it, it would be far easier for us to finish our project.

https://github.com/JanVeb/pianotrainer_app

Link to my original Flutter project, so you can get idea about what we are making.

Thank you for making this project, really like it so much

**Comment by sschmidTU** [comment]
Our project has the BSD-3 license, you can find it on our main github page.
That audio player is technically violating the license by not showing OSMD's license.
It's also using Jimutt's osmd-audio-player, which is outdated, so the audio issues might come from there. I think we use a different sound font now as well.
I'm not sure how exactly that audio player is built, but it shouldn't be too hard to replace it with OSMD's own sponsor audio player.

**Comment by JanVeb** [comment]
Thank you for your replay, yeah I've come to realize that patikapusula library we are using is based on Jimutt library, which has license in it self. And we used Jimutt library to work with patikapusula's library. We would like to connect directly with you however, thats why I'm writing here as well, our product enables people like me, without any music training to be able to start playing music and read music sheets as well, with little effort, train the ear and much more, I mean, one still needs to sit in front of an instrument, but rather than wasting their time on trying to figure on what is going on, we provide the user the seamless emersion into it, therefore, we are interested to know how we can publish our app, in order that everything is done legally and that we can continue using OSMD in our project

**Comment by sschmidTU** [comment]
Yes, that sounds like a nice vision. All you need to do from a legal standpoint is respect the licenses of the open source libraries you're using. In OSMD's case, for example, you need to include OSMD's license in your product, e.g. in a disclaimer on your website or app.
Here's OSMD's license in case you haven't found it:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/LICENSE

**Comment by JanVeb** [comment]
Thank you, I thought this license doesn't apply to your player, since it is not publicly available, though, I guess then, that we can use patikapusula's library as long as we are including OSMD original license in our project?

But we would also like to get access to your OSMD player, in that case we simply, for the start need to pledge 14 euro per mont to your project?

**Comment by JanVeb** [comment]
Thank you for the info, I've become OSMD sponsor, looking forward to work with OSMD player and get connected with your community
