### ISSUE TITLE
OSMD size

### ISSUE THREAD

**Issue by JanVeb** [opensheetmusicdisplay/opensheetmusicdisplay#1137]
Found here in issues that I can control music sheet size by zoom and did it like this in css

.score {
    Zoom: 100vh; /* set size of music sheets */
}

And it worked great until today when I wanted to add it to a settings so user is able to change it, but it doesn't work anymore, first my player controller would get enlarged instead, goes because I have them inline in score return

 return (
      <div className="page">
        <div className="score"> 
        {loaded && <PlayerController player={player} updateId={updateId} />}
        <div ref={refContainer} /> 
        </div>
        <div ref={refContainer} /> 
      </div> 

  );

Any way, was I overwrote zoom somewhere and thats why it doesn't work or something? Wanted to ask if anyone had similar issue.

Also Im still new to css, how can I implement settings option which would control OSMD size, since in css I can't use variables or access localStorage

<ion-text>Size of Music Sheets</ion-text><IconButton className="menuButton" onClick={OSMDSizePlus}>+</IconButton><IconButton className="menuButton" onClick={OSMDSizeMinus}>-</IconButton><ion-text>{musicSheetsSize}</ion-text>

thank

**Comment by sschmidTU** [comment]
You should probably use `osmd.Zoom` instead of CSS zoom. Not sure if CSS zoom would work without problems in OSMD.

**Comment by JanVeb** [comment]
Thank, I really done have idea where should I put osmd.Zoom, when I enter it in score.js file at various places app crashes with errors like

score.js:69 Uncaught TypeError: Cannot set properties of null (setting 'Zoom')
    at Score (score.js:69:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)

**Comment by sschmidTU** [comment]
osmd is the instance of OpenSheetMusicDisplay, maybe you named it differently.
