### ISSUE TITLE
Missing ledger line on rest

### ISSUE THREAD

**Issue by infojunkie** [opensheetmusicdisplay/opensheetmusicdisplay#1142]
I am filing a few bugs referencing [this sheet](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/8054656/Take_These_Broken_Wings.zip). 

This is bug 2 on the OSMD screenshot. ![OSMD screenshot](https://user-images.githubusercontent.com/92977/153731183-c9bbb76a-0241-4f95-9b30-e50702b63547.png)

The leger line is missing on the rest. 
![Take_These_Broken_Wings-1-MuseScore](https://user-images.githubusercontent.com/92977/153731230-62fbef5d-7e17-4413-ac1b-413109e7b229.png)

**Comment by sschmidTU** [comment]
Fixed.
After:
<img width="232" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/f0cffaba-9aee-40b1-9d02-f560842071e4">

Before:
<img width="203" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/f0b42e61-0d15-4b1d-a017-1d585ea32b5f">

`test_ledger_line_rest.musicxml`

After:
<img width="590" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/b5af4622-5d43-42d7-8567-fe670a7d2eb4">

Before:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/bdc5ce8a-8a65-4b33-903e-b055921e5373)

`Take_These_Broken_Wings.musicxml`

The approach is very close to https://github.com/0xfe/vexflow/pull/1418, adding a new glyph for whole and half notes with ledger lines.

I initially went for a more complex approach drawing ledger lines using vexflow's standard ledger line system, but first of it was more complex (only drawing the last ledger line for rests), and secondly the rest positioning in Vexflow/OSMD is quite fickle under certain circumstances, making it difficult to make sure that the note is always under/above the ledger line etc.
You can find that apprach on the branch `fix/ledger-lines-rest`.

The current approach is on `fix/ledger-lines-rest-glyph-approach` / PR #1463.
