### ISSUE TITLE
Typesafe MusicXML management

### ISSUE THREAD

**Issue by jaredjj3** [opensheetmusicdisplay/opensheetmusicdisplay#1153]
Are you interested in using [@stringsync/musicxml](https://github.com/stringsync/musicxml) to parse MusicXML into a typed structure for internal OSMD use? If so, I can eventually work on a PR to integrate it into OSMD.

The library contains an OSMD-specific test suite ([files](https://github.com/stringsync/musicxml/blob/59940c1325e9a2f26e9e8bd109e322b65b01b178/src/examples/manifest.ts#L126), [test](https://github.com/stringsync/musicxml/blob/59940c1325e9a2f26e9e8bd109e322b65b01b178/src/compatibility/osmd.test.ts)) that copied (plus some minor modifications) all the files from [opensheetmusicdisplay/test/data](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/tree/develop/test/data) and asserted:

- the files are valid MusicXML v4.0 based on [musicxml.xsd](https://www.w3.org/2021/06/musicxml40/listings/musicxml.xsd/)
- `@stringsync/musicxml` can losslessly parse and reserialize the files

**Pros**

- [MusicSheetReader](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/72633da238a18c0f41c1a82e24fba26955ba16cf/src/MusicalScore/ScoreIO/MusicSheetReader.ts) can be simplified
- OSMD inherits the ability to mutate a MusicXML structure, which might be useful in future features

**Cons**

- it's another dependency (I noticed that OSMD is conservative with dependencies)
- at `@stringsync/musicxml@0.1.4`, the bundle size is ~800kB minified and ~50kB minified + gzipped, which is not trivially small
- the API is unstable
- no adoption besides myself (it's brand new)
- not a trivial integration

**Comment by sschmidTU** [comment]
This would be nice to have, but it seems like a lot of work to integrate and refactor MusicSheetReader, and there doesn't seem to be much immediate benefit in terms of features or bugfixes.
Also, a 800kB bundle size added dependency sounds way too large for the build and for what it's adding as functionality.

By the way, another problem may be that many music programs export incorrect MusicXML, so I'm not sure if we actually want to be type safe and validated regarding MusicXML. We need to support MusicXML as it's used in practice.

**Comment by jaredjj3** [comment]
Thanks for the prompt response. I'll close this issue.

>we want to keep OSMD small for website bundles

That makes sense, that's a reasonable constraint.

>By the way, another problem may be that many music programs export incorrect MusicXML

This was one of my pain points working with MusicXML exports from different software. FWIW, `@stringsync/musicxml` solves this by conforming invalid MusicXML into valid MusicXML when parsing and serializing.

**Comment by sschmidTU** [comment]
Thanks anyways for the suggestion and presentation, interesting framework!
