### ISSUE TITLE
GraphicalTies being undefined

### ISSUE THREAD

**Issue by TormodKv** [opensheetmusicdisplay/opensheetmusicdisplay#1156]
![image](https://user-images.githubusercontent.com/61188430/157071965-f7df2076-0459-451e-b896-afaab27dfe1d.png)
From the [demo](https://opensheetmusicdisplay.github.io/demo/) ^

The error only occurs with osmd 1.4.3 and newer versions.

I don't know exactly why this error happens. I think it has something to do with turning to many instruments invisible at once.

Or i may be using some weird sheet file.
[kakebordet.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/8199222/kakebordet.txt)

One solution was to edit MusicSheetCalculator.ts
replacing this for loop and the `setTieDirections()` call inside the null check above:
![image](https://user-images.githubusercontent.com/61188430/157075603-c27d951e-24e6-4de4-999e-40c21936695d.png)
![image](https://user-images.githubusercontent.com/61188430/157075696-c8a77a57-d895-4833-b6d0-1a9c80409106.png)

Also, the error only appear when calling the `updateGraphic()` method before rendering, but i need it to correctly render a transposed sheet, so i don't think i have a choice...

**Comment by TormodKv** [comment]
![image](https://user-images.githubusercontent.com/61188430/157190750-e0a58c0b-5edc-433a-b270-225f62fc8c14.png)

Found out it also happens with this score, so the file isn't the problem

**Comment by sschmidTU** [comment]
It works if you don't call `updateGraphic()`. Is there a reason you (need to) call updateGraphic()? Normally you don't need to and you're not supposed to.
However, I added a null check before line 2133 and it also works with updateGraphic() now.

**Comment by TormodKv** [comment]
Nice! Thank you!
I don't think transposing works as supposed to when rendering without calling `updateGraphic()` first

**Comment by sschmidTU** [comment]
Ah yes, it may be required when transposing after the sheet has been rendered once.

**Comment by TormodKv** [comment]
![image](https://user-images.githubusercontent.com/61188430/165306635-a294381e-6847-4e74-a077-b06d9fb4fa2a.png)
Having a similar problem with `findGraphicalStaffEntryFromTimestamp` being undefined...
My sheet music:
[kakebordet.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/8199222/kakebordet.txt)

**Comment by sschmidTU** [comment]
@TormodKv fixed.

Here's the code to replicate, for reference: (please share as text in addition to screenshot next time)
```js
for (let i = 0; i <= 6; i++) {
    if (i !== 3) {
        osmd.Sheet.Instruments[i].Visible = false;
    }
}
osmd.updateGraphic();
osmd.render();
```
