### ISSUE TITLE
Stopped working on iOS with WKWebView from 1.4.x

### ISSUE THREAD

**Issue by massimobio** [opensheetmusicdisplay/opensheetmusicdisplay#1157]
I've been successfully using OSMD in a WKWebView on iOS/macOS in my app.
I was trying to update form 1.3.1 to the latest 1.4.5 and it stopped working.
None of the 1.4.x versions work and I get this Javascript Error when trying to load OSMD:
```
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={
WKJavaScriptExceptionLineNumber=2,
WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: opensheetmusicdisplay,
WKJavaScriptExceptionColumnNumber=37,
...
```

index.html looks like this:
```HTML
<html>
	<head>
		<title></title>
        	<script src="opensheetmusicdisplay.min.js"></script>
	</head>
	<body>
		<div id="osmdContainer"></div>
	</body>
</html>
```

When index.html is loaded I send a script to setup OSMD and load a score and it crashes at:
`var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");`

I made a barebones [sample project with OSMD 1.3.1](https://github.com/massimobio/OpenSheetMusicDisplay-Swift-Example) that works correctly and a [branch with OSMD 1.4.0](https://github.com/massimobio/OpenSheetMusicDisplay-Swift-Example/tree/osmd-1.4.0) that doesn't work.

I looked at the [changelog for version 1.4.0](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/CHANGELOG.md#140-2022-01-14) but didn't see anything suspicious. I even looked through all the [changed files form 1.3.1 to 1.4.0](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/compare/1.3.1...1.4.0) but couldn't spot anything. Maybe something changed in the way the package is compiled?

Any ideas what the issue could be?

**Comment by sschmidTU** [comment]
@massimobio The change is probably due to the update from webpack 4 to 5 in OSMD 1.4, it builds slightly differently. Though it's a bit odd it doesn't work, because our [Simple Plain Javascript Usage example](https://github.com/opensheetmusicdisplay/RawJavascript-usage-example/blob/master/indexSimpler.html) still works with OSMD 1.4x.
Maybe try inserting `type="module"` in `<script>`? (though it's not necessary for our example)

Otherwise I'd search for WKWebView issues with webpack 5 builds.

**Comment by massimobio** [comment]
Looking at the Simple Play Javascript example I noticed some differences.
Adding `<meta content="text/html;charset=utf-8" http-equiv="Content-Type">` to my index.html file fixed it.

Yes, transposition wasn't available when I initially made the demo project. Will integrate it soon, thank you for your help.
