### ISSUE TITLE
Unofficial MusicXML Test Suite

### ISSUE THREAD

**Issue by rvilarl** [opensheetmusicdisplay/opensheetmusicdisplay#1169]
https://lilypond.org/doc/v2.20/input/regression/musicxml/collated-files#test-cases

@sschmidTU I believe that it would be good to include this test set, what do you think?

**Comment by sschmidTU** [comment]
I actually looked at that at some point. But for one, we cover a lot of that already with our test samples, and secondly, the links are dead. Good idea though!
