### ISSUE TITLE
type error notes[0].getIntrinsicTicks

### ISSUE THREAD

**Issue by stwktw** [opensheetmusicdisplay/opensheetmusicdisplay#117]
[Error] TypeError: undefined is not an object (evaluating 'notes[0].getIntrinsicTicks')
	Beam (osmd.js:24731)
	finalizeBeams (osmd.js:52246)
	staffMeasureCreatedCalculations (osmd.js:52305)
	staffMeasureCreatedCalculations (osmd.js:52495)
	createGraphicalMeasuresForSourceMeasure (osmd.js:48397)
	prepareGraphicalMusicSheet (osmd.js:47495:82)
	initialize (osmd.js:47457)
	GraphicalMusicSheet (osmd.js:46019)
	load (osmd.js:61178)

what is error?

I want to render attached file.(safari/mac)

Tell me. how to use. plz.
[Let_It_Go.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/904414/Let_It_Go.xml.zip)

**Comment by sebastianhaas** [comment]
Thanks for letting us know! I'll have a look asap!

**Comment by stwktw** [comment]
Hi

I try to rendering again that xml file.
I success render that file.
But waring message. 
"Warning! Beam with no notes! Trying to ignore, but this is a serious problem."
this is serious problem?

and,I would like to contribute to this project if I have a chance.

**Comment by sebastianhaas** [comment]
As I said, I'll have a look at it as soon as possible. Regarding the beams, it's either an error in the supplied XML or a problem in our parsing. Either way, I'll have a look at it.

Re contributing, you can take a look [here](http://opensheetmusicdisplay.org/develop/contributing/) for a list of issues that are marked as good for contribution.

**Comment by matt-uib** [comment]
Dear @stwktw, the problem seems to come from an unfinished parsing of beams in grace notes. I fixed this for now with an "undefined" check so that your xml file opens now normally.

**Comment by sebastianhaas** [comment]
Fixed in  07edb53
