### ISSUE TITLE
How to log transposed XML? 

### ISSUE THREAD

**Issue by ultraGentle** [opensheetmusicdisplay/opensheetmusicdisplay#1172]
Hello, thanks for this library!  

I'm able to render a transposed score, but I **can't access/log the transposed XML**.  

```
osmd.sheet.Instruments[0].Transpose = 1;
osmd.updateGraphic(); 
console.log(e.target.result);   //  logs non-transposed XML. 
                                //  how to log **transposed** XML?
```
Thanks for any suggestions!

**Comment by sschmidTU** [comment]
OSMD is not a MusicXML export library, so unfortunately OSMD doesn't have MusicXML export.

**Comment by sschmidTU** [comment]
You can display the transposed pitch of individual notes.

**Comment by ultraGentle** [comment]
Thanks, understood.  I've inspected the `sheet` object, and one thing I'm confused by is the `accidental` field -- it seems to always be `2`, regardless of whether the note is sharp/flat/natural.  How should `accidental` be interpreted.  Or is there a different property that describes whether it's a b/#/nat?

**Comment by sschmidTU** [comment]
not sure which `.accidental` field you mean, but probably `pitch.accidental`, where `2` is natural. You shouldn't get 2 for sharp or flat. 0 is sharp, 1 flat. You can also check `accidentalXml` (when not transposing) or `pitch.ToString()` for a string representation of the note.
