### ISSUE TITLE
webview performance issue

### ISSUE THREAD

**Issue by yogaliu** [opensheetmusicdisplay/opensheetmusicdisplay#1173]
Great project, our group wants to use osmd to make a music app. During the research phase, we found that a 200-bar piano score takes 8 seconds to parse and 7 seconds to draw in webview. 
1. the problem of parsing cannot be solved at present. Is there any solution? 
2. can osmd support paging rendering, which may solve the problem of long drawing time
3. can Android use the osmd library directly, or only webview 
The picture is the performance analysis under chromeL,ooking forward to your reply,thx
![image](https://user-images.githubusercontent.com/15954570/170992493-37a8e91e-19d7-48b4-b637-232c8334ffc5.png)

**Comment by sschmidTU** [comment]
What exactly do you mean with "parsing", is that osmd.load()? In my experience and in your screenshot, the by far biggest part of time is spent in render(). We already improved performance in OSMD 1.5.0 (30-60%) and earlier, so currently it's hard to reduce render time even more.

Large scores unfortunately do take a long time to render, especially on Android and weak processors. A 200 bar score is huge.

Answering your questions:
1. Not sure what you mean.
2. You can draw part of the score, i.e. select start and end measure number to draw. See here (OSMDOptions.ts):
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Getting-Started#osmd-options
3. There isn't really native Javascript on Android as far as I'm aware. You could use React Native. Or Custom Tabs. But other than that you probably need to use Webviews. I'm not sure that there is much possibility to improve Webview performance, but you could search for that.

**Comment by yogaliu** [comment]
> “解析”到底是什么意思，是 osmd.load() 吗？根据我的经验和您的屏幕截图，到目前为止，大部分时间都花在了 render() 中。我们已经在 OSMD 1.5.0 (30-60%) 及更早版本中提高了性能，因此目前很难进一步减少渲染时间。
> 
> 不幸的是，大分数确实需要很长时间才能渲染，尤其是在 Android 和弱处理器上。200 条的分数是巨大的。
> 
> 回答您的问题：
> 
> 1. 不明白你的意思。
> 2. 您可以绘制部分乐谱，即选择开始和结束小节编号进行绘制。请参见此处（OSMDOptions.ts）：
>    [https](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Getting-Started#osmd-options) ://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Getting-Started#osmd-options
>    您可以尝试首先仅加载部分乐谱，然后稍后在另一个 div 中加载其余部分.
> 3. 据我所知，Android 上并没有真正的原生 Javascript。你可以使用 React Native。或自定义标签。但除此之外，您可能还需要使用 Webviews。我不确定提高 Webview 性能的可能性很大，但你可以搜索一下。



> What exactly do you mean with "parsing", is that osmd.load()? In my experience and in your screenshot, the by far biggest part of time is spent in render(). We already improved performance in OSMD 1.5.0 (30-60%) and earlier, so currently it's hard to reduce render time even more.
> 
> Large scores unfortunately do take a long time to render, especially on Android and weak processors. A 200 bar score is huge.
> 
> Answering your questions:
> 
> 1. Not sure what you mean.
> 2. You can draw part of the score, i.e. select start and end measure number to draw. See here (OSMDOptions.ts):
>    https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Getting-Started#osmd-options
>    You could try to at first only load part of the score, then load the rest later in another div.
> 3. There isn't really native Javascript on Android as far as I'm aware. You could use React Native. Or Custom Tabs. But other than that you probably need to use Webviews. I'm not sure that there is much possibility to improve Webview performance, but you could search for that.

Thank you for your reply
1. I divided the osmd library into two parts, the first part refers to parsing xml, calculating internal coordinates, and generating javascript objects for drawing. The second part is to call the vexflow library to draw into svg/canvas.
2.Thanks a lot, I will try it, it may take time to process the screen height to determine how many parts to divide.
3.rn does not support svg and canvas, so it can only be done through webview. Does the practice bird use the native implementation? The rendering speed is quite fast.

**Comment by sschmidTU** [comment]
Practice Bird uses a native C# implementation which is similar to OSMD, but has its own rendering engine instead of vexflow. It doesn't use any javascript.

**Comment by JanVeb** [comment]
> Great project, our group wants to use osmd to make a music app. During the research phase, we found that a 200-bar piano score takes 8 seconds to parse and 7 seconds to draw in webview.
> 
> 1. the problem of parsing cannot be solved at present. Is there any solution?
> 2. can osmd support paging rendering, which may solve the problem of long drawing time
> 3. can Android use the osmd library directly, or only webview
>    The picture is the performance analysis under chromeL,ooking forward to your reply,thx
>    ![image](https://user-images.githubusercontent.com/15954570/170992493-37a8e91e-19d7-48b4-b637-232c8334ffc5.png)

Hi there, did you found a way to speed up your project, still interested into it?

I was working on it recently and found a way to speed up my android app project substantially, literary can change scores during play time and app will immediately change score and just continue playing new one, although I don't plan to enable this in my app, still it's great show case for how fast OSMD can be.

Though there are some caveats, but with further work on this I think that this could cover majority of use cases.

Though, as this is still experimental, and includes playing as well, i decided to make it available only to sponsors at the moment and hopefully if I find more people interested into this, maybe I find someone that would help me to code this into main OSMD project.

In the video you can see what kinds of speeds I'm talking about
Video was recorded on Android device, using react.is, ionic, capacitor.js frameworks, though I don't see any reason why this shouldn't work in any framework and on any device.

https://user-images.githubusercontent.com/93236084/189990651-87e9c280-afc3-4850-b778-17a63378a4ee.mp4

**Comment by showtan001** [comment]
Android WebView loading and rendering is very slow, iOS is very fast. 
Do you have any good optimization solutions for Android?

**Comment by JanVeb** [comment]
> Android WebView loading and rendering is very slow, some "xml" takes close to 60 seconds. However iOS is very fast, it only takes 6~7 seconds. Do you have any good optimization solutions for Android?

You can check my app on Android, where you can see that it's possible to greatly improve performance on Android, i can even load scores that are 250+ measures long within a second.

Though this is only possible if you have access to sponsors OSMD extended, if you do, contact me on sponsors channel in discord and I'll let you know how to do that.

Otherwise, OSMD extended will become available to everyone over time, then as well I could show you how I do this as well.

I do this by instead of calling OSMD.render(), instead i load presaved SVG of the score, and data that allows me playing and cursor move i get from OSMD extended

**Comment by showtan001** [comment]
We are using react-native's WebView to load.
Are you using WebView to load and render? 
thanks! @JanVeb

**Comment by JanVeb** [comment]
> We are using react-native's WebView to load. Are you using WebView to load and render? thanks! @JanVeb

I'm using react.is, ionic, capacitor.is

Though this isn't that important, i don't se any reason why this shouldn't work on any platform, react native included.

Though I don't call neither OSMD load or render, actually I call it once, save SVG and data I need for cursor and play and there after I just display this saved svg and facilitate with data I saved about notes, cursor etc

**Comment by showtan001** [comment]
Hey, dude, how to save svg and cursors? I can't save it with react.js.

**Comment by JanVeb** [comment]
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/670

Exporting SVG or PNG image of score is implemented function in OSMD, you can check more about it in upper link.

How ever, i don't do it this way as I didn't figure it out and I found easier way for me to do it.

In browser you simply right click on OSMD score and click inspect.

It will take you to SVG element, copy that element and paste it in New file named yourScore.svg

You could also do this with code, I presume, but for simplicity try it like this until you figure it out.

Then lead this yourScore.svg as you would any other svg.

Cursor, you have to draw your own cursor over your score.svg, as you can't use OSMD cursor without OSMD.render().

You have to save data about cursor for that specific score, data you need is cursor.top, cursor.left, cursor.height, cursor.left for each note.

Here you need OSMD extended, as when you loop cursor on normal OSMD it doesn't follow repeats, this is only enabled for now in OSMD extended.

**Comment by showtan001** [comment]
@JanVeb thanks!
