### ISSUE TITLE
Title Clips on Smaller Screens

### ISSUE THREAD

**Issue by ComposingGloves** [opensheetmusicdisplay/opensheetmusicdisplay#1179]
Ran across this issue while working on my site. Decided to see if it happened on the official demo after searching around for wrap text documentation. Turns out the demo has the same problem. 

![image](https://user-images.githubusercontent.com/86903737/174455929-f31dc64d-06b1-496d-a0df-07e17c80169a.png)

Is there something I am missing? Currently going to remove the title and add it in a separate container.

**Comment by sschmidTU** [comment]
Yes, there's not enough space in this screen width to render the title. If you do want OSMD to render it there, you can reduce the font size with `osmd.EngravingRules.SheetTitleHeight`.
This is an extremely small screen size fitting only one measure, there will be other things too that will inevitably not look good, it's impossible to render a score well on such a small portrait format screen.
(if you want to display a score on a phone, which will never really look good, it's probably a better idea to go for landscape format)

**Comment by sschmidTU** [comment]
you can also reduce osmd.Zoom of course.

**Comment by ComposingGloves** [comment]
Alright I'll try those out. I'm writing some exercises for students and I anticipate some of them trying to do it on their phone so I am trying to get it as readable as possible. 

Thanks for your help!

**Comment by sschmidTU** [comment]
You're welcome, feel free to ask again!
