### ISSUE TITLE
How to get the speed (force) of the note press

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1189]
I want to get the speed (force) of the piano when the notes are played, but in the case, there is only how to get the notes and time of playing, I don't know how to do that

**Comment by sschmidTU** [comment]
Again, don't open audio player issues here, open them in the sponsor repository.

**Comment by JanVeb** [comment]
Did you find solution?

Force with which a key is pressed is usually termed velocity, however this term is mostly used in midi terms, related term here is volume, although not exactly the same, but you can use volume as velocity
