### ISSUE TITLE
How to get note default-x?

### ISSUE THREAD

**Issue by showtan001** [opensheetmusicdisplay/opensheetmusicdisplay#1191]
Hello! I want to get the "default-x" in `<note color="#000000" default-x="85">`, is there any good way?

**Comment by sschmidTU** [comment]
No, not in OSMD currently. This information is useless for OSMD, so we don't save it. Vexflow does the layout. The default-x is where the original program which exported the sheet put the note, but that doesn't mean Vexflow puts it there.
You could get it from the MusicXML file, you would just need to create a mapping between the notes there and in OSMD.

**Comment by showtan001** [comment]
How to parse the MusicXML file to get the data, any good suggestions?

**Comment by sschmidTU** [comment]
Use either a generic XML parser, or a Musicxml parser (javascript).


> Also, how do I convert halfTone + 12 to note. eg 70 => A#4

`osmd.cursor.NotesUnderCursor()[0].Pitch.ToString()`

or:
`osmd.cursor.NotesUnderCursor()[0].Pitch.Octave`
`osmd.cursor.NotesUnderCursor()[0].Pitch.FundamentalNote`

**Comment by JanVeb** [comment]
I use ```
osmd.EngravingRules.GNote(
          note
        ).vfnote[0].note_heads[0].x.toFixed()
```
to get note x position
Though I don't use it much at the moment, but on fly over over the data, it seems that results are consistent with real note x position, at least when osmd.Zoom = 1
