### ISSUE TITLE
Map rendering

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1192]
I wonder if it is possible to render piano notation instead of staff?

**Comment by sschmidTU** [comment]
What do you mean?

**Comment by zhouxiang233** [comment]
I can't send a picture here, which shows the piano spectrum, which is numerical

**Comment by zhouxiang233** [comment]
I have sent the detailed questions to your email

**Comment by sschmidTU** [comment]
Ok. I don't know what you're talking about. If you mean numbered notation, also known as Jianpu, we don't support that, as it's only used in China, and extremely different to normal scores.
