### ISSUE TITLE
Extracting note timing for playing

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1193]
I followed the method in the document to extract the notes, but this line of code reported an error:
const bpm = getBPMAtMeasure(iterator.CurrentMeasureIndex);
The error message is getBPMAtMeasure is not function,I wonder what I should do next

**Comment by sschmidTU** [comment]
There is no getBPMAtMeasure function. If you want a measure's BPM, take sourceMeasure.TempoInBPM.

Again, please don't open audio player issues in this repository. You seem to be a subdeveloper of a sponsor. Please ask your boss to ask for access for the sponsor repository.

If you keep opening audio player issues in this repository, which is only for public OSMD, We might have to ban you.
