### ISSUE TITLE
XML Rendering problems

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1194]
When I was doing the score rendering, I noticed that a rest was rendered, but its color was set to transparent. I wonder what caused this

**Comment by sschmidTU** [comment]
Please add a sample MusicXML file and an image. It's impossible to answer without that.

**Comment by zhouxiang233** [comment]
Here is the sample file
















At 2022-07-26 17:48:27, "Simon" ***@***.***> wrote:

Please add a sample MusicXML file and an image. It's impossible to answer without that.

**Comment by sschmidTU** [comment]
You can't attach files to github issues by replying by mail. Please visit the github website, don't reply by email.

**Comment by sschmidTU** [comment]
Also, please share an image of which note you think should not be transparent

**Comment by zhouxiang233** [comment]
I'm sorry to send the problem by email, but my Github can't send pictures and files, so I can only bother you in this way.
The first image is the finished rendering,In the second picture, I changed the color of the notes in the whole score, and you can see that the first note in the first picture is transparent, and in the second picture there is a rest

**Comment by sschmidTU** [comment]
If you can't share files or pictures, I can't help you, sorry. I can only see your github post.
