### ISSUE TITLE
Rest rendered transparently

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1195]
When rendering the track, a rest is rendered, but it is rendered transparent
![屏幕截图 2022-07-26 174211](https://user-images.githubusercontent.com/86224160/181025939-a1e3071f-967f-4249-a6fd-db2fd2b869af.png)
![屏幕截图 2022-07-26 174257](https://user-images.githubusercontent.com/86224160/181025947-63912bca-1a9d-485a-933b-478dcca2e178.png)
![屏幕截图 2022-07-26 174522](https://user-images.githubusercontent.com/86224160/181025951-fcbe1a2c-eefd-462b-92ce-c8417201c1a2.png)
Below is the track file I rendered
[temp_1.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9190509/temp_1.zip)

**Comment by sschmidTU** [comment]
the rest in the xml has `<note print-object="no">` which means it should not be rendered.
Also, rgba means red green blue alpha, and alpha means opacity/transparency. so alpha 0 means transparent/invisible.

**Comment by zhouxiang233** [comment]
OK, thank you very much. I think I know. I've also revised it
