### ISSUE TITLE
How to convert "graphic.verticalGraphicalStaffEntryContainers" into "measureList"

### ISSUE THREAD

**Issue by showtan001** [opensheetmusicdisplay/opensheetmusicdisplay#1197]
How to convert "graphic.verticalGraphicalStaffEntryContainers" into "measureList", I hope it contains relevant data of "measure", for example: the first "measure"
![image](https://user-images.githubusercontent.com/32892347/181414625-aeed54c0-ed8a-46df-8317-c455f0929050.png)
![image](https://user-images.githubusercontent.com/32892347/181414875-319a57c0-33df-4e26-a394-0c1f764c7b7d.png)

**Comment by sschmidTU** [comment]
osmd.graphic.measureList
