### ISSUE TITLE
GetNearestNote  How do you know where the note is  measureList

### ISSUE THREAD

**Issue by junke365** [opensheetmusicdisplay/opensheetmusicdisplay#1198]
osmd.graphic.measureList[noteSubsectionIndex][0].staffEntries

        if(type=="touchEnd")
        {

        let cools= osmd.graphic.svgToOsmd({x:posx,y:posy});
        console.log("------------------------type  updateNoteupdateNote:" + type + "x=" + posx + "y=" + posy);
        console.log("------------------------type  notes:" + type + "x=" + cools.x + "y=" + cools.y);
        let clickpointf2d={x:cools.x,y:cools.y};
        let maxdist={x:10,y:10};

        console.log( "get nearestnote ----------------->"+ osmd.GraphicSheet.GetNearestNote(clickpointf2d,maxdist));
        let notes=osmd.GraphicSheet.GetNearestNote(clickpointf2d,maxdist);
      

        }

**Comment by sschmidTU** [comment]
Please add a description and question in the form of a full sentence.
