### ISSUE TITLE
The number of "cursors" jumps is reduced

### ISSUE THREAD

**Issue by showtan001** [opensheetmusicdisplay/opensheetmusicdisplay#1199]
The number of "cursors" jumps is reduced, as shown in the figure, there are "1" and "2", cursors[0].next only jumps once, only jumps "2", "1" does not jump, "xml" file "1" ", "2" are not in the same "AbsolutePosition.x". What is the reason?
![image](https://user-images.githubusercontent.com/32892347/181461085-eb7ec09f-1086-48c6-9ae8-428425c22a43.png)
![image](https://user-images.githubusercontent.com/32892347/181462532-6e784f42-9783-494a-9bb0-4b43738e2102.png)

**Comment by sschmidTU** [comment]
Grace notes are no cursor positions, as technically the belong to the next note.
