### ISSUE TITLE
Correct type definitions for Vex.Flow.StaveConnector.type

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#120]
`NONE` is missing.
https://github.com/0xfe/vexflow/blob/master/src/staveconnector.js#L38

**Comment by sebastianhaas** [comment]
Depends on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15741

**Comment by sschmidTU** [comment]
merged.
