### ISSUE TITLE
Can't hide instrument brackets

### ISSUE THREAD

**Issue by showtan001** [opensheetmusicdisplay/opensheetmusicdisplay#1205]
I want to hide it, but tupletsBracketed: false doesn't work

```
new OSMD(xmlRef.current as string | HTMLElement, {
    tupletsBracketed: false
});
```
![image](https://user-images.githubusercontent.com/32892347/183590047-8094be6a-05f3-47d5-9759-4561874f6893.png)

**Comment by sschmidTU** [comment]
That's not a tuplet bracket, it's an instrument bracket.
There is currently no option not to draw instrument brackets, as it's a standard part of the score. But we could add one.
