### ISSUE TITLE
possibility to loop over selected measures

### ISSUE THREAD

**Issue by maaaaaaaartin** [opensheetmusicdisplay/opensheetmusicdisplay#1209]
Hello,
Will that be possible to select some measures and loop over the selection with the audio player? It would be quite useful. Thank you for your work.
Martin

**Comment by sschmidTU** [comment]
Yes, it's possible in our audio player, though it requires some custom code to do the looping.

**Comment by maaaaaaaartin** [comment]
Thanks! I see. Would be cool to have it at the user level, directly on the web page.
