### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#121]
Right now, we have a bundle size of 777KB for the minified version of this library. That is probably too much.

Mid-term goals:
- [ ] Move to webpack ( #103 )
- [ ] Remove dependencies that are obsolete
- [ ] Investigate in minification options
- [ ] Exclude tests (are they included right now?)
- [ ] Split up library in modules that can be included as required
- [ ] Investigate in further possibilities

**Comment by bneumann** [comment]
Hi, you guys need help on that? I am also writing a MusicXML Parser and was pretty baffled seeing the stuff you already have here. But my library is around 800kB including vexflow ;) So maybe I can give you a hand?

**Comment by sebastianhaas** [comment]
Any help is more than welcome :) Don't have much expertise on these matters, the only thing I have on my agenda right now is moving to webpack and removing obsolete dependencies, if any.

Do you have any suggestions? What do you think about the bundle size?

**Comment by bneumann** [comment]
Sorry for the long pause. I was a bit distracted after becoming a father :) Anyways: I just had the chance to go over the repo, build and inspect everything and the size doesn't look so bad. It's 768kB for the minified version. And It's a lot (!) of code.

I will try and extend the gruntfile to work with webpack and see what magic it can do. I'll keep you posted

**Comment by bneumann** [comment]
Opened a pull request (#127) might want to check it out. I did not yet include hot replacement for webpack because I just checked the build system and don't have the time to let the code run.

**Comment by sebastianhaas** [comment]
Congratulations! 👶🏻 
Thank you for your contribution, I'll hopefully get the chance to take a look this weekend :)

**Comment by bneumann** [comment]
I just tested again and I got 1024453 bytes for the grunt build & uglify and 1004042 bytes for the webpack build (around 2%). Uglifying webpack brings the bundle down to 1001803 (Around 2.2%). That's not a lot but on the webpack build is faster (well at least it feels fast ;) )

**Comment by bneumann** [comment]
Check dis out: Hab das analyzer plugin direkt mit eingebaut. Damit kriegst Du beim build direkt sone schicke Grafik mit:
![image](https://user-images.githubusercontent.com/2605131/36451955-fe2c5c68-1692-11e8-928b-3b0694923430.png)
Und damit auch gleich die gute Nachricht. Unser Code macht "nur" 36% aus :)
