### ISSUE TITLE
possibility to adjust volume of each track separately

### ISSUE THREAD

**Issue by maaaaaaaartin** [opensheetmusicdisplay/opensheetmusicdisplay#1210]
Hello,
Will that be possible to adjust the volume of each track separately? That would be quite useful as well. Thanks again for your work.
Martin

**Comment by sschmidTU** [comment]
That's already possible in our audio player, .e.g. `osmd.Sheet.Instruments[1].Staves[0].Volume = 0.5` (piano left hand) or just `osmd.Sheet.Instruments[1].Volume = 0.5` (piano).

**Comment by maaaaaaaartin** [comment]
Thanks also for this! Similarly, it would be useful to have it at the user level, directly on the web page.
