### ISSUE TITLE
How to display a double cursor

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1211]
I want to display two cursors in the music score, one in the bass area and the other in the treble area. What do I need to do,

**Comment by sschmidTU** [comment]
We don't have cursors for specific parts/instruments only. You'll have to write your own (like Cursor.ts), and modify the y value in Cursor.update().

**Comment by zhouxiang233** [comment]
![image](https://user-images.githubusercontent.com/86224160/185945446-2c574f98-9a1b-4dc8-b8d6-f8b6b0b1e1dc.png)
What I want is two cursors up and down, not sure if it's possible

**Comment by sschmidTU** [comment]
@zhouxiang233 I know. As I said, it's currently not possible.
