### ISSUE TITLE
Cursor jump

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1216]
I want to jump the cursor to the specified note. What code do I need to use to achieve this function

**Comment by sschmidTU** [comment]
Call next() until you're there. It's basically instantaneous.

**Comment by zhouxiang233** [comment]
What I want to do is jump to the specified note. Is this possible? In the normal version

**Comment by sschmidTU** [comment]
Yes, as I said. call cursor.next() and check cursor.NotesUnderCursor() or whatever you want to check for your desired position.

**Comment by zhouxiang233** [comment]
I'm sorry to disturb you again, but I want to know the position of the clicked notes in all the notes. What should I do? Thank you very much

**Comment by JanVeb** [comment]
You can get position of cursor with these lines:
```
document.getElementById('cursorImg-0').style.left. //it returns distance in px from left
document.getElementById('cursorImg-0').style.top //it returns distance in px from top
```


You can loop `osmd.cursor.next()` to iterate over all cursor positions and then run ```
document.getElementById('cursorImg-0').style.left.
document.getElementById('cursorImg-0').style.top
``` and then save result in object


You can move cursor to specific note with
```
    osmd.PlaybackManager.setPlaybackStart(
      window.allNotes[10].noteObject.getAbsoluteTimestamp()
    );
```

You can get an array of all the notes from osmd with this code
```
const register_note_from_osmd = (osmd) => {
  if (osmd && osmd.cursor) {
    let iterator = osmd.cursor.Iterator;

    var allNotes = [];
    var allNotesWRest = [];

    while (!iterator.EndReached) {
      const voices = iterator.CurrentVoiceEntries;
      for (var i = 0; i < voices.length; i++) {
        const v = voices[i];
        const notes = v.Notes;
        for (var j = 0; j < notes.length; j++) {
          const note = notes[j];
          // make sure our note is not silent
          if (note != null) {
            allNotesWRest.push({
              note: note.halfTone + 12, // see issue #224
              time: iterator.currentTimeStamp.RealValue * 4,
              length: note.length.realValue,
              noteObject: note,
            });
          }
          if (note != null && note.halfTone != 0 && !note.isRest()) {
            allNotes.push({
              note: note.halfTone + 12, // see issue #224
              time: iterator.currentTimeStamp.RealValue * 4,
              length: note.length.realValue,
              noteObject: note,
            });
          }
        }
      }

      iterator.moveToNext();
    }
    window.allNotes = allNotes;
    window.allNotesWRest = allNotesWRest; // this includes also rest notes
  }
};
```

**Comment by zhouxiang233** [comment]
> 您可以使用以下行获取光标的位置：
> 
> ```
> document.getElementById('cursorImg-0').style.left. //it returns distance in px from left
> document.getElementById('cursorImg-0').style.top //it returns distance in px from top
> ```
> 
> 您可以循环遍历所有光标位置，然后运行`osmd.cursor.next()`
> 
> ```
> document.getElementById('cursorImg-0').style.left.
> document.getElementById('cursorImg-0').style.top
> ```
> 
> ，然后将结果保存在对象中
> 
> 您可以将光标移动到特定笔记
> 
> ```
>     osmd.PlaybackManager.setPlaybackStart(
>       window.allNotes[10].noteObject.getAbsoluteTimestamp()
>     );
> ```
> 
> 您可以使用此代码从osmd获取所有笔记的数组
> 
> ```
> const register_note_from_osmd = (osmd) => {
>   if (osmd && osmd.cursor) {
>     let iterator = osmd.cursor.Iterator;
> 
>     var allNotes = [];
>     var allNotesWRest = [];
> 
>     while (!iterator.EndReached) {
>       const voices = iterator.CurrentVoiceEntries;
>       for (var i = 0; i < voices.length; i++) {
>         const v = voices[i];
>         const notes = v.Notes;
>         for (var j = 0; j < notes.length; j++) {
>           const note = notes[j];
>           // make sure our note is not silent
>           if (note != null) {
>             allNotesWRest.push({
>               note: note.halfTone + 12, // see issue #224
>               time: iterator.currentTimeStamp.RealValue * 4,
>               length: note.length.realValue,
>               noteObject: note,
>             });
>           }
>           if (note != null && note.halfTone != 0 && !note.isRest()) {
>             allNotes.push({
>               note: note.halfTone + 12, // see issue #224
>               time: iterator.currentTimeStamp.RealValue * 4,
>               length: note.length.realValue,
>               noteObject: note,
>             });
>           }
>         }
>       }
> 
>       iterator.moveToNext();
>     }
>     window.allNotes = allNotes;
>     window.allNotesWRest = allNotesWRest; // this includes also rest notes
>   }
> };
> ```

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1216
When I use this function, I prompt not a function. I want to know why

**Comment by zhouxiang233** [comment]
> > 您可以使用以下行获取光标的位置：
> > ```
> > document.getElementById('cursorImg-0').style.left. //it returns distance in px from left
> > document.getElementById('cursorImg-0').style.top //it returns distance in px from top
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 您可以循环遍历所有光标位置，然后运行`osmd.cursor.next()`
> > ```
> > document.getElementById('cursorImg-0').style.left.
> > document.getElementById('cursorImg-0').style.top
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ，然后将结果保存在对象中
> > 您可以将光标移动到特定笔记
> > ```
> >     osmd.PlaybackManager.setPlaybackStart(
> >       window.allNotes[10].noteObject.getAbsoluteTimestamp()
> >     );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 您可以使用此代码从osmd获取所有笔记的数组
> > ```
> > const register_note_from_osmd = (osmd) => {
> >   if (osmd && osmd.cursor) {
> >     let iterator = osmd.cursor.Iterator;
> > 
> >     var allNotes = [];
> >     var allNotesWRest = [];
> > 
> >     while (!iterator.EndReached) {
> >       const voices = iterator.CurrentVoiceEntries;
> >       for (var i = 0; i < voices.length; i++) {
> >         const v = voices[i];
> >         const notes = v.Notes;
> >         for (var j = 0; j < notes.length; j++) {
> >           const note = notes[j];
> >           // make sure our note is not silent
> >           if (note != null) {
> >             allNotesWRest.push({
> >               note: note.halfTone + 12, // see issue #224
> >               time: iterator.currentTimeStamp.RealValue * 4,
> >               length: note.length.realValue,
> >               noteObject: note,
> >             });
> >           }
> >           if (note != null && note.halfTone != 0 && !note.isRest()) {
> >             allNotes.push({
> >               note: note.halfTone + 12, // see issue #224
> >               time: iterator.currentTimeStamp.RealValue * 4,
> >               length: note.length.realValue,
> >               noteObject: note,
> >             });
> >           }
> >         }
> >       }
> > 
> >       iterator.moveToNext();
> >     }
> >     window.allNotes = allNotes;
> >     window.allNotesWRest = allNotesWRest; // this includes also rest notes
> >   }
> > };
> > ```
> 
> #1216 当我使用这个函数时，我不提示一个函数。我想知道为什么

![image](https://user-images.githubusercontent.com/86224160/187626561-9835a424-c734-4b4c-936b-b4ce2e91a8d0.png)

**Comment by JanVeb** [comment]
```
  osmd.PlaybackManager.setPlaybackStart(
      window.allNotes[10].noteObject.getAbsoluteTimestamp()
    );
```

You need to enter a note to which you want to jump,  `window.allNotes[10]` this is undefined if you didn't call `register_note_from_osmd()` function first. `getAbsoluteTimestamp()` is information on the note which you need in order for cursor to move to specific note
