### ISSUE TITLE
Can I cache

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1219]
I want to know whether it is possible to cache after the first osmd. Load(), and then enter the page without loading again to reduce the loading time?

**Comment by sschmidTU** [comment]
No. Also, load() takes almost no time, the overwhelming majority is spent in render(). You could export the svg or image from canvas, but you can't import that into OSMD.

**Comment by zhouxiang233** [comment]
I tried to extract and save the contents in SVG, but neither osmd. Cursor. Next() nor osmd. Cursor. Reset() can be used before executing the method osmd. Render()

**Comment by sschmidTU** [comment]
That is correct. The cursor needs both the information from load() and render() to work.

**Comment by zhouxiang233** [comment]
So if I want to load the SVG cache directly, I can only rewrite the cursor function myself, right

**Comment by sschmidTU** [comment]
Yes. And that will be difficult, unless you only have a single staffline, then you can probably just go from one vf-stavenote to the next in the SVG.

**Comment by zhouxiang233** [comment]
Well, thank you very much.

**Comment by JanVeb** [comment]
You could also save all cursor positions and cursor left into a map, 
```
parseInt(
      document
        .getElementById('cursorImg-0')
        .style.left.match(/[+-]?\d+(\.\d+)?/g)
        .join(''),
      10
    );
```

cursorPositionsMap = {1: 80,
2:100,
3:130} // etc

You could then draw your own cursor over saved svg and move it based on this cursorPositionsMap, this should be fairly easy to implement
