### ISSUE TITLE
TypeError: b[g][0].e is not a function[Learn More]  osmd.min.js:8:525

### ISSUE THREAD

**Issue by MegaArman** [opensheetmusicdisplay/opensheetmusicdisplay#122]
Not sure what's going on, but when I try this as per the website  instructions:
```
<script src="osmd.min.js"></script>
<script>
var osmd = new OSMD("container-id");
osmd.load("http://downloads2.makemusic.com/musicxml/MozaVeilSample.xml").then(
  function() {
    osmd.render();
  }
);
</script>
```

I get this error:
```
Uncaught TypeError: b[g][0].e is not a function
    
at e (osmd.min.js:8)
 
at osmd.min.js:33
 
at osmd.min.js:8

```

Error occurs in both Firefox and Chrome.

**Comment by sebastianhaas** [comment]
Hey! I'm able to reproduce on Firefox now, I will take a look, thanks for reporting.

**Comment by Croxxpwn** [comment]
I got the same Error QwQ, both on Firefox or Chrome. Does it occur when using 0.2.0? I'm trying to build 0.2.0 instead.

**Comment by sebastianhaas** [comment]
The problem occurs due to minification in combination with the standalone browserify build, so you can always try the non-minified bundle if you're building locally. Also the CommonJS version from npm is working fine. Sorry for the inconvenience, I'll make sure to get to this as soon as possible.

**Comment by matt-uib** [comment]
no longer relevant due to new build/tool chain.

**Comment by borismus** [comment]
Please update the released version.

**Comment by bneumann** [comment]
Yes the releases lag a lot behind right now. Will do a new one the next days. The build scripts are for the develop branch which uses webpack 4 already while the latest release still uses grunt scripts and browserify
