### ISSUE TITLE
Reduce Grace note margin / spacing, add EngravingRules.GraceNoteGroupXMargin

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#1221]
Grace note margin to the main note was frequently much larger than necessary.
E.g. in Schubert - An die Musik:
![image](https://user-images.githubusercontent.com/33069673/187954096-1d4e75a3-08e6-4a7e-8f2f-0f05ccd9bb96.png)
after:
![image](https://user-images.githubusercontent.com/33069673/187954166-90c0bd37-5027-4a7a-aae3-9957a26474cb.png)

Türk - Ballet:
<img width="143" alt="image" src="https://user-images.githubusercontent.com/33069673/187954395-863c8535-82df-4db2-8582-58693f167d16.png">
after:
<img width="137" alt="image" src="https://user-images.githubusercontent.com/33069673/187954438-60d667d8-25fd-46fe-9d05-f1a57f9d680c.png">

If you prefer the old behavior or want to change the margin, adjust `osmd.EngravingRules.GraceNoteGroupXMargin` (new default 0, used to be 0.4).

In very rare cases, the 0 margin can be a bit tight:
<img width="203" alt="image" src="https://user-images.githubusercontent.com/33069673/187954705-ddb150c3-c124-44ab-9254-e97ca58bef5d.png">
(test_grace_slash_simple)

But in almost all cases, the margin is unnecessary, and the new default a clear improvement.

**Comment by michaelavery1** [comment]
@sschmidTU HI. the zip file above  only contained pngs, which mxml files to he correlate to?

**Comment by sschmidTU** [comment]
@michaelavery1 For example Türk - Ballet (G1 A3). Or do you mean something else?
Also Schubert - An Die Musik, which is a sampe in our demo.
The zip file contains the visual changes in our OSMD demo samples.
