### ISSUE TITLE
Chord with slash notehead displayed incorrect

### ISSUE THREAD

**Issue by mauxion** [opensheetmusicdisplay/opensheetmusicdisplay#1228]
When opening musicxml with drum chords all notes in chord displayed as slash if there is at least one slash note. 

Expected: 
![image](https://user-images.githubusercontent.com/3764909/190121183-f09b674d-640c-46c9-9a58-5fb9314a9367.png)

Actual:
![image](https://user-images.githubusercontent.com/3764909/190121235-04d6d0f5-0939-43ef-88bb-a744ff953c1c.png)

Here is file itself:
(sorry for .txt format, can't upload .musicxml or .xml)
[Bossa_nova_2_3.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9565081/Bossa_nova_2_3.txt)

Here is a 3 notes from first chord. Only one of them has slash notehead
>
            <note default-x="62.21" default-y="-35.00">
                <unpitched>
                    <display-step>F</display-step>
                    <display-octave>4</display-octave>
                </unpitched>
                <duration>1</duration>
                <instrument id="P1-I37"/>
                <voice>1</voice>
                <type>eighth</type>
                <stem>down</stem>
                <beam number="1">begin</beam>
            </note>
            <note default-x="62.21" default-y="-15.00">
                <chord/>
                <unpitched>
                    <display-step>C</display-step>
                    <display-octave>5</display-octave>
                </unpitched>
                <duration>1</duration>
                <instrument id="P1-I38"/>
                <voice>1</voice>
                <type>eighth</type>
                <stem>down</stem>
                <notehead>slash</notehead>
            </note>
            <note default-x="62.21" default-y="5.00">
                <chord/>
                <unpitched>
                    <display-step>G</display-step>
                    <display-octave>5</display-octave>
                </unpitched>
                <duration>1</duration>
                <instrument id="P1-I43"/>
                <voice>1</voice>
                <type>eighth</type>
                <stem>down</stem>
                <notehead>x</notehead>
            </note>

**Comment by sschmidTU** [comment]
Fixed in #1229. We'll soon make a new release that will include this. Thanks for submitting and providing a sample!

**Comment by sschmidTU** [comment]
@mauxion The fix is now published in OSMD 1.5.5.

**Comment by mauxion** [comment]
thanks a lot!
