### ISSUE TITLE
note after transpose not reverse

### ISSUE THREAD

**Issue by vunguyen260798** [opensheetmusicdisplay/opensheetmusicdisplay#1230]
![image](https://user-images.githubusercontent.com/59702511/190889003-34641a8e-f723-45c5-ba9a-68d690ad2829.png)
note aftar transpose, if it is 2nd line, it should be reverse to this 
![image](https://user-images.githubusercontent.com/59702511/190889037-e6512a55-e4c7-4ba9-a6c0-23a960278d0e.png)
thank you

**Comment by sschmidTU** [comment]
You probably mean the stem direction. We could look into that.

**Comment by sschmidTU** [comment]
@vunguyen260798 You should probably set `osmd.EngravingRules.SetWantedStemDirectionByXml = false` when you use transposition.
This should solve the issue, right?
<img width="182" alt="image" src="https://user-images.githubusercontent.com/33069673/190892970-3e6ca637-64c8-42e6-b7c5-b0a3cf054b89.png">
