### ISSUE TITLE
The cursor cannot appear due to different loading methods

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1233]
I directly parse the xml into a string through the function. When I use this string to load, the cursor will disappear
![image](https://user-images.githubusercontent.com/86224160/191476162-e1f18061-9f2b-4476-8850-b42f1c56d5d3.png)
![image](https://user-images.githubusercontent.com/86224160/191476308-515669b5-42a7-4032-9783-09841372d118.png)
It can be found that the cursor is set to display: none, and the width and height of the cursor are gone
![image](https://user-images.githubusercontent.com/86224160/191476955-f505bed3-46f8-417e-8379-d4def3ed91fc.png)
When I set the local path, the cursor can appear
![image](https://user-images.githubusercontent.com/86224160/191477124-c6a32867-a506-4c93-a38a-48be9a35282f.png)
I want to know whether this situation is caused by my wrong use method? How can I solve it

**Comment by sschmidTU** [comment]
Try `osmd.cursor.show()`.
Otherwise please share the xml file.

**Comment by sschmidTU** [comment]
No problem.
