### ISSUE TITLE
Not fully working using MuseScore MusicXml file

### ISSUE THREAD

**Issue by ljfreelancer88** [opensheetmusicdisplay/opensheetmusicdisplay#1238]
I downloaded a score from MuseScore and use it for my localhost setup, but the display is different.
https://musescore.com/user/1326956/scores/5931423

![Screenshot from 2022-09-23 16-51-21](https://user-images.githubusercontent.com/7919039/192054950-ed6a2edf-eec8-42b3-ade5-a029a0c30780.png)

![Screenshot from 2022-09-23 16-51-37](https://user-images.githubusercontent.com/7919039/192054953-1576dc5e-d7ec-4067-bf53-26499ac21ea1.png)

**Comment by sschmidTU** [comment]
Imported sheets look different in every sheet music viewer or editor you import them into, that's normal and expected. If you export a sheet from Sibelius to MusicXML and import it in MuseScore, it will look different.
If there is an issue with a specific element that looks bad, feel free to add more details.

**Comment by ljfreelancer88** [comment]
Sorry but how can I fully maximize the usage of OSMD? What's the best "workflow"? Because seems importing from MuseScore displays different value of the note (see 2nd bar of my screenshot)

**Comment by sschmidTU** [comment]
It looks to me like you have too many notes in the MusicXML. At the end of the 2nd bar, you have 387 in the tabs in OSMD, but only 87 in MuseScore. It might be that Musescore doesn't export correctly here. In that case you would need to delete the extra notes from the MusicXML.
It could also be that OSMD creates some extra notes somehow, but I can't imagine how.
By the way I also can't download the file, you need a Musescore subscription for that. And the score is copyrighted without a license, so I wouldn't upload it here.

**Comment by sschmidTU** [comment]
Unfortunately, MusicXML export is rather bad in a lot of music editors, especially for complex scores.
