### ISSUE TITLE
Dynamic coloring notes of a chord

### ISSUE THREAD

**Issue by rvilarl** [opensheetmusicdisplay/opensheetmusicdisplay#1246]
Based on the description found in
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo
and using the SVG version (getSVGGElement()) so as not to not have to re-render.

I am storing the `NoteToGraphicalNoteObjectId` for each note and I get different IDs for each notehead within the chord.

However when I use:
`osmd.EngravingRules.NoteToGraphicalNoteMap.getValue(gId)getSVGGElement();`
I get the pointer to the same vf-stavenote for the diffent noteheads.

How can I figure out which notehead is the appropriate one?

**Comment by rvilarl** [comment]
It would also help me to get the pointer to the associated vfnotehead. I will make a PR in VexFlow to get the SVGElement directly from the NoteHead. Is ther a way to do that?

**Comment by sschmidTU** [comment]
The noteheads are always stored in the same order in the SVG: from lowest to highest
<img width="802" alt="image" src="https://user-images.githubusercontent.com/33069673/193401548-2a8a351d-70a0-49ad-889b-14c08e1102fa.png">
That's the same order as in our VoiceEntry (`gnote.sourceNote.ParentVoiceEntry.Notes`), so you can write a little function to get the notehead you want by checking and using the same indices.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/33069673/193401730-f42f74fb-2520-4630-b0b6-29d1c6be016c.png">

Yes, it would be nice to have a function to get the notehead for each note directly!

**Comment by rvilarl** [comment]
Thanks Simon, and is there an easier way get the vfnotehead associated with a OSMD Note?

**Comment by sschmidTU** [comment]
Not in OSMD currently, or do you mean maybe in Vexflow?
We could write a relatively simple function in OSMD to get the vfnotehead, as I described above.

**Comment by rvilarl** [comment]
Thanks I meant in OSMD. 
And as said, I will make a PR in VexFlow to easily access the different SVGElements.

**Comment by sschmidTU** [comment]
Actually this might be a very useful function, and you might be the second person to ask about it :)
so maybe we'll also implement it in OSMD for vexflow 1.2.93.
(though it will be great to have it naturally in vexflow 4!)
