### ISSUE TITLE
Only one staff-line is displayed instead of 5

### ISSUE THREAD

**Issue by mauxion** [opensheetmusicdisplay/opensheetmusicdisplay#1254]
My scorepartwise is displayed with only 1 staff-line despite the fact that I didn't specify in staff-details->staff-lines

I have this problem only with this file. All other my drum notes created with the same way displayed correct.
And when I add staff-details->staff-lines to attributes it works as expected.

OSMD version 1.5.8

Expected:
![image](https://user-images.githubusercontent.com/3764909/196174820-1925f54c-1b75-49ce-aa8e-2f8ba9b9a416.png)

Actual:
![image](https://user-images.githubusercontent.com/3764909/196175322-f28c7ca9-57a2-4ac2-b329-0e8098afb901.png)

My settings:

> backend: 'Canvas',
> drawTitle: false,
> drawPartNames: false,
> pageFormat: 'Endless',
> drawFingerings: false,
> drawCredits: false,
> drawMetronomeMarks: false,
> drawTimeSignatures: false,
> renderSingleHorizontalStaffline: true,
> autoResize: false,
> coloringMode: 0,
> pageBackgroundColor: '#FFFFFF',
> performanceMode: false,
> drawingParameters: 'compacttight',
> drawUpToMeasureNumber: Number.MAX_SAFE_INTEGER
> osmd.EngravingRules.RenderClefsAtBeginningOfStaffline = false

Here is file itself:
(sorry for .txt format, can't upload .musicxml or .xml)
[SwingOnRide.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9800116/SwingOnRide.txt)

Related to:
#1252 
#1253

**Comment by sschmidTU** [comment]
You should set `osmd.EngravingRules.PercussionOneLineCutoff = 0`.
<img width="259" alt="image" src="https://user-images.githubusercontent.com/33069673/196479979-77a0f91d-94d1-4267-bbc7-b0c75fb22cca.png">

We should probably think about not having one line percussion parts by default, though they are only used when there are 3 or less different tones by default, in which case they usually save a lot of space in scores with multiple parts while still being easy to read.

**Comment by mauxion** [comment]
PercussionOneLineCutoff  helped, thank you!

**Comment by mauxion** [comment]
but now I've got another problem. When I have multiple parts, one-line parts looks not correct.
"Backbeat" part has staff-details->staff-lines 1.

Expected
![image](https://user-images.githubusercontent.com/3764909/196697523-6199a0ab-fc98-491f-b966-c4f9ec99f53c.png)

Actual
![image](https://user-images.githubusercontent.com/3764909/196697451-d6afeab2-44bd-4a91-a6a6-5b57e28a815c.png)

**Comment by sschmidTU** [comment]
Interesting, can you share the file again? We can probably check for the staff-lines attribute and better coordinate it with the positioning and PercussionOneLineCutoff.
I haven't seen a score with both one line and multiline drums before.

**Comment by sschmidTU** [comment]
@mauxion You can try changing `PercussionXMLDisplayStepNoteValueShift`, though I'm not sure why the notes are so far below the line in this case with default settings.

**Comment by mauxion** [comment]
Sure, here is a file
[TwoParts.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9821599/TwoParts.txt)

I'm not doing any export from program, this musicxml is generated by my software and I add\remove staff-lines intentionally because I do mix of rhythms\drum beats so I thought that it would be comfortable for user to see parts with one instrument on one line and parts with number of instruments on 5 lines. 

This issue is not critical for me, but I really appreciate your help, thx.

JFYI: here is the idea of my app
[https://www.youtube.com/watch?v=CLCur9BLzFI](https://www.youtube.com/watch?v=CLCur9BLzFI)
now I'm working on web version made totaly with kotlin (kotlin multiplaform\koltin-js\kotlin-react)

**Comment by sschmidTU** [comment]
Then maybe you're not setting display-step correctly. See here:
https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/display-step/

Otherwise, as I said, try adjusting the shift.
