### ISSUE TITLE
Lyrics for multple voices in same staff are overlaid

### ISSUE THREAD

**Issue by eddycurrently** [opensheetmusicdisplay/opensheetmusicdisplay#1268]
Hello all,

I've found an issue with rendering lyrics for multiple voices in the same staff. If I add lyrics above and below stave on both staves, the lyrics are only added below the stave as show here:
![lyrics_stacked](https://user-images.githubusercontent.com/33544599/200291092-47e20f45-0016-4117-a2fc-21355f4fee74.png)
[Here is a small MusicXML example demonstrating this issue.](https://drive.google.com/file/d/19zWu_Av-tC35_xa2xv4UwiYU-_HSpQst/view?usp=sharing)

Let me know if you need more information.

Regards

**Comment by sschmidTU** [comment]
Lyrics above stave are not supported.
By the way, Musescore does the exact same here.
