### ISSUE TITLE
Question: How to retrieve Rhythm-, Key- and ClefInstruction from a loaded score

### ISSUE THREAD

**Issue by ma-ku** [opensheetmusicdisplay/opensheetmusicdisplay#1273]
I am displaying mxl score using OSMD and so far everything is nice. Now I want to pull the RhythmInstruction data from the score to setup the metronome accordingly. For other purposes I also need to get the Key/ClefInstructions. I searched the objectmodel of a loaded score for these instructions but without success.

The score file does contain the information and it is also rendered (this is an example file):
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/519754/201393424-d270d6cb-d8c7-43dd-97b6-8910a4f1d85a.png">

Where do I find these objects? Any help is appreciated.

**Comment by sschmidTU** [comment]
The time signature is easily found like this:
`osmd.Sheet.SourceMeasures[0].ActiveTimeSignature`

In addition, you can find time signature, key signature and clef in `osmd.Sheet.SourceMeasures[0].firstInstructionsStaffEntries[0].Instructions`

This is an array of `AbstractNotationInstruction`, which can be (is inherited by) ClefInstruction, KeyInstruction or RhythmInstruction.

**Comment by ma-ku** [comment]
Thank you for the information. I still struggle finding my way through the API as most of the stuff is still undocumented. I found this and could use it.

**Comment by sschmidTU** [comment]
@ma-ku Glad it helped! I would highly recommend going through the wiki, especially the page "Exploring the Demo".
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo
