### ISSUE TITLE
Question: How to provide cursor options

### ISSUE THREAD

**Issue by ma-ku** [opensheetmusicdisplay/opensheetmusicdisplay#1276]
I saw there are CursorOptions defined in the API but so far I have not found a place where to apply these to a new or existing cursor. Any directions would be great.

**Comment by sschmidTU** [comment]
Two ways:
1. set `osmd.cursor.cursorOptions` (if you're in Typescript, it's private, so you currently need to cast to `any`: `(osmd.cursor as any).cursorOptions`. I've just added a setter CursorOptions on develop, will be in the next release 1.6.2)
2. set `cursorsOptions` in the OSMD constructor or via `osmd.setOptions({cursorsOptions: myOptions})`. It's an array of options, the first element being for the first cursor, which is probably the only cursor you're using, so just use an array including one CursorOptions object.

**Comment by ma-ku** [comment]
That was pretty quick. Thank you. Indeed, since I am using TS, many of these things are private and in a way I do respect that decision since poking the data might have severe side effects. Thank you for opening the options.

One suggestion; maybe you should not have an array of options but a map. That way a cursor could have a class/style as I would assume that relying on the order of creation might lead to troubles down the road?!

**Comment by sschmidTU** [comment]
I don't think so. You can change the options and call cursor.update() to update at any time.

**Comment by ma-ku** [comment]
OK, sound OK to me.
