### ISSUE TITLE
Is the cursor data missing?

### ISSUE THREAD

**Issue by showtan001** [opensheetmusicdisplay/opensheetmusicdisplay#1283]
I found that where the cursor moves, there is no corresponding data in "graphic.verticalGraphicalStaffEntryContainers" or "graphic.measureList". How can I get these data? As shown in the screenshot below, there are 3 first measures. But there is only one in the "verticalGraphicalStaffEntryContainers" data. How can I get the other 2 data in "verticalGraphicalStaffEntryContainers" or "measureList".
thank you very much!

![image](https://user-images.githubusercontent.com/32892347/206150473-362f6710-b935-4796-85a1-a639850c9a43.png)

**Comment by sschmidTU** [comment]
This is as expected. One position (x-position) is one VerticalGraphicalStaffEntry. A VerticalGraphicalStaffEntry contains all the staff entries at the position. A staff entry can contain multiple voice entries which can contain multiple notes. At the red position there is one vertical staff entry with 3 staff entries (1 for each of the 3 staffs), which should each have one note, as expected.

**Comment by showtan001** [comment]
> At the red position there is one vertical staff entry with 3 staff entries (1 for each of the 3 staffs), which should each have one note, as expected.

Thank you very much for your reply!

I want to get the data at "0 1" position from "verticalGraphicalStaffEntryContainers" at one time. When "cusor" jumps to "0 1" position, the data at "0 1" position can change color.
It changes color just like the back one.

What should I do?

image:
![image](https://user-images.githubusercontent.com/32892347/207277220-7b93029f-951b-452e-a0b6-b52999a13b34.png)

**Comment by showtan001** [comment]
> Just get the notes from the staff entries/voice entries or `osmd.cursor.GNotesUnderCursor()` and change the color, I don't understand the problem. If it's specific to this sheet, I need the musicxml file.

@sschmidTU 
address: [https://xh-piano.oss-cn-hangzhou.aliyuncs.com/file/20221130/19640b3471951438a63fbf7b8205bbf4.mxl](url)

I want to get "0 1" in "verticalGraphicalStaffEntryContainers", but I can't find "0 1" related data, only "2" related data

![image](https://user-images.githubusercontent.com/32892347/207526646-85c08f2f-3924-4855-8361-13a5b984f733.png)

**Comment by sschmidTU** [comment]
2 ways to get it:
```js
osmd.cursor.GNotesUnderCursor()[0].getSVGGElement()
osmd.graphic.MeasureList[0][2].staffEntries[0].graphicalVoiceEntries[0].notes[0]
```

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/33069673/207638046-490080e0-4e6c-40ff-98a5-9295f03b0e7e.png">
