### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'clear' of object

### ISSUE THREAD

**Issue by momolarson** [opensheetmusicdisplay/opensheetmusicdisplay#1288]
This issue occurs when using any version above 0.9.5.   There is a compatibility issue between OSMD and other projects that use the same SVG package:  When a web application tries to load the following error appears:

```Uncaught TypeError: Cannot assign to read only property 'clear' of object '[object Object]' at extend (bundle.js:31603:33) at List.extend (bundle.js:34039:3) at ./node_modules/@svgdotjs/svg.js/dist/svg.esm.js (bundle.js:39094:6)```

**Comment by sschmidTU** [comment]
As discussed on gitter, giving the redefined array prototype methods `writable: true` should fix this, right?

By the way, the original commit where the clear method was redefined seems to be this one:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/ceea6ae51f422dd5c83b25bb322f31055a69d490
later merged to develop in this commit:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/b21bb40f962c531806a4f524ce2a7b3a9311766f

Of course, redefining methods of basic prototypes like Array is a bit sketchy for compatibility reasons, maybe we can try to eliminate these entirely.

By the way, if you don't want to get credit for the commit via a PR, I'll just commit the fix in a few hours :)

**Comment by sschmidTU** [comment]
@momolarson OSMD 1.7.1 is now released with this change, could you test the compatibility again? That would be great :)

**Comment by momolarson** [comment]
it works!

**Comment by sschmidTU** [comment]
Great, thanks! Closing.
