### ISSUE TITLE
There are too many Notes for Measure, and the Notes are not displayed on the Phone

### ISSUE THREAD

**Issue by showtan001** [opensheetmusicdisplay/opensheetmusicdisplay#1290]
> Code:

```

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>

  <body>
    <div id="osmd"></div>
  </body>
  <script src="./opensheetmusicdisplay.min.js"></script>
  <script type="text/javascript">
    var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmd");
    osmd.load("https://xh-piano.oss-cn-hangzhou.aliyuncs.com/file/20221229/bb6e2a95095af3dffdaa2497786c83f7.mxl").then(
      function() {
        osmd.zoom = 0.4;
        osmd.render();
        window.addEventListener("resize", () => {
        osmd.render();
      });
    });
  </script>
</html>


```

> Xml:

https://xh-piano.oss-cn-hangzhou.aliyuncs.com/file/20221229/bb6e2a95095af3dffdaa2497786c83f7.mxl

> Do not display screenshots:

![image](https://user-images.githubusercontent.com/32892347/209935778-d3b533a6-a23d-4096-b1f0-4bfc483867a2.png)

> MuseScore:

![image](https://user-images.githubusercontent.com/32892347/209935812-53bd51a3-12cd-49d5-96c8-6e2fbf7b2588.png)

**Comment by sschmidTU** [comment]
If you get problems with too small widths, reduce the zoom, or use landscape format.
OSMD isn't made for very small widths.
Also, that score is extremely complex, which further makes it unsuitable for mobile portrait display.
