### ISSUE TITLE
Missing Pedal Marks on System Break

### ISSUE THREAD

**Issue by Andrew13648** [opensheetmusicdisplay/opensheetmusicdisplay#1292]
When I try to render pedal marks with a manual system break and the `newSystemFromXML: true` option, the pedal marks are not rendered on the second line.  Example in MuseScore:

![MuseScore_Pedal_Demo_2](https://user-images.githubusercontent.com/12521436/210245490-dfd96932-2c14-4378-94ca-5c192de391b1.png)

Now in OSMD:

![OSMD_Pedal_Demo_2](https://user-images.githubusercontent.com/12521436/210245512-7530cf9a-e525-43ba-8597-8a74b630a376.png)

If I set`newSystemFromXML: false`, the marks are rendered correctly (although on a single line).  I further observed this error being logged in the console:

```
Error: <path> attribute d: Expected number, "M495.5 493LNaN 493LNaN 483".
(anonymous) @ opensheetmusicdisplay.min.js:2
applyAttributes @ opensheetmusicdisplay.min.js:2
stroke @ opensheetmusicdisplay.min.js:2
(anonymous) @ opensheetmusicdisplay.min.js:2
drawBracketed @ opensheetmusicdisplay.min.js:2
draw @ opensheetmusicdisplay.min.js:2
drawPedals @ opensheetmusicdisplay.min.js:2
drawStaffLine @ opensheetmusicdisplay.min.js:2
drawStaffLine @ opensheetmusicdisplay.min.js:2
drawMusicSystemComponents @ opensheetmusicdisplay.min.js:2
drawMusicSystem @ opensheetmusicdisplay.min.js:2
drawPage @ opensheetmusicdisplay.min.js:2
drawPage @ opensheetmusicdisplay.min.js:2
drawSheet @ opensheetmusicdisplay.min.js:2
drawSheet @ opensheetmusicdisplay.min.js:2
render @ opensheetmusicdisplay.min.js:2
...
```

XML to recreate the issue:
[test_pedal_systembreak.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10483727/test_pedal_systembreak.zip)

[edit: replaced text paste with .zip upload - sschmidTU]

**Comment by sschmidTU** [comment]
Fixed in #1291, improved in #1306.

<img width="543" alt="image" src="https://user-images.githubusercontent.com/33069673/214152971-9a52eeaa-4846-48d0-82a4-10e1bd4db69d.png">

Thanks for the samples and reports! Really happy with the improvements :)
