### ISSUE TITLE
Highlighting notes according to measure/vertical graphical staff entry container

### ISSUE THREAD

**Issue by pokemon963** [opensheetmusicdisplay/opensheetmusicdisplay#1297]
Hi! I am trying to use the cursor in OSMD to highlight a certain portion of the sheet music according to its notes. Something like how the demo does it with coloring certain notes (i.e. osmd.graphic.measureList[0[0].staffEntries[0].graphicalVoiceEntries[0].notes[0].sourceNote.noteheadColor = "#FF0000"). Is there a way to do something like that for the cursor? I need to highlight all the notes aligned with each other, but I want to have more control over it rather than just using next or previous. Is there a way to do this?

(Also, I know that there are VerticalGraphicalStaffEntryContainers. Is there a way to index them?)

**Comment by sschmidTU** [comment]
What exactly do you want to highlight? Can you add an image? You're kind of saying "I want to highlight anything", so it's hard to answer how. But probably no, that is not possible with stock methods. The cursor is a relatively simple class. You can highlight a whole measure for example.
In the end you'll probably have to create your own cursor class or use some of the existing cursor code and modify it.

**Comment by pokemon963** [comment]
Here:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/84149276/213328261-7ce84e2c-3070-4d18-b737-4980b86b4c4f.png">

I essentially want to highlight/color the notes the way the cursor does but through indexing/identifying notes in particular, like instead of using previous/next a certain number of times to get there. I want to be able to "jump" the cursor if that makes sense from one area to another.

**Comment by sschmidTU** [comment]
You can just use `cursor.hide()`, use `cursor.next()` until you are where you want to be, then `cursor.show()` again.
`cursor.next()` is basically instantaneous, so don't worry about the speed of it.
You could also index all the notes beforehand if you want, for example via cursor.hide(), cursor.next(), etc.
also, use cursor.reset() to get back to the beginning.

**Comment by pokemon963** [comment]
Thank you so much! But is there really no way to index it then set the cursor to appear at a certain area. The project that I am working on requires me to read from a text file and highlight the notes corresponding to the label given.  These are examples of the label:

1+0/1
1+1/4
1+3/8
1+1/2

This is an explanation for the meaning of the labels: _For example, 1+0/1 represents the first measure and the first beat, and 4+3/4 represents the fourth measure and past the third quarter note._

Hence, the math to be worked out using cursor.next(), etc. might be a bit complex as each measure does not necessarily have the same labels.

I do realize I could create a list with the labels and index them from there. But I just wanted to know if there was a way to do it by just indexing with OSMD.

**Comment by sschmidTU** [comment]
You could do this, e.g. for measure 4 + 3/4:
```js
const targetFraction = new Fraction(4*4+3, 4);
// or: const targetFraction = new Fraction(4, 4).Add(new Fraction(3, 4);
osmd.cursor.iterator = new MusicPartManagerIterator(osmd.Sheet, targetFraction);
osmd.cursor.update();
```

But it's basically the same as calling cursor.next() until cursor.iterator.currentTimeStamp is at the fraction you want it to be.

**Comment by pokemon963** [comment]
Sorry! I have one more question. How do I import MusicPartManagerIterator in my js file? I have imported OSMD into my HTML by: <script src="https://unpkg.com/opensheetmusicdisplay@1.7.2/build/opensheetmusicdisplay.min.js"></script>. Is there a similar method for MusicPartManagerIterator ?

**Comment by sschmidTU** [comment]
You should be able to use it like `new opensheetmusicdisplay.MusicPartManagerIterator`, see here with TransposeCalculator:
https://github.com/opensheetmusicdisplay/RawJavascript-usage-example/blob/master/indexSimpler.html
(our plain javascript usage example)

**Comment by sschmidTU** [comment]
It worked for me with the code above:
```js
const targetFraction = new Fraction(4*4+3, 4);
// or: const targetFraction = new Fraction(4, 4).Add(new Fraction(3, 4);
osmd.cursor.iterator = new MusicPartManagerIterator(osmd.Sheet, targetFraction);
osmd.cursor.update();
```

by the way this would actually be measure 5 + 3/4, since measure 1 starts at 0.

If it doesn't work, please share your code.

**Comment by pokemon963** [comment]
This is my code: 
`function showCursor(){
  osmd.cursor.show();

  const targetFraction = new Fraction(1, 2);
  osmd.cursor.iterator = new opensheetmusicdisplay.MusicPartManagerIterator(osmd.Sheet, targetFraction);
  osmd.cursor.update();
}`

After loading a sheet music and hitting a button, I was trying to both show the cursor and move it. Just to make it in the same measure, I'm trying to move it to 1+1/2.

**Comment by sschmidTU** [comment]
You probably also have to use new opensheetmusicdisplay.Fraction(). It's our own class.
Do you see any errors in the console? What exactly happens when you excecute the code?

**Comment by pokemon963** [comment]
Oh thank you! The new opensheetmusicdisplay.Fraction() did the trick! When you used Fraction, I thought you were using the fraction.js class. 

I really appreciate all your help! Thank you so much!

**Comment by pokemon963** [comment]
I am having some issues with the `new opensheetmusicdisplay.MusicPartManagerIterator(osmd.Sheet, targetFraction);`

I am trying to get to '2+0/1'. Hence, my code is:

```
var targetFraction = new opensheetmusicdisplay.Fraction(1, 1);
osmd.cursor.iterator = new opensheetmusicdisplay.MusicPartManagerIterator(osmd.Sheet, targetFraction);
osmd.cursor.update();
```

However, instead of taking me to '2+0/1', it takes me to '2+1/4'. Is there something wrong with the way I am putting my Fraction?

**Comment by sschmidTU** [comment]
@pokemon963 you're probably in a 3/4 score. 1/1 is not always a full measure, only in 4/4. in 3/4, Fraction(3, 4) is a full measure further.
after a quarter note has passed, the timestamp is + Fraction(1, 4).

**Comment by pokemon963** [comment]
Thank you so much! Can I ask how would I know how much to add given the score? The score I am working with is 6/8 and just for other scores in the future. I am not knowledgeable on music and the scores.

**Comment by sschmidTU** [comment]
measure.Duration tells you how long the measure is.
Alternatively, you could also just do `const newTimestamp = measure.AbsoluteTimestamp.Add(myFractionWithinMeasure)`. So you just need to select the correct measure instead of counting.
(e.g. `const measure = osmd.Sheet.SourceMeasures[measureNumber - 1]`)

**Comment by pokemon963** [comment]
How do I access measure? I have tried doing osmd.measure.Duration but it does not work.

Can I also clarify how would I use `newTimestamp` and `measure` to update my iterator? Would I just add `newTimestamp` and `measure` together and put it in `MusicPartManagerIterator`?

**Comment by sschmidTU** [comment]
@pokemon963 You have to choose which measure you want. osmd.Sheet.SourceMeasures has all the measures in the music sheet. As I wrote in my last comment, you can choose a measure like this: `const measure = osmd.Sheet.SourceMeasures[measureNumber - 1]`

to update the cursor with a timestamp, do this:
```js
osmd.cursor.iterator = new opensheetmusicdisplay.MusicPartManagerIterator(osmd.Sheet, startTimestamp)
osmd.cursor.update();
```
I also wrote in my last comment how you get the startTimestamp (newTimestamp in the comment).

**Comment by pokemon963** [comment]
How am I able to get `const newTimestamp = measure.AbsoluteTimestamp.Add(myFractionWithinMeasure)`? When I put the command in, it says that measure is undefined?

**Comment by sschmidTU** [comment]
You have to define measure before you can use it.
You have to execute this beforehand, for example:
```js
const myTargetMeasureNumber = 2;
const measure = osmd.Sheet.SourceMeasures[myTargetMeasureNumber - 1];
```

**Comment by pokemon963** [comment]
Your method works when I'm inputting a measure and the cursor jumps to the beginning to that measure. For some reason, when I try to do for another thing, the cursor just hangs/doesn't move. I am trying to get the cursor to move along with the audio playing. 

```
var measureEdited = osmd.Sheet.SourceMeasures[measure - 1];
                    var targetFraction = measureEdited.AbsoluteTimestamp.Add(new opensheetmusicdisplay.Fraction(numerator, denominator));// jumps to beginning of measure
                    osmd.cursor.iterator = new opensheetmusicdisplay.MusicPartManagerIterator(osmd.Sheet, targetFraction);
                    osmd.cursor.update();
```
When doing this method, the cursor doesn't move.


```
const targetFraction = new opensheetmusicdisplay.Fraction((denominator * (measure - 1)) + numerator, denominator); // computes for position
                    osmd.cursor.iterator = new opensheetmusicdisplay.MusicPartManagerIterator(osmd.Sheet, targetFraction);
                    osmd.cursor.update(); // updates cursor
```
When I do this method however, the cursor moves but it just doesn't move correctly to the right spot. Is there a reason why the second one makes the cursor moves but the first one doesn't? From what I can tell, the targetFraction value is increasing way too much but I am not sure why? Is there another method to achieve what I want?

**Comment by sschmidTU** [comment]
What's your denominator, measure and numerator there? The targetFraction must be incorrect

**Comment by sschmidTU** [comment]
Just use the method with the measure.AboluteTimestamp.

**Comment by pokemon963** [comment]
The values for denominator, numerator and measure change. But they come from/within the sheet. For example, they can be “2+0/1”then “2+1/4”. Then, I separate the measure, numerator and denominator from each other and place it into targetFraction. But for some reason in the first method, the cursor just hangs. I’m not sure what’s wrong/what I can do to fix it. 

Is there another method to achieve this? For example with 2+0/1, is there an amount I could add to Fraction(2, 1) to get it to the right spot in a 6/8 sheet.

**Comment by sschmidTU** [comment]
You definitely use the wrong values for numerator and denominator.
As I said a few comments ago, "1/1 is not always a full measure, only in 4/4. in 3/4, Fraction(3, 4) is a full measure further.
after a quarter note has passed, the timestamp is + Fraction(1, 4)."
So, in a 6/8 sheet, one measure further is Fraction(6, 8), not Fraction(1, 1).

So if you want to get to measure 3 + 1/8 in a 6/8 sheet, you need to add Fraction(2 * 6, 8) and Fraction(1, 8).

**Comment by pokemon963** [comment]
Hi! That worked perfectly! Thank you! 

I do have one more question. Is there a way to extract 6/8 from the sheet so that the calculate the timestamp for any sheet at different scores.

**Comment by sschmidTU** [comment]
Yes, at least if there are no time signature changes during the sheet (for example, the sheet could start in 6/8, then switch to 4/4 after 4 measures. it happens in some pieces, though usually not in popular music).
Then the measure duration is always `osmd.Sheet.SourceMeasures[0].ActiveTimeSignature`, whose RealValue is the same as `osmd.Sheet.SourceMeasures[0].Duration` (e.g. ActiveTimeSignature can be 4/4 while duration is 1/1, same RealValue, simplified fraction).

**Comment by pokemon963** [comment]
Thank you so much! I think I was able to fix my problems!
