### ISSUE TITLE
osmd.load/render fails silently

### ISSUE THREAD

**Issue by zprjk** [opensheetmusicdisplay/opensheetmusicdisplay#130]
Hello,
I'm having problems loading a musicxml file. Here's my simple setup:

```typescript
let osmd = new OSMD('music-display-container', false);
osmd.setLogLevel('trace')

osmd
  .load('./assets/test.xml')
  .then(
    () => osmd.render(),
    (err) => console.log(err)
  );
```
```html
<div id="music-display-container"></div>
```

in the console devtools only appears:
(there's no errors only this info msg)
```
OSMD.js:81 Loaded sheet Unknown path successfully.
```

I tested loading my file in other js tools and it worked, but not in this one.
Maybe the problem is related with the way the file was exported? 
![image](https://cloud.githubusercontent.com/assets/9919760/26217430/43f6de72-3bff-11e7-85bd-936d007536b5.png)

here's the file: https://gist.github.com/zprjk/7b1b39d40342a53da911ba758914baf3 (this will be up temporally)

Thanks.

**Comment by zprjk** [comment]
Update: The problem is that my file has the field **part-name** with a whitespace
![image](https://cloud.githubusercontent.com/assets/9919760/26489678/4bd9ae10-4200-11e7-8af9-cb97b89022a9.png)

Changing to a name will load the xml with no problems:
![image](https://cloud.githubusercontent.com/assets/9919760/26489822/d30c3006-4200-11e7-821f-e71cb6150342.png)

But If I switch the whitespace to its html entity name **&nbsp** this will actually work:
![image](https://cloud.githubusercontent.com/assets/9919760/26489850/f327a08c-4200-11e7-9a3e-22ac1c60b5ee.png)

So this seems to be a bug with this library, yes?

Also the 'Unkown path' appears because the file has no **work-title** and I don't have a option to not now show the title or simply don't show the title if there's any.

**Comment by sebastianhaas** [comment]
@zprjk thanks for detailed exploration. I think OSMD should be able to cope with both the empty title and part name. Should be easy to fix as well. The real issue I see here, is that it fails silently, logging `Loaded sheet successfully`, that's something we really want to change.

My time is very limited at the moment, so if anyone wants to provide a fix, you're very welcome to do so. I'll get to this as soon as possible otherwise.

**Comment by matt-uib** [comment]
@zprjk, i fixed the error by adding missing initialization at the boundingBox object. So now your file is now rendered!
