### ISSUE TITLE
After advancing past the last note of the score, osmd.cursor.previous() doesn't work

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1302]
Steps to reproduce:
1. Open https://opensheetmusicdisplay.github.io/demo/.
2. Under "Cursor", click "Show".
3. Press the "Next" button or hold the Right Arrow Key until the cursor reaches the last note of the score.
4. Press the "Next" button or the Right Arrow Key one more time to advance past the last note of the score.
5. Attempt to go backwards by pressing the "Back" button or the Left Arrow Key one or more times. However, the cursor does not move backwards and remains stuck on the last note. The program appears to get stuck in an infinite loop and the webpage becomes unresponsive.

**Comment by sschmidTU** [comment]
Oh, good find, thanks! Should be relatively easy to fix.

**Comment by sschmidTU** [comment]
Fixed.

Simple test sample:
[test_cursor_back_end.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10472694/test_cursor_back_end.zip)

I'll see if I can quickly add a karma test for this.
