### ISSUE TITLE
Inconsistent cursor visibility at beginning of score

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1303]
Steps to reproduce:

1. Open https://opensheetmusicdisplay.github.io/demo/.
2. Click "Show", then click "Back". The first note of the score is highlighted in green.
3. Refresh the page.
4. Click "Back", then click "Show". The first note of the score is *not* highlighted in green.

This may be the intended behavior. 

But, a natural question that arises is: should order matter?
In other words, should "Show" + "Back" produce a different outcome than "Back" + "Show"?

**Comment by sschmidTU** [comment]
Fixed. This definitely wasn't intuitive behavior and could be puzzling when nothing happens on clicking "Show".

The problem (as well as #1304) arose by the fact that `previous()` is a recent addition to the functionality, so the cursor and iterator were never intended to be able to go backwards, certainly not beyond the beginning of the sheet, as they could always simply be reset to a position instead.

Thanks for the report(s)!
