### ISSUE TITLE
Inconsistent cursor visibility at end of score

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1308]
Steps to reproduce:

1. Open [demo](https://opensheetmusicdisplay.github.io/demo/). 
2. Type the following commands into console: `osmd.cursor.show(); while (!osmd.cursor.iterator.endReached) {osmd.cursor.next();}`. The last note of the score is highlighted in green.
3. Refresh the page.
4. Type the following commands into console: `while (!osmd.cursor.iterator.endReached) {osmd.cursor.next();} osmd.cursor.show();`. The last note of the score is *not* highlighted in green.

**Comment by sschmidTU** [comment]
It works for me (last note is highlighted). Maybe your browser didn't clean up objects correctly.

**Comment by michaelcchu** [comment]
Oops sorry, my bad. I downloaded the most recent version and it works now! :)

**Comment by michaelcchu** [comment]
Hmm I think I made a mistake... for some reason I am still having trouble... :(

Here's a slight variation: if you try `osmd.cursor.hide(); while (!osmd.cursor.iterator.endReached) {osmd.cursor.next();} osmd.cursor.show();`, is the last note unhighlighted?

**Comment by sschmidTU** [comment]
Ok, that reproduced it. Fixed.
The issue is that if you advance past the end of the sheet, the cursor position is basically beyond the sheet / not well defined, so it's not so clear why anything would be highlighted anyways.
But it's definitely more intuitive to show the last note/sheet position.

**Comment by sschmidTU** [comment]
Cursor is now shown at start/end of measure if going before/after the first/last position of the sheet:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/33069673/214583336-5f534ab5-f22b-4e9d-8adf-9a322c4fdb69.png">

<img width="271" alt="image" src="https://user-images.githubusercontent.com/33069673/214583363-e6d763d9-b0c8-45ed-832b-2d5741b6442f.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/33069673/214583187-3ba449a1-5896-44ba-b5bf-ba9a2b951502.png">

<img width="228" alt="image" src="https://user-images.githubusercontent.com/33069673/214583237-eef2e589-015c-40f4-b223-94bb854bc29e.png">

This seems more intuitive, eliminating the issue of the cursor visually doing nothing when you go `next()` or `previous()` to before or after the confines of the sheet.

**Comment by sschmidTU** [comment]
I updated the online [demo](https://opensheetmusicdisplay.github.io/demo/), so this is easily testable (before the next release).

**Comment by michaelcchu** [comment]
Oh cool, that's a nice feature! I agree, I think it makes more sense that way. Thanks for adding it!
