### ISSUE TITLE
Inconsistent currentTimeStamp

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1309]
Steps to reproduce:

1. Open [demo](https://opensheetmusicdisplay.github.io/demo/).
2. Upload this test file: [test_currentTimeStamp.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10486175/test_currentTimeStamp.zip).
3. Click "Show", then click "Next".
4. `osmd.cursor.iterator.currentTimeStamp.realValue` returns `1`, as expected.
5. Click "Next", then click "Back".
6. `osmd.cursor.iterator.currentTimeStamp.realValue` returns `0`. This is **unexpected**. We expected `1`.

**Comment by sschmidTU** [comment]
Fixed.
