### ISSUE TITLE
Highlight at beginning and end of score

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1310]
In [demo](https://opensheetmusicdisplay.github.io/demo/), if you try this command: `osmd.sheet.Instruments[0].Visible=false; osmd.render(); osmd.cursor.previous(); osmd.cursor.show();`, is the beginning of the score unhighlighted?

**Comment by michaelcchu** [comment]
Also, if you refresh the page and try this command: `osmd.sheet.Instruments[0].Visible=false; osmd.render(); while (!osmd.cursor.iterator.endReached) {osmd.cursor.next();} osmd.cursor.show();`, is the end of the score unhighlighted?

**Comment by sschmidTU** [comment]
Quick question, are you actually using these cursor.previous() use cases functionally or are you just trying to find ways to make cursor.previous() not work?
You always have the option not to use cursor.previous() (which was added by an external PR) and instead use cursor.reset().
Or use this:
```js
cursor.Iterator = new MusicPartManagerIterator(osmd.Sheet, new Fraction(0, 0);
cursor.update();
```
(instead of a fraction, you can use a VerticalGraphicalStaffEntryContainer.AbsoluteTimestamp)

**Comment by michaelcchu** [comment]
Yes, I'm using `osmd.cursor.previous` in a project called [EasyPlay7](https://mcchu.com/easyplay7/) (here's a [demonstration](https://youtu.be/IDK4v80pdYI?t=4), and here is the [source code](https://github.com/michaelcchu/easyplay7)). Sometimes I happened to discover the edge cases naturally, and other times I actively looked for them. In EasyPlay7, the user presses the Left Arrow Key (which calls `osmd.cursor.previous`) and the Right Arrow Key, (which calls `osmd.cursor.next`) to navigate the score. The edge cases aren't super important, since the user will probably only run into them occasionally, but I think it's good to make the interface as intuitive and consistent as possible, to ensure that the user has a happy/satisfying experience with minimal confusion when using EasyPlay7.

One edge case that is somewhat important and particularly likely to come up in EasyPlay7 is `osmd.cursor.show(); while (!osmd.cursor.iterator.endReached) {osmd.cursor.next();} osmd.sheet.Instruments[0].Visible=false; osmd.sheet.Instruments[1].Visible=true; osmd.render();`. This happens when the user plays through the violin part, reaches the end of the score, and then changes to the cello part. Currently, when the user is past the end of the score and changes from the violin part to the cello part, the cursor disappears, but it would be nice if the cursor did not disappear.

In EasyPlay7, the cursor before the beginning of the score represents the idea that "we haven't played any notes yet", and the cursor after the end of the score represents the idea that "we have played all of the notes / finished the piece".

As for the timestamp issue (#1309), this used to be important when I was using timestamps. I was checking `if (currentTimeStamp === 0)` to see whether or not the cursor was at the beginning of the score, and sometimes the cursor was giving incorrect timestamps (due to `cursor.previous`). So my program sometimes thought that the cursor was at the beginning of the score, even though it wasn't, and this led to problems. But eventually, I ended up not needing to rely on timestamps, so the issue doesn't matter as much.

**Comment by sschmidTU** [comment]
Fixed.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/33069673/214982584-0b4903b3-b30b-4a66-9d7b-e80fda82d2b0.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/33069673/214982605-c3dceecb-c1c0-45e1-8762-1a15bcf6619a.png">

original samples:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/33069673/214982648-6182e3b4-90d0-415a-97b3-b263fbac66f9.png">

<img width="415" alt="image" src="https://user-images.githubusercontent.com/33069673/214982665-a90b228a-8f0e-4cac-a783-c579963d3e05.png">

[test_cursor_instruments_visible_false_samples.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10514570/test_cursor_instruments_visible_false_samples.zip)

code to reproduce (see above):
```js
osmd.cursor.show();
while (!osmd.cursor.iterator.endReached) {osmd.cursor.next();}
osmd.sheet.Instruments[0].Visible=false;
osmd.sheet.Instruments[1].Visible=true;
osmd.render();
```
