### ISSUE TITLE
osmd.cursor.NotesUnderCursor() returns incorrect pitches

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1311]
Steps to reproduce:

1. Open [demo](https://opensheetmusicdisplay.github.io/demo/).
2. Click "Show" and use the arrow keys to navigate to the last VerticalGraphicalStaffEntryContainer of "An die ferne Geliebte (Page 1)". The eighth note "C2" and the lyrics word "schen" should be highlighted. 
3. In console, enter the following command: `for (const note of osmd.cursor.NotesUnderCursor()) {console.log(note.pitch.frequency);}`.
4. Console outputs three frequencies. The first, `523.2511306011972`, is good. The second and third, `3951.066410048993` and `1174.6590716696303`, are not good. There is only one note under the cursor, so there should only be one frequency, and the other two "notes", which are rests, should have `undefined` pitches.

This issue is not related to `osmd.cursor.previous`, and it affects anyone using the `NotesUnderCursor` function to obtain pitch information. If I use an [`OscillatorNode`](https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode) to play the frequencies in the sheet music, a very high `3951` Hz pitch will be played (when it should just be a rest), which is incorrect and confuses/bothers the users, who expect the correct frequencies to be played.

**Comment by sschmidTU** [comment]
Fixed, though there is a simple way to avoid this, by checking e.g. `osmd.cursor.NotesUnderCursor()[1].isRest()`. You shouldn't try to play rest notes ;)
OSMD needs the pitch calculation for the placement on the stafflines, which can be dictated in the MusicXML file. We could work around this, or we could expect users not to play rest notes.
