### ISSUE TITLE
Wiki: Error in downloading!

### ISSUE THREAD

**Issue by marsung** [opensheetmusicdisplay/opensheetmusicdisplay#1313]
Hello, there was a mistake when downloading Wiki!
-----------------------------------------------------------------------------------------------
$ git clone https://github.com/opensheetmusicdisplay/opensheetmusicdisplay.wiki.git
Cloning into 'opensheetmusicdisplay.wiki'...
remote: Enumerating objects: 1106, done.
remote: Total 1106 (delta 0), reused 0 (delta 0), pack-reused 1106
Receiving objects: 100% (1106/1106), 1.18 MiB | 750.00 KiB/s, done.
Resolving deltas: 100% (690/690), done.
error: invalid path 'Tutorial:-Extracting-note-timing-for-playing.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by sschmidTU** [comment]
Huh. Which OS are you on? Mac? It works for me on Linux (Mint).
We might just rename the page so that the title doesn't have a `:` (colon) in it.

**Comment by sschmidTU** [comment]
Also, what's your git version?
`git --version`

**Comment by marsung** [comment]
thank you!
I'm on Windows 7.
MINGW64 (minty 3.6.1) for git terminal.

**Comment by marsung** [comment]
git version 2.38.1.windows.1

**Comment by sschmidTU** [comment]
Ok, my git is older, so it's Windows not liking the colon in the path, makes sense.

I removed it, can you try git clone again?

**Comment by marsung** [comment]
Clone succeeded! thank you.
