### ISSUE TITLE
When loading a new score in console, should osmd.zoom get reset to 1?

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1317]
Currently, in [demo](https://opensheetmusicdisplay.github.io/demo/), loading a new score in `console` results in `osmd.zoom` getting reset to `1`.

For example,
```js
osmd.zoom = 1.5;
osmd.render();
osmd.load("./Mozart_Clarinet_Quintet_Excerpt.mxl").then(() => {osmd.render();});
console.log("Zoom:", osmd.zoom);
```
outputs 
```js 
Zoom: 1 
```
rather than
```js 
Zoom: 1.5
``` 
. 

Should this be the case?

On the one hand, some might argue that it makes sense to reset the zoom to `1` because that's a good default value, and every score is different, so every score might require a different amount of zoom to be optimally viewable for the user. 

On the other hand, some might argue that it make sense *not* to reset the zoom to `1` because scores are mostly similar, so every score requires about the same amount of zoom to be optimally viewable for the user. For example, if the user sees the current score best at `osmd.zoom = 1.5`, then it's likely that the user sees all other scores best at `osmd.zoom = 1.5`. Also, at least one other property remains constant despite file changes: `renderSingleHorizontalStaffline`. When we run the following code:
```js
osmd.setOptions({renderSingleHorizontalStaffline: true});
osmd.render();
osmd.load("./Mozart_DasVeilchen.xml").then(() => {osmd.render();});
```
the new score is still rendered as a single horizontal staffline (despite the file change).

What do you think? When loading a new score in `console`, should `osmd.zoom` get reset to `1`?

**Comment by sschmidTU** [comment]
Similar situation as in #1316.
With our use cases, we are usually not interested in keeping the zoom from the previous piece.
But it might be a better default, depends on the situation.

**Comment by michaelcchu** [comment]
If you drop a MusicXML on the page, the demo keeps the zoom from the previous piece. 
But if you load a MusicXML in console, the zoom gets reset to `1`.
To be consistent, I think the demo should keep the zoom from the previous piece.

More generally (outside of the demo / using OSMD as a library), I think `osmd.zoom` shouldn't get reset unless the developer intentionally resets it. If the developer sets `osmd.zoom = 1.5` and never changes `osmd.zoom` , then `osmd.zoom` should always be `1.5`, no matter what.
