### ISSUE TITLE
Can I transpose musicxml document using this library ?

### ISSUE THREAD

**Issue by martinfou** [opensheetmusicdisplay/opensheetmusicdisplay#132]
I wanted to know if it is possible to transpose a musicxml document according to key or intervals using this library? If not can you suggest one that could?

**Comment by matt-uib** [comment]
Yes we have a transposition plugin implemented, but we want to license this feature and therefore it is not in the open-souce part of opensheetmusicdisplay. With it you can transpose the whole piece by a given number of semitones (for every semitone we also show the corresponding key-signature - so you can select by key as well). The key signature and the accidentals will be recalculated to get a clean transposed display of the score on screen.
But if you meant actually to read an xml, transpose it and finally save it with the changes back to xml, we cannot do this right now, as there is no musicXML Exporter implemented. But of course an exporter would be nice to have!

**Comment by MIDIculous** [comment]
@matt-uib When do you think this transpose function will be available and how much would it be to license?

**Comment by matt-uib** [comment]
@MIDIculous currently we are a bit busy with some other things, but we want to soon discuss internally about which features can be licensed and about the pricing model. I hope i can come up with some info and numbers soon.

**Comment by MIDIculous** [comment]
@matt-uib Do you have a website?

**Comment by sebastianhaas** [comment]
http://opensheetmusicdisplay.org/ ?

**Comment by sschmidTU** [comment]
The OSMD Transposition plugin is now integrated into OSMD, see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/733#issuecomment-823530818.
(currently on the develop branch, will be released in the next OSMD version after 0.9.5)
