### ISSUE TITLE
The cursor cannot return to the first position

### ISSUE THREAD

**Issue by junke365** [opensheetmusicdisplay/opensheetmusicdisplay#1320]
Click the note event, and the last cursor is marked with the first note.The cursor cannot return to the first position

**Comment by sschmidTU** [comment]
Not sure what you mean. There are no click events by default in OSMD. Are you talking about the audio player?

**Comment by junke365** [comment]
There's a function where the cursor can follow the note

**Comment by sschmidTU** [comment]
Do you also know the name of that function?
Please describe in more detail.

**Comment by junke365** [comment]
![image](https://user-images.githubusercontent.com/25856057/217553837-22ecf978-e382-43a3-b5a4-3068e8719354.png)
![image](https://user-images.githubusercontent.com/25856057/217553903-7497f240-7ef0-4cc6-b281-afd4cb102d72.png)

**Comment by junke365** [comment]
After clicking the note, osmd.cursor.reset() has no effect, does not return to the first position, and stays there

**Comment by sschmidTU** [comment]
Clicking a note sets the start position (osmd.Sheet.SelectionStart).
reset() resets to the start position.
You are not supposed to use cursor functions with playback, instead use `osmd.PlaybackManager.reset()`, or use `osmd.PlaybackManager.setPlaybackStart()` to reset to the beginning.

Also, please open audio player issue in the audio player repository next time.
