### ISSUE TITLE
Display sheet music containing multiple preludes

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1324]
This [sheet music](https://musescore.com/user/13033246/scores/5743221) contains Bach's [Six Little Preludes](https://en.wikipedia.org/wiki/Six_Little_Preludes_(Bach)). When I download or export as .musicxml and display the sheet music in [osmd](https://opensheetmusicdisplay.github.io/demo/), all of the preludes are joined together one after another, without any breaks. Is there a way to separate the preludes?

Current output (osmd):

![preludes](https://user-images.githubusercontent.com/50280000/218359538-7144b6b9-50c7-47b4-96b1-edc8840c9fea.png)

Desired output (musescore):

![image](https://user-images.githubusercontent.com/50280000/218359006-bb1fd022-3e02-4621-a987-8d70d7c2636e.png)

**Comment by sschmidTU** [comment]
You can use `osmd.EngravingRules.NewPageAtXMLNewPageAttribute = true` to create a page break when the MusicXML gives one (though many MusicXMLs abuse this and set it at positions that don't make sense for OSMD).
But generally we are limited by how the MusicXML is constructed, we show what and how it says to show. There is almost no information in the MusicXML at measure 17 that indicates a new prelude starts (I also couldn't find the text "2. prelude in c minor..." etc).

**Comment by michaelcchu** [comment]
Using MuseScore, I exported a more full .musicxml file ([Bach__Sechs_kleine_Prludien__BWV_933-938_full.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10751684/Bach__Sechs_kleine_Prludien__BWV_933-938_full.zip))
which contains the words "1. Prelude in C major, BWV 993" as part of a `<credit-words>` element ([https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/credit-words/](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/credit-words/)) (see code below).

```xml
<credit page="4">
<credit-words default-x="700.2" default-y="1906.21" justify="center" valign="top" font-size="14">Sechs kleine Präludien</credit-words>
</credit>
<credit page="4">
<credit-type>composer</credit-type>
<credit-words default-x="1333.73" default-y="1832.87" justify="right" valign="bottom" font-size="12">Johann Sebastian Bach</credit-words>
</credit>
<credit page="4">
<credit-words default-x="700.2" default-y="1866.21" justify="center" valign="top" font-size="19">1. Prelude in C major, BWV 933</credit-words>
</credit>
<credit page="5">
<credit-words default-x="700.2" default-y="1906.21" justify="center" valign="top" font-size="14">Sechs kleine Präludien</credit-words>
</credit>
<credit page="5">
<credit-words default-x="700.2" default-y="1866.21" justify="center" valign="top" font-size="19">2. Prelude in C minor, BWV 934</credit-words>
</credit>
<credit page="5">
<credit-type>composer</credit-type>
<credit-words default-x="1333.73" default-y="1832.87" justify="right" valign="bottom" font-size="12">Johann Sebastian Bach</credit-words>
</credit>
<credit page="6">
<credit-words default-x="700.2" default-y="1906.21" justify="center" valign="top" font-size="14">Sechs kleine Präludien</credit-words>
</credit>
<credit page="6">
<credit-words default-x="700.2" default-y="1866.21" justify="center" valign="top" font-size="19">3. Prelude in D minor, BWV 935</credit-words>
</credit>
<credit page="6">
<credit-type>composer</credit-type>
<credit-words default-x="1333.73" default-y="1832.87" justify="right" valign="bottom" font-size="12">Johann Sebastian Bach</credit-words>
</credit>
```

Currently, by default, osmd demo doesn't display the `<credit-words>` text. Is there a way to display this text?

**Comment by sschmidTU** [comment]
If it's past page 1, no, currently not.

**Comment by michaelcchu** [comment]
Thanks for your help! I think you are right.

I was trying to display multiple pieces / movements using a `.musicxml` file, but after doing some research, I now see that this is bad practice / not recommended. According to [musicxml.com](https://www.musicxml.com/publications/makemusic-recordare/notation-and-analysis/a-sample-musicxml-encoding/#:~:text=MusicXML%20score%20files,and%20musicological%20data.),

> MusicXML score files do not represent presentation concepts such as pages and systems. The details of formatting will change based on different paper and display sizes. In the XML environment, formatting is handled separately from structure and semantics. The same applies for detailed interpretive performance information. Separate XML languages could be developed to represent individual printings and performances.

and

> Each MusicXML score file represents a single movement. Multi-movement works and collections are represented in a MusicXML opus file, based on a separate DTD for linking and musicological data.

.

So in the future I will not attempt to display multiple pieces of sheet music in a single `.musicxml` file.

Once again, thanks for your help, and sorry if I am bothering you too much. I hope that my comments may be useful to the osmd community in some way. I really appreciate your work; OSMD is great! :)

**Comment by michaelcchu** [comment]
As a followup question, the [musicxml.com](https://www.musicxml.com/publications/makemusic-recordare/notation-and-analysis/a-sample-musicxml-encoding/#:~:text=Each%20MusicXML%20score%20file%20represents%20a%20single%20movement.%20Multi%2Dmovement%20works%20and%20collections%20are%20represented%20in%20a%20MusicXML%20opus%20file%2C%20based%20on%20a%20separate%20DTD%20for%20linking%20and%20musicological%20data.) article distinguishes between MusicXML "score files" and MusicXML "opus files". Is OSMD primarily designed to display MusicXML score files or MusicXML opus files? Additionally, how does OSMD handle the MusicXML [`<opus>`](https://www.w3.org/2021/06/musicxml40/opus-reference/elements/opus/) element?

**Comment by sschmidTU** [comment]
OSMD is for normal MusicXML scores, not opus files. Actually, I've never seen an opus file in practice. It also seems to go against the idea of MusicXML representing a single movement, as you shared above.
The opus element seems to only exist in opus files. OSMD doesn't process it.
