### ISSUE TITLE
Measure numbers for first and second endings

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1326]
How does osmd assign measure numbers for first and second endings?

**Comment by sschmidTU** [comment]
OSMD gives each measure its own measure number.
Gould's Behind Bars apparently "recommends two different systems for numbering endings (p. 237): the 155a and 155b system and the straight-through, the latter particularly for ensemble music to avoid rehearsal confusion."

If the MusicXML gives a different measure numbering, that is used instead, unless you set `osmd.EngravingRules.UseXMLMeasureNumbers = false`.
