### ISSUE TITLE
Should first full measure be labeled "1"?

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1328]
When I upload this test file [test_pickup_multimeasure_rest.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10722778/test_pickup_multimeasure_rest.zip) in [demo](https://opensheetmusicdisplay.github.io/demo/), the first full measure is labeled "2", but should it be labeled "1"? See image below:

![pickup](https://user-images.githubusercontent.com/50280000/218479675-165f85a1-812a-4aaf-bee2-d7068a6f54aa.png)

I'm not sure if there's an official convention, but some sources say that numbering should start after the pickup measure:

https://music.stackexchange.com/questions/96339/should-pickup-measures-have-measure-numbers
> No, a pickup measure will not be counted as measure 1 in a score. Instead, the first full measure following the pickup will be labeled as measure.

https://acmp.net/art-and-science-measure-numbering/

>  Composer/arranger George A. Speckert, an editor at Baerenreiter, ... defines the Baerenreiter conventions
> 
> The first full measure is “1” – , do not count upbeats.
> The first and second ending brackets are numbered “a” and “b” ( i.e. 16a, 16b.) This will only be printed if the bracket is at the beginning of a line. No special treatment for repeats and jumps — even if the repeat is in the middle of a measure.
> In cases where one voice is notated with a repeat and another without (i.e. different phrase endings), both numbers are noted, like 17 (25).

http://cmceast.org/resources/numbering-measures.php

> How to Number Measures
> There is no universally-agreed-upon system for counting measures. The following scheme is frequently found in pre-numbered parts and can be applied successfully in almost all cases:
> 
> - Place a bar number either at the beginning of each line or every ten bars; you don't need to number each bar.
> - Count the beginning of each measure. Do not count any partial measure at the start of a movement. Always check the number of beats in the first bar to be sure.
> - If a measure is divided across a double bar, across a repeat, across a change of clef, key or meter, or from one staff system to the next, be sure not to count it twice. Don't count subdivisions within measures marked by dotted lines.
> - At a repeat with first and second endings, don't count the first ending. In general, count only the last in a set of endings.
> - Count trios, codas or variations in continuity with the preceding printed measures, even if they are not played in that sequence; do not restart from 1. Count tacet parts in trios or variations in accordance with the score.
> - Count each movement individually.

https://ultimatemusictheory.com/incomplete-measure/
> The Anacrusis, Upbeat or first Incomplete Measure will not have a Measure Number. 

http://www.kellydeanhansen.com/MeasureNumbers.html
> Upbeats or other partial measures at the beginning of a section will be included in the time index, but not in measure numbers.  The first complete measure of a movement or song is m. 1.  Upbeats at the beginning of pieces are not counted as measures.

**Comment by sschmidTU** [comment]
Yes, your .musicxml files uses measure number 1 for the pickup and measure number 2 for the first full measure for some reason.
You can use `osmd.EngravingRules.UseXMLMeasureNumbers = false` if you can the measure numbers to be calculated by OSMD and it will use 1 for the first full measure.
<img width="231" alt="image" src="https://user-images.githubusercontent.com/33069673/219205860-548aee54-233d-4832-8d0a-f7b0fb7c8cea.png">
