### ISSUE TITLE
Rendering Apple Logic Pro X MusicXML Files....

### ISSUE THREAD

**Issue by MIDIculous** [opensheetmusicdisplay/opensheetmusicdisplay#133]
Hey guys...I hope someone can help!

I'm building an application that will take an existing MusicXML from say Apple Logic Pro or another DAW and wanted to know if this will interpret any MusicXML or if it has to be in a certain format. 

I have attached the PDF, MusicXML file, and the MIDI file for reference. Can someone please import this MusicXML and tell me how well it converts the information using Logic ProX? 

[Test Files.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/1033210/Test.Files.zip)

**Comment by sebastianhaas** [comment]
I'm not sure I understand your question. Do you want to test your MusicXML with OSMD? If so, just drag and drop it onto the demo page.

http://opensheetmusicdisplay.org/demo/

We don't opt for any special DAW or music typesetter, any MusicXML that complies with the standard should work fine.

**Comment by MIDIculous** [comment]
Yep, works great! Once I get the Transpose thing down I should be set. @sebastianhaas  I'm still waiting for your response on the License for the Transpose.
