### ISSUE TITLE
Pedal sometimes too low

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1330]
![pedal](https://user-images.githubusercontent.com/50280000/218547178-6c611370-5586-4564-b45d-3f454ab13f8e.png)

Source: musicxml downloaded from https://musescore.com/classicman/scores/117606
[Nocturne_Opus_27_No._1_in_C_Minor.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10751656/Nocturne_Opus_27_No._1_in_C_Minor.xml.zip)

**Comment by Guseyn** [comment]
The bigger issue I see here is the slurs. Is it default behaviour?

**Comment by sschmidTU** [comment]
We'll investigate, maybe the bounding box is too large or the bottomline too low.

@Guseyn There are a few edge cases where the slurs calculate an unnecessarily high arc, we are also working on that.
I'm assuming it has something to do with the dynamics and tempo markings (rallent., p, etc).
This doesn't happen very often though.

**Comment by sschmidTU** [comment]
@Guseyn We also use Bezier curves, that's not the problem, the problem is avoiding collisions, setting the points, and calculating the arc of the slur (so as to avoid collisions).

**Comment by sschmidTU** [comment]
@Guseyn We also use Bezier curves, that's not the problem, the problem is avoiding collisions, setting the points, and calculating the arc of the slur (so as to avoid collisions).
But if you think your experience might be helpful, we'd definitely appreciate you sharing it!

**Comment by sschmidTU** [comment]
This particular issue seems to have been solved.
<img width="891" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/e0eab968-f232-4a17-bcfd-98b780196c75">

Not sure what exact change fixed this, must have been one of the fixes in the last 6 months.
