### ISSUE TITLE
 How to get grace note absolute position?

### ISSUE THREAD

**Issue by 59lou** [opensheetmusicdisplay/opensheetmusicdisplay#1331]
when i use GraphicVoiceEnetry.PositionAndShap.absolutePosition to get the abosulte postion for the grace note, but is not the true postion. Do any one have any idea ? Thanks you!

**Comment by sschmidTU** [comment]
Hi, unfortunately it's hard to get the exact position out of Vexflow (we could try if we can get it for the grace note).
You could try getting it via the SVG bounding box, e.g.:
`osmd.cursor.GNotesUnderCursor()[0].getSVGGElement().getBBox()`
(check `osmd.cursor.GNotesUnderCursor()[0].sourceNote.IsGraceNote` to see if it's a grace note)

**Comment by 59lou** [comment]
Just like this. I want to get the grace note position and draw numbered notaion for it. But it is not an easy work.
[Grace_note_exmple](https://github.com/59lou/TempImageStore/blob/main/Grace_note.png?raw=true)

**Comment by 59lou** [comment]
Thanks for your anwser! I want to find the grace note position not just under cursor, but all in the score.

**Comment by sschmidTU** [comment]
there are multiple ways to do this, the simplest may be like this:
```js
osmd.cursor.hide();
osmd.cursor.reset();
do {
const notes = osmd.cursor.GNotesUnderCursor();
for (const note of notes) {
  if (note.sourceNote.IsGraceNote) {
    // show numbered notation
  }
}
osmd.cursor.next();
} while (!osmd.cursor.Iterator.EndReached)
osmd.cursor.reset();
osmd.cursor.show(); // if you want to show the cursor
```

you could also go over all staffentries in osmd.graphic.measureList[i][j] -> staffEntries.

**Comment by 59lou** [comment]
OSMD help me a lot! Thank you very much!
