### ISSUE TITLE
OSMD Matching Algorithm

### ISSUE THREAD

**Issue by pokemon963** [opensheetmusicdisplay/opensheetmusicdisplay#1332]
Hi! I was wondering what algorithm `MusicPartManagerIterator` uses in OSMD when inputting a fraction and measure to jump to on a sheet. In an issue I had before (linked here: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1297#issuecomment-1396311121), I have a text file in which each row has a label in the sheet and a time stamp of where that is played in the corresponding audio. However, the labels from this text file do not always match the labels/fractions in OSMD (i.e. could be 3+3/4 in OSMD but 3+5/8 in the text file) and/or sometimes skip some labels in the sheet (such as breaks with no note/sound). Hence, I am looking for a matching algorithm to be able to get a label from OSMD and match it to the corresponding label in my text file to get the corresponding time stamp.

Here is an example of what the text file looks like:

1+0/1	1.024
1+1/8	1.520
1+1/4	1.680
1+3/8	2.048
1+1/2	2.480
1+5/8	2.736
2+0/1	3.088

**Comment by sschmidTU** [comment]
I don't understand your text file's system. First of all 0/1 is 0, so you can just write 0 or nothing.
Secondly, 1/4 is twice as big as 1/8, yet 1.680 is not much further than 1.520 (1+1/8) when compared to 1.024 (1+0/1).

OSMD's system is quite simple, you start at 0 (first note in the sheet), and when a 1/4 note has passed, you add 1/4 to the timestamp.

the "x+" number at the start, as I said before, is relative to the time signature. So in a 6/8 time signature, a 6/8 measure is only 6/8 long, not 1/1 or 8/8.
We've discussed this in #1297, so unfortunately I'm not sure what I should add.

**Comment by pokemon963** [comment]
Yeah, you are right that it is the measure number.

I guess what I am asking about is the matching algorithm that OSMD uses. Because OSMD labels each note with a fraction and measure similar to the text file using `osmd.cursor.iterator.currentVerticalContainerInMeasureTimestamp` and `osmd.cursor.iterator.currentMeasureIndex`. However, some of the labels given by `osmd.cursor.iterator.currentVerticalContainerInMeasureTimestamp` are not always the same with the text file due to the software used to produce the text file. For example, if OSMD says one note is 5+3/4, the text file might label that same note as 5+5/8. However, I have noticed that in OSMD if I plug in an incorrect label/fraction using the `MusicPartManagerIterator `and no such note exists, it is able to match it to the closest possible match. So with the example I gave, if I plugged in 5+5/8, the cursor would match it and highlight 5+3/4 since 5+5/8 does not exist in the sheet for OSMD. Hence, I am wondering what algorithm is used since sometimes I need it the other way around where I get the label from OSMD and need to input it and find the corresponding label/match in the text file.

**Comment by sschmidTU** [comment]
It's the algorithm as I described above:
> OSMD's system is quite simple, you start at 0 (first note in the sheet), and when a 1/4 note has passed, you add 1/4 to the timestamp.

One issue may be that for OSMD, the first note in a 6/8 measure starts at 0/8, not at 1/8, so if there are 6 8ths in the measure, the 5th one would be at 4/8, not 5/8.

**Comment by sschmidTU** [comment]
Feel free to continue asking questions, and I'll try my best to answer, but this is a custom algorithm for your project that's really your project's issue, not OSMD's, as probably noone else will use it, so I'm closing this for now.
