### ISSUE TITLE
Repeat sign consumed by multimeasure rest

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1333]
>By the way, I just fixed repetitions being consumed by a multiple rest measure, so you can enable multiple rests again (when the next release is out).

_Originally posted by @sschmidTU in https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/901#issuecomment-862390110_

This is no longer working.

test-file: [repeat-test.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10752499/repeat-test.zip)
relevant musicxml excerpt:
```xml
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        <repeat direction="backward"/>
        </barline>
```
osmd-version: 1.7.4
local-test:
![local_test](https://user-images.githubusercontent.com/50280000/219278516-b4d15475-6008-4e25-864e-ac23c0902bc7.png)
web-test:
![web_test](https://user-images.githubusercontent.com/50280000/219278553-4accd67b-f4f0-494f-8f55-acca841ebcfd.png)
musescore-test:
![musescore](https://user-images.githubusercontent.com/50280000/219278860-e46b59d3-8c7c-48ae-b6d3-258dc197f929.png)

**Comment by sschmidTU** [comment]
Fixed.

Also works with 3 multiple rest measures:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/33069673/219518395-597197be-e3ff-4792-a4fd-3cc8b8f205b0.png">

test samples for 2 and 3 multiple rest measures added.
[test_multiple_rest_measures_repeat_samples.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10762068/test_multiple_rest_measures_repeat_samples.zip)
