### ISSUE TITLE
isReducedToMultiRest error

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1334]
When I load this musicxml file: [Beethoven__Symphony_No._9__Op._125-Clarinetto_1_in_C_(Clarinet).zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10752936/Beethoven__Symphony_No._9__Op._125-Clarinetto_1_in_C_.Clarinet.zip) in local demo (most recent 1.7.4 development version of osmd) and resize the page, the sheet music doesn't render and an error appears in console:
![image](https://user-images.githubusercontent.com/50280000/219289339-13af074c-4fc4-4a83-9983-353bfb2b233f.png)

**Comment by sschmidTU** [comment]
Doesn't happen for me, but I've added a null check for safety.

**Comment by michaelcchu** [comment]
Thanks! That fixed it for me.
