### ISSUE TITLE
Should cursor highlight grace note?

### ISSUE THREAD

**Issue by michaelcchu** [opensheetmusicdisplay/opensheetmusicdisplay#1337]
Currently, the cursor doesn't highlight grace notes. Do you think it should highlight grace notes? Here is a test file: [grace_note.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10772794/grace_note.zip).

**Comment by sschmidTU** [comment]
Grace notes don't have their own playback positions, that's why they're skipped.

**Comment by sschmidTU** [comment]
This is also kind of a technical requirement for how our audio player (which is currently in early access for sponsors) processes playback positions, so this is unfortunately non-negotiable.

**Comment by michaelcchu** [comment]
Ok, sounds good; thanks for letting me know! Either way (highlight or no-highlight) is fine for me; I was just curious to consider the possibilities. Good luck with the audio player project; that sounds cool! :)
