### ISSUE TITLE
Automatic Scroll for Cursor

### ISSUE THREAD

**Issue by pokemon963** [opensheetmusicdisplay/opensheetmusicdisplay#1343]
Hi, I want to have an automatic scroll that follows the cursor. I saw the answer from https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/943#issue-789151877. However, it only works when I use osmd.cursor.next. However, when I am advancing the cursor as my audio is playing (using MusicPartManagerIterator), it would only scroll the cursor into view when I pause the audio and I am not sure why.

This is a segment of my code when advancing my cursor when the audio is playing:

```
if ((audioTime >= textTime) && (audioTime < nextTextTime)) {
              console.log(textfile_list[index][1]);
              // console.log(audioTime);

              const targetFraction = new opensheetmusicdisplay.Fraction((measure - 1) * score_numerator, score_denominator).Add(new opensheetmusicdisplay.Fraction(numerator, denominator));
              // const targetFraction = new opensheetmusicdisplay.Fraction((denominator * (measure - 1)) + numerator, denominator); // computes for position
              osmd.cursor.iterator = new opensheetmusicdisplay.MusicPartManagerIterator(osmd.Sheet, targetFraction);
              osmd.cursor.update(); // updates cursor
            }
```

**Comment by sschmidTU** [comment]
Maybe your audio playing code is blocking execution (doesn't return)? I don't know, impossible to say from this code snippet, that's not what's causing the issue.
Or maybe the if condition doesn't trigger?
I would try debugging into it.

**Comment by pokemon963** [comment]
Thanks! I will try that! May I ask if there is another method to scroll or just to get the cursor in the center of the div/screen?

**Comment by sschmidTU** [comment]
Not in OSMD, but you can try to use one yourself, e.g. the scrollIntoView() method which the DOM provides via HTML Element.
<img width="824" alt="image" src="https://user-images.githubusercontent.com/33069673/224184222-30336473-2dbd-4529-ab2b-0cee60eb5d6b.png">
