### ISSUE TITLE
Is there a way to set a fixed measure width for all measures?

### ISSUE THREAD

**Issue by ZeljkoRacki** [opensheetmusicdisplay/opensheetmusicdisplay#1344]
I'm trying to generate random sequences of notes but I often get these weird crowded notes
<img width="314" alt="image" src="https://user-images.githubusercontent.com/90096287/224678580-240223d7-d039-47f5-beab-b23fdf41c309.png">

Is there a way to set one large fixed measure width for all the measures and display the notes accordingly.

**Comment by sschmidTU** [comment]
FixedMeasureWidth option now available (in next release), see #1314.
