### ISSUE TITLE
Changing color of cursor

### ISSUE THREAD

**Issue by pokemon963** [opensheetmusicdisplay/opensheetmusicdisplay#1346]
Hi, I am trying to change the color of the cursor. However, the solution at https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/556#issue-476124867 did not work for me. I got this error: Uncaught DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('undefined') could not be parsed as a color.

**Comment by sschmidTU** [comment]
@pokemon963 great! would you mind sharing the fix?

**Comment by pokemon963** [comment]
osmd.cursorsOptions[0].color = "#ffffff"; // or any color you want
osmd.render();
