### ISSUE TITLE
Fingering Below Single Stave

### ISSUE THREAD

**Issue by chbauman** [opensheetmusicdisplay/opensheetmusicdisplay#1348]
Currently, setting the option `this.rules.FingeringPosition = 1` (`fingeringPosition = "below"` in options) does not work if there is a single stave, fingering markings will always be placed on top. 

The reason is that in `calculateFingerings()`, this option is always overwritten to "Above" because `measure.isUpperStaffOfInstrument()` returns true.

**Comment by sschmidTU** [comment]
Fixed in #1349.
Thanks for the report and fix!
