### ISSUE TITLE
Getting position of cursor/knowing when cursor jump to other line

### ISSUE THREAD

**Issue by pokemon963** [opensheetmusicdisplay/opensheetmusicdisplay#1351]
Hi! I want to be able to get the position of the cursor like relative to the line it is in. Here is a picture of an example:

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/84149276/225986835-6b548e71-025e-4da1-b50e-ef3274ee4905.png">

So, this sheet in particular has two lines (like two lines of measures) and right now, the cursor is on the first line. I want to know when it jumps from the line it is on to another/to get the position of the cursor to determine if it has changed lines.

I have tried using this: `osmd.cursor.cursorElement.getBoundingClientRect().top`, however, each note has its own position and this position value is not the same of notes in the same measure line. Any assistance on this would be greatly appreciated!

**Comment by sschmidTU** [comment]
`osmd.cursor.GNotesUnderCursor()[0].parentVoiceEntry.parentStaffEntry.parentMeasure.parentStaffLine.parentMusicSystem.id`
will change to 1 on the 2nd "line" etc.

What you (and others) call a "line" is a system in sheet music terms, or MusicSystem in OSMD.

**Comment by pokemon963** [comment]
Thank you so much! Also, can I ask, is there a way to get the position of the box? I want to be able to scroll down to the "line" when it changes. Hence, I need to know the height difference between the top of the first "line" and the bottom of the second "line"

**Comment by sschmidTU** [comment]
I don't fully understand your descriptions, but you should be able to take the difference between the `getBoundingClientRect().top` between first line and second line etc.
