### ISSUE TITLE
some fingering is not display

### ISSUE THREAD

**Issue by 59lou** [opensheetmusicdisplay/opensheetmusicdisplay#1352]
i have added all fingerings for notes in the musicxml file, when i open use OSMD, some fingering not display.  i open in museScore3, all fingerings can be display.
![Open_OSMD](https://github.com/59lou/TempImageStore/blob/main/open_osmd.png?raw=true)
![Open_MuseScore3](https://github.com/59lou/TempImageStore/blob/main/open_museScore3.png?raw=true)
[origin_musicxml_file](https://github.com/59lou/TempImageStore/blob/cffcb8b7170d8e75a73097e1f6a0e0c23a9c474e/123.xml)

**Comment by sschmidTU** [comment]
This seems fixed now, not sure by which change.
<img width="194" alt="image" src="https://user-images.githubusercontent.com/33069673/227324208-beda966a-d4f9-4ecb-8b7b-db34ac0490df.png">

I first thought it depended on the aspect ratio of the window, but I tried various sizes, and it didn't happen.
It does still happen in our public demo:
https://opensheetmusicdisplay.github.io/demo/

<img width="178" alt="image" src="https://user-images.githubusercontent.com/33069673/227324388-cec41a29-8ea3-44da-be5f-30ebad2818d9.png">

So please either try our develop branch, or wait until we release the new version, and see if the problem persists.

**Comment by 59lou** [comment]
Thanks a lot!

**Comment by sschmidTU** [comment]
@59lou OSMD 1.7.5 is released, including this fix!

**Comment by 59lou** [comment]
Thank you very much !
