### ISSUE TITLE
Help needed to understand this code function meaning

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1358]
Hello.

I am working to implement needed modifications to the code according to [this issue](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1347), but I can't make sense of this function inside the MultiTempoExpression.ts file:

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/19e417bab4acfe1bdcee667d3da8ad95da82195e/src/MusicalScore/VoiceData/Expressions/MultiTempoExpression.ts#L110

That function, I guess, is supposed to check for duplicate tempo expressions, but it doesn't do anything since the "expression" variable (an array) is reset every time the [addExpression](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/19e417bab4acfe1bdcee667d3da8ad95da82195e/src/MusicalScore/VoiceData/Expressions/MultiTempoExpression.ts#L83) function is called so that subsequent tempo added expressions cannot be compared to the previously added ones.

Am I correct or am I missing something? Can the person who wrote that code explain how that works to me? I'd have a solution, but before proceeding, I'd like to understand what's the meaning of all that. According to my tests, the checkIfAlreadyExists function ([line 110](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/19e417bab4acfe1bdcee667d3da8ad95da82195e/src/MusicalScore/VoiceData/Expressions/MultiTempoExpression.ts#L110)) never returns true, because of that problem.

Furthermore, that function seems to be limited and constraining due to the fact it is just comparing tempo expressions "labels" and not their position, as it should (according to my own reasoning).

I am eager to know what's behind that code because after spending hours trying to figure it out myself, I still can't make sense of it.

Thank you!

**Comment by sschmidTU** [comment]
I think you misread something. addExpression() stores the expression in this.expressions, and checkIfAlreadyExists checks if it exists in this.expressions. this.expressions is not reset.

> Furthermore, that function seems to be limited and constraining due to the fact it is just comparing tempo expressions "labels" and not their position, as it should (according to my own reasoning).

No, a MultiTempoExpression is at one single unambiguous timestamp (this.timestamp), so the expressions it is comparing are at the same timestamp/position.

**Comment by fablau** [comment]
I am sorry, but what you say doesn't correspond to what I see.

I have modified the [addExpression()](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/19e417bab4acfe1bdcee667d3da8ad95da82195e/src/MusicalScore/VoiceData/Expressions/MultiTempoExpression.ts#L83) and [checkIfAlreadyExists()](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/19e417bab4acfe1bdcee667d3da8ad95da82195e/src/MusicalScore/VoiceData/Expressions/MultiTempoExpression.ts#L110) functions for logging purposes as follows:

```
public addExpression(abstractTempoExpression: AbstractTempoExpression, prefix: string): void {

      console.log("OUT: addExpression called");
      
      if (this.checkIfAlreadyExists(abstractTempoExpression)) {
          console.log("OUT: Already exists");
          return;
      }

      if (abstractTempoExpression instanceof InstantaneousTempoExpression) {
          this.instantaneousTempo = <InstantaneousTempoExpression>abstractTempoExpression;
      } else if (abstractTempoExpression instanceof ContinuousTempoExpression) {
          this.continuousTempo = <ContinuousTempoExpression>abstractTempoExpression;
      }
      const tempoExpressionEntry: TempoExpressionEntry = new TempoExpressionEntry();
      tempoExpressionEntry.prefix = prefix;
      tempoExpressionEntry.Expression = abstractTempoExpression;
      tempoExpressionEntry.label = abstractTempoExpression.Label;
      this.expressions.push(tempoExpressionEntry);

      
  }
```

```
private checkIfAlreadyExists(abstractTempoExpression: AbstractTempoExpression ): boolean {
      console.log("OUT: inside checkIfAlreadyExists")

      console.log("OUT: expressions length: " + this.expressions.length);
      console.log("OUT: expressions contents: " + JSON.stringify(this.expressions));

      console.log("OUT: abstractTempoExpression label: " + abstractTempoExpression.Label);

      for (const entry of this.expressions) {
          console.log("OUT: Inside loop!")
          console.log("OUT: Label: " + entry.label);
          if (entry.label === abstractTempoExpression.Label) {
              return true;
          }
      }

      console.log("OUT: return false from checkIfAlreadyExist")

      return false;
  }
```

I have tested it with the attached MusicXML example, and here is what I get in the console output:

![image](https://user-images.githubusercontent.com/10005316/228635686-26c78468-0be2-456d-8d57-93846cf524df.png)

As you can see, checkIfAlreadyExists() always return false, and the contents length of expressions is always zero. The inside "for" loop never gets executed.

Furthermore, if you look at [line 112](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/19e417bab4acfe1bdcee667d3da8ad95da82195e/src/MusicalScore/VoiceData/Expressions/MultiTempoExpression.ts#L112) you can see that checkIfAlreadyExists() compares just the labels, that are two strings:

```
if (entry.label === abstractTempoExpression.Label) {
    return true;
}
```

What am I missing?

**Comment by sschmidTU** [comment]
I'm not completely sure what's going on here yet, would have to look more in detail, but you still have to explain why you think that addExpression() resets this.expressions (it doesn't).

My guess is that multiple tempo expressions are created at different timestamps, or maybe even at the same timestamp, only containing a single expression in this.expressions in the end, so of course there are no other expressions in this.expressions to compare with.

**Comment by sschmidTU** [comment]
So in short, I think your sample just doesn't trigger the duplicate check for some reason
(note I edited my comment above a couple times)

**Comment by sschmidTU** [comment]
This is also a prominent problem in other samples, like Gounod - Meditation:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/33069673/228657236-4e70c878-d1c2-4410-957e-107513a0acc5.png">

We probably just need to check for duplicates across MultiTempoExpressions or something.

If it would cost you too much time to go through and fix the code for this (very understandable, OSMD is complex), I can also try to fix this at some point, as it's an important issue anyways, and then we can move on and add your option.
Might just be a few days until I have time for this.

**Comment by fablau** [comment]
Thanks for taking the time to respond and for looking into this. I can certainly wait for you to understand what's going on; I am not in a hurry ;)

To answer your question about why I think that array gets reset every time, I have no idea, I am still trying to figure it out, but you can see from my logging above the length of "expressions" is always zero right inside the checkIfAlreadyExists() function. If the array was filled with something added previously, its length should be more than that.

And how do you explain the "label" comparison for duplicate checking? I don't see a comparison at the timestamp level there.

I don't need an answer today, but maybe I can help to understand what's going on and how to improve the code ;)

Thanks again!

**Comment by fablau** [comment]
Got it. Thank you for explaining! As you said, it'll take some time, but I'll grasp the code sooner or later!

**Comment by fablau** [comment]
I found [line 611](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/19e417bab4acfe1bdcee667d3da8ad95da82195e/src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts#L611) of ExptessionReader.ts being where the MultiTempoExpression() class gest re-initialized every time, hence the reset of all variables inside it.

Just as a reference. I'll keep studying the code ;)

**Comment by sschmidTU** [comment]
Closing for now, feel free to keep commenting.
