### ISSUE TITLE
Non-traditional key signatures are not rendered

### ISSUE THREAD

**Issue by PolariTOON** [opensheetmusicdisplay/opensheetmusicdisplay#1360]
Key signatures that do not follow the circle of fifths are not rendered.

Here is how [this sample](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11112911/non_traditional_key_signature.zip) renders in MuseScore 4:
![image](https://user-images.githubusercontent.com/36267812/228877264-1676b804-39ca-46c0-8632-4ed480100525.png)
And on the public demo for OSMD:
![image](https://user-images.githubusercontent.com/36267812/228877477-ccd6740e-1f78-4715-bc07-dd1c43d2e70c.png)

**Comment by sschmidTU** [comment]
Yes, they are unfortunately not supported, as our renderer library Vexflow doesn't support them. Would be very hard to implement.
