### ISSUE TITLE
AJAX error with large MusicXML files

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1362]
I am sorry to post another issue in such a short time, but today I was working with large MusicXML files (over 3MB), and I see that OSMD has problems with them. I get a "Could not retrieve requested URL 0" error coming from this line of the source code:

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/9b4a2fae7f9472915fecf3b54fc8cb45b43c4b4a/src/OpenSheetMusicDisplay/AJAX.ts#L31

I am working on my own web implementation (your online DEMO can display it without issues), which includes this simple JS call:

```
osmd
.load("01Beet5th.musicxml")
.then(
		function() {
	
		         //Zoom...
		        osmd.Zoom = 0.9;
		        console.log("Start rendering...");
	                goRender();
                }
);
```

You can test it here:

https://www.virtualsheetmusic.com/test/osmd/LargeFilesTest.html

I tried to figure that out myself, but I don't understand what's the problem. I see the script doesn't go over the "then" function above. Any ideas?

I am attaching one of those files that is giving me trouble.

[01Beet5th.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11114216/01Beet5th.musicxml.zip)

**Comment by sschmidTU** [comment]
And it works with smaller files? The URL looks sus, but if it works with smaller files, okay.

You can always just load the file yourself and pass the XML content as string to load().

Otherwise, there might be some improvements in our loading code necessary, but a 3MB file probably takes forever to render and looks bad anyways.

**Comment by fablau** [comment]
Thank you for your reply, but why did you say that "the URL looks sus"? I am the CEO of virtualsheetmusic.com. What's "sus" about it? ;)

Anyway, yes, it works fine with small files. Here it is the same code opening a smaller file (less than 1MB):

https://www.virtualsheetmusic.com/test/osmd/LargeFilesTest2.html

About the file, I don't know what version of MuseScore you have, but I can open it perfectly in Musescore 4.0.1 for Mac.

Also, I have exported it from Sibelius Ultimate with the latest Dolet 8 plug-in, which is the most reliable way to export MusicXML files from Sibelius.

We plan to use your system on the VSM repertoire, which includes almost 3,000 classical music titles. It is pretty common in such kind of repertoire to have MusicXML files larger than 2-3MB, and I got issues with that kind of size as well.

I tested the same large file inside NoteFlight, and it opened without issues. I strongly think your system should be able to handle that kind of file size, and I don't see any reason not to.

And, of course, I can do my own loading procedure... but why miss the opportunity to improve your system on that as well?

Thanks again.

**Comment by sschmidTU** [comment]
Oh, sorry, that's a misunderstanding, I didn't mean the web URL, I meant the URL in `osmd.load()`:
`osmd
.load("01Beet5th.musicxml")`

I'm guessing you're serving the musicxml files from the root directory in that demo. I would have expected the files to be in a subdirectory. As long as serving the files works that should be fine.

Yes, would be nice to look into improving the AJAX loading for extremely large scores.

Just giving you a warning though, a 39-page orchestral score will take several seconds to render, maybe even more than a minute. Try for yourself with the string.

**Comment by fablau** [comment]
Thank you Simon for clarifying! And sorry on my part for the misunderstanding ;)

And yes, that file in the same directory of the script.

It's great to know you are willing to allow larger files. If I can help with that, please, let me know. I am still studying the code, and it'll take some time on my part to have a complete grasp of it.

As for the time to load that large score (which is actually one of the largest ones we have, so it is an "extreme" example), I just tested it with your [DEMO page](https://opensheetmusicdisplay.github.io/demo/) and took 10 seconds on my MacBook Pro M1 Max. I am sure that slower machines would take longer, but as I said, that's an extreme situation (at least in the context of our own repertoire).

Thank you again!

All the best,

Fab

**Comment by sschmidTU** [comment]
Great! Maybe you want to protect users from loading scores that are too large, for example you could only load the first 50 or so measures first (see `drawFromMeasureNumber` and `drawUpToMeasureNumber` options).

The AJAX/loading code is pretty simple and short, so if you could fix it for large files, that would be great!

**Comment by fablau** [comment]
That's a great idea, I didn't think about that. Ok, I'll do my best!

**Comment by fablau** [comment]
Stupid me! Actually, I could just fix the problem by setting the global loadUrlTimeout to more than the default of 5000 milliseconds. Let's say though that the ajax() function should return the correct error (timeout) and for some reason didn't return it correctly. It returned the generic "Could not retrieve requested URL".

Anyway, problem solved.

**Comment by sschmidTU** [comment]
Great. We just return the error that Ajax returns. I'm also not sure that technically it's always possible to distinguish between a timeout and a different error (maybe Ajax should be able to do it).
