### ISSUE TITLE
With regard to the numerical representation in Transpose, is there a relevant comparison table

### ISSUE THREAD

**Issue by AlanPaine** [opensheetmusicdisplay/opensheetmusicdisplay#1364]
With regard to the numerical representation in Transpose, is there a relevant comparison table

**Comment by sschmidTU** [comment]
what?
In Transpose, 1 = 1 halftone up.

**Comment by sschmidTU** [comment]
I don't understand what you want to show. As I said, 1 = transposing 1 halftone upwards.
