### ISSUE TITLE
Repeat counter wrong

### ISSUE THREAD

**Issue by johansmolinski** [opensheetmusicdisplay/opensheetmusicdisplay#1367]
Sorry if I am using the wrong wording here, but I have a sheet where there is a repeat counter telling what to play the first and second time. The first one should be marked 1 and the second 2. Osmd marks both with 1. Attaching the mxl file.

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/45559525/231991784-3b6d573d-64eb-41c6-ba96-d9ca4ba3a7fa.png">

Look at bar 9.

[fe61.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11230739/fe61.mxl.zip)

**Comment by sschmidTU** [comment]
Fixed.
<img width="376" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/3f9697eb-d27c-4bb6-b0e7-3a394a7d28d7">

Finale has some questionable MusicXML syntax here, but it seems like the MusicXML spec does allow the volta text to be overwritten with the ending node value:
"The element text is used when the text displayed in the ending is different than what appears in the number attribute."
https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/ending/
I'm assuming they mean e.g. the `2` in `<ending number="1">2</ending>`.

The truly questionable part in the Finale MusicXML file/syntax is that they duplicate the ending node, one at the start of measure barline, one at the end of measure barline, and only the one at the start has `print-objecf="no"`. So I'm assuming Finale wanted to not show the voltas, but forgot to put that attribute at the end barline instead, and/or accidentally duplicated the `<ending>` node. But maybe they do want to show it, which Musescore does as well (noting that it's not a valid MusicXML file), and we do too.
