### ISSUE TITLE
Preprocessing MusicXML files + unfold repeat signs

### ISSUE THREAD

**Issue by joaocc** [opensheetmusicdisplay/opensheetmusicdisplay#137]
When a MusicXML is opened, it would be interesting to be able to specify some pre-processings.

A possible approach could be to define a simplified pipeline that could receive one (or more) functions that could transform/modify the content.

A commonly used and useful set of pre-processing functions could be available (see below)
Eg: When the file has a "repeat sign", duplicate the paragraph and remove the "repeat sign".

**Comment by sebastianhaas** [comment]
Very interesting topic, thanks for the input. I would love to have something like a pipeline in OSMD. This is probably very close to #1 #16 etc., a plugin infrastructure that allows plugins to hook into the reading/parsing/layouting/rendering steps and alter OSMD's behaviour.

**Comment by joaocc** [comment]
We would love to fund this and other features/improvements of osmd (see #136) but it's not been easy to get in touch with contributors...
