### ISSUE TITLE
How does OSMD represent MusicXML data

### ISSUE THREAD

**Issue by pokemon963** [opensheetmusicdisplay/opensheetmusicdisplay#1370]
Hi! I am trying to understand how OSMD represents the data from MusicXML sheet music and cannot find any documentation on that. To my understanding, OSMD represents the data using an internal data structure that is tree-like, in which it is composed of a series objects. And those objects contain a series of more objects that contain information on corresponding attributes of the sheet.

Any information regarding this would help or just any assurance if my understanding of OSMD is correct!

**Comment by sschmidTU** [comment]
You say you can't find documentation, but have you read the wiki? A lot of the OSMD internals are explained there.
If you want to know how OSMD works, you should read the wiki, e.g. "How OSMD processes sheet music".
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki

OSMD transforms the XML data into its own tree-like structure, yes.
The structure is in MusicSheet for the pure logical data, and in GraphicalMusicSheet for the graphical adaptation of it. (and then there's VexFlow classes that adapt our neutral graphical objects to Vexflow's structures).

**Comment by pokemon963** [comment]
Thank you so much!
