### ISSUE TITLE
loading sample songs error 

### ISSUE THREAD

**Issue by Sihooni** [opensheetmusicdisplay/opensheetmusicdisplay#1375]
https://courageous-palmier-383002.netlify.app/

Hello, i just builded the demo without modifying any, but it does not work at loading sample songs unlike in local. 
Anyone who had same problem? How do i fix this? Thanks

(Also, my goal is to add some my musicxml files in the sample) #

**Comment by Sihooni** [comment]
> It looks like it can't load the musicxml file you're trying to load. <img alt="image" width="315" src="https://user-images.githubusercontent.com/33069673/238731820-3f4d8564-3b11-457c-a742-769e63bd95c4.png">
> 
> Probably an issue with the path to load the file, file access permissions, server settings, and so on. It looks like javascript can't load from the URL to the musicxml file you're giving to OSMD. You can also try loading the file yourself, then passing the XML file content as a string to osmd.load() instead of the URL.

Thank you for reply!  passing the XML file content as a string to osmd.load() instead of the URL would be easier way to upload my songs? they are more than 6000songs! what would be the easy way to fix this and add my songs?

**Comment by sschmidTU** [comment]
If you want to load your songs, they need to be uploaded somewhere, ideally on your server, yes.
If you just use it for yourself, you can also drag and drop the files into the demo instead.

**Comment by Sihooni** [comment]
I just added some songs and it works perfect in local, but it still doesnt load the songs in webserver. How do i fix this?? As I just started to making a website for hobby, i am struggling. anyway, thank you so much

**Comment by sschmidTU** [comment]
You need to host the files on your server.
This is the URL OSMD is trying to load:
`https://courageous-palmier-383002.netlify.app/Beethoven_AnDieFerneGeliebte.xml`
You can try this in your browser, it doesn't work there, so it also won't work for OSMD.

With how it's currently set up, you would need to add all the .xml (and .musicxml, .mxl) files to the home directory of your app.
Better would be to add a folder `samples/` or something and put all the music files in there, but then you would also need to change the code of the demo to load the files from there, e.g.:
`https://courageous-palmier-383002.netlify.app/samples/Beethoven_AnDieFerneGeliebte.xml`

**Comment by Sihooni** [comment]
Do i have to  change the code in webpack.common.js?or package js or both?? where should I make changes?

**Comment by sschmidTU** [comment]
in demo/index.js.
In line 11, set `var sampleFolder = "samples/",`.
If you have new files that you want to load from the drop down menu, you need to add them in the same format in the `samples` object below.
then `npm run build` again.

Of course, if you have 6000 samples, the most appropriate way would be to write code to load the file names for you, and probably not use a simple drop-down list.

**Comment by Sihooni** [comment]
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/133592177/18b63b02-0814-48cb-8b9f-bf03954ae63d)

I made "samples" folder like demo/sample  and  modified code

/*jslint browser:true */
(function () {
    "use strict";
    var openSheetMusicDisplay;
    var sampleFolder = "samples/",
        samples = {
            "Beethoven, L.v. - An die ferne Geliebte": "Beethoven_AnDieFerneGeliebte.xml",
            "Clementi, M. - Sonatina Op.36 No.1 Pt.1": "MuzioClementi_SonatinaOpus36No1_Part1.xml",
            "Clementi, M. - Sonatina Op.36 No.1 Pt.2": "MuzioClemen
         


but it is still not working and shows the error above. should I change the codes in other js files like package.js or webpack?

(I am trying to make a search dropdown with select2)

**Comment by sschmidTU** [comment]
Your website still can't serve the files. I don't know what your website/server setup is, but you need to make this URL work:
`https://courageous-palmier-383002.netlify.app/samples/Beethoven_AnDieFerneGeliebte.xml`

**Comment by Sihooni** [comment]
Do you know what functions are loading the samples? I really appreciate your help

**Comment by sschmidTU** [comment]
`openSheetMusicDisplay.load(str)` in index.js,
load() in OpenSheetMusicDisplay.ts

**Comment by Sihooni** [comment]
I am trying to figure out how to load samples in remote server (https://courageous-palmier-383002.netlify.), but for me, it is too complex to understand how it works. I am curious how it could not work but works perfectly in local. Also, it seems that sampleFolder should remain "" to make it work at least in local.

**Comment by sschmidTU** [comment]
I'll close this for now, as it's a server issue, not an OSMD issue.
But if you have any further questions, feel free to ask.
You have to figure out how to make your server/website host files from a URL.
