### ISSUE TITLE
Cursor "next" method not consistent

### ISSUE THREAD

**Issue by joaocc** [opensheetmusicdisplay/opensheetmusicdisplay#138]
In some MusicXML files, trying to navigate via the "next" method, seems to jump back a few notes and then jumps forth to continue normally, with no visible reason.
Anyone found this behaviour?
Thanks

**Comment by sebastianhaas** [comment]
Would you mind giving an example in which scores you encounter these issues? Thanks

**Comment by joaocc** [comment]
This one is a good example.
https://downloads2.makemusic.com/musicxml/DebuMandSample.xml
Thx

**Comment by matt-uib** [comment]
I had a look at the cursor issue and it originates from beams with notes in two staff lines. The beams are not correctly rendered and also the x-layout of the notes is not correct. As this is not so often used, we will fix it at a later stage.
