### ISSUE TITLE
trouble making a clone website

### ISSUE THREAD

**Issue by Sihooni** [opensheetmusicdisplay/opensheetmusicdisplay#1380]
I forked the OSMD website to my repository and created a web page with github page.

https://sihooni.github.io/opensheetmusicdisplay/
https://sihooni.github.io/opensheetmusicdisplay/demo

However, neither page shows the demo OSMD website that works properly.
In https://sihooni.github.io/opensheetmusicdisplay/demo here, when i invested with chrome developer, I can found some objectives.
However, It is invisible and not working at all. What is the problem? 
Also, What branch should I select when building?
(my final purpose is to add some xml files in sample dropdown, but i want to try this after clone website is working)

**Comment by Sihooni** [comment]
Also, What branch should I select when building?

**Comment by sschmidTU** [comment]
Copy the demo.min.js from the OSMD build into the /demo folder

**Comment by sschmidTU** [comment]
Also, have you activated Github Pages?
Settings -> Pages
<img width="852" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/969059e9-b726-43c8-b2d5-12a583726881">

**Comment by sschmidTU** [comment]
I think you've forked the wrong repository.
You need to fork the demo:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay.github.io
You forked OSMD.

**Comment by Sihooni** [comment]
Thank you so much I solved it!

**Comment by Sihooni** [comment]
I want to ask just another last thing. How do i use transposer in this demo website? I cannot find it.
Thank you so much

**Comment by sschmidTU** [comment]
There's no button for it in the public demo yet, you can do it using the console.
`osmd.Sheet.Transpose = 1` etc
you'd have to copy the button from the developer demo (npm start)
