### ISSUE TITLE
When zoom is changed, PositionAndShape is not updated.

### ISSUE THREAD

**Issue by sty1103** [opensheetmusicdisplay/opensheetmusicdisplay#1381]
I get the position and size of measure and staff from PositionAndShape, and use it to create a control pannel on the score.

<img width="598" alt="Screenshot 2023-05-19 at 1 23 46 AM" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/31470574/f86f361f-9c35-43d6-b723-2f67b7441d59">

When zoom is set to 1, it works fine.

![Screenshot 2023-05-19 at 1 15 31 AM](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/31470574/f5b4a32a-aa34-4820-8dac-4b0f02983cb6)

But when I change the value of zoom, it returns the position and size when zoom was 1.

(zoom is set to 0.75)
![Screenshot 2023-05-19 at 1 26 07 AM](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/31470574/ed1eeb4a-cdd6-495d-96c1-f6eead6e44da)

Is there a way to get the position and size of the zoomed measure and staff?

**Comment by sschmidTU** [comment]
OSMD coordinates/units are designed not to change with zoom level. A OSMD unit (1) is always the distance between two lines of a 5-line staff. (e.g. E to G)

Don't you get the right pixel coordinates by multiplying 10 with the zoom (e.g. 0.75)?

Also see these methods for coordinate conversions:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/504#issuecomment-778674805

**Comment by sty1103** [comment]
As you said, One more multiplication by 0.75 fixed it! Thank you

...
const top = staff.PositionAndShape.AbsolutePosition.y * 10 * 0.75
...

**Comment by sschmidTU** [comment]
Great! I would multiply by this.zoom (or osmd.zoom) instead though, as you need to multiply by the zoom, so if the zoom changes to 0.8 or 1, you need to multiply by 0.8 or 1.
