### ISSUE TITLE
Ignore repeated symbols in music

### ISSUE THREAD

**Issue by AlanPaine** [opensheetmusicdisplay/opensheetmusicdisplay#1387]
So if I call moveToNext, how do I ignore repeated notation in music and skip it

**Comment by sschmidTU** [comment]
Check `osmd.cursor.NotesUnderCursor()[0].sourceMeasure.endingBarStyleEnum` or `osmd.cursor.NotesUnderCursor()[0].sourceMeasure.endingBarStyleXml̀`.

Please explain your questions better, it's almost impossible to understand what you want. I know English is not your first language, but please use more words and longer descriptions in that case to improve understandability.
