### ISSUE TITLE
Svg file id generation rules

### ISSUE THREAD

**Issue by miller06** [opensheetmusicdisplay/opensheetmusicdisplay#1388]
Hello, may I ask if the ID generation rule id="vf-auto1396" can be seen in the folder? I need to understand the principle. Thank you

**Comment by sschmidTU** [comment]
Vexflow does that.
https://github.com/0xfe/vexflow/blob/430f607053f7caa24cb96feac722c1b5fb821b06/src/element.js#L13

It's just a unique ID, there isn't a big principle behind it.
