### ISSUE TITLE
How can I get the height of a measure?

### ISSUE THREAD

**Issue by sty1103** [opensheetmusicdisplay/opensheetmusicdisplay#1389]
I found out that the height of the measure in the music sheet is not fixed,
and I'm having a hard time figuring out the height of each measure.

![Screenshot 2023-05-29 at 2 41 26 PM](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/31470574/6b005cc9-1f05-4c70-9aa7-33df7416e13c)

In now, I'm using a fixed value of 41 for height like the code below.

<img width="769" alt="Screenshot 2023-05-29 at 2 50 59 PM" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/31470574/898b3576-d01e-44f9-9369-e1ee3a2ecfd0">

Is there any way to get the height of the measure?

Thank you always.

**Comment by sschmidTU** [comment]
Tab measures use a different spacing between the 6 lines than classical measures.
The spacing in Vexflow 1.2.93 is 13 pixels, so your height would be 5x13.
