### ISSUE TITLE
The modifier is not being played correctly and cannot be selected

### ISSUE THREAD

**Issue by yogaliu** [opensheetmusicdisplay/opensheetmusicdisplay#1390]
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/15954570/fbaa730c-e135-43c2-93a7-0d6882fec549)
The modifier is not being played correctly and cannot be selected.
When using osmd-extend to play, the modifiers are also skipped.

[Waltz_in_A_MinorChopin.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11596852/Waltz_in_A_MinorChopin.mxl.zip)

**Comment by sschmidTU** [comment]
Please open audio player issues in the audio player repository.
These are called grace notes and there is an issue 79 for that in the player repository.
