### ISSUE TITLE
Triplet numbers not displayed on some time-modifications

### ISSUE THREAD

**Issue by mauxion** [opensheetmusicdisplay/opensheetmusicdisplay#1399]
I've got this issue on my local project with opensheetmusicdisplay.min.js but it could be reproduced using demo https://opensheetmusicdisplay.org/demos/public-typescript-demo/

I'm using simple music sheet with one instrument imported as musicxml from MuseScore

Expected: 
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/3764909/dd39a89b-4d0b-4b5d-84a0-e6a483d5b69c)

Actual from public-typescript-demo:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/3764909/a5368392-e02a-46a3-a31d-7d08c5c21763)

Actual from my local project with opensheetmusicdisplay.min.js
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/3764909/3054a7f1-9e5d-4532-93f8-0bab244ebbf7)

(The bug is that there are no '3' at last 2 tuplet groups)

Here is a file for reproduce (sorry for .txt format, github does not allow to upload .musicxml)

[adowa.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11744776/adowa.txt)

**Comment by sschmidTU** [comment]
`osmd.EngravingRules.TupletNumberLimitConsecutiveRepetitions = false`

Maybe we should deactivate this option by default, as I believe you are the second person who didn't know about it.
It works well for piano scores which repeat triplets endlessly, but it seems less suited to other instruments.

**Comment by mauxion** [comment]
it helped, thx!
