### ISSUE TITLE
Can OSMD use vexflow in SVG mode?

### ISSUE THREAD

**Issue by joaocc** [opensheetmusicdisplay/opensheetmusicdisplay#140]
The reason for the question is that it seems to be easier to build interactions if SVG mode is used instead of Canvas.
Thx

**Comment by sebastianhaas** [comment]
Not at the moment, but it should be really easy to do. This is also one possible fix for #69.
I'm not so sure about whether it's _easier_ to interact with a static vector graphic than with an HTML5 canvas.
PRs welcome, this should really require just a few lines of code.

**Comment by sebastianhaas** [comment]
SVG rendering was introduced in #154.
