### ISSUE TITLE
How to obtain note types

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1414]
I want to get the type of each note (Half note, Whole note). What should I do

**Comment by sschmidTU** [comment]
check e.g. `osmd.cursor.NotesUnderCursor()[0].noteTypeXml` or `osmd.cursor.NotesUnderCursor()[0].typeLength`.
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/VoiceData/NoteType.ts
