### ISSUE TITLE
Chord Symbols displayed in odd positions

### ISSUE THREAD

**Issue by yogaliu** [opensheetmusicdisplay/opensheetmusicdisplay#1415]
Why are some notes displayed in odd positions?
osmd：
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/15954570/34bde9f6-7fbd-432c-a928-9ecf17823d7f)

musescore：
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/15954570/8008f6c5-2acb-44de-af21-4e005e13c430)

**Comment by sschmidTU** [comment]
These are chord symbols, not notes. I'm guessing there isn't enough space for them since they're on 16ths notes.
Please share the musicxml file.

**Comment by yogaliu** [comment]
> These are chord symbols or maybe staff text, not notes. I'm guessing there isn't enough space for them since they're on 16ths notes (or at least 2-character texts on 8ths notes etc). So to avoid overlaps we have to stack them vertically. Please share the musicxml file.

Okay, please take a look at this.
[ai_piano_pre_10175686.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11904158/ai_piano_pre_10175686.mxl.zip)

**Comment by yogaliu** [comment]
> These are chord symbols or maybe staff text, not notes. I'm guessing there isn't enough space for them since they're on 16ths notes (or at least 2-character texts on 8ths notes etc). So to avoid overlaps we have to stack them vertically. Please share the musicxml file.

Is there any progress or any solution yet?

**Comment by sschmidTU** [comment]
You can work around this with some settings to make measures wider, e.g.:
```js
osmd.EngravingRules.VoiceSpacingMultiplierVexflow = 1.2 // multiplier
osmd.EngravingRules.VoiceSpacingAddendVexflow = 4 // one-time addition per measure
```

<img width="350" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/14948ca0-46bb-4f9a-84a3-5cc8833145c2">

But in general, as I said, there just isn't enough space for this high number of labels on 16th notes in a normal layout.
Also, they are exported to MusicXML as `<words>`, not as chord symbols (`<harmony>`). If they were added as chord symbols, OSMD would space them to get enough room for them horizontally. But OSMD isn't made to put a `words` element above every note.
