### ISSUE TITLE
When obtaining SVG note graphic elements from a score, some elements are within the same parent element, so I cannot find each detailed note through the ID of the parent element. What should I do?

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1416]
When I get all the note graphic elements, I find that when two or more Whole note svg elements appear in a section, they will be in the same parent element, which makes it impossible for me to bind to the corresponding note graphic through the ID, what should I do in this case? Is this a problem with my xml?
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/86224160/160481af-de5f-4a5a-ac79-001096e36c56)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/86224160/c4013494-c945-46f4-a361-22fe95cf091e)
[“自新大陆“交响曲.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11876699/default.zip)

**Comment by zhouxiang233** [comment]
For example, there are two Whole note under the current cursor. I need to set the colors of these two notes to different colors. How can I know which one I need, because they belong to the same parent element at present

**Comment by sschmidTU** [comment]
That seems to be an issue with Vexflow, they generate the IDs.
They should always be in the same order (e.g. higher note first), so you should be able to find some way to bind/link each to the corresponding note.

**Comment by sschmidTU** [comment]
Also, you can just save `osmd.cursor.GNotesUnderCursor()[1].getSVGGElement()`, the noteheads will be in a list, bottom to top.

**Comment by zhouxiang233** [comment]
Thank you very much. I think I have found the corresponding pattern
