### ISSUE TITLE
Analysis of Note value

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1421]
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/86224160/d9efa019-d15a-43b5-af5e-beb4c69ef164)
As shown in the above figure, the red area I circled is a dotted Half note, whose time value should be two-thirds of a beat. However, the time value obtained after parsing with OSMD is a standard Half note time value. I want to know whether OSMD can recognize Dotted note, and how I can operate if I can. Thank you very much.

**Comment by sschmidTU** [comment]
`note.Length.RealValue` will be 0.75 (3 quarter notes).
You can also check `osmd.cursor.GNotesUnderCursor()[0].vfnote[0].dots`, which will be 1.
