### ISSUE TITLE
The changes in key signature appear as if they were in the TREBLE CLEF.

### ISSUE THREAD

**Issue by ammatwain** [opensheetmusicdisplay/opensheetmusicdisplay#1423]
**The changes in key signature appear as if they were in the TREBLE CLEF.**
These tests were conducted using a simple html page with clean OSMD and **without** enabling transposition.

|*Image 1*
|:--
|The first image is taken from MuseScore. In this image, the changes in key signatures that occurred in the clefs of G, C and F appear consistent with the context of their respective clefs:
| ![musescore](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/8464862/1d5e9efa-aaa4-485a-92a7-eb3824b401f7)|

|*Image 2*
|:--
| The second image is produced by OSMD. In this image, the changes in key signatures that occurred in the clef of C and F **appear** as if they had occurred in the clef of G: 
|![osmd2-elab](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/8464862/c3555b6c-ace9-4ed4-b759-e19eb6641a30)|

|*Image 3*
|:--
| The third  (and interesting) image is produced with OSMD, and it's the typical situation where there is little space for the entire musical staff. The staff starts again and updates the current clef. In this case, the subsequent key signature is in the correct position, but the problem reoccurs in the next measure:
|![osmd3-elab](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/8464862/5e70b1f9-a2cc-478f-877c-64e1f6ad37cd)|

|*Image 4*
|:--
|The fourth image is produced by OSMD, with a modification in `MusicSystemBuilder.AddInstructionsAtMeasureBegin()` method, around line 504: Changing `if (isSystemStartMeasure}` to `if (true /* isSystemStartMeasure */ )`. The modification is intended to force the drawing of the clef at the beginning of each measure. ***In this case, everything appears correct, except for an overabundance of clef symbols.***:
|![osmd4-elab](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/8464862/e32a1d03-8104-4196-81b3-7a508b673b06)|

If I have to speculate something, I speculate that in the timeline of events to be drawn, there should regularly be a "currentClef" (or something similar) that is "null|undefined" and this state should bring back into play the last active clef of the staff. However, instead of taking the last active clef in the staff, for some reason, perhaps due to ambiguous conditionals, the default clef which is certainly the "G" clef, is brought back into play.

I apologize, I haven't gained enough experience in the OSMD graphics engine to explore a solution more in-depth. I pass along this information in the hope that it may be useful to more experienced individuals.

I am attaching the test file.

***NB: In any case, the notes always appear to be represented correctly.***

[Stress_Test_Clef_and_Key.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11990079/Stress_Test_Clef_and_Key.musicxml.zip)

**Comment by ammatwain** [comment]
Update:

In KeySignature.js,
const clef in format() method is always "treble"
const clef = ((this.position === StaveModifier.Position.END) ? this.stave.endClef : this.stave.clef) || this.stave.clef;

**Comment by sschmidTU** [comment]
@ammatwain Hah, I just discovered that too, and fixed it in #1424!
Still, thank you for the very thorough report, sample and code hint, that was extremely helpful.
