### ISSUE TITLE
Problem with brackets and bar numbers

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1430]
Hello OSMD friends, here I am with another little problem that I am trying to fix myself, but I can't figure out.

Take the attached score I have already presented you:

![Braket2](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/74486ea1-d959-4505-aabd-2bfe50406c0b)

As you may notice the bar numbers are hidden by the top of the system bracket. I know OSMD shouldn't do that, the code inside MusicSheetCalculator.ts, from line [538](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/2e662020ede8171139c33f3cc245dd9ed78d62d1/src/MusicalScore/Graphical/MusicSheetCalculator.ts#L538) is clearly looking for that, but for some reason, doesn't seem to be working. The value of musicSystem.GroupBrackets.length is always 0, therefore no vertical shift is applied to the bar number.

Any ideas?

[BrandenburgShort.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12064337/BrandenburgShort.xml.zip)

**Comment by fablau** [comment]
Any thoughts about this issue? @sschmidTU ?

**Comment by sschmidTU** [comment]
Yes, it's an issue. We should probably increase the skyline at x=0 by around 1 when there's a bracket.

**Comment by sschmidTU** [comment]
Fixed.
<img width="117" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/792127b4-c151-4ec8-8cfb-ef0cfdec667f">

visual diffs:
[diff_groupbracket-measure-number-y-offset.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12187263/diff_groupbracket-measure-number-y-offset.zip)

(5 samples improved)

**Comment by fablau** [comment]
Fantastic, thank you Simon!!
