### ISSUE TITLE
Issues and questions about the ContinuousTempoExpression class

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1431]
Hello @sschmidTU  and friends.

Here I am with another issue that I can't figure out.

I have just discovered that all the expressions listed inside the [ContinuousTempoExpression](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/VoiceData/Expressions/ContinuousExpressions/ContinuousTempoExpression.ts) class are NOT rendered. 

Take the following example:

![contExpr](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/2dcef476-6ed9-4fe8-b6b2-85693a91945e)

Inside the OSMD demo viewer, I get the following:

![contExpr2](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/516acc89-e0a1-4b4b-a02c-5e52d4e43fe1)

It looks like the "poco meno" expression is completely ignored, or at least not rendered for some reason.

Also, I am just wondering what's the exact difference between the [ContinuousTempoExpression](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/VoiceData/Expressions/ContinuousExpressions/ContinuousTempoExpression.ts) and the [InstantaneousTempoExpression](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/VoiceData/Expressions/InstantaneousTempoExpression.ts) classes. It is my understanding that the former is about "tempo expressions that keep changing for a while" (i.e. "ritardando" or "accelerando"), whereas the latter is about sudden and definitive tempo change expressions such as "Andante" or "Tempo primo" or "a tempo." But if so, I don't understand why "poco meno" or "meno mosso" are listed under the ContinuousTempoExpression class when they should be listed under the InstantaneousTempoExpression class since those describe a sudden and definitive tempo change. If we have such a different way of interpreting tempo expressions, we should also remove all the expressions that are actually "continuous" inside the InstantaneousTempoExpression class such as "rit." or "rallentando." I am afraid those were added by myself with one of the latest pull requests...

Sorry for so many questions!

I am attaching below a .zip file with the MusicXML file of the example shown above. Thanks!

[testShort.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12177906/testShort.musicxml.zip)

**Comment by sschmidTU** [comment]
> all the expressions listed inside the [ContinuousTempoExpression](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/VoiceData/Expressions/ContinuousExpressions/ContinuousTempoExpression.ts) class are NOT rendered.

That's not entirely true, for example the "ritard." in Haydn Concertante measure 240 is rendered.
<img width="173" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/14931f8c-2a4f-42a8-84c5-72377cd892d7">

> what's the exact difference between the [ContinuousTempoExpression](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/VoiceData/Expressions/ContinuousExpressions/ContinuousTempoExpression.ts) and the [InstantaneousTempoExpression](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/VoiceData/Expressions/InstantaneousTempoExpression.ts) classes

Yes, you got that right. InstantaneousTempoExpression generally have an instant instead of continuous effect.
Or rather, the instant ones are the standard tempo expressions that are usually used for an entire piece or at least large sections, while e.g. meno mosso or poco meno is usually used for short sections within a larger "Instantaneous" section, e.g. allegro. For meno mosso, a music dictionary notes that it "generally occurs in the middle of a movement". So I suppose a more precise naming would be `"LargeSectionTempoExpressionThatAlmostExclusivelyOccursAtTheStartOfAMovement"` and the other one `"MidPieceTempoChangeThatIsUsuallyContinuousButNotQuiteAlways"`, but I don't think poco meno and meno mosso justify that name change, and code wise it is rather irrelevant anyways, as it behaves the same as e.g. ritardando for rendering.

> we should also remove all the expressions that are actually "continuous" inside the InstantaneousTempoExpression class such as "rit." or "rallentando." I am afraid those were added by myself with one of the latest pull requests...

Right, they should probably be moved to ContinousTempoExpression, I overlooked that in the PR. I hope it doesn't cause big issues for rendering.

**Comment by sschmidTU** [comment]
Actually most of the ContinuousTempoExpressions we have behave the same as the "Instant" ones, at least graphically speaking. The difference is rather in playback (ritardando = gradual tempo reduction).

So graphically I've treated them the same as instant expressions for now, and there are no visual regressions, and it fixes your sample.

<img width="619" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/059be7e7-b1ff-4102-bcfd-e6c01758578e">

**Comment by sschmidTU** [comment]
I think we can close this for now. There's a naming / refactoring discussion left, but I think the rendering issue was more important here.

**Comment by fablau** [comment]
Thank you Simon for responding, I agree with you on everything. I am just wondering if all "instant Expressions" will be then rendered in bold face type?

**Comment by sschmidTU** [comment]
> I am just wondering if all "instant Expressions" will be then rendered in bold face type?

I don't know, are they? Should they be? Do you have any concerns?
In any case, not all continuous tempo expressions are rendered in bold, as you can see in the image above.

**Comment by fablau** [comment]
I'll check and report. I think I saw boldface type applied to all instant expressions, but maybe I am mistaken. I'll check!

**Comment by fablau** [comment]
Simon, have you applied this fix to the latest develop branch? Just wondering. Thanks again.

**Comment by sschmidTU** [comment]
Yes, see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/94b3dec263267fbcfba4ff20047107dc9931cddf

**Comment by fablau** [comment]
Yes, got it now! Thanks!

**Comment by fablau** [comment]
About the instant expressions being in bold, I can confirm that. I see no problems with that (for now).

Thanks again :)
