### ISSUE TITLE
npm install hangs/fails with npm 9.5.1 and node v18.16.0

### ISSUE THREAD

**Issue by eedeebee** [opensheetmusicdisplay/opensheetmusicdisplay#1433]
Had to hit ^C - reliably repeatable on my Mac (intel) with a clean (empty) project to start.  Attached the npm debug log. I tried waiting like 15 minutes and gave up.  My mac has decent network connectivity... I can see the terminal bar bouncing between clang and c++lang

```
 % npm install opensheetmusicdisplay                                    
(##################) ⠦ reify:gl: timing reifyNode:node_modules/vexflow Completed in 933ms
```

[2023-07-27T22_20_42_725Z-debug-0.log](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12188594/2023-07-27T22_20_42_725Z-debug-0.log)

**Comment by sschmidTU** [comment]
@eedeebee  Does it work if you bump the `gl` dependency to 6.0.2?
```json
"optionalDependencies": {
    "gl": "^6.0.2"
  },
```

They seem to have fixed the Mac build.
If it does, we'll bump the dependency.

What I was otherwise going to write:

---

Try node v14, as our .nvmrc indicates (do `nvm use`).
Or have a look at #1239 with the link to the wiki (try `CXX=gcc-10 npm i`)

Unfortunately Mac seems to have an issue with the GL library. If I knew how to fix it, I would.

**Comment by sschmidTU** [comment]
Should be fixed in 1a1356016dfe645ebc441973cba96b18887e2d05 (upgrading the dependency), hopefully.

**Comment by eedeebee** [comment]
So I was hoping to install the npm package.  I pulled down the repo and things are _closer_ but if you can build and update the npm package and I can just use it, then great!  Seems some more updating of versions is in order...

``` 
% npm i
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-jsdoc@37.9.7',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@es-joy/jsdoccomment@0.20.1',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^16 || ^17' },
npm WARN EBADENGINE   current: { node: 'v18.16.0', npm: '9.5.1' }
npm WARN EBADENGINE }

> opensheetmusicdisplay@1.8.1 prepare
> npm run build


> opensheetmusicdisplay@1.8.1 prebuild
> npm-run-all prebuildVexflow prebuildKarma


> opensheetmusicdisplay@1.8.1 prebuildVexflow
> ncp src/VexFlowPatch/src/ node_modules/vexflow/src/


> opensheetmusicdisplay@1.8.1 prebuildKarma
> ncp src/KarmaWebpackPatch/lib/ node_modules/karma-webpack/lib/


> opensheetmusicdisplay@1.8.1 build
> npm-run-all lint build:webpack


> opensheetmusicdisplay@1.8.1 lint
> npm run eslint


> opensheetmusicdisplay@1.8.1 eslint
> eslint -c .eslintrc.js --ext .ts .


> opensheetmusicdisplay@1.8.1 build:webpack
> webpack --progress --config webpack.prod.js

assets by status 3.41 MiB [cached] 228 assets
orphan modules 789 KiB [orphan] 87 modules
runtime modules 8.99 KiB 15 modules
javascript modules 3.93 MiB
  modules by path ./src/ 1.68 MiB 202 modules
  modules by path ./node_modules/ 2.2 MiB
    modules by path ./node_modules/core-js/internals/*.js 96.2 KiB 142 modules
    modules by path ./node_modules/core-js/modules/*.js 41.4 KiB 21 modules
    modules by path ./node_modules/typescript-collections/dist/lib/*.js 112 KiB 17 modules
    modules by path ./node_modules/raf/ 2.92 KiB 2 modules
    + 10 modules
  ./demo/index.js 43.6 KiB [built] [code generated]
asset modules 1.57 KiB
  ./src/MusicalScore/Graphical/Shaders/VertexShader.glsl 140 bytes [built] [code generated]
  ./src/MusicalScore/Graphical/Shaders/FragmentShader.glsl 1.43 KiB [built] [code generated]

ERROR in /Users/ericbloch/repos/opensheetmusicdisplay/tsconfig.json
/Users/ericbloch/repos/opensheetmusicdisplay/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'eslint'.
  The file is in the program because:
    Entry point for implicit type library 'eslint'
ts-loader-default_e3b0c44298fc1c14

webpack 5.88.2 compiled with 1 error in 27208 ms
ERROR: "build:webpack" exited with 1.
npm ERR! code 1
npm ERR! path /Users/ericbloch/repos/opensheetmusicdisplay
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ericbloch/.npm/_logs/2023-07-27T23_11_38_251Z-debug-0.log```

**Comment by sschmidTU** [comment]
Does bumping these packages help?
```json
"eslint-plugin-jsdoc": "^46.4.5",
"eslint-plugin-standard": "^5.0.0",
```

**Comment by sschmidTU** [comment]
Also bumped eslint to 8.45.0.

**Comment by sschmidTU** [comment]
Also, if npm install still fails, try deleting the `node_modules/` folder and try again.

**Comment by eedeebee** [comment]
Thanks folks - additionally upping the eslint packages per the above made the build in the repo eventually succeed for me (I had to nuke existing node_modules).  Will you consider updating the latest at npm with this?

**Comment by sschmidTU** [comment]
Great to hear!
The npm build shouldn't be affected by any of this though, as these are only dev dependencies, they aren't included in the build.
But regardless, we will soon publish a new release to npm (will be 1.8.2).

**Comment by eedeebee** [comment]
Fwiw seems I wasn't clear  in my original bug report.  I was trying to npm install the package itself, which I presume will be fixed when these changes are pushed up to npm, I presume.

**Comment by sschmidTU** [comment]
@eedeebee 1.8.2 is published to npm, can you try npm install with it again? Would be good to know if it works out of the box now.

**Comment by eedeebee** [comment]
Works for me!

**Comment by joshstovall** [comment]
I also have been running into errors lately, using Node 18 on Windows. I think related to Canvas or GL. My fix is to do `nvm use 16` and it's seems to work. Glad to see the continued updates and support. Thanks 🙏

**Comment by sschmidTU** [comment]
@joshstovall Good to know, thanks for the node 16 hint. Does it still cause errors with 1.8.2 if you don't use node 16? Then maybe we should look into upgrading canvas and/or other packages as well.
