### ISSUE TITLE
Note pitch changed with bad MusicXML by Noteflight

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1435]
Hello everyone.

I am trying to figure out why OSMD makes this strange bad interpretation of this piece in the first bar:

![Sample1](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/33a9754b-b66e-4db7-8773-fb64d46c4988)

Whereas it should be displayed as follows:

![sample2](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/54ff0a81-544c-4982-964d-19b877d5f15d)

By looking at the XML file, everything seems correct. Any ideas? I am attaching the MusicXML file compressed into a .zip file. Thanks.

[Bicycle.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12262732/Bicycle.xml.zip)

**Comment by ammatwain** [comment]
Hi  @fablau, I tried to open that file with MuseScore 4 and it's categorizing it as "invalid musicxml." Nonetheless, MSC4 is able to open it and re-export it again in XML. And if I try to open it with OSMD, it seems to be just as you posted it.

**Comment by fablau** [comment]
Thanks @ammatwain for trying. That XML file was exported from Noteflight, and the shot I took is from there... but I could open the ssame file without issues in the latest version of Sibelius Ultimate, which shows it correctly as follows:

![Sib](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/b114db20-39ce-4a19-9f3f-1d596d777fa8)


Despite it first gives me this sort of "error":

![SibError](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/150a3544-7515-4472-8887-55cacc1ab8ec)

But at the end it opens it and shows it correctly. I am puzzled by the fact OSMD changes the first notes in the first bar.

**Comment by sschmidTU** [comment]
That's a MusicXML from hell if I've ever seen one.
<img width="686" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/fa61aaaa-2d64-4ab3-8f6f-43aac64b7597">

It first backs up the timestamp, which is already annoying to deal with, then changes the divisions in the middle of the measure.
It also doesn't know what line breaks are.
I've never seen such a disorganized MusicXML export. My music program also tells me it's not valid MusicXML.
We can try and see if we can fix their MusicXML for them, but I'm not sure how long that's going to take.

**Comment by fablau** [comment]
I agree Simon, the MusicXML file is kind of a mess. But the definition of notes seems ok to me. No need to fix their file, I was just wondering why OSMD isn't getting the note pitches correctly. ;)

**Comment by sschmidTU** [comment]
Maybe you can try loading it in Musescore or another program and re-exporting it to MusicXML. You might have to change something insignificant (and then maybe change it back), because otherwise I think MuseScore just exports back the original file.

**Comment by fablau** [comment]
Yes Simon, that did the trick ;) Thanks!
