### ISSUE TITLE
Flag and feature to enchange Transposition and Sheet Title in OSMD

### ISSUE THREAD

**Issue by ammatwain** [opensheetmusicdisplay/opensheetmusicdisplay#1436]
Hi @sschmidTU Simon, these two things I'm asking about are for something specific I need, and they might be helpful for people who use transposing a lot.

1. Instead of what we worked on before, could we add a special setting in `rules` and `OSMDOptions`  that allows transposing the sheet music on the first opening? (if `TransposeCalculator` is there, I was thinking of having it work together with `RenderCount`).
3. Another thing, not as important, but related to the first request, it would be helpful if we could change the title of the sheet music even if it's already there. That way, I could write something like _"Für Elise changed to Db"_ on it. (Unless this is already a thing and I just haven't seen it.)

Amedeo

**Comment by sschmidTU** [comment]
1. You can already do that, there's an example line you can enable in the index.js.
<img width="836" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/61d55e42-ea08-456b-9091-bb98f067b01f">

2. You can also already do that:
`osmd.Sheet.Title.text = "Für Elise changed to Db"`
<img width="762" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/58732e8f-14f3-4fe5-ab21-04ba85d8b8ee">

(obviously, this score is not Für Elise)

**Comment by ammatwain** [comment]
You're right, @sschmidTU. I was too focused on `RenderCount`. But even so, the issue of transposing from 'x' to 'C' would still arise. At this point, I'm thinking of implementing a transposition that isn't directly to the target key, but rather by calculating the existing relationship between the `MainKey` and the `Transpose` Value. I had started to implement it, and I was wondering if it would be redundant. Well, it seems not! (Basically, F# => F# would be 0, while F# => C would be 6).

Thanks Simon, you've cleared up a doubt for me!

**Comment by sschmidTU** [comment]
Closing this for now, feel free to add comments or reopen!
