### ISSUE TITLE
BUG: Octave shift crashes on render when some instrument is hidden

### ISSUE THREAD

**Issue by rlisbeth** [opensheetmusicdisplay/opensheetmusicdisplay#1439]
Hello OSMD team,

I think I have spotted another bug in the octave shift code : sometimes I get a crash when I render my .mxl file which contains piano scales on 4 octaves with left and right hand in different Instruments and the right hand is hidden. This crash is quite random, doesn't happen every time, but I guess it is related to the width of the viewport since I manage to get it systematically when resizing the window.

I provide a minimal code for you to reproduce the bug in a [zip file](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12311587/osmd-issue.zip). The code is pretty simple :

```html
<div id="osmdContainer" />
<script src="opensheetmusicdisplay.min.js"></script>
<script>
    const osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");
    osmd.setOptions({
        backend: "svg",
        drawTitle: true,
        drawingParameters: "compacttight" // don't display title, composer etc., smaller margins
    });
    osmd
        .load("./Scale_sixteenth.mxl")
        .then(
            function () {
                osmd.sheet.Instruments[0].Visible = false
                osmd.render();
            }
        );
</script>
```

I have built a debug version of osmd (included in zip) to get a more readable stacktrace:

```
VexFlowMusicSheetCalculator.ts:988 Uncaught TypeError: Cannot read properties of undefined (reading 'Measures')
    at VexFlowMusicSheetCalculator.calculateSingleOctaveShift (VexFlowMusicSheetCalculator.ts:988:80)
    at VexFlowMusicSheetCalculator.calculateOctaveShifts (MusicSheetCalculator.ts:3404:34)
    at VexFlowMusicSheetCalculator.calculateMusicSystems (MusicSheetCalculator.ts:948:18)
    at VexFlowMusicSheetCalculator.calculate (MusicSheetCalculator.ts:294:14)
    at GraphicalMusicSheet.reCalculate (GraphicalMusicSheet.ts:195:25)
    at OpenSheetMusicDisplay.render (OpenSheetMusicDisplay.ts:230:22)
    at OpenSheetMusicDisplay.ts:741:26
    at resizeEnd (OpenSheetMusicDisplay.ts:776:17)
```
If you don't get the crash at first launch, please try to resize the window. My guess is that the crash could be related to the number of lines breaks used to display the sheet.

Thanks for your amazing work !

**Comment by ammatwain** [comment]
Hi @rlisbeth. Hi @sschmidTU . It's not entirely random. It occurs when a staff line is hidden, and the octave line should "break" to restart on the next lower staff line. In the function  `VexFlowMusicSheetCalculator.calculateSingleOctaveShift()`, the variable representing it, `nextShiftStaffline`, is `null`.

One possible approach could be this, I've tried it and it seems to work reasonably well. However, it's just a temporary workaround; perhaps we should consider avoiding that staff line altogether.

```
...
const nextShiftStaffline: StaffLine = nextShiftMusicSystem.StaffLines[staffIndex]; // !Perhaps null.
if (nextShiftStaffline){ // PATCH!  <--- add this before
    const nextShiftFirstMeasure: GraphicalMeasure = nextShiftStaffline.Measures[0];
    // Shift starts on the first measure
    const nextOctaveShift: VexFlowOctaveShift = new VexFlowOctaveShift(octaveShift, nextShiftFirstMeasure.PositionAndShape);
    let nextShiftLastMeasure: GraphicalMeasure = this.findLastStafflineMeasure(nextShiftStaffline);

    if (i < systemsInBetweenCount - 1) {
      // if not - 1, the last octaveshift will always go to the end of the staffline
      nextOctaveShift.endsOnDifferentStaffLine = true;
      nextOctaveShift.graphicalEndAtMeasureEnd = true;
      nextOctaveShift.endMeasure = nextShiftLastMeasure;
    }
    const firstNote: GraphicalStaffEntry = nextShiftFirstMeasure.staffEntries[0];
    let lastNote: GraphicalStaffEntry = nextShiftLastMeasure.staffEntries[nextShiftLastMeasure.staffEntries.length - 1];

    //If the is the ending staffline, this endMeasure is the end of the shift
    if (endMeasure.ParentStaffLine === nextShiftStaffline) {
      nextShiftLastMeasure = endMeasure;
      lastNote = endStaffEntry;
    }

    if (lastNote.graphicalVoiceEntries.length === 1 &&
      lastNote.graphicalVoiceEntries[0].notes.length === 1 &&
      lastNote.graphicalVoiceEntries[0].notes[0].sourceNote.isWholeMeasureNote()
    ) {
      // also draw octaveshift until end of measure if we have a whole note that goes over the whole measure
      nextOctaveShift.graphicalEndAtMeasureEnd = true;
      nextOctaveShift.endMeasure = nextShiftLastMeasure;
    }

    const logPrefix: string = "VexFlowMusicSheetCalculator.calculateSingleOctaveShift: ";
    if (!firstNote) {
      log.warn(logPrefix + "no firstNote found");
    }
    if (!lastNote) {
      log.warn(logPrefix + "no lastNote found");
    }
    nextOctaveShift.setStartNote(firstNote);
    nextOctaveShift.setEndNote(lastNote);
    nextShiftStaffline.OctaveShifts.push(nextOctaveShift);
    this.calculateOctaveShiftSkyBottomLine(firstNote, lastNote, nextOctaveShift, nextShiftStaffline);
} // PATCH!!! <-- add this after
```

**Comment by sschmidTU** [comment]
Fixed.

<img width="863" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/1a6e89f0-b2e9-41c2-ac46-e21b262557dc">

Thanks @rlisbeth for the report and @ammatwain for the nice workaround! It was a good hint on where to look, though I've implemented a more complete solution now which still draws the octaveshift.

I've also added this test sample which now forcibly creates a new system/line after measure 2 in the visual regression tests, so that this test situation doesn't depend on the container dimensions anymore.
[test_octaveshift_first_instrument_invisible_Scale_sixteenth_break_m2.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12321960/test_octaveshift_first_instrument_invisible_Scale_sixteenth_break_m2.zip)

You can mimic this like this (in our demo):
```js
osmd.EngravingRules.NewSystemAtXMLNewSystemAttribute = true;
osmd.sheet.Instruments[0].Visible = false;
```
