### ISSUE TITLE
The Problem of Homophonic Multitone Score

### ISSUE THREAD

**Issue by zc52406** [opensheetmusicdisplay/opensheetmusicdisplay#1441]
The problem of homophones with multiple parts is that only one note will be displayed in the score display. As shown in the following example：
[https://static.doyure.com/dmapi/free_training/songs/yh_23~24/A2.mxl](url)

There is no problem with the presentation format in MuseScore,
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/13899303/73b85993-5054-4c2e-873c-1a1a823a31c9)

But after OSMD processing, one of the notes will be missed.
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/13899303/84264f49-7d68-49ac-b90b-e5c752f9fc5a)

**Comment by zc52406** [comment]
I also reported the issue to gitter.im
https://matrix.to/#/!QdKfQrWTpunkZJtxtb:gitter.im/$4pi932xDecb90lG3gWjk2CFUPhzlIi3wqpm1KM_p4Lg?via=gitter.im&via=matrix.org

**Comment by sschmidTU** [comment]
The mxl file is not available anymore.
Please upload the samples to github (zipped) instead of linking to a private server.
The note is not missing, the stem is just not doubled.
I can reopen and take a look when I have the sample.
