### ISSUE TITLE
Invisible parts affect alignment

### ISSUE THREAD

**Issue by kimkanu** [opensheetmusicdisplay/opensheetmusicdisplay#1444]
Hello, I encountered with a possible bug. Even with the 2nd part hidden, it affects to the alignment of notes in the 1st part. (See unequal spacing of 8th notes grouped by beams.)

Currently OSMD renders:
<img width="1367" alt="Screenshot 2023-08-16 at 19 37 48" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/22598138/4abe6815-ea7b-4663-9ca7-7d9f173d4bb7">

But it should be like as:
<img width="1065" alt="Screenshot 2023-08-16 at 19 38 09" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/22598138/fb39ebab-0c42-4d8f-bd3c-d478f98976c3">

Which part do I have to modify to achieve the wanted result?
I'll attach a sample musicxml file to reproduce the issue.

Sample file: [sample.musicxml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12359181/sample.musicxml.txt)

**Comment by sschmidTU** [comment]
test

**Comment by sschmidTU** [comment]
Where is the issue exactly? I'm looking at around 100 notes.
So, it would be nice to have a simpler sample.

**Comment by kimkanu** [comment]
Sorry for not making the issue clear. Here is a simpler file (created using MuseScore 4):
[simpler.musicxml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12363308/simpler.musicxml.txt)


Tests are done on the demo page (https://opensheetmusicdisplay.github.io/demo). 

First the file contains following tag so the second staff should be hidden, while it is not hidden when rendered with OSMD.
```xml
 <part id="P2">
    <measure number="1">
      <attributes>
        <!-- omitted -->
        <staff-details print-object="no">
          <staff-lines>5</staff-lines>
        </staff-details>
      </attributes>
<!-- omitted -->
```
<img width="1164" alt="Screenshot 2023-08-17 at 5 31 56" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/22598138/51cf3da6-8f5c-495a-91d2-35eab47d9a42">


When I hide it manually by `osmd.Sheet.Parts[1].Visible = false; osmd.render();`, notes in the second part affect the alignment of notes in the first one. You can see the unequal spacing of the quarter notes:
<img width="1184" alt="Screenshot 2023-08-17 at 5 36 03" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/22598138/81433acb-43f2-44dc-aa06-7b1e952eaaba">

In comparison, MuseScore 4 renders it as follows:
<img width="1020" alt="Screenshot 2023-08-17 at 5 28 13" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/22598138/724626fe-b627-4a2f-bee5-339dad41ceae">

**Comment by sschmidTU** [comment]
Fixed.
`osmd.Sheet.Instruments[1].Visible = false`
<img width="736" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/6cb1c28f-bc37-4536-9e06-3a12fb38984d">

`osmd.Sheet.Instruments[1].Visible = true`
<img width="744" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/951decdd-566d-4d2c-adaa-eb83e3ea66ad">

Thanks for the nice, simplified sample! Added to visual regression tests.

**Comment by sschmidTU** [comment]
@phscott99 Can you upload or point to a sample where this makes a difference and say in which measure?

**Comment by phscott99** [comment]
[Issue_1444.txt](https://github.com/user-attachments/files/17438553/Issue_1444.txt)
Here you go - hiding P1 should mean that the two measures of P2 are the same width, but measure 1 is wider than measure 2.
The measures are equal width when the chord symbols are removed.
