### ISSUE TITLE
Passing a VexFlow object to OpenSheetMusicDisplay

### ISSUE THREAD

**Issue by davidbrochart** [opensheetmusicdisplay/opensheetmusicdisplay#1447]
I started [ipyscore](https://github.com/davidbrochart/ipyscore) which is a Python binding for VexFlow as a Jupyter widget. Currently it's just mimicking the EasyScore API, but I'd like to offer the ability to play a score (maybe using [ipytone](https://github.com/benbovy/ipytone)), and it would be great to have the currently playing notes highlighted, just like you do with the cursor.
I'm not sure how OpenSheetMusicDisplay interacts with VexFlow though. For instance, can I pass a VexFlow object to OpenSheetMusicDisplay, or does it always start from a MusicXML file?
Also, I see a VexFlowPatch directory, does it mean that you vendor your own version of VexFlow?

**Comment by sschmidTU** [comment]
Hi, interesting approach!
You can't currently pass a Vexflow object to OSMD without maybe hacking it in or changing OSMD code.
You're right, OSMD is intended to start from a MusicXML file.
We also have some examples (e.g. [OSME](https://github.com/opensheetmusicdisplay/osme/blob/develop/src/OSME/SourceGenerator/ExampleSourceGenerator.ts)) to create your own score model via OSMD methods without any MusicXML, but it's not that easy.

OSMD uses Vexflow for most of the rendering, especially what's within the stafflines (notes, note layout, key+time signature, clefs, etc). But OSMD also does some rendering of its own, e.g. instrument names, lyrics, dynamics wedges and expressions (like dim.), etc. You can see most of that in our local demo if you show bounding boxes for labels:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/adc5488f-9436-4b76-a8ad-a94e6afbbe9d)

And yes, VexFlowPatch is our custom patch applied on Vexflow version 1.2.93. We could theoretically publish it as our custom version on npm, but the patch format works fine practically, it's a prebuild script.

By the way, if you're wondering why we're still on Vexflow 1.2.93 when there's already 4 and 5 (5 currently in heavy development), unfortunately the formatter changed drastically from Vexflow 3 onwards, and there are still too many layout issues that look worse in 3+, so we stick to the version that produces the best results overall. See here: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1139

**Comment by sschmidTU** [comment]
By the way, what kind of Vexflow object would you like to pass to OSMD?

**Comment by davidbrochart** [comment]
Thanks for all the details!
I'm not sure what kind of VexFlow object to pass, the thing is that my entry point is currently the VexFlow API, not a MusicXML file. Maybe I could have my own API that would generate MusicXML, and then use OSMD, but I'm not sure I would have enough control over the rendered score.
Also, maybe [using CSS](https://github.com/0xfe/vexflow/wiki/Animation-with-VexFlow-&-CSS) is enough for my use case.

**Comment by sschmidTU** [comment]
Feel free to reopen once you have further questions / know what kind of object you want to pass!
