### ISSUE TITLE
How do I know if a note belongs to the high or low range

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1451]
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/86224160/d7253224-d2e3-4c1a-ab77-48904c0c7b52)

As shown in the above figure, how do I know if the notes in the current score belong to the high range (red box part) or the low range (green area part)?

**Comment by sschmidTU** [comment]
`osmd.cursor.GNotesUnderCursor()[1].parentVoiceEntry.parentStaffEntry.parentMeasure.ParentStaff.ParentInstrument`, look at Id etc

**Comment by zhouxiang233** [comment]
Sorry, I apologize for not understanding your code. What I want to know is whether each note belongs to the high or low range. What should I do? I hope you can answer my questions. Thank you very much.

**Comment by sschmidTU** [comment]
check note.parentVoiceEntry.parentStaffEntry.parentMeasure.ParentStaff.Id. If it's 1, it's the first staff (treble staff, right hand. If it's 2, it's the second staff).
It depends on how you get the note, which you didn't report, but for example:
`osmd.cursor.GNotesUnderCursor()[0].parentVoiceEntry.parentStaffEntry.parentMeasure.ParentStaff.Id`

**Comment by Muromi-Rikka** [comment]
> check note.parentVoiceEntry.parentStaffEntry.parentMeasure.ParentStaff.Id. If it's 1, it's the first staff (treble staff, right hand. If it's 2, it's the second staff). It depends on how you get the note, which you didn't report, but for example: `osmd.cursor.GNotesUnderCursor()[0].parentVoiceEntry.parentStaffEntry.parentMeasure.ParentStaff.Id`
The id obtained through this way will change in different situations. For example, when there is only one note at the same time, the id of the second staff will become the id of the first staff, like this.
![image](https://github.com/user-attachments/assets/739a0276-7190-4b67-b7e2-f063056b77ec)
In my design, blue should be the mark for the first staff, but it accidentally got the id of the second staff.
