### ISSUE TITLE
XML loading error

### ISSUE THREAD

**Issue by zhouxiang233** [opensheetmusicdisplay/opensheetmusicdisplay#1455]
I encountered an error while using the following function to obtain svgId
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/86224160/d3cf6ca4-7d5d-4fd7-a8d4-1adaf48b7c62)

![屏幕截图 2023-09-06 141123](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/86224160/8a9ea96f-4da6-40e4-8d04-2e8b4e3d8f8c)
and I found that undefined will appear in the current array when using the code line osmd. graphics. measureList
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/86224160/f2c8824f-1d9b-49fd-a96c-47cc339767e3)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/86224160/a61b235a-cbad-4d51-bf8c-027715fc9e19)
The track file has been uploaded. Could you please answer my question
[纸飞机（教师弹奏）(1).zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12534009/1.zip)

**Comment by sschmidTU** [comment]
You should skip undefined notes. It shouldn't be a surprise that you can't call a function on an undefined variable.
You also didn't provide code to reproduce this issue.
