### ISSUE TITLE
label error

### ISSUE THREAD

**Issue by caomingrui** [opensheetmusicdisplay/opensheetmusicdisplay#1457]
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/642b83dc27fd1671349eab691935953c903985c0/demo/index.html#L30C52-L30C52

**Comment by sschmidTU** [comment]
And what do you think the error is? Canvas is canvas.

**Comment by caomingrui** [comment]
This line of HTML has an additional '>' symbol, doesn't it

**Comment by sschmidTU** [comment]
Ah, you're right, I overlooked that. Fixed. Thanks for the report!
