### ISSUE TITLE
Incomplete sample address

### ISSUE THREAD

**Issue by caomingrui** [opensheetmusicdisplay/opensheetmusicdisplay#1458]
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/fceb767917d4e8a9369f9fc2cdf07acd1ccaf0d2/demo/embedded_demo.html#L95

Missing Closed -》“&endUrl“
http://localhost:8000/?embedded&openUrl=xxx&endUrl

**Comment by Asmit-Rai** [comment]
Try this
<a href="http://localhost:8000/?embedded&openUrl=http://localhost:8000/BrookeWestSample.musicxml">Link</a>

**Comment by Asmit-Rai** [comment]
try this
<a **href="http://localhost:8000/?embedded&openUrl=http://localhost:8000/BrookeWestSample.musicxml">Link</a>**

**Comment by caomingrui** [comment]
I may not have expressed it clearly, what I mean is that the example link is missing the closed key character '&endUrl'

Therefore, it is not possible to load the expected musicXML file
In the findGetParameter method
`           let startParameterName = 'openUrl=';
            let endParameterName = '&endUrl';
            let openUrlIndex = location.search.indexOf(startParameterName);
          ...
            let endIndex = location.search.indexOf(endParameterName) + endParameterName.length;
            ...
            let urlString = location.search.substring(openUrlIndex + startParameterName.length, endIndex - endParameterName.length);`

**Comment by sschmidTU** [comment]
Fixed. You're right, the links with `openUrl` weren't working. Now they do.
(It's been a long time since I've looked at the embedded demo)
