### ISSUE TITLE
Beamings over notes issue

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1464]
Hello @sschmidTU  and team,
Here I am with another issue with OSMD, this time about beamings going over notes in particular cases like this one:

![OSMD_shot](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/2070d7c8-f210-4c40-b65c-96082cc8afda)

As you can see, the bottom notes are completely hidden by the beamings. I am uploading the corresponding MusicXML file. The file was exported from Sibelius, but even editing it with MuseScore and exporting it again didn't make any difference.

Thoughts?
[OSMD_test.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12809293/OSMD_test.musicxml.zip)

**Comment by sschmidTU** [comment]
I wonder why the engraver made the beams downwards, it doesn't make much sense to me, unless you artificially make the beams extremely short. It makes more sense to flip them upwards. That's what I would do.
Very rare situation with an honestly bad engraving choice in my opinion. Not sure if we can catch this. I would just flip the beams in the file.

**Comment by fablau** [comment]
Good point Simon... I was just curious to know your thoughts about it.

I guess the meaning was to differentiate the 3 voices in the music (melody at the top, accompaniment in the middle, bass). But of course, that's particularly strange.

If you see no easy fix in OSMD (or any other "engraving rules" trick to set an exception for that kind of situation), we'll rework the score to make it more "standard."

Thanks!
