### ISSUE TITLE
Cannot read properties of undefined (reading 'FromNote')

### ISSUE THREAD

**Issue by miller06** [opensheetmusicdisplay/opensheetmusicdisplay#1465]
Hey,OSMD cannot obtain GraphicalNote，
window.osmd = openSheetMusicDisplay;
let gNote =  window.osmd.GraphicalNote.FromNote(note, osmd.rules)
Thank you

**Comment by sschmidTU** [comment]
Can you please share the MusicXML file? You can rename it to .txt or zip it and drop it here.

**Comment by miller06** [comment]
[index.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12816575/index.zip)
Thank you

**Comment by sschmidTU** [comment]
@miller06 That is a Javascript file. I need a MusicXML file. Because this issue doesn't happen with any of our test samples.

**Comment by miller06** [comment]
I solved it with your method,Thank you.
const gNote = osmd.rules.GNote(note) (in typescript: osmd.EngravingRules)
