### ISSUE TITLE
Can OSMD write bold text corrrrectly?

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1472]
Hello @sschmidTU and team.

I have just submitted a pull request to add a few tempo indications to the InstantaneousTempoExpression.ts because some key tempos, such as "Maestoso" or "Allegro assai" weren't included:

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1471

I am also wondering about any other possible tempo that, at least from the "graphical" standpoint, I think should always be written in bold text. So, I am suggesting updating OSMD to follow the `font-weight='bold'` attribute of <words>, whenever that's present. It looks like that's ignored, and instead, unrecognized tempos, even if defined with a "bold" face, are always written in Italics.

You can try the attached file, which includes the "Maestoso" tempo for your reference.

Thoughts welcome!

Thanks :)

[03Joy_to_the_World.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12875426/03Joy_to_the_World.musicxml.zip)

**Comment by sschmidTU** [comment]
Fixed in #1471. Thanks for the report and PR, great change!
