### ISSUE TITLE
Issues with Noteflight XML files

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1473]
Hello @sschmidTU and team.

I am trying to understand why OSMD is throwing an error when importing the attached XML file I have exported from Noteflight. MuseScore imports it correctly, even though it is giving a warning that the file is "not valid."

Here is the error I get:

`demo.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'StaffEntries')`

Thoughts?

Thanks.

[Sonata in C.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12898574/Sonata.in.C.xml.zip)

**Comment by sschmidTU** [comment]
Fixed the error. (No visual regressions)
It looks like there is some erroneous timestamp information in the MusicXML, leading to an AbsoluteTimestamp of NaN.

Now it renders, though unfortunately this MusicXML is still a complete disaster, it has dynamics and slurs duplicated multiple times, from a quick look.
<img width="369" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/870f9c5c-e9d3-4608-9782-b2f558040116">
<img width="216" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/4f1268ec-7a56-4e97-84dd-306c2a6d7445">

I would try to remove the duplicate nodes from the MusicXML file, if you find that worth the effort and desperately want to show this sample / improve the rendering. Of course it would be preferable if Noteflight didn't duplicate expressions and slurs for no reason ;)

**Comment by sschmidTU** [comment]
By the way, this Noteflight MusicXML sample says it's Noteflight version 0.4. It also doesn't use newlines.
Is it possible that this was exported with an old version of Noteflight that's outdated by now?
Just a quick thought.
Unfortunately I didn't find a way to figure out the current version of Noteflight (that gets put into the MusicXML file).

**Comment by fablau** [comment]
Thank you Simon, I didn't realize the XML file was that bad! Actually I exported it from the current Noteflight version. The source file though could be old.

Anyway, thanks again for looking into this ;)
