### ISSUE TITLE
Adjust staff line Spacing

### ISSUE THREAD

**Issue by 59lou** [opensheetmusicdisplay/opensheetmusicdisplay#1475]
hi, the default spacing between staff line is too large, how can i decrease this spacing? thank you very much
![exmaple](https://github.com/59lou/TempImageStore/blob/04e42c23133a1b7e395e03a157e17e2a0a9002e8/exmaple_1.png?raw=true)

**Comment by sschmidTU** [comment]
You can try some of these settings, mainly:
`osmd.EngravingRules.MinSkyBottomDistBetweenSystems = 2`

This should be enough, but you can try some other "Between" settings:
```js
MinimumDistanceBetweenSystems
BetweenStaffDistance
MinSkyBottomDistBetweenSystems
```

etc.
