### ISSUE TITLE
Problems with tremolos

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1478]
Here I am with another issue related to tremolos.

Have a look at the attached zip file. It includes two MusicXML files:

1. testTremolo.musicxml
2. SwanLake.musicxml

The first file is just 3 bars taken from the second file, for testing purposes. The second file, makes OSMD freeze completely, and I have no idea why, unless that's related to the tremolo issue I am going to talk about in the first file.

If you open the first file inside MuseScore or any other notational program, here is how it should look like:

![TremoloRight](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/89d66af2-6bec-4efa-bba3-a67183f5d9b9)

But inside OSMD I get this:

![TremoloWrong](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/2560df81-98d5-49cb-820d-09cf3d5130ff)

It is clear that OSMD is unable to handle tremolos the correct way. Is that a feature that still needs to be implemented? And what about the second file freezing it completely?

I am eager to know your thoughts about all this.

Thanks!

[TremoloFiles.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/13233744/TremoloFiles.zip)

**Comment by fablau** [comment]
Ok, after some more research, it looks like the section from bar 85 is causing the freeze. I have isolated that section in the attached file here below. I have no idea what's causing that problem.

[SwanLakeBars.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/13233938/SwanLakeBars.musicxml.zip)

**Comment by sschmidTU** [comment]
Fixed. It was a rare infinite loop caused by complex rhythms and floating point inaccuracies, thanks for finding this and especially isolating the 3 measures in the sample!
Strangely, it seems to happen in measure 3, but if I cut out everything but measure 3 manually in the XML, it doesn't happen anymore.

**Comment by fablau** [comment]
Fantastic, thank you again!

**Comment by sschmidTU** [comment]
display of this test sample was improved by the fix in #1540 by the way.
before:
<img src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/4e34800f-3e7c-490e-a846-0ddb5c42ba34" height="250">

after:
<img src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/28d73ac7-bd36-4f26-8f52-667e7745bb53" height="250">

The durations for notes in certain complex tuplets were not correct.

**Comment by fablau** [comment]
That's great Simon. What about the missing tremolos in the first sample above? Any plans to handle those?
