### ISSUE TITLE
Drawing Chord Symbols

### ISSUE THREAD

**Issue by motozy** [opensheetmusicdisplay/opensheetmusicdisplay#148]
Hi,
Since we need Drawing Chord Symbols on OSMD, so I implemented it tentatively, but how is it possible to be merged to OSMD?
If possible, I would like to cooperatively implement it in such a way that it will eventually be merged into OSMD.
https://github.com/motozy/opensheetmusicdisplay/

**Comment by matt-uib** [comment]
Hi!
Thanks for contacting us! We have already planned a simple textual Display of the Chords (E.G. A7, Esus4...) which will be drawn as a label above a stave note (staff entry). I will check out the details and get back to you.
All the best,
Matthias

**Comment by motozy** [comment]
Hi Matthias!
Thanks for your answer.
Hope to hear from you. :-)

**Comment by matt-uib** [comment]
As we had the parsing already prepared, i implemented it in a basic version. Was faster now than explaining how to do it. Chord symbols are shown now and layouted in x direction correctly, but - this is generally an open topic - not layouted in y direction. We will add a y-layout measurement and calculation in the future. For now you could just set a fixed offset for every ChordSymbolContainer.BoundingBox.relativePosition.y at the function VexFlowGraphicalSymbolFactory.createChordSymbol():
e.g.:
graphicalChordSymbolContainer.PositionAndShape.relativePosition.y = - 3;

**Comment by matt-uib** [comment]
see the chordSymbols feature branch

**Comment by motozy** [comment]
Great! I will try it in this version.
Thank you very much!

**Comment by matt-uib** [comment]
i merged the chordSymbols feature branch into develop as it fixed the x coordinates of the bounding boxes needed for positioning of graphical objects. Therefore i close this issue now.
