### ISSUE TITLE
Rendering sheet-music in MIDI?

### ISSUE THREAD

**Issue by Treata11** [opensheetmusicdisplay/opensheetmusicdisplay#1488]
First of all, I have to appreciate your great product, works seamlessly!

I just wanted to make sure that there isn't any straight forward way to render the music-sheet for **midi** files using _OSMD_?

If that's the case, I'd appreciate any guidance for this purpose. 
I haven't found any library to add as a dependency to my project in order to convert _Midi to mxl_ & haven't seen any project which renders musical-notation for midis neither ...

**Comment by sschmidTU** [comment]
Hello, there is already an issue for this:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/206

I think the PHPMusicXML library has made progress recently, but as I wrote in that issue, in general, midi is not meant to be displayed as sheet music and will look terrible when converted. But I wish you best of luck!

**Comment by Treata11** [comment]
@sschmidTU Thanks for the heads up.
Didn't know that Midi sheet musics don't look as appealing as the musicxml ... I've downloaded some tracks both in midi & mxl from [MuseScore](https://musescore.com/openscore) & didn't notice anything at all (of course, the file could've been written in MIDI first & then converted to other formats in when published on the web...).
And I really was hoping that I could use MuseScore's plugins as a package-dependency for this purpose ... but turns out [Batch-Export](https://github.com/Jojo-Schmitz/batch_export) is written as an exclusive plugin for MuseScore that could not be deployed anywhere else, which is a shame ...

Anyway, I'd appreciate if you introduce any other projects that you know and are capable of rendering sheet music from MIDI.

**Comment by sschmidTU** [comment]
Yes, the midis on MuseScore are extracted from the score, not the other way round.
Midi is made for playback, not for display.

**Comment by Treata11** [comment]
@sschmidTU I read all of the comments on issue #206.
Unfortunately I'm limited to deploy only C-family libraries (with some other exceptions like JS). 

A thousand thanks.

**Comment by sschmidTU** [comment]
Ah, unfortunate. You're welcome. If you find some interesting libraries yourself, please let us know as well!

**Comment by Treata11** [comment]
For sure.
Another thing I'd better ask 'til you here ...
If you know any projects that are able to convert the other way round **MXL -> MIDI** it'll work for me just as fine ...

**Comment by Treata11** [comment]
Almost forgot!
Not 100% sure but I think [Music21](https://github.com/cuthbertLab/music21) has conversion capabilities.

**Comment by sschmidTU** [comment]
I was about to say yes, but it's in Python, haha.
https://web.mit.edu/music21/doc/usersGuide/usersGuide_08_installingMusicXML.html

Maybe you can create an executable that you can call from C or something.

There's also the open source "version" of MuseScore, which is C++ though. It apparently also has a command line interface. Again, maybe you can create an executable.
https://github.com/musescore/MuseScore
https://musescore.org/en/handbook/3/command-line-options

MuseScore Features (shown on Github):
* MusicXML import/export
* MIDI (SMF) import/export

**Comment by Treata11** [comment]
Hi @sschmidTU
Sorry I bother you again with another question :)
Probably should've opened a new issue for it, but here we are ...

I just have a question about [The Cursor](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo#the-cursor).
Is there a ready made API for it that syncs with the playback of the musicxml file?

**Comment by sschmidTU** [comment]
No, unfortunately not in public OSMD. Our audio player, which is exclusive to OSMD sponsors on Github, which also has all the playback code, has a function to jump to the position at x milliseconds for a given tempo.
It relies on a lot of playback code though, so if we brought that to public OSMD, we'd need to port half the audio player over.

**Comment by sschmidTU** [comment]
No, unfortunately not in public OSMD. Our audio player, which is exclusive to [OSMD sponsors on Github](https://github.com/sponsors/opensheetmusicdisplay), which also has all the playback code, has a function to jump to the position at x milliseconds for a given tempo.
It relies on a lot of playback code though, so if we brought that to public OSMD, we'd need to port half the audio player over.

**Comment by Treata11** [comment]
I appreciate your response. 
Saw #218 & https://github.com/sponsors/opensheetmusicdisplay a little bit late ... I was hoping you didn't read the comment.
But thank you anyway.

Is there any chance that it'll be public soon?

**Comment by Treata11** [comment]
#258 , my bad :)
>  you could also then try to extract the code for setting the cursor to x milliseconds and use it in your project.
I don't have any idea how hard and time consuming that would be ... 

And I actually would love to sponsor the project, the issue is _I simply can not use Github sponsors_ for some strange & stupid geopolitical reasons.
Is crypto accepted?

**Comment by Treata11** [comment]
@sschmidTU I appreciate your help so far ...

**Comment by kamshory** [comment]
I've moved PHPMusicXML to a new repository at https://github.com/Planetbiru/MusicXML

This library has successfully converted:

- MIDI -> MusicXML
- MIDI -> PDF
- MIDI -> SVG

MusicXML can also be played using OSMD, but for complex music, it seems the audio still needs improvement. However, it's quite good for simply displaying notation on the screen.

For synchronization purposes with MIDI players, use SVG format instead of PDF. The repository also provides an example of synchronizing a MIDI player with SVG, which displays notation highlights and playhead movement. This repository is also available on Packagist.
