### ISSUE TITLE
Piano arpeggio pronunciation error

### ISSUE THREAD

**Issue by Dahurica** [opensheetmusicdisplay/opensheetmusicdisplay#1491]
The arpeggio pronunciation of osmd is pronounced together, but the arpeggio should be pronounced one by one. How can I modify the sound?

**Comment by sschmidTU** [comment]
That sounds like an audio player issue to me. Please open the issue in the sponsor repository. Public OSMD has no playback.

**Comment by Dahurica** [comment]
Alright, I should also mention that I've found some issues with the judgement of legato in the playback function. Sometimes, parts of an arpeggio can be played legato, but the result seems to be completely blocked out. This might require some modifications in the logic of judgement. As for the arpeggio, I have only identified where the problem roughly lies. I will have our project manager follow up on this.
