### ISSUE TITLE
Override the default layouts

### ISSUE THREAD

**Issue by Treata11** [opensheetmusicdisplay/opensheetmusicdisplay#1500]
Of course, the rendering engine draws the notes based on the screen bounds. However, I think it is drawing them a bit large. Is there any way to override the layout and have the notes smaller and possibly using less horizontal padding?"

![Screenshot 2024-01-12 at 19 19 53 Large](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/107116406/95187e87-6ce5-4b9b-8f35-80857f296aa7)

It's great that it displays the name of the track on top, but that also isn't something that I want to have drawn ...

**Comment by sschmidTU** [comment]
Hi! First of all, rendering large scores on phones in portrait orientation is difficult, because width is the most important dimension for scores. So, I would consider using landscape mode.

But even in portrait mode there are a few things you can optimize:

* You can remove the instrument name to the left of the staffline:
```js
osmd.EngravingRules.RenderPartNames = false;
osmd.EngravingRules.RenderPartAbbreviations = false;
```

* You can remove the title:
```js
osmd.EngravingRules.RenderTitle = false;
```

* You can reduce margins, e.g. some of the settings in our compact mode:
```js
        osmd.EngravingRules.MinSkyBottomDistBetweenStaves = 1.0; // default 1.0. this can cause collisions with slurs and dynamics sometimes
        osmd.EngravingRules.MinSkyBottomDistBetweenSystems = 1.0; // default 5.0
        // note that osmd.EngravingRules === osmd.rules, since it's passed as a reference

        osmd.EngravingRules.BetweenStaffDistance = 2.5;
        osmd.EngravingRules.StaffDistance = 3.5;
        osmd.EngravingRules.MinimumDistanceBetweenSystems = 1;
        // osmd.EngravingRules.PageTopMargin = 0.0; // see osmd.EngravingRules.PageTopMarginNarrow used in compact mode
        osmd.EngravingRules.PageBottomMargin = 0.0;
        osmd.EngravingRules.PageLeftMargin = 2.0;
        osmd.EngravingRules.PageRightMargin = 2.0;
```
        
* Finally, you can reduce the size of any configuration by reducing the zoom:
```js
osmd.zoom = 0.75; // only 75% as big (25% smaller). default is 1.
```

**Comment by Treata11** [comment]
@sschmidTU Just have to thank you for your immediate & complete answers to issues as always :)
Done things you recommended & the results are already way better:
![Screenshot 2024-01-12 at 20 13 44 Large](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/107116406/90d86df6-e6b9-4053-b160-6a3f5d90d972)

🌹

**Comment by Treata11** [comment]
Just another thing I have to mention ...
I really want to sponsor the project, but unfortunately I'm unable to use Github's sponsorship (as I may have mentioned before ...)
Are there any crypto options?
