### ISSUE TITLE
Set up simplified music notation

### ISSUE THREAD

**Issue by miller06** [opensheetmusicdisplay/opensheetmusicdisplay#1501]
Hi，May I ask if it is possible to set the score as a simplified score? What I hope is to switch to a simplified score with just one click
![11](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/38524928/cee53b07-c184-423f-8d07-12a82c2c1f39)

**Comment by sschmidTU** [comment]
What do you mean? What kind of simplified score?
