### ISSUE TITLE
Where can I find dynamics inside the osmd object?

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1502]
Hello Simon and team.

I am trying to understand where to find dynamics definitions inside the "graphicalMesures" object tree, but I am unable to find anything related to that. Maybe I am looking in the wrong place? What I am trying to find are dynamics like "p" or "f" or "ff" related to a specific graphical entry.

If I look inside this object, I get lost:

`osmd.graphic.musicPages[0].MusicSystems[0].graphicalMeasures[0][0].staffEntries[0]`

Any help is appreciated!

**Comment by sschmidTU** [comment]
The data object e.g.:
`osmd.graphic.musicPages[0].MusicSystems[0].graphicalMeasures[0][0].parentSourceMeasure.staffLinkedExpressions[0][0].instantaneousDynamic`

The graphical object lives in the staffline (`staffline.AbstractExpressions`), e.g.:
`osmd.graphic.musicPages[0].MusicSystems[0].graphicalMeasures[0][0].ParentStaffLine.AbstractExpressions`

I hope that answers the question!

**Comment by fablau** [comment]
Yes, thank you so much!
