### ISSUE TITLE
Problems with dynamics in this excerpt

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1511]
Hello @sschmidTU  and team, here I am with another issue with the attached file.

If you try to load the file "osmd_error_excerpt_with_p.musicxml" into OSDM, it throws an error in line 3511 of MusicSheetCalculator.ts because it looks like the `this.graphicalMusicSheet.VerticalGraphicalStaffEntryContainers[horizontalIndex]` is undefined.

If you remove the piano (p) dynamic indication from that last bar (or open the "osmd_error_excerpt_without_p.musicxml" file), it loads without issues. Of course, I could put an !== undefined check right there to avoid the problem, but if I do that, the dynamic indication gets rendered at the beginning of the staff as shown below (circled in red):

![OSMDdynamic](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/fce6a10b-c427-4d81-8b38-2e87b17dc79c)

I could dive deeper and try to understand why the horizontalIndex is screwed in there, but maybe you can understand the cause of that faster than me?

[DynamicExamples.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/14169342/DynamicExamples.zip)

**Comment by sschmidTU** [comment]
Fixed.
<img width="364" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/c5884c21-7971-4dff-b407-0aa9e18d59d6">
The `p` is even at the right place now!

This was another fun example of complex rhythms like 1.33333334/4 causing havoc😅


visual regressions:
[diff_NaN_fraction_from_0_GCD_fix.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/14302679/diff_NaN_fraction_from_0_GCD_fix.zip)

(one change, which seems to be a similar sample/case with a complex rhythm, probably correct now and was wrong before)

**Comment by fablau** [comment]
Awesome! Thank you Simon, I knew I could count on you on this as well!
