### ISSUE TITLE
Different vertical alignment of lyricist vs composer when composer is missing.

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1513]
Hello @sschmidTU and team.

Another issue involving the lyricist text on the first page. When both lyricist and composer are present, both texts are correctly aligned vertically so that there is some needed space between them and the start of the music below, as you can see from the example below:

![ComposerOK](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/4686182f-d4e9-48b5-9ef4-2059fcf88514)

When instead the composer is not present, for some reason, the lyricist is moved further down so that it may collide with tempo-related indications or other staff-related contents:

![NoComposer](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/10005316/27e4ed57-4e06-4c87-9e60-5763400c7438)

Is that something that can be easily fixed? I am attaching both XML files of the above examples.

Thanks!

Fab.

[LyricistIssue.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/14250842/LyricistIssue.zip)

**Comment by sschmidTU** [comment]
Hi, this should be fixed now, at least for your sample:
<img width="441" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/8ac3d1ed-2a4a-4dfa-9126-f17c0a795857">

This may not be a complete fix for all samples, but it's simply doing exactly the same as we already did for the composer label also for the lyricist label, adding a default offset.
(if there's both lyricist and composer, they're y-aligned by using the highest position for both)

Also, this is a rather rare case, I've never seen a lyricist collision before, so I hope this is good enough for now.

No visual regressions.

**Comment by fablau** [comment]
Wonderful thank you!
