### ISSUE TITLE
Guitar tabs show a white background even when PageBackgroundColor is set

### ISSUE THREAD

**Issue by zacharyappleseed** [opensheetmusicdisplay/opensheetmusicdisplay#1514]
Hello, thanks for the great sheet music platform.

I have an issue in my attempt to display sheet music snippets on my page and any advice would be appreciated. I have the music notation displaying perfectly on a dark background on my site. The problem is that the guitar tab notation has a rect behind each number, and the rect has its fill and stroke set to white. I am kind of stuck trying to edit it. I was able to use document.querySelectorAll to change the values to my background color, but upon resizing the window and activating the re-render, the white rectangles come back. Any help would be appreciated. I'm not sure if this is exactly a bug/issue, but I do think - as a user - I was expecting for the backgrounds of the tab notes to match the general background of the page if i set PageBackgroundColor to my sites background.

This occurs on when you leave PageBackgroundColor unedited or when explicitly setting it to something.
thank you for your time

<img width="685" alt="Screenshot 2024-02-14 at 11 27 14 AM" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/121331218/3464de96-7ca3-4962-9dc4-2d05e5a7a06e">

**Comment by sschmidTU** [comment]
Hi, this should be fixed now:
<img width="112" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/a8cfe2b1-5a64-4297-9d21-e4983b3003ea">

This also fixes a black background in a white score in image programs that display transparent color as black.
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/0a08efd2-e075-4b75-8291-693c4c4c55e9)
To be clear, there are also programs that displayed this "correctly" as white, but e.g. IrfanView doesn't.

This should be released in the next few days in 1.8.7, but if you're using the release version, you'll have to wait until then.
Thanks for the report, and I'm glad you're enjoying using OSMD!

visual regression diffs show simply the tab numbers not having black boxes anymore (depending on image viewer), as in the image above.
[visual_diff_tab-pagebackgroundcolor-fix.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/14301434/visual_diff_tab-pagebackgroundcolor-fix.zip)

Added a dark mode test to the visual regression tests so we don't accidentally break this:
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/73c4443c-ba4c-4eea-ad2b-e7b1960ea8c8)
