### ISSUE TITLE
About how stem coloring has been similar to notes

### ISSUE THREAD

**Issue by AlanPaine** [opensheetmusicdisplay/opensheetmusicdisplay#1521]
osmd.cursor.GNotesUnderCursor()[0].getSVGGElement().children[0].children[0].children[1].style.fill = "#FF0000";

**Comment by sschmidTU** [comment]
What is the issue exactly?

**Comment by sschmidTU** [comment]
Try `osmd.cursor.GNotesUnderCursor()[0].getSVGGElement().children[0].children[0].children[1].style.stroke = "#FF0000";`

**Comment by sschmidTU** [comment]
Also, you can use `osmd.EngravingRules.ColorStemsLikeNoteheads = true;` to color stems with the color of the noteheads.

**Comment by sschmidTU** [comment]
Again, `Try osmd.cursor.GNotesUnderCursor()[0].getSVGGElement().children[0].children[0].children[0].style.stroke = "#FF0000";` solves this.

**Comment by sschmidTU** [comment]
@AlanPaine `osmd.cursor.GNotesUnderCursor()[0].getSVGGElement().children[0].children[0].children[0].style.stroke = "#FF0000";`

<img width="46" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/0ad6e06f-288d-4a8e-8d8b-53d5711a6780">

(for the notehead, it's `osmd.cursor.GNotesUnderCursor()[0].getSVGGElement().children[0].children[1].children[0].style.fill = "#FF0000"`)

**Comment by sschmidTU** [comment]
Sorry, I don't understand your problem, you are not giving sufficient information.

**Comment by sschmidTU** [comment]
For beamed notes the stem path might be at a different place among the children nodes.
It should work with `osmd.cursor.GNotesUnderCursor()[0].getStemSVG().children[0].style.stroke = "#FF0000"`, which is also more simple.

**Comment by sschmidTU** [comment]
For some notes it can also be `osmd.cursor.GNotesUnderCursor()[0].getStemSVG().style.stroke = "#FF0000"'`
