### ISSUE TITLE
moving the cursor according to the actual rhythm

### ISSUE THREAD

**Issue by manzhizhen** [opensheetmusicdisplay/opensheetmusicdisplay#1528]
Hello, this is the server development of students, in a recent use OSMD to read MXL file to map sheet music, but the official to https://opensheetmusicdisplay.github.io/demo/ example is manually move the cursor, I hope to be able to move the cursor according to the actual rhythm of the MXL file, but I have not found a good example. Can the official or any expert provide an example of moving the cursor according to the actual rhythm of the MXL file? Thank you so much

@sschmidTU come on

**Comment by rvilarl** [comment]
I did my own timer have a look at https://github.com/rvilarl/pianoplay

**Comment by manzhizhen** [comment]
> I did my own timer have a look at https://github.com/rvilarl/pianoplay

Thanks

**Comment by sschmidTU** [comment]
What you're asking for is basically an audio player (except for the playing audio part), we've spent a lot of time building that.
Our player will soon be open source, though it's currently still in early access for sponsors only.
I hope the link above helps you. If not, feel free to reopen.
Basically you need to build a scheduler, at least figure out at which time the next note needs to be played, which depends on rhythm, tempo, notation, etc.
