### ISSUE TITLE
Cannot read properties of undefined (reading 'PositionAndShape')

### ISSUE THREAD

**Issue by alexshenker** [opensheetmusicdisplay/opensheetmusicdisplay#1539]
When clicking any note in the 3rd measure, the following error appears:
```
Uncaught TypeError: Cannot
demo.min.js:1 read properties of undefined 
(reading 'PositionAndShape') at_0x4a2ef. ‹computed>.updateWithTimestamp
```

Encountered this error with a score I've been using. I managed to cut down the mxl to the smallest portion I could while still being able to reproduce the error.
Seems that if I cut the first measure (the upbeat measure), this doesn't seem to fail.

Below is a screenshot, vid, and the mxl.

[problem_file.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/14925285/problem_file.mxl.zip)

![Screenshot 2024-04-09 at 7 58 50 PM](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/87500375/e99b0cb8-b869-440c-8c8a-1785156263e3)

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/87500375/3c36afed-186c-4df0-aa88-1d5932bc7ce6

**Comment by sschmidTU** [comment]
Fixed. Thanks for the report and the good sample and documentation!

Note that this is purely an audio player issue, as the method cursor.updateWithTimestamp() doesn't exist in public osmd.
Please open audio player issues in the audio player repository in future. Thanks!

**Comment by alexshenker** [comment]
> Fixed. Thanks for the report and the good sample and documentation!
> 
> Note that this is purely an audio player issue, as the method cursor.updateWithTimestamp() doesn't exist in public osmd. Please open audio player issues in the audio player repository in future. Thanks!

@sschmidTU Hey, would you please clarify what is the repo for the audio player - Looking at the code, seems BasicAudioPlayer is built in osmd (albeit using soundfont-player) but I'm unclear where to post issues with regard to the audio player - did you mean in the extended repo?
I ask because I'm facing the same error after pulling latest code, so I'm trying to understand if I missed something.
 Thank you!

**Comment by sschmidTU** [comment]
Yes, it's osmd-extended. You should have gotten a mail about that if you are a sponsor with early access to the player ;)
I don't get the error in the audio player, and it would be surprising if I did, because I merged this fix to the player a couple days ago. Maybe your pull went wrong?

**Comment by alexshenker** [comment]
> Yes, it's osmd-extended. You should have gotten a mail about that if you are a sponsor with early access to the player ;) I don't get the error in the audio player, and it would be surprising if I did, because I merged this fix to the player a couple days ago. Maybe your pull went wrong? Maybe you haven't updated the build?

@sschmidTU I can confirm I have the latest code/build - the demo works with no error. So I tried to replicate the demo's setup in context of my project unsuccessfully, then, I tried to perform the cursor update without initializing a PlaybackManager, using:
```
        const verticalEntry =
            osmd.GraphicSheet
                .VerticalGraphicalStaffEntryContainers[newIndex];

        osmd.Cursor.updateWithTimestamp(
            verticalEntry.AbsoluteTimestamp,
        );
```
I got the same error for the same portion of the score.

To summarize: anywhere I click on the score except that measure, works with / without playback manager. Only in the demo, the error doesn't occur. 

Any suggestions as to what to focus on while debugging?

**Comment by sschmidTU** [comment]
You've got the exact same error? reading undefined on .PositionAndShape? That should not be possible.
Your vertical entry exists?
Debugging should focus on why/when the thing that we're trying to read .PositionAndShape on is undefined.

**Comment by sschmidTU** [comment]
Also, you're using the audio player without initializing the PlaybackManager? That doesn't really make sense. Then you can just use public osmd.

**Comment by sschmidTU** [comment]
In other words, the PlaybackManager is a central component of the audio player, it's not optional.

**Comment by alexshenker** [comment]
> In other words, the PlaybackManager is a central component of the audio player, it's not optional. But I guess you probably don't need to use it much after initialization.

@sschmidTU Audio playback is not important for my usecase, I used playback manager since it was automatically handling score-clicks cursor positioning. 
I noticed that manually checking where the score was clicked and setting cursor position with `updateWithTimestamp` works faster than PlaybackManager does it, so I'll go that route for now.
For now, my workaround for the bugged entries is setting cursor to start of the score and calling 'next()' until we reach the desired entry note index after `updateWithTimestamp` fails.

I guess I'm not using the extended version to its specifications so I'll adapt for now.

**Comment by sschmidTU** [comment]
If you can tell me how to reproduce this from our demo, I can try to fix it.
Maybe not initializing PlaybackManager is enough?

**Comment by alexshenker** [comment]
> If you can tell me how to reproduce this from our demo, I can try to fix it. Maybe not initializing PlaybackManager is enough?

Let me see if I can reproduce this in a smaller sharable project that resembles my use, Will get back to you.

**Comment by alexshenker** [comment]
@sschmidTU Well now everything works... Both With playbackmanager and Without.
I'm using Nextjs for my project. I think the nextjs build did not get fully updated with the new osmd build, but today, after i woke up and ran `npm run dev`, it made a completely new build that actually implemented the newest osmd build.

I should have considered deleting the next build yesterday and running a clean slate, but just didn't occur to me. 
Very sorry about the run-around.

**Comment by sschmidTU** [comment]
Ah, no problem, I've heard that about nextjs before, it apparently likes to not use updated builds ;)
glad to hear it's working now!
