### ISSUE TITLE
Cursor misbehaving on tuplet notes

### ISSUE THREAD

**Issue by NyuBlara** [opensheetmusicdisplay/opensheetmusicdisplay#1540]
Scrolling the cursor through the following file : 

[Touront-O_gloriosa.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/15039938/Touront-O_gloriosa.musicxml.zip)

In which measure 75 features a triplet on the uppermost staff consisting of a whole and half note totaling a round note, filling the measure of 2/2 time : 

![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/74717e74-00f2-447e-833a-d3fd807c9e6b)

Results in the cursor having a dedicated position for the whole note : 

![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/d46668e9-eaef-4bdc-a39e-e13e81da4b9c)

But not for the associated half note ; this is the next cursor position : 

![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/5a1f4c54-0099-42ea-8248-2dd2844d1f43)

This behavior is encountered identically using OSMD@1.8.8 as installed via NPM, and in the online demo.

**Comment by NyuBlara** [comment]
Further testing reveals that the same behavior is encountered in measure 127 of this file :

[Bassere-Missa_D-Agnus.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/15041209/Bassere-Missa_D-Agnus.zip)

Also on a triplet, but this time, skipping the middle note of said triplet to jump to its last : 

![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/4717b2be-4fc3-440f-ac58-53cecefd5c8f)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/6d10fb21-de4b-4ff1-9958-a020eedec969)

However, both cases still involve triplets mixing whole notes with notes of different length.

**Comment by NyuBlara** [comment]
A more glaring and personally more concerning misbehavior can be observed on the following file : 
[Dufay-Belle_que_vous_ay_je_mesfait.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/15163554/Dufay-Belle_que_vous_ay_je_mesfait.zip)

On measure 25, the cursor iterates through the following notes entirely out of order : 

![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/277e7dfc-c557-46d5-99ac-4fecc819b1fc)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/4052a4df-dc3e-4b0d-8ebc-6c69603651ed)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/a8bb552b-902a-4b1c-adba-c86a528b2fbd)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/6409c3ef-856f-43fd-8ed5-ed9d27d0f996)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/440f99db-d64d-4724-b97c-85ea589663c3)
![image](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/61560065/2ad95c43-64fd-4bc9-aefc-27ac2e2b068e)

**Comment by matt-uib** [comment]
There seems to be also something wrong with the notes here:
The first staff shows 9 quarter notes in the triplet.
The other 2 staves show 6 quarter notes.

**Comment by sschmidTU** [comment]
@matt-uib I think this is normal, the other 2 staves are not in the triplet, just the top stave.

**Comment by matt-uib** [comment]
ah right - didn't see that.

**Comment by NyuBlara** [comment]
Yes, this is the case in all three files ; perhaps this is a lead ; although the behavior of the third file being completely different puzzles me.

**Comment by sschmidTU** [comment]
Fixed.

I condensed the Dufay sample into a single one measure sample (m.25):
[test_cursor_next_order_tuplets_dotted.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/15312778/test_cursor_next_order_tuplets_dotted.zip)
<img width="264" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/ca5e6e5c-160d-4962-b651-4af46a790a0f">

The order is correct now, going through it with cursor.next(), and it was reproducibly wrong in 1.8.8 (/ current demo version).

For the whole note in Touront and Bassere, it was a separate issue. The whole note has duration 1, represented by the fraction with WholeValue 1 and numerator 0, denominator 1 (duration = 1 + 0/1). We missed to add whole value and only took nominator/denominator here (0/1 = 0).
Again reduced sample to 2 measures:
[touront-m75-76.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/15312821/touront-m75-76.zip)
No more notes skipped.
<img width="202" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/7405f3cc-ad69-42e2-9b9b-7ec1161dbe3c">
Similar for Bassere m127.
[bassere-m127.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/15312874/bassere-m127.zip)
(added as _wholenote_skip in test/data)
