### ISSUE TITLE
Is there a way to get the voice of a note assigned inside the source XML?

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1544]
Hello @sschmidTU and team.

I am trying to find a way to know the source XML voice number of a note from the OSMD object, but after hours of research, I had no luck.

For example, from this location, I get the object of a specific note:

osmd.GraphicSheet.musicPages[0].musicSystems[0].graphicalMeasures[0][0].staffEntries[0]. graphicalVoiceEntries[0].notes[o]

But I can see anything inside there that lets me understand what voice inside the source XML file that note belongs to. I have looked everywhere inside the OSMD object tree, and I could not find anything that can tell me that. Is there another way to find that information? And if not, is it possible to add that information to the object tree? That'd be very useful to link notes inside the OSMD object to the source XML file.

I am eager to know your thoughts on this.

Thank you!

**Comment by sschmidTU** [comment]
This should do it: `osmd.GraphicSheet.musicPages[0].musicSystems[0].graphicalMeasures[0][0].staffEntries[0].graphicalVoiceEntries[0].parentVoiceEntry.ParentVoice.VoiceId`
Note however that OSMD is not particularly interested in linking OSMD objects to XML objects, unless there's a very good reason for it, which for OSMD internally there usually isn't. Of course if it's very useful for developers we can try adding some help for linking, but being able to link every XML tag to every OSMD object would probably bloat the code a lot, especially given that MusicXML doesn't have unique ids for nodes by default.

**Comment by fablau** [comment]
Thank you Simon.

Yes, I see your point. I am using OSMD for our new viewer below:

https://www.virtualsheetmusic.com/playground/

And I am adding interactive features that need to link OSMD internal structure objects to XML as well as to the displayed SVGs in some way. I am using a modified local version of OSMD for that, and I am trying to minimize the bloat. So far, it is working well.

In the particular case of this discussion, I have solved the problem by linking notes to the XML. My Javascript script is adding IDs to the XML file to each note which is taken by OSMD and added to its "note" object. So I can retrieve that and know exactly where each note is located inside the XML file. If that's something that interests you, I could perform a pull request on that as well.

I am going to release a new version of our Playground today (1.6) with the ability to remove slurs, ties, and hairpins from the score that use exactly that functionality.

Thanks again.
