### ISSUE TITLE
Obtaining the note staff id at the cursor position is inconsistent at different times.

### ISSUE THREAD

**Issue by Muromi-Rikka** [opensheetmusicdisplay/opensheetmusicdisplay#1552]
osmd.cursor.GNotesUnderCursor()[0].parentVoiceEntry.parentStaffEntry.parentMeasure.ParentStaff.Id
The id obtained through this way will change in different situations. For example, when there is only one note at the same time, the id of the second staff will become the id of the first staff, like this.
![354811132-739a0276-7190-4b67-b7e2-f063056b77ec](https://github.com/user-attachments/assets/e390dbef-71bc-4a85-b7fe-3254d7146f62)
In my design, blue should be the mark for the first staff, but it accidentally got the id of the second staff.

**Comment by sschmidTU** [comment]
I don't understand the issue. I get staff id 2 for all notes in the second staff in a sample of mine. The id of the staff doesn't change. It doesn't change the id of the staff if the other staff doesn't have a note vertically above it.
![image](https://github.com/user-attachments/assets/e62b90b7-6940-4041-b94d-20a9bd587d52)
[test_staff_id.zip](https://github.com/user-attachments/files/16573539/test_staff_id.zip)
