### ISSUE TITLE
Some xml files are not working

### ISSUE THREAD

**Issue by sty1103** [opensheetmusicdisplay/opensheetmusicdisplay#1553]
I tested it with the file below on the demo site and got an error.

- https://drive.google.com/file/d/1uvQRSbGtSp2zKZtY0iPj7zDTtK-wMi8J/view?usp=sharing

```
demo.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'TempoExpressions')
    at R.createMetronomeMark (demo.min.js:2:862574)
    at R.calculateTempoExpressionsForMultiTempoExpression (demo.min.js:2:688345)
    at R.calculateTempoExpressions (demo.min.js:2:725823)
    at R.calculateMusicSystems (demo.min.js:2:671173)
    at R.calculate (demo.min.js:2:660756)
    at e.GraphicalMusicSheet.reCalculate (demo.min.js:2:619414)
    at M.render (demo.min.js:2:1158607)
    at demo.min.js:2:1169830
    at o (demo.min.js:2:1170098)
createMetronomeMark @ demo.min.js:2
calculateTempoExpressionsForMultiTempoExpression @ demo.min.js:2
calculateTempoExpressions @ demo.min.js:2
calculateMusicSystems @ demo.min.js:2
calculate @ demo.min.js:2
reCalculate @ demo.min.js:2
render @ demo.min.js:2
(anonymous) @ demo.min.js:2
o @ demo.min.js:2Understand this error
```

Are there any restrictions on the xml files that can be used with osmd?

**Comment by sschmidTU** [comment]
Fixed. Demo is updated, so it should work for you now.
(if not, try a hard refresh of the page = Ctrl+R)

It was a rare null error, the first sample I've seen to cause it.

sample for posterity: (google drive is less permanent)
[1553_metronome_error.zip](https://github.com/user-attachments/files/16638721/1553_metronome_error.zip)

**Comment by sty1103** [comment]
Thanks for fixing the bug.
I'm using opensheetmusicdisplay 1.8.9 in react. If I update to the latest version, will I be able to use the fixed version?

**Comment by sschmidTU** [comment]
If you simply use the release, that will not have the fix yet, you'd need to wait for the next release.
Or manually replace the .min.js with the current build. (clone osmd -> npm install -> npm run build on develop branch -> build is in build/ directory)

**Comment by sty1103** [comment]
I'll try it. Thank you :)
