### ISSUE TITLE
Bug with octave lines and transposition.

### ISSUE THREAD

**Issue by fablau** [opensheetmusicdisplay/opensheetmusicdisplay#1556]
Here I am with a new bug I just discovered.

I am attaching the source XML file, which includes the following short example:

![bugOSM](https://github.com/user-attachments/assets/f620956f-f165-403e-83be-85e2648e2eda)

When I transpose it 6 steps higher, I get this:

![bug2osm](https://github.com/user-attachments/assets/ff541f2e-1474-4378-8d87-2faaba039df2)

Which is clearly a bug (look at bar 4). All other transpositions seem to work fine.

Any ideas on how to fix it?

Thanks.

[fluteOctaveBug.musicxml.zip](https://github.com/user-attachments/files/16881877/fluteOctaveBug.musicxml.zip)

**Comment by sschmidTU** [comment]
It looks like this only happens when you transpose multiple times.
This is sometimes an issue in general, and while it would be good to fix, I would suggest to reload the score every time before you transpose (so that it is only transposed once).
<img width="637" alt="image" src="https://github.com/user-attachments/assets/786198e6-a412-48b3-bf05-26f659f861f3">
`osmd.Sheet.Transpose = 6`

**Comment by sschmidTU** [comment]
Oh, ignore my previous comment, it's not correct either if you just transpose once. I'll take a look.

**Comment by sschmidTU** [comment]
The pitches are technically correct, it's just that the F natural should be an E sharp to be correctly notated in F# major.

**Comment by fablau** [comment]
Thank you Simon for looking into this.

Besides the enharmonic issue, why those two notes are shown one octave lower? That's the big problem I was talking about.

**Comment by sschmidTU** [comment]
Right, sorry, I forgot about the octave when I looked at the accidentals.
I'll look into it, probably an edge (off by one) case with transposition + octaveshifts.

**Comment by sschmidTU** [comment]
Fixed.
<img width="351" alt="image" src="https://github.com/user-attachments/assets/490599d0-ea21-4e7a-bddb-2eb353744b0f">

[fluteOctaveBugShort2Measures.zip](https://github.com/user-attachments/files/16999375/fluteOctaveBugShort2Measures.zip)

OSMD forgot that it had already applied the octave downwards from the octaveshift when it recreated pitches for some accidental checks, so it was applied twice.

**Comment by fablau** [comment]
Awesome! Thank you Simon!!
