### ISSUE TITLE
Synchronizing OSMD Cursor with MIDI Playback

### ISSUE THREAD

**Issue by Leptune** [opensheetmusicdisplay/opensheetmusicdisplay#1557]
Hello,

I am currently using OSMD (OpenSheetMusicDisplay) to render musicXML files and using Tone.js to handle MIDI playback. I have successfully implemented both the rendering and playback functionalities, but I am struggling to synchronize the OSMD cursor with the MIDI playback.

Here is a brief summary of the current setup:

OSMD is used to render the sheet music and display the cursor.
Tone.js is used for MIDI playback, and the notes from the MIDI file are played using a Tone.Part with PolySynth.
The basic playback controls (play, pause, stop) are working as expected.
The OSMD cursor can be controlled manually using the "Next" and "Previous" buttons.
Problem:
I would like the OSMD cursor to automatically follow the MIDI playback in real-time, moving in sync with the notes being played. Currently, the cursor is static during playback and can only be moved manually.

Questions:
How can I link the MIDI playback time (via Tone.js) with the OSMD cursor movement so that they stay in sync?
Is there an efficient way to map the MIDI timing information to the visual position of the cursor in OSMD?
Any help or guidance on how to achieve this synchronization would be greatly appreciated.

Thank you!

Here is my code, which can be run directly in the browser.
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MIDI Playback with OSMD and Tone.js</title>
    <script src="https://rtest.tlmykj.com/musicxml/opensheetmusicdisplay_v1.8.9.min.js"></script>
    <style>
        #osmd-container {
            width: 100%;
            border: 1px solid black;
        }
        #midi-controls {
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div id="midi-controls">
        <button id="play">Play</button>
        <button id="pause">Pause</button>
        <button id="stop">Stop</button>
        <button id="next">Next</button>
        <button id="prev">Prev</button>
    </div>
    <div id="osmd-container"></div>
</body>
<script src="https://rtest.tlmykj.com/musicxml/tone_v15.0.4.js"></script>
<script src="https://rtest.tlmykj.com/musicxml/midi_v2.0.28.js"></script>
<script>
let osmd;
let midi;
let part;
let synth;

async function initOSMD() {
    osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay('osmd-container');
    await osmd.load('https://rtest.tlmykj.com/musicxml/get_music_xml.php');
    osmd.render();
    osmd.cursor.show();
}

async function initMIDI() {
    // Load the MIDI file only once
    const response = await fetch('https://rtest.tlmykj.com/musicxml/get_midi.php');
    const arrayBuffer = await response.arrayBuffer();
    midi = new Midi(arrayBuffer);

    // Create a Tone.js PolySynth
    synth = new Tone.PolySynth().toDestination();

    // Create a Tone.Part to handle playback
    part = new Tone.Part((time, note) => {
        synth.triggerAttackRelease(note.name, note.duration, time);
    }, []);

    // Populate the part with notes from the MIDI file
    midi.tracks.forEach((track, trackIndex) => {
        track.notes.forEach(note => {
            note.trackIndex = trackIndex;
            part.add(note.time, note);
        });
    });
    part.start(0); // Start the part at the beginning
}

document.getElementById('play').addEventListener('click', async () => {
    await Tone.start();
    Tone.Transport.start();
});

document.getElementById('pause').addEventListener('click', () => {
    Tone.Transport.pause();
});

document.getElementById('stop').addEventListener('click', () => {
    Tone.Transport.stop();
    osmd.cursor.reset(); 
});

document.getElementById('next').addEventListener('click', () => {
    osmd.cursor.next();
});

document.getElementById('prev').addEventListener('click', () => {
    osmd.cursor.previous();
});

window.onload = async function() {
    await initOSMD();
    await initMIDI();
}
</script>
</html>


```

**Comment by sschmidTU** [comment]
Hi, you're basically implementing an OSMD Audio Player, which we have implemented ourselves, it's currently available for [monthly sponsors on Github](https://github.com/sponsors/opensheetmusicdisplay).
If you want to implement it yourself in the way you described, you would probably need to go through all cursor positions of the piece once, then have a function that calculates each timestamp (roughly absolute timestamp in quarters * 60 / bpm in quarters), then reset the cursor. Just off the top of my head, since we implemented already, so I don't need to think about it anymore ;)
