### ISSUE TITLE
Rendering pitch name on notes

### ISSUE THREAD

**Issue by danielsvane** [opensheetmusicdisplay/opensheetmusicdisplay#1560]
Im trying to render the pitch name on the note, but Im stuck creating some custom labels. Is there any documentation or ideas to how I can render some custom text? I have managed to iterate the notes and get the pitch, so I think Im somewhat on the right track.

 ```js
osmd.GraphicSheet.measureList.forEach(measureList => {
  measureList.forEach(measure => {
    measure.staffEntries.forEach(staffEntry => {
      staffEntry.graphicalVoiceEntries.forEach(graphicalVoiceEntry => {
        graphicalVoiceEntry.notes.forEach(graphicalNote => {
          const pitch = graphicalNote.sourceNote.Pitch
          if (pitch === undefined) return
          const pitchName = pitch.ToString();

          // Render the pitch name on the note
        });
      });
    });
  });
});
```

**Comment by sschmidTU** [comment]
You can probably use a similar method like this:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo#drawing-overlay-lines-over-the-score-and-getting-a-notes-position
Except instead of `DrawOverlayLine()`, you would use `renderLabel()` (for which you need to create a GraphicalLabel object), or if you want to hack it lower level you can probably use `osmd.Drawer.backend.renderText()` directly (backend is private, but it looks like you're using javascript, otherwise cast it to any).
You can also get the SVG x and y position as you can see there.

**Comment by danielsvane** [comment]
I have stolen some code from the drawBoundingBox method

```js
if (labelText) {
    const label: Label = new Label(labelText);
    this.renderLabel(new GraphicalLabel(label, 0.8, TextAlignmentEnum.CenterCenter, this.rules),
        layer, tmpRect.width, tmpRect.height, tmpRect.height, new PointF2D(tmpRect.x, tmpRect.y + 12));
    // theoretically we should return the nodes from renderLabel here as well, so they can also be removed later
}
```

And adapted it for my own

```js
const x = graphicalNote.PositionAndShape.AbsolutePosition.x;
const y = graphicalNote.PositionAndShape.AbsolutePosition.y;

console.log(pitchName, x, y)

const label = new Label(pitchName);
const layer = 5;
const width = 50;
const height = 50;
const graphicalLabel = new GraphicalLabel(label, 40, TextAlignmentEnum.CenterCenter, osmd.drawer.rules);
osmd.drawer.renderLabel(graphicalLabel, layer, width, height, height, new PointF2D(x, y));
```

The console output shows sensible values, and theres no console errors, but cant seem to render anything. Am I missing something?

**Comment by danielsvane** [comment]
After some more testing, trying to use the `drawBoundingBox` method directly, I can render the bounding boxes, but no text label text appears

```js
const boundingBox = staffEntry.boundingBox
osmd.drawer.drawBoundingBox(boundingBox, "#cccccc", false, "Test");
```
![image](https://github.com/user-attachments/assets/eea64a3c-7e65-4e2a-8252-a9fde49d9c2d)

**Comment by sschmidTU** [comment]
@danielsvane There was actually a bug in that debug code that prevented the labels from showing.
I fixed it, but disabled it by default anyways, because it's pretty useless to see the class name.
Basically you need this after `new GraphicalLabel()`:
`gLabel.setLabelPositionAndShapeBorders();`

**Comment by danielsvane** [comment]
@sschmidTU
Thank you so much, I was indeed missing the `setLabelPositionAndShapeBorders()`. I think I'm getting somewhere now.
![image](https://github.com/user-attachments/assets/fbb04f23-a0d1-413d-8c85-c7d5b301e88d)

**Comment by sschmidTU** [comment]
You're welcome, nice to see it work!
Don't forget that you can try a couple other approaches, especially if you go back to my comment about the link to the wiki, there you can find ways to get the highest/lowest position in the measure (e.g. below the stafflines), etc etc. Or maybe you can just adjust color, size, positioning, etc

**Comment by danielsvane** [comment]
@sschmidTU Yeah I'm going to play around with it some more, just didnt want to go too much off-topic here. I have plenty more questions :)
