### ISSUE TITLE
Bounding box of GraphicalNote

### ISSUE THREAD

**Issue by danielsvane** [opensheetmusicdisplay/opensheetmusicdisplay#1561]
Drawing the bounding box of a GraphicalNote, I kinda expected the bounding box to be the graphical element of the note head.

It seems like the bounding box has 0 width and height, and is not always centered on the note head, if they are pushed to the sides. Can I somehow calculate the bounding box of the note heads?

```js
osmd.GraphicSheet.measureList.forEach(measureList => {
  measureList.forEach(measure => {
    measure.staffEntries.forEach(staffEntry => {
      staffEntry.graphicalVoiceEntries.forEach(graphicalVoiceEntry => {
        graphicalVoiceEntry.notes.forEach(graphicalNote => {
          osmd.drawer.drawBoundingBox(graphicalNote.PositionAndShape, "#ff0000", true);
        });
      });
    });
  });
});
```

![image](https://github.com/user-attachments/assets/4f5a6196-0252-492e-bc44-c486ab60bc8c)

**Comment by sschmidTU** [comment]
These aren't really made to be displayed, that's just a debugging tool for us if we need it.
Do you have any specific purpose for drawing these?
You can draw the voice entry bbox instead (e.g. `osmd.cursor.GNotesUnderCursor()[0].parentVoiceEntry.PositionAndShape`), or get the precise SVG bbox in a child node of `graphicalNote.getSVGGElement()`.

**Comment by danielsvane** [comment]
I wanted to debug some issue with text alignment on labels, and wanted to make sure that the bounding box I had for the note heads was right. I found another way to draw a rectangle around the area to inspect.

It turns out, that `getSVGGElement()` on a note is a SVG group with all the other notes in the same group / voice entry? (my music notation language is limited).

To actually get the SVG for the note head, you have to get the list of `.vf-notehead` in the SVG, and get the one with the same index as the note in the `graphicalVoiceEntry`.

```js
graphicalVoiceEntry.notes.forEach((graphicalNote, noteIndex) => {
  const svg = graphicalNote.getSVGGElement()

  svg.querySelectorAll('.vf-notehead').forEach((notehead, svgIndex) => {
    if (noteIndex !== svgIndex) return

    const svgBox = notehead.getBBox()
  });
});
```
