### ISSUE TITLE
Force note length when rendering

### ISSUE THREAD

**Issue by danielsvane** [opensheetmusicdisplay/opensheetmusicdisplay#1562]
Im trying to write the note name on the note head. For half notes it gets really hard to read. Is there some way I can hack into the rendering, and set the length/duration of the note before rendering?

I have tried some weird stuff like this, but no changes to the rendering of the note length.

```js
osmd.sheet.staves.forEach((stave) => {
  stave.voices.forEach((voice) => {
    voice.voiceEntries.forEach((voiceEntry) => {
      voiceEntry.notes.forEach((note) => {
        note.length = new Fraction(1, 4);
        note.typeLength = new Fraction(1, 4);
      });
    });
  });
});

osmd.render();
```

![image](https://github.com/user-attachments/assets/b32c0533-4a35-486f-a544-208f0af66801)

**Comment by sschmidTU** [comment]
I've added an option to set a custom notehead for each note, which might be handy for us in the future anyways:
```js
note.CustomNoteheadVFCode = "vb"; // note that `note` here is a Note, not a GraphicalNote, for which you need graphicalNote.sourceNote
```

The jsdoc for that property lists some useful values and where to find the others (tables.js).

Another way to do this that works without this code update I just pushed is to just change the SVG path of the notehead (specifically, the `d` attribute) to the one of a quarter note (filled), which I guess you need to hard code copy from somewhere.
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/2cf026ea-1be6-4187-91ac-4d078b1cfe9d">

Here are 2 test samples, the one with the chord showing that the correct notehead within a chord is changed.
[test_notehead_custom.zip](https://github.com/user-attachments/files/17030660/test_notehead_custom.zip)

**Comment by danielsvane** [comment]
@sschmidTU Thats perfect, thank you so much. Will it be published to npm, or should I install it from github?

**Comment by sschmidTU** [comment]
It will be updated on npm eventually, but I can't say for sure when the next release will be, so up until then it's probably best to build the develop branch of OSMD and use that.
