### ISSUE TITLE
Undisplayed tuplets

### ISSUE THREAD

**Issue by NyuBlara** [opensheetmusicdisplay/opensheetmusicdisplay#1565]
In the following sample : 

[K279-2.zip](https://github.com/user-attachments/files/17473092/K279-2.zip)

There are several instances of triplets which go undisplayed (as seen in the public demo) : 

![image](https://github.com/user-attachments/assets/12ea5712-ddfc-4aed-a8e9-8d23c339e12b)

For reference, these triplets can be seen here in MS3 :

![image](https://github.com/user-attachments/assets/b740b31f-6e50-4c1b-92c9-af7be8c2633b)
![image](https://github.com/user-attachments/assets/6fc2e76f-7c71-4041-b004-7136acbb7658)

**Comment by sschmidTU** [comment]
`osmd.EngravingRules.TupletNumberLimitConsecutiveRepetitions = false`
We limit the number of consecutive repetitions by default. Probably shouldn't be a default settings, but this can look bad for a lot of scores like Clementi Sonatina 36/1 Pt 2 where it's clear that (almost) the whole piece is in triplets for the left hand.

**Comment by NyuBlara** [comment]
I had somehow not seen this message — thank you, and apologies for my late response !
