### ISSUE TITLE
How to get the bottom position value of a measure?

### ISSUE THREAD

**Issue by sty1103** [opensheetmusicdisplay/opensheetmusicdisplay#1571]
Is there a way to get the position value of the lowest entry as shown in the picture below?

<img width="811" alt="Screenshot 2024-12-01 at 1 29 42 PM" src="https://github.com/user-attachments/assets/74e6f125-866c-4520-a987-88bb8160c62c">

**Comment by sschmidTU** [comment]
<img width="698" alt="image" src="https://github.com/user-attachments/assets/f51c8b56-2a23-45f4-bdd0-bff31e32b4b7">

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo
That's a wiki site worth exploring :)

**Comment by chz8494** [comment]
How to delete such bottom line after creating?
