### ISSUE TITLE
wrong cursor height

### ISSUE THREAD

**Issue by chz8494** [opensheetmusicdisplay/opensheetmusicdisplay#1572]
cursor height wrong in new lines:
First line works fine, can get right height, but starting on second line seems it's not updating with correct height:
<img width="1101" alt="image" src="https://github.com/user-attachments/assets/0653cab6-74a3-4d2c-99bd-5b4cc708db42">
notice in my example that my first line has few `Force mark`, which sort of increases height on first line, but my second line doesn't have this, and it ends up ugly.

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/930eb3d2-40c5-4377-919c-215a6c895ef6">
[your code](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/aae428e6b880d08b65e21822a635525049c8d204/src/OpenSheetMusicDisplay/Cursor.ts#L211)

```ts
if (bottomStaffline) { // can be undefined if drawFromMeasureNumber changed after cursor was shown
      endY += bottomStaffline.PositionAndShape.RelativePosition.y + bottomStaffline.StaffHeight;
    }
    height = endY - y;

    // Update the graphical cursor
    const visibleMeasure: GraphicalMeasure = this.findVisibleGraphicalMeasure(currentMeasureIndex);
    if (!visibleMeasure) {
      return;
    }
    const measurePositionAndShape: BoundingBox = visibleMeasure.PositionAndShape;
    this.updateWidthAndStyle(measurePositionAndShape, x, y, height);
```
I think it's supposed to update height on every cursor move.

**Comment by sschmidTU** [comment]
I can't reproduce this error, can you share the sample and code necessary to reproduce it in our (localhost/npm start) demo?
<img width="205" alt="image" src="https://github.com/user-attachments/assets/f8fd6c76-0505-4e22-a1a5-9e6fbc596513">
