### ISSUE TITLE
Some info on how the MusicSheetCalculator logic works

### ISSUE THREAD

**Issue by toneo** [opensheetmusicdisplay/opensheetmusicdisplay#160]
I've noticed that OSMD has a lot of trouble rendering complicated pieces from Chopin and Liszt for example.  Sometimes Measures are blank, or the notes get totally out of sync (often because of the crazy special additions in the complex music, and the unusual time signatures).
I've noticed the x position of the notes get set to NaN in the end, causing all sorts of errors in the javascript log

So I've been looking in the code, trying to understand and then resolve and fix the issues.
The code seems really nice and clean but one aspect of it is layout logic where it converts the ticks to calculate the x position of the notes confuses me.

The layout logic where it converts the ticks to calculate the x position of the notes

For a particular song, Liszt Consolation no 3.
I've noticed that the notes are getting correctly generated with 1/12 time.
However some where along the line, before it reaches calculateXLayout in MusicSheetCalculator,
The notes "time" is adjust by the intrinsic ticks. and the ticks fractions go pretty crazy.

It seems the numerator of the ticks is adjusted by the intrinsic multiplier table ending with numbers like 73728, but the denominator is remaining at 6, and for some following notes, I get a ticks value of {numerator: 1365.3333333333333, denominator: 1}

Could someone point me in the right direction of the logic in determining the final fractions, and how that gets used for a final x value for the notes?  Where abouts in the code this is? Why are the ticks ending up with such values.
Wouldn't it be better if the intrinsic ticks where not applied to the fractions initially and only used at the very end as a final multiplier?
It makes it impossible to debug, or easily determine if the correct position of a note has been determined, as the fraction is no longer based on the original time signature.

If I have missed something obvious here, or this is unexpected behaviour please let me know

Many Thanks!

**Comment by toneo** [comment]
So I can see in the createTickContexts in the Formatter that the tickUsed is 0/1.
I think this is something to do with this song having only a full rest for voice 1 for the first measures.

**Comment by sebastianhaas** [comment]
Thanks for posting such detailed information! As we wait for @matt-uib to step in here and post some in-depth information on `MusicSheetCalculator `, are you able to attach the musicxml you're working on (or at least an exemplary, relevant excerpt) here so we're all on the same page?

**Comment by toneo** [comment]
Thanks for the response!

And certainly can.
Here you go.

[Some_Complex_Songs.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/1335418/Some_Complex_Songs.zip)

The Consolation one was the one I was referring to..
There are some weird errors on the first treble measure of the full score, and once I tried to fix that then it just went blank,
the smaller file I am using for debugging so its a simpler problem.

Fantasie impromptu also has timing problems, so I included here.

I've got a lot more music xml files that have problems too, which I can show you when it suits.

I've got a fairly good gist of what all the code is doing now, but some help around how the fractions and ticks logic work will be really handy.
Once I know whats supposed to be happening I can help work on fixing them

**Comment by matt-uib** [comment]
@toneo, thanks very much for the files! That helps very much. I will check them out and get back to you!

**Comment by matt-uib** [comment]
@toneo sorry for the delay... i could fix some issues regarding the tuplet rendering, but there have to be more things done.
As an info about xml divisions/durations and fractions:
in xml there is given at the start the attributes/divisions (mostly 24) which says how many ticks a quarter note has. A 4/4 measure has then 96 divisions.
The notes have a duration: eg duration = 48 for a half note.
from that information we generate the fractions to use a modelling that comes closer to the musical notation (half note is a 1/2 fraction, sixteenth note is a 1/16 fraction...)
To my opinion this actually helps in debugging as i think at which fraction a note shall be and how long it is and check it with the current values while debugging - but maybe this differs for others
Anyway, this method can lead to very high numerators and denominators for large pieces for the absolute position timestamps (fractions) - maybe you have seen that. We have already solved that by refactoring the fraction by adding a "whole" number and making the num/denom always smaller than 1. But this code is not public yet and will be added hopefully soon.
The problem that i found in your files was mostly the layouting of tuplets, where we handed over by mistake the the duration_override value to vexflow, which i thought is necessary, but it's not, as Vexflow calculates the right values internally already. I changed this now and it works now much more correctly, but there is still an issue with visualizing the correct note type for the tuplets. There we need to store the given values from xml and set it in vexflow accordingly, i guess. I will think about how to fix this finally.

**Comment by matt-uib** [comment]
@toneo actually i just saw, that the refactored code for the Fraction object (having the whole number included) was already added to the develop branch in August and is public. @toneo did you already try debugging again with latest code? Is it still the same problem?

**Comment by toneo** [comment]
Hi Matt,

Sorry for the late reply!, been very busy with work...

I just took a look now, and there is definitely a big improvement! I can see Consolation no 3 by liszt no longer has a big empty measure at the start, and fantasie impromptu is now readable.  This is great.

I have switched to the development branch now, and I will start using it and will see how it goes

Thanks for the help!

**Comment by matt-uib** [comment]
@toneo great!
