### ISSUE TITLE
Implement lyrics

### ISSUE THREAD

**Issue by vinzentt** [opensheetmusicdisplay/opensheetmusicdisplay#188]
Hi,

I would like to know if opensheetmusicdisplay supports lyrics ? And if so, can these lyrics be imported using Music Xml format ?

thanks for your answer.

**Comment by bneumann** [comment]
Hi @vinzentt, 
Actually I am just working on the lyrics feature. I hope I can finish it in a weeks time or so. I'll keep you posted.
And yes it will use the lyrics set inside musicxml. 

Cheers

**Comment by vinzentt** [comment]
Hi Benjamin, 

thanks for your answer. That's great news. Tell me if I can help you somehow.

Cheers,
Vincent

**Comment by bneumann** [comment]
Actually you can. I only have two sheets with lyrics here to test against. If you happen to have some more and are willing to share, I could test more. Best case would be if you have umlauts in it.

**Comment by vinzentt** [comment]
I'm sure you already know musescore, here I found a sheet with lyrics in french. There is an accent that may be also a good test 
https://musescore.com/user/13350351/scores/4886177
You can dowload it as MusicXml

**Comment by sebastianhaas** [comment]
I have to jump in here, the file you linked looks pretty nice, not too complex as well, so I guess it would make for a nice test case.

Unfortunately, the author has not stated any license
> None (All rights reserved)

so I guess we can't add it to OSMD's repository of demo sheets for testing etc. We can still use it for offline testing, but I guess it would be nice to have some sheets with lyrics available for CI tests as well.

**Comment by vinzentt** [comment]
Ok I was not aware of this requirement. In that case maybe this one is better: https://musescore.com/user/2848856/scores/4885383
Umlaut and creative common license :)

**Comment by bneumann** [comment]
Yeah we cannot use it in the code but I can still use it on my machine to check for errors. Thank you

**Comment by bukaznik** [comment]
I sent a message to the author of https://musescore.com/user/13350351/scores/4886177. He is ok that we use it for testing reasons...

**Comment by bneumann** [comment]
I added the Parlez moi piece to our test data in commit b28639ddcaec36ab44ea4dbca3d547cb777fb9f6. The lyrics are also rendering now in a static way. Skylining and dynamic lyric setting is the next step but @vinzentt if you want to use it already feel free to checkout the feature/Lyrics feature branch

**Comment by bneumann** [comment]
The lyrics feature has just been merged to develop!
