### ISSUE TITLE
Cannot use yarn to add opensheetmusicdisplay in react typescript project

### ISSUE THREAD

**Issue by weixiao-huang** [opensheetmusicdisplay/opensheetmusicdisplay#190]
Firstly I use [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript) to create a initial react typescript project. Then I use `yarn add opensheetmusicdisplay` to add this package. However, I got an error below:

<img width="847" alt="screen shot 2018-01-16 at 9 08 14 pm" src="https://user-images.githubusercontent.com/8834733/34990532-6d4027cc-fb01-11e7-802a-9e0518f120f7.png">

And I cannot get the package. I wonder what happened. My system is `Mac OS High Sierra 10.13.2`, I'm use `nodejs v9.2.0`

**Comment by sebastianhaas** [comment]
I will check it today. Your log output suggests it actually fails while deleting a legacy folder containing typings. This is done in a `postinstall` hook in the latest master. I suppose the problem will go away as soon as we publish a new release.

In the meanwhile, and just to make sure, could you try installing from the latest `develop` branch and see if that works for you?

I never used yarn, but I suppose it will work similar to this: (not tried)
```
yarn add https://github.com/opensheetmusicdisplay/opensheetmusicdisplay#develop
```

**Comment by sebastianhaas** [comment]
Will close this due to inactivity.
