### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#2]
Publish osmd as npm package.

- [x] Refine `package.json` contents
- [x] Wait for #3 to be done
- [ ] Publish to npm

**Comment by sebastianhaas** [comment]
Created webpack example project for use with the npm package to come.
https://github.com/opensheetmusicdisplay/webpack-usage-example

**Comment by sebastianhaas** [comment]
#4 Merged @oliver-h @acondolu are we good to merge into master and build `0.0.1` or do we wait for the plugin infrastructure?

**Comment by oliver-h** [comment]
In my opinion, we don't have to wait for the plugin infrastructure - the question is, if we should wait for the (almost certain) license change.
@bukaznik What do you say?

**Comment by sebastianhaas** [comment]
`0.0.1-alpha.0` published https://www.npmjs.com/package/opensheetmusicdisplay after merging #4
