### ISSUE TITLE
Migrating to TypeScript 2.0

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#20]
TypeScript 2.0 is [Beta](https://github.com/Microsoft/TypeScript/releases) since one week, so the first stable release will be out soon. I suggest we make the move sooner than later so we can figure out what has changed and what causes problems.

[What's new in TypeScript 2.0](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-20)
[Breaking Changes](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-20)

**Comment by oliver-h** [comment]
Agree. I would suggest that we upgrade as soon as the stable version is out

**Comment by sebastianhaas** [comment]
Done in 830006be24d3b168f7d1078283e8d2ba2e95fafa
