### ISSUE TITLE
Row and bar count of current screen

### ISSUE THREAD

**Issue by dominikmeixner** [opensheetmusicdisplay/opensheetmusicdisplay#200]
Hi,

I would like to know if there is a possibility to get the count of the current rows shown on the screen.
And is it possible to get the count of bars from each row (as array)?

I would need these two informations for a project of mine, but I am not very familiar with JavaScript and TypeScript.

Thanks a lot

**Comment by sebastianhaas** [comment]
That is totally possible, obviously that information is available during the process of rendering. The question to me is how are you planning to use that data. Can you elaborate on that project of yours? What is the usage scenario? What technology are you using then if not JS? How are you planning to incorporate OSMD then?

**Comment by dominikmeixner** [comment]
I am planning on making an Android App, where the score should scroll in a certain tempo. Currently I am using a webview element to display the score, but I need the data of the score (row and bar count) in my JavaActivity, to see how much information is really displayed. With this information I want so scroll the webview to the next page and use them for some statistics.
I am planning to get the data with a javascriptInterface from the webview, but to do that I need to know the names of the variables respectively the name of the function I have to call.

**Comment by sebastianhaas** [comment]
I would love to help out on this. As of now, I guess there is no clean way to do this built into OSMD. However, I guess we can add such functionality pretty easily.

Scrolling is a different question though. I can't really see how you would be using such data for scrolling. OSMD always renders the entire sheet, therefore, it would be always returning the total number of bars and rows. There is no such thing as pages. Why not render the whole sheet and let the webview do the scrolling?

**Comment by dominikmeixner** [comment]
I am using the WebView to scroll. The problem is, I do not know how far I have to scroll in order to only skip one row or having it look good. That's what I need the row and bar count in order to calculate how far I have to scroll down on different devices, if that makes sense to you. Is there or are there certain commands to get these counts?

**Comment by matt-uib** [comment]
You can do it the following way:
Iterate through: GraphicalMusicSheet->MusicPages->MusicSystems
and get MusicSystem->BoundingBox->AbsolutePosition
Then use: 
screenPos = VexFlowMusicSheetDrawer.applyScreenTransformation(AbsolutePosition)
to get the position on screen.
Finally set the webview to screenPos.y.
That's about how we are planning to do it as we also would like to add scrolling in the future (possibly this year)

**Comment by matt-uib** [comment]
...if you want to know the measureNumber of the first measure in the system:
MusicSystem->StaffLines[0]->Measures[0].measureNumber.
You can also iterate through all the measures to get all measure numbers of this system.

**Comment by rios88** [comment]
Hello, I'm trying to put automatic scroll in angularjs. How could I know when the bar is in the last position of the staff so that it does the automatic scroll. Thanks for the help

**Comment by matt-uib** [comment]
Hello @rios88!
Why not using the current musicSystem.PositionAndShape.AbsolutePosition.y ?
When the cursor goes to the next system you get a next y coordinate to move to...
Again finally use 
screenPos = VexFlowMusicSheetDrawer.applyScreenTransformation(AbsolutePosition) for your movement.

**Comment by rios88** [comment]
Hello @matt-uib , 

I get the error Can not read property 'applyScreenTransformation' of undefined and Can not read property 'PositionAndShape' of undefined. Sorry but I'm a beginner

**Comment by dominikmeixner** [comment]
Thanks very much! @matt-uib 
It worked for me, exactly what I needed.

@rios88 maybe you did not finish loading and are assigning the values before it did. Try using .then() after .load() to wait until you finished loading. Hope that helps!
