### ISSUE TITLE
demo.js not found

### ISSUE THREAD

**Issue by impactcolor** [opensheetmusicdisplay/opensheetmusicdisplay#201]
build/demo/index.html when I run this file it gives me an error that demo.js is not found.
In the file it has:     <script src="./demo.js" type="text/javascript"></script>
However this file does not exist here: ./demo.js

**Comment by bneumann** [comment]
Hi, thanks for filing this. We did change the build system a bit so right now it is not really consistent. Did you run grunt build:pack before?

**Comment by impactcolor** [comment]
Hi, no I didn't run grunt build:pack the wiki documentation doesn't reference that:

          lint  Lints all JavaScript and TypeScript files.                                         
    build:demo  Builds the demo.                                               
    build:test  Builds the tests                                               
    build:dist  Builds for distribution on npm and Bower.                      
          test  Runs unit, regression and e2e tests.                           
       default  Default task, running all other tasks. (CI)  

I ran build:demo and build:test and those didn't add the demo.js

Thank you your suggestion worked.

**Comment by bneumann** [comment]
Ah damn, yes I will update the documentation as well. But good if you can work for now

**Comment by bneumann** [comment]
Hey @impactcolor ist that related to your post in #179?

**Comment by impactcolor** [comment]
@bneumann no I think it's different.  This works as you said.
