### ISSUE TITLE
Color the bar

### ISSUE THREAD

**Issue by rios88** [opensheetmusicdisplay/opensheetmusicdisplay#207]
Hello,

I have managed to paint the notes except the bar (the bar connects the stems of two or more notes). The notehead and the stem if you paint them but the bar does not. Could I do it in some way?

I use fillStyle and strokeStyle to paint the notes.

Regards

**Comment by bneumann** [comment]
Hi, yes the bar is a different object in vexflow. And currently there is no access to it from osmd. I have a small demo locally where you can set the colors like a theme. Do you need to color them during runtime as well?

**Comment by rios88** [comment]
Hello, what I need is that you can color the entire musical note. Right now I can color both the stem and the notehead but not the bar that one two eighth notes. I do not know if it says beam in English.

**Comment by bneumann** [comment]
You mean like this:
![image](https://user-images.githubusercontent.com/2605131/36933900-34ac45a4-1ee1-11e8-8a56-5f1b30e9c9d7.png)

**Comment by rios88** [comment]
Yes

**Comment by bneumann** [comment]
OK, and will you need to change it for each note?

**Comment by rios88** [comment]
I would like to be able to color that part in all the notes as you have it in the image.
If you could choose which ones to color better.

**Comment by rios88** [comment]
I still can not put color to the bar. Could you tell me how you got to put it like the one in the picture? I use the following code for the style: setStyle ({fillStyle: "blue", strokeStyle: "green"}) thanks

**Comment by bneumann** [comment]
Hi ríos88, 

Sorry for the delay. I am quite busy right now. And additionally there seems to be a problem/bug in vexflow. So it is not just a "here is the code" thing.

I might be able to push my branch today evening and let you check if that helps.

**Comment by bneumann** [comment]
Hi @rios88 ,

so I open a new branch you might wanna check out. There is a new interface in the OSMD.ts file called: colorizeNotes. You can hand over any style object you like. I also added it to the demo so you can fiddle around with it:

![image](https://user-images.githubusercontent.com/2605131/37303710-9ec9805a-262f-11e8-9410-f2894ee8a2c0.png)

Pressing the button should result in something like this:

![image](https://user-images.githubusercontent.com/2605131/37303743-b2c3500e-262f-11e8-8268-49b0210f48b3.png)
 

The style object can have these properties:

```javascript
styleobj = {
shadowColor, 'green',
shadowBlur: 0,
fillStyle: 'red'
strokeStyle: 'blue',
lineWidth: 4
}
```
For more, check out the [canvas documentation](https://www.w3schools.com/tags/ref_canvas.asp)

NOTE: This is not a official branch, I just hacked this together so you can fiddle around with it. Please let me know if this is somewhat usable for you.

**Comment by zachberry** [comment]
@bneumann Would it be possible to use some form of theming like that to highlight specific notes (for example, Color the 7th and 12th note for Voice?

**Comment by bneumann** [comment]
It would and we are discussing this internally how to do it (because right now it is also static). But there seems to be a bug either in our code or in vexflow that randomly colors note only notes but also stafflines, braces etc.

**Comment by sschmidTU** [comment]
You can color everything now, including the beam,  take a look at the wiki examples:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo
