### ISSUE TITLE
Use logging framework

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#21]
I suggest log4js, but it's really up to you. Again, I would love to hear @petrosalema's input on this. Might be good to use the same technology.

I used log4js in various places and found it super intuitive.
This will close #9

**Comment by oliver-h** [comment]
If it's easy to use, I agree on using a logging framework. For the node version of log4js, there are also typings available (which maybe doesn't make sense to use it, because there is less browser specific code in it...)
