### ISSUE TITLE
Microtonal Support

### ISSUE THREAD

**Issue by muratcorlu** [opensheetmusicdisplay/opensheetmusicdisplay#215]
Vexflow has support for microtonal accidentals https://github.com/0xfe/vexflow/wiki/Microtonal-Support But as I see, opensheetmusicdisplay is not supporting these accidentals. Is it hard to add these?

**Comment by bneumann** [comment]
No it actually is only putting more cases inside the VexFlowConverter.ts at the accidental method. Actually a quite nice contribution topic

**Comment by sschmidTU** [comment]
@muratcorlu I added support for quarter tones in the commit referenced above, should be in develop/the demo soon. Were you looking for other microtonal accidentals like the Turkish ones?
Unfortunately microtonal accidentals are indeed not trivial to support, and MusicXML and many sheet music programs aren't ideal for them, MuseScore needs an extension for Turkish ones.
One more issue is that we have a transposition engine in OSMD, and transposing microtones is not so easy.
But if you can send me an example MusicXML file with some more microtonal accidentals, preferably those supported by VexFlow, i'll see what i can do.
Closed for now, can be reopened.
