### ISSUE TITLE
Is it possible to get the pitch of a specific note? (+issue with displaying the cursor)

### ISSUE THREAD

**Issue by NclsK** [opensheetmusicdisplay/opensheetmusicdisplay#224]
I am currently working on a little android project of mine. I am trying to use the cursor and move it to the next note each time the pitch of the current note is played. Is it possible to get the pitch of the note the cursor is on?

**Comment by matt-uib** [comment]
You can get that info via the iterator in the cursor (is currently a private member):
e.g. with this code:
this.iterator.CurrentVoiceEntries[0].Notes[0].halfTone
get midi semitone of the first note at the current cursor position.
