### ISSUE TITLE
Draw Ornaments (trill, turn, mordent...)

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#227]

**Comment by matt-uib** [comment]
Drawing works - some problem with delayed ornaments -> will create new issue.

**Comment by JanvyHung** [comment]
how to get the ornaments information of notes ?

**Comment by matt-uib** [comment]
If there is an ornament present, you find it in VoiceEntry.OrnamentContainer
If not, it will be undefined.
