### ISSUE TITLE
Line connectors sometimes not correct

### ISSUE THREAD

**Issue by bneumann** [opensheetmusicdisplay/opensheetmusicdisplay#230]
Sometimes the line connectors seem to be not where they should be:

An die ferne Geliebte
![image](https://user-images.githubusercontent.com/2605131/37989730-90cc2b20-3204-11e8-8ba8-d40a0007237f.png)
Here the last measure is NOT connected

Präludium C
![image](https://user-images.githubusercontent.com/2605131/37989774-a52fc220-3204-11e8-9fc8-058e9aa98ab5.png)
Here the last connectors are not connected

**Comment by matt-uib** [comment]
Seems to be always the one before the last line

**Comment by matt-uib** [comment]
Fixed
