### ISSUE TITLE
Fix Minify/Uglify to reduce bundle size and loading time

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#231]
e.g. extract the whole Graphical code and make a second bundle.
The xml Reader ist loaded frist and if used, the calculator/renderer module will be loaded and used afterwards.

**Comment by matt-uib** [comment]
@bneumann @sebastianhaas  wouldn't uglifying help to reduce the whole size as it might reduce long names to some shorter cryptic letters?

**Comment by bneumann** [comment]
We are already uglifying. It's in the webpack.prod.js file. 

We can still split, refactor and reuse more

**Comment by matt-uib** [comment]
but not in the demo right? there i can read a lot of function names..

**Comment by bneumann** [comment]
Because you have source maps😉

**Comment by matt-uib** [comment]
.. but i can read e.g. the following in demo.min.js (or also opensheetmusicdisplay.min.js):
.sourceNote.ParentVoiceEntry.ParentVoice
or
this.currentMeasure.VerticalSourceStaffEntryContainers
in a normal text editor!

**Comment by bneumann** [comment]
@matt-uib I did some research about your last comment. It seems that uglify mangle variables. Properties and core objects are not touched because unexpected results. See https://stackoverflow.com/a/16335097/1561071
