### ISSUE TITLE
Fix articulation placement for beams

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#232]
Currently beams are not taken into account for the placement of articulations. So depending on the single note position first the stem is calculated and the articulation placed according to that. Then comes the beam and possibly changes the stem direction, but the articulation stays... has to be fixed.
Better place the articulations after the beam has been layoutet.
should be all done in Graphical/VexFlow files.

**Comment by matt-uib** [comment]
Here an example of the problem:
(actually all notes have staccato, but it is completely missing on the second note here - has to be checked as well)
![grafik](https://user-images.githubusercontent.com/17180665/38020199-e5c07fc6-3279-11e8-829e-8d0631f75e2e.png)

**Comment by ChrisUib** [comment]
Fixed
