### ISSUE TITLE
Triplets render with the wrong duration

### ISSUE THREAD

**Issue by marnen** [opensheetmusicdisplay/opensheetmusicdisplay#236]
I haven't tested this with other tuplets yet, but OSMD 0.2.1 doesn't render triplets properly.

Test file (zipped so GitHub will accept it):
[test.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/1885457/test.musicxml.zip)

Imported into MuseScore:
![image](https://user-images.githubusercontent.com/34378/38442254-b7185ec6-39b5-11e8-8c6b-81e5db6f32d9.png)

Rendered by OSMD:
![image](https://user-images.githubusercontent.com/34378/38442299-e0edff9e-39b5-11e8-87fc-79dffacccb2a.png)

Note that OSMD renders the triplet as 16ths, not 8ths.

**Comment by matt-uib** [comment]
@marnen thanks very much for the clear bug description!
Yes this is actually a known problem, but has been forgotten and was currently not filed as a bug here.
We will try to soon solve it.

**Comment by bneumann** [comment]
I just had a look into it and got this representation with the latest build:

![image](https://user-images.githubusercontent.com/2605131/38691640-b78a6efa-3e81-11e8-859f-543d584e28ac.png)

So somehow it seems this bug has been solved automagically :) 

@matt-uib I know you are kinda busy but we seriously should consider releasing a new version ;)

**Comment by bneumann** [comment]
I'll close this as we already have an issue regarding a new release

**Comment by matt-uib** [comment]
@bneumann thanks for the check - should have done it myself. So it seems not the bug has been forgotten, but i forgot that i fixed that already :-)
