### ISSUE TITLE
Highlighting bars / lines?

### ISSUE THREAD

**Issue by borismus** [opensheetmusicdisplay/opensheetmusicdisplay#239]
I'd like to be able to go from midi time to bar geometry. The TypeScript version of this library is too airtight to allow this to happen. Nothing is exposed here except loading, rendering and access to the cursor.

https://opensheetmusicdisplay.org/classdoc/classes/osmd.html

I'll have to break through the privately declared methods :(

**Comment by bneumann** [comment]
Hi,
Thanks for the comment. That's true but to be honest typescript's private is more of a recommendation like "don't step on the lawn" 😂

But of course there should be ways to achieve this. We are currently thinking about a plugin concept that exposes all kind of functionality also at runtime to control osmd.

**Comment by sschmidTU** [comment]
Not sure what the goal here is, but you can highlight measures now with a specific cursor type (type 3).
Also, there are plenty of public options, settings and accessors now.
If you need to access something private, use `(object as any)`.
