### ISSUE TITLE
support question

### ISSUE THREAD

**Issue by vernetztekirche** [opensheetmusicdisplay/opensheetmusicdisplay#241]
When I try to get the browserexample (https://opensheetmusicdisplay.org/usage/script/) working, I always get the error "opensheetmusicdisplay is not defined".
I used the opensheetmusicdisplay.min.js from the build-folder.

The demo from /build/index.html doesn't work either. No errors, no action

I used the newest git version, with npm install. Runs without errors on OSX (npm version 5.8)

Sorry for the stupid question, but can you give me some hints to get a working browser-demo for a web-application?

**Comment by bneumann** [comment]
Hi,

thanks for filing this. This is definitely a bug. The library name is missing in the webpack config. Mea Culpa, will fix it now

**Comment by bneumann** [comment]
Okay I fixed this in c9b9f0d and 44ed881 (because I always need 2 commit to do things right :( ) Let me know if this helps with your situation

**Comment by bneumann** [comment]
From the quick view on my mobile it looks like your mxl is just a zipped xml which could cause the problem.
Can you attach the other file as well so I can have a look?

**Comment by vernetztekirche** [comment]
I had to zip it, because github doesn't allow pure xml as attachments. The other files are the ones, that are created in the build-Folder.

Only changed line 85 in demo/index.js to
select.value = "Mozart_DasVeilchen.xml";

Downloaded the file https://downloads2.makemusic.com/musicxml/MozaVeilSample.xml , renamed it and saved in the build folder.

**Comment by bneumann** [comment]
OK understood. I will have a look into Firefox. It should of course work in any case

**Comment by bneumann** [comment]
Whoops. This is actually a bug. I will raise a new one for the firefox issue

**Comment by bneumann** [comment]
@vernetztekirche checkout issue #242, I fixed the encoding under firefox. While doing so I had the questionable pleasure to debug in Firefox which is kinda slow in terms of loading and rendering. Can you comfirm that?
