### ISSUE TITLE
VexTab transcription from a MusicXML score 

### ISSUE THREAD

**Issue by mdan312** [opensheetmusicdisplay/opensheetmusicdisplay#244]
Is it possible to get a VexTab transcription of a MusicXML score ?

**Comment by bneumann** [comment]
AFAIK @mat-uib implemented that in the latest develop branch.

**Comment by bneumann** [comment]
Don't thank me yet 😁 I just browsed the commit list and I don't see it. I will talk to him

**Comment by matt-uib** [comment]
@bneumann mixed this up with the guitar Tabs - but @mdan312 meant the notation language VexTab, right?
No sorry, we don't provide a VexTab transcription as we go from MusicXML directly via typescript code to VexFlow for rendering - so we don't need VexTab. Maybe it is better to ask this question at the VexTab repo?
