### ISSUE TITLE
Create OSMD Wordpress plugin

### ISSUE THREAD

**Issue by acondolu** [opensheetmusicdisplay/opensheetmusicdisplay#25]

**Comment by sebastianhaas** [comment]
I can do this whenever @bukaznik wants me to (please assign milestone), I have some experience in creating WP plugins and php in general. It will take approximately one day including release and documentation.

**Comment by bukaznik** [comment]
should work within page builders (eg for enfold and avada theme)

**Comment by fredmeister77** [comment]
https://wordpress.org/plugins/opensheetmusicdisplay/ 😁
