### ISSUE TITLE
Support for page breaks/printing

### ISSUE THREAD

**Issue by SevenBlocks** [opensheetmusicdisplay/opensheetmusicdisplay#250]
Currently if someone tries to print or save the web page as PDF, page breaks will occur anywhere, including in the middle of a staff, which makes the result unplayable. 
Are there plans to allow formatting the music into pages? I think this would make a big difference in the experience for most users. I'm willing to work on this feature if someone can give an overview on how it might be implemented.

**Comment by SevenBlocks** [comment]
I think this could be done using CSS "page-break-before: always" on multiple SVG/canvas elements.

**Comment by bneumann** [comment]
Hi, thanks for posting this. The css might actually work. And you could easily try it out on your own if you want. There are the canvas base class and the svgcanvas child class that need to be touched. I think

**Comment by SevenBlocks** [comment]
I was able to get page breaks to work using CSS "page-break-before: always", but I had to draw each musical page on a separate "SvgVexFlowBackend". So, like using an array of "backends" instead of just one. That broke the cursor functionality (probably wouldn't be too hard to fix--it just needs to move the cursor across pages). I didn't try to submit the entire change since it will likely break other people's scripts, but some non-breaking changes were in the pull request by @LearnedLately. I can post the full set of changes I made if you're interested.

**Comment by matt-uib** [comment]
@SevenBlocks this might be a useful solution for printing - yes it would be great to see your changes in a pull request and discuss them there. The Cursor shall of course also work for multiple pages finally, so it makes fully sense to look into that as well at some point, but maybe for now we can just add another flag/mode "Render for print" where we currently switch off the cursor, have an option to set the page aspect ratio (A4, Letter) and use many backends to lay them out for printing.

**Comment by SevenBlocks** [comment]
I committed my full set of changes in the fork. You might need to cleanup a little before merging, but page breaks when printing/saving as PDF seem to work.

**Comment by bneumann** [comment]
@SevenBlocks which fork are you referring to? Your repositories are quite empty at the moment

**Comment by SevenBlocks** [comment]
@bneumann, https://github.com/LearnedLately/opensheetmusicdisplay

**Comment by sschmidTU** [comment]
Seems solved, see #372, which is a duplicate anyways.
