### ISSUE TITLE
Time signature?

### ISSUE THREAD

**Issue by NclsK** [opensheetmusicdisplay/opensheetmusicdisplay#253]
How do you get the information of which time signature applies to a measure?

**Comment by NclsK** [comment]
I already use  `this.cursor.iterator.currentVoiceEntries[0].notes[0].halfTone` to get the pitch and `this.OSMD.cursor.iterator.currentVoiceEntries[0].notes[0].length.realValue`  to get the value of a note. So yes, it would be quite convenient if there was a way to get the time signature with a simple query.

**Comment by matt-uib** [comment]
@NclsK currently there is no way to get the currently active Timesignature, but what you can use and what should mostly be correct is using:
this.OSMD.cursor.iterator.CurrentMeasure.Duration.realValue
on a 4/4 TimeSignature you would get 1.0 here. (3/4 => 0.75 ...)
So you can compare the measure length with the note length... i guess that's what you are looking for.
Problems might arise when there is a pickup measure with reduced length - depends on your needs.

**Comment by praisethemoon** [comment]
Hi, as I am facing the same issue, I highly recommend using this library: [https://github.com/saebekassebil/musicjson](https://github.com/saebekassebil/musicjson). You can use it to get any measure info you need and even more features, as it seems to me OSMD is more optimized for rendering (and should remain).

Let me know how it goes, I am still toying with that library as well.
