### ISSUE TITLE
test xml files for opensheetmusicdisplay 0.3.0 with errors

### ISSUE THREAD

**Issue by oleviolin** [opensheetmusicdisplay/opensheetmusicdisplay#254]
[Testxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2002264/Testxml.zip)
includes two files. One is generated with Muscore, it does not render with version 0.3.0 (the application chokes i.e. stops working totally, and the browser tab must be closed)
The other one looses some information in part 2.3 (not in the first part) in the beginning of each repetition.
Both files render fine with a very old vexflow.musicxml.js.

I hope you can use these files.
Question is there a older version of opensheetmusicdisplaythat will render chords and repetition marks (that vexflow.musicxml.js does not render)

**Comment by bneumann** [comment]
Hi, thanks for the vast information and debug material. I will have a look at it when I find some time.
You can try the opensheetmusicdisplay version 0.2.1 but I am not sure if it has chords in there.

**Comment by matt-uib** [comment]
@oleviolin thanks for the test file! @bneumann will check out the freeze and i will check out the repetitions.

**Comment by matt-uib** [comment]
Dear @oleviolin, i just checked the NinskaBanja_LoosMeasures.xml file for the problems with repetitions and can only see that the two endings (ending 1 and 2 voltas) at the first repetition are missing, when i compare it with the output of musescore. This is clear, as we have an open issue on implementing the rendering of endings. It seems, that you mean something else, right? Or is it that?

**Comment by oleviolin** [comment]
![errordescription](https://user-images.githubusercontent.com/14174047/40086923-a8bac706-58a0-11e8-845f-6c1dea017114.gif)

The problem is that the notes for 2nd and 3 parts are dropping out. just after a repetition mark.

other problems is:
Exporting this xml from muscore and loading kills the browser.
UTF-8 letters not supportet.

I did not mention this before, but I cannot reload the music with javascript, I must reload the complete page, which is not very nice.

**Comment by oleviolin** [comment]
http://lyoe-oelejr.dk/nodetest/demo1/BrowserKiller.php
This code kills the tab of Chrome
<!DOCTYPE html>
<html>
<head>
<meta  charset=utf-8" />
<script src="opensheetmusicdisplay.min.js"></script>
<script>
function loadOSMD(){
  var openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("container-id");
  openSheetMusicDisplay
    .load("NiskaBanja_DoesNotRender.xml")
    .then(
      function() {
        openSheetMusicDisplay.render();
      }
    );
}	
</script>


</head>
<body onLoad="loadOSMD()">
Niška Banja
<div id="container-id"></div>

</body>
</html>

**Comment by matt-uib** [comment]
@oleviolin thanks for the perfect description - i don't know how i overlook that :-) now it is clear!

**Comment by bneumann** [comment]
@matt-uib I had a look at the crashing file. It happens in the Fraction.ts line 62:
```javascript
while (b !== 0) {
      if (a > b) {
        a -= b;
      } else {
        b -= a;
      }
    }
```
b becomse NaN which causes the while loop to hang. This should not happen and I will take a look why it is NaN in the first place. But for the time being this is a common bug, sorry feature, in Javascript and we should prevent entering the while loop in that case

**Comment by matt-uib** [comment]
@bneumann thanks for checking it out. Yes i fully agree - we have to avoid the NAN here in the while loop, as this often happened when somesthing else went wrong in the parsing and sheet calculations. But o course we need to eliminate the real cause of the NAN as well. I will have a look into that, ok?

**Comment by matt-uib** [comment]
@oleviolin @bneumann i checked out the problem with "NiskaBanja_DoesNotRender.xml" - reason is the compare bug inside RepetitionInstruction. The fix is already available in pull request #251. With that it renders. We will try to soon include this and make a new release.

**Comment by matt-uib** [comment]
just checked also the other file - also shows the missing notes with that fix!

**Comment by bneumann** [comment]
@oleviolin @matt-uib this is done right? Both files work now in develop
