### ISSUE TITLE
Last notes in measure sometimes rendered outside of measure

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#255]
See e.g. Elite Syncopations measure 50 in standard zoom:
![grafik](https://user-images.githubusercontent.com/17180665/40082246-b70dfa22-5890-11e8-92b0-c4f859707b01.png)

**Comment by bneumann** [comment]
@matt-uib I found the error. The rest note in the first line is not set correctly. The duration is given as 0.75 which is then returned as "h" for half a note. Seems the Vexflow Converter does not take the timing into account because the piece is 3/4 which makes the rest a "w" in vexflow speak

**Comment by bneumann** [comment]
Just checked the Joplin piece you mentioned and from the XML it looks like the 1st voice skips consists of 4 16th while the timing is 2/4 which means 1/4 too less. 
As far as I can see vexflow does not support "filling" the rest of the beat so we actuall need to manually insert a break here :(

**Comment by matt-uib** [comment]
fixed by filling not shown rests by ghost objects.
