### ISSUE TITLE
Write Sheet Music Tester

### ISSUE THREAD

**Issue by acondolu** [opensheetmusicdisplay/opensheetmusicdisplay#26]
Like for the apps.

**Comment by bukaznik** [comment]
1. exception test for library
2. visual comparison test

**Comment by matt-uib** [comment]
The Music sheet tester should do the following:
It iterates through a list of music pieces and performs:
- read music sheet (using MusicSheetReader)
- calculate graphical music sheet (using MusicSheetCalculator)
If an error occurres it stops and returns false plus the error and the corresponding sheet as log message.

the list of music pieces should be hidden and not accessable to the public if possible.

**Comment by bukaznik** [comment]
use http://openmusicscore.org/index.php?option=com_content&view=categories&id=79&Itemid=531 as sample sheet music
