### ISSUE TITLE
Support standalone-vexflow-context

### ISSUE THREAD

**Issue by javiercbk** [opensheetmusicdisplay/opensheetmusicdisplay#267]
I would be really useful for react-native users to have this library support [this browser independent vexflow](https://github.com/panarch/standalone-vexflow-context).

This would allow others to make native app with this wonderful library.

**Comment by bneumann** [comment]
Hi,
 
from what I remember vexflow enabled react native support quite a time ago. I also did a react app with it and had no problems. 
What is the reason it does not work at the moment?

**Comment by javiercbk** [comment]
From what I understand, it seems that other developer created an independent context to use with react native but he did not make a PR to vexflow and the issue is still open.

I assumed that this library would not work with react native by looking only the code BUT I haven't test this.

I wasted enough of your time, I'll get my hands dirty and try to make it work with react native, if it doesn't I'll reopen this ticket with more information.

**Comment by sschmidTU** [comment]
just in case anyone reads this in the future, the context/canvas should be able to be replaced using JSDOM and perhaps cross-blob, see our node script that generates PNG images without a browser:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/test/Util/generateImages_browserless.js
