### ISSUE TITLE
Color and visualize two bars

### ISSUE THREAD

**Issue by davidsancal** [opensheetmusicdisplay/opensheetmusicdisplay#268]
Hello, I have seen the question Color the bar #207 but I can not color the bars of sixteenth notes and if I introduce the mentioned changes when I put a color the title and other parts are colored. I would also like to know if you could visualize two bars in the score. Thank you

**Comment by bneumann** [comment]
So you have tried the branch I mentioned?

**Comment by davidsancal** [comment]
Yes, but if in each of the voices I put a color it is when I paint the title and other parts. I would like to be able to paint each voice in a different color, I do not know if it would be possible.

**Comment by bneumann** [comment]
Hmm I think it is but ionly implemented a general method for colorization in the mentioned branch

**Comment by sschmidTU** [comment]
Coloring each voice in a different color would be a nice option.
Should be put cleanly into a new issue though.
