### ISSUE TITLE
Autobeam

### ISSUE THREAD

**Issue by acidjunk** [opensheetmusicdisplay/opensheetmusicdisplay#275]
Hi, I'm experimenting a bit with opensheetmusic display. I like it a lot :) 

I'm running a platform that uses lilypond format and I'm in the progess of switching to MusicXML. I run into a rendering difference between Muse score and OpensheetMusic (or vexflow?)

First the render as it's done in Musescore when I open the xml:
<img width="894" alt="screen shot 2018-06-25 at 08 56 28" src="https://user-images.githubusercontent.com/685002/41834772-ad5167be-7855-11e8-8421-94cf5678f48b.png">

Now the same render but then from opensheetmusicdisplay:
<img width="1213" alt="screen shot 2018-06-25 at 08 57 29" src="https://user-images.githubusercontent.com/685002/41834827-d6ff8f64-7855-11e8-866f-285b0440ab98.png">

The used XML: https://api.improviser.education/test-musicxml

As I do some processing to get a valid MusicXML (Concat lot's of small Lilypond strings to MusicXML), I'm not sure where to start searching. Do I need something in my Music XML to enable autobeam on each quarter note?

**Comment by bneumann** [comment]
Hi @acidjunk,

thanks for reporting this. I am not sure, maybe @matt-uib has something up his sleeve that might help with autobeaming. Usually music xml does group notes that share a beam with the ```<beam>``` tag inside the note tag, like so:

```XML
<note default-x="158">
    <pitch>
        <step>D</step>
        <octave>5</octave>
    </pitch>
    <duration>12</duration>
    <voice>1</voice>
    <type>eighth</type>
    <beam number="1">begin</beam>
</note>
<note default-x="206">
    <pitch>
        <step>E</step>
        <alter>-1</alter>
        <octave>5</octave>
    </pitch>
    <duration>12</duration>
    <voice>1</voice>
    <type>eighth</type>
    <beam number="1">end</beam>
</note>
```

So you could implement this in your parser and have full control over your beams, or as said maybe there is some hidden gem in the code :)

**Comment by acidjunk** [comment]
Ah cool, I like total control :)
I will try to update my parser tomorrow.

I think it would be a nice option if opensheetmusic display could use the VexFlow autobeam function (e.g. with a configuration option or something when stuff is initalised)

**Comment by bneumann** [comment]
Wait, vexflow has autobeaming? If so this might be very simple

**Comment by bneumann** [comment]
Note to self: 😁

https://github.com/0xfe/vexflow/wiki/Automatic-Beaming


This sounds pretty straight forward. @matt-uib your opinion? Should we implement that? Or maybe have an option for it?

**Comment by sebastianhaas** [comment]
I guess it would be nice it it was possible activate it per configuration. :)

**Comment by sschmidTU** [comment]
I added an autoBeam option to beam notes that don't have beams in XML.
Added OSMD Function Test - AutoBeam:
![image](https://user-images.githubusercontent.com/33069673/47177504-dd489f00-d318-11e8-8028-2c3cd72249b7.png)

With autoBeam disabled:
![image](https://user-images.githubusercontent.com/33069673/47177525-e8033400-d318-11e8-8c01-2a1685060ecf.png)

You can also set autoBeamOptions like how many beats to beam together (groups), see the AutoBeamOptions interface.

To enable autoBeam during runtime in the Demo, write `osmd.setOptions({autoBeam: true})` in the console.
(If you already have the function test selected, click clear and Re-render)

By the way, here's a regular expression to remove all beams from a MusicXML:
`^[ ]*[<]beam.*$`

If you still have improvements to suggest, feel free to keep commenting.

**Comment by acidjunk** [comment]
That's really cool and it's looks nice on my musician eyes. Will try it on a new part of the https://improviser.education tomorrow. If you need any help in OSMD let me know: i'm quite new to javascript (focussing mainly on ES6 + ReactJS nowadays) but 'll have some time the coming weeks.
