### ISSUE TITLE
Create overview sheet music structure

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#28]
publish in wiki
use http://typedoc.io/

**Comment by acondolu** [comment]
https://opensheetmusicdisplay.github.io ?

**Comment by oliver-h** [comment]
The intention was to create an overview/visualization on how the musicsheet is structured, which classes are involved and so on (the musicsheet has pages, the page has systems, somewhere there is this verticalstaffentrycontainer, ....)

**Comment by bneumann** [comment]
@sschmidTU has done that in the wiki. Clos?

**Comment by sschmidTU** [comment]
Yes, i updated the Wiki.
Wiki pages like [How OSMD processes Sheet Music](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/How-OSMD-processes-Sheet-Music),
[Music Sheet Object Model](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Music-Sheet-Object-Model)
and [Directory Layout](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Directory-Layout) (which also gives a summary of individual classes)
sum up to a decent overview of the project's structure, i think.
