### ISSUE TITLE
Measure numbers overlap chords

### ISSUE THREAD

**Issue by zwiebelspaetzle** [opensheetmusicdisplay/opensheetmusicdisplay#285]
Chords and measure numbers sometimes overlap.  Is it possible to turn off display of measure numbers?  Or to move the chord letters higher?

Thanks!

**Comment by bneumann** [comment]
Hi, thanks for mentioning. This will be fixed with PR #270. Unfortunately it might take some time then for the next release

**Comment by bneumann** [comment]
PR is through, this should be fixed
