### ISSUE TITLE
Global config class

### ISSUE THREAD

**Issue by bneumann** [opensheetmusicdisplay/opensheetmusicdisplay#288]
There should be a global class (singleton?) that can be configured on startup for things like:
- debugging (skyline, bounding boxes, ...)
- Autobeam
- Autostem
...

Remakr: Reuse .\MusicalScore\Graphical\DrawingParameters.ts for this

**Comment by sebastianhaas** [comment]
What about adding an `option` parameter to the [`OpenSheetMusicDisplay `constructor](https://opensheetmusicdisplay.org/classdoc/classes/opensheetmusicdisplay.html#constructor)?

We could move `autoResize `and `backend` in that parameter as well, e.g. create an Interface that specifies all options that can be set:

```typescript
interface OSMDOptions {
  autoResize: boolean;
  backend: OSMDBackend;
  autoBeam: boolean;
  autoStem: boolean;
  [...]
}

OpenSheetMusicDisplay(container: string | HTMLElement, options?: OSMDOptions)
```

**Comment by bneumann** [comment]
Sounds good, I really like the interface idea. It would also support common js objects then?

**Comment by sebastianhaas** [comment]
yes, absolutely. e.g.:

```javascript
var osmd = new OpenSheetMusicDisplay(container, {
  autoStem: true;
});
```

(which could be TypeScript or JS)

**Comment by bneumann** [comment]
I just wondered why you wrote such bad words like global and singleton. Then I saw that I came up with that. Sorry about that. Of course we'll take the interface. Have to see how we propagate the data through all our modules
