### ISSUE TITLE
Render Dynamic Wedges (VexFlow: StaveHairpin)

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#290]
![grafik](https://user-images.githubusercontent.com/17180665/42369197-848f2ab6-8109-11e8-8fd3-f201fa7fb8f7.png)

As first step, find out how to render Wedges in Vexflow:
As an example, go to 
http://public.vexflow.com/tests/
and look at the source code at
public.vexflow.com/tests/stavehairpin_tests.js

**Comment by matt-uib** [comment]
![grafik](https://user-images.githubusercontent.com/17180665/42370096-2b2cbc9c-810c-11e8-9f64-5443762e2dac.png)

Is it also possible to draw a "continuing" wedge like shown here?

**Comment by bneumann** [comment]
I am confused, isn't that part of the expressions feature?

**Comment by sschmidTU** [comment]
@bneumann i don't know, but in the expressions branch, i could not find code producing wedges (or crescendos).
I tried the StaveHairpin class and it seems like for now these hairpins can only go over one stave. Though that would be nice to have for now. If we want continuing wedges over multiple staves and systems, we might have to extend StaveHairpin in VexFlow.

**Comment by bneumann** [comment]
It's in the dynamic expressions object. I have not yet implemented it but I wanted to use the stave pins for that. @matt-uib comments?

**Comment by bneumann** [comment]
But I checked the vexflow implementation and they only offer closed pins. But it would be really simple to extend that in vexflow itself. I vote for fixing it there and asking for a release

**Comment by sschmidTU** [comment]
you mean StaveHairpins, right? yes. we should probably extend it in Vexflow, it's a bit limited now.
While we're at it, we can fix that this line calls pixelsPerTick, which doesn't exist.
```
const ppt = formatter.pixelsPerTick;
```

Of course, if you're already working on this, i'm happy if you can implement the wedges, i'm also working on other issues.

**Comment by matt-uib** [comment]
Sorry for the confusion - @bneumann i wanted to know what vexflow has to offer here, also regarding our last discussion about y-layout. So it's good to know that this is also not possible right now in vexflow. Yes it could be an option to extend their StaveHairpin or we simply use rendering a line - we have to calculate the lines completely in our code in MusicSheetUnits anyway as it seems...

**Comment by matt-uib** [comment]
Let's leave it for at this point - for the next steps we need some decisions and then new issues.
