### ISSUE TITLE
Draw Grace Notes 

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#293]
Implement drawing grace notes as smaller notes with VexFlow.

**Comment by sschmidTU** [comment]
@matt-uib Shouldn't we use VexFlow's GraceNote system? We could simply add a Vex.Flow.GraceNoteGroup to a StaveNote as a modifier, see here:
https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ#how-do-i-display-grace-notes

(it also has somewhat hacked support for slurs via `StaveTie`s, [see here](https://github.com/0xfe/vexflow/issues/154))

Of course, we could also draw grace notes manually as smaller notes as you suggested, but it seems we'll need some extra x-layouting then.

In any case, i thought i should complete or at least consider the Grace Notes refactor (#56) first.

**Comment by matt-uib** [comment]
@sschmidTU Ah, you misunderstood me there - of course we shall use their grace note system!

**Comment by sschmidTU** [comment]
Done and merged into develop. There doesn't seem to be any grace note drawing functionality missing now.
Note that in the current commit, a custom VexFlow build has to be used, until their next release (see #286).
