### ISSUE TITLE
Dot of dotted notes gets vertically misplaced after redraw

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#300]
After changing zoom level or resizing the window in the demo, the dots of dotted notes get shifted upwards, when using a Vexflow master build. On the initial load of the demo, the dots are placed correctly.

![dot_misplacement_zoom_illu](https://user-images.githubusercontent.com/33069673/43149571-02ec5124-8f68-11e8-8ad2-471352f978d6.png)
In the image, the zoom is set to 120, then back to 100, causing the same shift.
The shift seems to be exactly half a line distance per zoom.

This seems to be a regression ~~caused by recent formatting or other changes~~ in the Vexflow master since last release, since the issue is not present in our [last release demo](https://opensheetmusicdisplay.org/demo/) or when using a fresh npm install of Vexflow.

**Comment by bneumann** [comment]
Maybe correlated to the setX changes we made?

**Comment by sschmidTU** [comment]
why setX? this is a y issue.
formatter.format is not the issue btw (just checked)

**Comment by bneumann** [comment]
Haha... Yes

**Comment by sschmidTU** [comment]
@bneumann Actually our Vexflow patch caused this bug. Oops!
If you replace the vexflow-debug.js in our node_modules_vexflow/releases with the still current vexflow release instead of our master branch build, this dot shift doesn't happen.

I'll look at [our fix](https://github.com/0xfe/vexflow/pull/632/commits) and try to fix it. It's weird, because we only touched ornaments, and x-shift, not y-placement. But it would be nice if we don't introduce bugs to the Vexflow repo ourselvels ;)

**Comment by sschmidTU** [comment]
@bneumann Actually our Vexflow master branch build caused this bug, not the code from our fix. Because we built our patch build from the master branch of Vexflow, which seems to have other new commits integrated compared to the last vexflow release, and one of these is causing the issue.

If you replace the vexflow-debug.js in our node_modules_vexflow/releases with the still current vexflow release instead of our master branch build (or just checkout a branch with a fresh npm install), this dot shift doesn't happen.

So for now, we can take the build from the last Vexflow release and just apply the patch there.

**Comment by sebastianhaas** [comment]
> by the way, there's some caching issues with npm modules and/or Chrome, so sometimes just replacing the files in /releases doesn't affect our local build.

are you on Windows? Webpack dev reload is having troubles big time with Windows file handles, take a look at the Ionic forums... ;) Obviously that doesn't help a lot but it's good to know the many times fixing one part of a problem in file A then another one in file B often results in webpack serving a cached, unchanged version of A again. I ended up using vagrant or a full VM for webpack intense work in the last months... jfyi.

**Comment by sschmidTU** [comment]
@sebastianhaas that's good to know, thanks! yes, i'm on Windows right now because of Visual Studio for the App. but otherwise VS Code etc works fine.

**Comment by sschmidTU** [comment]
So, i'll try to find the faulty code in the master branch of Vexflow, or at least create an issue there.

**Comment by sschmidTU** [comment]
Found the issue, it's a [one-character fix gone wrong](https://github.com/0xfe/vexflow/commit/298cd8813e0a545c31fb312bd9f7dfa31e634e17) in Vexflow. If you remove the +, our dot shift doesn't happen.
I'm creating a PR for them fixing their fix, which was just intended to position the dot for dotted rest notes correctly.

**Comment by sschmidTU** [comment]
Again a bug when doing multiple draws with Vexflow by the way. They really don't test this a lot.

**Comment by bneumann** [comment]
I guess it's not a use case. But one of the things we should mention

**Comment by sschmidTU** [comment]
[PR for dot y-shift](https://github.com/0xfe/vexflow/pull/633) is up.

**Comment by sschmidTU** [comment]
The PR for dot y-shift was merged, so this issue is fixed in the Vexflow master branch, though we'll have to wait for the next Vexflow release.

If you want to try the fix (including ornaments and grace note shift fixes), build the Vexflow master branch yourself with grunt stage and replace the releases/vexflow-debug.js (and .map) in your osmd/node_modules/vexflow/releases.

Or simply take these build files from here:
https://drive.google.com/drive/folders/15U4J_iPXskFkk38SpghvtwmmQvLkww4s?usp=sharing
