### ISSUE TITLE
Reading key signature from XML needs mode attribute set

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#302]
An XML without the mode attribute set does not display the key signature:
![image](https://user-images.githubusercontent.com/33069673/43152145-06496eb4-8f6e-11e8-9c2b-ad3657590f44.png)

It works with the mode attribute set:
```
        <key>
          <fifths>2</fifths>
	  <mode>major</mode>
          </key>
```
![image](https://user-images.githubusercontent.com/33069673/43152439-cfab7ad6-8f6e-11e8-8016-afb2a3c6c3e6.png)

However, it should also work without the mode attribute set, as Musescore exports it, since it does not need to be decided whether a piece is minor or major:
```
	<key>
	  <fifths>2</fifths>
	  </key>
```

**Comment by sebastianhaas** [comment]
That may be something I caused, as far as I remember I did some work on the vexflow converter back in the days. We do have component tests on this, and I think I followed the MusicXML specs pretty closely so it might be worth checking if Musescore is actually following the specs here ;)
