### ISSUE TITLE
add build .js files to repo

### ISSUE THREAD

**Issue by supersational** [opensheetmusicdisplay/opensheetmusicdisplay#333]
Requesting that the `build/opensheetmusicdisplay.min.js` and `build/opensheetmusicdisplay.js` files be added to the repo.

This would allow easy linking, (and to different versions) using https://rawgit.com/ 

Hopefully a simple request, this is a fantastic project btw!

**Comment by bneumann** [comment]
Hi, thanks for the request but usually build files should not be included in a repository.
Anyways there if there is a demand for pre-built libraries you can use a CDN service. I just checked and it seems jsdelivr has our npm package:

https://www.jsdelivr.com/package/npm/opensheetmusicdisplay

We should check if we can also provide it over cdnjs

**Comment by sschmidTU** [comment]
Vexflow uses both rawgit and npmcdn for jsfiddles (interactive demos). They also host the builds on their website and include it in the repo. They're a bit all over the place.
Of course we don't need to follow Vexflow in that regard.

@supersational if you type in https://unpkg.com/opensheetmusicdisplay, it will direct you to https://unpkg.com/opensheetmusicdisplay@0.3.1/build/opensheetmusicdisplay.min.js.
That should be all you need, right?
By the way, we should be making a new release with big improvements soon.

**Comment by supersational** [comment]
Thanks, that solves most of my problems! 
Is there any link to the unminified library? I'm getting errors rendering certain musicXML files and being able to link to either unminified source or a source mapped library would help debugging. I am currently injecting into pages I don't have control of so can't use webpack.

**Comment by supersational** [comment]
looking into it I think it needs to go into the 'files' field, see https://docs.npmjs.com/files/package.json#files
```
"files": [
...
    "build/opensheetmusicdisplay.js",
```

should add it to unpkg

**Comment by bneumann** [comment]
You are right that would be an easy fix

**Comment by supersational** [comment]
Sweet, look forward to the new release!

**Comment by sschmidTU** [comment]
@supersational I created a PR for this, #335. If you have any input, go ahead. This is your chance to influence the debug.js you'll receive ;)

**Comment by sebastianhaas** [comment]
Would be interesting to learn about how people are actually using/including OSMD. I guess we should look into the cdn option anyway.
@bneumann let's discuss that in another issue? Afaik cdnjs, Google Hosted Libraries, Fastly, jsdelivr etc. all offer free hosting for Open Source libraries, we just need to apply there.

Regarding npm package: Ofc we can do that, I'm just wondering if it makes a lot of sense. Usually, when including OSMD via npm, we're in a Node-powered (webpack, browserify, Ionic, Angular whatever) environment where build tools will automatically pick up the minified version and include it in the respective build. The library file is determined using the `main` field in our `package.json`- so if somebody wanted to debug OSMD in a scenario like that, they would have to browse to `node_modules/opensheetmusicdisplay/package.json` and manually edit the entry point which is something that you probably don't want to do. Any npm install will wipe those changes. If somebody is not retrieving OSMD via npm, but downloads the bundle from Github we don't have this issues. We might just might want to include it as release asset: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases/tag/0.3.1.

Anyway, we should take a look at other libraries, e.g. Angular, rxjs etc. and see how they do it. They all include source maps in their npm packages. That is probably the way to go.

**Comment by sschmidTU** [comment]
Good idea to look at other packages. Just adding the source map for the minified version seems like the best option to me at the moment, as i wrote in #335. Not sure if we need to add the debug file as well.

**Comment by supersational** [comment]
Just to clarify my pain-points using the library here: 

The main website says use `<script src="opensheetmusicdisplay.min.js"></script>` however no link is provided where to download the minified library. You need to know to look in the non-obvious 'releases' tab on GitHub.

I'm encountering an error in the library rendering empty scores. Currently to switch to the unminified bundle requires downloading and building the whole project from scratch, and uploading it so I can link to it, at that point I'm not 100% sure the version numbers are the same (is there a 'version-number' property included in the JS somewhere?). 

Having a link to a CDN would solve these problems (ideally with source maps or an unminified version), and would be useful if it was linked to on the main page.

FYI, I'm trying to use it with music21 in a jupyter notebook, [issue linked here](https://github.com/cuthbertLab/music21/issues/306).

**Comment by sschmidTU** [comment]
The main website will be overhauled soon, you're right that it could be clearer.

I agree that an unminified release or source map would be helpful. I'll see if we can get it into a CDN, while still trying not to pollute our git or npm package with too many binaries.

Thanks for the input! By the way, it's interesting that you get an error rendering empty scores, we should fix that. If you could give me a StackTrace, that would be perfect. But i might just start looking into it myself anyways.

**Comment by sschmidTU** [comment]
@supersational We published a [new release 0.5.0 on Github](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases/tag/0.5.0). I added the source map along with the build.
You should be able to use these with RawGit or hopefully import from anywhere, because they have static links.

**Comment by sschmidTU** [comment]
@supersational Since the new OSMD 0.5.1 release, you can now run `npm run build webpack-sourcemap` on the cloned repository, which will give you a .min.js.map file in the build/ folder.
Also, `npm run build webpack-dev` will give you a non-minified debug build as before.

**Comment by sschmidTU** [comment]
source map is added, but non-minified debug build would probably bloat our npm release too much.
if the argument is debugging, source map should be enough, otherwise you can run the npm build as described above.
