### ISSUE TITLE
Slurs fixes

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#334]
There are a few small issues that would be nice to fix before the new release.

In our Schumann - Dichterliebe sample, we get an error:
TypeError: Cannot read property 'x' of undefined at VexFlowMusicSheetDrawer../src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts.VexFlowMusicSheetDrawer.drawSlur

And in Land der Berge, it looks like the Bezier curve points are a bit misplaced, probably because the piece has two voices with two slurs a lot. Maybe the problem is that both voices and starting notes for both slurs are very close to each other.
![image](https://user-images.githubusercontent.com/33069673/44580803-a1231300-a79b-11e8-80d7-e8b1373d8423.png)

Strangely, in a similar later part (bar 24), it looks fine.
![image](https://user-images.githubusercontent.com/33069673/44580820-b4ce7980-a79b-11e8-8fb8-b2a2ae2138d9.png)

**Comment by matt-uib** [comment]
Reason are crossed slurs (from one staffline to another) in Dichterliebe, where the calculation is still missing...
For the anthem, there was a mistake in the placement: if lyrics: place above! I changed that to only be used if there is only one voice.
