### ISSUE TITLE
Question: Accessing Cursor Note / Notes

### ISSUE THREAD

**Issue by clintmasden** [opensheetmusicdisplay/opensheetmusicdisplay#339]
Is there currently a way to access what note is being highlighted by the cursor or a way to get retrieve an array of notes being converted by MusicXML?

**Comment by matt-uib** [comment]
You can get that info via the iterator in the cursor (is currently a private member):
e.g. with this code:
this.iterator.CurrentVoiceEntries[0].Notes[0].halfTone
..to get midi semitone of the first note at the current cursor position.

**Comment by clintmasden** [comment]
That answered the question!  Thank you again Matt.

**Comment by matt-uib** [comment]
Let's leave your issue open for now, as it might be of interest to others - ok? (we had already a simmilar question in a closed issue before).

**Comment by sschmidTU** [comment]
though if people are not looking for already asked questions in closed issues, they are probably also not looking for it in open issues. I prefer having issues open only if they are unsolved and relevant, so in my opinion this should be closed.
If the same question comes up again, one can just reference the solved issue, and close the new one.

**Comment by matt-uib** [comment]
yes right in principle, but it seems that Github shows only open issues by default and people seem to look only into these... @clintmasden, i guess it was like this for you, right?
Maybe we should move answered questions to the wiki and add some kind of Q&A - i think this would make most sense.

**Comment by clintmasden** [comment]
@matt-uib I was going to suggest adding a WIKI / FAQ section.  I did look through the closed issues to find this answer and couldn't find anything related.  BTW I'm surprised how fast you responded which is awesome.

**Comment by bneumann** [comment]
@clintmadsen yeah we really should do that. But then again accessing stuff in opensheetmusicdisplay will be done with proper access in the future. For now the method @matt-uib suggests works quite okay

**Comment by clintmasden** [comment]
@bneumann, yup his method works perfectly, which is why i closed the issue/question at the beginning =)
