### ISSUE TITLE
Implement Arpeggios

### ISSUE THREAD

**Issue by ChrisUib** [opensheetmusicdisplay/opensheetmusicdisplay#343]
![image](https://user-images.githubusercontent.com/33069673/44660302-7ccb6e80-aa07-11e8-9e7a-ada65435cf5c.png)
e.g. 2nd bar in Debussy - Mandoline:
![image](https://user-images.githubusercontent.com/33069673/44660230-50afed80-aa07-11e8-97f8-be5d911bf287.png)
Vexflow can do this, so it should be easy for us as well.

**Comment by sschmidTU** [comment]
Downward/Upward done in PR #411.

For directionless, i implemented them in Vexflow [PR #658](https://github.com/0xfe/vexflow/pull/658).
As soon as the PR is through (and maybe we get a new Vexflow release), they will be trivial to add to OSMD.

**Comment by sschmidTU** [comment]
Done including neutral arpeggios, see #411.
Also added to our function test.
![image](https://user-images.githubusercontent.com/33069673/46734639-2f901d00-cc94-11e8-9b07-a45efd526199.png)
