### ISSUE TITLE
Implement Glissando lines

### ISSUE THREAD

**Issue by ChrisUib** [opensheetmusicdisplay/opensheetmusicdisplay#344]
**Glissando lines**, horizontal:
![image](https://user-images.githubusercontent.com/33069673/44661122-eea4b780-aa09-11e8-848d-613d9ebcb899.png)

**Comment by sschmidTU** [comment]
Main implementation done in #1318, for advanced features new issues should be opened (like `gliss.` text and wavy lines), see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1318#issuecomment-1412898062.
