### ISSUE TITLE
Implement Fingering information display

### ISSUE THREAD

**Issue by ChrisUib** [opensheetmusicdisplay/opensheetmusicdisplay#350]
**Fingering**
Vexflow:
![image](https://user-images.githubusercontent.com/33069673/44661443-fe70cb80-aa0a-11e8-9ced-eb8837674fe1.png)

MuseScore:
![image](https://user-images.githubusercontent.com/33069673/44661576-57d8fa80-aa0b-11e8-9f96-374471f89f52.png)

**Comment by sschmidTU** [comment]
Done as Left-side fingering by Vexflow (see above) in (628562bdc2d7987f42ec5b1a258238347acb463f).
For right, above and below, see #406.

**Comment by sschmidTU** [comment]
Right, above, below and auto position options are implemented now in #406.
I'll merge and close this as the y-options are marked as experimental, and we can always improve them with better layouting (using Labels) in the future.

The auto option gives a good overview:
![image](https://user-images.githubusercontent.com/33069673/46759815-97fcef80-ccd0-11e8-8a60-833f843398bf.png)

Description of #406 updated, more details there.
