### ISSUE TITLE
Correctly display arbitrary tuplets

### ISSUE THREAD

**Issue by ChrisUib** [opensheetmusicdisplay/opensheetmusicdisplay#351]
**Arbitrary Tuplets**
![image](https://user-images.githubusercontent.com/33069673/44661698-bd2ceb80-aa0b-11e8-898d-ede47feb23e0.png)
This should display 5 and 3, not 5:2 and 3 (like in Musescore).

**Comment by sschmidTU** [comment]
I fixed ratios and brackets:

Before (OSMD 0.5.0):
![image](https://user-images.githubusercontent.com/33069673/46098094-dcae6400-c1c3-11e8-9e2d-5a99725d6c6c.png)

After:
![image](https://user-images.githubusercontent.com/33069673/46098133-f6e84200-c1c3-11e8-8d8e-0856015c0f5a.png)

You can also set whether to print ratios and brackets for all tuplets (plus special setting for triplet brackets) as EngravingRule and OSMDOption.

Many pieces have long sequences of triplets, and making them all bracketed looks too cluttered:
![image](https://user-images.githubusercontent.com/33069673/46098253-43338200-c1c4-11e8-887e-2df173abf528.png)
(Clementi Sonatina Op. 36 No. 1 Part 2)
