### ISSUE TITLE
Implement displaying copyright etc

### ISSUE THREAD

**Issue by ChrisUib** [opensheetmusicdisplay/opensheetmusicdisplay#353]
**Score properties**
MuseScore offers these properties.
For MusicXML there's `<identification>` including `<rights>` (copyright).
https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-identification.htm
There's `<work>` including `<work-title>`, but nothing for subtitle specifically.
https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-work.htm

We don't need to put all these in the score, but copyright would be nice.
MuseScore displays copyright, the rest in the header was added manually.
MuseScore render of a page + properties editor:
![image](https://user-images.githubusercontent.com/33069673/44664879-cbcbd080-aa14-11e8-88c8-7d4347c71093.png)

**Comment by bneumann** [comment]
What do you think about mouse over? We are developing for the web so we can also use some established patterns. Or something like the three dots menu for this kind of stuff
