### ISSUE TITLE
Error rendering empty score

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#358]
[As supersational reported in #333](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/333#issuecomment-416592023), loading an empty score causes an error.

StackTrace:
```stacktrace
Uncaught TypeError: Cannot read property 'Staves' of undefined
    at new GraphicalMusicSheet (GraphicalMusicSheet.ts:33)
    at OpenSheetMusicDisplay../src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts.OpenSheetMusicDisplay.load (OpenSheetMusicDisplay.ts:126)
    at selectSampleOnChange (index.js:219)
    at FileReader.reader.onload (index.js:311)
```

this is because MusicSheetReader.createMusicSheet() returns undefined in OpenSheetMusicDisplay.ts:125

I'll look into it.

<details>
<summary>XML causing the error</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<score-partwise version="3.0">
  <identification>
    <creator type="composer">Music21</creator>
    <encoding>
      <encoding-date>2018-08-22</encoding-date>
      <software>music21 v.5.3.0</software>
    </encoding>
  </identification>
  <defaults>
    <scaling>
      <millimeters>7</millimeters>
      <tenths>40</tenths>
    </scaling>
  </defaults>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
      <part-abbreviation>Pno</part-abbreviation>
      <score-instrument id="Ic248cbee2ba04bcf23dfa435ea191da3">
        <instrument-name>Piano</instrument-name>
        <instrument-abbreviation>Pno</instrument-abbreviation>
      </score-instrument>

    </score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>10080</divisions>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
        </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
      </attributes>
    </measure>
  </part>
</score-partwise>
```

**Comment by sschmidTU** [comment]
I changed it so we return a sensible error ("given music sheet was incomplete or could not be loaded.") plus stacktrace instead of "Cannot read property 'Staves' of undefined" and a much longer stacktrace.
![image](https://user-images.githubusercontent.com/33069673/45027083-a6584b80-b040-11e8-8ea4-4f8b391c8df6.png)
(only on branch so far, 87960d21090dd7723ee314173b75d501d6ffcd84)

Is this fine or shouldn't we return an error at all?
I think returning an error is okay, because you shouldn't try to render an invalid MusicXML in the first place.
It's not so easy to just do nothing because many of our methods assume we have a valid score with measures in it and so on.

**Comment by sschmidTU** [comment]
Now we can load this empty score. It only displays a warning that it found no voices, seems fitting.
![image](https://user-images.githubusercontent.com/33069673/45028809-c25eeb80-b046-11e8-833a-34820f5d2df8.png)
I improved error handling in a few places, like parsing and undefined voices.

**Comment by sebastianhaas** [comment]
What does the standard say about it?

**Comment by bneumann** [comment]
You mean the music xml standard?

**Comment by sschmidTU** [comment]
The empty score has measures without notes, i think that was OSMD's problem.
The MusicXML XSD says measures only need a _number_ attribute. I think. Not sure why the _Occurs_ column says _1..1_ for almost every component.
http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-measure.htm

Now having no notes in a measure will not produce an error and an undefined MusicSheet anymore.

**Comment by bneumann** [comment]
Easiest way is to validate against the schema. But I think musescore does that. By the way which musicxml versions are we supporting?

**Comment by sschmidTU** [comment]
Validating against the schema would avoid parsing exceptions, though we have to be careful in case some sheet music program's XML export doesn't produce 100% valid MusicXML, but would still be readable for us.

It seems like we support MusicXML 2.0 to 3.1, judging from our demo sample files:
Elite Syncopations is 2.0 (Finale 2005 export),
Saltarello is 3.0 (Finale 2011 export),
Land der Berge is 3.1 (MuseScore export)
