### ISSUE TITLE
New Release 0.5.0

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#369]
Edit: OSMD 0.5.0 is released, adding slurs, dynamics, grace notes, ornaments and much more.
[See Changelog](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/CHANGELOG.md)

0.5.0 is available as [Github release](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases/tag/0.5.0), tag and push to master.
I attached the source map to the release assets for people who want to debug OSMD.

[Npm package 0.5.0](https://www.npmjs.com/package/opensheetmusicdisplay) is live as well.

You can try the new release in our Demo:
https://opensheetmusicdisplay.github.io/demo/

---
Old comment:

We will release a new OSMD version tomorrow (Wednesday, September 5 2018), in time for a public presentation.

This will mean a new npm release, a git tag, a Github release with assets files, etc.

What about the version number? Since the last release 0.3.1 we added dozens of new features and fixes, so for me, 0.5 would be a more than justified push to the version number.
Remember that 1.0 is not too far away (#338).

I can prepare most of the release, perhaps i will need some help from the release veterans here (@sebastianhaas and others) at some point.

It would be nice to include the new options interface (#368), but it may not be in time, and the most important thing is releasing on time, and testing thoroughly, to make sure the release goes smoothly.

There's also still time to rethink #333, though we can in any case add a source map to Github release assets.

**Comment by sebastianhaas** [comment]
We do have a release checklist document floating around somewhere. You got access to it? Something is broken with the demo, I remember that we had to upload the demo.js every single time after a release @bneumann can you comment on that?

I don't see a chance to get either #333 or #368 done before tomorrow. If you want, we can have a call tomorrow or today and I'll guide you through the process :)

**Comment by bneumann** [comment]
@sebastianhaas it's not broken just stupid but we can fix it. If we rename the sheets folder in the demo page to test/data (or so) it should work. It's just that the demo is looking for the same folder per default which I "fixed" with another webpack build target

**Comment by sschmidTU** [comment]
@sebastianhaas Can you give me publish rights to the npm package? Forgot about that. Same username.

**Comment by sschmidTU** [comment]
Almost done on the Changelog, I rephrased some commit messages and removed unimportant fixes. Added some commits that weren't using angular commit message syntax.

**Changelog:** (WIP)

<a name="0.5.0"></a>
# [0.5.0](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/compare/0.3.1...0.5.0) (2018-09-05)


### Bug Fixes

* **Skyline:** Labels affect height of skyline now. Start and end ([b5f3bcd](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/b5f3bcd))
* **Cursor:** Fix x-position of cursor ([6887f20](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/6887f20))
* **Demo:** Fix console warning on init ([#332](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/332)) ([0845c6d](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/0845c6d))
* **Demo:** Sample file names more consistent ([c9fcbae](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/c9fcbae))
* **Expressions:** Octaveshift line breaks work now ([e2b1780](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/e2b1780)), closes [#309](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/309)
* **In-measure clef layout:** add as NoteSubGroup instead of ClefNote directly. ([97a0043](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/97a0043)), closes [#307](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/307) [#311](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/311)
* **LyricsSpacing:** eliminate overlap between lyrics labels by extending measures ([622f346](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/622f346))
* **LyricsSpacing/Dashes:** reduce lyrics spacing and number of dashes ([7565bb0](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/7565bb01515885ed7b75bf9521f74f582e51bd38))
* **Lyrics:** Shorten lyrics y offset ([0c8eb28](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/0c8eb28))
* **Demo:** add OSMD function test files to index.js ([fe260c0](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/fe260c0))
* **Relative Bounding Positions:** Relative x positions in bounding boxes were not adjusted to note head ([af21d7e](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/af21d7e)), closes [#309](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/309)
* **VexFlowMusicSheetCalculator:** fix vexflow formatting error caused by align_rests = true ([4fa7b4e](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/4fa7b4e))
* **TimeSignatures**: Display Common/Alla Breve time symbols instead of numbers, fix key signature without mode ([6e99997](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/6e999976e06e1f39f15e97647bc727e574d2b0a9)), closes [#305](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/305)
* **VexFlow**: Update to VexFlow version 1.2.85, fixes rerender issues with grace notes, ornaments, etc. ([a840ea3](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/a840ea37678b25c5cd42cee1dfe903cad60d7817))
* **Repetitions**: Fix drawing repetition endings using VexFlow Voltas ([c32ba9d](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/c32ba9dc83e241c42c5060b6fc208b57d96e97ec))

### Features

* **Slurs:** Display Slurs ([1123251](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/1123251d5a85dedc3305f7e1d29ca32bac3d1198)) [#359](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/359)
* **Ornaments:** Display Ornaments ([7032fdc](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/7032fdc484d7c3f28481feba92c8d9294e561b86))
* **GraceNotes:** Display GraceNotes ([3412e9a](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/3412e9a)), closes [#293](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/293)
* **GraceNotes:** Display Grace slur (boolean) ([2525e92](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/2525e92)), closes [#293](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/293)
* **Accidentals:** Display quarter tones, triple sharps/flats ([024b95e](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/024b95e)), closes [#215](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/215) [#284](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/284)
* **In-Measure Clefs:** Display in-measure clefs ([3158eb4](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/3158eb4))
* **NoteHeads:** Add Note Head Shapes (Percussion: Slash, Triangle, Diamond, X) ([#337](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/337)) ([4599d51](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/4599d51)), closes [#327](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/327) [#325](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/325)
* **Lyrics:** Draw LyricsExtends (_), fix lyricsSpacing ([#322](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/322)) ([e9da9e1](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/e9da9e1))
* **Dynamics:** Display Dynamics (Instantaneous expressions) ([29337c9](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/29337c9))
* **Lyrics:** Left-Alignment (default), Center optional, fix lyricsSpacing ([#356](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/356)) ([6205fe3](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/6205fe3))
* **Tempo Expressions:** Add all tempo expressions ([83d59c8](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/83d59c8)), closes [#309](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/309)

**Comment by sschmidTU** [comment]
0.5.0 is out, at least as a [Github release](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases/tag/0.5.0), tag and push to master.
I attached the source map to the release assets for people who want to debug OSMD.

Only thing missing is npm publish. My fault for not asking for npm publish rights earlier.
https://www.npmjs.com/package/opensheetmusicdisplay

**Comment by jimutt** [comment]
Thank you for a great release! Haven't been looking at the project for a while because I've mainly been waiting for the lyrics support to improve. And it's starting to get pretty solid know! You're making really great progress!

**Comment by jimutt** [comment]
@sschmidTU Looking great, looking forward the 1.0 release. I just did a quick experiment making the 0.5 version render and play a choral piece and I'm rather happy with the results. I've been waiting for a viable (and free and OS) solution for rendering multi-voice scores with lyrics on the web and I'm pretty confident that I won't need to look anywhere else now. 

I've got some plans (if I ever get enough time...) for a free to use website/platform mainly targeted towards offering public domain choral works along with interactive tools to let people play and learn new scores without needing to know sheet music. There's lot of great sheet music available on for example CPDL and IMSLP but those wiki-style sites are really not that accessible and welcoming for amateurs.

**Comment by bneumann** [comment]
@jimutt THAT is awesome! Check out our [Roadmap](https://opensheetmusicdisplay.github.io/develop/roadmap/) we also are about to include playback in the future

**Comment by sschmidTU** [comment]
@jimutt wow. it looks like you're ahead of us for [Audio Playback](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/258). Is your code open source?

**Comment by sschmidTU** [comment]
Closed as [0.5.1 is out](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/397).
