### ISSUE TITLE
Incorrect repetition detection leads to crashes

### ISSUE THREAD

**Issue by p-himik** [opensheetmusicdisplay/opensheetmusicdisplay#370]
For example, `RepetitionInstructionReader` uses `StringUtil.StringContainsSeparatedWord(innerText, "d.s.")` which in turn uses `String.prototype.search()` which accepts a RegEx.
Hence, the above check for "d.s." passes also for such text as "dust".

In the end, it crashes at
```typescript
case RepetitionInstructionEnum.DalSegno:
	this.currentMeasure.LastRepetitionInstructions.push(currentRepetitionInstruction);
```
at `RepetitionCalculator.handleRepetitionInstructions` because `this.currentMeasure ` was not set.

**Comment by bneumann** [comment]
Oh that's not cool. You're right about the search method. Must have been from the early days where the knowledge about JS was limited.
I will work on osmd again tomorrow so I can fix that. @sschmidTU should be included in a release

**Comment by p-himik** [comment]
[osmd_370.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2351442/osmd_370.zip)
