### ISSUE TITLE
Main link from GitHub repo is broken

### ISSUE THREAD

**Issue by evanrmurphy** [opensheetmusicdisplay/opensheetmusicdisplay#374]
@sschmidTU thanks for [answering my question about Vexflow](https://github.com/0xfe/vexflow/issues/647#issuecomment-419147658) and for introducing me to OSMD. Connecting MusicXML and VexFlow fulfills an important need, and I'm impressed by the demo at https://opensheetmusicdisplay.github.io/demo/ .

When I was checking out your project I found that the main link at the top of your GitHub repo didn't work for me. It links to https://www.opensheetmusicdisplay.org . When I follow this link, I get an HTTPS warning about the connection not being secure. And if I switch to plain HTTP or remove the `www.` then I get a GitHub 404.

Maybe someone with account privileges could update the link to https://opensheetmusicdisplay.github.io/ ? Or when there's time fix the domain mapping/HTTPS issue.

**Comment by evanrmurphy** [comment]
Ah it looks like this project also uses https://osmd.org/ which is working for me. So maybe the link just needs to be updated to that.

**Comment by sschmidTU** [comment]
Yes, we just pushed our new site at osmd.org these last few days, and we didn't get to update all links and redirects yet. In the end, the osmd.org site will be available at opensheetmusicdisplay.org again.
I currently do not have the priviledge to update that particular link.

Happy you like our demo! It's brand new from our recent 0.5.0 release.

**Comment by PieterHartzer** [comment]
New website is looking good!  I just noticed the broken links because Google isn't showing the new one yet.

**Comment by sschmidTU** [comment]
https://opensheetmusicdisplay.org/ is now available again, as our newly built site.
