### ISSUE TITLE
Npm 6 audit of OSMD/Vexflow

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#385]
When using npm 6.x and running npm install, npm audit automatically runs at the end of it.
Currently it shows 20 moderate vulnerabilities from Vexflow. It's not really a security issue i think, because you won't use Vexflow's npm, but it doesn't look good when someone runs npm install on OSMD or a project that has OSMD as a dependency.
![image](https://user-images.githubusercontent.com/33069673/45558579-8abf2300-b840-11e8-91e7-a1db90f7725f.png)

I already created a [PR for Vexflow which fixes this](https://github.com/0xfe/vexflow/pull/653) by updating npm to 6.4.1, that should do it.
But if you have any input, go ahead.
Another reason to look forward to another Vexflow release.

**Comment by bneumann** [comment]
Should we ask Mo again?

**Comment by sschmidTU** [comment]
It's already merged, just need another Vexflow npm release to fix our vulnerability warnings.
We could ask Mo for another release, and/or close the issue.

**Comment by sschmidTU** [comment]
Fixed since Vexflow 1.2.87.
Npm audit now finds 0 security vulnerabilities for our package :)
![image](https://user-images.githubusercontent.com/33069673/46805354-1dca7a80-cd65-11e8-8103-f6b40e435006.png)
