### ISSUE TITLE
bar-style element is ignored

### ISSUE THREAD

**Issue by npmccallum** [opensheetmusicdisplay/opensheetmusicdisplay#391]
When a .musicxml file specifies the barline bar-style, OSMD ignores it. The full list of styles is [here](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-bar-style.htm). Please note that the page gives examples of all the barline styles *except* `none`.

**Comment by sschmidTU** [comment]
This should be pretty easy. Seems like Vexflow only supports single, double, end and repeat barlines though.
So far we only read the bar-style attribute in RepetitionInstructionReader, probably needs to be read somewhere else too.

**Comment by npmccallum** [comment]
The one that I need most is: `none`. We use this for chant to express unmeasured music without freaking out the sanity checkers of all the typesetting apps.

**Comment by sschmidTU** [comment]
Oh, i didn't even know that was a usecase. So when bar-style is none, there shouldn't be a barline.
So e.g. with two 4/4 bars and a barline none between them, it will have 8/4 between barlines. Just visually speaking.

**Comment by npmccallum** [comment]
@sschmidTU Can you point me to the parts of the code that would need changing?

**Comment by sschmidTU** [comment]
In InstrumentReader.ts, you'll have to process the xmlNode with name "barline" and check for an element "bar-style":
```javascript
else if (xmlNode.name === "barline") {
  if (xmlNode.element("bar-style") !== undefined ) {
    const barStyle: string = xmlNode.element("bar-style").value;
    // set barStyle so that it can be turned into the right barline in Vexflow
   // maybe just handle it in RepetitionInstructionReader.ts.handleLineRepetitionInstructions()
```
then probably add support for further styles in VexflowMeasure.addMeasureLine().
It helps to search for where `VexFlowBarlineType` is used.

It seems like some barline handling is already done in RepetitionInstructionReader.ts.handleLineRepetitionInstructions().

I'm not sure whether we want to handle normal barline styles the same way as repetitions, but that may be how it's done right now and how it's easiest.

**Comment by sschmidTU** [comment]
@npmccallum a bit late, but it's now possible not to draw barlines,
with the `bar-style none attribute`.
there was a bug where resetting the VexFlow stave readded standard barlines.

![image](https://user-images.githubusercontent.com/33069673/67110225-82b77c80-f1d2-11e9-9200-71923e4e485a.png)
this + piano sample:
[barline_none_samples_xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3744832/barline_none_samples_xml.zip)
