### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by npmccallum** [opensheetmusicdisplay/opensheetmusicdisplay#392]
[Two years ago this week](https://opensheetmusicdisplay.org/2016/09/19/hello-world-opensheetmusicdisplay-musicxml/) you announced the first release of OSMD!

**This project is really important!**

Without OSMD, music is a second-class citizen on the web. Because of your efforts we will be able to openly preserve and distribute the human history of music. Thanks for all your hard work!

Here's a round of beers on me!

🍺🍺🍺🍺🍺

**Comment by bneumann** [comment]
Did someone say beer? 🍺 Thank mate

**Comment by bukaznik** [comment]
@npmccallum thank you! can put this as a quote on our website?

> Without OSMD, music is a second-class citizen on the web. Because of your efforts we will be able to openly preserve and distribute the human history of music.

**Comment by npmccallum** [comment]
@bukaznik Absolutely!

**Comment by npmccallum** [comment]
Feel free to close this issue whenever you think it appropriate.

**Comment by bneumann** [comment]
Still waiting for the beer😁
