### ISSUE TITLE
Clean up project build setup

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#40]
Status quo:
Grunt is used together with npm scripts as our main build tool. We might want to either move away from Grunt (which is what I would prefer personally) or clean up that Gruntfile and move the `prepublish` and `postinstall` hooks to Grunt?

Anyway, we have to keep npm so I would really prefer if we just left Grunt behind. I also don't see a real benefit from using it.

For reference, here is the current configuration:
```javascript
    // Register tasks
    grunt.registerTask('lint',      ['jshint', 'tslint']);
    grunt.registerTask('start',     ['typings']);
    grunt.registerTask('all',       ['typings', 'default']);
    grunt.registerTask('default',   ['browserify', 'uglify']);
    grunt.registerTask('npm-test',  ['typings', 'test']);
    grunt.registerTask('docs',      ['typedoc']);
    grunt.registerTask('test',      ['browserify:debug', 'lint', 'karma:ci']);
    grunt.registerTask('fast-test', ['browserify:debug', 'karma:ci']);
    grunt.registerTask('rebuild',   ['clean', 'default']);
    grunt.registerTask('publish',   ['clean', 'typings', 'browserify:dist', 'uglify:bundle']);
    grunt.registerTask('debug-build', ['browserify:demo']);
    grunt.registerTask('debug-browser', ['http-server:demo']);

    // Fix these in the future:
    // grunt.registerTask('test debug Firefox', ['browserify:debug', 'karma:debugWithFirefox']);
    // grunt.registerTask('test debug Chrome', ['browserify:debug', 'karma:debugWithChrome']);
```

Its quite hard for me to tell what is getting executed when and for what reason. @acondolu @oliver-h feedback pls.

**Comment by acondolu** [comment]
You can find a general description of the tasks in the wiki https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Grunt-Tasks.

Do you want feedback on something specific? Why do you wish to get rid of Grunt?

**Comment by sebastianhaas** [comment]
I don't really know to be honest. It's just a lot of tasks and together with npm scripts it gets quite challenging. But yeah. Maybe its more about the build structure tsd/browserify etc. than about the build tool. I should get working on that probably.

**Comment by sebastianhaas** [comment]
See #54. Can be closed on merge.
