### ISSUE TITLE
Class doc missing after migration to WordPress 

### ISSUE THREAD

**Issue by bneumann** [opensheetmusicdisplay/opensheetmusicdisplay#408]
Our autogenerated class doc page is gone. Can we get it again? @suhr was asking on gitter.

**Comment by suhr** [comment]
There actually is some doc at https://opensheetmusicdisplay.github.io/classdoc/, but it's hard to navigate.

**Comment by bneumann** [comment]
Oh yeah, didn't find it and I knew I was looking for it ;)
@bukaznik Can we put a link on the page? The style is different though, not sure if and how to change that

**Comment by bneumann** [comment]
I agree but as I mentioned we just started our new page so some things are still missing.

**Comment by sschmidTU** [comment]
Well, the github.io page was our old main page, and it obviously also links to the classdoc.
https://opensheetmusicdisplay.github.io/

The [Wiki](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki) also links to it.

The www.opensheetmusicdisplay.org is supposed to be more oriented towards the broader public than developers, so i'm not sure a link to the classdoc there would fit.

By the way, you could find the [Directory Layout](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Directory-Layout) page on the Wiki more insightful, though it could be a bit out of date.

**Comment by bukaznik** [comment]
yep, this is confusing atm. actually, we don't need the github pages anymore, do we @bneumann @sschmidTU? the wiki should be the only place with up-to-date info.

**Comment by sschmidTU** [comment]
There may still be some useful info there that we could convert and put somewhere else, like the Quick Start section and the Usage and Develop subsites.

**Comment by bukaznik** [comment]
ok so let's put this in the wiki as well?

**Comment by sschmidTU** [comment]
Yes, that seems to be our main Development site now. Some of the info we have there already, I'll see what could be added to the Wiki.

**Comment by sschmidTU** [comment]
@suhr by the way, i've never used the classdoc, i simply browse through the code and hit the F12 key when I see a class or method i want to understand (opens the definition).

**Comment by suhr** [comment]
This doesn't solve the problem of holistic understanding. For example, [this](https://docs.rs/rouille/) is the documentation of a micro web framework I am using. As you can see, it is very friendly and helps you to understand not only separate parts but the library as the whole. But the documentation of OSMD is very different from that.

**Comment by sschmidTU** [comment]
Have you seen [Basic usage](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Basic-usage) or any other Wiki page? There's a lot of holistic documentation there.
The thing is, you don't need to understand a lot about OSMD to use it, other than setting options. With Rouille or Vexflow on the other hand, the user has to code a lot.
And if you want to contribute to OSMD, you need to look at the code anyways.
We could perhaps make some prettier documentation, but there are many other important issues right now.
