### ISSUE TITLE
Display only a part of whole score

### ISSUE THREAD

**Issue by suhr** [opensheetmusicdisplay/opensheetmusicdisplay#409]
For example, the first few measures.

**Comment by sschmidTU** [comment]
Just insert a cut-down XML ;)
To be serious though, we could offer an option like "only show measures 1 to x" or even "show measures x to y, a to b,..." and so on, wouldn't be too hard.
Would this be a common use case for you?

**Comment by bneumann** [comment]
@matt-uib we had a discussion about this which ended in you saying we already habe that somewhere in the code
