### ISSUE TITLE
Fix milestone setup for project planning

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#41]
We need to have a proper milestone configuration for me (and others) to plan issues and workload. Currently, all three milestones are set to a past date.

We want to use [semver](http://semver.org/) for version naming, so I did wrong, naming our first release `0.0.1` as it should be `0.1.0`. 

Since we have quite some changes in the meanwhile, I suggest continuing with `0.1.0-alpha` and then `0.1.0-alpha.1` etc. We can then make a beta for `0.1.0` or even a release candidate `0.0.1-rc.1`.

I can't tell what features are to be done before we can make a first release `0.1.0`, but I think you have the overall time frame in mind.

**Comment by bukaznik** [comment]
ok, here is what I did:

- I  created 0.1.0-beta and assigned all issues (as far as I could tell) I think are necessary for the first official version. 
- for those I didn't know (and still have a alpha version for now): you need to explain them to me :) if issues are not necessary for 0.1.0, we create 0.2.0, correct?

if this is done we can delete the alpha milestones, can't we?

**Comment by bukaznik** [comment]
all tasks reassigned except #25
