### ISSUE TITLE
ReferenceError: OpenSheetMusicDisplay is not defined

### ISSUE THREAD

**Issue by truj** [opensheetmusicdisplay/opensheetmusicdisplay#412]
I was following the instructions on https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Basic-usage
I always got this error in the browser console:
ReferenceError: OpenSheetMusicDisplay is not defined

This happens with Firefox and Chromium.
I'm sure that **opensheetmusicdisplay.min.js** has been loaded before calling **new OpenSheetMusicDisplay(...)**. And I'm also sure that the script is correctly linked in my **<script src="..."></script>**.

I've tried out versions 0.5.1, 0.5.0 and 0.3.1 from this site:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases
Always the same problem.

**Comment by truj** [comment]
Yes, that fixed the problem. Thank you very much.

**Comment by sschmidTU** [comment]
Just for documentation, to avoid common pitfalls like this in the future, [Basic Usage](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Basic-usage) in the Wiki now lists a new plain Javascript example project, and this way of accessing the OSMD object is shown as well.
