### ISSUE TITLE
Allow two voices to use the same note head

### ISSUE THREAD

**Issue by kenakofer** [opensheetmusicdisplay/opensheetmusicdisplay#414]
Here is musicxml using two voices on the same staff.

Musescore generated pdf:
![screenshot_2018-10-04](https://user-images.githubusercontent.com/6500636/46489212-cc554500-c7d2-11e8-930b-f1b94c913cdd.png)

OSMD render:

![screenshot_2018-10-04 screenshot](https://user-images.githubusercontent.com/6500636/46488983-38837900-c7d2-11e8-84ca-ec7b6507c25d.png)

Is it intentional that the note heads are not combined? I couldn't find a way for MusicXML to specify one way or the other, but [this page](https://www.musicxml.com/tutorial/percussion/notehead-shapes/) seems to imply that they should be combinable:

>  There are many cases where, for instance, a downstem half note shares a hollow notehead with an upstem eighth note. The eighth note can specify that it uses an unfilled normal notehead, making things display correctly when moving back and forth between notation programs.

Although that is regarding notes with different lengths on the same pitch.

Could this be added as an optional feature?

**Comment by sschmidTU** [comment]
Good idea, by default there should only be one note head if both notes have the same duration.
The solution is to only draw one note with two stems. Given that Vexflow supports that.
This might not be so easy to implement though, i'll check.

Thanks for the info! Good to know MusicXML might have support for this.

**Comment by sschmidTU** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/33069673/126009028-0008be31-d448-44d5-b1fb-09b522b006c9.png)
[shared_stems.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6833386/shared_stems.musicxml.zip)
