### ISSUE TITLE
Fix chords (root-alter with negative values)

### ISSUE THREAD

**Issue by mt633** [opensheetmusicdisplay/opensheetmusicdisplay#418]
I've tried the two latest releases with a couple of MusicXML files with chords and I have noticed that some measures no longer get drawn, which they did in 0.3.1. Looking closer at it, it seems to be because of the changes made to the root-alter value that now only allows a positive value (but turns the chord to a flat instead of a sharp).

Also, if a chord were to fail in the future, the remaining parts of the measure (such as notes and lyrics) should still be drawn, instead of rendering a whole note rest like it does now.

**Comment by sschmidTU** [comment]
@mt633 Can you give an example XML? Which value do you mean exactly, do you mean the `<alter>` element/tag? Does it only happen for non-integer values?
I haven't noticed this before, sounds quite critical, so it should be fixed soon.

**Comment by mt633** [comment]
Sure, here's what it looks like in MuseScore:
![example in muscescore](https://user-images.githubusercontent.com/44020490/46769047-bff94c80-ccea-11e8-924f-6b232a297a7e.png)

And here's how OSMD renders it:
![example in osmd](https://user-images.githubusercontent.com/44020490/46769048-c091e300-ccea-11e8-907d-bbb8e60aa7be.png)

No, the value is called `<root-alter>` (see below) but I suppose the `<alter>` tag does the same thing for notes.

```
<harmony print-frame="no">
    <root>
        <root-step>A</root-step>
        <root-alter>-1</root-alter>
    </root>
    <kind>major</kind>
</harmony>
```

**Comment by sschmidTU** [comment]
Fixed along with other <AccidentalEnum> uses in ChordSymbolReader.

@mt633 thanks for the report and example xml, made it easy to fix!

**Comment by sschmidTU** [comment]
I also added some spacing in 78cd2eddcf145a0a1b5ef687a10a279523c864e6 so that the chord symbols don't collide with these notes.
![image](https://user-images.githubusercontent.com/33069673/47101939-b7999800-d23b-11e8-87bc-e0f37d548953.png)

It's not ideal yet of course, because notes higher than a ledger line above the stave can still collide, but if we want to avoid these collisions completely, we need a real spacing method for that.

**Comment by mt633** [comment]
Thanks for fixing this, it seems to be working now. Regarding the Y Offset, it's a nice workaround but it seems to be colliding with the composer name.

Yes, most of my sheet music have chord symbols, so it's quite an essential feature for me.

**Comment by sschmidTU** [comment]
Yes, as I said, for real chord symbol spacing we would need a complete collision detection and spacing method, at best for all labels. We'll probably do that at some point anyways, but maybe it's too much for now.

**Comment by mt633** [comment]
Sure, no problem. It's a workaround that works for now. By the way, I also noticed a collision among the chords within a measure when there were many chords, so at some point that should also be accounted for when calculating the measure width/spacing.
