### ISSUE TITLE
Display Tremolo slashes

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#431]
There is a [Tremolo element](https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-tremolo.htm) under `<Ornaments>`.
I just opened a [Vexflow PR](https://github.com/0xfe/vexflow/pull/667) that fixes Vexflow.Tremolo offsets and scaling.
For now the offsets are too far off for OSMD, but after the PR we can add this.

![image](https://user-images.githubusercontent.com/33069673/47204356-6e546000-d383-11e8-8f65-eece14411b1d.png)

Unfortunately, there is no Tremolo between two notes in Vexflow yet.
That's not too common, but in orchestral string parts it's not that rare either.
![image](https://user-images.githubusercontent.com/33069673/47205105-51209100-d385-11e8-9aa1-efbdbdbbfbe4.png)
https://en.wikipedia.org/wiki/Tremolo

**Comment by sschmidTU** [comment]
Vexflow PR is merged, just waiting for a new release.

**Comment by sschmidTU** [comment]
Tremolo slashes on single notes are now implemented, see the new Function Test in the Demo:
![image](https://user-images.githubusercontent.com/33069673/54926629-fe896900-4f10-11e9-98c9-7d7008e1dbfc.png)

Tremolos between two alternating notes are at least possible for half notes now (see #472), though it's a bit of a hack.
It also only works if given in XML in this way:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2655482/Beam_BadArguments.zip
_from https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/472#issuecomment-454870833_

An idea to implement these is to add them as beams in Vexflow, and add an option to Vexflow to create Tremolo beams, which are simply shorter beams that begin at a higher x and end at a lower x.
Though maybe we can simply add them as full beams at first, see extract of image from first comment:
![image](https://user-images.githubusercontent.com/33069673/54926863-722b7600-4f11-11e9-8c9f-0c7b858d5c3d.png)

**Comment by ronnycsharp** [comment]
Hi Simon,

is there still any progress here?
Will this feature be supported in the future?
Or maybe, it's already implemented and I couldn't see it ?!
I need to display sheet music, which contains tremolo notes (two separated notes with one ore more tremolo slashes).

Thanks a lot for the fantastic work on OSMD.

Greetings from Berlin
Ronny

**Comment by sschmidTU** [comment]
@ronnycsharp Hi! What do you mean exactly? The feature is already implemented.
If you're talking about tremolo slashes between notes, that is very difficult to achieve with Vexflow and would take a lot of time to implement, so it's currently a bit further down the roadmap.

**Comment by ronnycsharp** [comment]
@sschmidTU Hi Simon, yes that's exactly what I mean. I need to render tremolos between two different notes. I hope this feature will be supported in the future :)

**Comment by alexshenker** [comment]
@sschmidTU Any word on alternating note tremolo support? Is there a feature request open somewhere, or a roadmap indication? 
Thank you

**Comment by alexshenker** [comment]
Any word on plans for implementation of alternating-note tremolos?
Thank you

**Comment by alexshenker** [comment]
@sschmidTU Any word on plans for implementation of alternating-note tremolos?
What does it take to accomplish this in Vexflow?

**Comment by sschmidTU** [comment]
No plans currently. It doesn't exist in Vexflow, as I said, so you either have to implement it in Vexflow or in OSMD, which might be easier.
I'm not a vexflow graphical developer, so I can't tell you out of hand what it takes in Vexflow, unfortunately.

**Comment by sschmidTU** [comment]
Tremolo between notes will be covered in #1551. Tremolo slashes are implemented, so let's close this and handle between-note tremolo separately in the new issue.
