### ISSUE TITLE
Highlight/Color multiple notes

### ISSUE THREAD

**Issue by mpwind** [opensheetmusicdisplay/opensheetmusicdisplay#434]
Hi there, 

I am working on rendering one more column at one time, like that when you click the show button, two columns(on two different notes) will display instead of one.

I try the ctx.fillRect(15,15, newWidth, 1); but it does not work. Then I also tried to create one more cursorElement , add it to the container. But most of the time, it just replaces the previous one.

Thank you in advance!

**Comment by sschmidTU** [comment]
Our cursor isn't made to highlight two positions at once. What do you want to use this for, can you give an example?
In any case, you'll probably have to modify the Cursor class for your purpose. The easiest way is probably to create multiple instances of Cursor, but you'll have to modify the constructor and other methods so they don't overwrite what the other Cursor object does.

**Comment by mpwind** [comment]
I want to make the cursor.show() highlight several positions at once.  I am working on reading a musicXML file and highlighting some specific notes at one time.   For example, it inputs a musicXML file and wants to highlight the 1st 3rd, 7th note , then I click the show button, these three notes will be colored.

**Comment by sschmidTU** [comment]
I see. You'll definitely have to make changes to the Cursor class. Sorry, i may not be able to help you out that much right now, i haven't looked at the Cursor class that much.
However, we were thinking about coloring notes and using colors given in XML. You would have to assign the colors in the XML though. See #125

**Comment by mpwind** [comment]
Thank you very much. It is enough for me

**Comment by sschmidTU** [comment]
You mean being able to color notes by XML would be enough for you?

**Comment by mpwind** [comment]
yes, I thought I can highlight the notes by this at the beginning, but when I found the cursor, I think it will be easier to color many notes at once by it. The fact is I am wrong... i'll try to color notes by XML then

**Comment by sschmidTU** [comment]
It's not a bad idea to highlight multiple notes with cursors, if it was easy i would implement it right away. Though controlling which notes to highlight with multiple cursors also wouldn't be easy.
I'll tell you when we can color notes, shouldn't be too hard!

**Comment by mpwind** [comment]
Thank you

**Comment by mpwind** [comment]
Can you give me some advice on how to locate the specific symbol(newbie to music...)  ,  i've seen                       
  for (let note of notes) {
        (<Vex.Flow.StaveNote> note).setStyle({fillStyle: "green", strokeStyle: "green"});
   }
it colors all the symbol (notes, beam ,something else) ，if I want to access the specific beam/note , how I do it ?
Thank you in advance, I've been stuck there for hours.

**Comment by bneumann** [comment]
Hi @mpwind I am afraid that is an old topic that we haven't solved yet.
There is however a way to implement the note coloring if you want to build your own version. I can share that with you later today.

**Comment by sschmidTU** [comment]
You can check the note.sourceNote for properties like pitch.
Or you can parse the note color from XML in InstrumentReader and add it as a new attribute of Note, which i'm going to do soon anyways.
Then:
```javascript
for (let note of notes) {
  if (note.colorXML !== undefined) {
    (<Vex.Flow.StaveNote> note).setStyle({fillStyle: note.colorXML, strokeStyle: note.colorXML});
  }
}
```

**Comment by sschmidTU** [comment]
I implemented displaying notehead colors given in XML on the feature/colorNotes branch (c770f26552eccadb0b6dcfad0b26387e57c6469d).
![image](https://user-images.githubusercontent.com/33069673/47358299-adf3b280-d6c9-11e8-925f-5e29ffe5c36f.png)
[color_beethoven_geliebte.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2505948/color_beethoven_geliebte.zip)

The limitation so far is that the stem will also be colored, and you can't color individual notes in a VoiceEntry (chord) differently. In the example above, i only set the color of one of the notes of the piano's first chords in the XML, but it's drawn for all of the VoiceEntry's notes.

That's because in VexflowConverter and elsewhere, we only use one Vexflow.StaveNote for a whole VoiceEntry containing multiple notes.

If we want to color individual notes and stems, we'll probably have to create a StaveNote for each note in a VoiceEntry, which would require major refactors, because VexFlowVoiceEntry.vfStaveNote is used in many different places for all the VoiceEntry's notes, e.g. to set the stem for all notes.

**Comment by matt-uib** [comment]
@sschmidTU for the StaveNote i think it makes sense to do refactoring in Vexflow - maybe we can create a pull request for it? At least i think it makes very much sense to have a StaveNote (VoiceEntry), but still be able to then access the individual notes for e.g. coloring...

**Comment by sschmidTU** [comment]
Hmm, that's true. There's even a StaveNote.drawNoteHeads() function, where you could set and restore the color. We'll only have to give the notehead and stem colors, for noteheads probably simply in order like the keys:
```javascript
  new StaveNote( {
    keys: ["d/4", "e/5"],
    colors: ["#FF00FF#", "#FF0000"]
  });
```

I'll make a PR like that unless someone has more suggestions.

**Comment by sschmidTU** [comment]
I implemented stem coloring and coloring individual notes in a chord in #436.
It doesn't even strictly need a Vexflow PR, though with it the code would be nicer (for now, we have to access StaveNote.note_heads directly).
![image](https://user-images.githubusercontent.com/33069673/47367142-624c0380-d6df-11e8-836c-211a6d0cd2d2.png)
[color_notehead_stem_tests.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2506490/color_notehead_stem_tests.zip)

Actually there are many MusicXML Elements that support color, see here:
https://usermanuals.musicxml.com/MusicXML/Content/AT-MusicXML-color.htm

It would be simple to color many other elements too, like accidentals and barlines. I'd like to somehow unify the code and have a color attribute in a superclass of all colorable elements, though for now classes like Arpeggio and OrnamentContainer don't have a superclass or implement an interface.

But for now, it may be better to focus only on a few key elements like accidentals and implement coloring them.

**Comment by sschmidTU** [comment]
We should probably offer an option to disable coloring.

**Comment by sschmidTU** [comment]
Flags are now colored with the stem color, and beams with the stem color if all stem colors of the beam notes are identical.
There are EngravingRules to turn off coloring for beams, flags and everything.
(abfd252c98a3318bdbdf93d0f9b849210582860f)

Added Function Test Color to the demo.
![image](https://user-images.githubusercontent.com/33069673/47373585-70ece780-d6ec-11e8-9cfe-670bd8d2f2a1.png)
