### ISSUE TITLE
Program to Color Scores

### ISSUE THREAD

**Issue by rios88** [opensheetmusicdisplay/opensheetmusicdisplay#442]
What program do you use to color the scores? I've been testing musescore and sibelius but it just lets me paint the notehead. Thanks

**Comment by sschmidTU** [comment]
In Musescore, you can click almost any element, and in the Inspector (F8) click on the color field (black filled area) to select a color.
![image](https://user-images.githubusercontent.com/33069673/47721351-320ce380-dc50-11e8-9bcc-a55a88d15efb.png)

OSMD can only color noteheads, stems, flags and beams for now, but at

**Comment by rios88** [comment]
if what happens is that when I save the file in xml only the noteheads are painted

**Comment by sschmidTU** [comment]
Musescore exports all colors to XML for me. Take a look at the OSMD function test Color, i just selected the colors as i described and exported to XML:
[OSMD_function_test_color.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2531592/OSMD_function_test_color.zip)

Take a look at it in our [Demo](https://opensheetmusicdisplay.github.io/demo/).

Maybe update your Musescore version.

**Comment by rios88** [comment]
when I open the file that you have spent with musescore v2.3.2 on mac only appear the noteheads painted but in the demos they appreciate well

**Comment by sschmidTU** [comment]
That's true, Musescore seems not to be able to read the color of stems, time signature and clef that it exported itself, it can only read the note head color. That's a problem with Musescore, the attribute is present in the XML.

**Comment by sschmidTU** [comment]
Actually, it looks like Musescore only exports the color for note heads. You'll have to look at the XML and insert the `color="..."` yourself to each attribute like `<stem color="...">`. I forgot I did this.
