### ISSUE TITLE
Code Climate

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#444]
We had this Code Climate banner in the Readme:
[![Code Climate](https://codeclimate.com/github/opensheetmusicdisplay/opensheetmusicdisplay/badges/gpa.svg)](https://codeclimate.com/github/opensheetmusicdisplay/opensheetmusicdisplay)

I think it's very unreasonable for our project, so we removed it.
For one thing, it wants every file to be 250 lines or less, which is completely contrary to our style.
Jonathan Blow also argued against fragmentation and for accepting large coherent code blocks.

Also, Code Climate calculates "Cognitive Complexity", which is quite high for a lot of our music system building methods. But that's just how it is, it's a complex system, it's not going to get much simpler with refactoring.

But there's something useful about Code Climate too: [Duplicate code detection](https://codeclimate.com/github/opensheetmusicdisplay/opensheetmusicdisplay/issues?category%5B%5D=duplication&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed#). I do think there are quite a few instances of code duplication that could be refactored into methods in OSMD.

Also, we could make variables in EngravingRules public, so that we don't need to have getters and setters for every one of them, which is getting annoying to add for new variables.

@bneumann thoughts?

**Comment by bneumann** [comment]
Ah sorry just rembemered you wanted some input. Yeah I think breaking down code into smaller chunks is always a good idea. But as you said with our complexity it is just not possible sometimes. However we could do thinks like having all the draw methods (that actually do drawing) in the corresponding classes instead calling them all inside the megamoth MusicSheetDrawer which then would just call the draw methods and things like that.

Checking for duplicate code is a brillant idea. I refactor that whenever I see some and there is a lot. Also concerning the just mentioned MusicSheetDrawer which has the same loops all the time which screams "Please do some better approach here!!!" :)
