### ISSUE TITLE
Question about extensibility and private variables

### ISSUE THREAD

**Issue by jeremija** [opensheetmusicdisplay/opensheetmusicdisplay#448]
Hi there, this is a pretty cool library - thanks for making it open source!

I've been trying to use it in a TypeScript project, but have run into a wall pretty quickly. A lot of the interesting variables are `private` and they _can_ be accessed from a JavaScript project or browser console, but cannot from a `TypeScript` source file (which makes sense). One such example is being able to access notes under the cursor via `osmd.cursor.iterator` variable, but that doesn't work in `.ts` because the `iterator` variable is defined as private:

```
  private iterator: MusicPartManagerIterator;
```

and I get the expected error:

```
2341: Property 'iterator' is private and only accessible within class 'Cursor'.
```

I was also thinking about extending the `OpenSheetMusicDisplay` and `Cursor` classes and exposing a method like `get notesUnderCursor()`, but I cannot do that because the `iterator` in `Cursor` class is `private`, not `protected`. Additionally, the `Cursor` class isn't exported.

Are you planning on exposing some of these variables at some point, or making them `protected`, or at least adding more methods that give access to internal information? Right now the only solution I can think of is to fork the project and add the getters myself, but I'm wondering if you might have any better suggestions.

Thanks!

**Comment by sschmidTU** [comment]
Hi, thanks for your interest!
Of course you can always fork the project or create a local branch with your changes.

That being said, you're not the first to be interested in the Cursor and its iterator.
I think there would be no harm in making it public.
@bneumann thoughts?

**Comment by jeremija** [comment]
Hi @sschmidTU, thanks for a quick reply. Making the iterator public would definitely help a lot! But that was just one example. Another one would be adding on-click handlers (a little related to #262) to the rendered notes in `svg`, for example `osmd.graphic` below is also `private`:

```javascript
let ml = osmd.graphic.MeasureList

let tickables = []
ml.forEach(m => m.forEach(mm =>
  Object.keys(mm.vfVoices).forEach(voiceKey =>
    mm.vfVoices[voiceKey].tickables.forEach(t => tickables.push(t))
  )
))

tickables
.filter(t => !!t.attrs.el)
.forEach(t => t.attrs.el.addEventListener('click', () => {
   console.log('clicked on', t)
}))
```

The above might not be the right way of doing it because the click handler seems to have access only to `Vex.Flow.StaveNote`, and not the OSMD's abstraction (which I believe is `Note` from `src/MusicalScore/VoiceData/Note`).

Maintaining forks and keeping up-to date with upstream changes can be tedious, especially for a project of this size. I was wondering if there's a place I could read about the plug-in architecture you're planning on building (or is already being built)? Maybe that would be a better start to contributing instead of forking and submitting pull requests that might not be accepted because of different long-term project visions.

**Comment by sschmidTU** [comment]
I've created a getter for things like the `Cursor.Iterator` and `osmd.Sheet`, see commit above.
Let me know if you need access to other fields.
By the way, you can always cast something to `<any>` and access its private variables. Not ideal, but a good workaround.

If you can get a `get NotesUnderCursor()` method and make a Pull Request for it, that would be nice to have! Otherwise, we might add that at some point.

**Comment by jeremija** [comment]
@sschmidTU Thanks for making that commit!

I've already added the `NotesUnderCursor`, as well as some other methods to the `Cursor` class. I submitted the pull request to run the CI. Please don't merge it yet since I might have to make some modifications. Would welcome your feedback, though!

**Comment by jeremija** [comment]
@sschmidTU, the latest changes seem to have broken my project build (my TypeScript project that uses OSMD, but not the build of OSMD itself). Importing the build of commit 52023f8 works, but the build of 1410d5c does not. The following fails:

```typescript
import {OpenSheetMusicDisplay as OSMD} from '../../opensheetmusicdisplay'
```

with errors below:

```
TypeScript error: ../opensheetmusicdisplay/build/dist/src/musicalscore/graphical/vexflow/vexflowbackend.d.ts(17,37): Error TS2694: Namespace 'Vex.Flow' has no exported member 'RenderContext'.
TypeScript error: ../opensheetmusicdisplay/build/dist/src/musicalscore/graphical/vexflow/vexflowmeasure.d.ts(111,24): Error TS2694: Namespace 'Vex.Flow' has no exported member 'RenderContext'.
```

I believe this has something to do with the newly exported variables and the additional Vexflow definitions in the `external` folder, but haven't had the time to investigate further.

**Comment by sschmidTU** [comment]
That's weird, we already have RenderContext exported as a class, just not as an interface.
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/0.6.2/external/vexflow/vexflow.d.ts#L359

But I added it to the definitions and it doesn't cause problems, so if this works for you and makes typescript projects including OSMD compile, why not.
@jeremija can you confirm the build works for you now? I'd like to push a 0.6.3 release and it would be nice if it works with typescript projects.

**Comment by jeremija** [comment]
I've just tried it in a new TypeScript project, and both the latest and the previous commits work. Then I went back to the other project, and realized I had `@types/vexflow` installed. As soon as I uninstalled it, it started compiling successfully. I guess the extended type definitions provided by osmd were in conflict with the original Vexflow typedefs. Sorry for the confusion!

**Comment by sschmidTU** [comment]
No problem! Good to know that that's a conflict in TypeScript projects. I'll take the definition out again.

**Comment by sschmidTU** [comment]
Seems like this is solved.
For importing, see #454.

**Comment by jeremija** [comment]
Thank you for your help!
