### ISSUE TITLE
Create Music sheet object model comparison visualisation & naming

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#45]
Create a graphic simliar to what is pinned at your desk comparing different naming vexflow vs osmd.

**Comment by matt-uib** [comment]
Use or create notes where Ties, tuplets, Ornaments, Keys, clefs, accidentals, ... are used to being able to name them.
besides the obvious also visualize in the picture:
VerticalGraphicalStaffEntryContainer
SourceMeasure
Staff
Instrument
...

**Comment by bukaznik** [comment]
see https://drive.google.com/drive/folders/0BxR4XlOO1cUrU3ZWQk9sUFlKRzg?usp=sharing

**Comment by acondolu** [comment]
Please give me feedback: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Music-Sheet-Object-Model

**Comment by bukaznik** [comment]
finetuning tbd
