### ISSUE TITLE
False extra wedge in Mandoline

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#451]
There's a long extra wedge in Debussy - Mandoline that shouldn't be there, right at the start.

I noticed that this happened after some expressions changes a few weeks ago, one could trace which commit did this. Probably something about multiline wedges.
I just forgot to open an issue.

![image](https://user-images.githubusercontent.com/33069673/47997654-e26d6280-e0fc-11e8-84bf-9d476095e86c.png)

**Comment by bneumann** [comment]
Works on my machine:
![image](https://user-images.githubusercontent.com/2605131/48019518-eb2d5b00-e133-11e8-9166-574cb6504966.png)

Did you use another branch? I tried with latest develop

**Comment by bneumann** [comment]
Ok I can reproduce it when squeezing the window. It looks like the start position of the wedge is wrong. Somehow it tells me that we are at the start of the line but we are actually at the end.

**Comment by bneumann** [comment]
Okay so what I see is that the Timestamp is somewhat odd. Could that be that there is a light miscalculation prior to the call?

**Comment by bneumann** [comment]
@sschmidTU I sorta found the issue. In the bug case the ```getRelativePositionInStaffLineFromTimestamp``` function returns 5.5 something and in the good case it returns a proper position ~50 something. So I think that might be an issue where @matt-uib can help? The weird thing is that all the positions are calculated correctly but still when getting the position here the measure X value seems to be off.

**Comment by sschmidTU** [comment]
Doesn't happen anymore.
