### ISSUE TITLE
Import OSMD classes in TypeScript with Webpack

### ISSUE THREAD

**Issue by shishkin** [opensheetmusicdisplay/opensheetmusicdisplay#454]
I'm struggling to import e.g. `Pitch` class in my project using webpack and typescript. Interestingly, I'm able to import typings for typescript type checking, but the code fails at runtime not being able to find `Pitch`. I've added `opensheetmusicdisplay` 0.6.3 dependency with NPM and then import `Pitch` class like this:

```
import { OpenSheetMusicDisplay } from 'opensheetmusicdisplay';
import { Pitch, NoteEnum } from 'opensheetmusicdisplay/build/dist/src/Common/DataObjects/Pitch';

...

const osmd = new OpenSheetMusicDisplay(container, {});
osmd.setLogLevel("info");

...

Pitch.getNoteEnumString(NoteEnum.C);
```

Interestingly `OpenSheetMusicDisplay` class is getting imported and works just fine.

**Comment by sebastianhaas** [comment]
Related to #5

**Comment by sschmidTU** [comment]
We should really support this, and we're already working on it in #5.

Even though OSMD is primarily there to (interactively) render scores and not as an API to investigate rendered scores, it seems like a lot of people use it like that, and this would add a lot of value to the project.

**Comment by shishkin** [comment]
BTW, I've found two workarounds, in case someone needs it before #5 gets released:

1. Clone OSMD as a Git submodule, add transitive dependencies and compile OSMD sources as part of my project;

2. Use TypeScript black magic:

```
const NoteF = () => new OpenSheetMusicDisplay(null).Sheet.Instruments[0].Voices[0].VoiceEntries[0].Notes[0];
type Note = ReturnType<typeof NoteF>;
```

**Comment by sschmidTU** [comment]
Thanks for the workarounds! That black magic in the second workaround is hilarious.

I just created PR #458 for #5, so maybe we won't need a workaround for long and importing OSMD classes in typescript will be easy soon.

**Comment by sschmidTU** [comment]
I just merged #458, so you should be able to import all classes in Typescript now.

@shishkin could you perhaps test this? I already tested it in the [Webpack usage example project](https://github.com/opensheetmusicdisplay/webpack-usage-example).
You should be able to build OSMD and replace the build folder and package.json in your node_modules/opensheetmusicdisplay folder for testing.

I'd like to push another release 0.6.4 with this and just make sure the typings work well.

**Comment by sschmidTU** [comment]
@shishkin I just released OSMD 0.6.4 with this change, so it should be easier to test.
I tested it with the [Webpack usage example project](https://github.com/opensheetmusicdisplay/webpack-usage-example) and i can easily import and use a lot of classes. All imports can now be added from "opensheetmusicdisplay" as well.

**Comment by shishkin** [comment]
Thanks @sschmidTU, 0.6.4 works perfectly!

**Comment by sschmidTU** [comment]
Great! If there are ever any imports that don't work, just give a notice. Chances are the script didn't create the index properly or we created a new class.

**Comment by loganknecht** [comment]
Hey @sschmidTU! Apologies for being the squeaky wheel lately. I've just tried to import the type [GraphicalVoiceEntry](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/GraphicalVoiceEntry.ts) from here, based on me trying to interrogate the graphical staff note for its position.

I do this:
```
// -----------------------------------------------------------------------------
// Third-Party Libraries
// -----------------------------------------------------------------------------
import { GraphicalVoiceEntry, OpenSheetMusicDisplay } from "opensheetmusicdisplay";
// -----------------------------------------------------------------------------
// Custom Components
// -----------------------------------------------------------------------------
// N/A
// -----------------------------------------------------------------------------
// Resources
// -----------------------------------------------------------------------------
// N/A

// TODO: Fix return typing
export function retrieveGraphicNote(
    open_sheet_music_display_object: OpenSheetMusicDisplay,
    stave_index: number,
    measure_index: number,
    note_index: number
): GraphicalVoiceEntry {
    const does_stave_exist = open_sheet_music_display_object.GraphicSheet.NumberOfStaves > stave_index;
    const does_measure_exist = open_sheet_music_display_object.GraphicSheet.MeasureList.length > measure_index;
    const does_note_exist =
        does_stave_exist &&
        does_measure_exist &&
        open_sheet_music_display_object.GraphicSheet.MeasureList[measure_index][stave_index].staffEntries.length >
            note_index;
    const do_multiple_voices_exist =
        does_note_exist &&
        open_sheet_music_display_object.GraphicSheet.MeasureList[measure_index][stave_index].staffEntries[note_index]
            .graphicalVoiceEntries.length > 1;

    if (do_multiple_voices_exist) {
        throw new Error(`"Stave [${stave_index}]
                        - Measure [${measure_index}]
                        - Note [${note_index}]
                        multiple notes exist and I don't know what to do.
                        Make sure this is handled correctly.`);
    }
    if (!(does_stave_exist && does_measure_exist && does_note_exist)) {
        throw new Error(`"Stave [${stave_index}]
                        - Measure [${measure_index}]
                        - Note [${note_index}]
                        does not exist and I don't know what to do.
                        Make sure this is handled correctly.`);
    }
    const note_to_return =
        open_sheet_music_display_object.GraphicSheet.MeasureList[measure_index][stave_index].staffEntries[note_index]
            .graphicalVoiceEntries[0];
    return note_to_return;
}
```

This doesn't work, I get the compilation error:
```
 Module '"../typescript_front_end/node_modules/opensheetmusicdisplay/build/dist/src/index"' has no exported member 'GraphicalVoiceEntry'.

Version: 6.6.0

Also if there's a better way to interrogate the position of the note I'd love to be corrected :)

**Comment by sschmidTU** [comment]
Ah, the Graphical classes weren't caught by our export script. I added them to the exports now, though there's no new release yet.
For now you should be able to use `<any>`.
You may be able to dodge the graphical classes by accessing osmd.sheet, which has the class `MusicSheet` instead of `GraphicalMusicSheet`.
I may be able to look at the code later, but do tell me if this works for you!
