### ISSUE TITLE
Donation, possible?

### ISSUE THREAD

**Issue by ikelaiah** [opensheetmusicdisplay/opensheetmusicdisplay#456]
Hi,

How can I donate $$ to this project?

**Comment by sschmidTU** [comment]
Hello ikelaiah,

first of all thank you for considering to donate to and support our project! We have been considering donation options for a while.

We decided to enable people to support us via PayPal, this button is now added to our Github frontpage (Readme):
[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FPHCYVV2HH8VU)

Again, thanks to you and anyone considering to donate.

Of course, there are also other great ways to support our project, like bug reports, feature requests, contributing code, etc., and we appreciate it all.

**Comment by ikelaiah** [comment]
Thanks and done. Looking forward to donate more in the future.
