### ISSUE TITLE
How to scale down rendering by 75%?

### ISSUE THREAD

**Issue by ikelaiah** [opensheetmusicdisplay/opensheetmusicdisplay#457]
I managed to use OpenSheetMusicDisplay to show MusicXML on my website.
Only thing, the notes seem big.
I suppose, I could change it from MuseScore, but could change it programamtically via js?

**Comment by sschmidTU** [comment]
The OpenSheetMusicDisplay object has a `public zoom` field that you can set before calling `render()`. The default value is 1, meaning 100% of the default note size.
So do something like this:
```javascript
let osmd = new OpenSheetMusicDisplay(container);
osmd.zoom = 0.8;
osmd.load(myScore);
osmd.render();
```

You can also try the zoom button in the [Demo](https://opensheetmusicdisplay.github.io/demo/) and look at the demo code (`demo/index.js`).

**Comment by ikelaiah** [comment]
Got that. Thank you! 😄
