### ISSUE TITLE
Drawing single or multiple lines?

### ISSUE THREAD

**Issue by dominikmeixner** [opensheetmusicdisplay/opensheetmusicdisplay#459]
Is it possible to draw only a few or a single line AFTER rendering the entire music-sheet?

**Comment by sschmidTU** [comment]
What do you mean exactly? You mean after rendering a music sheet, you want to render some additional lines?
You could create a second (div-)container and a second instance of OSMD to render your extra lines.

By the way, i'm working on a "Draw measure 1 to X" option right now. With that you could definitely draw the first few lines of a piece.

**Comment by sschmidTU** [comment]
Do you mean rendering empty Stafflines after the piece?

**Comment by dominikmeixner** [comment]
That is kind off what I meant. I also meant, "overriding" specifig lines. For example having the first line be overwritten by the fifth line, if that makes sense.

**Comment by sschmidTU** [comment]
Writing over a line with another will be very difficult to impossible, a lot of the code assumes you don't mess with the piece in ways that break its logic.
We could render empty lines at the end with an option, though i'm not sure that that's often useful. As i said, you can create multiple (div) HTML elements and OSMD objects and let each render what you want, given the right XML.
There's also a new `drawUpToMeasureNumber' option, so you can draw measures 1 to X now, for any X.

**Comment by dominikmeixner** [comment]
Alright, thanks for the quick response! Have a great weekend :)
