### ISSUE TITLE
Move demo to demo.opensheetmusicdisplay.org

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#46]
Let's host the demo at demo.opensheetmusicdisplay.org

**Comment by sebastianhaas** [comment]
Why not host demo on github pages too? We could have something like 

* http://opensheetmusicdisplay.github.io/demo (displaying a start page with links to both demo and docs)
 * http://opensheetmusicdisplay.github.io/demo (for the demo pages)
 * http://opensheetmusicdisplay.github.io/docs (for the API documentation)

Advantages of this approach:
* Demos and docs are always up to date with the latest release, you don't have to take care of that manually, demos and docs can be published automatically on every release.
* You can use a custom domain as well (https://help.github.com/articles/using-a-custom-domain-with-github-pages/)
* No additional cost
* Anyone can easily contribute to demos and docs
* Github ❤️ 

PTAL @bukaznik
