### ISSUE TITLE
Chord symbols are not to be taken into account for system bounding box size

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#464]
then the distance to the previous system is too small.
i guess it also is not taken into account for in-system staffline distances

**Comment by bukaznik** [comment]
This should also fix the composer
![screenshot 2018-11-23 16 10 52](https://user-images.githubusercontent.com/14196717/48950099-610a3280-ef3a-11e8-907a-a27c68f64d8b.png)
