### ISSUE TITLE
Add part name abbreviation

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#466]
![screenshot 2018-11-23 16 29 08](https://user-images.githubusercontent.com/14196717/48950875-eb539600-ef3c-11e8-9f55-47753bcf42ad.png)

**Comment by sschmidTU** [comment]
Done.
Abbreviations are read from XML, and there's a new option to disable them (drawPartAbbreviations).
![image](https://user-images.githubusercontent.com/33069673/53303283-d1da2700-3868-11e9-90e9-4a2eb35df67a.png)
