### ISSUE TITLE
Can't open Gershwin - Rhapsody in Blue from MuseScore

### ISSUE THREAD

**Issue by bneumann** [opensheetmusicdisplay/opensheetmusicdisplay#470]
This file https://musescore.com/user/24069/scores/196941 results in an "tick not found" error.

**Comment by matt-uib** [comment]
I had the same issue with our app.
Even musescore cannot read the file :-)
It's an xml parsing error - the xml seems corrupted.
I created a Forum entry at musescore:
https://musescore.org/en/node/278478
