### ISSUE TITLE
error: Beams can only be applied to notes shorter than a quarter note.

### ISSUE THREAD

**Issue by sug1no** [opensheetmusicdisplay/opensheetmusicdisplay#472]
First of all thank you for a great project,

please drop attached Beam_BadArguments.xml{[Beam_BadArguments.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2655482/Beam_BadArguments.zip) : (musx, xml, pdf)
} to https://opensheetmusicdisplay.github.io/demo/  ( 0.6.6 (https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/472#issuecomment-445162944))
then causes an error:

```js
Uncaught t?{code: "BadArguments", message: "Beams can only be applied to notes shorter than a quarter note."} demo.min.js:formatted:9696
  code: "BadArguments"
  message: "Beams can only be applied to notes shorter than a quarter note."
e @ demo.min.js:formatted:9696
e.finalizeBeams @ demo.min.js:formatted:45771
e.graphicalMeasureCreatedCalculations @ demo.min.js:formatted:45903
e.graphicalMeasureCreatedCalculations @ demo.min.js:formatted:41900
t.createGraphicalMeasuresForSourceMeasure @ demo.min.js:formatted:27283
t.prepareGraphicalMusicSheet @ demo.min.js:formatted:26374
t.initialize @ demo.min.js:formatted:26360
t @ demo.min.js:formatted:33430
t.load @ demo.min.js:formatted:36764
P @ demo.min.js:formatted:53236
e.onload @ demo.min.js:formatted:53301
load (async)
(anonymous) @ demo.min.js:formatted:53300
```

for the reference, {museScore, https://www.soundslice.com/musicxml-viewer/, finale + xml and finale generated pdf image}  is as  follows:

![image](https://user-images.githubusercontent.com/3293067/49621008-ba786400-fa06-11e8-82ad-e244b72a6f0d.png)

Beam_BadArguments.xml may contains some features (I'm not tested with OSMD):
- `<notehead filled="no">normal</notehead>`
  - https://www.soundslice.com/musicxml-viewer/, museScore: NG filled
- `<tuplet bracket="no" number="1" show-number="none" type="start">`
  - https://www.soundslice.com/musicxml-viewer/: NG : shown
- `        <time-modification>
          <actual-notes>2</actual-notes>
          <normal-notes>8</normal-notes>
        </time-modification>`

BTW, how can I get OSMD version from demo.min.js (or others)?

Regards

**Comment by sug1no** [comment]
> Are these tremolos? 

yes!

>  Do you want to know which version of OSMD is used in the demo? 

yes, I wanted to leave demo.min.js version as environmental information to reproduce this problem to this issue.

**Comment by sschmidTU** [comment]
Hmm, i don't think you can get the OSMD version from the demo.min.js right now. We could include an OSMD class member like this.version = x. The current version is 0.6.6 by the way.

Unfortunately, it seems like Vexflow can't draw beams between half and quarter notes for tremolos, even if you comment out the check that produces the error you pointed out in Vexflow.

For now, we could just ignore these beams.

**Comment by sug1no** [comment]
Thank you for your response!

I think the version property may be helpful to you in the future. 😄 

> Vexflow can't draw beams between half and quarter notes 

The tremolos in Beam_BadArguments.xml are generated by Finale 2014 + Easy Tremolos Plug-in:
<http://usermanuals.finalemusic.com/Finale2014Mac/Content/Finale/Easy_Tremolos_Plug_in.htm>

As you may already know about the following ...

The tremolos in Beam_BadArguments.xml seems to be defined as follows:
- ` <note> ...<type>16th</type> ... </note>`: 16th notes: 
  - <https://usermanuals.musicxml.com/MusicXML/Content/ST-MusicXML-note-type-value.htm>
  - <https://www.musicxml.com/tutorial/notation-basics/note-appearance/>
- with beam
- 2:8 tuplet (with time-modification and tuplet)
  - <https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-time-modification.htm>
- `<notehead filled="no">` to render hollow notehead:
  - <https://usermanuals.musicxml.com/MusicXML/Content/AT-MusicXML-filled.htm>

>Unfortunately, it seems like Vexflow can't draw beams between half and quarter notes for tremolos

Because I thought why {half and quarter note}? attached one more simple test [16th_tuplet_2_8.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2661033/16th_tuplet_2_8.zip) to test :
- 16th notes
- 2:8 tuplet

And images of {16th_tuplet_2_8.xml with (OSMD 0.6.6, museScore 2.3.2, soundslice, finale(xml, pdf)} and vexflow example are as follows:

<img src="https://user-images.githubusercontent.com/3293067/49704426-5b109300-fc56-11e8-9e42-ffe82962bef5.png" height="400">

- OSMD renders quater notes (not 16th). Does OSMD ignore note.type property(`note.type=16th`) ?
- I think vexflow can render 16th notes(with beam) + 2:8 tuplet(need to place 16th notes as quarter notes) :
  - <https://github.com/0xfe/vexflow/wiki/Tuplets>
  - <http://jsfiddle.net/y6dcnpe1/> 

Regards

**Comment by sschmidTU** [comment]
I fixed tremolos between quarter or longer notes causing an error in Vexflow by ignoring them, for now.
Currently it looks like this:
![image](https://user-images.githubusercontent.com/33069673/51267359-cc620500-19bd-11e9-9fd6-f02d96a0b4ef.png)

Next step will be to get the beams to display, somehow. It's unfortunate Vexflow can't draw beams between notes => quarter. Maybe patching Vexflow is easier than dealing with it in OSMD.

**Comment by sschmidTU** [comment]
fixed. half note tremolo/beams are now possible, and note.type is now used for tuplets (since an older commit, see #485).

![image](https://user-images.githubusercontent.com/33069673/53107139-b7d0d980-3534-11e9-879e-5b3d352b8236.png)

![image](https://user-images.githubusercontent.com/33069673/53107113-a687cd00-3534-11e9-93af-03b50de4dc6e.png)
