### ISSUE TITLE
Using Timestamps to move the Cursor

### ISSUE THREAD

**Issue by loganknecht** [opensheetmusicdisplay/opensheetmusicdisplay#480]
Hey folks. I hope this isn't an inappropriate issue request to raise, but I've been reading through documentation, the example repositories, the issues and I can't seem to find anything directly related to this.

I would appreciate any guidance on this.

#  Problem

I want to to display a cursor by using a timestamp that represents the current time in the song when using an arbitrary tempo.

The idea is that I have a `start timestamp` that represents when the song started "playing", then using an arbitrary timestamp via something like `new Date()` and a `tempo` I want to place the cursor where it should be on the Open Sheet Music Display Render based on that context.

The cursor should draw on the first note if the `current time` < `start time`
The cursor should draw in its respective location derived from the time stamp if `start time` < current_time` < `end time`
The cursor should draw on the end of the final staff if `current time` > `end time`

## Minimum Information Required
- `Song start timestamp` (Date): This is a timestamp of when the song started "playing"
- `Current timestamp` (Date): This is a current timestamp a.k.a. `new Date()`
- `Tempo` (number): This is the tempo of the song

# Existing Solutions
## Current Cursor
I see that there is a cursor implementation in OSMD that can be used. However I can't find a lot of documentation on it.

I do know that this test demonstrates how to add the cursor?
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/9da9cb4207e66e8654be7a4ca7755e3a4de7f6ed/test/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer_Test.ts#L36

And this webpack example shows how to display the cursor?
https://github.com/opensheetmusicdisplay/webpack-usage-example/blob/master/index.ts#L30

But again, I'm not sure I understand the nuance of its usage. 

The demo itself also shows the cursor usage here:
https://opensheetmusicdisplay.github.io/demo/

But this indicates that the cursor is displayed as a step based solution that iterates with respect to the notes, and does not appear to iterate based on time through some song?

## Personal Solution
I've attached a file called `open_sheet_music_display_helpers` that I used personally in order to get this kind of information that I need for my project.
[open_sheet_music_display_helpers.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2715948/open_sheet_music_display_helpers.txt)

It has functions such as:
- `function getCurrentTimestamp()`
    - Returns a `new Date()`
- `function calculateVexflowNoteCenterPosition(vexflow_note)`
    - Used to make sure the time bar overlaps correctly on a note
- `function calculateTotalStaves(open_sheet_music_display_object, ensemble_index)`
    - Returns the total number of measures in the song
- `function calculateSongDurationInSeconds(open_sheet_music_display_object, tempo)`
    - Returns the total duration of the song in seconds based on the tempo. Uses the total number of staves and time signature to determine this
- `function calculateSongDurationInMilliseconds(open_sheet_music_display_object, tempo)`
    - Returns the total duration of the song in milliseconds based on the tempo. Uses the total number of staves and time signature to determine this
- `function calculatePercentageThroughSongByTime(open_sheet_music_display_object, song_start_timestamp, current_timestamp, tempo)`
    - Returns a floating point number that indicates the the percentage through a song using a time stamp to determine the position
    - Floors and ceilings the output so that it can't be outside of the first note or last note
- `function convertTimeStampToStaveIndex(open_sheet_music_display_object, song_start_timestamp, current_timestamp, tempo)`
    - Returns the stave that the currentTimestamp is "in"
- `function convertTimeStampToNoteIndex(open_sheet_music_display_object, song_start_timestamp, current_timestamp, tempo, ensembles )`
    - Returns the note that the currentTimestamp is "in", a.k.a. the current not being played
- `function convertTimestampToSheetMusicPositionRelativeToNotes(open_sheet_music_display_object, song_start_timestamp, current_timestamp, start_note_ensemble_index, start_note_stave_index, start_note_index, next_note_ensemble_index, next_note_stave_index, next_note_index, tempo, ensembles)`
    - Returns a position object with x and y indicating where the timestamp would draw on the sheet
- `function convertTimestampToVexflowSheetMusicPosition(open_sheet_music_display_object, song_start_timestamp, current_timestamp, tempo, ensembles)`
    - Returns a position object with x and y indicating where the timestamp would draw on the sheet
- `function retrieveVexflowStave(open_sheet_music_display_object, ensemble_index, stave_index)`
    - Returns the stave specified
- `function retrieveVexflowNotes(open_sheet_music_display_object, stave_index, note_index)`
    - Returns the notes specified 
- `function retrieveVexflowNote(open_sheet_music_display_object, ensemble_index, stave_index, note_index)`
    - Returns the notes specified 

# Question

So with all this said my questions are this

- Is there more documentation on the `Cursor` functionality that can provide more guidance?
- Is there a mechanism to draw the cursor implementation in the current Open Sheet Music Display library with respect to `start time`, `current time`, and `tempo` variables?
- Is there a mechanism to draw the cursor implementation in the current Open Sheet Music Display library in a continuous fashion, rather than the discrete steps based on the demo?
- Is there a mechanism to calculate how long a song is in milliseconds based off the time signature and a tempo, if so how?
- Is there a mechanism to calculate how long a song is in seconds based off the time signature and a tempo, if so how?
- Is there a way to convert a `TimeStamp` to represent the percentage through the song, based on tempo
- Based on the percentage through the song is Is there a way to convert a `TimeStamp` to the respective x position of the sheet music staff?
- Based on the percentage through the song is Is there a way to convert a `TimeStamp` to the respective y position of the sheet music staff?
- Is there a mechanism to interrogate specific instruments, staves, and/or notes to determine their positions in the sheet music display (i.e. instrument 0, stave 0, note 0, position x or y)?

# Final Thoughts

I realize this is a pretty open-ended question, and I'm under the impression these aren't directly supported in Open Sheet Music Display, but from my personal experience building a timer display on top of this wonderful library I think they would be very valuable.

I see similar pieces in areas of the codebase like this:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/GraphicalMusicSheet.ts#L776

Where it is using a timestamp to determine position.

I just don't know how to leverage the existing code in the the library to achieve what I want.

I would appreciate any guidance on how to work the most efficiently with the library to achieve this, because at the moment I feel like I'm hacking away at the edges of your library 😄

**Comment by sschmidTU** [comment]
The [Cursor class](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/master/src/OpenSheetMusicDisplay/Cursor.ts) is very simple, so reading its code is the best documentation. The main functions are show(), hide(), and next().

Accessing a specific part of the piece by timestamp is not such a good idea in my opinion. You are probably trying to synchronize it with some playback. In that case, you need to calculate which notes you can skip ahead to. An eigth note is an eigth of the duration of a full measure.
The better solution would be to coordinate playback with the cursor and update the cursor every time you play the next note. You can find such examples here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/258#issuecomment-406620322

The answer to the first three questions is No.
> Is there a mechanism to calculate how long a song is in milliseconds based off the time signature and a tempo, if so how?
Yes, that's just maths. A 4/4 song with 60 bpm and 60 bars is 60*4 seconds long. Bpm is beats per minute. You may have to count the beginning and ending separately though, if there's a pickup bar or the last bar of the piece isn't full.

> Is there a way to convert a TimeStamp to represent the percentage through the song, based on tempo
If you solved the previous problems, it's again just maths.

> Based on the percentage through the song is Is there a way to convert a TimeStamp to the respective position of the sheet music staff?
You can either use percentage or TimeStamp, Then you need to calculate which note you land on (maths, see above), then put the Cursor there, get the note under the cursor, and get its position.

> Is there a mechanism to interrogate specific instruments, staves, and/or notes to determine their positions in the sheet music display (i.e. instrument 0, stave 0, note 0, position x or y)?
Yes, notes and staves have an AbsolutePosition and a RelativePosition. For a note, the RelativePosition is the (beginning of the) corresponding stave the note is placed in.

Again, you need to somehow set the cursor intelligently, then see what's under the cursor.
You can see [here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/453) for some inspiration on getting notes under the cursor.

**Comment by loganknecht** [comment]
Very cool! I can definitely understand why that decision was made.

With respect to the calculation helpers I mentioned. I was thinking they could be added to the [MusicSheetCalculator](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/46715d97360445b9906b95f4be504bb22b1f0d90/src/MusicalScore/Graphical/MusicSheetCalculator.ts). Is that ok?

I am excited to make the pull request, when my time permits!

**Comment by sschmidTU** [comment]
MusicSheetCalculator is maybe not the best place to add these methods, because this class is for creating the music sheet logic, for which we do not need timings in seconds. Unless that's where the corresponding logic is, but maybe you could then just send the relevant information to another method. Why not add it to the Cursor class or to a new helper class?

**Comment by sschmidTU** [comment]
By the way, we appreciate the support! We have thought about adding many features like these, but we have to set priorities. We're also open to changes to existing features, we just try to keep the logic in the project consistent especially where it affects other parts.

**Comment by ronnycsharp** [comment]
Hi, I've seen this discussion and I have similar requirements. 
Is there any progress within a helper-class or any additional information about absolute timings of each note? I'd like to sync midi playback and the musicxml sheet.

Kind regards
Ronny

**Comment by sschmidTU** [comment]
No. This would be neat to integrate into OSMD, but it's not strictly a score rendering feature.
Others have done this before, see here: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/258#issuecomment-406620322

**Comment by sschmidTU** [comment]
@ronnycsharp loganknecht added his OSMD timestamp helper methods to [the first comment of this thread](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/480#issue-394746188).

Also, there was a conversation about how to get timestamps on [OSMD's Gitter](https://gitter.im/opensheetmusicdisplay/opensheetmusicdisplay), where @praisethemoon recommends ToneJS:

<details>

<summary>ToneJS recommendation and conversation on Gitter</summary>

I use ToneJS for that, i schedule a list of notes to be played
I save the notes time, and compare that time with the cursor current time
i use something like this
while(cursor.iterator.time < note.time) cursor.next()

postdep lincoln
@praisethemoon How can the cursor be implemented if you want to customize the speed? And your example can dynamically adjust the speed. Can you give me some advice on this idea? Another way I figured out was that I dynamically generated MIDI files and played them back in the background, so that osmd focused on video. Reduce coupling complexity, because I want to achieve bass and bass

praisethemoon
@postdep Same for me, OSMD handle only the display, I convert all notes times and durations to seconds. When a note is about to be played, I check if the cursor is at the correct position with this.osmd.cursor.iterator.currentTimeStamp.realValue
I compare that value with the note current timestamp, and make sure they are aligned

</details>

**Comment by praisethemoon** [comment]
Hello people! Sorry for joining so late, I will be honest and tell you that the conversation is so long that I will have to answer to answer the question directly without reading. First, checkout my tutorial on how to read note timestamps from OSMD here: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Tutorial:-Extracting-note-timing-for-playing

After extracting all notes start times and durations, you would want to reset the cursor, and capture the current visible notes with `this.osmd.cursor.iterator.currentVoiceEntries`. For each note, you want to compare the note timestamp with `osmd.cursor.iterator.currentTime`, and use the following pseudo code:

```
while(osmd.cursor.iterator.currentTime < currentNote.timestamp) {
    osmd.cursor.next()
}
```

Let me know if that helps! (or if it doesn't)

**Comment by sschmidTU** [comment]
Right, i forgot about that Wiki page, sorry!

**Comment by ilionic** [comment]
Any tips achieving aforementioned cursor behaviour in continuous fashion?

**Comment by loganknecht** [comment]
@ilionic You should check out the cursor logic. It's the best place to start. I've got a variation of that working, but haven't had the chance to submit a solution to the repo.

The key thing you'll need to do is get the location of the notes, calculate the time you are through the current note and then draw at the appropriate distance between them.

**Comment by ilionic** [comment]
Thanks for heads up @loganknecht ! I was initially thinking about approach similar to flowkey ( static cursor but scrolling score ) but your suggested way sounds more approachable.

**Comment by sschmidTU** [comment]
If you have any more questions, feel free to ask, just closing this for now.

**Comment by BALAVIGNESHDOSTRIX** [comment]
how to move the cursor based on the metronome
