### ISSUE TITLE
[Feature Request] Ability to render parts of a score

### ISSUE THREAD

**Issue by turnerhayes** [opensheetmusicdisplay/opensheetmusicdisplay#482]
This may be prohibitively difficult, but it would be really neat if this library could render individual segments of a score (I'm thinking single measures). A use case for this would be if you wanted to progressively and interactively show a piece as it was playing.

**Comment by loganknecht** [comment]
This would be amazing! +1 on this request!

It would be fantastic if we could arbitrarily select measures to render. I know that ties, slurs, etc. might make it difficult, but it would be fantastic to select any possible combination.

For those instances, I'm of a mind where I'd say they wouldn't need too be rendered,.

It's usage might be like
'osmd.render()'

But then also something like
'osmd.render([1,2,3])'
or
'osmd.render([1,5,9,11])'

**Comment by sschmidTU** [comment]
This would be awesome, yes, though it may well require huge changes in the code. I've looked at this before, the problem is that many different methods try to access the whole xml and score.

There is already an option to draw measures 1 to X, where you specify X. Have you seen that?
[See OSMDOptions](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/OpenSheetMusicDisplay/OSMDOptions.ts)

Of course drawing arbitrary measures would be nice, but it might be hard. Maybe i'll look at this again in the near future, because several people would like to have this.

In the meantime, you could try various programs to extract specific measures from a piece/XML and make it into a new XML.

**Comment by loganknecht** [comment]
@sschmidTU do you have specific library/program suggestions?

Right now I'm using music21, a python library, to break a song into single measures and it works, but it's just ok. Do you know if there is a JavaScript specific library to do the same or have any guidance?

Also very cool feature from 1 to X! I didn't know that!

**Comment by sschmidTU** [comment]
I don't have library suggestions for this, sorry. I would use Musescore for this to do it manually, but i haven't needed to extract bars from pieces automatically yet.
Good to know that music21 can do this though. I've heard of it before, the maker is an active contributor to Vexflow too.

**Comment by turnerhayes** [comment]
Thanks for the suggestion and the pointer to `drawUpToMeasureNumber`! Maybe you could add a `drawFromMeasureNumber` option (or something). It looks like it would be pretty easy to implement; it seems like you can just change [this line](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/MusicSheetCalculator.ts#L674) to be something like

```
for (let idx: number = (EngravingRules.Rules.MinMeasureToDrawIndex || 1) - 1, len: number = allMeasures.length; ...
```

That would take care of the use case of drawing one measure, or one contiguous set of measures. It would be better, of course, if we could change the drawing range after it's loaded rather than having to render a new OSMD object each time, but at least for a first pass, this would help.

**Comment by turnerhayes** [comment]
FWIW I have implemented a measure extraction function that seems to work (at least on the XML I have tried it on):

```
Array.from(doc.querySelectorAll("measure")).forEach(
    (measureNode) => {
      const currentMeasureNumber = Number(measureNode.getAttribute("number"));

      if (currentMeasureNumber === measureNumber) {
        if (attributesNode && !measureNode.querySelector("attributes")) {
          measureNode.insertBefore(attributesNode, measureNode.children[0]);
        }

        return;
      }

      if (currentMeasureNumber < measureNumber) {
        const currentAttributesNode = measureNode.querySelector("attributes");

        if (currentAttributesNode) {
          attributesNode = currentAttributesNode;
        }
      }

      measureNode.parentNode.removeChild(measureNode);
    }
  );

  return doc;
}
```

Mostly seems to work, although it's not drawing measure numbers, which is unfortunate.

**Comment by sschmidTU** [comment]
> Thanks for the suggestion and the pointer to `drawUpToMeasureNumber`! Maybe you could add a `drawFromMeasureNumber` option (or something). It looks like it would be pretty easy to implement; it seems like you can just change [this line](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/MusicSheetCalculator.ts#L674) to be something like
> 
> ```
> for (let idx: number = (EngravingRules.Rules.MinMeasureToDrawIndex || 1) - 1, len: number = allMeasures.length; ...
> ```
> That would take care of the use case of drawing one measure, or one contiguous set of measures. It would be better, of course, if we could change the drawing range after it's loaded rather than having to render a new OSMD object each time, but at least for a first pass, this would help.

I tried this and i get one error after another, because as i said many different parts of the code try to access all measures of the score. I tried fixing the first error, but got another, and i think it'll continue for a while. So as i said, this can't be implemented by changing one line.

@turnerhayes Your second method of extracting measures seems neat. Would be even better if we manage to keep drawing measure numbers. Where would you insert this in our code? (i could infer that, but i hope you'll save me the time to check, because you already tried it)

**Comment by turnerhayes** [comment]
Ah, I'm sorry to hear that. I hadn't actually tried it, just hoped it would be that simple.

I don't know if my extraction code would integrate with the actual library very well; I used it like so:

```
const sheetDisplay = new OpenSheetMusicDisplay(
        this.containerRef.current,
        {
          autoResize: false,
        }

      xml = getMeasure(xml, measureNumber);
    
      sheetDisplay.load(xml)
        .catch(
          (err) => console.error(err)
        );
```

Not as efficient as it could be, of course, but it at least seems to function.

**Comment by sschmidTU** [comment]
@turnerhayes there are now OSMD options minMeasureToDraw and maxMeasureToDraw.
release will be out soon as well.
In the Demo there's a new OSMD Function Test that will select random measures to draw everytime you click Clear and Re-Render.
![image](https://user-images.githubusercontent.com/33069673/61163067-33dfb400-a50c-11e9-82f8-e6b110b4b852.png)

**Comment by sschmidTU** [comment]
Most of the work was done by @praisethemoon in PR #528, i added a few fixes.
