### ISSUE TITLE
Dotted rest notes cause misalignment of following notes

### ISSUE THREAD

**Issue by davidsancal** [opensheetmusicdisplay/opensheetmusicdisplay#484]
I was trying out your new version and in a score that I have, a part is visualized badly (a note is displaced)
Attached image
<img width="341" alt="captura de pantalla 2019-02-06 a las 12 03 36" src="https://user-images.githubusercontent.com/39929700/52337202-4f97d900-2a07-11e9-9ddf-00650416ecd1.png">

**Comment by sschmidTU** [comment]
Hi, thanks for submitting an issue!
Unfortunately I could not reproduce this bug by copying the extract of your score.
Could you give me a more complete xml extract that will reproduce this issue?

Here is the score i tested:
![image](https://user-images.githubusercontent.com/33069673/52342192-fdf64b00-2a14-11e9-8b4c-a95f041b398a.png)

[Alignment dotted half break test.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2836351/Alignment.dotted.half.break.test.musicxml.zip)

**Comment by sschmidTU** [comment]
Also @davidsancal do you have any hidden notes in this bar or the bar before? We are aware of issues with hidden notes and layouting.

**Comment by davidsancal** [comment]
Hi @sschmidTU , I'm attaching an xml file with the bug
[prueba.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2841446/prueba.xml.zip)

**Comment by sschmidTU** [comment]
Fixed.

Sample from @davidsancal:
![image](https://user-images.githubusercontent.com/33069673/52494170-90414f00-2bcd-11e9-8686-d9ac2fa5f75b.png)

Double dotted rest:
Before:
![image](https://user-images.githubusercontent.com/33069673/52494261-d7c7db00-2bcd-11e9-803e-b012b57b456f.png)

After:
![image](https://user-images.githubusercontent.com/33069673/52494277-e0b8ac80-2bcd-11e9-9487-9502f392c7ed.png)

@davidsancal I will make a new release of OSMD with this fix in the coming days, I will notify you again then. Thanks for pointing out the issue!

**Comment by sschmidTU** [comment]
@davidsancal OSMD 0.6.8 is released, including a fix for your bug. Thanks again!
