### ISSUE TITLE
Automatic coloring of notes by key

### ISSUE THREAD

**Issue by davidsancal** [opensheetmusicdisplay/opensheetmusicdisplay#486]
Hi!

There would be some way to color the scores automatically by assigning a color to each note, for example, that the C's look red, the D's yellow ...

Thanks!

**Comment by sschmidTU** [comment]
Hi, we've actually been thinking about this, and we intended to use the Boomwhacker coloring as a default (were you thinking of Boomwhackers too?), ideally you could configure the colors as an option.
This would be nice to have, we'll see if we can make it a priority.

For now, you can of course color your scores manually in a sheet music program (e.g. MuseScore) or XML, OSMD will show colors of notes and rests given in the MusicXML file.

**Comment by davidsancal** [comment]
If it would be good for children. I've tried to paint with musescore but it just paints the head of the note. It's as if exporting the xml does not save that data since I would like to be able to paint the whole note and not just the head

**Comment by bneumann** [comment]
![image](https://user-images.githubusercontent.com/2605131/53298902-38911d80-3834-11e9-896d-1c2218062ec7.png)

Tataaa

**Comment by sschmidTU** [comment]
Colors modified to be better visible,
and there is now an option to give a custom color set (HTML Hex strings) for the 7 notes and rests.
This is now the OSMD Function Test - Auto-Coloring.
![image](https://user-images.githubusercontent.com/33069673/53306304-d9f78e00-388b-11e9-8d6b-1c9c4d245bad.png)

**Comment by sschmidTU** [comment]
@davidsancal by the way, Musescore does not export all colors to XML unfortunately, you'll have to put it into the XML yourself or use another program, unfortunately

**Comment by bneumann** [comment]
@davidsancal if that's approximately what you wanted I'd like to close the issue. The PR is merged in will come with the next release

**Comment by sschmidTU** [comment]
We should probably give an option to also color the stems in the same color, otherwise they will remain black.
I will probably do that and make the automaticColoring option an object with suboptions, shouldn't take long.
```javascript
osmd.setOptions( {
  autoColoring: {
    enabled: true
    coloringMode: 2
    coloringSetCustom: ["#d82c6b", "#F89D15", "#FFE21A", "#4dbd5c", "#009D96", "#43469d", "#76429c", "#ff0000"]
    colorStemsSameAsNoteheads: true
  }
});
```

instead of as it is right now:
```javascript
            openSheetMusicDisplay.setOptions({
                coloringMode: 2,
                coloringSetCustom: ["#d82c6b", "#F89D15", "#FFE21A", "#4dbd5c", "#009D96", "#43469d", "#76429c", "#ff0000"]
                // last color value of coloringSetCustom is for rest notes
            });
```

I think there are some other options that can be unified into an object as well.

**Comment by davidsancal** [comment]
If you could paint the whole note it would be fantastic

**Comment by sschmidTU** [comment]
Yes, we can already color whole notes with the new Auto-Coloring mode.
But it's still a good mention, we should include whole notes and rests in the coloring sample.
![image](https://user-images.githubusercontent.com/33069673/53574388-cb50f580-3b6f-11e9-8a9b-26c7d2ae876a.png)

**Comment by embeddedt** [comment]
Has stem coloring been implemented? I can't find it in the current version.

**Comment by sschmidTU** [comment]
hold my beer

**Comment by sschmidTU** [comment]
You're probably looking for stems to be colored the same as noteheads in autocoloring modes, right?
We could make a general option `colorStemsSameAsNoteheads: boolean` which also applies when taking color information from XML.
Though in that case there can be specific colors set for the stems in XML and those should probably take precedence.

**Comment by loganknecht** [comment]
Hello @sschmidTU! Still love the work you're doing, and still support this cause one-hundy!

I hope this isn't too distracting from the conversation.

With respect to note coloring, and stem coloring: I too am trying to leverage this functionality, however I am doing my coloring after the rendering has occurred. I do this by targeting the element that is rendering and modifying the CSS associated with it.

I was hoping to communicate that there is an additional use case for coloring that I would like to request be considered.

Specifically In this instance, **I would like to request that there be support for coloring the notes and note stems after rendering**.

It would be particularly helpful if this could targeted on a per note basis. I don't have access to my code at the moment to demonstrate how I'm doing this, but can provide and example of what I'm doing if needed.

**Comment by sschmidTU** [comment]
Hi @loganknecht, that's nice to hear!
Unfortunately, redrawing small parts of the measure like single notes in Vexflow is not so easy and not yet supported in OSMD.

I've said it elsewhere, we'd need a custom rerendering system where we can rerender specific parts of the sheet without redrawing the whole sheet, and we do not have that yet.
And for that we probably need to clear a whole measure (paint over the bounding box of the measure with transparent color) and redraw that measure, because if you just erase a single note, it'll erase everything behind it like staff lines, so it will "leave a hole".
How difficult this will be i'm not sure.

**Comment by sschmidTU** [comment]
@embeddedt I added a `colorStemsLikeNoteheads` option.
If you set it to true, the autocoloring mode will color the stems like the noteheads, like this:
![image](https://user-images.githubusercontent.com/33069673/61161434-f4ad6500-a503-11e9-854c-75b7c54dcc6a.png)

You can try it in the demo by selecting the OSMD Autocoloring sample.
We'll probably also make a new release soon (which will enable drawing from measures x to y), then it will be in the online demo too.

**Comment by embeddedt** [comment]
@sschmidTU Thank you! I will test it and get back to you tomorrow.

**Comment by embeddedt** [comment]
@sschmidTU Works very well, thanks for the quick implementation!

**Comment by bneumann** [comment]
I remember we implemented it. Closing it now
