### ISSUE TITLE
Irrelevant production dependency

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#487]
The dependency list on npm just caught my attention, listing 7 required dependencies. As I was wondering what these could be, I found that `increase-memory-limit` is almost certainly not required in production, which is why it should be moved to `devDependencies`.

https://www.npmjs.com/package/opensheetmusicdisplay?activeTab=dependencies

**Comment by sschmidTU** [comment]
Good catch! I'll take a look.

**Comment by sschmidTU** [comment]
Yes, increase-memory-limit is only used as an npm script right now, seems like we don't even need it as a devDependency anymore.
@bneumann you have used increase-memory-limit in the past, right? Do we still need it?

Also, it seems like we don't need shortid (unique id generator) as a dependency at all. It's only used in the BaseIdClass, which 2 classes inherit from (Tie and SourceMeasure), but the ids aren't used at all.

**Comment by bneumann** [comment]
We certainly won't need increase memory limit in production so dev is fine.

The shortid is AFAIK just ported from the main code. Has no use here in JS.
