### ISSUE TITLE
Using OSMD to generate SVG on mobile

### ISSUE THREAD

**Issue by YotaVGA** [opensheetmusicdisplay/opensheetmusicdisplay#491]
I'm new with many of the concepts I'll use in this question so I'm not sure to not to make any errors formulating it.

I'd like to use OSMD on mobile without using a web view but extracting the SVG. With software like [LiquidCore](https://github.com/LiquidPlayer/LiquidCore) and [jsdom](https://www.npmjs.com/package/jsdom) it seems possible to execute on mobile the script, and then extract the SVG from the DOM. Do you see any flaws with this workflow? Or a way to do it better?

But, supposing that all the procedure is ok, I have many other doubts. In particular I'd like to know if the fonts used from the SVG are embedded in it, and which SVG features I should support to let it works correctly. In my specific framework probably I won't be able to use the SVG directly so I'll have to render it on another image, and I need to know this to know if there exists a good library to convert it on mobile (specifically Android and iOS)

**Comment by bneumann** [comment]
Hi,

so from what I understand your focus is on mobile right? So problem with the most frameworks is, that they miss classes we take for granted in opensheetmusicdisplay for the browser.  Such as document, window, etc.
So say you use jsdom to mock and fake all that you might get a proper SVG on your mobile. 

As for the fonts, you will only see Times New Roman as we currently only support this font. And we don't render text as shapes so it depends on your renderer how it interprets something like

`<text stroke-width="0.3" fill="black" stroke="none" stroke-dasharray="none" font-family="Times New Roman" font-size="23px" font-weight="bold" font-style="italic">ppp</text>`

But as far as I can tell this is not really about our library but more about using a mobile framework for rendering SVG right?

**Comment by sschmidTU** [comment]
There's some related discussion about SVG and rendering without DOM in #432, but this probably isn't going to help you much. Unfortunately this isn't solved yet, OSMD is pretty much made for the Browser, for now. Would be nice to be able to use it directly in Apps in the future, of course.

**Comment by YotaVGA** [comment]
> But as far as I can tell this is not really about our library but more about using a mobile framework for rendering SVG right?

@bneumann, you're right, but I had to know at least something about the SVG your library generate. Information you already wrote in your post, at least partially. And I hoped to know if the undertaking in general was realistically feasible, and your info about the classes used by OSMD seems to suggest the opposite.

> There's some related discussion about SVG and rendering without DOM in #432, but this probably isn't going to help you much. Unfortunately this isn't solved yet, OSMD is pretty much made for the Browser, for now. Would be nice to be able to use it directly in Apps in the future, of course.

@sschmidTU, as you wrote, sadly the post is not very helpful. I think that for my specific case I'll use a webview even if it is suboptimal, but the gain I'd obtain is too few to justify the effort that this task seems to entail

**Comment by sschmidTU** [comment]
@YotaVGA have you seen the feat/exporting branch? Getting the SVG is very easy with this branch. The question is if you can get the SVG to render correctly without a browser.

**Comment by bneumann** [comment]
I tried porting our library to plain node. That was quite tedious but worked in the end. Also mocking and wrapping it in react native worked but debugging was plain hell.
That said, it's a lot of work to get it run without web view and any change on our side can break the whole chain again 😢

**Comment by YotaVGA** [comment]
> But as far as I can tell this is not really about our library but more about using a mobile framework for rendering SVG right?

@bneumann, you're right, but I had to know at least something about the SVG your library generate. Information you already wrote in your post, at least partially. And I hoped to know if the undertaking in general was realistically feasible, and your info about the classes used by OSMD seems to suggest the opposite.

> There's some related discussion about SVG and rendering without DOM in #432, but this probably isn't going to help you much. Unfortunately this isn't solved yet, OSMD is pretty much made for the Browser, for now. Would be nice to be able to use it directly in Apps in the future, of course.

@sschmidTU, as you wrote, sadly the post is not very helpful. I think that for my specific case I'll use a webview even if it is suboptimal, but the gain I'd obtain is too few to justify the effort that this task seems to entail

**Comment by YotaVGA** [comment]
> @YotaVGA have you seen the new feat/exporting branch? Getting the SVG is very easy with this branch.
> The question is if you can get the SVG to render correctly without a browser.

@sschmidTU, that is really interesting, I'll give it a chance.

@bneumann, I think I want to avoid any solution that will require too much effort in updating my dependencies. But really thanks for the effort.

**Comment by sschmidTU** [comment]
this should now be possible, see #432. just needs a small adjustment of the PNG script.
