### ISSUE TITLE
Create index.ts files for easier importing

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#5]
E.g. in `src/index.ts`, put:

``` typescript
export * from "./Common";
export * from "./MusicalScore";
export * from "./Util";
export * from "./MusicSheetAPI";
```

in `src/Common/index.ts`, put:

``` typescript
export * from "./Calculation";
export * from "./Graphical";
export * from "./Interfaces";
export * from "./MusicParts";
export * from "./MusicSource";
export * from "./ScoreIO";
export * from "./VoiceData";
export * from "./Exceptions";
export * from "./Instrument";
export * from "./InstrumentalGroup";
export * from "./Label";
export * from "./MusicSheet";
export * from "./SubInstrument";
```

etc. This is a non-breaking change, it just makes importing so much easier so this is quite a high-priority thing to do for a second release or so.

**Comment by sebastianhaas** [comment]
This allows, for instance, to import `MusicSheet` using
```typescript
import { MusicSheet } from "openmusicsheetdisplay";
```
which is clearly favorable.

**Comment by p-himik** [comment]
Actually, I don't think importing anything other than `OpenSheetMusicDisplay` is possible without this change when you use the npm package. `OpenSheetMusicDisplay` is the only thing that's added to the exports.

**Comment by sebastianhaas** [comment]
Yep. In the meanwhile, I'm not so confident about exporting everything on root level anymore, but clearly something like
 
```typescript
import {  Module } from "openmusicsheetdisplay/certainArea";
```

would be beneficial over 

```typescript
import {  Module } from "openmusicsheetdisplay/path/to/certain/area/and/module";
```

**Comment by sebastianhaas** [comment]
Would you mind sharing your use case? Or reasons why you prefer one approach over the other? Just to have some background. :)

**Comment by p-himik** [comment]
@sebastianhaas I don't have a preference, it's just that right now I don't have a way to use `OpenSheetMusicDisplay` without the class with the same name. Or maybe I'm doing something terribly wrong - always a possibility. But I still don's see any way to import e.g. `IXmlElement` from the npm module.

The issue with `OpenSheetMusicDisplay` class is that it always draws with `isPreviewImageDrawer` set to false and it also uses a cursor - I don't need any of that.

**Comment by sschmidTU** [comment]
We could provide an optional DrawingParameters argument for the OpenSheetMusicDisplay constructor,
it wouldn't change existing code.

It could be a string with possible values `allOn/default`, `thumbnail`/`preview`/`basic` (one of these names) and `leadsheet`.

@p-himik that would at least allow you to use isPreviewImageDrawer drawing parameters, which disable the cursor.

**Comment by bneumann** [comment]
@sschmidTU sounds like #288 to me 😉

**Comment by sschmidTU** [comment]
@bneumann oh, yes, that would be a much better solution. let's get to it then ;)

**Comment by sebastianhaas** [comment]
>  But I still don's see any way to import e.g. IXmlElement from the npm module.

You can do that with a direct path to the module. However, you should not need to use it. Plus, for all other modules that might be beneficial in advanced use cases, we should offer a better import structure. That's what this issue is about. The thumbnail/cursor thing belongs to #288.

**Comment by p-himik** [comment]
@sebastianhaas The compiled version of the library (a single JS file) exports only a single class, other classes are hidden by the Webpack machinery.
But maybe I don't know something, I don't use Webpack in my workflow at all. Could you please provide an example of how one should import any class other than `OpenSheetMusicDisplay` when using the npm version of the library?

**Comment by bneumann** [comment]
These index files are only for internal purposes. After transpiling you will only see the opensheetmusicdisplay library as one file. We could however export other things as well.
But for example the mentioned ```IXmlElement``` would not make sense to me at all.

**Comment by bneumann** [comment]
So I tried creating index files a few days back hunting for the karma bug. I have a local branch with the changes but unfortunately it does not build anymore.
Somehow if you use this technique you have to manually check the order of imports of the files. Which sucks.
See: https://stackoverflow.com/questions/48990604/webpack-dependencies-from-index-ts-resolved-in-wrong-order

**Comment by sschmidTU** [comment]
@p-himik At least you can disable the cursor now and set the drawing parameters to thumbnail mode, via IOSMDOptions parameter in the constructor. (develop branch)

**Comment by sschmidTU** [comment]
I also tried adding sample index files, and in the [webpack usage example project](https://github.com/opensheetmusicdisplay/webpack-usage-example), importing the classes worked by importing from "opensheetmusicdisplay", but i couldn't use them.

@bneumann It's too bad webpack can't import Typescript files in the right order, it just doesn't understand Typescript. How much work is it to manually order the imports? Can you push your test branch? Maybe we could just add a reduced set of indexes for now.

By the way, here's an interesting article about bundling typescript libraries with webpack. It also mentions you should have a .npmignore because otherwise npm uses .gitignore? Though this doesn't seem to be an issue for us for now.
https://marcobotto.com/blog/compiling-and-bundling-typescript-libraries-with-webpack/

**Comment by sschmidTU** [comment]
@bneumann I just put up PR #458 which exports all OSMD classes and seems to work in the webpack usage example project (at least using Cursor and Note).

**Comment by sschmidTU** [comment]
Also, it doesn't seem like export or import order matters anymore, because i can import both Note and VoiceEntry in the project and these classes import each other.
Maybe Webpack got smarter, we just [updated it to 4.25.0 9 days ago](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/eaf852911d1410ef4ce0f414abb655c5c7ffb62a).
