### ISSUE TITLE
SVG/Vexflow to MusicXML ?

### ISSUE THREAD

**Issue by MarianneAK** [opensheetmusicdisplay/opensheetmusicdisplay#500]
Converting MusicXML to Vexflow is possible but what about the opposite ?

**Comment by bneumann** [comment]
Hi, 

that would be possible, but it can't be done in opensheetmusicdisplay. I am also not sure if there are a lot of use cases for this. That's like convertig a PDF to a word document. Quite interesting but really hard to do.

**Comment by MarianneAK** [comment]
> Hi,
> 
> that would be possible, but it can't be done in opensheetmusicdisplay. I am also not sure if there are a lot of use cases for this. That's like convertig a PDF to a word document. Quite interesting but really hard to do.

Well I thought so, but I need this in a project where the user can write musical scores and export them to MusicXML/MEI.
Guess it has to be implemented.

**Comment by loganknecht** [comment]
@MarianneAK You might want to check out https://flat.io for that

**Comment by sschmidTU** [comment]
flat.io doesn't seem to be able to handle Vexflow, but it can export to MusicXML.
Looks like a neat tool for collaborative score writing!
