### ISSUE TITLE
Manual adjustment of the OSMD layout / content

### ISSUE THREAD

**Issue by byebb** [opensheetmusicdisplay/opensheetmusicdisplay#501]
After loading a MusicXML Document, I would like to programmatically add some analysis visualizations about the content of the document on top of the measures.

To achieve this, I need to increase the space between two adjacent systems / connected stave lines.

For the additional content I need the position of the single measures, or even better the x/y position of single note for the placement. 

I'm using JavaScript and I already found out, that I get the left upper corner for each measures by using this code for the first measure:

```
X = osmd.drawer.graphicalMusicSheet.measureList[0].boundingBox.dataObject.stave.x;
Y = osmd.drawer.graphicalMusicSheet.measureList[0].boundingBox.dataObject.stave.y;

```
Can you help me with getting the position of single notes?

In addition I would like to change for example single notes, how is this possible?

**Comment by sschmidTU** [comment]
To get the position of a single note, take the relativePosition (or absolutePosition) of the VoiceEntry's BoundingBox:
```js
osmd.graphic.measureList[0][0].staffEntries[0].graphicalVoiceEntries[0].boundingBox.relativePosition
> PointF2D {x: 0, y: 0.5}
```
The y-position starts at the top line of the system. 1 is the distance between one line and the next (e.g. for treble clef: top line (F) to line below (D). In Vexflow, it's 10.

For spacing, check EngravingRules.betweenStaffLinesDistance, which you can change before calling osmd.render(), and maybe afterwards if you then call osmd.render() again.
Also check the other layout constants there, you can change all of them.

You can try this sort of thing in the local demo using the Console:
![image](https://user-images.githubusercontent.com/33069673/54712124-d59d5880-4b4b-11e9-948e-327869851c40.png)
Instructions for running the local Demo:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Debugging

You can also use the online Demo, though to rerender you'll have to zoom in and out again.
https://opensheetmusicdisplay.github.io/demo/

```js
osmd.graphic.measureList[0][0].staffEntries[0].graphicalVoiceEntries[0].notes[0].sourceNote.noteheadColor = "#FF0000"
"#FF0000"
osmd.graphic.measureList[0][0].staffEntries[0].graphicalVoiceEntries[0].notes[0].boundingBox.absolutePosition
PointF2D {x: 22.4995200625, y: 23.22}
osmd.graphic.measureList[0][0].staffEntries[0].graphicalVoiceEntries[0].boundingBox.relativePosition
PointF2D {x: 0, y: 0.5}
osmd.graphic.measureList[0][0].staffEntries[0].boundingBox.relativePosition
PointF2D {x: 10.943856, y: 0}
```
By selecting VoiceEntries for "Show bounding box for", you'll see the position of notes visualized.

Coloring the notes is handy to debug. After coloring, click the Re-render button.
For some reason, calling osmd.render() reloads the page right now. It should do the same as the re-render button.

Also, you can use the Cursor to select notes organically, as in the webpack example project:
```js
var cursor: Cursor = osmd.cursor;
	cursor.show();
	cursor.next();
	const cursorVoiceEntry: VoiceEntry = cursor.Iterator.CurrentVoiceEntries[0];
	const baseNote: Note = cursorVoiceEntry.Notes[0];
	console.log("Stem direction of VoiceEntry under Cursor: " + StemDirectionType[cursorVoiceEntry.StemDirection]);
	console.log("base note of Voice Entry at second cursor position: " + baseNote.Pitch.ToString());
```
https://github.com/opensheetmusicdisplay/webpack-usage-example/blob/master/index.ts

**Comment by sschmidTU** [comment]
Changing a note's pitch after it has been loaded from XML is not so easy.
I tried changing the pitch, but it doesn't affect the rendering unfortunately, because once the Vexflow Voice Entries have been set, it's hard to remove or replace them.
I can see if there's a way to make this possible, because that would be a neat feature.

**Comment by byebb** [comment]
Thank you so much for all the information! It helped me a lot!!! Changing notes similar as changing the color would be a great new feature! If you find a way to do this somehow, please let me know. 

Your explanations are very informative. Keep on doing your great work. Thanks!

**Comment by byebb** [comment]
> ```js
> osmd.graphic.measureList[0][0].staffEntries[0].graphicalVoiceEntries[0].notes[0].sourceNote.noteheadColor = "#FF0000"
> "#FF0000"
> osmd.graphic.measureList[0][0].staffEntries[0].graphicalVoiceEntries[0].notes[0].boundingBox.absolutePosition
> PointF2D {x: 22.4995200625, y: 23.22}
> osmd.graphic.measureList[0][0].staffEntries[0].graphicalVoiceEntries[0].boundingBox.relativePosition
> PointF2D {x: 0, y: 0.5}
> osmd.graphic.measureList[0][0].staffEntries[0].boundingBox.relativePosition
> PointF2D {x: 10.943856, y: 0}
> ```

Are the pixel distances the same as in the SVG or is there some different distance system in OSMD?

**Comment by sschmidTU** [comment]
Not sure, you should be able to find a scale factor to compute one from the other.
Perhaps it's x10? That's the factor from OSMD to Vexflow.

**Comment by matt-uib** [comment]
@byebb as @sschmidTU already explained in an upper post: one OSMD Unit derives from the vertical distance between 2 lines of the five lines of a stave. So every stave is 4 units in height (y direction) - always.
So the OSMD coordinates are the same for different zoom levels (besides that the measure layout might change while zooming).

**Comment by sschmidTU** [comment]
@byebb FYI, we just released OSMD 0.7.0 with a bunch of new features.
If you've been using the develop branch, only Tremolos and a few new options will be new to you.
Also, I've expanded on my first comment in this issue and made a Tutorial-like Wiki page out of it:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo

**Comment by byebb** [comment]
@sschmidTU Thank you very much!! That is good to know. I really appreciate all your work!

**Comment by victorhugoenri8** [comment]
I am implementing an app and everything is going well only that the indications do not render me from coda to coda nor do the section indications, and I downloaded all the github implem

**Comment by sschmidTU** [comment]
@victorhugoenri8 
Can you share a sample musicxml (zipped)?
This is an old and probably unrelated issue by the way.
