### ISSUE TITLE
Retrieving the most top position for each system

### ISSUE THREAD

**Issue by byebb** [opensheetmusicdisplay/opensheetmusicdisplay#502]
I've loaded the following XML with OSMD and enabled the SkyLine:

![image](https://user-images.githubusercontent.com/4288893/54833979-76605500-4cbf-11e9-8085-871be6e8f039.png)

As you can see, only the notes are considered for drawing the Skyline.

I want to retrieve the closest vertical position of a horizontal line that doesn't intersect with a system located on top of each system, like this:

![image](https://user-images.githubusercontent.com/4288893/54834273-20d87800-4cc0-11e9-99c8-9fa3b63eccf2.png)

How is it possible to retrieve this position as x and y coordinates relative to the main svg root (the x-y coordinates are not exact, but only a sketch).

What's the best way to get these coordinates?

**Comment by bneumann** [comment]
Oh, that's a good find. The repitition line should be considered by the Skyline calculation.

In general (meaning if that is fixed) you can just call the max or min functions of the Skybottomcalculator class. Every staffline has one.

**Comment by matt-uib** [comment]
@byebb actually the BoundingBox of every System should tell you this:
In the BoundingBox you have the relativePosition and also e.g. the borderTop.
if you take relativePosition.y + borderTop, then you get the y position of your blue line.
Only Problem is, that not all components are already considered for the skyline...
