### ISSUE TITLE
Converting OSMD coordinates to SVG Pixel coordinates

### ISSUE THREAD

**Issue by byebb** [opensheetmusicdisplay/opensheetmusicdisplay#504]
The new [Exploring-the-Demo](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo) page explains in detail how to get the OSMD coordinates of visual elements. To be independent of this coordinate system it would be really helpful to have an easy way to retrieve the corresponding pixel values x/y relative to the root of the general SVG that contains all the information.

Is it easy possible to call a function that provides me the current pixel values instead of the OSMD coordinates? I imagine that you only need to convert the current zoomlevel of the osmd graphic sheet to the html document page size. Is this mapping somehow available?

I would love to create overlay visualizations on top of the OSMD SVG to enrich music documents with additional information. For this it would be really helpful to have such a mapping.

**Comment by sschmidTU** [comment]
I know less about this than @bneumann who coded the SkyBottomLineCalculator, but you can examine the example of SkyBottomLineCalculator.calculateLines() to get your bounding box to SVG pixel position mapping.

Here are some relevant lines:
```js
// This magic number is an offset from the top image border so that
// elements above the staffline can be drawn correctly.
vsStaff.setY(vsStaff.y + 100);
```

```js
const imageData: any = ctx.getImageData(0, 0, width, height);
const rgbaLength: number = 4;
const measureArrayLength: number = Math.max(Math.ceil(measure.PositionAndShape.Size.width * this.mRules.SamplingUnit), 1);
const tmpSkyLine: number[] = new Array(measureArrayLength);
const tmpBottomLine: number[] = new Array(measureArrayLength);
for (let x: number = 0; x < width; x++) {
  // SkyLine
  for (let y: number = 0; y < height; y++) {
    const yOffset: number = y * width * rgbaLength;
    const bufIndex: number = yOffset + x * rgbaLength;
    const alpha: number = imageData.data[bufIndex + 3];
    if (alpha > 0) {
      tmpSkyLine[x] = y;
      break;
```

Maybe @bneumann can hand over the magic formula more simply.

Try it in the local demo:

![image](https://user-images.githubusercontent.com/33069673/55120997-9f864880-50f8-11e9-8670-4093f16c6172.png)

**Comment by matt-uib** [comment]
I didn't test it, but that's what i guess it shoud be:
In VexFlowMusicSheetDrawer you have:
```
     /**
     * Converts a distance from unit to pixel space.
     * @param unitDistance the distance in units
     * @returns {number} the distance in pixels
     */
    public calculatePixelDistance(unitDistance: number): number {
        return unitDistance * unitInPixels;
    }

     /**
     * Converts a point from unit to pixel space.
     * @param point
     * @returns {PointF2D}
     */
    protected applyScreenTransformation(point: PointF2D): PointF2D {
        return new PointF2D(point.x * unitInPixels, point.y * unitInPixels);
    }

    /**
     * Converts a rectangle from unit to pixel space.
     * @param rectangle
     * @returns {RectangleF2D}
     */
    protected applyScreenTransformationForRect(rectangle: RectangleF2D): RectangleF2D {
        return new RectangleF2D(rectangle.x * unitInPixels, rectangle.y * unitInPixels, rectangle.width * unitInPixels, rectangle.height * unitInPixels);
    }
```
And as we do the zooming via the backend (canvas..) the "zoom" variable is not included in this functions as we didn't need it for any calculations up to now.
So i guess you just need to write 3 new functions (e.g. transformToPixelSpace...) where you e.g. write:
return new PointF2D(point.x * unitInPixels * zoom, point.y * unitInPixels * zoom);
New functions are needed, as we need the current ones to render some geometries onto the backend, where i don't need the zoom to be included.

**Comment by sschmidTU** [comment]
By the way, there's a function `GraphicalMusicSheet.GetNearestNote()` that may be useful for finding notes by OSMD coordinates and implementing click events:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/772be0ddaf4759bac3ace744308afc393c8a71d5/src/MusicalScore/Graphical/GraphicalMusicSheet.ts#L475

**Comment by lkkmm** [comment]
@sschmidTU  hello guys, How do I call this function (GraphicalMusicSheet.GetNearestNote())?

**Comment by sschmidTU** [comment]
how about osmd.graphic.GetNearestNote(clickPosition, 5)? 5 means it looks in a circle around the position whose radius is the size of a staffline (5 lines). Any note further away will not be found.

Or are you asking how to get the clickPosition? There are answers for converting your screen coordinates to OSMD coordinates (or the other way round) in this issue.

**Comment by matt-uib** [comment]
Just for clarification of the units: 5 units is more than the staffline height. 
The staffline has 5 lines with 4 gaps in between and every gap is exactly 1 unit - that's actually how we define our unit.
So the staffline has a height of 4 units.
OSMD coordinates are based on this unit.

**Comment by lkkmm** [comment]
i am sorry about that i can't call up this function, console.log(osmd.graphic) i'm not find GetNearestNote

**Comment by ifredom** [comment]
> 对不起，我无法调用此功能，console.log（osmd.graphic）我找不到GetNearestNote

You should call osmd. Load(musicXML) first,then  will get osmd.graphi & osmd.sheet

**Comment by ifredom** [comment]
> i am sorry about that i can't call up this function, console.log(osmd.graphic) i'm not find GetNearestNote

You should call osmd. Load(musicXML) first,then will get osmd.graphi & osmd.sheet

**Comment by lkkmm** [comment]
> > i am sorry about that i can't call up this function, console.log(osmd.graphic) i'm not find GetNearestNote
> 
> You should call `osmd. Load(musicXML)` first,then will get (osmd.graphic) & (osmd.sheet)

yeah, i get(osmd.graphic) after osmd.render()

**Comment by lkkmm** [comment]
> > i am sorry about that i can't call up this function, console.log(osmd.graphic) i'm not find GetNearestNote
> 
> You should call `osmd.load(musicXML)` first,then will get (osmd.graphic) & (osmd.sheet)
> 
> ![image](https://user-images.githubusercontent.com/13759936/68260269-73ac4780-0077-11ea-926a-a61cbdbe8808.png)

but i also don't get getNearestNote

**Comment by sschmidTU** [comment]
you need to call osmd.graphic.GetNearestNote().
osmd.graphic is defined after load(), though you should probably should also call osmd.render() before GetNearestNote() will return anything meaningful.
if you can't call getNearestNote, there's something wrong with your setup. what version of osmd are you using? check with osmd.Version. you should have 0.7.1 at least.

**Comment by lkkmm** [comment]
> @lkkmm you need to call osmd.graphic.GetNearestNote().
> osmd.graphic is defined after load(), though you should probably should also call osmd.render() before GetNearestNote() will return anything meaningful.
> if you can't call getNearestNote, there's something wrong with your setup. what version of osmd are you using? check with osmd.Version. you should have 0.7.1 at least.

osmd.version is 0.7.1, i must inport GraphicalMusicSheet, then use GraphicalMusicSheet.prototype can find GetNearsNote, the source code the qusetion name is 'GetNearstNote', There's a 't' missing.
And i use osmd.graphic after osmd.render.
This picture is i console.log(osmd.graphic)
![image](https://user-images.githubusercontent.com/42935640/68441270-8f932300-0208-11ea-8878-e17081b50a59.png)

**Comment by sschmidTU** [comment]
that picture doesn't show any methods of osmd.graphic, so it's not helpful here.
Just try it in the online demo:
https://opensheetmusicdisplay.github.io/demo/
![image](https://user-images.githubusercontent.com/33069673/68472344-93cb3a80-0220-11ea-85c8-cd7101d2ecb4.png)
this is from Chrome Console.

**Comment by lkkmm** [comment]
> that picture doesn't show any methods of osmd.graphic, so it's not helpful here.
> Just try it in the online demo:
> https://opensheetmusicdisplay.github.io/demo/
> ![image](https://user-images.githubusercontent.com/33069673/68472344-93cb3a80-0220-11ea-85c8-cd7101d2ecb4.png)
> this is from Chrome Console.
I found this function(GetNearestNote, getClickedObject) in osmd.graphic.prototype, and then return  musicPages not  note. So I wonder if this is accurate?


![image](https://user-images.githubusercontent.com/42935640/68520505-4360e500-02d3-11ea-8ad9-591f415616ca.png)

**Comment by lkkmm** [comment]
I found this function(GetNearestNote, getClickedObject) in osmd.graphic.prototype, and then return musicPages not note. So I wonder if this is accurate?
![Uploading image.png…]()

**Comment by sschmidTU** [comment]
GetNearestNote and getClickedObject are two different functions in GraphicalMusicSheet. You can try either. but this specific function you describe that returns musicPages is not a function in OSMD. I don't know where you are searching, in the chrome console or the OSMD npm package you will find all OSMD functions as i described above.
By the way, your screenshot did not upload correctly.

**Comment by lkkmm** [comment]
Debugging osmd in the chorme  console, output undefined.But yesterday I solved the problem that bothered me. Thank you very much for creating this open source project and thank you for your reply.

**Comment by lkkmm** [comment]
> GetNearestNote and getClickedObject are two different functions in GraphicalMusicSheet. You can try either. but this specific function you describe that returns musicPages is not a function in OSMD. I don't know where you are searching, in the chrome console or the OSMD npm package you will find all OSMD functions as i described above.
> By the way, your screenshot did not upload correctly.

Debugging osmd in the console, output undefined, may be my configuration problem.But yesterday I solved the problem that bothered me. Thank you very much for creating this open source project and thank you for your reply.

**Comment by philipp-siegmantel** [comment]
For future reference: In order to convert a osmd coordinate to a screen coordinate you multiply the x and y values by opensheetmusicdisplay.unitInPixels. To go the other way around you divide. That is, if you use the canvas backend. If you use the SVG backend, you get SVG viewbox coordinates back instead of screen ones. Converting these to screen coordinates is described [here](https://github.com/0xfe/vexflow/issues/712#issuecomment-546633821)

**Comment by sschmidTU** [comment]
These methods are now integrated in osmd:
```js
osmd.graphic.svgToOsmd({x: number, y: number})
osmd.graphic.domToSvg({x: number, y: number})
osmd.graphic.svgToDom({x: number, y: number})
```
As phillip said, from osmd to svg, it's essentially `* 10` (VexFlowMusicSheetDrawer.unitInPixels).
