### ISSUE TITLE
Display Multi-Measure rests

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#506]
Added to Vexflow in November 2018 ([PR 671](https://github.com/0xfe/vexflow/pull/671)).
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-multiple-rest.htm

Currently, we render these measure for measure, because they are also still given like that in XML.
The starting multi-measure rest bar just has an added attribute:
```xml
    <measure number="6" width="0.00">
      <attributes>
        <measure-style>
          <multiple-rest>4</multiple-rest>
          </measure-style>
        </attributes>
      <note>
        <rest/>
        <duration>4</duration>
        <voice>1</voice>
      </note>
    </measure>
```

- [ ] TODO: Add Vexflow.MultiMeasureRest to type definitions

Sample:
[Multi-Measure-Rest_sample.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3015639/Multi-Measure-Rest_sample.musicxml.zip)

Musescore Rendering:
![image](https://user-images.githubusercontent.com/33069673/55118659-5bdb1100-50ef-11e9-9fe6-8fdaeedaedf1.png)

OSMD 0.7 Rendering:
![image](https://user-images.githubusercontent.com/33069673/55118676-6dbcb400-50ef-11e9-9286-07664f18c543.png)

This will have a few small challenges like needing to skip creating GraphicalMeasures and incrementing measure number count for measureNumberLabel, but the Vexflow part should be easy.

**Comment by sschmidTU** [comment]
Done.

Added new OSMD Function Test - Multiple Rest Measures to the demo.

![image](https://user-images.githubusercontent.com/33069673/86180359-40e62080-bb2c-11ea-8708-10efe20fc413.png)

**Comment by sschmidTU** [comment]
I suppose the measure number labels need a change now,
they should be drawn after a multi rest measure if the interval between labels (e.g. every 3 measures) fell into the multi rest measure.

**Comment by matt-uib** [comment]
@sschmidTU Yes makes sense to adapt the numbering, but is it really such a coincidence, that no numbering falls on a rendered measure?
Actually measure 9 is rendered in your image for example, but no number is shown - seems some other problem here...

**Comment by sschmidTU** [comment]
Fixed the measure number label generation.
The problem was that it checked for the measure in exactly that interval (e.g. in 2 measures), which can now be inside a multirest.
Now, it checks whether the measure number is greater or equals the previous label plus the interval.
![image](https://user-images.githubusercontent.com/33069673/86270159-16977000-bbcb-11ea-969a-c58ccf45ddcd.png)

**Comment by MilesMorel** [comment]
This is awesome! Very nice!!

**Comment by sschmidTU** [comment]
By the way, you can disable multiple rest measures by setting:
```js
osmd.EngravingRules.RenderMultipleRestMeasures = false;
```
This will render all rest measures individually.

**Comment by sschmidTU** [comment]
Improved bounding boxes for StaffEntries + VoiceEntries + GraphicalNotes in multi-measure rests:
showing StaffEntry bounding boxes:
<img width="760" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/d65c6d37-19c6-4c7d-8cec-fe926978ea58">

this helps click detection, because apparently a bounding box with width 0 is not detected as an overlap.

Before, it was like this:
<img width="374" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/c41a7ddc-03c2-4b45-8c08-de6d6d618756">

(use the Show bounding box button in the local demo)
<img width="152" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/b3da5792-2040-4045-bad9-31c003867015">

**Comment by sschmidTU** [comment]
Slightly reduced the bbox, moved the lower edge of the rectangle upwards by 1.
<img width="71" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/9f4ffe9b-d120-49cb-8fd8-3edb1ae269d5">

Couldn't move the upper edge downwards by 1 somehow.
