### ISSUE TITLE
Color Themes e.g. White Notes on Black Background

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#507]
Should be pretty easy, there's a Vexflow demo with about 20 lines total.
https://github.com/0xfe/vexflow/issues/674
http://jsfiddle.net/9cd3s0v2/4/

![image](https://user-images.githubusercontent.com/2474537/48243569-ea533c80-e445-11e8-8f18-652faf53234b.png)

This should be an OSMDOption that accepts a background color and stroke color.

**Comment by sschmidTU** [comment]
Fixed in #1125.
![image](https://user-images.githubusercontent.com/33069673/149658477-8ea0dc93-c3b7-4de2-9064-d4812c7442bc.png)

**Comment by rvilarl** [comment]
Perhaps we should port the dark mode to VexFlow.

**Comment by sschmidTU** [comment]
@rvilarl Yes, that would be nice, though basically it's already possible, you only have to set the strokeStyle/fillStyle once for the context before drawing everything.
It would also be nice to be able to set a fillStlye/strokeStyle for key signature, time signature, clefs, slurs, ties, etc., and also for them to have SVG classes and ids (e.g. `<path class="vf-clef">`).
That would allow instant recoloring without re-rendering, via SVG.

This is what it looks like if I don't set the color of the context (to red) before drawing everything:
![image](https://user-images.githubusercontent.com/33069673/149679955-1208cab4-400f-433a-830b-02936a5c4871.png)
