### ISSUE TITLE
Example in wiki is wrong

### ISSUE THREAD

**Issue by cliffckerr** [opensheetmusicdisplay/opensheetmusicdisplay#508]
On the "Getting started" page (https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Getting-Started), the example

```
var container = document.getElementById("div-container");
var osmd = new OpenSheetMusicDisplay(container);
```

should actually be

```
var container = document.getElementById("div-container");
var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay(container);
```

**Comment by sschmidTU** [comment]
You're right. It was already correct two lines above that.
Fixed it, thanks for the hint!

**Comment by cliffckerr** [comment]
Yes, I forgot to mention that -- if it hadn't been correct just above, I probably wouldn't have figured it out :) Thanks for fixing so quickly!!
