### ISSUE TITLE
Wrong measure width with whole rests at top of the system

### ISSUE THREAD

**Issue by chrissbarnett** [opensheetmusicdisplay/opensheetmusicdisplay#510]
I'm having an issue where measure widths are too small to fit all of the notes if there is a whole rest at the top of the system.

Example:
![Screen Shot 2019-04-04 at 3 14 24 PM](https://user-images.githubusercontent.com/1591807/55582596-ea522280-56ed-11e9-8076-63b61e0ec02c.png)

If I change the order of the staves or fill the top staff with rests of different values, the problem goes away:
![Screen Shot 2019-04-04 at 3 16 05 PM](https://user-images.githubusercontent.com/1591807/55582664-1077c280-56ee-11e9-9cc6-971543fbeb0e.png)

or:
![Screen Shot 2019-04-04 at 3 19 52 PM](https://user-images.githubusercontent.com/1591807/55582687-18cffd80-56ee-11e9-9a73-a8de76bbd717.png)

This particular example is in 12/8 time.

I see the same issue in both versions 0.6.8 and 0.7.0.

**Comment by chrissbarnett** [comment]
Adding music xml sample.
[measure_issue.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3045352/measure_issue.xml.zip)

**Comment by bneumann** [comment]
Oh dear. I have a clue why this is happening. I think we are calculating the width based on the first measure in the stave. Or basically vexflow does at and we apply it. 
There also was something about whole rests not being calculated correctly. Maybe @sschmidTU knows more

**Comment by matt-uib** [comment]
Really strange, as our logic should be to first find the minimum width needed for all staves of one measure and then take the max from that for all. Or do we feed everything to vexflow and let the formatter do this job?
Then there is something wrong in vexflow and we have to format every stave separately and find the required width as the max of all min widths.

**Comment by sschmidTU** [comment]
This was fixed a while ago.
<img width="259" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/b1949005-dc2e-4937-89d4-ad6d31013bd8">
