### ISSUE TITLE
Second voice not shown using backup

### ISSUE THREAD

**Issue by YotaVGA** [opensheetmusicdisplay/opensheetmusicdisplay#511]
I'm using OSMD 5.1 on an android WebView.
I'm generating a musicxml file programmatically, and this is one example of xml generated (it is just prettified to be easier to read):
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
	<part-list>
		<score-part id="P1">
			<part-name>Music</part-name>
		</score-part>
	</part-list>
	<part id="P1">
		<measure number="1">
			<attributes>
				<divisions>16</divisions>
				<key>
					<fifths>0</fifths>
				</key>
				<time>
					<beats>4</beats>
					<beat-type>4</beat-type>
				</time>
				<clef>
					<sign>G</sign>
					<line>2</line>
				</clef>
			</attributes>
			<note>
				<pitch>
					<step>E</step>
					<alter>0</alter>
					<octave>4</octave>
				</pitch>
				<duration>16</duration>
				<voice>1</voice>
				<notations/>
			</note>
			<backup>16</backup>
			<note>
				<pitch>
					<step>C</step>
					<alter>0</alter>
					<octave>4</octave>
				</pitch>
				<duration>16</duration>
				<voice>2</voice>
				<notations/>
			</note>
		</measure>
	</part>
</score-partwise>
```
The problem is that the second note, with the second voice, is not shown at all. If I remove the backup instruction it works as expected, the second note is shown, but (as expected) it comes after the first one.
Am I generating a wrong xml or is there a bug in OSMD?

**Comment by YotaVGA** [comment]
Sorry, it was my mistake, I don't write "duration" tag inside backup

**Comment by sschmidTU** [comment]
No problem! I recommend using OSMD 0.7 though, since it has quite a few improvements to 0.5.1, and there is no downside except maybe slightly different constructor options.
