### ISSUE TITLE
Follow the cursor (Auto Scroll) Feature

### ISSUE THREAD

**Issue by ronnycsharp** [opensheetmusicdisplay/opensheetmusicdisplay#512]
Hi,

is there any way to follow a cursor inside a music sheet?
I didn't see anything like this. The document should be scrolled automatically.
If not, I've to implement it. 

Regards
Ronny

**Comment by sschmidTU** [comment]
No, unfortunately we don't have that feature yet, would be great to have.
If you can do that and submit a Pull Request so that we can all benefit, that would be highly appreciated!

**Comment by ronnycsharp** [comment]
Ok, I will try to implement it.

**Comment by sschmidTU** [comment]
There is now a followCursor option implemented in #532.
