### ISSUE TITLE
drawPartNames: false still results in staff with x offset the same as if it were drawing the part names

### ISSUE THREAD

**Issue by jnpdx** [opensheetmusicdisplay/opensheetmusicdisplay#515]
Given a staff with a rather long part name (such as "Bb Clarinet", for example), when the option `drawPartNames: false` is passed to OpenSheetMusicDisplay, the part name is not displayed, but the staff is still equally offset in the x axis as if to give room to the staff name that isn't being displayed.

I tried looking into the source to try to figure out where the layout is done for the initial stave/measure, but I couldn't find it.

Can anyone point me in the right direction?

**Comment by jnpdx** [comment]
Can anyone point me in a direction to where the staff layout work is done?

**Comment by sschmidTU** [comment]
Hi, sorry for the late reply!
In exchange, i fixed the issue myself.

DrawPartNames = true now does not leave any more unnecessary x-spacing to the left of the first StaffLine.
![image](https://user-images.githubusercontent.com/33069673/57323019-36392280-7105-11e9-9c41-b19340d4aa8c.png)

You can see the relevant code spots in my commit 595f8ab5a28a951289da7545342a4430f55d4552.

**Comment by jnpdx** [comment]
Wow -- fantastic!  Thanks for the pointer to the commit, too, so that I can start to learn how some of this works under the hood.
