### ISSUE TITLE
opensheetmusicdisplay-feature-Tabs

### ISSUE THREAD

**Issue by 279259621** [opensheetmusicdisplay/opensheetmusicdisplay#517]
opensheetmusicdisplay-feature-Tabs
Cursor Wrong position display,The cursor position of the call to moveToNext is not correct

**Comment by bneumann** [comment]
Do you mean the feature branch? That one is quite stale at the moment

**Comment by 279259621** [comment]
Yes! We need to draw the guitar score, Can you fix bugs and update feature branches,thanks

**Comment by sschmidTU** [comment]
Sorry, but we do not have the resources for that right now. We're a community of volunteer developers with many different goals, projects and desired features, and we can't just start working on what someone needs right now.
Tabs would be a great feature for OSMD, but not everyone plays the guitar.

Regarding the Cursor position, try merging the recent changes to Cursor.ts to that branch.

If you want to render tabs, i suggest you use VexTab for now, or Vexflow directly.
http://vexflow.com/vextab/

**Comment by sschmidTU** [comment]
What are you trying to build, by the way?

**Comment by 279259621** [comment]
Parse musicxml to draw guitar score and play music. The cursor can move with the progress of the music

**Comment by 279259621** [comment]
Do you have any good Suggestions

**Comment by sschmidTU** [comment]
If you want to parse MusicXML and have a cursor, your best bet probably is reviving this branch, merging it with develop, and getting it to work.
Otherwise you can try using Vextab alone.
Take a look at this, there are already some working playback demos (without tabs):
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/258#issuecomment-406620322

**Comment by bneumann** [comment]
The tabs branch is far from finished. I really want to see it in our develop branch but as @sschmidTU said: ain't nodoby got time for that.

**Comment by matt-uib** [comment]
please see #126 and try the new branch.
And also please comment there.
