### ISSUE TITLE
Support for breath marks

### ISSUE THREAD

**Issue by jnpdx** [opensheetmusicdisplay/opensheetmusicdisplay#527]
Breath marks don't seem to get displayed.  Is there a way to enable them or is this a feature that needs to get added?
[Clarinet - 3 - Faster And Stronger.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3208375/Clarinet.-.3.-.Faster.And.Stronger.xml.zip)

**Comment by bneumann** [comment]
Oh darn, sorry no one answered so far. The whole team is quite busy at the moment.
AFAIK breath marks are currently not implemented but maybe @matt-uib knows more. Sometimes xml elements are already parsed and only need to be rendered

**Comment by sschmidTU** [comment]
Likewise, somehow I missed this issue.
@jnpdx breath marks are unfortunately not yet supported in Vexflow, and we try to let Vexflow do most of the rendering, though we do already do some extra rendering like for slurs.
We could of course add a breath mark rendering function in OSMD, though of course it would be nicer to implement it in Vexflow first so it's well integrated and Vexflow users benefit too.

**Comment by sschmidTU** [comment]
someone asked about breath mark support in Vexflow once:
https://www.bountysource.com/issues/45858561-er-breath-mark

**Comment by c4xx4c** [comment]
fyi @sschmidTU,

there is an example for Vexflow here: https://github.com/0xfe/vexflow/issues/740
which uses a TextNote plus glyph: 'breath'

maybe worth to re-consider if it's doable.

**Comment by sschmidTU** [comment]
@c4xx4c yes, we are actually already considering implementing breath marks soon!

**Comment by sschmidTU** [comment]
Implemented in #1285 :)

<img width="157" alt="image" src="https://user-images.githubusercontent.com/33069673/207125713-4253c499-edbd-4439-b284-a83f8bf1ce4a.png">

`test_breath_mark.musicxml`

New EngravingRule `BreathMarkDistance`: % distance to next note or end of staff. default 0.8 = 80% distance towards next note/staff.

Will be released shortly in OSMD 1.6.2.
