### ISSUE TITLE
AutoFit to ViewSize

### ISSUE THREAD

**Issue by DrWenz** [opensheetmusicdisplay/opensheetmusicdisplay#533]
Is it possible to render the musicxml to fit in the size of the canvas ?

**Comment by sschmidTU** [comment]
Have you tried `osmd.setOptions({autoResize: true})`?
autoResize will be true automatically though if you use an empty constructor.
It will only be false if you use constructor options, but don't set autoResize to true.

**Comment by sschmidTU** [comment]
Actually autoResize will be true even if undefined, so it should be true in your case.
Can you give an example and screenshot where OSMD doesn't fill the canvas size?
Some layouts may cause issues for our autoResize method, like FlexBox, see #331.
