### ISSUE TITLE
A question about measure width and the white space between notes

### ISSUE THREAD

**Issue by DavoWU** [opensheetmusicdisplay/opensheetmusicdisplay#534]
@sschmidTU Hi there, I am currently doing the rendering measures, I need to render BPM time (shown as a red bar on the top of each node),  so the player can exactly know how long should he press the key on the piano.  

I found that osmd or vexflow will have an accurate white space proportion in each one measure. But if we look at the whole measures, I found that osmd or vexflow will render less white space between each node if there is fewer nodes in one of measure, and will extend measure length if there are more nodes (as for example in measure 2, 3, 4). 

![Screen Shot 2019-06-17 at 15 10 29](https://user-images.githubusercontent.com/23088138/59588585-88189380-911a-11e9-8739-9bd9bec31b52.png)

it makes me feel hard to show BPM time, because the BPM time base on space distance in between (for example, 1/2 node will be 50px distance in between, 1/4 node will be 25px distance in between).

aim to solve this problem, I have an idea is to find the largest measure width, and then modify all the other measures in this measure width. so that make sure the whole measure system has the right distance proportion.

so my question is :
1. if I want to adjust measure width with a fixed number, where should I start? or which function I should change?
2. if each measure support to be changed width individually, then will OSMD render nodes in right proportion automatically according to the new measure width? 

Really thanks for helping me

**Comment by sschmidTU** [comment]
What do you mean with showing BPM time based on space distance?
Do you want to show the beat number above a note?
In that case, you can get the note's position on the screen and render it above it.
For example GraphicalNote.PositionAndShape.AbsolutePosition.
Also, with the SkyBottomLineCalculator, you can calculate the maximum y position along the measure that OSMD draws things at, so you can always draw above everything else.
So i don't think you need to change the measure widths.

If you still want to change the measure widths, look at VexflowMusicSheetCalculator.calculateMeasureXLayout.
Specifically, the width is set here, i think:
```js
vexflowMeasure.formatVoices(minStaffEntriesWidth * unitInPixels);
```
