### ISSUE TITLE
Support principal-voice element

### ISSUE THREAD

**Issue by samuelbradshaw** [opensheetmusicdisplay/opensheetmusicdisplay#536]
MusicXML has a `<principal-voice>` element which allows you to put a start bracket or end bracket above a note, to mark sections of a song. This is used for [Hauptstimme and Nebenstimme](https://en.wikipedia.org/wiki/Hauptstimme), but in my case I'd like to use these brackets for marking piano introductions, as is common for hymns in various hymnals (see https://github.com/w3c/musicxml/issues/275).

Here's the documentation for principal-voice:
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-principal-voice.htm

Here's a MusicXML code example for the start bracket:
```
      <direction placement="above">
        <direction-type>
          <principal-voice type="start" symbol="plain"/>
        </direction-type>
      </direction>
```
And the end bracket:
```
      <direction placement="above">
        <direction-type>
          <principal-voice type="stop" symbol="plain" />
        </direction-type>
      </direction>
```

(In the MusicXML file, the `<direction>` element is placed immediately before the `<note>` where you want the bracket to appear.)

Finally, here's an example of what I'd expect the brackets to look like:
![54478498-67b60180-47d8-11e9-989b-e9151ea09fbe](https://user-images.githubusercontent.com/7323052/60059748-004b0000-96ab-11e9-86d5-f2552bb085e8.png)

**Comment by sschmidTU** [comment]
This is a rare element that I've personally never seen in sheet music, and Vexflow does not support it, so unfortunately it's currently not feasible to implement in OSMD.
Once this is added to Vexflow, we can add it to OSMD too.
Thanks for pointing it out though, I was not aware of it.
