### ISSUE TITLE
Some slurs are not included

### ISSUE THREAD

**Issue by misterallx** [opensheetmusicdisplay/opensheetmusicdisplay#539]
Hello all!

Wanted to direct your attention to this issue that I spotted a while back. In some cases, certain slurs are not included. The image shows the original score and then the import on OSMD. Please see the area circled in Blue. There should be one Tie between the two As, and a slur from A to the high E.
The orange and green circles are additional things I thought would be good to show.
Thank you!

![sample 1](https://user-images.githubusercontent.com/33357194/60301334-194bef00-98ff-11e9-903c-02cb9876ec8e.png)

**Comment by sschmidTU** [comment]
Should be fixed in OSMD 1.4.3. Otherwise please supply a musicxml sample.
