### ISSUE TITLE
how to add additional notes and remove certain notes

### ISSUE THREAD

**Issue by suziW** [opensheetmusicdisplay/opensheetmusicdisplay#540]
i am working on a project which recognizing music sound(mostly played by people with piano). now i want to compare the recognized result with the origin sheet. so there will be some additional notes which don't belong to origin sheet and i want to show it. can osmd do that? and how?

**Comment by bneumann** [comment]
Hi,
Well you could do this by either manipulating the xml itself before passing it to the renderer. Or you write a hook after the parser (we don't have that yet unfortunately) where you can change the score object (and single notes) before it is passed to the drawer.

But be aware OSMD does not reflect changes in the internal data to the XML. So it's only one way.

**Comment by sschmidTU** [comment]
as commented in #482, for dynamic rendering we would need a re-render system in OSMD that can re-render parts of the score, probably one measure at a time, because we'd have to "paint over" notes with transparent color, leaving "holes".

**Comment by suziW** [comment]
> Hi,
> Well you could do this by either manipulating the xml itself before passing it to the renderer. Or you write a hook after the parser (we don't have that yet unfortunately) where you can change the score object (and single notes) before it is passed to the drawer.
> 
> But be aware OSMD does not reflect changes in the internal data to the XML. So it's only one way.
