### ISSUE TITLE
How to use Chinese score?

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#547]
Is there any method to use chinese piano scores ?

**Comment by sschmidTU** [comment]
What do you mean? You can use chinese characters in lyrics and title if that's what you're asking.
You just need to have characters in the MusicXML file that you load.
![image](https://user-images.githubusercontent.com/33069673/61374113-d5179300-a89b-11e9-8467-7f032fb511fb.png)
https://musescore.com/jonasblumenberg/scores/1428531

**Comment by sschmidTU** [comment]
Can you give me an example of such a score?

**Comment by JanvyHung** [comment]
Thank U very much!

--------------原始邮件--------------
发件人："Simon "<notifications@github.com>;
发送时间：2019年7月17日(星期三) 晚上8:05
收件人："opensheetmusicdisplay/opensheetmusicdisplay" <opensheetmusicdisplay@noreply.github.com>;
抄送："JanvyHung "<tiansheng.huang@musetk.com>;"Author "<author@noreply.github.com>;
主题：Re: [opensheetmusicdisplay/opensheetmusicdisplay] How to use Chinese score? (#547)
-----------------------------------

 
What do you mean? You can use chinese characters in lyrics and title if that's what you're asking.
 You just need to have characters in the MusicXML file that you load.
 
 https://musescore.com/jonasblumenberg/scores/1428531

**Comment by JanvyHung** [comment]
Can I edit  English titles with Chinese charactors just in OSMD ? I mean I may need to change En. to Ch. title.

--------------原始邮件--------------
发件人："Simon "<notifications@github.com>;
发送时间：2019年7月17日(星期三) 晚上8:05
收件人："opensheetmusicdisplay/opensheetmusicdisplay" <opensheetmusicdisplay@noreply.github.com>;
抄送："JanvyHung "<tiansheng.huang@musetk.com>;"Author "<author@noreply.github.com>;
主题：Re: [opensheetmusicdisplay/opensheetmusicdisplay] How to use Chinese score? (#547)
-----------------------------------

 
What do you mean? You can use chinese characters in lyrics and title if that's what you're asking.
 You just need to have characters in the MusicXML file that you load.
 
 https://musescore.com/jonasblumenberg/scores/1428531

**Comment by sschmidTU** [comment]
no, you should do that in the MusicXML file. You can use MuseScore for that, for example.

**Comment by sschmidTU** [comment]
Can you upload a sample musicxml file? (you need to put it into a .zip for github)
without a sample, i can't tell you how to solve your problem. As you can see above, another score with chinese characters seems to work well.
