### ISSUE TITLE
can u provide and example that use in vue.js?

### ISSUE THREAD

**Issue by kongwutw** [opensheetmusicdisplay/opensheetmusicdisplay#554]
can u provide and example that use in vue.js?

**Comment by praisethemoon** [comment]
Hello, I do not know anything about vuejs, but if it supports refs as react you can check this repo: [https://github.com/opensheetmusicdisplay/react-opensheetmusicdisplay](https://github.com/opensheetmusicdisplay/react-opensheetmusicdisplay), let me know how it goes!

**Comment by bneumann** [comment]
Hi @kongwutw, yeah vue is on my long list of to dos. I don't have the time currently to hack a demo like the react example that @praisethemoon mentioned.
If you manage to get something running it would awesome if you share it here.

**Comment by sschmidTU** [comment]
closed for now, if anyone gets a vuejs example running or has other related questions, feel free to comment.

**Comment by sschmidTU** [comment]
@nicolas-cardona That seems fantastic, thank you very much! Great to have a vue example project.
Maybe you want to add a screenshot to the readme? I know there isn't much UI and that's not the focus, which is the vue integration, but it might be nice.
I'll put one here:
<img width="787" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/24288667-9043-41cd-8987-f7882e9487d1">
