### ISSUE TITLE
Trouble on Getting Started

### ISSUE THREAD

**Issue by dlujan** [opensheetmusicdisplay/opensheetmusicdisplay#555]
I'm having trouble getting started. I'm not sure if I'm supposed to make a new js file? I'll show what I have right now. But nothing is being displayed when I open index.html in the browser. I know I'm not doing it right but the instructions aren't clear to me.

// This is 'index.html' ... btw I put 'opensheetmusicdisplay.min.js' in the same directory as 
// 'index.html'

!DOCTYPE html>
html>
head>
    title>Page Title</title>
    link rel="canonical" href="https://opensheetmusicdisplay.github.io//demo/">
    script src="opensheetmusicdisplay.min.js" type="text/javascript"></script>
/head>
body>
    div id="div-container">
    /div>
    script src="script.js"></script>
/body>
/html>

// This is 'script.js
var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("div-container");
osmd.load("http://www.example.org/my-score.xml");
container.style.width = "720px";
osmd.render();

//////////////////////////////////////////////////////////////
Here is my directory organization:
>node_modules
index.html
opensheetmusicdisplay.min.js (moved from node modules)
script.js
package-lock.json

Please help, I really want to use this! D:

**Comment by dlujan** [comment]
The html is displaying weird in my post for some reason.
This is in the head:
<link rel="canonical" href="https://opensheetmusicdisplay.github.io//demo/">
<script src="opensheetmusicdisplay.min.js" type="text/javascript"></script>
This is in the body:
<div id="div-container">
</div>
<script src="script.js"></script>

**Comment by bneumann** [comment]
Hi there, the line ```osmd.load("http://www.example.org/my-score.xml");``` looks like you didn't load a real sheet.

Can you post the error or warning that osmd prints in the browser console?

**Comment by dlujan** [comment]
Hi, thanks for responding. This is the error I get:
 opensheetmusicdisplay.min.js:15 Access to XMLHttpRequest at 
 'file:///Users/daniellujan/Desktop/OSMDTest/xmls/Score1.xml' from origin 'null' has been blocked 
 by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, 
 chrome, chrome-extension, https.
 (anonymous) @ opensheetmusicdisplay.min.js:15
 (anonymous) @ opensheetmusicdisplay.min.js:15
 e @ opensheetmusicdisplay.min.js:15
 t.ajax @ opensheetmusicdisplay.min.js:15
 t.load @ opensheetmusicdisplay.min.js:15
 (anonymous) @ script.js:5
 opensheetmusicdisplay.min.js:15 Uncaught Error: OpenSheetMusicDisplay: Before rendering a 
 music sheet, please load a MusicXML file
     at t.render (opensheetmusicdisplay.min.js:15)
     at script.js:8

Does this mean I have to put 'opensheetmusicdisplay.min.js' inside 'osmd.render();?
I also read about the CORS thing. So I tried setting up a simple Express server but then it doesn't recognize 'document' in 'var container = document.getElementById("div-container");'

**Comment by samuelbradshaw** [comment]
I ran into the XMLHttpRequest CORS problem the other day. Have you tried pointing to an external MusicXML file to test? Here's an example:
https://www.churchofjesuschrist.org/music/library/childrens-songbook/youve-had-a-birthday-round/xml.xml

**Comment by samuelbradshaw** [comment]
See also:
https://stackoverflow.com/questions/32126003/node-js-document-is-not-defined

**Comment by dlujan** [comment]
Unfortunately I still get: 
Access to XMLHttpRequest at 'https://www.churchofjesuschrist.org/music/library/childrens-songbook/youve-had-a-birthday-round/xml.xml' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

And this error still which I don't understand:
Before rendering a music sheet, please load a MusicXML file
    at t.render (opensheetmusicdisplay.min.js:15)
    at script.js:8
I try osmd.render();
and
osmd.render('opensheetmusicdisplay.min.js');
and neither option works. ???
I apologize if this is supposed to be simple.

**Comment by samuelbradshaw** [comment]
Sorry, I should have checked if that page had the `Access-Control-Allow-Origin` header. I'm having trouble finding other examples of MusicXML files hosted online. But it sounds like your solution to spin up a local server might have gotten around that error for your local file.

Unfortunately, I'm not very experienced in JavaScript/Node yet either, so hopefully someone else can chime in.

**Comment by dlujan** [comment]
Thanks for the help anyway! As long as the OSMD stuff is right I can focus on making the server work.

**Comment by sschmidTU** [comment]
Have you looked at [Getting Started](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Getting-Started) in the Wiki, and specifically the [Plain Javascript/HTML-Repository](https://github.com/opensheetmusicdisplay/RawJavascript-usage-example) and its Readme? It explains how to setup OSMD without a module bundler like Webpack (which is recommended), and how to avoid CORS issues.

**Comment by sschmidTU** [comment]
If you check out that repository and follow the Readme, you'll have a working basic OSMD setup.

**Comment by webbruin** [comment]
How should the entire environment be started? How to use the PlaybackSettings class?

**Comment by sschmidTU** [comment]
@webbruin I don't know what you mean. The plain javascript example can be started like described in the readme: start the file server, then open index.html
the OSMD demo from this repository is started with npm start.
In your own code, you simply need to import OSMD and call osmd.load, osmd.render and so on.
PlaybackSettings can't be used at all yet because there's no playback yet in OSMD.

**Comment by webbruin** [comment]
Thanks for your rapid feedback.
I could like to clarify "playback", I mean I can click on score and it can play music according to where I point, just like midi do.
Actually I want to display notation and play it on my website based on musicxml files. for example:
https://www.practicebird.com/
opensheetsdisplay can perfectlly display musicxml noatation on web, but I'm not sure whether it can also play it?
Many thanks

**Comment by webbruin** [comment]
@sschmidTU 
Thanks for your rapid feedback.
I could like to clarify "playback", I mean I can click on score and it can play music according to where I point, just like midi do.
Actually I want to display notation and play it on my website based on musicxml files. for example:
https://www.practicebird.com/
opensheetsdisplay can perfectlly display musicxml noatation on web, but I'm not sure whether it can also play it?
Many thanks

**Comment by sschmidTU** [comment]
@webbruin as i said, there is no audio playback yet in OSMD.
Some people have made their own playback for OSMD, see examples here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/258#issuecomment-406620322

There is also some new help on using timestamps to play the right note at the right time here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/480#issuecomment-527601410

**Comment by ifredom** [comment]
> 不幸的是，我仍然得到：从源“ null”
> 访问“ https://www.churchofjesuschrist.org/music/library/childrens-songbook/youve-had-a-birthday-round/xml.xml的XMLHttpRequest 已被阻止通过CORS策略：请求的资源上不存在“ Access-Control-Allow-Origin”标头。
> 
> 而且这个错误仍然是我不理解的：
> 在渲染乐谱之前，请 在script.js：8的
> t.render（opensheetmusicdisplay.min.js：15）加载MusicXML文件， 我尝试osmd.render（）;。 和 osmd.render（'opensheetmusicdisplay.min.js'）; 而且这两个选项都不起作用。??? 如果这很简单，我深表歉意。



> Sorry, I should have checked if that page had the `Access-Control-Allow-Origin` header. I'm having trouble finding other examples of MusicXML files hosted online. But it sounds like your solution to spin up a local server might have gotten around that error for your local file.
> 
> Unfortunately, I'm not very experienced in JavaScript/Node yet either, so hopefully someone else can chime in.

It is recommended that you start a local static server without CORS problems, and it is simple.
