### ISSUE TITLE
change cursor color

### ISSUE THREAD

**Issue by DavoWU** [opensheetmusicdisplay/opensheetmusicdisplay#556]
hi there,  I am trying to change the default cursor colour (green), to grey. I noticed that the original OSMD transfer png to base64 formate, so I thought I could use my base64 instead of the original base64(green one).
here is my code 
```
let canvas = document.createElement("canvas");
let dataURL = canvas.toDataURL("img/cursor.png");
dataURL.replace(/^data:image\/(png|jpg);base64,/, "");
this.osmd.cursor.cursorElement.src = dataURL;
this.osmd.cursor.cursorElement.currentSrc = dataURL;
````

but there is nothing change happen
can anyone tell me where i did wrong ? thanks a lot :)

**Comment by sschmidTU** [comment]
@DavoWU could you share your solution? maybe others will find it useful in the future.
I'm guessing you either corrected the replace or replaced the cursor image file.

**Comment by praisethemoon** [comment]
I personally use `this.osmd.cursor.updateStyle(3 * 10.0 * this.osmd.zoom, '#41e9f2')`

**Comment by praisethemoon** [comment]
I might submit a PR on how to correctly handle it, as the style will be dropped if you re-render OSMD
