### ISSUE TITLE
How to get bpm?

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#557]
If bpm is displayed in the score, how to get it in the program？Also, is it possible to get a document for all available elements of OSMD?

**Comment by praisethemoon** [comment]
Hello, this is currently a feature that I am working on, basically, the BPM (aka tempo) is indeed rendered, and you can get its textual value. However, the code that extract the true BPM value is commented, IDK. I am currently working on implementing this, so stay tuned for my PR once I get it done. I will because I need it as well ;)

**Comment by praisethemoon** [comment]
Guess what, I think I just found out how :D @sschmidTU , I am thinking of creating a new attribute in `SourceMeasure` called `tempoInBPM`, do you have any better ideas? If there is a present BPM value, the current measure will be assigned that one, if not, it will inherit its previous measure's BPM.

**Comment by sschmidTU** [comment]
sounds good! it's not graphical but measure data, so SourceMeasure seems like the right place.
I mean, in theory the tempo could change in the middle of the measure, and you could have a tempo per StaffEntry or something... but maybe not something to worry about right now.

**Comment by praisethemoon** [comment]
It is done, PR in few mins

**Comment by JanvyHung** [comment]
Good job! Thank you very much! Here are some questions.  1. What the differeces between defaultStartTempoInBpm and userStartTempoInBPM?  2. How do you get the bpm from the scores without bpm ,but have some musical terms like "poco moto"?

--------------原始邮件--------------
发件人："Soulaymen Chouri "<notifications@github.com>;
发送时间：2019年8月10日(星期六) 上午8:48
收件人："opensheetmusicdisplay/opensheetmusicdisplay" <opensheetmusicdisplay@noreply.github.com>;
抄送："JanvyHung "<tiansheng.huang@musetk.com>;"Author "<author@noreply.github.com>;
主题：Re: [opensheetmusicdisplay/opensheetmusicdisplay] How to get bpm? (#557)
-----------------------------------

 
It is done, PR in few mins

**Comment by praisethemoon** [comment]
@JanvyHung  Hello, please refer to this comment: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/558#issuecomment-520149690
