### ISSUE TITLE
Cursor starts at measure 1 even if drawFromMeasureNumber > 1 

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#566]
Since the ability to select the range of measures to draw was added,
we now need to advance the cursor to the starting measure, which was previously always 1.
This could be done either in Cursor.show() or in initialization, probably in show().
Also, reset() will need to do the same.

**Comment by matt-uib** [comment]
For this you should only set MusicSheet.SelectionStart to the absolute timestamp of the first measure you want to draw. The iterator will set the cursor on this position then i suppose.

**Comment by ifredom** [comment]
Can you give us a small example of choosing a certain range of notes?

**Comment by sschmidTU** [comment]
You can't choose a range of notes.
If you want to not draw certain notes, set `PrintObject = false` in the XML.
See OSMD Function Test - Invisible Notes in the demo.

**Comment by sschmidTU** [comment]
Or of course set it for each note in code: note.PrintObject = false
(might need another osmd.render() if you do this after rendering)
