### ISSUE TITLE
Spelling mistake in method name

### ISSUE THREAD

**Issue by dnlfrst** [opensheetmusicdisplay/opensheetmusicdisplay#568]
I suppose the method name below should actually be `GetNearestNote` (observe the missing **t** below)?

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/772be0ddaf4759bac3ace744308afc393c8a71d5/src/MusicalScore/Graphical/GraphicalMusicSheet.ts#L475

**Comment by sschmidTU** [comment]
good catch, quick report, quick fix!

By the way, this method is unused in OSMD, but potentially a big help for implementing click events, and perhaps relevant to #504.
I hadn't taken a look at this method before, so that typo was perhaps quite useful.
