### ISSUE TITLE
Hide/Show Tab staff line from library

### ISSUE THREAD

**Issue by naranbaat** [opensheetmusicdisplay/opensheetmusicdisplay#579]
I successfully rendered Music XML file but need to show/hide tab staff line from rendering.
Because in some cases, i want to display only standard staff line except of tablature
How it could be. Is there any option so i can use from library interface.

![How to hide tablature staff line](https://user-images.githubusercontent.com/48118372/66725447-b7d76e00-ee64-11e9-9df6-630298fdf7d0.png)

**Comment by sebastianhaas** [comment]
https://opensheetmusicdisplay.github.io/classdoc/classes/voice.html#visible

Probably multiple ways to get to your `Voice`, one would be via the music sheet's instruments list.

Just open the [demo](https://opensheetmusicdisplay.github.io/demo/) and execute the following lines:

```js
osmd.sheet.instruments[0].voices[0].visible = true
osmd.render()
```

which will hide the first voice of your first instrument.

**Comment by sschmidTU** [comment]
you can also try `Instrument.Visible = false` (e.g. `osmd.sheet.instruments[1].Visible = false` if possible. Can't try it right now.

**Comment by matt-uib** [comment]
Just for clarification: _Instruments_ mean here actually _Parts_ of the music piece. Should be renamed some time later. It seems that the TAB is given as an extra Part in your xml. As explained by the collegues you can hide it with the visibility flag.

**Comment by naranbaat** [comment]
I get it.
I appreciate your help.
