### ISSUE TITLE
How to do transposing

### ISSUE THREAD

**Issue by naranbaat** [opensheetmusicdisplay/opensheetmusicdisplay#580]
Some notes happen at really low place out of range of staff lines.
This is the screenshot from demo
![rendering low](https://user-images.githubusercontent.com/48118372/66746110-8934b400-eeb3-11e9-8dce-4ee5e3374026.png)

------------------------------------------------------------------------------------------------------------
That is the screenshot from the same music xml file using [another tool](https://www.soundslice.com/musicxml-viewer).
![rendering using transposing](https://user-images.githubusercontent.com/48118372/66746321-0ceea080-eeb4-11e9-8e06-c245407aab93.png)

I want them to display above using transposing like above.
Is there any option to do it easily?

**Comment by matt-uib** [comment]
@naranbaat that is strange and should work correctly for a standard bass clef.
I suspect the problem within the xml file. With which program was the file created? did you try to load it in another program (not the one where it has been created)? It seems to me that the octave of the pitch is not correctly set in the xml.

**Comment by naranbaat** [comment]
It's created by Sibelius.
let me attach file.
[allforyou.xml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3724708/allforyou.xml.txt)

**Comment by matt-uib** [comment]
![grafik](https://user-images.githubusercontent.com/17180665/66757288-2257d080-ee9c-11e9-9270-c1888b07c1e4.png)

I tried it with musescore - same problem. So really the octave is wrong in the xml.

**Comment by matt-uib** [comment]
Soundslice seems to either render it wrong or has some logic which tries to "fix" this...

**Comment by naranbaat** [comment]
yeah,  i want to know how to do transposing in that case like Soundslice.

**Comment by matt-uib** [comment]
The right way to me would be: Open some editor like musescore (free for download), transpose there and save.
We have nothing built in for that purpose, but you could also iterate all measures, within all staffentries, within all voiceentries and within all notes and change the octave in the pitch.
But i would rather remove the cause and not the syptom...

**Comment by naranbaat** [comment]
That make sense.

**Comment by naranbaat** [comment]
I think I can write this feature for OSMD.
Let me know how can i request to commit to repository for OSMD project.

**Comment by sschmidTU** [comment]
fork the repository, submit a pull request

**Comment by ice6** [comment]
is there any progress about the transposing function?

**Comment by sschmidTU** [comment]
The OSMD Transposition plugin is now integrated into OSMD, see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/733#issuecomment-823530818.
(currently on the develop branch, will be released in the next OSMD version after 0.9.5)
