### ISSUE TITLE
Positioning Lyrics

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#583]
I'm just getting started loading MusicXML from Sibelius and rendering it in Javascript.

How can I position the Lyrics between the Staves?

Is this in the documentation anywhere?

![image](https://user-images.githubusercontent.com/8965352/66769764-2a4f4a80-ee73-11e9-856f-22c19f1a6c15.png)

**Comment by sschmidTU** [comment]
I've never seen the lyrics placed so far up into the music system, see the [demo](https://opensheetmusicdisplay.github.io/demo/) for samples, like Schubert an die Musik.

can you give me an xml sample that produces this?
you can fix this manually by setting `osmd.EngravingRules.Rules.LyricsYOffsetToStaffHeight`, though theoretically it shouldn't happen like in your screenshot anyways.

**Comment by AlbertHart** [comment]
Thanks for taking a look at this. I'll take a look at the LyricsYOffsetToStaffHeight.

The original score was imported into Sibelius from an old version of Sibelius.

I made a new score from scratch with just 4 bars for testing. It still displays the same.



I have uploaded a ZIP file with both the Sibelius .sib file and the xml file extracted from Sibelius
[All The Things You Are - 4 bars - new.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3726582/All.The.Things.You.Are.-.4.bars.-.new.zip)

**Comment by AlbertHart** [comment]
I changed LyricsYOffsetToStaffHeight before the omsd.render and it did not change anything.

Before: osmd.EngravingRules.LyricsYOffsetToStaffHeight: 3

After: osmd.EngravingRules.LyricsYOffsetToStaffHeight: 6

**Comment by sschmidTU** [comment]
did you call osmd.render() after setting that? you need to do that after most option changes

**Comment by AlbertHart** [comment]
Here is the code I used:

console.log("Before: osmd.EngravingRules.LyricsYOffsetToStaffHeight: %s",
        osmd.EngravingRules.LyricsYOffsetToStaffHeight);

        osmd.EngravingRules.LyricsYOffsetToStaffHeight = 6;

        console.log("After: osmd.EngravingRules.LyricsYOffsetToStaffHeight: %s",
        osmd.EngravingRules.LyricsYOffsetToStaffHeight);

        osmd.render();    

I have attached a ZIP file with a stand-alone HTML and JS I am executing to render this.

The code is very simple.

The XML is stored in a string in the .js file,

Then processed in the HTML



[allthings4.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3726952/allthings4.zip)

**Comment by AlbertHart** [comment]
If you have, or can make a similar small XML that works, I can compare them and perhaps pre-process the Sibelius XML for any basic differences.

**Comment by AlbertHart** [comment]
I made a similar score in MuseScore and compared them using ArAxisMerge

The problem turned out to me the <lyric> line

MuseScore uses: <lyric number="1" default-x="6.58" default-y="-40.00" relative-y="-30.00">

**Comment by AlbertHart** [comment]
I made a similar score in MuseScore and compared the XMLs using ArAxisMerge

The problem turned out to me the <lyric> line

MuseScore uses: <lyric number="1" default-x="6.58" default-y="-40.00" relative-y="-30.00">

Sibelius uses:      <lyric default-y="-79" number="part1verse1" color="#000000">

If I change "part1verse1" to "1", then it works OK. 
So the OSMD parser must be requiring that the lyric number is a number and not alpha and ignoring the entire line in the case of an error.

I can pre-process my XML to replace the numbers. But if we can make the lyric numbers work as strings, then OSMD will work better for other Sibelius users.

I just located the lyric number specification in the MusicXML documentation. It is marked as a NMTOKEN:

Here is the definition of a DTD NMTOKEN:
An NMTOKEN (name token) is any mixture of Name characters. It cannot contain whitespace (although leading or trailing whitespace will be trimmed/ignored).

So characters should be allowed.

**Comment by sschmidTU** [comment]
that's an interesting finding, shouldn't be too hard to fix.

**Comment by AlbertHart** [comment]
This is the code in the ,js:


```
[var v=t.elements("lyric");
void 0!==this.lyricsReader&&void 0!==v&&(this.lyricsReader.addLyricEntry(v,this.currentVoiceEntry),this.voice.Parent.HasLyrics=!0);](url)
```

Which then runs:

`try{g=parseInt(u.attribute("number").value,10)}`

I guess someone could replace parseInt() with trim() and see what happens.

for now, I have added 

```
// <lyric default-y="-79" number="part1verse1" color="#000000">
            xml_string = xml_string.replace(/part1verse/g, "");
```

to my code

**Comment by matt-uib** [comment]
If easily possible, i would change the variables and the dictionaries we use here from int/number to string. Then numbers and string keys should work...

**Comment by sschmidTU** [comment]
I fixed the bug:
![image](https://user-images.githubusercontent.com/33069673/67084827-073bd800-f19e-11e9-969c-5a1dac62166c.png)

Sibelius format lyrics numbering should now be supported.

We actually had the code to check for Sibelius format, but it didn't get executed, because it was in a try-catch block, but parseInt just returns NaN instead of throwing an error.

**Comment by sschmidTU** [comment]
Also added your sample to our test samples:
`test_lyrics_number_string_and_space_for_unused_lines.musicxml`

before:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/33069673/208434890-ef5a9f36-d10b-4689-a0d3-d4221129f702.png">

after:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/33069673/208434993-0416188f-a0ed-4e58-a372-3ca4386be7bf.png">

**Comment by sschmidTU** [comment]
PR #1284 improves on above fix by handling lyrics numbers as strings instead of numbers, deleting a lot of lines that the Sibelius fix/workaround was, which is now unnecessary.
