### ISSUE TITLE
Source Code Editor

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#584]
When I open opensheetmusicdisplay.min.js with Visual Studio it takes forever to load (because of source code scanning) and is not really usable because it seems to have long lines of code.

What editors can you recommend for a Mac which work better with HTML and Javascript?

It would be good to find an editor with a source file manager as well.

![image](https://user-images.githubusercontent.com/8965352/66847896-62b55e00-ef31-11e9-9302-8e545880f5a9.png)

**Comment by samuelbradshaw** [comment]
I use Xcode for HTML / JavaScript and it works really well, though I do wish there were an "Xcode lite" available that didn't take up as much space on my computer (Xcode is primarily designed for iOS and Mac app development).

**Comment by sschmidTU** [comment]
Visual Studio Code or Webstorm maybe.
I use VSCode, see a [debugging guide](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Debugging) for it in the Wiki.

**Comment by AlbertHart** [comment]
I am trying VIsual Code and except for figuring out how to set up the .vscode folder, it is working pretty well.
