### ISSUE TITLE
OctaveShift causes error when start/end missing (AbsoluteTimeStamp error)

### ISSUE THREAD

**Issue by DavidQinqianWu** [opensheetmusicdisplay/opensheetmusicdisplay#586]
Hi, I am using osmd to render to musicXML, and chrome warning that "Cannot read property 'AbsoluteTimestamp' of undefined" 
which is located at MusicSheetCalculator.ts at line 1982

I was trying to render score only on "measure 2", my function is to use js to slice musicxml file structure(for example, if I want to render only measure 2, I will delete rest and measure 1, keep some necessary information to rebuild a new musicxml structure ), and then send it to osmd, let it to render. before the function works well, and I can render any specific measures, but now this alarm is my first time to see.

I know that osmd now has a new function that can choose specific measures to render, but now it's kind of hard for to change my code structure, but I will try that later.

 Could you please explain that why osmd said it could AbsoluteTimestamp is undefined? is that because when I slice musicxml, that I missed some necessary elements fo musicxml? So that osmd cound not calculate the AbsoluteTimestamp? 

Thanks

**Comment by DavoWU** [comment]
ok I use the new function of osmd, it said "End measure or staffLines for octave shift are undefined! This should not happen!" , and it does there is octave shift in it.

**Comment by DavoWU** [comment]
btw, is there any good way to fix it ?

**Comment by sschmidTU** [comment]
Yes, there's information missing in the xml, you can't just slice away measures you don't need from the xml, because they have necessary information of slurs ending etc.
So, it's better to use osmd.setOptions({drawFromMeasureNumber: x, drawUpToMeasureNumber: y}) instead of slicing.
But we could try to fix incomplete octave shifts during parsing.
could you maybe upload an xml sample that causes this error (in a .zip)?

**Comment by sschmidTU** [comment]
Ok, I now have a sample, but i'm afraid this will not be easy to fix, and octave shift will not be the only issue. so i really recommend you to use the drawFromMeasureNumber and drawUpToMeasureNumber options instead of slicing xmls manually.

**Comment by sschmidTU** [comment]
I improved the octave shift calculation so it works better with draw ranges.
It now reacts to drawFromMeasureNumber and drawUpToMeasureNumber and starts and ends within this range.

Previously it caused an error when the octave shift wasn't completely within draw range.

Test samples:
[octave_shift_draw_range_tests.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3741049/octave_shift_draw_range_tests.zip)

The six measure sample is good for playing around with the drawing range, it always draws as much of the 4 measure octave shift as it can (measures 1 and 6 are rests):
![image](https://user-images.githubusercontent.com/33069673/67042204-aec9f380-f127-11e9-8177-b1c18a3896d0.png)

**Comment by sschmidTU** [comment]
The AbsoluteTimeStamp error could be fixed separately, though it only occurs when the xml is invalid (start/end of octaveshift missing).

**Comment by DavoWU** [comment]
Thanks!  @sschmidTU, if AbusoluteTimeStamp error could be bixed separately, that would be excellent, and I  will try to  use the drawFromMeasureNumber and drawUpToMeasureNumber to fix the problem,  which is much more helpful and keep xml integrity.
 thanks for help 👍

**Comment by DavoWU** [comment]
I just found this 
![Screen Shot 2019-10-18 at 11 23 32](https://user-images.githubusercontent.com/23088138/67063556-cb067880-f199-11e9-8bb7-ddbd6ba9ce27.png), i saw the barline pop up when there is an ocative shift at the start measure, is that normal ?

**Comment by DavoWU** [comment]
I kind of fixed (start/end of octaveshift missing) problem and osmd does not warn me anymore. I build a octaveshift end tag node and octaveshif start tag node. if I slice the measures and missing the end of octaveshift tag, I will add the octaveshift end tag node at the end of measure that I keep. It works. Of course, it's not a good way, but does can fix the problem and have minimal changes for my current codes~~.

**Comment by sschmidTU** [comment]
> I just found this
> ![Screen Shot 2019-10-18 at 11 23 32](https://user-images.githubusercontent.com/23088138/67063556-cb067880-f199-11e9-8bb7-ddbd6ba9ce27.png), i saw the barline pop up when there is an ocative shift at the start measure, is that normal ?

That's weird, i've never seen that before. Could you give me a sample that reproduces this error?

>I kind of fixed (start/end of octaveshift missing) problem and osmd does not warn me anymore, and it can render properly. I build a octaveshift end tag node and octaveshif start tag node.

That's basically also what i did to fix the octave shifts with the draw measure range, just outside of XML.

**Comment by DavoWU** [comment]
> > I just found this
> > ![Screen Shot 2019-10-18 at 11 23 32](https://user-images.githubusercontent.com/23088138/67063556-cb067880-f199-11e9-8bb7-ddbd6ba9ce27.png), i saw the barline pop up when there is an ocative shift at the start measure, is that normal ?
> 
> That's weird, i've never seen that before. Could you give me a sample that reproduces this error?
> 
> > I kind of fixed (start/end of octaveshift missing) problem and osmd does not warn me anymore, and it can render properly. I build a octaveshift end tag node and octaveshif start tag node.
> 
> That's basically also what i did to fix the octave shifts with the draw measure range, just outside of XML.

yes sure here it is the sample that i was trying to render 
[sample.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3746455/sample.musicxml.zip)

**Comment by sschmidTU** [comment]
yes, there's still a bug in the OctaveShift calculation when the OctaveShift goes over multiple systems (lines). That needs to be fixed at some point.
By the way, this sample didn't load at all in OSMD 0.7.1.d, and depending on the system breaks the octave shifts do get rendered correctly, so that's progress.
https://opensheetmusicdisplay.github.io/demo/

**Comment by sschmidTU** [comment]
This seems fixed, samples render fine.
