### ISSUE TITLE
Show/Hide detail of sheet

### ISSUE THREAD

**Issue by naranbaat** [opensheetmusicdisplay/opensheetmusicdisplay#587]
I want to hide some details of sheet.
![Annotation 2019-10-18 004449](https://user-images.githubusercontent.com/48118372/67030293-b1d1dd80-f141-11e9-97b6-bda5e496a93c.png)

**Comment by sschmidTU** [comment]
```js
osmd.setOptions({
  drawCredits: false,
  //alternative:
  //drawTitle: false,
  //drawComposer: false,
  drawPartNames: false
});
osmd.sheet.instruments[1].Visible = false
osmd.render()
```

take a look at [OSMDOptions](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/OpenSheetMusicDisplay/OSMDOptions.ts) and the [Wiki](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki).

**Comment by naranbaat** [comment]
Ok, thanks for your answer.
