### ISSUE TITLE
Naming of bundled opensheetmusicdisplay

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#59]
Currently, the bundled version of opensheetmusicdisplay is called `osmd.js` or `osmd.min.js`.

I vote for renaming it to `opensheetmusicdisplay.js`, because:
- that is what it is,
- gives an idea on the subject in contrary to another acronym (imagine going through 30 script tags),
- we already have our main class called `OSMD`, so I'd prefer it if it was clear that there is a difference between the library as such and the main class for using it,
- our main (global) export is called `opensheetmusicdisplay`, so you put `opensheetmusicdisplay` in your script tag, and get a variable called `opensheetmusicdisplay`.
### How to achieve this

Have to rename browserify output in our `Gruntfile.js`
- browserify dist target, named `opensheetmusicdisplay.js`
- browserify demo target, named `opensheetmusicdisplay-debug.js`
- browserify test target, named `opensheetmusicdisplay-test.js`
- Change uglify task I/O from `osmd` to `opensheetmusicdisplay`.
- Change copy job for demo to reflect renaming
- Change demo html script tag accordingly

**Comment by bneumann** [comment]
@sebastianhaas @bukaznik Is this still relevant?

**Comment by matt-uib** [comment]
@bneumann would also be for opensheetmusicdisplay.js
I'm also totally fine with the full name. So let's do it @bukaznik ?

**Comment by bukaznik** [comment]
sure! @matt-uib @bneumann

**Comment by matt-uib** [comment]
Done so far! @sebastianhaas how can we update also the class documentation?
