### ISSUE TITLE
ViewPort issues

### ISSUE THREAD

**Issue by qky1412** [opensheetmusicdisplay/opensheetmusicdisplay#593]
Hi~Thx for the great work here!
I met a problem when it comes to mobile rendering. The meta "viewport" is set to "width=device-width, initial-scale=1.0", and it shows like this:
![IMG_4054](https://user-images.githubusercontent.com/4263356/67190952-6fe7b680-f423-11e9-8c53-e75bab735d4b.PNG)
Actually what I want it to be like this:
![IMG_4055](https://user-images.githubusercontent.com/4263356/67191360-116f0800-f424-11e9-888b-577f97f108be.PNG)
But I can not just simply set width to a specific number, say 750. Even if I do so, on my iPhone,  it first displays like this:
![IMG_4056](https://user-images.githubusercontent.com/4263356/67191639-8a6e5f80-f424-11e9-97cf-403d18c79b53.PNG)
I wonder how to make it render to auto fit the device width without double-tap the webView.

**Comment by matt-uib** [comment]
Maybe there is also a retina display problem occurring here as well. You might need to also multiply the retina multiplier (x2, x3) into the zoom variable...

**Comment by qky1412** [comment]
> Maybe there is also a retina display problem occurring here as well. You might need to also multiply the retina multiplier (x2, x3) into the zoom variable...

Thx for your reply, I set zoom to 0.55, now it looks fine!

**Comment by cparch** [comment]
I have multiple components on the page where I am rendering the sheet music. You can also just add the css zoom property to the container where the sheet music is if you don't want to effect the entire page.
