### ISSUE TITLE
Does <transpose> in MusicXML work

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#595]
Does this do anything?

```
<transpose>
     <diatonic>-4</diatonic>
     <chromatic>-7</chromatic>
    </transpose>
```

**Comment by sebastianhaas** [comment]
You can take a look at the source code to see what is implemented at this point:

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/ScoreIO/InstrumentReader.ts#L726


For reference: https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-transpose.htm

**Comment by sschmidTU** [comment]
In other words, no.
And correct me if i'm wrong, but transposition should only play a role for audio playback (#258, which could come in a few months), since the notated notes are given untransposed, as in score for the transposing instrument.
The only difference for using OSMD as a library is that the note's pitch will not be the transposed one, but you can access that in `instrument.PlaybackTranspose`, as seen in the code above.

**Comment by AlbertHart** [comment]
If a piano player is playing with a Bb trumpet player, the trumpet player would appreciate a leadvsheet in one key - say C - with notes and chords in C - which would playback in Bb so he can read it the way he has learned but hear it transposed into what he will hear from his trumpet.

On the other hand, the Piano player would appreciate a score in the transposed key Bb which lowers all notes 3 half steps and shows the chords and notes lowered into into Bb, in this example, so that when the piano player plays in Bb he will play in the same "key" as the trumpet player.

I want to able to view and print both lead sheets by changing one value and reloading them.

I can return to Sibelius, transpose the score, re-export and reload it. But it would be handier if this was a simple option when loading the musicxml into OSMD. 

I can also look into loading the musicxml into OSMD and altering everything which is in pitch before rendering. I was hoping that code was already available somewhere. 

In #132, matt-uib commented on May 24, 2017

> Yes we have a transposition plugin implemented, but we want to license this feature and therefore it is not in the open-source part of opensheetmusicdisplay. Yes we have a transposition plugin implemented, but we want to license this feature and therefore it is not in the open-source part of opensheetmusicdisplay.

I have not figured out how to find OSMD plugins yet. But I would rather find or create something which everyone can use for free.
