### ISSUE TITLE
Tabs: Use number of staff-lines given in XML

### ISSUE THREAD

**Issue by naranbaat** [opensheetmusicdisplay/opensheetmusicdisplay#596]
I am not sure how to render staff-lines on tablature.
In the XML, there is tag <staff-lines>

![Annotation 2019-10-23 100136](https://user-images.githubusercontent.com/48118372/67350059-38d8e880-f57c-11e9-9dc7-a9a153637024.png)

I want to display tablature, so trying to run Feature/Tabs branch.
It almost works well but it doesn't display staff lines correctly like following.
![Annotation 2019-10-23 101132](https://user-images.githubusercontent.com/48118372/67350518-84d85d00-f57d-11e9-83ae-d8eae330b49f.png)
As you can see above, I think there shouble be 4 staff lines(specified in XML.) but always 6 lines for now. 
Is there any solution to fix this?

**Comment by naranbaat** [comment]
I attached to MusicXML file for reference.
[rests3.xml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3759634/rests3.xml.txt)

**Comment by matt-uib** [comment]
unfortunately we currently don't have the resources for the tabs - please see also my comment in #126 .
Here in your screenshot you actually see also one of the open issues with the tabs: the rests are not considered correctly and the tab numbers are then not aligned vertically with the notes above.
Regarding your problem:
should be not too complicated:
- The lines-value needs to be read from XML in the MusicSheetReader/InstrumentReader and saved for this Instrument.
- For the rendering of the measure with Vexflow this lines-value has to be handed over so that Vexflow only draws e.g. 4 lines (see Vexflow repo for that)

**Comment by naranbaat** [comment]
I am writing code now.

- For parsing staff-lines part
 addAbstractInstruction() function in InstrumentReader.ts
`const staffLineNode: IXmlElement = nodeList.element("staff-lines");`
- For the rendering of the measure with Vexflow
resetLayout() function in VexFlowTabMeasures.ts
`this.stave = new Vex.Flow.TabStave(0, 0, 0, {
            space_above_staff_ln: 0,
            space_below_staff_ln: 0,
            num_lines: 4,
        });`
I am not sure how to hand over staffline number to render.

**Comment by sschmidTU** [comment]
Not entirely sure what you need or what your questions are, but you can find the staffline in `graphicalMusicPage.MusicSystems[i].StaffLines`. Each staffline has an Id.

**Comment by tresero** [comment]
Has there been any work on this? I have a lot of educational stuff that is for Cuban tres which is 3 strings. I am retired now, so may have some time to look at this if not, just don't want to duplicate effort.

**Comment by sschmidTU** [comment]
4 strings works, not sure about 3 strings, can you share a MusicXML file with it? Never seen one.
For the 4 strings one see `test/data/test_tabs_4_strings_bass_guitar.musicxml`

**Comment by sschmidTU** [comment]
I just re-checked the original file in this issue and it has `<staff-lines>6</staff-lines>` in it instead of 4, so the original issue/sample is not an issue with OSMD.
But it would be interesting to see if 3 strings works.

@tresero by the way, 4 strings was fixed in #991, might give you some pointers.

**Comment by tresero** [comment]
It doesn't work, but here is a sample.
![Guanaja](https://github.com/user-attachments/assets/82b72035-9aaa-40d0-946e-41809472e9b9)

**Comment by sschmidTU** [comment]
@tresero Thanks, but I need a MusicXML file to test it myself ;)

**Comment by tresero** [comment]
Sorry, trying to figure out how to attach xml. 
[Son Guanaja.zip](https://github.com/user-attachments/files/16997824/Son.Guanaja.zip)

**Comment by sschmidTU** [comment]
@tresero 3-string also fixed now.
<img width="884" alt="image" src="https://github.com/user-attachments/assets/5b40fe4b-e7ad-44cd-b4ab-73afe8e67488">
Vexflow didn't support the 3-staffline setting.

(run `npm run build` after the pull, or at least `npm run prebuildVexflow`)

**Comment by tresero** [comment]
Awesome! I wonder if there is a way to have it just read whatever lines there are. I'm sure other ethnic instruments have 5, 7 etc. Just a thought. My use case is covered, and I appreciate it. That was stopping me from using it.

**Comment by sschmidTU** [comment]
It now supports 3 to 8 strings. A score with 2 could exist and be interesting, though maybe noone has ever written a 2-staffline tab musicxml file, who knows.
We could just not throw an error and see what happens, though I would prefer having a 2-staffline file to test.
I'm not 100% sure why Vexflow decides to throw an error here, though it looks like you need to adjust at least 2 parameters for each number of stafflines, and there were no settings for it before.
