### ISSUE TITLE
Support loading MusicXML by URL

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#6]
We also want to move asynchronous loading of a `.xml`/`.mxl` file inside OSMD. The pattern used at [1] did not work for me with FF 47 on OSX, retrieving a local file. I got it working with Typescript in [2], however, no error handling is done there. But let's keep the `load(XML Element)` too!

- [x] Load from URL
- [x] Load from (xml) `Element`
- [x] Write tests including possible error handling

[1] https://github.com/opensheetmusicdisplay/demo/blob/master/src/demo.js#L99
[2] https://github.com/opensheetmusicdisplay/webpack-usage-example/blob/master/index.ts#L15

**Comment by acondolu** [comment]
Unfortunately, the loading from arbitrary URLs does not seem possible because of cross-domain security restrictions of JavaScript in browsers...

**Comment by sebastianhaas** [comment]
Hm kay, but isn't that something the user of OSMD has to take care of using a proper CORS setup?
What if somebody wants to load an external Mxl? If we only accept a `Document`, the user would have to unpack the zip file themselves? Besides of that, it would work for same-domain URLs which probably is the most relevant use-case anyway?

OT:
We're gonna host our MusicXmls on S3 http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html.

**Comment by acondolu** [comment]
Still missing loading from URL, for which I was planning to just use `JSZipUtils`.

**Comment by sebastianhaas** [comment]
Hm do you really think we need that? Its barely 100 lines of code and we would probably need to maintain it ourselves.

**Comment by acondolu** [comment]
No, we don't **need** that. Do you know any good library for reading binary files through AJAX?

**Comment by acondolu** [comment]
Basic support implemented in 8f20bf72bff1dc76b970362c946f0d2d01687b25.
