### ISSUE TITLE
Write visual comparison test

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#60]

**Comment by matt-uib** [comment]
i guess that 90% of the code changes will also change the optical output in nearly all the music pieces we have. Therefore it makes no sense to use the music pieces from our archive.
We would have to produce small pieces with all the different music symbols (for every note type, chord, tuplets, ties, clefs, ...) for it to make sense (Vexflow also has it that way).

**Comment by bneumann** [comment]
I had a quick look into the methods how vexflow does it and it is quite simple. I would only need the mentioned samples. But I can start of simple with notes only and see how that goes

**Comment by sebastianhaas** [comment]
I would also be interested in that, especially from a technical point of view. :) So if you had a chance to get things started I'm happy to contribute some more tests later on

**Comment by matt-uib** [comment]
@bneumann please just start on this whenever you feel like it.

**Comment by sschmidTU** [comment]
Implemented in #676.
