### ISSUE TITLE
Metronome mark overlaps chord text

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#601]
My metronome mark is overlapping my chord text.

![image](https://user-images.githubusercontent.com/8965352/67531722-fcdb7b80-f680-11e9-9589-758decf2af8c.png)

I tried setting  EngravingRules.Rules.MetronomeMarkYShift.

When I set it to -1.0, it moves it up a bit, but when I try setting it to -1.5 it breaks something.

![image](https://user-images.githubusercontent.com/8965352/67532406-593f9a80-f683-11e9-88dd-626809932355.png)

I get this error:

```
opensheetmusicdisplay.min.js:1 Uncaught TypeError: Cannot read property 'Measures' of undefined
    at e.t.calculateLyricExtend (opensheetmusicdisplay.min.js:1)
    at e.t.calculateLyricsExtendsAndDashes (opensheetmusicdisplay.min.js:1)
    at e.t.calculateLyricsPosition (opensheetmusicdisplay.min.js:1)
    at e.t.calculateMusicSystems (opensheetmusicdisplay.min.js:1)
    at e.t.calculate (opensheetmusicdisplay.min.js:1)
    at t.reCalculate (opensheetmusicdisplay.min.js:15)
    at t.render (opensheetmusicdisplay.min.js:15)
    at do_song (osmd_score.htm
```

One of these lines must mess things up:

    ```
(<any>vfStave.getModifiers()[vfStave.getModifiers().length - 1]).setShiftX(
      EngravingRules.Rules.MetronomeMarkXShift * unitInPixels
    );
    // TODO calculate bounding box of metronome mark instead of hacking skyline to fix lyricist collision
    const skyline: number[] = this.graphicalMusicSheet.MeasureList[0][0].ParentStaffLine.SkyLine;
    skyline[0] = Math.min(skyline[0], -4.5 + EngravingRules.Rules.MetronomeMarkYShift);
```

**Comment by AlbertHart** [comment]
I am able to get around it by setting MetronomeMarkXShift) to -10 instead.

![image](https://user-images.githubusercontent.com/8965352/67532643-3c579700-f684-11e9-933a-458675682987.png)

**Comment by sschmidTU** [comment]
Yes, this is also due to non-existent chord spacing (#597), but it's worth noting that the metronome mark should be included in the x-spacing of chords.
