### ISSUE TITLE
How to make alignment of Key/Rythminstruction between two stafflines

### ISSUE THREAD

**Issue by naranbaat** [opensheetmusicdisplay/opensheetmusicdisplay#604]
I want to make alignment left of Keyinstruction and Rythminstruction between several staff lines.

![Annotation 2019-10-28 141557](https://user-images.githubusercontent.com/48118372/67656076-b3937080-f98d-11e9-8b41-9ce8a20af546.png)
Is there any function and variable so i can control to achieve this?

**Comment by sschmidTU** [comment]
Fixed in #1427.
