### ISSUE TITLE
Zoom action on mobile

### ISSUE THREAD

**Issue by qky1412** [opensheetmusicdisplay/opensheetmusicdisplay#606]
How to zoom in&out and then re-render the sheet on mobile using gestures?

**Comment by sebastianhaas** [comment]
You may want to take a look at Hammer.js or something similar. Maybe you can translate the touch gestures to control the OSMD zoom level. But as you can see in the demo, rendering takes some time so you won't get that feeling of actually being able to seamlessly zoom into the score.

Please let me know if that points you towards the right direction.

**Comment by praisethemoon** [comment]
I think it is wiser to manipulate the raw SVG for zooming without re-rendering. I don't have much knowledge about it but seems more resonable to me.
