### ISSUE TITLE
Implement drawing note articulations

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#61]
Articulations are read from xml and given in every VoiceEntry (member Articulations, type ArticulationEnum[]).
Implement preparation code in VexFlowMusicSheetCalculator.layoutVoiceEntry which will be called for every voiceEntry.
Store created VexFlow objects in VexFlowStaffEntry given as parameter graphicalStaffEntry in the method if needed.

**Comment by ZhiguoZhang** [comment]
This the Articulations removed one year ago, and still not return, I need this feature for e.g. the piano fingering number. Trying to use develop branch do some develop. Strange is that looks there were something about Articulations, but removed. Don't know the reason.

**Comment by matt-uib** [comment]
Hi @ZhiguoZhang yes right fingering is not an articulation (which are things like staccato, tenuto...).
We have already something prepared for layouting the fingering - it would be great if you could help us here!
See e.g. line 1595 in MusicSheetCalculator.ts
// private calculateFingering()...
and line 61 in VoiceEntry.
public get TechnicalInstructions()
The code for reading in the fingering information from xml i have already prepared, but it is not committed right now. Let me prepare that for you and then you can hand over the fingering info to vexflow for rendering.

Just that i get it right, what do you mean by Articulations have been removed? do you mean that help wanted has been removed? We changed it to contrib -> contribution wanted... maybe that was misleading?

**Comment by ZhiguoZhang** [comment]
hi, @matt-uib 

### Fingering
yes, I saw such prepared, and would like to continue, the basic idea is that in `InstrumentReader.readNextXmlMeasure` loop

 ```typescript
for (let xmlNode of xmlMeasureListArr) {
```
 for each VoiceEntry if `technical` element be found, then will be attached to `CurrentVoiceEntry` for later rendering. 

Please commit if you could, I would like try to hand over for rendering. (which branch then? develop branch, right?)
### Articulations
about Articulations it is also important I guess, I found that current demo/release there is not articulation feature at all. And I notice that there are commented code about Articulations, e.g. in `VoiceGenerator` line: 52

```typescript
//private articulationReader: ArticulationReader;
```
that is what I mean it is removed.

**Comment by matt-uib** [comment]
I will create a new branch for this.

Yes exactly! Also for the Articulations we have something prepared - we can do it more or less similar to the fingering.

**Comment by ZhiguoZhang** [comment]
cool!

**Comment by matt-uib** [comment]
I created the feature/Articulations branch for you.
Articulations and fingering technical instructions are now read from xml and can be handed over to VexFlow here:
See VexFlowMusicSheetCalculator.ts:
```
/**
   * Add articulations to the given vexflow staff entry.
   * @param articulations
   * @param voiceEntry
   * @param graphicalStaffEntry
   */
  protected handleVoiceEntryArticulations(articulations: ArticulationEnum[],
                                          voiceEntry: VoiceEntry, staffEntry: GraphicalStaffEntry): void {
    // uncomment this when implementing:
    // let vfse: VexFlowStaffEntry = (graphicalStaffEntry as VexFlowStaffEntry);

    return;
  }

  /**
   * Add technical instructions to the given vexflow staff entry.
   * @param technicalInstructions
   * @param voiceEntry
   * @param staffEntry
   */
  protected handleVoiceEntryTechnicalInstructions(technicalInstructions: TechnicalInstruction[],
                                                  voiceEntry: VoiceEntry, staffEntry: GraphicalStaffEntry): void {
    // uncomment this when implementing:
    // let vfse: VexFlowStaffEntry = (graphicalStaffEntry as VexFlowStaffEntry);
    return;
  }
```

**Comment by ZhiguoZhang** [comment]
Thank you, I will try to continue.

**Comment by matt-uib** [comment]
Dear @ZhiguoZhang how is it going with the articulations? Do you need help or some input?

**Comment by matt-uib** [comment]
@ZhiguoZhang we have implemented reading and rendering articulations now. Please have a look if you wish in the develop branch.
