### ISSUE TITLE
drawPartNames: false -  causing error on second staff

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#612]
(https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3801747/Like.Someone.in.Love-.Ab.xml.zip)
When I set drawPartNames to false I get this error at the start of the second staff, and only the first staff gets rendered.

Note: When I change the zoom, to see more bars per staff, the error still occurs at the start of the second staff.

backend: canvas also fails 0- but with no error message.

It does not fail on every song . but on at least two I tested.

osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay(container, {
                backend: "svg",
                drawingParameters: "compact",
                drawPartNames: false, // causes svg error on the party's over
 

opensheetmusicdisplay.min.js:1 Error: <svg> attribute height: Expected length, "Infinity".

Here is a musicxml file:

[ Like Someone in Love- Ab.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3801750/Like.Someone.in.Love-.Ab.xml.zip)

**Comment by sschmidTU** [comment]
I don't get this error with any of the settings and the xml you provided, not even in the [online demo](https://opensheetmusicdisplay.github.io/demo/).
There must have been other causes for your issue. Maybe you can re-investigate and provide a set of sample and options that reliably reproduces this.

**Comment by AlbertHart** [comment]
I made a self contained .htm (except for opensheetmusicdisplay.min.js) which demonstrates the problem.

I have attached it, and also put a copy on my website.

http://alhartapps.com/Music/test_drawpartnames.htm

Select false for drawPartNames and you get the error:

![image](https://user-images.githubusercontent.com/8965352/68431577-c537fd80-016f-11ea-967d-092c3b41eb82.png)

**Comment by sschmidTU** [comment]
Sorry, your sample htm isn't available anymore. I can't reproduce this error. If you can put up a reproducible sample again, i can reopen and check again.

**Comment by thinker3** [comment]
I got a similar error message, but I don't know the detail, please check the sample file.
[千与千寻片尾.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3920874/xml.zip)

**Comment by sschmidTU** [comment]
@thinker3 this was fixed on the 16th of October, it's just not included in the latest release yet (error still happens in the [online demo](https://opensheetmusicdisplay.github.io/demo/), but not in the local demo built from the develop branch).
There will probably be a new release soon, then it will be fixed.
If you want to fix it beforehand, you can check out the develop branch, run npm install and npm build, and use the .min.js from the build folder.

**Comment by sschmidTU** [comment]
Here's a screenshot of your sample with the current develop version:
![image](https://user-images.githubusercontent.com/33069673/70145025-74002880-169f-11ea-9a39-61978988f9fa.png)
no infinity error.
