### ISSUE TITLE
Modifying - Rendering in the SVG

### ISSUE THREAD

**Issue by dedan** [opensheetmusicdisplay/opensheetmusicdisplay#615]
I currently work on a little project for me to do piano practices and directly evaluate them. I want to show myself a certain exercise (for example a scale) in an OSMD. When I play this scale I record the notes via MIDI and would like to render information on how well I did directly into the exercise. I know that your API allows to e.g. change the color of a note so that I could mark the notes that I missed.

But I would like to show more information, for example, a bar graph with the velocity with which I played the note. 

The question: What's the preferred way to directly render into the SVG into which the sheet music is rendered? When I modify the SVG by hand, the next OSMD render update would probably destroy my changes.

Thank you very much for publishing such a great library.

**Comment by sschmidTU** [comment]
I'm not sure, but a render update shouldn't be a problem, because you can just modify the SVG again after the render, right?
Also, have you considered just rendering over the SVG instead of into it?
There are multiple issues for getting screen coordinates, like #504.

> Thank you very much for publishing such a great library.

<3

**Comment by dedan** [comment]
Hey Simon,

thank you very much for that quick and helpful response. Rendering over the SVG sounds like a great solution and I will experiment with that. 

Also thanks for pointing me to the issues related to getting screen coordinates. 

I'll keep you posted regarding my progress. Feel free to close the issue for now.

**Comment by AlbertHart** [comment]
> "When I modify the SVG by hand, the next OSMD render update would probably destroy my changes."

I am working on a project where I need to render but not lose the SVG from the first render. To do this I copy the entire innerHTML from the first render into a second div. The SVG bets copied properly, and then not rendered over, so you can change it, but not lose it.

In this example, I render into container_temp, and then move it to music_container4.

```
<h3> Chords used in Score</h3>
<div id="music_container4" style="width:1100px;" ></div>
<p></p>

<!-- draw here and then move -->   
<div class="noprint" id="container_temp" style="width:1100px;" ></div>
<p></p>
```




```
         osmd.render();

        // move to proper container
        container_temp = document.getElementById(container_temp_id);
        page_html = container_temp.innerHTML
        elt = document.getElementById(container_for_sheet_id);
        elt.innerHTML = page_html;
        container_temp.innerHTML = "<h3>MOVED TO: " + container_for_sheet_id + "</h3>";
        elt.scrollIntoView(true);
```

**Comment by sschmidTU** [comment]
Great, and thank you @AlbertHart for the help.
Feel free to keep replying even if the issue is closed.

ps @AlbertHart : Sorry your issues mostly go unanswered for now, but as i wrote in other issues, the team members really are quite busy at the moment.

**Comment by luyunxu** [comment]
> > “当我手动修改SVG时，下一次OSMD渲染更新可能会破坏我的更改。”
> 
> 我正在一个需要渲染但不丢失第一个渲染的SVG的项目中工作。为此，我将整个内部HTML从第一个渲染复制到第二个div中。SVG将被正确复制，然后不呈现，因此您可以更改它，但不会丢失它。
> 
> 在此示例中，我渲染到container_temp，然后将其移动到music_container4。
> 
> ```
> <h3> Chords used in Score</h3>
> <div id="music_container4" style="width:1100px;" ></div>
> <p></p>
> 
>    
> <div class="noprint" id="container_temp" style="width:1100px;" ></div>
> <p></p>
> ```
> 
> ```
>          osmd.render();
> 
>         // move to proper container
>         container_temp = document.getElementById(container_temp_id);
>         page_html = container_temp.innerHTML
>         elt = document.getElementById(container_for_sheet_id);
>         elt.innerHTML = page_html;
>         container_temp.innerHTML = "<h3>MOVED TO: " + container_for_sheet_id + "</h3>";
>         elt.scrollIntoView(true);
> ```

After the experiment according to your method, the playback and other functions of osmd failed
