### ISSUE TITLE
What are you considering for audio

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#619]
I am trying to create a web app which will ask the user to choose a piano chord - as part of a quiz - from 4 choices - and I want to let the user hear the chords by pressing on them.

I think I can use OSMD to draw the chord choices, but then I want to generate the sounds.

I am starting to look at options to play the sounds - e.g. HTML5 <audio> or Tone.js.

I believe you are working on the ability to play OSMD scores.

What technology would you recommend for audio generation - and do you have anything to share yet?

![image](https://user-images.githubusercontent.com/8965352/68692147-35f56600-0532-11ea-9507-c2cd9065775d.png)

**Comment by ifredom** [comment]
A simple control method is to use html5 audio.  To synchronize cursor and voice, you can refer to [JIMMY’S AUDIO PLAYER](https://github.com/jimutt/osmd-playback-demo)

**Comment by sschmidTU** [comment]
[See here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/258#issuecomment-406620322)
