### ISSUE TITLE
Implement drawing grace notes as smaller notes

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#62]
Look first at the createGraceNote method in VexFlowGraphicalSymbolFactory. 
Compare then how normal notes are handled in the createNote method and in VexFlowStaffEntry.
Check out what VexFlow needs to draw a note as grace note. Depending on the findings set some flag in the grace-VexFlowGraphicalNote or store the grace notes as list member in VexFlowStaffEntry and handle them similar to the graphicalNotes member.
All implementation should be done in classes in the VexFlow folder - if this doesn't seem possible, please get in touch.

**Comment by bohoffi** [comment]
According to the vexflow sources `GraceNote` _extends_ `StaveNote`. So rendering the note's size is handled by vexflow's engine.
Note as StaveNote:
![2017-05-19_15h41_49](https://cloud.githubusercontent.com/assets/9944566/26250287/d8168f94-3ca9-11e7-9757-9dc63c9e8897.png)

Note as GraceNote:
![2017-05-19_15h41_13](https://cloud.githubusercontent.com/assets/9944566/26250294/df2fa338-3ca9-11e7-847a-3a27310fb114.png)

What has to be done:
- adding `GraceNote` (extending `StaveNote`) to typings (if implemented before switching to `@types/vexflow`)
- adding appropriate `static GraceNote` to `VexFlowConverter`
- adding a flag to `GraphicalNote` or its property `sourceNote` (`typeof Note`) if it's a grace note or not
  - maybe in `handleGraceNote()` (`VoiceGenerator.ts:541`) after `let graceNode: IXmlElement = node.element("grace");`
- use the added method from the converter in `staffMeasureCreatedCalculations()` (`VexFlowMeasure.ts:349`) if the grace note flag is true

**Comment by matt-uib** [comment]
@bohoffi thanks very much for your input and directions here! Are you on it? Would you like to implement it?

**Comment by bohoffi** [comment]
@matt-uib no problem ;)
I really would like to implement this but I don't think that I can handle this before the end of the year.

**Comment by matt-uib** [comment]
@bohoffi that's totally fine! January... please just let us know, if you might not start on it. But great! Please ask me if you need something. I will try to think through it also once more and add my thoughts then..

**Comment by matt-uib** [comment]
@bohoffi Regarding the implementation i suggest the following to support the current system best:
We currently store grace notes in our object model in the "main" voice entry (meaning the main note(s) where the grace notes belong to musically) in two lists `GraceVoiceEntriesBefore `and `GraceVoiceEntriesAfter`. And it would totally make sense to add a grace flag to a `VoiceEntry `directly - this would also simplify some of the `MusicSheetCalculator `code. But as this needs a lot more refactoring action, i would for now leave it that way, but do the following (very close to your suggestion):
- Add a "isGrace" flag in `VexFlowGraphicalNote`.
- In `VexFlowGraphicalSymbolFactory.createGraceNote()` create a `VexFlowGraphicalNote `with `isGrace=true`
- In `VexFlowMeasure.staffMeasureCreatedCalculations()` before currently the `VexFlowConverter.StaveNote(gnotes[voiceID])` is created, add a check if all `VexFlowGraphicalNotes` of `gnotes[voiceID]` have the isGrace flag true. If this is the case call `VexFlowConverter.GraceNote(gnotes[voiceID])` instead
- And implement `VexFlowConverter.GraceNote()` as you suggested.
- The methods `VexFlowConverter.StaveNote()` and `VexFlowConverter.GraceNote()` should directly take `VexFlowGraphicalNotes`, so cast them already in `VexFlowMeasure`

**Comment by bohoffi** [comment]
@matt-uib I'm really sorry but I can not find the time to start on this right now. So if anyone else would like to give it try?
WIll give support as much as I can...

**Comment by matt-uib** [comment]
That's totally fine, no problem - thanks very much for telling us!

**Comment by sschmidTU** [comment]
(duplicate of #293, already implemented)
