### ISSUE TITLE
Merging noteheads in different voices

### ISSUE THREAD

**Issue by sephshewellbrockway** [opensheetmusicdisplay/opensheetmusicdisplay#623]
In closed-score choral music, when two voices that share a stave sing the same note at the same time, the usual practice is to write a single notehead with both an upper and a lower stem. Is it possible to enable this behaviour in OSMD? See [here](http://pdhp.codex.scot/tune/5de6669487fe661513000001) for an example of the kind of situation I’m talking about; the minim Ds in the soprano and alto parts in bar 3 should have their heads merged.

**Comment by sschmidTU** [comment]
Yes, we already have an issue for that: #414.
It's not easy to find though, so don't worry about it.
This is not so easy to implement, but would definitely be nice to have. I'll take a look soon.
