### ISSUE TITLE
Complete introduction of usage information

### ISSUE THREAD

**Issue by ifredom** [opensheetmusicdisplay/opensheetmusicdisplay#627]
I look forward to updating the readme and adding information on how to introduce and use it in the introduction page.so more people use osmd for easier discussion.

**Comment by sschmidTU** [comment]
I appreciate your help. However, information on how to use OSMD should be in the [Wiki](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki), not in the source folder. Have you read the Wiki start page and pages like Getting Started inside it? The Readme is not a tutorial, and it already points to the Wiki.

**Comment by ifredom** [comment]
> 我感谢您的帮助。但是，有关如何使用OSMD的[信息](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki)应在[Wiki中](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki)，而不在源文件夹中。您是否已阅读Wiki起始页以及其中的“ [入门”之类的](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Getting-Started)页面？自述文件不是教程，它已指向Wiki。
> 当然，欢迎您向Wiki添加信息。

Thanks i found it in the wiki
