### ISSUE TITLE
Are there any listening events after musicxml has been loaded?

### ISSUE THREAD

**Issue by postdep** [opensheetmusicdisplay/opensheetmusicdisplay#628]
Are there any listening events after musicxml has been loaded?

**Comment by sschmidTU** [comment]
Do you mean an event that tells you when the musicxml has been loaded?
You can use Promises for that:
`osmd.load(str).then()` or
`osmd.render().then()`.
If you mean click events, there's a discussion in #262.

**Comment by postdep** [comment]
@sschmidTU thanks
