### ISSUE TITLE
I don't know if I can do similar graffiti operations on osmd?

### ISSUE THREAD

**Issue by postdep** [opensheetmusicdisplay/opensheetmusicdisplay#629]
I want to use graffiti to mark the score and promote my practice. I don't know if this function can be realized?

**Comment by sschmidTU** [comment]
what do you mean with graffiti?
This is graffiti:
![image](https://user-images.githubusercontent.com/33069673/70678940-e7073180-1c93-11ea-99ab-1e578ef2bdf3.png)

**Comment by bneumann** [comment]
Haha, I think we have a confusion here. @postdep, you mean 亂畫? Like drawing, mark, comments on your osmd render?
That is currently not possible but would be a nice feature

**Comment by postdep** [comment]
Almost. If osmd can export a picture, I'll doodle on it and then cover it with a layer. Don't you know if it's feasible? @sschmidTU @bneumann

**Comment by ifredom** [comment]
> const Raphael = require("raphael");

you can use Raphael have a test。I am making a similar function, using raphael to overlay an animation effect on osmd。

**Comment by sschmidTU** [comment]
OSMD isn't really made for fast interactive rendering yet, but your best bet is manipulating the SVG or rendering over the SVG/image.
See #670, #549, #615, #504, etc.
