### ISSUE TITLE
Implement drawing in-measure clefs

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#63]
Clefs at the beginning of a staff-line and at the end of measures are already drawn.
But there can also be clef changes within a measure, e.g. happening before the second quarter note in a 4 quarters measure.
See therefore the VexFlowGraphicalSymbolFactory.createInStaffClef() method. Here you get the clefInstruction which shall be placed before the given GraphicalStaffEntry (is a VexFlowStaffEntry).
Store the information here inside VexFlowStaffEntry for being able to finally prepare the drawing of the clef in VexFlowMeasure.staffMeasureCreatedCalculations().
All implementation should be done in classes in the VexFlow folder - if this doesn't seem possible, please get in touch.

**Comment by matt-uib** [comment]
Implemented it: in-measure clef is shown.
A final test is needed, if it also works for more than one Voice per Staff and also for more than one Instrument. (not that we need Ghost notes again...)

**Comment by sschmidTU** [comment]
Done.
Multi-Voice Multi-Instruments works.
Two clefs in two voices at one timestamp are not valid notation, i think.
![image](https://user-images.githubusercontent.com/33069673/53457078-3516b580-3a31-11e9-8ff7-731f428515a0.png)
[inmeasure_clef_multi_voice_multi_instrument.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2908087/inmeasure_clef_multi_voice_multi_instrument.zip)
