### ISSUE TITLE
osmd render  notes in wrong positioning (voice entry is wrong )  when notes cross bass and treble 

### ISSUE THREAD

**Issue by DavidQinqianWu** [opensheetmusicdisplay/opensheetmusicdisplay#632]
A question that OSMD seems to render cross note will have some wrong position
OSMD render:
<img width="653" alt="70515977-2ab54a80-1b71-11ea-86a8-20501fb983db" src="https://user-images.githubusercontent.com/23088138/70845032-a7ec0280-1e84-11ea-9014-f33bcf786974.png">
but the reall score is 
![70516074-4b7da000-1b71-11ea-88d1-cda07502a8b1](https://user-images.githubusercontent.com/23088138/70845035-ba663c00-1e84-11ea-9273-2b94bea4d18c.png)
they are on different events.
Also here is another score that I found: 
<img width="388" alt="截屏2019-12-14下午3 17 22" src="https://user-images.githubusercontent.com/23088138/70845049-03b68b80-1e85-11ea-8bb6-015f2e692319.png">
but the real score is :
![截屏2019-12-14下午3 19 37](https://user-images.githubusercontent.com/23088138/70845066-32346680-1e85-11ea-96ab-11f5f9cfa2c9.png)
(ignore share beams one ) I think the problem is the notes are should note on the same time event, It seems OSMD calculates the notes on the same time event when notes that cross the bass and treble. 

here  are samples: 
[Hanon.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3963579/Hanon.musicxml.zip)
[demo.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3963580/demo.musicxml.zip)
Thanks

**Comment by DavidQinqianWu** [comment]
in this score, OSMD put the staff entries are in wrong position, 
<img width="170" alt="截屏2019-12-14下午4 29 28" src="https://user-images.githubusercontent.com/23088138/70845894-fdc5a800-1e8e-11ea-9637-c1f3a5722185.png">. 

but in another score that osmd  put the staff entries are right  position, but  note did not place the that place 
<img width="272" alt="截屏2019-12-14下午4 27 19" src="https://user-images.githubusercontent.com/23088138/70845920-39607200-1e8f-11ea-9d17-d6ca1266b507.png">
<img width="272" alt="截屏2019-12-14下午4 27 19" src="https://user-images.githubusercontent.com/23088138/70845935-56954080-1e8f-11ea-85fb-e0108461d837.png">

**Comment by sschmidTU** [comment]
#630 is a duplicate (not sure why that one was closed).
@DavidQinqianWu thanks for creating the issue, we will investigate.

**Comment by sschmidTU** [comment]
This was fixed a while ago.
<img width="156" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/6f515f9e-ba86-4faa-b73a-9b407ef81231">

<img width="164" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/39cee323-931a-4ed0-9fc9-28a584f233ab">
