### ISSUE TITLE
Whether other page turning methods are supported

### ISSUE THREAD

**Issue by TheBrightestStarInTheNightSky** [opensheetmusicdisplay/opensheetmusicdisplay#633]
In my android project, I want to ask if I can replace the first line of music with the third line when I play the music to the second line, and keep flipping through all the music on the same page. Does osmd support this kind of page turning

**Comment by ifredom** [comment]
目前似乎不支持这种渲染方式，只要load xml，就会根据osmdOption参数渲染出整个乐谱。

**Comment by TheBrightestStarInTheNightSky** [comment]
> 目前似乎不支持这种渲染方式，只要load xml，就会根据osmdOption参数渲染出整个乐谱。

请问你知道osmd是否可以控制一个小节或者一行乐谱的svg内容的方法吗？

**Comment by ifredom** [comment]
> > 目前似乎不支持这种渲染方式，只要load xml，就会根据osmdOption参数渲染出整个乐谱。
> 
> 请问你知道osmd是否可以控制一个小节或者一行乐谱的svg内容的方法吗？

描述具体一点？

**Comment by ifredom** [comment]
I think you can partially render the score and then set the page turning effect in other ways。

```js
  /**
   * start,end measureIndex
   *
   * @param {*} start
   * @param {*} end
   * @memberof MusicEngine
   */
  sliceMeasure(start, end) {
    this._osmd.setOptions({
      drawFromMeasureNumber: start,
      drawUpToMeasureNumber: end
    });
    this._osmd.render();
  }
```

**Comment by sschmidTU** [comment]
Such rapid changes of the score aren't suitable for OSMD. ifredom has a good idea for an approach.
