### ISSUE TITLE
wrong clef type is used (treble instead of bass)

### ISSUE THREAD

**Issue by eyalcohen7** [opensheetmusicdisplay/opensheetmusicdisplay#635]
I have read the following file using opensheetmusicdisplay, the xml was exported with a Bass Clef, but it's displayed as a Treble Clef

[L.H.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/3980850/L.H.txt)

![image](https://user-images.githubusercontent.com/3308022/71129517-4ca96f80-21f8-11ea-943e-41f8e6137bae.png)

any ideas?

**Comment by DavidQinqianWu** [comment]
Hi , I have chekc your file, i found this file is a single staff musicxml file. But in your file, at the line 123` <clef number="2" color="#000000">` which is not correct, because this is a single staff, which means you actually don't have number 2.  so if you change you clef node attribute `number=2` to `number =1`, or remove attribute `number`, it will works fine for  you

**Comment by eyalcohen7** [comment]
Thanks! However the file was exported from Sibelius - is there something I can do there to fix it?

**Comment by DavidQinqianWu** [comment]
maybe you can use 
1. Node.js to read your file,  and use `x2js` on npm, to transfer you string format data  to json format, and change the attribute value through json, and then retransfer to xml.
2. use DomParse() on web , to instroe you text file to DOM version, if(chrome ), use `getElementByTagName('clef)`,  then use `removeAttribute `to remove `number `attribute

**Comment by bneumann** [comment]
Jupp the second approach seems feasible. We won't talk about the first proposal...ever again 😉

Anyways having a kind of a hook to manipulate the parsing would be nice. Unfortunately our xml loading is not as straight forward and hooking in there needs some refactoring I presume. So writing you own preloader before sending the XML to osmd is a good way.

**Comment by eyalcohen7** [comment]
I guess I can fix the file manually this time, but what about other exports from Sibelius? how can I detect the issue?

**Comment by sschmidTU** [comment]
@eyalcohen7 I fixed this by correcting the clef/staff number that was wrongly exported into the XML (by Sibelius).

Visual regress(ion tests show no changes over our 41 standard samples)
