### ISSUE TITLE
Can I control all SVG elements in a Measure or a line of music

### ISSUE THREAD

**Issue by TheBrightestStarInTheNightSky** [opensheetmusicdisplay/opensheetmusicdisplay#636]
Is there a way that I can control all SVG elements in a Measure or a line of music, including note, beams, and speed markers?In my Android project, I want to control how a line of music content moves up or down by controlling SVG

**Comment by TheBrightestStarInTheNightSky** [comment]
Excuse me, can you give me some advice?@sschmidTU

**Comment by sschmidTU** [comment]
This is currently not possible. The SVG consists of small independent elements like a single line of the 5 lines of a staff.
