### ISSUE TITLE
Implement drawing brace for multi-line instrument (e.g. piano)

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#64]
In VexFlowMusicSystem.createInstrumentBrace(firstStaffLine: StaffLine, lastStaffLine: StaffLine) the staff lines are given which shall be embraced.
Create a new Class called VexFlowInstrumentBrace which inherits from GraphicalObject.
In createInstrumentBrace instanciate a new VexFlowInstrumentBrace with a x-width corresponding to the width of a VexFlow Brace (in sheet units - see VexFlowMusicSheetDrawer.calculatePixelDistance and make inverse if needed). Use a negative left margin for representing a positive width (has to do with right aligning the object).
Store all other needed information like the VexFlowStaffLines in VexFlowInstrumentBrace.
Write the drawing code into VexFlowMusicSheetDrawer.drawInstrumentBrace().
All implementation should be done in classes in the VexFlow folder - if this doesn't seem possible, please get in touch.

**Comment by matt-uib** [comment]
@bneumann i've created a new feature branch for you and added some more info in comments about how to implement it.

**Comment by bneumann** [comment]
@matt-uib anything else here from your side? Otherwise I'd say we close this one

**Comment by matt-uib** [comment]
We still need the x measurement and correct bounding box creation at some point, but as we have the main part working - yea, let's close it!
