### ISSUE TITLE
Does it support a uniform height for each line of sheet music

### ISSUE THREAD

**Issue by dyj11** [opensheetmusicdisplay/opensheetmusicdisplay#640]
Does it support a uniform height for each line of sheet music ? I want each line of sheet music  to have a fixed height

**Comment by DavidQinqianWu** [comment]
well, it's probably not a good choice a make each line of scores has the same height, because there are different symbols and signs of each measure. If the each line of the score has the same line height, which means might some lines are might very loose, and some lines  might very crowded.

**Comment by DavidQinqianWu** [comment]
but if you want to get each lines information, you can check OSMD object which contains the  measures information, and there is bounding box information in there, which you  get the data that you may need

**Comment by TheBrightestStarInTheNightSky** [comment]
> 但是，如果要获取每条线的信息，则可以检查包含度量信息的OSMD对象，并且其中包含边界框信息，您可以获得所需的数据

Because I found that in MuseScore3 my music line heights are the same, and I need to unify the line heights in my Android project to achieve better results

**Comment by TheBrightestStarInTheNightSky** [comment]
> but if you want to get each lines information, you can check OSMD object which contains the measures information, and there is bounding box information in there, which you get the data that you may need

Because I found that in MuseScore3 my music line heights are the same, and I need to unify the line heights in my Android project to achieve better results

**Comment by ifredom** [comment]
> > but if you want to get each lines information, you can check OSMD object which contains the measures information, and there is bounding box information in there, which you get the data that you may need
> 
> Because I found that in MuseScore3 my music line heights are the same, and I need to unify the line heights in my Android project to achieve better results

The height of each line is unified, I did not find a similar method
