### ISSUE TITLE
Anacrusis (rest) note value bug in 6/4

### ISSUE THREAD

**Issue by oni7uka** [opensheetmusicdisplay/opensheetmusicdisplay#642]
This is my test file [PianoSolo.xml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4018034/PianoSolo.xml.txt)(Please remove .txt suffix).
Incorrect note position display in low range. The version of OSMD I use is develop branch

**Comment by oni7uka** [comment]
This is the correct note position：
![correct](https://user-images.githubusercontent.com/15939343/71831669-54b44b00-30e4-11ea-83eb-3b62f85b9b3d.png)

But OSMD like this：
![bug](https://user-images.githubusercontent.com/15939343/71831736-7ad9eb00-30e4-11ea-9c8a-26f9f19662eb.png)

**Comment by sschmidTU** [comment]
Yes, OSMD supports 3.0 in general, this is not an issue with MusicXML version, but a bug probably related to time signature and anacrusis. Will look into it when I can.

**Comment by sschmidTU** [comment]
this was fixed at some point since the issue was created ;)

<img width="225" alt="image" src="https://user-images.githubusercontent.com/33069673/217938993-d363073b-132a-4d92-a24d-760d9dc94d9b.png">
