### ISSUE TITLE
Implement drawing bracket for a group of instruments (e.g. choir voices)

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#65]
This issue is very simmilar to the instrument brace issue.
In VexFlowMusicSystem.createGroupBracket(firstStaffLine: StaffLine, lastStaffLine: StaffLine) the staff lines are given which shall be visually grouped.
Create a new Class called VexFlowGroupBracket which inherits from GraphicalObject.
In createGroupBracket() instanciate a new VexFlowGroupBracket with a x-width corresponding to the width of a VexFlow Bracket (in sheet units - see VexFlowMusicSheetDrawer.calculatePixelDistance and make inverse if needed). Use a negative left margin for representing a positive width (has to do with right aligning the object).
Store all other needed information like the VexFlowStaffLines in VexFlowGroupBracket.
Write the drawing code into VexFlowMusicSheetDrawer.drawGroupBracket().
All implementation should be done in classes in the VexFlow folder - if this doesn't seem possible, please get in touch.

**Comment by matt-uib** [comment]
@bneumann this is finished, right?

**Comment by bneumann** [comment]
Jupp
