### ISSUE TITLE
`drawFingerings` does not update

### ISSUE THREAD

**Issue by dedan** [opensheetmusicdisplay/opensheetmusicdisplay#650]
When I initialize a new OSMD with `{drawFingerings: true}` the fingerings are correctly displayed. However when I initialize an OSMD with `{drawFingerings: false}` and later call 

```js
osmd.setOptions({drawFingerings: true})
osmd.render()
```
the fingerings are still not displayed. I would have expected that the OSMD would re-render with visible fingerings.

As a check to make sure that this is generally the right method of changing rendering options I tried the same with the option `drawTitle` and here it works as expected:

First, the title is not visible, but after running

```js
osmd.setOptions({drawTitle: true})
osmd.render()
```
 it becomes visible

**Comment by sschmidTU** [comment]
That is because fingerings are only added during Vexflow note generation.
I suppose we could add them any time this option is turned on, or always add them and make them invisible if turned off. I'll see if this can be easily accomplished.
For now, you'll have to reload the sample.

**Comment by dedan** [comment]
Ok, thank you very much for your quick response.  Please keep me updated if you make any progress on that
