### ISSUE TITLE
sometime slur is not render

### ISSUE THREAD

**Issue by gloddream** [opensheetmusicdisplay/opensheetmusicdisplay#651]
when there is  a tie in a slur，the slur is not render。
image of musicxml：
![image](https://user-images.githubusercontent.com/16585500/72658990-acf82080-39f3-11ea-8ece-bd2706565538.png)

image of osmd render：
![image](https://user-images.githubusercontent.com/16585500/72658996-c305e100-39f3-11ea-895b-d40de481ad03.png)

**Comment by sschmidTU** [comment]
osmd.Drawer.drawLine was intended to be used by OSMD only.
However, this highlighted some TODOs with the new music page generation method.

So I added a method **DrawOverlayLine** for the user to draw:
```ts
osmd.Drawer.DrawOverlayLine(start: PointF2D, stop: PointF2D, musicPage: GraphicalMusicPage,
                           color: string = "#FF0000FF", lineWidth: number = 0.2)
```
you can use it like this for example (javascript):
```js
let start, end, startNote = 0; // only do this once if testing in the console

startNote = osmd.graphic.measureList[6][0].staffEntries[0].graphicalVoiceEntries[0].notes[0];
start = startNote.PositionAndShape.AbsolutePosition; 
end = osmd.graphic.measureList[6][0].staffEntries[1].graphicalVoiceEntries[0].notes[0].PositionAndShape.AbsolutePosition;

osmd.Drawer.DrawOverlayLine(start,end,startNote.ParentMusicPage, "red", 1.5); // GraphicalNote.ParentMusicPage is also a new method, returning parentVoiceEntry.parentStaffEntry.parentMeasure.parentMusicSystem.Parent;
```

![image](https://user-images.githubusercontent.com/33069673/73009575-21c2c480-3e11-11ea-9498-5ca3d83e9fb3.png)

This method now works across MusicPages, for example for measure 3 and 7 here:

![image](https://user-images.githubusercontent.com/33069673/73009672-4a4abe80-3e11-11ea-8055-396dadf3cbb1.png)

**Comment by sschmidTU** [comment]
Sorry, i got a cached Github page with the old issue title and description.
Some slurs not being rendered already has its own issue, #539.
