### ISSUE TITLE
Bad beaming layout when zooming

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#655]
An die ferne Geliebte:
144%
![grafik](https://user-images.githubusercontent.com/17180665/72611501-99cd4e00-392a-11ea-8512-07134f9a971d.png)

172%
![grafik](https://user-images.githubusercontent.com/17180665/72611614-dbf68f80-392a-11ea-8e84-e2a1433e0a88.png)

207%
![grafik](https://user-images.githubusercontent.com/17180665/72611701-119b7880-392b-11ea-8450-983d48a0449f.png)

Must be a VexFlow Bug. 
I'm pretty sure what the reason could be:
The Beams for the VexFlow Measure are layouted for the minimum length.
Then when we change the measure length to the final one, the beam slopes are not recalculated.
So the beams are simply elongated in x-direction with the initial slope.
The steeper the slope the more such misplacement happens.
Solution: don't use the stored slope, but store the endpoint instead. Leave y-value always the same and only recalculate x value of it.

**Comment by sschmidTU** [comment]
447c4f9a22be4348356761498c50a1f0a916894b fixes this, but we need to see how much performance this costs with multiple re-renders.
Visual regression test shows no diffs.
I'll do the new OSMD release firs.
