### ISSUE TITLE
Error handling ending with type discontinue

### ISSUE THREAD

**Issue by compilelife** [opensheetmusicdisplay/opensheetmusicdisplay#656]
check this: http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-ending.htm#kanchor500

So "discontinue" should not add an instruction [here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/53df5ddd1b4259178364b85b51c1176c88cf793a/src/MusicalScore/ScoreIO/MusicSymbolModules/RepetitionInstructionReader.ts#L108): 

```ts
if (type === "stop" || type === "discontinue") {//Should we ignore type === "discontinue" branch?
            const newInstruction: RepetitionInstruction = new RepetitionInstruction(this.currentMeasureIndex, RepetitionInstructionEnum.Ending,
                                                                                    AlignmentType.End, undefined, endingIndices);
            this.addInstruction(this.repetitionInstructions, newInstruction);
          }
```

**Comment by sschmidTU** [comment]
We'll look into this.

From the MusicXML manual:
>The stop and discontinue types are associated with the right barline of the last measure in an ending. Stop is used when the ending mark concludes with a downward jog, as is typical for first endings. Discontinue is used when there is no downward jog, as is typical for second endings that do not conclude a piece.

**Comment by sschmidTU** [comment]
You were right, discontinue has no downward jog, as in Musescore.
Removing the `|| type === "discontinue` did the job.

Saltarello.xml, bar 9:

Musescore:
![image](https://user-images.githubusercontent.com/33069673/76350607-5bda1e00-630c-11ea-85e4-8cd6824d60e0.png)

OSMD 0.73:
![image](https://user-images.githubusercontent.com/33069673/76350705-7dd3a080-630c-11ea-8a78-c3360e6cb9a5.png)

fixed OSMD:
![image](https://user-images.githubusercontent.com/33069673/76350960-f0dd1700-630c-11ea-8273-3f65536eba54.png)
