### ISSUE TITLE
Rendering n Single Measures as Separate OSMD Instances neatly next to each other

### ISSUE THREAD

**Issue by byebb** [opensheetmusicdisplay/opensheetmusicdisplay#658]
I am developing an application which requires me to render each measure of a piece separately so that I can flexibly position each measure on the screen.

Assume we have [this sheet music](https://musescore.com/classicman/scores/56800): 

Visualizing this within a single OSMD instance would like this:

![image](https://user-images.githubusercontent.com/4288893/72806682-f647aa80-3c55-11ea-82b9-292fc7a728a3.png)

I use the [GeneralObjectExporter from music21](https://web.mit.edu/music21/doc/moduleReference/moduleMusicxmlM21ToXml.html) to extract the single measures as separate musicxml sheets so that I can render each measure as a separate OSMD instances. With this, I try to achieve visual entities that I can display and transition on the screen independent of each other:

![image](https://user-images.githubusercontent.com/4288893/72807573-006aa880-3c58-11ea-9d85-2b248f154e58.png)

I want to display each measure now with the same visual options, so that I can display them neatly next to each other as if they have been rendered in a single OSMD instance.
I assume, one of the biggest issues are the additional articulation elements and diminiuendo or crescendo, which require additional space. I do not care about overlapping, if that would be the other option.

I could not find any settings of [OSMD's engravingRules](https://opensheetmusicdisplay.github.io/classdoc/classes/engravingrules.html#betweenstaffdistance) which allows me to force the distance between the two staffs in this example. 

In addition, I would like to remove the clefs and time signature, and only show it for the first measure, similar to this:

![image](https://user-images.githubusercontent.com/4288893/72807779-6d7e3e00-3c58-11ea-9be2-eef8f0fee596.png)

Can you provide me some further information, on how I could 

1.: Force a common distance (incl. margin, padding) so that I can place all measure neatly next to each other?
2.: Use settings to remove unwanted elements (Clefs, Time & Key Signature)?

Any other ideas, on how I could achieve what I want?

edit:
`this.fixStafflineBoundingBox = false; // TODO temporary workaround`

I found this line [in the EngravingRules class](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/4068565/src/MusicalScore/Graphical/EngravingRules.ts#L443). Could this be used (if set to true) to fix the described issue?

**Comment by matt-uib** [comment]
dear @byebb thanks for your question and good description.
As OSMD is a Layout-Engine for complete sheets, it would not make very much sense to adapt for your use case. It would be quite some effort for us and i don't think many people will need the same options.
For me it sounds, as there would be a better way for what you are planning to do. So my question would be why you first want to split a musicXML into its measures to render them then finally next to each other again.
If you actually only want to know the coordinates of each measure: we have all coordinates of nearly all objects in the BoundingBox object which is a member in our GraphicalObjects (like each measure, staffentry, note...)
If you use our layout engine only for single measures, each measure will be layouted on its own and will have different vertical size - but switching off the layouting will lead to collisions of objects at some positions (e.g. low note in right hand staff - high note in left hand staff).
So maybe you could tell more what you finally want to achieve and then we might come to a much better solution (you can also email me, if it should not be public: m.uiberacker@phonicscore.com)

**Comment by sschmidTU** [comment]
I agree with @matt-uib, if you give 13 OSMD instances 13 individual MusicXML sheets, you will get 13 different (complete) sheets rendered. OSMD isn't made for not rendering sheets.

You can already make the time signature invisible though (`print-object="no"`).
Maybe we could do the same for clef and key signature.
Here's a sample:
[invisible_time_key_signature_clef.musicxml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4091516/invisible_time_key_signature_clef.musicxml.txt)

>edit:
this.fixStafflineBoundingBox = false; // TODO temporary workaround
>
> I found this line in the EngravingRules class. Could this be used (if set to true) to fix the described issue?

You can set this via `osmd.EngravingRules.FixStafflineBoundingBox = true`, but it will only lead to less wasted space below some systems with multiple stafflines (e.g. piano), it won't fix your issue.

**Comment by matt-uib** [comment]
If you don't care about the image output size, you can simply set:
EngravingRules.StaffDistance = 30 (or more)
EngravingRules.BetweenStaffDistance = 30 (or more)
Here what comes out for 20:
![grafik](https://user-images.githubusercontent.com/17180665/72814227-fbf8bc80-3c64-11ea-9dd9-dd4d3dd995b3.png)
Still there are differences from system to system, so a little change in the OSMD code would still be required, to really always have the staves at equal y-positions per system.

**Comment by ifredom** [comment]
> I am developing an application which requires me to render each measure of a piece separately so that I can flexibly position each measure on the screen.
> 
> Assume we have [this sheet music](https://musescore.com/classicman/scores/56800):
> 
> Visualizing this within a single OSMD instance would like this:
> 
> ![image](https://user-images.githubusercontent.com/4288893/72806682-f647aa80-3c55-11ea-82b9-292fc7a728a3.png)
> 
> I use the [GeneralObjectExporter from music21](https://web.mit.edu/music21/doc/moduleReference/moduleMusicxmlM21ToXml.html) to extract the single measures as separate musicxml sheets so that I can render each measure as a separate OSMD instances. With this, I try to achieve visual entities that I can display and transition on the screen independent of each other:
> 
> ![image](https://user-images.githubusercontent.com/4288893/72807573-006aa880-3c58-11ea-9d85-2b248f154e58.png)
> 
> I want to display each measure now with the same visual options, so that I can display them neatly next to each other as if they have been rendered in a single OSMD instance.
> I assume, one of the biggest issues are the additional articulation elements and diminiuendo or crescendo, which require additional space. I do not care about overlapping, if that would be the other option.
> 
> I could not find any settings of [OSMD's engravingRules](https://opensheetmusicdisplay.github.io/classdoc/classes/engravingrules.html#betweenstaffdistance) which allows me to force the distance between the two staffs in this example.
> 
> In addition, I would like to remove the clefs and time signature, and only show it for the first measure, similar to this:
> 
> ![image](https://user-images.githubusercontent.com/4288893/72807779-6d7e3e00-3c58-11ea-9be2-eef8f0fee596.png)
> 
> Can you provide me some further information, on how I could
> 
> 1.: Force a common distance (incl. margin, padding) so that I can place all measure neatly next to each other?
> 2.: Use settings to remove unwanted elements (Clefs, Time & Key Signature)?
> 
> Any other ideas, on how I could achieve what I want?
> 
> edit:
> `this.fixStafflineBoundingBox = false; // TODO temporary workaround`
> 
> I found this line [in the EngravingRules class](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/4068565/src/MusicalScore/Graphical/EngravingRules.ts#L443). Could this be used (if set to true) to fix the described issue?

**I think you have the same needs. You need to divide a score into pieces for practice. You can try this**

![image](https://user-images.githubusercontent.com/13759936/81165375-71925980-8fc4-11ea-908c-0b85ce1703a0.png)

**Comment by AlbertHart** [comment]
I have some code which renders a score - puts the rendering into one frame, then renders the same or another score and lets you view or print both at the same time.

Would this be of help?
