### ISSUE TITLE
Easily access GraphicalNote from Note/Cursor: create Dictionary

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#660]
PR #659 rightfully mentions that finding a GraphicalNote from a Note is not straightforward,
especially given that Cursor.NotesUnderCursor returns Note[] and not GraphicalNote[].

However, we intentionally left out a reference from a Note to its GraphicalNote to modularize OSMD, and make the music data model completely independent from the graphical model. So, you could load a sheet, but never render it or even use graphical classes (e.g. for a pure audio player).

The easiest and most efficient solution under these constraints is to create a hashmap from Note to GraphicalNote in a class belonging to the graphical model.
We could do the same for other object-graphical pairs like VoiceEntry and GraphicalVoiceEntry.

To make this mapping more visible, we could add a static method `GraphicalNote.FindFromNote(note: Note): GraphicalNote` for example, and/or in the Cursor.

**Comment by praisethemoon** [comment]
I would say, when rendering each note, vexflow would generate a unique ID for the node's DOM element. Since each `GraphicalNote` References a `Note`, we can add an `uid: string` field in `Note` and assign the generated ID to that field. Then we create the mapping in the dictionary, what do you think?

**Comment by sschmidTU** [comment]
That would work well, except that we then have to do it as a dependency on Vexflow and in a VexFlow class (and all of them are in a VexFlow sub directory in the Graphical directory), again because we want to separate the dependencies of the sheet model, graphical model, and VexFlow-specific adaptations.

**Comment by praisethemoon** [comment]
Alright then, does `Note` have any information that could be combined for hashing? If not maybe something as little as this https://github.com/ai/nanoid would do!

When a `GraphicalNote` is created, it sets the value on the Dictionary mapping the source note with itself. How about that?

**Comment by sschmidTU** [comment]
Yeah, i definitely wanted to do the mapping when the graphical notes are created.
It would be unfortunate though if we had to add a dependency just for unique identifiers.
Maybe we can just use a WeakMap:
https://stackoverflow.com/a/35306050/10295942
Or simply a Dictionary in the same style.

**Comment by praisethemoon** [comment]
Now that's something new! Glad you shared that with me 😄  Where do you think is the best place/class to store the dict?

**Comment by sschmidTU** [comment]
Probably in the GraphicalMusicSheet, which contains all graphical elements, and then we can access it with static methods from there or from GraphicalNote or Cursor.

**Comment by praisethemoon** [comment]
If you did not start working on this already, I would love to get it done! Maybe this weekend 😄

**Comment by sschmidTU** [comment]
Sure, that would be great, thanks!
Just remember, no graphical references in non-graphical classes, and no Vexflow references in Graphical classes (excluding the Vexflow folder) ;)

**Comment by sschmidTU** [comment]
@praisethemoon do you still plan on working on this? Since this was requested again in #659 ;)

**Comment by ice6** [comment]
If Note and GraphicNote is one-to-one mapping relationship, I think there is no need to add a dictionary layer just because code style preference.

GraphicNote depends on Note, if we don't want to make circular dependency and make the layer separated, just design a model / view pattern to follow, will make the code more maintainable.

for example, add a `view` property to model, when we construct view, set the `view` property of corresponding model as view instance.

just follow a consistent pattern, the code will be more maintainable.

how do you think, @sschmidTU ?

**Comment by matt-uib** [comment]
@ice6 you are right of course on the thoughts of model-view.  
But at the design phase back then we thought about use cases that don't even have a view and therefore we wanted to not have an empty reference in every object of the datamodel. But as we never implemented such a use case up to now we can really think once more about adding a reference to the graphicalObject (=view).

**Comment by ice6** [comment]
Note has not only sound, it has represention, it has view. :)

Adding the reference is OK for me as theyh have strong relationship.

Follow some pattern to make the code maintainable will be ok.

**Comment by sschmidTU** [comment]
There is now the static `GraphicalNote.FromNote(note: Note, rules: EngravingRules)`,
so you can easily get the GraphicalNote like this:
`const gNote = GraphicalNote.FromNote(note, osmd.rules);`

**Comment by sschmidTU** [comment]
There is an even easier method now:
`const gNote = osmd.rules.GNote(note)`
will give you the GraphicalNote from a Note reference.
