### ISSUE TITLE
OSMD embedded viewer options

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#661]
- [X] change embedded to showDebugControls (default = false -> don't show debug controls)
- [X] add compactMode
- [X] add measure range (measureRangeStart, measureRangeEnd)
- [X] pageFormat
- [ ] showPageFormatControl
- [ ] showExportPdfControl
- [X] backendType (defaut=svg)

**Comment by sschmidTU** [comment]
TODO:
- [ ] add above options as URL parameters
- [ ] check that we don't have null-access on github.io demo HTML elements because they don't exist in that index.html
- [ ] give a warning when you try to generate a pdf from canvas backend (only works on SVG for now)

**Comment by sschmidTU** [comment]
openUrl works with any URL now, just needs an `&endUrl` at the end now.
Can be tested like this:
http://localhost:8000/?openUrl=OSMD_function_test_all.xml&endUrl

**Comment by sschmidTU** [comment]
The special embedded zoom controls are broken for now because of disabling the debug controls (visibility hidden), will take a look. Ideally, these controls should probably be generated at runtime anyways, otherwise they can be undefined if visibility=hidden.

**Comment by sschmidTU** [comment]
showZoomControl works again, added showExportPdfControl and showPageFormatControl.
Also, elements that should not be shown aren't visible while the page is loading anymore.
showControls by default shows all three controls: zoom/pdf/format

unfortunately, i didn't figure out how to redistribute the space in the column when one or more of the controls aren't shown. may be a limitation of the ui x column grid container.

tests:

// show zoom/pdf/pageformat controls:
http://localhost:8000/?embedded=1&showHeader=0&debugControls=0&showControls=1&zoom=1.0

show zoom/export controls:
http://localhost:8000/?embedded=1&showHeader=0&debugControls=0&showControls=1&showExportPdfControl=0

show zoom/pdf controls:
http://localhost:8000/?embedded=1&showHeader=0&debugControls=0&showControls=1&showZoomControl=1&showPageFormatControl=0&showExportPdfControl=1
