### ISSUE TITLE
Add more sheet music to Sheet Music Tester

### ISSUE THREAD

**Issue by bukaznik** [opensheetmusicdisplay/opensheetmusicdisplay#67]
use

http://openmusicscore.org/index.php?option=com_content&view=categories&id=79&Itemid=531

http://www.gutenberg.org/browse/categories/4 (for downloading see http://www.gutenberg.org/wiki/Gutenberg:Information_About_Robot_Access_to_our_Pages and http://www.gutenberg.org/MIRRORS.ALL)

as sample sheet music sources.

**Comment by bukaznik** [comment]
a total of approx. 100 sheet music files would be fine. all sheet music needs to be public domain.

**Comment by sschmidTU** [comment]
I don't think we need 100 sample xmls in the demo, would also increase the size of the repository by a lot.
We can always add a few samples that add something new to what we already have, like a string quartet.
Correct me if i'm wrong.
