### ISSUE TITLE
Export PNG/SVG

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#670]
Feature: use OSMD to export a PNG (given width, height), or SVG,
to a file or on a REST-Server.

This is an often-requested feature (#523, #491, #437).
It's also useful for building a script or server that uses OSMD to generate score image files.

There is already the [feat/exporting](/opensheetmusicdisplay/opensheetmusicdisplay/tree/feat/exporting)-branch ([this commit](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/c0e8947d4b42d2a7b810de34f6472e93fc047cd0)), which allows you to download the SVG in the browser.

However, it would be useful to be able to save the file locally via node.js or to have a local server that gives you the files via GET request.
The node.js script is now on the feature branch.

The first step for PNG export, already done, was being able to set the background color of the canvas, because the canvas image always exported with a transparent background color (the white background in the demo comes from the browser/div/style).

So there's now an OSMDOption `pageBackgroundColor: string`, e.g. `"#FFFFFF"` is white, or `#FF000088` is a half-transparent red.
It can also be used as a parameter for the demo: `localhost:8000/?pageBackgroundColor=E1E1E1`
(the `#` has to be omitted for the url parameter)
![image](https://user-images.githubusercontent.com/33069673/74263965-212a9900-4d00-11ea-8821-ae1a6bcd09d0.png)
`http://localhost:8000/?showHeader=0&debugControls=0&backendType=canvas&pageBackgroundColor=E1E1E1`

**Comment by sschmidTU** [comment]
There's now a branch `feat/export-png-svg-and-diff-images` where you can run `npm run generatePNG` to save a PNG of a score locally.
The local webserver has to be running (`npm start`).
It will be extended to export multiple files or folders, e.g. by command line argument.
This will be a basis for the RESTful node server returning these per GET request.

Reference for navigation error ("Execution context was destroyed"):
https://github.com/puppeteer/puppeteer/issues/3323

Reference for Puppeteer screenshot (not needed for now because we can export the canvas dataUrl):
https://gist.github.com/malyw/b4e8284e42fdaeceab9a67a9b0263743

**Comment by sschmidTU** [comment]
You can now generate PNGs without using the browser at all, purely in Nodejs, and it's about twice as fast!
See the generatePNG and generate:* npm scripts.

This means we don't need puppeteer as devDependency anymore, which downloaded >100MB for Chromium.
install it as dev dependency locally if you want to test generatePNG:puppeteer*.

This could enable testing without a headless browser in Karma as well.

browserless PNG generation is about twice as fast as puppeteer,
and has a way faster startup (about 4x as fast for single sample):
```sh
time npm run generatePNG:puppeteer:single # generate 1 PNG for 1 sample (Beethoven)
real    0m33.656s
user    0m1.044s
sys     0m0.630s

time npm run generatePNG:single # same as above, with --debug for fairness of console.logs usage
real    0m5.320s
user    0m3.614s
sys     0m0.416s

time npm run generatePNG:puppeteer # 41 sheets
real    2m32.108s
user    0m4.207s
sys     0m2.006s

time npm run generate:current # 41 sheets, browserless, with debug output
real    1m18.662s
user    1m1.342s
sys     0m3.048s
```

**Comment by sschmidTU** [comment]
The script now generates pages with the exact width/height given.
They may be cut off though if a page is too small to fit a single system,
so we could still add some optional logic to auto-adjust zoom if the dimensions are too small for a page.

**Comment by hallvors** [comment]
The "server-side SVG export" feature did not land yet, it seems? Is the solution on this branch still the way to do it?
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/compare/feat/exporting

**Comment by sschmidTU** [comment]
In principle yes, the branch is just severely outdated. Maybe we can update it, though we also have some other important priorities right now. Would you be able to do it, hypothetically?

**Comment by sschmidTU** [comment]
Actually, looking at the branch, it's a very simple method, i thought it needed merging.
Looks like it should be simple to integrate into develop.

**Comment by hallvors** [comment]
Maybe I could have a go, I might use it for a project I'm trying to figure out how to do at the moment. I am rather new to OSMD though and definitely don't feel like I know my way around anything yet :)

**Comment by hallvors** [comment]
(At least I have verified that doing `git merge develop` gets the branch up to date without conflicts. I'm obviously not allowed to push the result ;))

**Comment by sschmidTU** [comment]
Yes, it seems like the method should work as well, i'll see about merging it later (maybe tomorrow)!

**Comment by hallvors** [comment]
In addition to what's on that branch it would require some code similar to test/Util/generateImages_browserless.js in order to use this server-side, I assume?

**Comment by sschmidTU** [comment]
Oh, yes, the rendering in itself needs these browser 'hacks' (simulating a canvas context in nodejs).
I assume you do want to render serverside. I think integrating the SVG export into the generateImages script as an option should not be too difficult either, will just need some refactoring.

**Comment by hallvors** [comment]
I got batch generation of SVG images working:
![Skjermbilete_2021-01-13_00-47-34](https://user-images.githubusercontent.com/120136/104388198-04629b00-5539-11eb-9804-4944d55d4a03.png)

**Comment by sschmidTU** [comment]
Fantastic! Would you kindly open a pull request or share the code? Did you modify the existing node script?

**Comment by hallvors** [comment]
Yes, I copied and modified. I will share shortly, but will try to figure out if there's more stuff from the canvas version that's obsolete now first. Cleanup :)

**Comment by hallvors** [comment]
Some of those SVG files are almost 20MB - wow :) 
I want to know if generating SVGs server-side will get me better performance in the web app, seems likely. And it's going to be kids sheet music, so probably never 20MB. Still perhaps I should look at gzipping them.. :)
Good night, please review https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/932 at your leisure (and get some sleep first if you're in a European tz..).

**Comment by sschmidTU** [comment]
It wouldn't surprise me if Actor - Prelude is 20MB, that's an abnormally large xml, an orchestral score. You'll probably rarely if ever need to render something like that. Yes, I will review the PR a bit later, but at my pleasure ;)

**Comment by sschmidTU** [comment]
SVG export is now integrated into `generateImages_browserless.js`!

new command line option `png|svg` (imageFormat):
```sh
usage:
node test/Util/generateImages_browserless.js osmdBuildDir sampleDirectory imageDirectory svg|png [width|0] [height|0] [filterRegex|all|allSmall] [--debug|--osmdtesting] [debugSleepTime]
```

**Comment by sschmidTU** [comment]
Once again thanks to @hallvors for implementing SVG export in the first place!

**Comment by hallvors** [comment]
You are very welcome, it was not much "implementation" since all the hard stuff was done already :)

**Comment by geniot** [comment]
> SVG export is now integrated into `generateImages_browserless.js`!
> 
> new command line option `png|svg` (imageFormat):
> 
> ```shell
> usage:
> node test/Util/generateImages_browserless.js osmdBuildDir sampleDirectory imageDirectory svg|png [width|0] [height|0] [filterRegex|all|allSmall] [--debug|--osmdtesting] [debugSleepTime]
> ```
It should be generateImages_browserless.**mjs** 
I just tried it. Should a file a bug for the following output?
![image](https://user-images.githubusercontent.com/199748/168249277-eddd639d-3ddb-445b-a84f-5a2db144bc61.png)

**Comment by geniot** [comment]
> The script was renamed. You could open an issue. Does it only happen in the script, not in the demo? Can you share the musicxml file? (or a smaller one that has the same effect?) I'm guessing it has something to do with the 12/8 time signature.
[soul_melody.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/8686324/soul_melody.zip)
Let me try the demo and changing the time signature. I also plan to fix it and create a pull request if I find how to fix it. Thanks.
