### ISSUE TITLE
feature request: tempo for measure

### ISSUE THREAD

**Issue by Jack-Works** [opensheetmusicdisplay/opensheetmusicdisplay#680]
![image](https://user-images.githubusercontent.com/5390719/75443064-9d2d0e00-599b-11ea-9b93-88c1dd3fd579.png)

Now: every tempo symbol displayed at the first measure. (tempo=100 then temp=180)

**Comment by sschmidTU** [comment]
We didn't get to this yet, sorry.
For now, we could at least only show the first tempo indication, if we can't show multiple ones yet.
But hopefully, drawing the tempo indication over the measure it was given for should be relatively simple as well.

**Comment by sschmidTU** [comment]
There is now an option to not draw metronome marks:
```js
osmd.setOptions({drawMetronomeMarks: false});
// or more simply:
osmd.EngravingRules.MetronomeMarksDrawn = false;
```

this is merged on develop, new release will hopefully come very soon.

**Comment by sschmidTU** [comment]
Maybe creating metronome marks per measure will not be much harder, fingers crossed for next release.

**Comment by sschmidTU** [comment]
This is fixed, see OSMD Function Test - Metronome Marks.
![image](https://user-images.githubusercontent.com/33069673/89950800-a00a7b00-dc2a-11ea-8be4-5939809294ca.png)
