### ISSUE TITLE
I want you to merge ’feat/noLineBreaksSingleSystem’ into ‘develop’.

### ISSUE THREAD

**Issue by tsugumi** [opensheetmusicdisplay/opensheetmusicdisplay#681]
I’m using horizontal one line score. I hope to add the rendering option for line breaking on/off.

**Comment by bneumann** [comment]
Please submit a pull request. I presume the branch mentioned is in your personal repo or fork.

**Comment by bneumann** [comment]
A sorry, just saw that it is one of @sschmidTU. No pr needed

**Comment by tsugumi** [comment]
OK. Thanks.

**Comment by sschmidTU** [comment]
Yes, we can make an OSMDOption for this. I'll look into it soon.

**Comment by sschmidTU** [comment]
done

**Comment by sschmidTU** [comment]
To enable this, you have to set the option 'renderSingleHorizontalStaffline':
```js
osmd.setOptions({ renderSingleHorizontalStaffline: true })
```

Or you can simply test this by running the local demo and navigating to:
http://localhost:8000/?horizontalScrolling=1&singleHorizontalStaffline=1
