### ISSUE TITLE
layered canvas problem

### ISSUE THREAD

**Issue by tsugumi** [opensheetmusicdisplay/opensheetmusicdisplay#682]
I'm layering another canvas over an osmdCanvas.
But current develop branch version, after more than one times rendering the osmdCanvas, layered canvas is deleted.
So I have to add canvas element again.
That can't be helped?

**Comment by tsugumi** [comment]
Please tell me about the current status. I have been feeling inconvinience this problem. 
I would like you not to be deleted another canvas at the time of drawing the osmdCanvas.

**Comment by sschmidTU** [comment]
We could probably add an option to not clear the canvas on re-rendering. Two questions:
1. Why do you render the same piece multiple times with the same overlay?
2. Why don't you just add your canvas layer again?

**Comment by tsugumi** [comment]
I'm using another canvas for real time drawing. 
All canvases are real time zooming.
If the canvas is deleted, to redraw another canvas must be using stored status.
It is cumbersome processing.

**Comment by sschmidTU** [comment]
I'm still not sure i fully understand your problem.
For OSMD to render again, it has to clear everything it has rendered before.
If you add extra graphical elements to OSMD's canvas, how is OSMD supposed to know what you added and what was from OSMD? We have to delete all child elements.
The much easier solution for you is probably to draw your additions on a separate canvas that you put over OSMD.

**Comment by h-sug1no** [comment]
> The much easier solution for you is probably to draw your additions on a separate canvas that you put over OSMD.

It's like this...

![image](https://user-images.githubusercontent.com/59550999/116527732-fb45e000-a915-11eb-9940-b125cd27f3ca.png)

- https://jsfiddle.net/ba1quyzp/28/
- canvas id="demo-ui-canvas": over an osmd image
  - pls select Renderer:Canvas by hand.(I couldn't reach the method to select canvas by default)
  - demo-ui-canvas is not deleted after osmd rendering (by {Re-Render or clear button or other UI))

**Comment by sschmidTU** [comment]
Yes, that's what i had in mind, thanks for providing example code @h-sug1no !

**Comment by sschmidTU** [comment]
Yes, that's what i had in mind, thanks for providing example code @h-sug1no !

**Comment by tsugumi** [comment]
Thank you for your advice. I used following code to link these sizes and positions.
But after this, I'm thinking of writing the code like your way.
And I will think about synchronization of the canvases measurements separately.

`<div id="osmdCanvas" style="position: relative;">`                                   
 `<canvas id="mycanvas" style="position: absolute; left: 0;"></canvas>`
`</div>`
