### ISSUE TITLE
The graphicalTies end/startNote's informations

### ISSUE THREAD

**Issue by tsugumi** [opensheetmusicdisplay/opensheetmusicdisplay#688]
If I want to know a tie start note's verticalGraphicalStaffEntryContainers' index from the end of a tie note, how can I get it from a graphicalTies end/startNote.

**Comment by sschmidTU** [comment]
I'm not sure that i understand the situation exactly. Which objects do you have access to, and which object do you want to get?
You can get the verticalGraphicalStaffEntryContainer from a graphicalNote via graphicalNote.parentVoiceEntry.parentStaffEntry.parentVerticalContainer.
If you have the container, you can iterate through the container's elements and check if they're equal to your note, to get the note's index in the container.

**Comment by tsugumi** [comment]
It is just wanted. Thank you.
I want to know the weather or not the note is the start of tie note. hasTie() indicates only weather or not the notes has ties.  For example, in case another voices notes located between tied notes, I want to know the start note's index from the end note.

**Comment by sschmidTU** [comment]
Maybe you can check the GraphicalStaffEntry.GraphicalTies:
```js
// use better checks, null checks etc. of course
if (graphicalNote.parentVoiceEntry.parentStaffEntry.GraphicalTies.length > 0 &&
    graphicalNote.parentVoiceEntry.parentStaffEntry.GraphicalTies[0].startNote === graphicalNote) {
  // graphicalNote is the start of a tie note
  // note: === may not always work for GraphicalNotes, not sure
}
```

otherwise I think from a GraphicalStaffEntry, you can use findEndTieGraphicalNoteFromNote(tieNote: Note).
```js
if (graphicalNote.parentVoiceEntry.parentStaffEntry.findEndTieGraphicalNoteFromNote(graphicalNote.sourceNote) !== undefined) {
  // graphicalNote is the start tie note
} else {
  // graphicalNote is the end tie note
}

**Comment by tsugumi** [comment]
Thank you. It is very helpful.
But it seems that 2nd example is not working well. 
I have to know whether or not a note is an attack note (the most first note of ties sequence).

**Comment by sschmidTU** [comment]
So, does the first example work? what's the problem with the second?

**Comment by tsugumi** [comment]
I'm using opensheetmusicdisplay as builded plain JavaScript.

It seems that the first example indicates whether or not the note is a start note of a tie correctly.
(I don't know if the note is the most first note of ties sequence.)

The second example, I'm using as follows.

```JavaScript
var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdCanvas", {backend:"canvas"});
...
// i, j, jj, kk are iterators.
...
if (osmd.graphic.verticalGraphicalStaffEntryContainers[i].staffEntries[j].graphicalVoiceEntries[jj].notes[kk].parentVoiceEntry.parentStaffEntry.findEndTieGraphicalNoteFromNote(osmd.graphic.verticalGraphicalStaffEntryContainers[i].staffEntries[j].graphicalVoiceEntries[jj].notes[kk].sourceNote) !== undefined) {
  // When sourceNote is not a rest. Allways return an object.
} else {
  //
}
...
...
```

Am I using is it the wrong way?

**Comment by tsugumi** [comment]
Off course, I know a note is the attack note if ,within recent 2 measures, there isn't the same pitch note or the same pitch note's graphicalTies hasn't that as the end note.

**Comment by sschmidTU** [comment]
Yes. So it seems at least one of the solutions works.
Can we close this or do you have further questions?

**Comment by tsugumi** [comment]
I agree with you. Thank you so much.
