### ISSUE TITLE
Vexflow Rendering is blurry on retina display

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#69]

**Comment by sebastianhaas** [comment]
SVG support was added in #154, apparently also the blurriness of the canvas demo was removed. Still have to investigate why that is the case.

**Comment by muratcorlu** [comment]
Maybe we should fix by setting canvas bigger and make it correct size by styling again: https://coderwall.com/p/vmkk6a/how-to-make-the-canvas-not-look-like-crap-on-retina

**Comment by bneumann** [comment]
Is this only a retina display issue?

**Comment by muratcorlu** [comment]
I think it's an issue on all high density screens.

**Comment by matt-uib** [comment]
It works fine in SVG mode, which is now default mode.
