### ISSUE TITLE
octaveShift will lost if the  it cross a mount of measures.  octaveShift will only show the begining  and end, missing middle part .  

### ISSUE THREAD

**Issue by DavidQinqianWu** [opensheetmusicdisplay/opensheetmusicdisplay#693]
OSMD seeems when calculate octaveShift will lost the middle part (this middle part means the whole stave is under octaveShift). In `MusicSheetcalculator.ts` Line 1916, the `sourceMeasure.staffLinkedExpressions[staffIndex]`, seems only have value that current stave, but if the octaveShift cross very long in XML, and those measures are rendered multi lines, and those measures are rendered in different lines will lost the OS.
<img width="1188" alt="截屏2020-03-18下午5 57 29" src="https://user-images.githubusercontent.com/23088138/76948383-f9070900-6941-11ea-8c82-5fe41e8b3244.png">  (this is the  score supposed). 

and this is the score that  osmd render
![截屏2020-03-18下午6 03 16](https://user-images.githubusercontent.com/23088138/76948955-ca3d6280-6942-11ea-9d57-89f159e51d49.png)

the measure 4,5,6 should  has octaveShift Sign, but seems they are the new line and OSMD will judge this stave(measure 4,5,6 ) don't have octaveShift tag...

**Comment by sschmidTU** [comment]
Can you add the musicxml file for this sample? Then I'll reopen.
Anyways, this will probably be fixed in #1378.
