### ISSUE TITLE
cursor not moving?

### ISSUE THREAD

**Issue by DetegiCE** [opensheetmusicdisplay/opensheetmusicdisplay#694]
I'm trying to move my cursor using timestamp
    
```
function startSong() {
var openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("main-div");
openSheetMusicDisplay.cursor.reset()
const its = openSheetMusicDisplay.cursor.iterator;

var timestamp = new Date().getTime();
  while(!its.endReached) {
    var temptime = new Date().getTime();
    if(temptime-timestamp > its.currentTimeStamp.RealValue*4000) {
      openSheetMusicDisplay.cursor.next();
    }
  }
} 
```

The cursor what I see in screen does not move but iterator is moving.

How can I fix this error?

**Comment by sschmidTU** [comment]
You need to call `openSheetMusicDisplay.cursor.show()` (before calling next), otherwise the cursor will never be displayed.

**Comment by DetegiCE** [comment]
@sschmidTU 

I have added

```
console.log(its);
console.log(temptime-timestamp);
openSheetMusicDisplay.cursor.show();
```

between if-statement and openSheetMusicDisplay.cursor.next();

but still it does not work...

![notworking](https://user-images.githubusercontent.com/26007107/77203041-e0117a00-6b32-11ea-80d3-c76b2b87f452.gif)

**Comment by sschmidTU** [comment]
interesting. of course you only need to call cursor.show() once, unless you call cursor.hide() after that.
what happens when you type osmd.cursor.next() in the browser console?
Does cursor.iterator.CurrentVisibleVoiceEntries() change between steps?
Is cursor.cursorElement not null?

As you can see when you try the [public demo](https://opensheetmusicdisplay.github.io/demo/), all of the cursor functions work without problem, so there must be something in your code.

**Comment by DetegiCE** [comment]
@sschmidTU 

Thanks for your help.
I have executed my code in demo page using browser console.

```
function startSong() {
  osmd.cursor.reset();
  var its = osmd.cursor.iterator;
  var timestamp = new Date().getTime();
  console.log("before start: ",its.CurrentVisibleVoiceEntries().length)
                  
  while(!its.endReached) {
    var temptime = new Date().getTime();
    if(temptime-timestamp > its.currentTimeStamp.realValue*4000) {
      console.log(its);
      console.log(temptime-timestamp);
      console.log(its.CurrentVisibleVoiceEntries())
      osmd.cursor.next();
    }
  }
 }
```

The console log normally printed.
However the cursor is not moving and when the program ends, the cursor teleports to the end.

Sorry for bothering again.

**Comment by sschmidTU** [comment]
I think you need an `await sleep` in your while loop, otherwise you have an inifinite while loop that runs on 100% of process/processor capacity every nanosecond or so.

**Comment by DetegiCE** [comment]
@sschmidTU 
I added `await sleep(125);` next to ``osmd.cursor.next()`` and it worked!

Thanks for your help!
