### ISSUE TITLE
Clef in wrong position

### ISSUE THREAD

**Issue by pablomanuellucero** [opensheetmusicdisplay/opensheetmusicdisplay#695]
There are Clef changes in the staff, the Clef appears in the previous bar.
In this case the Clef had to be in the middle of the measure

![image](https://user-images.githubusercontent.com/12152639/77230629-48348000-6b74-11ea-80fa-8bd64d4310dd.png)

Here is the correct version:

![image](https://user-images.githubusercontent.com/12152639/77230690-b5e0ac00-6b74-11ea-8a68-4f57d339eccd.png)

**Comment by sschmidTU** [comment]
can you upload the sample here as xml (zipped)?
This might be an unhandled backup tag in XML, which is a weird thing and not easy to handle by the way.

**Comment by pablomanuellucero** [comment]
Thanks for your reply.
Attached the requested XML file.

[hna.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4363930/hna.zip)

**Comment by sschmidTU** [comment]
Fixed in #1102.
![image](https://user-images.githubusercontent.com/33069673/143605376-8824219c-b56a-4160-9839-e187b766779c.png)
Thanks for the sample!
