### ISSUE TITLE
Display of numbered musical notation 

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#698]
Hello,I'd like to ask that do you support the display of numbered musical notation? I failed to display my example using OSMD.
[1076.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4378583/1076.zip)

**Comment by sschmidTU** [comment]
What do you mean?
Judging from your sample, you probably mean fingering.
Fingering is already implemented, just use this:
```js
osmd.setOptions({drawFingerings: true})
```
But since drawFingerings defaults to true, i'm not sure what the problem is.

**Comment by sschmidTU** [comment]
Your MusicXML has to use proper fingering tags, not incorrectly used Text fields to replace fingering. There should be a function in your notation software to add proper fingering elements instead of Text.

**Comment by JanvyHung** [comment]
> Your MusicXML has to use proper fingering tags, not incorrectly used Text fields to replace fingering. There should be a function in your notation software to add proper fingering elements instead of Text.
> 
> I just noticed your sample uses Text instead of Fingering tags, this is improper usage and not supported.

![jianpu](https://user-images.githubusercontent.com/50696364/77601753-923bae00-6f46-11ea-86b0-821fd3008023.PNG)
I mean the display of numbered musical notation (also called simple score or jianpu in Chinese) just like the picture , not fingering tags.

**Comment by sschmidTU** [comment]
No, this is not supported. I've never seen that.

**Comment by sschmidTU** [comment]
By the way, numbered musical notation isn't even properly supported by MusicXML, and in your sample it's exported as Text tags, which is not usable.

**Comment by sschmidTU** [comment]
If you want to display text below notes right now, put it as lyrics.

**Comment by hhly** [comment]
楼主您好，请问您解决简谱的显示了吗

**Comment by sschmidTU** [comment]
It is not yet available, but it might come in a few months.

**Comment by sschmidTU** [comment]
@AlanPaine We're actually currently working on Jianpu and it should be ready soon.
I don't think JanvyHung is working on it anymore.

here is a simple little preview:
![image](https://user-images.githubusercontent.com/33069673/223903767-d5aec40a-ab4c-4a26-96bc-e2c03c467031.png)

**Comment by sschmidTU** [comment]
@AlanPaine It's not ready yet, as I said.

**Comment by sschmidTU** [comment]
It should be mostly done at the end of March, but we can't say a precise release date.

**Comment by cyrsis** [comment]
Hopefully can get a taste of it soon
