### ISSUE TITLE
BUG: Half note triplets render without stems

### ISSUE THREAD

**Issue by MilesMorel** [opensheetmusicdisplay/opensheetmusicdisplay#700]
I've tried XML I wrote myself and XML exported from musescore and have been unable to get OSMD to render stems on half note triplets. They instead render like whole note triplets. Is this a bug?

Here is an example measure:
`<measure number="2" width="282.45">
          <note>
            <pitch>
              <step>C</step>
              <octave>5</octave>
              </pitch>
            <duration>4</duration>
            <voice>1</voice>
            <type>half</type>
            <time-modification>
              <actual-notes>3</actual-notes>
              <normal-notes>2</normal-notes>
              </time-modification>
            <stem>down</stem>
            <notations>
              <tuplet type="start" bracket="yes"/>
              </notations>
            </note>
          <note>
            <pitch>
              <step>C</step>
              <octave>5</octave>
              </pitch>
            <duration>4</duration>
            <voice>1</voice>
            <type>half</type>
            <time-modification>
              <actual-notes>3</actual-notes>
              <normal-notes>2</normal-notes>
              </time-modification>
            <stem>down</stem>
            </note>
          <note>
            <pitch>
              <step>B</step>
              <octave>4</octave>
              </pitch>
            <duration>4</duration>
            <voice>1</voice>
            <type>half</type>
            <time-modification>
              <actual-notes>3</actual-notes>
              <normal-notes>2</normal-notes>
              </time-modification>
            <stem>down</stem>
            <notations>
              <tuplet type="stop"/>
              </notations>
            </note>
          </measure>`

**Comment by sschmidTU** [comment]
Right, this is a bug, a whole note divided into half note triplets is missing the stems:
![image](https://user-images.githubusercontent.com/33069673/78279785-57beac00-7518-11ea-9d23-db4d95517202.png)
may be related to #485

**Comment by sschmidTU** [comment]
Thanks @fredmeister for fixing this in PR #700!

**Comment by sschmidTU** [comment]
Thanks @fredmeister77 for fixing this in PR #709!
