### ISSUE TITLE
How to highlight a part of a music score ?

### ISSUE THREAD

**Issue by Soap12323** [opensheetmusicdisplay/opensheetmusicdisplay#708]
or how to put every notes into a array

**Comment by sschmidTU** [comment]
I'm not sure what you mean.
To highlight a note with the cursor, use `osmd.cursor.show()` and then `osmd.cursor.next()` until you're at the note you want to highlight.
You could also change a note.NoteheadColor and note.ParentVoiceEntry.StemColor, then call `osmd.render()` again.
If you have other short questions, you can also ask in the gitter chat:
https://gitter.im/opensheetmusicdisplay/opensheetmusicdisplay

**Comment by Soap12323** [comment]
> I'm not sure what you mean.
> To highlight a note with the cursor, use `osmd.cursor.show()` and then `osmd.cursor.next()` until you're at the note you want to highlight.
> You could also change a note.NoteheadColor and note.ParentVoiceEntry.StemColor, then call `osmd.render()` again.
> If you have other short questions, you can also ask in the gitter chat:
> https://gitter.im/opensheetmusicdisplay/opensheetmusicdisplay

Thanks for replying my question. I have achieved my goal by setting a timer to repeat osmd.cursor.next(), just like demonstration of displaying the composition
