### ISSUE TITLE
A way to scroll to the given measure.

### ISSUE THREAD

**Issue by fkruczek** [opensheetmusicdisplay/opensheetmusicdisplay#710]
I wanted to use your library in React application (based on your: [https://github.com/opensheetmusicdisplay/react-opensheetmusicdisplay](url) ).

Is there a way to scroll to a given measure when the sheet is already rendered?

Is it possible to display cursor at given measure?

**Comment by fkruczek** [comment]
Measure the cursor is currently on:
```
    const currentMeasure = this.osmd.cursor.VoicesUnderCursor()[0]
      .parentSourceStaffEntry.VerticalContainerParent.ParentMeasure
      .MeasureNumber;
```

One way is to iterate using osmd.cursor.next() till given measure.

**Comment by sschmidTU** [comment]
Yes, of course disable graphic updates with osmd.cursor.hide() before you cycle through with cursor.next(), then call cursor.show() again, otherwise you'll probably get visual flicker.

**Comment by fkruczek** [comment]
Some functions to manage cursor.

```
  goToNextLine() {
    const currentMeasureNumber = this.osmd.cursor.VoicesUnderCursor()[0]
      .parentSourceStaffEntry.VerticalContainerParent.ParentMeasure
      .MeasureNumber;
    const measuresInLine = this.osmd.GraphicSheet.measureList[currentMeasureNumber[0].parentStaffLine.Measures;
    const lastMeasureOfLineNumber = measuresInLine.last().measureNumber;
    this.goToMeasure(lastMeasureOfLineNumber + 1);
  }

  goToMeasure(measure) {
    //in case we want to go back
    this.osmd.cursor.reset();

    while (
      this.osmd.cursor.VoicesUnderCursor()[0] &&
      this.osmd.cursor.VoicesUnderCursor()[0].parentSourceStaffEntry
        .VerticalContainerParent.ParentMeasure.MeasureNumber < measure
    )
      this.osmd.cursor.next();

    this.scrollToCursor();
  }

  scrollToCursor() {
    const diffToBar = this.osmd.cursor.cursorElement.getBoundingClientRect().top;

    window.scrollBy(0, diffToBar - 100);

    // OR

    // this.osmd.cursor.cursorElement.scrollIntoView({
    //   behavior: diff < 1000 ? "smooth" : "auto",
    //   block: "start",
    // });

    //but it cuts upper part of music sheet
  }
```


> Yes, as we discussed on [gitter](https://gitter.im/opensheetmusicdisplay/opensheetmusicdisplay).
> Of course disable graphic updates with osmd.cursor.hide() before you cycle through with cursor.next(), then call cursor.show() again, otherwise you'll probably get visual flicker.

It seems cursor.hide() is also resetting cursor and after show() it's on starting position. But it looks good without hiding.

**Comment by sschmidTU** [comment]
Oh, right, maybe we shouldn't reset cursor in hide(). Good to know!
These functions are nice, i'd also write such functions if i were using the cursor (which is a pretty basic class right now) extensively in a project.
If i were you i'd add a GetCurrentCursorMeasure() method which returns `cursor.VoicesUnderCursor()[0].parentSourceStaffEntry.VerticalContainerParent.ParentMeasure` while checking that VoicesUnderCursor().length > 0, for convenience. Maybe we'll add that to the cursor class, as it seems quite useful and not quite straightforward.

**Comment by mkuzmik** [comment]
Hi, I would also love to see this feature!

**Comment by sschmidTU** [comment]
@mkuzmik hi, fkruzek posted working code two comments above yours. Or are you saying you would like to see these methods integrated into the Cursor class? Of course you can always write these methods into a helper class of your own.
