### ISSUE TITLE
Inconsistent interpretation of MusicXML pitches between OSMD and MuseScore

### ISSUE THREAD

**Issue by codingjourney** [opensheetmusicdisplay/opensheetmusicdisplay#715]
I'm setting up a home-practice app for my fellow choir members, based on [Jimmy's Audio Player](https://github.com/jimutt/osmd-playback-demo). I prepare scores in MuseScore and export them as MusicXML for playback in the app. My problem: the app plays all pitches one octave lower than MuseScore, even though they render the same.

I created a minimal [test file](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4461731/test.xml.txt) with one measure in treble key and one note on the first ledger line below the staff (the "middle C"). In MuseScore's native format, it [says](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4461767/test.mscx.txt) `<pitch>60</pitch>`. When I export to MIDI, the `NOTEON` pitch is also 60. In the exported MusicXML file, it says `<pitch><step>C</step><octave>4</octave></pitch>`. Having loaded the file into my app using `MusicSheetReader.createMusicSheet(...)`, I would thus expect `sheet.Parts[0].Voices[0].VoiceEntries[0].Notes[0].Pitch.halfTone` to be 60 as well but it's 48 instead.

Looking into `VoiceGenerator.addSingleNote()`, the octave is parsed as number from the XML text on line 390 (so it would be 4), then lowered by `Pitch.OctaveXmlDifference` on line 436 (so it would be 1). It's then submitted to the `Pitch` constructor where it enters into the calculation of `halfTone` on line 169: `this.halfTone = <number>(fundamentalNote) + (octave + Pitch.octXmlDiff) * 12 + Pitch.HalfTonesFromAccidental(accidental);`

Now, `Pitch.OctaveXmlDifference` and `Pitch.octXmlDiff` seem to refer to the same thing which looks like a private static constant. So when it's subtracted from the octave and then added back, we are effectively working with the original value (4). Remaining parts of the expression are zeroes so `halfTone` is calculated as 0 + 4 * 12 + 0 which is, indeed, 48.

My conclusion is that OSMD intentionally disagrees with MuseScore on the _sound_ of `<pitch><step>C</step><octave>4</octave></pitch>`, even though both render it the same way. I have no way to decide which is correct but I have heard from my choirmaster that the app plays an octave lower than she does during practice. More generally, there does seem to be some disagreement as to what [Middle C](https://en.wikipedia.org/wiki/C_(musical_note)#Middle_C) actually refers to.

Please feel free to close this issue if it's not an actual problem in OSMD. I'm not a professional musician nor music theorist so any enlightenment in response would be appreciated. As for [my app](http://music.journey.sk/), I've added a work-around to the playback logic, adding 12 to each `halfTone` value before it's used.

**Comment by matt-uib** [comment]
Yes right, we didn't stick here to the midi standard or to what others use. So for playback simply add the 12 so that the right sounds are played there where you hand over the notes to the audio player.

**Comment by sschmidTU** [comment]
Very interesting, thank you for the very detailed and superbly researched investigation!
This is basically all the info we need.
The MusicXML standard should leave no room for interpretation of the pitch, so we'll see what's correct and change it, and i assume MuseScore does this correctly.
Of course, OSMD itself doesn't have audio playback yet, but it's one of our projects for this year anyways, and in any case we'd like to offer the correct pitch value to developers.

**Comment by codingjourney** [comment]
Wow, thanks guys for the rapid response. I forgot to mention that I'd looked in the [MusicXML spec](https://github.com/w3c/musicxml/blob/gh-pages/schema/musicxml.xsd) but the description of `<octave/>` there is not very useful.

**Comment by bukaznik** [comment]
> I'm setting up a home-practice app for my fellow choir members, based on Jimmy's Audio Player.

@codingjourney that sounds quite interesting :) if you don't mind please share with showcase@osmd.org once you are done so we can add this to the osmd showcases at https://opensheetmusicdisplay.org/showcases/

**Comment by sschmidTU** [comment]
@codingjourney We discussed this internally, and it's true that the midi standard expects 60 as pitch value for the middle C, but that's not defined by the MusicXML standard.
MusicXML only defines octaves from 0 to 9, with middle C being in octave 4. It makes sense then to multiply octave with 12, with the lowest C at 0, and the octave 4 (middle) C at 4*12 = 48.
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-octave.htm

Middle C itself seems musicologically well defined as C4 or c' and a frequency of ~261Hz (probably from A=440Hz).
https://en.wikipedia.org/wiki/C_(musical_note)#Middle_C

As a conclusion, it probably makes sense for OSMD to conform to the established MIDI standard for pitch, especially when MIDI is often converted to MusicXML, but technically the pitch value isn't well-defined in MusicXML.
So we may adapt OSMD to Middle C = 60 as pitch value soon, but for now, developers adding an offset of 12 to the pitch is fine and within the MusicXML standard.

**Comment by codingjourney** [comment]
@sschmidTU thanks for the clarification. @bukaznik thanks for the offer.

**Comment by ice6** [comment]
@codingjourney 👍 nice work
