### ISSUE TITLE
Cursor dissappears whenever resizing

### ISSUE THREAD

**Issue by OscarWoHA** [opensheetmusicdisplay/opensheetmusicdisplay#734]
Is there a way to make the cursor state persist through a resize, or at least give an option for a callback or something similar after the resized render has been completed?

**Comment by sschmidTU** [comment]
This is fixed now, the new default behavior is to restore the previous Cursor position on re-render and resize (which also triggers `render()`).
This can be turned off by `osmd.rules.RestoreCursorAfterRerender = false`.

Will be in the next OSMD release, which should be out soon.
