### ISSUE TITLE
Using a different font family

### ISSUE THREAD

**Issue by celtiberi** [opensheetmusicdisplay/opensheetmusicdisplay#737]
In my MusicXML file I am using a font that allows me to show the tin whistle tablature

```<words default-y="-40.00" relative-x="2.50" relative-y="-11.21" font-family="Tin Whistle Tab" font-size="35">j</words>```

I have been trying to figure out what changes I need to make in the code to allow this, but I need a few pointers.

Thanks

**Comment by sschmidTU** [comment]
have you tried `defaultFontFamily`?
`osmd.setOptions({detaulfFontFamily: "Times New Roman"})`
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/0.7.6/src/OpenSheetMusicDisplay/OSMDOptions.ts#L52

Setting the font for a single element is not yet possible, but it could be something that we'll implement.

**Comment by celtiberi** [comment]
I did, but that changes the font for everything, and the font I am trying to use just shows which holes are open, no letters :)

If you could point me to where in the code I should look I can try and add this myself.  I was thinking ```Label.ts``` might be the correct location but not sure

**Comment by sschmidTU** [comment]
Font family can now be set per label.
You can set this after osmd.load(), or even change it after render(), but then you need to call render() again.

Here i changed the title font family to "Comic Sans MS" (sorry ^^):
![image](https://user-images.githubusercontent.com/33069673/82231506-91fbd580-992d-11ea-9347-d248944e5265.png)
`osmd.sheet.title.fontFamily = "Comic Sans MS"`

@celtiberi We should probably also add an option to use the font family given in the XML, if available,
so OSMD for example automatically sets the tin whistle font where necessary, and not for the title of the sheet or something.

**Comment by bneumann** [comment]
@sschmidTU Tried this in the latest version and it seems to work. Closing

**Comment by sschmidTU** [comment]
@celtiberi by the way, could you share a sample with those tin whistle tab font labels?
would be useful for testing setting label fonts from the XML.
Just a few measures would be fine.

**Comment by sschmidTU** [comment]
You can now set a custom font family for fingerings too:
```js
osmd.load(...)
osmd.cursor.GNotesUnderCursor()[0].parentVoiceEntry.parentStaffEntry.FingeringEntries[0].label.fontFamily = "Comic Sans MS"
osmd.render()
```
<img width="67" alt="image" src="https://github.com/user-attachments/assets/6990bd07-ce97-472d-916d-4fa36cd0ee88">
sample: `test_fingerings_multiple_per_note_sibelius.musicxml`

**Comment by ismaelv90** [comment]
This is great!!

Thank you very much!!

**Comment by sschmidTU** [comment]
@ismaelv90 Lyrics font setting should also already be possible via individual lyrics entries.
<img width="119" alt="image" src="https://github.com/user-attachments/assets/30d97c57-0459-4fa6-a45b-2d137865e75d">

`osmd.cursor.GNotesUnderCursor()[0].parentVoiceEntry.parentStaffEntry.LyricsEntries[0].graphicalLabel.Label.fontFamily = "Comic Sans MS"`

<img width="123" alt="image" src="https://github.com/user-attachments/assets/713541f0-5559-429a-ac76-ede6875758b2">

**Comment by ismaelv90** [comment]
Thank you very much. I´ll try it as soon as posible.

Regards!

**Comment by ismaelv90** [comment]
Hello:

I´m trying to implement the change of Font Family for Lyrics entries.

I see in your example that you get the notes under the cursor, but, is it not possible to got throught all the notes in the score and change all of lyrics?

Regards!

**Comment by sschmidTU** [comment]
@ismaelv90 Yes, it is. E.g. `osmd.Sheet.SourceMeasures[0].VerticalSourceStaffEntryContainers[0].staffEntries[0]`
It's worth going through the main osmd properties and seeing what they have to offer ;)
