### ISSUE TITLE
Changing Tab font

### ISSUE THREAD

**Issue by scotus-49** [opensheetmusicdisplay/opensheetmusicdisplay#739]
Can the tablature font be changed, for example to **Bold**, to assist readability?

**Comment by sschmidTU** [comment]
This is now implemented (develop branch), you can set a label's [fontStyle](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/Common/Enums/FontStyles.ts), e.g. to Bold:

```ts
label.fontStyle = FontStyles.Bold // equivalent to fontStyle = 1, for now
```

This should be done after load() and before render(), it's not so easy to update a label's fontStyle after rendering.

You can also set a defaultFontStyle that applies to all labels:
```ts
osmd.setOptions({defaultFontStyle: FontStyles.BoldItalic}); // or defaultFontStyle: 3
```

defaultFontStyle Bold:
![image](https://user-images.githubusercontent.com/33069673/82219946-4b52af00-991e-11ea-9486-bd51956ea6ee.png)

BoldItalic:
![image](https://user-images.githubusercontent.com/33069673/82220043-6d4c3180-991e-11ea-98f6-e4d6e1dd97fe.png)

**Comment by sschmidTU** [comment]
@scotus-49 which part of the tablature exactly did you want to make more visible?

by the way, you can also set `osmd.rules.FingeringLabelFontHeight`, and `osmd.rules.UnknownTextHeight` to set font sizes.
