### ISSUE TITLE
Tiny tiny bug of NoteType enum definition

### ISSUE THREAD

**Issue by zyuchuan** [opensheetmusicdisplay/opensheetmusicdisplay#740]
`32nd` is missing in `NoteType` definition:
 
```
export enum NoteType {
    // xml note types, e.g. given as <note><type>quarter, see:
    //https://usermanuals.musicxml.com/MusicXML/Content/ST-MusicXML-note-type-value.htm
    ...
    _128th,
    _64th,
    _16th,
    EIGTH,
    QUARTER,
    ...
}
```

**Comment by sschmidTU** [comment]
You're right! It's fixed now.

It's strange that we missed this! It seems like we didn't need the 32nd type in this enum in OSMD.
But of course it could be useful for other developers.

I also added two tests for this in the test suite.
