### ISSUE TITLE
Skyline: Consider Repetition Endings

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#741]
Currently repetiton endings are ignored in the skyline calculation which can lead to overlapping systems.

![grafik](https://user-images.githubusercontent.com/17180665/81556207-3a3bf800-938a-11ea-96e3-16f3c051b90a.png)

**Comment by matt-uib** [comment]
for trying compact mode:
osmd.setOptions({drawingParameters: "compact"})
osmd.rules.BetweenStaffDistance = 2.5
osmd.rules.StaffDistance = 3.5
osmd.rules.MinimumDistanceBetweenSystems = 1

e.g. on elite syncpations

**Comment by matt-uib** [comment]
For changing and optimizing the Volta y-coordinate:
VexFlowMeasure.addVolta():
change last number here:
this.stave.setVoltaType(voltaType, repetitionInstruction.endingIndices[0], **50**);

We should do this dynamically:

1. get skyline before placing volta
2. drop volta on top
3. update skyline at volta x-range

**Comment by matt-uib** [comment]
check out why the volta is ignored right now first..

**Comment by sschmidTU** [comment]
On a side note, keep in mind there's stilll an x-position bug with repetition endings (voltas), see #301. I'll probably try to fix that soon as well, would fit together nicely with this one.

**Comment by matt-uib** [comment]
@sschmidTU yes thanks! We talked about it, but prefect that you referenced it here.

**Comment by fredmeister77** [comment]
Think we can discuss and review tomorrow, but I submitted PR#744 for this with test results and further details.
