### ISSUE TITLE
Is it possible to center the music vertically and/or horizontally?

### ISSUE THREAD

**Issue by adrian-saldanha** [opensheetmusicdisplay/opensheetmusicdisplay#745]
I am trying to render some MusicXML which may be very small but sometimes is much larger, so we have a large viewport but sometimes the notation doesn't fill up the viewport due to the lack of measures / notes.

I would like to center the canvas/svg div within its container, but I've found it difficult to do this. I guess I could do it after the fact if I could determine the exact bounds of the OSMD notation within its canvas.

So is there a way to center it vertically/horizontally and also maybe determine the bounds of the notation within its canvas/svg element? Thanks for making such a great library!

**Comment by sschmidTU** [comment]
Just a quick idea, have you tried something like this?
```js
divContainer.style.width = osmd.graphic.MusicPages[0].PositionAndShape.Size.width * 10;
```
this would shrink the container to the sheet music's width.

The unit of size in OSMD is pixels / 10, compared to vexflow.
for more screen coordinate details see #504

**Comment by sschmidTU** [comment]
otherwise you can set `osmd.rules.pageLeftMargin` after which you need to call `osmd.render()` again.

**Comment by adrian-saldanha** [comment]
I'll give your first idea a shot right now, thanks!

**Comment by adrian-saldanha** [comment]
Unfortunately osmd.graphic.MusicPages[0].PositionAndShape.Size.width*10 gives me the width of the entire viewport, so this won't be suitable, thanks though.

**Comment by sschmidTU** [comment]
Ah, how about this:
```js
osmd.graphic.MusicPages[0].musicSystems[0].PositionAndShape.Size.width`
```
This is much smaller when for example the system (line) has only few measures.

**Comment by sschmidTU** [comment]
You can also try a few other bounding box elements, like the AbsolutePosition of the last measure of a system plus its width

**Comment by matt-uib** [comment]
Yes, for y-centering use 
1) the AbsolutePosition of the last measure + it's height /2 -> convert to pixels
2) the current screen height in pixels
3) add this to the y-pos of the canvas: "value of 2)" - "value of 1)"
then the last measure should be vertically centered on your screen.

**Comment by sschmidTU** [comment]
If this didn't work for you or you have further questions, feel free to keep commenting, and i may reopen the issue.

**Comment by sschmidTU** [comment]
most of the lower case variables are private, the getters are upper case and public
may not matter in javascript, but it does in typescript.

**Comment by syntheso** [comment]
> most of the lower case variables are private, the getters are upper case and public.
> may not matter in javascript, but it does in typescript.

I'm not really familiar with Typescript, but in JS this was the only way I could access them for my usecase. The way you specified was undefined for me. Thanks for leading me to the solution though!

**Comment by sschmidTU** [comment]
It may be that one of these upper case variables had a typo or something. If both exist, the upper case one should be preferred, they lead to the same result.
In any case, glad it worked out!
