### ISSUE TITLE
.setOptions stops score rendering?

### ISSUE THREAD

**Issue by syntheso** [opensheetmusicdisplay/opensheetmusicdisplay#751]
I am not sure if I am doing something silly, but everything works fine and the score loads using the code below:

```
var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("sheet-music");
                var loadPromise = osmd.load("www.hi.com");
                              loadPromise.then(function(){
                              osmd.render();
                              });
```

but simply adding osmd.setOptions({drawingParameters: "compact"}); as below stops the score loading, but there are no errors:

```
var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("sheet-music");
                var loadPromise = osmd.load("www.hi.com");
                              loadPromise.then(function(){
                              osmd.setOptions({drawingParameters: "compact"});
                              osmd.render();
                              });
```

What am I doing wrong?

**Comment by sschmidTU** [comment]
That's strange, `setOptions()` should be fine there.
You could try setting the options before `osmd.load()`.

It appears that compact drawingParameters cause an issue with your sample. Have you tried different ones? Does this also happen in our [public demo](https://opensheetmusicdisplay.github.io/demo/) when you set the options via console? Could you share a sample that causes this problem?

**Comment by syntheso** [comment]
Setting the options before osmd.load() raises: **osmd.setOptions is not a function**

Any .setOptions causes the notation not to load e.g `osmd.setOptions({drawTitle: false});`

I can't share a full reproducible problem because I am using this in the context of an R Shiny app, but literally my script is just this:

```
<script>
                var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay("sheet-music");
                var loadPromise = osmd.load("www.hi.com");
                              loadPromise.then(function(){
                              osmd.render();
                              });
</script>
```

and it works fine except for when I add .setOptions. I wonder why Shiny would stop this if it is a Shiny problem. But weird that it otherwise works fine.

**Comment by sschmidTU** [comment]
That's very weird, that you can't use osmd.setOptions() directly after the constructor.
Maybe this is done synchronously and the object isn't ready in time?
But again, that shouldn't happen and is very weird.
You can just add the options object in the constructor by the way:
```js
var openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay(“osmdCanvas”, {
            // set options here
            backend: “svg”,
            drawFromMeasureNumber: 1,
            drawUpToMeasureNumber: Number.MAX_SAFE_INTEGER // draw all measures, up to the end of the sample
          });
```

Otherwise, maybe you can sleep for 50 milliseconds or something before calling setOptions?

**Comment by syntheso** [comment]
>  You can just add the options object in the constructor by the way

Yeah so that's what I tried originally:

               var osmd = new opensheetmusicdisplay.OpenSheetMusicDisplay(\"sheet-music\", {drawTitle: false});

Even weirder (perhaps), is that now the score loads, but it doesn't apply the options!

And even sleeping gives the same error.. very strange.

**Comment by sschmidTU** [comment]
That is some voodoo going on there...
one more angle to try: are you sure you have the right OSMD build?
Version 0.76 should work. (we'll have a new version soon)
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases/tag/0.7.6

setting the options in the constructor makes osmd call its own function, so this should always work, in theory...

which environment do you use this in, which browser?

**Comment by syntheso** [comment]
Oh, how embarrassing. I didn't have the latest build, it turns out. I'm not sure how that happened. I only downloaded it the other day. Apologies! But thank you for your help ! :) 

By the way, I can't seem to find a way to remove the tempo mark?

**Comment by sschmidTU** [comment]
No problem! Things like this happen to me too ;)
oh, yes, the tempo mark, we don't have an option to disable it yet, but at least disabling should be easy and done soon, see #680.

**Comment by sschmidTU** [comment]
@syntheso i just implemented the option to not show metronome marks, see #680 :)
