### ISSUE TITLE
Render a list of notes?

### ISSUE THREAD

**Issue by syntheso** [opensheetmusicdisplay/opensheetmusicdisplay#752]
Hello,

Is there a way to render a list of notes, preferably just a list of MIDI values? i.e

renderNotation([60,62,64,65,67,69,71, 72]) would render the major scale.

All the best,
Seb

**Comment by sschmidTU** [comment]
The best way is probably to generate a MusicXML and hand it to osmd.load(). You can even give the MusicXML as a string, no need to read files.
So, look for a library that creates MusicXML files from code (or code it yourself, your usecase is very simple in MusicXML).
An alternative way is to create the MusicSheet data yourself, see our OSME [ExampleSourceGenerator](https://github.com/opensheetmusicdisplay/osme/blob/develop/src/OSME/SourceGenerator/ExampleSourceGenerator.ts).
OSMD is focussed on displaying MusicXML files, so other than the two methods above, unfortunately we don't have a simple API like EasyScore for Vexflow. But both methods above shouldn't be too complex either.
