### ISSUE TITLE
Use renderSingleHorizontalStaffline to switch multiple lines in a single line in the page on Android project

### ISSUE THREAD

**Issue by TheBrightestStarInTheNightSky** [opensheetmusicdisplay/opensheetmusicdisplay#753]
When I use renderSingleHorizontalStaffline: true on my Android project, the score only displays one line. When I call renderSingleHorizontalStaffline: false again to re-render the page, the score becomes multiple lines, but the score display will have problems，for example
![singleLine](https://user-images.githubusercontent.com/37290585/82875739-6058bf00-9f6a-11ea-9878-06d04aeb0823.png)
![multipleError](https://user-images.githubusercontent.com/37290585/82875859-8bdba980-9f6a-11ea-9a14-52169de0a1f5.jpg)

The correct display should look like this
![multipleOk](https://user-images.githubusercontent.com/37290585/82875999-b0378600-9f6a-11ea-8914-d5b70fa54f73.jpg)

Excuse me, how do I solve this display problem?
[musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4680763/musicxml.zip)

**Comment by sschmidTU** [comment]
The second issue should be fixed in #724. I guess you are using OSMD release 0.7.6? We fixed it after that. There should be a new release soon including the fix.

As to the single line being cut off, have you set the container width to be large enough?
something like this:
`yourDivContainer.style.width = 5000`

**Comment by TheBrightestStarInTheNightSky** [comment]
> The second issue should be fixed in #724. I guess you are using OSMD release 0.7.6? We fixed it after that. There should be a new release soon including the fix.
> 
> As to the single line being cut off, have you set the container width to be large enough?
> something like this:
> `yourDivContainer.style.width = 5000`

Thanks for your answer. 
Yes, my osmd version is 0.7.6,.
I tried to set container.style.width = '5000' before and after cutting off a single line, but it did not improve

**Comment by sschmidTU** [comment]
Do you set the option before loading the sheet music? i think that needs to be the case.
If you take a look at our [demo](osmd.setOptions({renderSingleHorizontalStaffline: true})), you'll see that the option works there:
`osmd.setOptions({renderSingleHorizontalStaffline: true})`
But you have to click clear and re-render to make it work, which means that you have to re-load the XML (or load a different one) before it works.
Maybe you can compare your project to the demo and see where the differences are and how this works.
Maybe also looking at our code helps, specifically how this option is implemented.

**Comment by TheBrightestStarInTheNightSky** [comment]
> Do you set the option before loading the sheet music? i think that needs to be the case.
> If you take a look at our [demo](https://opensheetmusicdisplay.github.io/demo/), you'll see that the option works there:
> `osmd.setOptions({renderSingleHorizontalStaffline: true})`
> But you have to click clear and re-render to make it work, which means that you have to re-load the XML (or load a different one) before it works.
> Maybe you can compare your project to the demo and see where the differences are and how this works.
> Maybe also looking at our code helps, specifically how this option is implemented.

Thanks a lot,  through clear () and reloading the XML can solve this problem

**Comment by sschmidTU** [comment]
You're welcome, i'm glad it works!
