### ISSUE TITLE
Slurs on Tab Notes have incorrect bezier curves (SVG and canvas)

### ISSUE THREAD

**Issue by MilesMorel** [opensheetmusicdisplay/opensheetmusicdisplay#755]
I discovered a rather funny looking bug. This twisting of slurs happens on both SVG and canvas backend. It pretty much always happens for tab staves. I'm not sure if it's limited to just slurs or also ties and other technical notations. Please let me know if there is a fix or if this is a bug the OSMD team is aware of.

![image](https://user-images.githubusercontent.com/44449222/83072232-64eda800-a03c-11ea-9b41-d4b07880def0.png)

**Comment by MilesMorel** [comment]
I really need canvas backend for this part of my app for performance reasons otherwise I'd just go with SVG

**Comment by sschmidTU** [comment]
Funny indeed! This must be a bug in the Vexflow CanvasContext.
I checked our code, and the method to draw slurs (bezier curves) is basically the same for both CanvasBackend and SVGBackend.
CanvasContext is a bit orphaned in Vexflow unfortunately, there are a few bugs that SVG doesn't have here and there.

So i would take a look at the `svgcontext.js` and `canvascontext.js` in Vexflow, and look at the methods `bezierCurveTo`, `lineTo`, and `moveTo` (especially `bezierCurveTo`).
See our methods `CanvasVexFlowBackend.renderCurve()` and `SVGVexFlowBackend.renderCurve()`. Graphical slurs are saved in `staffline.GraphicalSlurs`.

**Comment by MilesMorel** [comment]
Thank you for the detailed directions! That's interesting about Vexflow and
CanvasContext. In my experience, canvas backend loads much faster and it
handles way better when you render many OSMD instances. The disadvantage is
the difficulty of interacting with the note elements (e.g. for custom
highlighting).

**Comment by matt-uib** [comment]
we had such a problem in our native apps as well and it looks indeed very funny :-)
I think the reason is the order of the bezier points and control points - like start and end point are given in wrong order...

**Comment by MilesMorel** [comment]
Ah that makes sense @matt-uib. It sounds like the bug would come from Vexflow and not OSMD in that case so feel free to close the issue if it belongs elsewhere and I'll keep it in my list so I hopefully find time. 

For now, I'll write a little function to remove slurs from tabs from the MusicXML directly before passing to OSMD. I'll be sure to share that and a larger set of MusicXML helper functions once they become a little more robust in case anyone finds them useful here!

**Comment by MilesMorel** [comment]
Hey great job on 0.8+. That fixed a lot of issues I was having recently. 

Just a quick update: Tie and slur twisting occurs in both canvas and SVG backends. 
As @matt-uib may have predicted, it always happens with canvas backend and seems to only sometimes happen with SVG backend. 

It appears then that this bug is not only Vexflow but lives in OSMD's code too fwiw.

**Comment by MilesMorel** [comment]
Here is an example of tie-twisting with SVG backend. 

[exp1b.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4814139/exp1b.musicxml.zip)

**Comment by MilesMorel** [comment]
After some more experience with is, it appears this bug occurs all the time in tab staves and almost never in normal staves. I will update the title and question accordingly

**Comment by sschmidTU** [comment]
@MilesMorel i don't see any twisted slurs in that sample. Which options and EngravingRules have you changed? Maybe there's a hidden interaction there.
![image](https://user-images.githubusercontent.com/33069673/89207586-46b3a380-d5bb-11ea-9af2-802f9dfc67f2.png)

**Comment by sschmidTU** [comment]
@MilesMorel also, which browser are you using? i've tested in Chrome and Firefox.

**Comment by MilesMorel** [comment]
I'm sorry I've gotten terribly behind on this. I hope to respond to all the open issues by this Wednesday. I'll reopen this example and see if I can pinpoint why it might be happening.

**Comment by sschmidTU** [comment]
No problem, looking forward to your ideas and/or improvements!
