### ISSUE TITLE
Dynamic expressions like dim. overlap next staff line

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#758]
It looks like these expressions are not respected in the Skyline/Bottomline.
They should be added to the Bottomline in the following cases:

Clementi sonatina op. 63 No 1 Part 2:
![image](https://user-images.githubusercontent.com/33069673/83048898-9a998d80-a04a-11ea-8a31-ba5c90456789.png)

An die Geliebte, bar 10:
![image](https://user-images.githubusercontent.com/33069673/83048776-6b831c00-a04a-11ea-8661-f6401cc8539a.png)

more visible now since merging #754, where i initially found and mentioned this issue.

You can manipulate the overlap by setting osmd.rules.MinimumSkyBottomLineDistance. default is 2.0, with 1.0 there will be even more overlap.
This wouldn't be possible if these expressions were respected in the skyline.

**Comment by matt-uib** [comment]
i have the feeling that these expressions might get collided from below to the Skyline instead of the Bottomline. Then this placement would make sense to me....

**Comment by sschmidTU** [comment]
Sounds plausible, but the expressions don't seem to be included in the skyline/bottomline:
![image](https://user-images.githubusercontent.com/33069673/83158489-1fe17880-a105-11ea-8919-18a6744b5454.png)

**Comment by sschmidTU** [comment]
Oh, there's an indentation in the bottomline where the expressions are, but somehow the placement is shifted

**Comment by sschmidTU** [comment]
Ok, if i skip the y-manipulation in AlignmentManager.ts, placement is same as skyline:
![image](https://user-images.githubusercontent.com/33069673/83159388-363c0400-a106-11ea-8371-1064d166e059.png)
(put a continue in the second for loop)

so either we skip this alignment, or if we do it, we need to update the skyline afterwards.

**Comment by sschmidTU** [comment]
In the Clementi sample, the shift depends on what's in the Staffline. For example, when you shrink the window in width, at some point the problem appears or disappears.

Maybe take a look at `MusicSheetCalculator.calculateGraphicalInstantaneousDynamicExpression()`, which sets the y position of something like 'f' (forte).

In a debug session, in `AlignmentManager.alignDynamicExpressions()`, there was a 'f' and the diminuendo in an alignment group.

**Comment by sschmidTU** [comment]
fixed in #770,
including Skyline and Bottomline:
![image](https://user-images.githubusercontent.com/33069673/83704265-f26b6200-a611-11ea-93a3-589e3b75ea7d.png)
