### ISSUE TITLE
Rest positioning: take display-step from XML?

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#759]
I noticed that there is a rest / beam overlap in the bass clef of measure 13 of An die ferne Geliebte in the OSMD Demo.

![image](https://user-images.githubusercontent.com/8965352/83270726-1b10d900-a186-11ea-9735-9baf49f1619c.png)

This musicxml for this has a display-step setting to try to position the rest in the same place as the notes before and after it.

```
<note default-x="76.94" default-y="-236.96">
        <pitch>
          <step>C</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>5</voice>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <beam number="1">begin</beam>
        </note>
      <note>
        <rest>
          <display-step>C</display-step>
          <display-octave>4</display-octave>
          </rest>
        <duration>1</duration>
        <voice>5</voice>
        <type>16th</type>
        <staff>2</staff>
        </note>
```

We seem to be ignoring display-step.

When I load the musicxml into musescore, the rest is displayed inline with the C,

![image](https://user-images.githubusercontent.com/8965352/83271055-8f4b7c80-a186-11ea-9e9b-5ce3ce0664ba.png)

However, interestingly, when I load it into Sibelius, it ignores "display-step" but alters the stem length to avoid the overlap.

![image](https://user-images.githubusercontent.com/8965352/83271247-d20d5480-a186-11ea-8b9b-15259238eb2b.png)

Have we looked at this issue before?
(I searched and could not find a discussion of it)

**Comment by AlbertHart** [comment]
I looked up the score in the Shirmer book as well, to see how it handled the rest in beam in measure 13

![image](https://user-images.githubusercontent.com/8965352/83354958-71fae780-a319-11ea-9c30-29212e5923ac.png)

**Comment by sschmidTU** [comment]
Ah, interesting! I didn't know about this MusicXML element. This could solve a lot of rest overlap issues.
This should be fairly easy to implement as well. And there could be an option to turn it on or off, but default should probably be on anyways.

**Comment by AlbertHart** [comment]
Good. I didn't bother to transpose the display-step and display-alter in our new OSMD Transpose code, since they didn;t change anything in OSMD.

I'll add the code to update them properly.

**Comment by AlbertHart** [comment]
When this is fixed, can you update OSMD demo to use it. That it the best way for me to test my use of it. (Also, measure 13 of An die ferne Geliebte should automatically reflect the change, and show the rest between the two 'C's.

**Comment by sschmidTU** [comment]
Sure, when this is fixed, it will be the default option, so when there's a new OSMD release (which should be soon), the demo will be updated as well.
Actually, i can also create a new tag for a new demo when this is done.

**Comment by matt-uib** [comment]
Another case of rest overlap:
![grafik](https://user-images.githubusercontent.com/17180665/84155781-0b886e80-aa69-11ea-9368-f80037c177f3.png)

**Comment by bneumann** [comment]
My PR should do the trick
