### ISSUE TITLE
Fifth chord symbol rendering

### ISSUE THREAD

**Issue by ilionic** [opensheetmusicdisplay/opensheetmusicdisplay#760]
Is there any particular reason `power` type of chords not rendering in chord symbol? 

Would expect switch to return `5`, so chord like **C5** would display correctly. 

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/66f020a3c1533c9dc556cd7faa6f3679eaf99228/src/MusicalScore/VoiceData/ChordSymbolContainer.ts#L190

Can also send a PR.

**Comment by sschmidTU** [comment]
Ah, i hadn't seen that chord in a MusicXML sample before, fixed.
Thanks for the hint!
