### ISSUE TITLE
Too much space when a sheet has lyrics

### ISSUE THREAD

**Issue by trantinan2512** [opensheetmusicdisplay/opensheetmusicdisplay#762]
When a lyric occupied a certain amount of space that it would overlap the next lyric, this happens:
OSMD display with `drawLyrics: true` (or leave default)
![image](https://user-images.githubusercontent.com/20013228/83542384-12712780-a525-11ea-88a9-9ee1cee60693.png)
OSMD display with `drawLyrics: false`
![image](https://user-images.githubusercontent.com/20013228/83542329-fe2d2a80-a524-11ea-8851-e82d3c5a4290.png)
MuseScore display
![image](https://user-images.githubusercontent.com/20013228/83542437-2cab0580-a525-11ea-9d72-3a1844758aab.png)
Sheet being tested: [Test_me_Vi3ck2n.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4718295/Test_me_Vi3ck2n.zip)

Also the spacing gets wider and wider when I try to add more `#` (placeholder) to the lyrics.
Is this a spacing bug or I messed up somewhere?

**Comment by sschmidTU** [comment]
This seems to be fixed in the develop branch now, we made some system and staffline spacing changes. can you test that?
By the way, there are some relevant settings for this you can try to change:

```js
osmd.EngravingRules.MinSkyBottomDistBetweenSystems = 2.0; // default 5.0, try 2.0, which we use in "compacttight" mode
// for other settings see compacttight mode
```

you can also take some inspiration from our CompactTight mode, which is enabled like this:
`osmd.setOptions({drawingParameters: "compacttight"})`

you can instead look at what the mode does and instead do some of it yourself:
```typescript
// DrawingParameters.ts:
public setForCompactTightMode(): void {
        this.setForCompactMode(); // also sets CompactMode = true
        this.DrawPartNames = false;

        // tight rendering mode, lower margins and safety distances between systems, staffs etc. may cause overlap.
        // these options can afterwards be finetuned by setting osmd.rules.BetweenStaffDistance for example
        this.rules.MinSkyBottomDistBetweenStaves = 1.0; // default 1.0. this can cause collisions with slurs and dynamics sometimes
        this.rules.MinSkyBottomDistBetweenSystems = 2.0; // default 5.0
        // note that this.rules === osmd.rules, since it's passed as a reference

        this.rules.BetweenStaffDistance = 2.5;
        this.rules.StaffDistance = 3.5;
        this.rules.MinimumDistanceBetweenSystems = 1;
        // this.rules.PageTopMargin = 0.0; // see this.rules.PageTopMarginNarrow used in compact mode
        this.rules.PageBottomMargin = 1.0;
        this.rules.PageLeftMargin = 2.0;
        this.rules.PageRightMargin = 2.0;
        // this.BetweenStaffDistance = 2.5 // etc needs to be set in OSMD.rules
        // this.StaffDistance = 3.5
        // this.MinimumDistanceBetweenSystems = 1
    }
```
