### ISSUE TITLE
Weird x position for left fingeringPosition

### ISSUE THREAD

**Issue by trantinan2512** [opensheetmusicdisplay/opensheetmusicdisplay#764]
Increasing `font-size`, using 3+ diatonic notes (for arpeggios), adding extra text to fingering text would it overlap the note head
![image](https://user-images.githubusercontent.com/20013228/83620694-df2ba880-a5b7-11ea-9856-01ad300a7f62.png)

**Comment by sschmidTU** [comment]
First of all, the fingering system is not designed for using more than one number (e.g. 6). what does ":6" or ".7" mean?
If you need more space, have you tried positioning the fingering above, below, or to the right of the notes? 
`osmd.setOptions({fingeringPosition: "above"})`

But in case an offset is helpful, I added an EngravingRule FingeringOffsetX:
`osmd.EngravingRules.FingeringOffsetX = -1`
(commit c981e42939d1b61d97c0c3bf7c6e4f7305336213)

but an offset of (-1) already nearly causes collisions on 16th notes:
![image](https://user-images.githubusercontent.com/33069673/83643282-21e98280-a5b0-11ea-9c8b-8070034e8644.png)
(OSMD Function Test All)

**Comment by trantinan2512** [comment]
Thank you! `fingeringPosition: 'above'` works great for my use case :D

Things like "..6" or ".7" are tine position for an instrument called kalimba, they're kinda popular with JianPu music notation, but I'm not a fan of it because traditional music sheets rock! So I'm trying to add such notation on each note.

Maybe in the future the kalimba is popular enough to make a dent on traditional music sheets 😂

Oh and there's also a bug when using `setOptions` to set `fingeringPosition` option. I tried to change it, then called `.render()` on the instance, but it wouldn't reflect the changes. I'll make another issue about this!

**Comment by sschmidTU** [comment]
Don't make another issue about this, you need to reload the sheet after you change the fingeringPosition.

**Comment by sschmidTU** [comment]
There are some options which cannot be changed just by calling render again, this is one of them. You need to reload the piece to make the option take effect.

I'm glad that option works for you.
I've seen the kalimba before, sounds like a nice project!

**Comment by trantinan2512** [comment]
Thanks for the explanation! And yeah I could figure that `drawLyrics` worked just fine using `.render()`, so I thought it was a bug haha.

Thank you again, and all the contributors for such a great library 👍
