### ISSUE TITLE
Wiki is editable by anyone?

### ISSUE THREAD

**Issue by eliot-akira** [opensheetmusicdisplay/opensheetmusicdisplay#771]
Hi - not really an issue, more of a report.

I found a couple of small errors in one of the demo code snippets in the article [Tutorial: Extracting note timing for playing](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Tutorial:-Extracting-note-timing-for-playing#code-1---inspect-a-sheet-in-the-demo-and-paste-the-code).

For `iterator.currentVoiceEntries` and `iterator.currentTimeStamp`, it said "Current" instead of "current".

Thinking I'd contribute a quick pull request, I clicked Edit in the Wiki page, and made the corrections. Surprisingly, the changes seem to have been committed directly, without any review process.

Is that normal that anyone without maintainer/contributor status can edit the Wiki?

**Comment by sschmidTU** [comment]
Hi, thanks for the hint!
We didn't have problems with rogue Wiki edits in the past, so it was probably fine, but i deactivated public Wiki editing for now. If someone wants to submit a change, they can write to us, i guess.
By the way, the Wiki has its own git repository, so restoring previous states is very easy.
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay.wiki.git

As for the capitalization, this was actually intended, these are the getters. In Typescript, you're not supposed to access private variables of other objects (though it's still possible).
But the getter for currentTimeStamp was wrong (it's `CurrentSourceTimeStamp` for some reason), and currentTimeStamp is public anyways, so i'll leave that at the uncapitalized version.

**Comment by eliot-akira** [comment]
Thank you for the clarification!
