### ISSUE TITLE
Problem to read Tabs

### ISSUE THREAD

**Issue by rolandimusic** [opensheetmusicdisplay/opensheetmusicdisplay#773]
Hello,
Sorry for my English....
I discovered the OSMD project a short time ago and wanted to integrate it into my application.

I tested the demo, everything works fine.
The only problem comes from guitar tabs.
Did I forget to include a specific lib?

Here is the demo url: https://www.imusic-school.tv/opensheet/demo/

thank you in advance for your help

**Comment by sschmidTU** [comment]
calling `osmd.Version` in the console, i see you use OSMD Version `0.7.1b-dev`. This is outdated, Tab support was only added later. Please use at least OSMD Version 0.7.6, which you can find here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/releases
or here (if you use npm):
https://www.npmjs.com/package/opensheetmusicdisplay

There will also be a new version with many improvements very soon.

**Comment by rolandimusic** [comment]
Thank you very much for your answer

Now I still have some problems.
I want to display the rhythms on the tablatures.
The 4/5 strings bass display 6 strings.
For the part Manha Do Carnaval I have : n.getTieLeftX is not a function.

Maybe it's necessary to do a new issue for each problem...

**Comment by sschmidTU** [comment]
@rolandimusic can you share a musicxml sample for this? I don't have a tab sample with such an error.

**Comment by sschmidTU** [comment]
by the way, i'm not sure what you mean, the tabs do show the rhythm.
![image](https://user-images.githubusercontent.com/33069673/84147046-06bdbd80-aa5d-11ea-8a74-c7ec5fb15f80.png)

**Comment by rolandimusic** [comment]
Hi,
https://www.imusic-school.tv/opensheet/demo/

If you choose the "--> ONLY TAB" we don't have rythm
if you choose the "--> Bass Tab 4/5 strings" you can see the problem
if you choose the "--> MANHA DO CARNAVAL MXL "

I log the links

**Comment by sschmidTU** [comment]
Hi, thanks for the samples! This should be fixed now.
We just released OSMD version 0.8.0, please go ahead and try it, it should solve this problem.

If you have any further issues, feel free to continue commenting.
