### ISSUE TITLE
Demo fails to process XML file

### ISSUE THREAD

**Issue by HerbCaudill** [opensheetmusicdisplay/opensheetmusicdisplay#778]
Unable to load an XML file generated by [Notion](https://www.presonus.com/products/notion).

See XML here: 
https://gist.github.com/HerbCaudill/95de7f50fc656ad002ab0e2b8099c81f

Error in console: 

``` 
Uncaught TypeError: Cannot read property 'AbsoluteTimestamp' of undefined
    at VexFlowMusicSheetCalculator.createGraphicalMeasure (demo.js:51165)
    at VexFlowMusicSheetCalculator.createGraphicalMeasuresForSourceMeasure (demo.js:51112)
    at VexFlowMusicSheetCalculator.prepareGraphicalMusicSheet (demo.js:49547)
    at VexFlowMusicSheetCalculator.initialize (demo.js:49512)
    at new GraphicalMusicSheet (demo.js:47205)
    at OpenSheetMusicDisplay.updateGraphic (demo.js:72599)
    at OpenSheetMusicDisplay.load (demo.js:72591)
    at selectSampleOnChange (demo.js:692)
    at FileReader.reader.onload (demo.js:905)
```

**Comment by sschmidTU** [comment]
The throwing of errors is fixed now. However, there were some open octave shifts where the end could not be found and perhaps some other timestamp issues, these will not display completely correctly (octave shift will end at same measure it starts).

This is a very complex sample, and it looks like it wasn't exported to MusicXML very cleanly. Do you know which program this was exported from?

simpler sample link:
[Black_Crow.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4755741/Black_Crow.xml.zip)

We just released OSMD 0.8.1 with this fix.

**Comment by HerbCaudill** [comment]
Thanks. I exported it from [Notion](https://www.presonus.com/products/notion). Here's the original .notion file FWIW. 
[Black Crow.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4763656/Black.Crow.zip)

**Comment by sschmidTU** [comment]
Oops, you did mention that. Well, either Norton doesn't export to MusicXML very well, or there are some issues in OSMD rendering due to the complexity of the file. It seemed to me that an octaveshift in the XML wasn't completed. Though i'm wondering why the last music system (row) is so large.

**Comment by sschmidTU** [comment]
Closing as the main issue is fixed (failing to load).
It would be nice to fix the octaveshift position of course, but it would be much easier with a much shorter sample, this one is huge, and likely has some faulty MusicXML from exporting from Norton. MuseScore does seem to get the octave shift starts correct though. probably a case of an octaveshift not being ended. (start+start instead of start+end+start) -> can go into new issue, ideally with a shorter sample.
