### ISSUE TITLE
Major-minor chord symbol rendering

### ISSUE THREAD

**Issue by ilionic** [opensheetmusicdisplay/opensheetmusicdisplay#780]
Related to https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/760
Noticed also missing chord symbol for major-minor chord

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/6e1558d031452338a5cf0a0479f971337c6abbaf/src/MusicalScore/VoiceData/ChordSymbolContainer.ts#L143

Based on MusicXML spec should be `min(maj7)`
![image](https://user-images.githubusercontent.com/1027871/84073289-c9abe980-a9d0-11ea-9f43-cff6e390cee1.png)

**Comment by sschmidTU** [comment]
fixed in #784.
