### ISSUE TITLE
Placement getter doesn't work for UnknownExpressions

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#781]
which uses this.expression.Placement, where expression is undefined.
Let's give the UnknownExpression also an AbstractExpression and store it in this.expression.

**Comment by sschmidTU** [comment]
first fixed in fa35e8f9ebe4ad9d00acf3ee4bf1537e1e9ac054.

**Comment by sschmidTU** [comment]
The ideal solution of course would be to store the UnknownExpression in GraphicalUnknownExpression, but this needs a bigger refactor where we don't split expressions into multiple smaller expressions without saving the whole expression separately.
