### ISSUE TITLE
Replace undefined checks with if (x) etc in codebase where possible

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#783]
This works then for _undefined_ and also for _null_ 

Also search for (x === undefined) ...

**Comment by sschmidTU** [comment]
Now I handled basically all `!== undefined` and `=== undefined` cases.

Some of these checks should actually not be changed, if it's a number, enum or a boolean. In that case, removing `!== undefined` is very different from leaving it.

```js
if (chordSymbolEnum !== undefined) // only true if undefined
if (chordSymbolEnum) // false if undefined or enum value 0
```

There are 4 small visual diffs, mostly positive or neutral changes.
