### ISSUE TITLE
how to skip writing maj in major chord

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#784]
like 
Cmaj7 -> C7
Dmaj7 -> D7

I can't find option about simplify major chord

I think it looks much better

**Comment by sschmidTU** [comment]
C7 is a minor seventh chord, basically the standard (more common/traditional) seventh chord.
So writing Cmaj7 as C7 is a mistake.
https://www.pianochord.org/c7.html

If you still want to write Cmaj7 as C7, give it as a minor chord instead.

**Comment by djae88** [comment]
Oh, I made a mistake for a moment. 
What I was going to say was,
how about maj to M (like Cmaj -> CM7, Cmmaj7 -> CmM7) 
I don't know if other countries use it like this,
but here we don't nearly use maj because
it makes chord symbol too long

and i just found that Cmmaj7 is showing as C in osmd, Is this intended?
![image](https://user-images.githubusercontent.com/56290540/84187549-25f43380-aacd-11ea-80b0-df7dcd67a8bd.png)
![image](https://user-images.githubusercontent.com/56290540/84187567-2f7d9b80-aacd-11ea-9cca-0d01146bd038.png)
![image](https://user-images.githubusercontent.com/56290540/84187582-37d5d680-aacd-11ea-94e1-c90206772204.png)


 Thank you for quick response

**Comment by sschmidTU** [comment]
you can now set your custom texts for chord symbols like this:
```
osmd.rules.setChordSymbolLabelText(5, "majorseventh");
// key: ChordSymbolEnum (5 = majorseventh), value: string
```
(implemented on develop, new release soon)

**Comment by sschmidTU** [comment]
Oh and i fixed majorminor, it now displays `m(maj7)` by default.

**Comment by ilionic** [comment]
> you can now set your custom texts for chord symbols like this
This is amazing! Thanks, hope it would help to display more complex chords ( I had issue with something like 'major seventh flat sixth' ) 

Could be closed then https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/780

**Comment by sschmidTU** [comment]
There is now also a new demo and test sample, OSMD Function Test - Chord Symbols:
![image](https://user-images.githubusercontent.com/33069673/84200885-b3bd2800-aaa7-11ea-95d3-1caf211988ae.png)

@ilionic i'm glad this seems useful, but i'm not sure this change helps with your example 'major seventh flat sixth'.
These are the chords you can change the text for currently:
```typescript
export enum ChordSymbolEnum {
    major,
    minor,
    augmented,
    diminished,
    dominant,
    majorseventh,
    minorseventh,
    diminishedseventh,
    augmentedseventh,
    halfdiminished,
    majorminor,
    majorsixth,
    minorsixth,
    dominantninth,
    majorninth,
    minorninth,
    dominant11th,
    major11th,
    minor11th,
    dominant13th,
    major13th,
    minor13th,
    suspendedsecond,
    suspendedfourth,
    Neapolitan,
    Italian,
    French,
    German,
    pedal,
    power,
    Tristan
}
```

I'm not sure which of these enums would be set for that chord.
Do you have a sample including such a chord? Or do you know what the `<kind>` etc xml data would be?

**Comment by ilionic** [comment]
Ok I see @sschmidTU so still should be compliant with musicXML `kind` based on: https://usermanuals.musicxml.com/MusicXML/Content/ST-MusicXML-kind-value.htm 

I came across more 'obscure' chords that don't really have direct mapping in musicXML schema ( or perhaps some named differently and I am not aware ), but would be cool in theory to be able to generate those. 
I don't have actual score containing those, instead looking into chords generation from more theoretical side. Some examples: 
7sus4, b9sus, dominant sharp, dominant flat, altered, sixth/ninth, lydian, major seventh flat sixth.
