### ISSUE TITLE
How can I enforce bottom-side margin on a music sheet?

### ISSUE THREAD

**Issue by dnlfrst** [opensheetmusicdisplay/opensheetmusicdisplay#788]
# What is the use case?

I would like to enforce [more-than-default](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/EngravingRules.ts#L256) bottom-side margin on a music sheet for better aesthetics.

# What did I try?
The [`EngravingRules`](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/EngravingRules.ts) contain a property [`PageBottomMargin`](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/EngravingRules.ts#L568-L573). Similar to the property [`PageTopMargin`](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/Graphical/EngravingRules.ts#L556-L561), I would expect `PageBottomMargin` to influence the distance between the last system and the end of the music sheet (i.e., the SVG). Setting `PageTopMargin` influences the distance between the top/title of the music sheet and the first system. However, [`PageBottomMargin` seems to have no effect](https://codesandbox.io/s/osmd-issue-788-7tgsu?file=/src/index.js), at all.

Surely, it is possible to manually adapt the `height` of the rendered SVG. However, I would prefer to use an "official" channel to set bottom-side page margin.

# Question
Is there another way, apart from `PageBottomMargin`, to achieve my goal? If `PageBottomMargin` is the only answer to that, why am I not able to achieve any effect using it?

**Comment by sschmidTU** [comment]
I assume you use this with endless PageFormat (not e.g. A3 Landscape format).
Otherwise, with paged format, this is tricky, because the pages have a predefined height and width. What we could maybe do there is add the margin to the last page, because the last page doesn't consider the margin right now.

I pushed a branch fix/pageBottomMargin where you can set osmd.rules.PageBottomMargin and it will add it to the last page for endless page format.
For paged format, this would probably be a pretty complicated issue.

**Comment by dnlfrst** [comment]
Indeed, I was referring to the endless `PageFormat`. I just [tested the new branch](https://codesandbox.io/s/osmd-issue-788-with-new-branch-6ulqx) and its exactly what I had in mind, great work! Are there any plans to include this feature in a future release?

**Comment by sschmidTU** [comment]
Great! Now that i know it's working and what you had in mind, i'll see about merging into develop and testing for side effects, then it'll be in the next release. cheers!

**Comment by sschmidTU** [comment]
There's a different new option now you can set:
`osmd.EngravingRules.PageBottomExtraWhiteSpace = 50;`

This is somewhat experimental, as it causes bugs when used with PageFormat (e.g. A3 Landscape, with lyrics (Beethoven Geliebte sample)), but that seems outside of your use case.

Merged to develop in #822, will be in next release.
