### ISSUE TITLE
Hide Time Signature?

### ISSUE THREAD

**Issue by DamianRivas** [opensheetmusicdisplay/opensheetmusicdisplay#793]
Hi, correct me if I'm wrong but I don't see a way to hide the time signature through `OSMDOptions`. Although we don't absolutely need this feature, we'd like our mobile application to hide it to simplify the view even further. Our app uses cards of single mesaured music notes to display things like chord shapes.

This is about as simple as we can get it right now:
![image](https://user-images.githubusercontent.com/10257813/84844562-7bfe3500-afff-11ea-89e3-94fdf3f05001.png)

Would it be easy to implement an option to hide the time signature?

**Comment by sschmidTU** [comment]
You can actually do this already, but it's a bit complicated.
It should be pretty easy to make an option for this, so i'll look into it.

If you type this in the console in the demo, then call osmd.render() again, the time signature in the voice will disappear:
```js
osmd.sheet.sourceMeasures[0].firstInstructionsStaffEntries[0].instructions[2].PrintObject = false
```
<img src="https://user-images.githubusercontent.com/33069673/84845462-015c0680-b04d-11ea-8244-e274c2b72a61.png" height="200">

From here, you can see that you can make a for loop over all firstInstructionsStaffEntries and instructions and check if it's `instanceof RhythmInstruction` then set PrintObject false.
<img src="https://user-images.githubusercontent.com/33069673/84845488-0faa2280-b04d-11ea-80b1-0e903f5da89f.png" height="200">

But as i said, that's pretty obscure, so i'll see if i can make a quick option.

**Comment by sschmidTU** [comment]
Done.
`osmd.setOptions({drawTimeSignatures: false})`

Merged in develop, will be in next release.

**Comment by DamianRivas** [comment]
Wow I thought I would have to fork it and do it myself. Thank you so much!!

**Comment by DamianRivas** [comment]
@sschmidTU If we want to fine tune the spacing between the clef and the first note, what properties should we be looking to modify?

**Comment by sschmidTU** [comment]
I'm not sure that that's possible. You'd probably have to change a private variable in Vexflow, which does most of the formatting, at least for things like clefs and notes.

What would be the purpose of this? Making the spacing more compact? Or aligning notes? I don't think it can be much more compact.
![image](https://user-images.githubusercontent.com/33069673/84847378-5a2d9e00-b051-11ea-9347-9fdad9e8a154.png)
If it's about aligning notes, Vexflow versions 3.x align notes vertically, we'll probably switch to these versions soon (they still have some formatting issues).

**Comment by DamianRivas** [comment]
Ah, I see.

We just to align notes horizontally. I admit we are probably not using OSMD as it was intended because we're building a sort of teaching application and we're basically only rendering single measures inside cards (think music flash cards). The teacher is creating all the mxl files through her music writing software.

OSMD just makes it easier to implement because the teacher can deal with creating the teaching material and the developers just deal with rendering it.

**Comment by sschmidTU** [comment]
I see. Well, you can set PageLeftMargin:
`osmd.rules.PageLeftMargin = 20`
but this will shift the complete system, including clef.

**Comment by sschmidTU** [comment]
You could also insert invisible notes before the actual notes, but you'll probably have to do that for every sample, seems like too much work.

**Comment by DamianRivas** [comment]
Hmm those are interesting options. It will ultimately be up to the stakeholder to decide what she wants us to go with. Thank you for the insight!
