### ISSUE TITLE
Auto ChordSymbolYOffset?

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#795]
If the notes are too high to reach the chord
I set ChordSymbolYOffset value but it applies to the whole sheet, 
So it doesn't look good for low notes.
![image](https://user-images.githubusercontent.com/56290540/84941687-af82b180-b11c-11ea-8045-319a7d67e003.png)

please let me know if there is any way to 
apply ChordSymbolYOffset manually to specific notes

or making something like auto ChordSymbolYOffset option that
automatically calculate Yoffset from high note
will be a great work

Thanks

**Comment by MilesMorel** [comment]
I am encountering issues with collisions between chord symbols and/or text annotations and other elements very regularly in guitar scores since the music is almost always rendered with either chord symbols (non-classical) or annotations/labels (classical).

I think this can reference #418:
@sschmidTU left off with:
> Yes, as I said, for real chord symbol spacing we would need a complete collision detection and spacing method, ideally for all labels. We'll probably do that at some point anyways...

@bneumann any chance this is in the works or could be soon? I think it would have a major impact on quality for my project

**Comment by MilesMorel** [comment]
Here is another case where triplets are colliding with chord symbols:

![image](https://user-images.githubusercontent.com/44449222/89128119-518a0d80-d4c1-11ea-866b-9937bd22c78a.png)

**Comment by MilesMorel** [comment]
And in this case, chord symbols are colliding with the tempo marking and with each other:
![image](https://user-images.githubusercontent.com/44449222/89128149-8d24d780-d4c1-11ea-8e9e-457d657686fb.png)

**Comment by MilesMorel** [comment]
And with notes if you don't set a uniform and high-enough offset, like the OP:
![image](https://user-images.githubusercontent.com/44449222/89128190-df65f880-d4c1-11ea-929c-b12283d5d1fa.png)

If these should be filed as separate issues, I can break them out but they seemed related.

**Comment by sschmidTU** [comment]
@MilesMorel this is just a workaround, but have you tried setting osmd.EngravingRules.ChordSymbolYOffset? It will shift all chord texts. Setting it a little higher will at least solve collisions with metronome marks and most notes that aren't too high.

**Comment by MilesMorel** [comment]
IN lieu of collision handling, the offset did help a lot of these cases ~ thank you!

**Comment by sschmidTU** [comment]
`osmd.EngravingRules.ChordSymbolYAlignment = false`
<img width="570" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/03260b7b-f3c9-4e47-b9fb-93cc85aef7b2">
