### ISSUE TITLE
Reattach to different DOM nodes?

### ISSUE THREAD

**Issue by DamianRivas** [opensheetmusicdisplay/opensheetmusicdisplay#796]
In our mobile-first application we have many screens where we're rendering a single measure of music notes. We only render one measure per screen, and we're using Preact.

The strategy I came up with was to just import and define an OSMD instance once and re-render different scores as needed.

So far, I am re-rendering trough OSMD by dynamically loading scores and calling `OSMD.render()`
```js
useEffect(() => {
  if (url) {
    loadMusicFile(url);
  } else {
    console.log("NO URL FOUND");
  }
}, [url]);
```
...where `loadMusicFile` does the load and re-render with the existing OSMD instance, but I would also like to handle the situation where the DOM node that the component renders in changes from some unforeseen factors.

But I see that OSMD attaches to a DOM node in its constructor and there is no API for reattaching an instance to different DOM nodes.

I could do something like this
```js
const canvas = useCallback((node) => {
  if (node) {
    openSheetMusicDisplay = new OpenSheetMusicDisplay(node, osmdOptions);
  }
}, []);
```
but is there a way I can just take the existing instance and re-attach `OSMD.container` to the new `node`?

Or perhaps I am tackling this all wrong? I am working under the assumption that it would be more efficient to re-attach it to a new node vs initializing a new instance of OSMD

**Comment by sschmidTU** [comment]
You can probably just give OSMD a new container if you want:
`osmd.container = newContainer`
Then you can probably transfer the SVG/Canvas to that container, and remove that child node from the old container. Or simply remove the old container (and its child nodes) and let OSMD render again.

Though, while I'm not an expert on the DOM, i can't imagine a non-bug case where the OSMD DOM node would change. You can give OSMD a custom container you create yourself and use for no other purpose, why would it be changed?

**Comment by DamianRivas** [comment]
Ah, yep! It was that simple. The following seems to work...
```js
if (openSheetMusicDisplay) {
  console.log("reattaching...");
  openSheetMusicDisplay.container = node;
} else {
  console.log("Initializing...");
  openSheetMusicDisplay = new OpenSheetMusicDisplay(node, osmdOptions);
}
```

The DOM node changes because the UI is dynamically being rendered and re-rendered with the JavaScript framework we're using. As the user navigates through the app, DOM nodes are being created and destroyed all in JS including the node that OSMD attaches to.
