### ISSUE TITLE
Single drum line with other instruments - alignment / keysignature offset

### ISSUE THREAD

**Issue by cyrilvinzent** [opensheetmusicdisplay/opensheetmusicdisplay#797]
Seems to be some alignment issues in the first bar when rendering single drum line with other instruments which have a key signature.

Demo:
![image](https://user-images.githubusercontent.com/62267836/84995191-02c02880-b14c-11ea-92fe-b04de09ea744.png)

MusicXML File: 
[Drum on one line.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4797214/Drum.on.one.line.musicxml.zip)

**Comment by matt-uib** [comment]
Yes, thanks - a classical "Vexflow" i would say :-) there were and are some alignment issues...
@sschmidTU can you again take a look at this?
Obviously, we need to take the max x width of all beginInstructions in all staves and use it as the start for placing the notes.

**Comment by sschmidTU** [comment]
Ah, i thought this was fixed in Vexflow 3.x, but it isn't.
I can see what we can do about that, though i don't think we can set any explicit spacing after the clef in Vexflow (see #793, later part). This part is layouted by Vexflow.

**Comment by sschmidTU** [comment]
The solution should be to draw an invisible key signature in Vexflow, like in #872.
Unfortunately I couldn't manage to make a key signature display in the single line drum staff, and i'm not sure why, I couldn't find a place in the Vexflow code where this would be checked.

**Comment by sschmidTU** [comment]
Fixed in #1427.

<img width="374" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/3e963e94-7fce-46b1-8cf9-ee2059901d35">
