### ISSUE TITLE
Bends and Releases for Tabs (Guitar)

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#798]
Feature was requested.

Tab examples (images):
https://www.guitarnick.com/how-to-play-on-guitar-bending-release.html

Vexflow has a bend class:
https://github.com/0xfe/vexflow/blob/master/src/bend.js

MusicXML bend element:
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-bend.htm

A MusicXML sample would be helpful.

**Comment by sschmidTU** [comment]
The Vexflow tests have a bend snippet:
"Double Bends with Release"
![image](https://user-images.githubusercontent.com/33069673/85028515-77f72200-b17b-11ea-8fa5-061e9434b664.png)
http://www.vexflow.com/tests/

**Comment by momolarson** [comment]
Hi Simon, Thanks for Opening the issue, here is a sample note that has a bend and release:

https://gist.github.com/momolarson/4d2eaa0be6cabea8138417afedee4083

I am assuming that some of the work would be done adding modifiers here:

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/ad80ad526ea66b200e4ec4d8c18aa56463b2136e/src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts#L547

**Comment by momolarson** [comment]
I was able to get this working under the basic conditions:

![Capture_simplebend](https://user-images.githubusercontent.com/43911543/85423630-2a403800-b534-11ea-9272-6c6539c8d5db.JPG)

I have some work to do on the more complex bend and releases:


![Capture_complexbend_release](https://user-images.githubusercontent.com/43911543/85423774-58257c80-b534-11ea-9bec-faddf3327682.JPG)

Kinda related, but probably it's own issue, I also added Vibratos:


![Capture_vibrato](https://user-images.githubusercontent.com/43911543/85423887-7a1eff00-b534-11ea-9f77-0645c9f886b7.JPG)

Code can be seen here, any comments and changes are appreciated!:  

https://github.com/momolarson/opensheetmusicdisplay/pull/1

**Comment by sschmidTU** [comment]
@momolarson i have your pull request merged on feat/tabs/bend-release.
Unfortunately, you didn't get credit as author in the commits, because your PR had merge conflicts.
If you want to get credit, you can merge the feat/tabs/bend-release branch into your PR, then i can merge it and you'll get credit. Otherwise i'll just merge the feat/tabs/bend-release branch.

In any case, i'll do some testing afterwards then hopefully merge to develop.
It seems the more complex bends/releases aren't working yet, but this is already an improvement worth merging to develop, right?

**Comment by sschmidTU** [comment]
@momolarson small update, i had to basically rename the feat/tabs/bend-release branch to feat/tab/bend-release (in a complicated way), because there was apparently a feat/tabs branch before, which was creating issues (but git didn't warn me when i pushed that).
So, simply merge feat/tab/bend-release into your PR if you want the commit credit.

**Comment by momolarson** [comment]
will do!

**Comment by momolarson** [comment]
Simon - let me know if this is what you are looking for:

https://github.com/momolarson/opensheetmusicdisplay/pull/2

**Comment by sschmidTU** [comment]
Yes, great! Merged it in #812, so you should get credit for the commit now. I did squash the commits into one because there were a bit too many, but you'll still get credited for that (e.g. on the [contributors page](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/graphs/contributors), once this is merged to develop).

**Comment by sschmidTU** [comment]
Merged to develop.

Thanks again @momolarson for the PR!

**Comment by sschmidTU** [comment]
Added your short one measure bar/release sample to our test/data samples for testing.
![image](https://user-images.githubusercontent.com/33069673/86403212-8da53500-bcad-11ea-9234-bab72c167b2b.png)
