### ISSUE TITLE
Hide ledger lines for invisible notes

### ISSUE THREAD

**Issue by AlbertHart** [opensheetmusicdisplay/opensheetmusicdisplay#799]
This is a relatively minor complaint.
In the attached score, I have hidden voice 2 - which contains a string of 1/8 notes to space out the lyrics - which are the rhythm beats.

It is working surprisingly well, except that the 1/8 notes in voice 2 were on middle c, so they are causing the middle staff addition to appear, even though the note itself is hidden.

I suspect that I can fix this for my score by moving the voice 2 1/8 notes to a D.

But, if a voice is hidden then the staff extensions should also be hidden.

![image](https://user-images.githubusercontent.com/8965352/85045524-4dda3b80-b14c-11ea-8c89-a55b40de239b.png)

[El_Prince-R3.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4799746/El_Prince-R3.xml.zip)

**Comment by AlbertHart** [comment]
In looking at the Music XML - it appears that Sibelius hides a voice by setting: print-object="no"

```
<note print-object="no" color="#000000" default-x="103" default-y="-77">
    <pitch>
     <step>C</step>
     <octave>4</octave>
    </pitch>
    <duration>128</duration>
    <instrument id="P1-I1" />
    <voice>2</voice>
    <type>eighth</type>
    <stem>down</stem>
    <staff>1</staff>
    <beam number="1">begin</beam>
    <lyric default-y="-125" number="part1verse2" color="#000000">
     <syllabic>single</syllabic>
     <text>1</text>
    </lyric>
   </note>
```

**Comment by sschmidTU** [comment]
fixed, invisible notes now also have invisible ledger lines.

before:
![image](https://user-images.githubusercontent.com/33069673/87803493-d551c200-c852-11ea-8e47-6f0579d8a282.png)

after:
![image](https://user-images.githubusercontent.com/33069673/87803526-e0a4ed80-c852-11ea-9024-0c51329f8b56.png)

sample:
[invisible_ledger_lines_test.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4938612/invisible_ledger_lines_test.musicxml.zip)

you can test this in the demo by loading the sample and executing this:
```
osmd.graphic.musicPages[0].MusicSystems[0].graphicalMeasures[0][0].getVoicesWithinMeasure()[0].VoiceEntries[0].Notes[0].PrintObject = true; osmd.render();
```

of course you can make the note invisible again with `PrintObject = false` as well.
