### ISSUE TITLE
Rename MusicSheetAPI

### ISSUE THREAD

**Issue by sebastianhaas** [opensheetmusicdisplay/opensheetmusicdisplay#8]
Should probably be renamed to something less confusing such as `OSMD` or `OpenSheetMusicDisplay`.  Suggestions? This is also what people will get when including OSMD as global using `<script>` tags.

- [x] Rename MusicSheetAPI
- [x] Don't forget to update `main` and `typings` field in `package.json` accordingly.
- [x] Update unit tests if required, if we don't have any for testing our main export yet we should get some.

**Comment by acondolu** [comment]
For me both possibilities are fine (OSMD or OpenSheetMusicDisplay). Maybe I slightly prefer OSMD. What do you vote for?

**Comment by oliver-h** [comment]
The same here. I like both, but OSMD is ahead by a nose

**Comment by sebastianhaas** [comment]
I'd also prefer OSMD.

**Comment by acondolu** [comment]
Renamed to 'OSMD' in cd8baf40fa5f22cbe778c2092edef271ef8919b8 and 37d827823ac916fcde4fb60dd92858d0d2c6e166.

**Comment by acondolu** [comment]
What about the third point in the checklist, and the "main export"?

**Comment by sebastianhaas** [comment]
Our main export is `OSMD` at the moment. This is also what you will get when using OSMD via script tags. We do have _some_ tests for OSMD, but only for the plugin infrastructure in #16. I think we should add tests for the methods OSMD exports, e.g. load, display, the constructor etc.
