### ISSUE TITLE
support for Breve/brevis note

### ISSUE THREAD

**Issue by RobbStarkAustria** [opensheetmusicdisplay/opensheetmusicdisplay#803]
Thanks for this wonder- and powerful tool.

I'm working on the conversation of white mensural notation to modern notation. In renaissance the use of the brevis note (simply said two whole notes) was common. Modern notation knows the brevis-note as well and there is a type for this in the musicXML-documentation. See here: [http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-type.htm%3FTocPath%3DMusicXML%2520Reference%7CScore%2520Schema%2520(XSD)%7CElements%7Cnote%7C_____126](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-type.htm%3FTocPath%3DMusicXML%2520Reference%7CScore%2520Schema%2520(XSD)%7CElements%7Cnote%7C_____126)

I'm using the react component of your tool and it works well instead of interpreting and displaying of a brevis note. These type of note is displayed as a whole note. The same issue can be found in your online demo-page. I have attached a demo-file where the first note is of brevis-type.

By the way, Musescore shows the brevis-type correctly.

Edit: I have noticed that the brevis rest is not recognized either. Also here only a whole rest is displayed. 

Please add support for brevis note and rest.

Thanks
[test_output.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4808974/test_output.zip)

**Comment by sschmidTU** [comment]
Done.

![image](https://user-images.githubusercontent.com/33069673/86415161-7aeb2a00-bcc6-11ea-8447-9423b9fda5d3.png)

by the way, try this option:
```js
osmd.setOptions({renderSingleHorizontalStaffline: true})
```

Otherwise your huge one measure with 50 or so notes will not fit on the page, and the notes will be squeezed.
(if you want to try this in our demo, you should set that option in the index.js, otherwise you won't get the horizontal scrolling bar)

I hope you don't also need longa (long) and maxima, because Vexflow doesn't seem to support them (though i could be wrong)

**Comment by sschmidTU** [comment]
brevis rest also seems to work:

![image](https://user-images.githubusercontent.com/33069673/86416014-1b424e00-bcc9-11ea-90e9-f356454ff692.png)

(this is after the second group of two eights in the sample above)

**Comment by sschmidTU** [comment]
by the way, you can also write measures and then remove the barlines (set barline none), see here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/391#issuecomment-543817518

that way, you don't need to use renderSingleHorizontalStaffline, and can have line breaks (new/multiple systems).

**Comment by RobbStarkAustria** [comment]
Hi Simon,

thank you for your solution. But I have the problem that I get this only work on your demo repository cloned and started as webpack. If I use the react component with the actual node module from npm installed the brevis note is shown as whole note.

The option you mentioned is set and working, but still no brevis in score. 

What can I do to get the react version work?

Thanks

**Comment by sschmidTU** [comment]
Yes, this is not released yet, just merged to develop. We'll release a new version soon, then you can use it from npm.

Meanwhile, you could run `npm run build` on osmd and copy the .min.js from the build folder to your npm-modules/opensheetmusicdisplay/... folder for testing.

**Comment by RobbStarkAustria** [comment]
Yes! This solution works as expected!

Thank you so much!
