### ISSUE TITLE
Handling tempo marking changes

### ISSUE THREAD

**Issue by MilesMorel** [opensheetmusicdisplay/opensheetmusicdisplay#804]
Sheet music with multiple tempo markings lose their coordinates on the score and end up rendering overlapped in the upper-left corner. Musescore handles it fine so I don't think there is an error in the musicxml.

Here is an example score I tested on the OSMD demo.
[A_New_Beginning.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4814162/A_New_Beginning.musicxml.zip)

**Comment by bneumann** [comment]
Musescore:
![image](https://user-images.githubusercontent.com/2605131/89122368-d62b5a80-d4c6-11ea-948b-a12b988cc6dc.png)


OSMD:
![image](https://user-images.githubusercontent.com/2605131/89122398-0b37ad00-d4c7-11ea-8adb-ac5f7d3a0b1f.png)

**Comment by bneumann** [comment]
It actually looks ok for me. Can you maybe show an screenshot of your rendering?

**Comment by bneumann** [comment]
Whoops. You meant TIME signature not the timing. Okay yeah I see that. Looking into it

**Comment by MilesMorel** [comment]
Great work @bneumann! Many thanks!

**Comment by sschmidTU** [comment]
added OSMD Function Test - Metronome Marks to samples.
![image](https://user-images.githubusercontent.com/33069673/89199237-9049c180-d5ae-11ea-882c-4988ee1626e0.png)
