### ISSUE TITLE
Slides for Tabs (Guitar)

### ISSUE THREAD

**Issue by momolarson** [opensheetmusicdisplay/opensheetmusicdisplay#814]
Requested Feature:

VexFlow Class: 

https://github.com/0xfe/vexflow/blob/master/src/tabslide.js

Music XML Element: 

https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-slide.htm

Samples from Vex Flow Test Page: https://www.vexflow.com/tests/

![VF_TabSlide](https://user-images.githubusercontent.com/43911543/85867926-d9744d80-b786-11ea-957d-49de14f78bdc.JPG)

**Comment by sschmidTU** [comment]
@momolarson This would be great to have, though i have to admit we're quite involved with other features right now. Do you think you could implement this (or #813)?

**Comment by momolarson** [comment]
yeah, I am working on it!  I do have some implementation questions I'd like to pass by you, would it be best to start that up on gitter?

**Comment by sschmidTU** [comment]
Yes, if it's not necessarily permanently relevant and encyclopedic like your first comment, gitter is great, especially for quick back-and-forth!
https://gitter.im/opensheetmusicdisplay/opensheetmusicdisplay

**Comment by bneumann** [comment]
@sschmidTU: I will close this as it is merged
