### ISSUE TITLE
Wrong slur layout at Clarinet Quintet measure 9

### ISSUE THREAD

**Issue by matt-uib** [opensheetmusicdisplay/opensheetmusicdisplay#815]
![slur-on-system-break](https://user-images.githubusercontent.com/17180665/86129271-b7f6c700-bae2-11ea-96c1-965417d703fb.png)

in measure 9 the slur has the wrong direction - should be mirrored

**Comment by sschmidTU** [comment]
This was fixed some time ago.
<img width="146" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/e4dfca10-654c-4315-a8f0-f73711f96385">
