### ISSUE TITLE
Vexflow Note formatting and spacing improvements

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#820]
Some work has already been done:
`feat(Spacing): optimize vexflow voice spacing/scaling, refactor` 817762a593aeb8bd13b49e550203b28ece698843

A discussion of the Vexflow 3.x formatter, which sometimes doesn't layout measures as regularly as 1.2.93, especially with half notes:
https://github.com/0xfe/vexflow/issues/798

An interesting comment from the Vexflow creator on notes overlapping the measure and calling getMinTotalWidth():
https://github.com/0xfe/vexflow/issues/778#issuecomment-616197758

It looks like for now we should stick to Vexflow 1.2.93 in most cases. There are also some issues with tremolos in 3.x.

**Comment by fredmeister77** [comment]
Perhaps good to discuss... I switch to use formatToStave function vs. format - This corrects the beginning measure having extra space and seems to help the other measures. I'm just not sure if this is short-sighted or there are other issues, so committed for now so it can be reviewed and discussed.

**Comment by sschmidTU** [comment]
if `formatToStave` is the solution, that's brilliant! I didn't have that function in my mind.
I'll have a thorough look at the visual regression diffs. If it's better in most cases and doesn't have severe drawbacks, let's use it.

**Comment by sschmidTU** [comment]
So, for compact scores with only one voice/instrument these settings are great to make them really compact:

![image](https://user-images.githubusercontent.com/33069673/86823345-0846c980-c08d-11ea-99be-57fe05f7a444.png)

but it seems like we shouldn't use this as default settings, some scores with piano and/or multiple instruments have some rendering issues:

Mozart - An Chloe
![image](https://user-images.githubusercontent.com/33069673/86841571-67fc9f00-c0a4-11ea-9707-97b966d43316.png)

Clementi Sonatina 36/1/1:
![image](https://user-images.githubusercontent.com/33069673/86842327-52d44000-c0a5-11ea-83d8-6721624518ba.png)


OSMD Function Test Grace Notes:
![image](https://user-images.githubusercontent.com/33069673/86842195-24566500-c0a5-11ea-934e-e525f8b79605.png)

OSMD Function Test Tabulature:
![image](https://user-images.githubusercontent.com/33069673/86842393-697a9700-c0a5-11ea-8635-98306777c280.png)

Most of the scores work well though, so we could have this set by an option, like in the existing `compacttight` mode, or maybe it should be a separate option.

Though in any case, every user can set these parameters themselves anyways.

I can implement this option setting myself, if you don't mind.

**Comment by fredmeister77** [comment]
Sure, that is fine

**Comment by sschmidTU** [comment]
This is merged to develop now.
Before the merge, i made it so that the current settings in this branch are only applied in compacttight mode,
and i set the default multiplier and addend back to 0.85 and 3.0, which is closer to the original 1.0 and 5.0, to make some scores a bit less cramped, e.g. Clementi:
![image](https://user-images.githubusercontent.com/33069673/87716049-8ce0c880-c7ae-11ea-8100-a4ae6fc6ca1d.png)

the (red) eights were a bit too compacted and too far from the ending barline.

But we still have more compact scores and options to make it even more compact (compacttight mode) or set the parameters oneself (osmd.rules.VoiceSpacingMultiplier and VoiceSpacingAddend).

**Comment by sschmidTU** [comment]
Relevant parameters if you want to change the spacing:

```js
  osmd.EngravingRules.VoiceSpacingMultiplier // default 0.85, 0.65 in compacttight mode
  osmd.EngravingRules.VoiceSpacingAddend // default 3.0, 2.0 in compacttight mode
```
