### ISSUE TITLE
quasar - osmd - changing display-size

### ISSUE THREAD

**Issue by noysealyzer** [opensheetmusicdisplay/opensheetmusicdisplay#824]
..how can I prevent these thousands of Errors, which appear when I'm changing the display-size..​ 

Error: <path> attribute d: Expected number, "M236.5536 NaNL236.5536 NaN…".
they're always on: opensheetmusicdisplay.min.js?2938:1

..there doesn't seem to be something like 'playbackEngine.reset'? 

..I'm using  https://quasar.dev/vue-components/resize-observer  but don't know the Command to reset the Engine..

**Comment by sschmidTU** [comment]
This is output by Vexflow, which seems to be getting NaNs somewhere, which can happen for some samples, though it shouldn't of course.
It's not so easy to disable console.logs by a specific javascript module, though you can google how to disable all console logs.
Maybe you can share a sample musicxml that reproduces this, then we can see in which OSMD/Vexflow function this occurs (probably some Vexflow render function, and handle NaNs there.

**Comment by sschmidTU** [comment]
Maybe you can also override console.log to filter out messages such as these.

**Comment by noysealyzer** [comment]
..I'm using 12 example scores and  the errors happen on all of them - for instance on  
"https://opensheetmusicdisplay.github.io/demo/sheets/MuzioClementi_SonatinaOpus36No3_Part1.xml" 

..but the errors also happen, when no score is loaded at all - after 'osmd' has been initialized..

**Comment by sschmidTU** [comment]
That's not the case for OSMD 0.8.2 in our demo.
https://opensheetmusicdisplay.github.io/demo/

Can you run osmd.Version in the console and tell me the result? Maybe you're using an outdated version?

**Comment by noysealyzer** [comment]
..it was:  "opensheetmusicdisplay": "^0.8.1" and as soon as I've upgraded the errors were gone..
..thank you so much for the hint - and I'd say: 'what a difference a day makes'.. .

**Comment by sschmidTU** [comment]
i'm glad it helped - we're constantly trying to improve OSMD :)

**Comment by noysealyzer** [comment]
..I'm happy to have gotten help so instantly - I want to program kindof a symbiosys between 
OSMD and all these<whom you certainly will know -suppose>: 
https://wim.vree.org/js3/xmlplay.html?test/vcftest_4v2.abc  -  with Menu in upper right corner
https://wim.vree.org/js3/xmlplay_readme.html  similiar to Your handling Soundfonts
https://wim.vree.org/js3/xmlplay_index.html - with a download at the bottom
..the man all behint this:
https://github.com/notator

thanks once again

**Comment by sschmidTU** [comment]
My pleasure, good luck!
Though i should mention that we're working on a dedicated project to bring audio playback to OSMD right now (open source), see #258 (though we haven't given a lot of updates recently).
Of course, that doesn't need to stop you from any projects of your own.
