### ISSUE TITLE
Slurs' placement

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#827]
I found that the direction of some slurs is often displayed in OSMD as the opposite of the direction set in the musicxmls. Here is a example:
<img width="757" alt="屏幕快照 2020-07-13 10 11 23" src="https://user-images.githubusercontent.com/50696364/87264309-42332800-c4f2-11ea-96fc-9708e5bfc17f.png">
![屏幕快照 2020-07-13 10 10 37](https://user-images.githubusercontent.com/50696364/87264325-4b23f980-c4f2-11ea-9025-7e4be805a92b.png)
[slurs_1.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4910259/slurs_1.zip)
Is there a good way to keep the direction of the slurs displayed in OSMD consistent with the direction set in musicxmls?
Looking forward to your answer. Thank you !

**Comment by sschmidTU** [comment]
Currently we calculate the slur direction ourselves, from what seems most reasonable (e.g. direction of the stems).
But we should at least give the option to take the slur direction from the XML.
This should be pretty simple, the responsible method seems to be `GraphicalSlur.calculatePlacement()`.

**Comment by JanvyHung** [comment]
@sschmidTU Thank you for your reply. I very agree with you that it is necessary to give the option to take the slur direction from the XML. Looking forward to the change.

**Comment by sschmidTU** [comment]
Fixed.
Slur direction is taken from XML by default now.
![image](https://user-images.githubusercontent.com/33069673/98293372-7b663b00-1fae-11eb-9155-8769273adf73.png)

New: `osmd.EngravingRules.SlurPlacementFromXML`, true by default (false would be old behavior).

Most of our samples look a lot better now,
e.g. An Chloe:
before:
![image](https://user-images.githubusercontent.com/33069673/98293499-b5cfd800-1fae-11eb-90c2-03fa6bd02471.png)

after:
![image](https://user-images.githubusercontent.com/33069673/98293444-a05aae00-1fae-11eb-993f-2747cd901809.png)

In a few cases our calculated direction in `GraphicalSlur.calculatePlacement()` was better, but in most cases, the XML had the better placement.

@JanvyHung sorry for the late response, but here is the fix!
