### ISSUE TITLE
Question about the display of  bpm symbol

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#828]
I found a question that the bpm symbols taken in unit beat other than quarter note  will be incorrectly displayed as quarter notes on osmd, as shown below, the dichotomy of the bpm symbol displays as a quarter note in OSMD.
![屏幕快照 2020-07-14 15 09 03](https://user-images.githubusercontent.com/50696364/87395486-0f695c80-c5e4-11ea-87ba-049c5eec8da3.png)
![屏幕快照 2020-07-14 15 09 33](https://user-images.githubusercontent.com/50696364/87395505-14c6a700-c5e4-11ea-91b7-4402c6410715.png)
And here are some examples about different bpm symbols.
[bpm_test.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4917113/bpm_test.zip)
Looking forward to your reply. Thank you very much.

**Comment by sschmidTU** [comment]
fixed.
![image](https://user-images.githubusercontent.com/33069673/87711537-acc0be00-c7a7-11ea-96d2-5b14158f724e.png)

this will be merged to develop soon, then released in the next version.

thanks for the report!
