### ISSUE TITLE
Render single horizontal staffline and center it

### ISSUE THREAD

**Issue by R-D-D-D** [opensheetmusicdisplay/opensheetmusicdisplay#830]
## Desired outcome
Hi, I'm building an app that flashes only one row of measures as the video progress. So I'll render part of the pieces at a time and dynamically change its content. It should look something like this.(this is done by purely vexflow, I'm abandoning this for OSMD)
![Screenshot (57)](https://user-images.githubusercontent.com/45935526/87851327-4b752800-c92a-11ea-991a-7b75d3a7fbac.png)

### I'm hoping to align the position of the stave as shown in the red line, the top space is decided by the measure which needs the most spaces at the top. 
My current setup:
```
        // drawFromMeasureNumber: 1,
        // drawUpToMeasureNumber: 2,
        fillEmptyMeasuresWithWholeRest: true,
        drawComposer: false,
        drawTitle: false,
        renderSingleHorizontalStaffline: true,
        drawPartNames: false,
        autoResize: true,
        drawMetronomeMarks: false,
        drawingParameters: 'compacttight'
```
![Screenshot (60) edited](https://user-images.githubusercontent.com/45935526/87851341-69db2380-c92a-11ea-83fa-6f3c5efa21ae.png)

### 1. 
I want to find where exactly is the position of the first horizontal line of the stave and from there position it to have fix top space across all measure so it appears smooth with the transition. However, the numbers in bounding box is really confusing, I do not understand what each value means and I couln't find it in the wiki nor any issues. 
![Screenshot (64)](https://user-images.githubusercontent.com/45935526/87851638-3352d800-c92d-11ea-872a-6578cf0ff12b.png)

I've tried the following during the transition but to no avail(basically render without actually drawing):
```
      let width = this.container.offsetWidth;
      if (this.rules.RenderSingleHorizontalStaffline) {
          width = 32767; // set safe maximum (browser limit), will be reduced later
      }
      console.log("[OSMD] render width: " + width);

      this.sheet.pageWidth = width / this.zoom / 10.0;
      if (this.rules.PageFormat && !this.rules.PageFormat.IsUndefined) {
          this.rules.PageHeight = this.sheet.pageWidth / this.rules.PageFormat.aspectRatio;
          console.log("[OSMD] PageHeight: " + this.rules.PageHeight);
      } else {
          console.log("[OSMD] endless/undefined pageformat, id: " + this.rules.PageFormat.idString);
          this.rules.PageHeight = 100001; // infinite page height // TODO maybe Number.MAX_VALUE or Math.pow(10, 20)?
      }
      this.graphic.reCalculate()
      var score = document.getElementById('score')
      score.style.top = `${(this.osmd.graphic.musicPages[0].boundingBox.borderMarginTop) * 10 * -1}px`
```

### 2 
I'm dynamically creating an element and give it absolute property to let it overlay the video player. However, I get height to be infinity and a warnming `Warning: height of Infinity exceeds CanvasBackend limit of 32767. Cutting off score.` when I remove the `renderSingleHorizontalStaffline: true` option. 
![Screenshot (65)](https://user-images.githubusercontent.com/45935526/87851639-38b02280-c92d-11ea-87d1-372949f78d4c.png)

My code: 
```
      var score = document.createElement("div")
      score.setAttribute('id', `video-score-${this.lesson.id}`)
      score.style.position = "absolute";
      score.style.background = "#FAFAFA";
      score.style.top = "0";
      score.style.left = "0";
      score.style.right = "0";
      this.osmd = new OpenSheetMusicDisplay(score, {...})
      var wrapper = document.getElementById('wrapper')
      wrapper.appendChild(score)
```

### 3 
As can be seen in the desired outcome, the score displayed span over the full width, is there a way to set the canvas to be 100% width of its container while only displaying the chosen measure?

Thanks!

**Comment by shadrachtuck** [comment]
try osmd.graphic.musicSheet.staves[0].stafflineCount = 1
it should automatically center

**Comment by shadrachtuck** [comment]
but it will only render one staff line. I think thats what you're trying to achieve though, no?

**Comment by R-D-D-D** [comment]
Hi, thanks for your reply. 

I think I didn't communicate very well. What I meant was:
![Screenshot (71)](https://user-images.githubusercontent.com/45935526/89126598-61cdd700-d519-11ea-825b-1f3f6c852f69.png)
![Screenshot (72)](https://user-images.githubusercontent.com/45935526/89126600-64c8c780-d519-11ea-8e97-9dfe212e338c.png)

given these two different bars, the bars are empty yet the y-displacement is different, so it is not smooth for displaying it continuously. Is there a way to make these two different set of measures to have the same y-displacement?

Thanks.

**Comment by sschmidTU** [comment]
@R-D-D-D can you share both samples? Do they have different titles/composers/credit tags? Try deleting those.
It may be that we add some height depending on credit labels, that probably shouldn't happen.

**Comment by R-D-D-D** [comment]
Both of them belong to the same file, it is just different measures of that file. I realise it is because the measure number change. When they are one digit(0-9) it's the same as the first one, when it reaches 11, there is some extra height.
