### ISSUE TITLE
Weird spacing of notes

### ISSUE THREAD

**Issue by R-D-D-D** [opensheetmusicdisplay/opensheetmusicdisplay#831]
When given the option renderSingleHorizontalLine and autoresize, the notes will shrink upon calling `render()` twice. More specifically, it should be the function `recalculate()`

To reproduce, go to [codepen](https://codepen.io/r-d-d-d/pen/MWKzEyJ?editors=1011)

## correct version
![Screenshot (66)](https://user-images.githubusercontent.com/45935526/87866845-fcc29f00-c9b8-11ea-9147-02ac854ee9a3.png)

## incorrect version
![Screenshot (67)](https://user-images.githubusercontent.com/45935526/87866850-02b88000-c9b9-11ea-81b6-ea0aaa7615c4.png)

**Comment by bneumann** [comment]
Hi there,

unfortunatly the file has been removed from your server so your codepen isn't working anymore. I tried a music xml with the same notes on my machine and it worked, even with the same options you set.

Can you trie and reproduce it again? I will look into it then

**Comment by R-D-D-D** [comment]
Hi there, thanks for your reply. I've uploaded the file again, I think it is because there are so few notes in one bar. 

You can take a look again at codepen, it's up now. Thanks

**Comment by bneumann** [comment]
Hey @R-D-D-D, I found your issue. It was something in the 0.8.2 version of OSMD. If you update the codepen to either explicitly use 0.8.3 or just ```https://unpkg.com/opensheetmusicdisplay``` It works fine.

Closing this here

**Comment by bneumann** [comment]
One last thing: You are using axion in your example, that is stricly speaking not necessary. You could actually just call OSMD like so:

```js
const url = "https://rhythm-academy.s3-ap-southeast-1.amazonaws.com/twinkle-twinkle-little-star.musicxml";

osmd.load(url).then(() => {
  osmd.render()
  osmd.render()
})
```

We take care of the loading internally using AJAX. If you don't won't to bloat your code you should use this solution
