### ISSUE TITLE
Divide system in a moderate proportion

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#833]
when I use "newSystemFromXML" option and It has four measure in first system,
system not divided in a moderate proportion

![1](https://user-images.githubusercontent.com/56290540/87900255-ce16f800-ca8e-11ea-97de-b1f253ca8cec.png)
↑ OSMD

![2](https://user-images.githubusercontent.com/56290540/87900442-55646b80-ca8f-11ea-8d6b-b515319bd5e6.png)
↑ Sibelius

Or is there a way to fix this manually? 
(like set up a specific measure width or scale)
Please let me know if there's a way.

Thanks

**Comment by sschmidTU** [comment]
FixedMeasureWidth option now available (in next release), see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1314.
