### ISSUE TITLE
Composer line-height?

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#835]
when composer is written in multiple lines,
I want more space between the lines
but I couldn't find the relevant option.

It would be a great help to add this option.
thanks

**Comment by sschmidTU** [comment]
A sample would be OSMD Function Test - Labels:

![image](https://user-images.githubusercontent.com/33069673/88686472-6b110b00-d0f7-11ea-83b0-225a302dbc6f.png)

We could make a general option for extra space between lines, or a specific option for composer labels only.

**Comment by sschmidTU** [comment]
Done. Merged to develop, will be in the next release.

```js
osmd.setOptions({spacingBetweenTextLines: 5});

// alternatively:
// osmd.EngravingRules.SpacingBetweenTextLines = 5;
```

This is with a spacing of 5:
![image](https://user-images.githubusercontent.com/33069673/89303228-314a8200-d66c-11ea-9ba0-c37b054e4d55.png)
(OSMD Function Test - Labels)

**Comment by sschmidTU** [comment]
Thanks to @anita2822 for the implementation!

**Comment by djae88** [comment]
Thanks for Excellent work!
