### ISSUE TITLE
The lyrics are sometimes out of line

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#837]
I find some lyrics are sometimes out of line

I'm sorry that the example is not english (But It's best to see this problem)
![example](https://user-images.githubusercontent.com/56290540/88257161-1c7aff80-ccf8-11ea-87dc-4b6ece5a62f8.png)

![eng](https://user-images.githubusercontent.com/56290540/88258103-4a614380-ccfa-11ea-82cb-64e9822226e4.png)
↑English
![kor](https://user-images.githubusercontent.com/56290540/88258105-4b927080-ccfa-11ea-854e-55828f96e57a.png)
↑Korean

It's little difficult to see, when lyrics are English
so I thought it was only problem when lyrics are korean
But when I tested it in another language, I got the same result.
![china](https://user-images.githubusercontent.com/56290540/88258118-53521500-ccfa-11ea-9f2b-61fca5f0b9f8.png)
↑Chinese

And I found out that this problem only happens 
when the note is alone and the stem is upward.

Thanks

**Comment by sschmidTU** [comment]
Sample?
I think this was fixed by #1407
