### ISSUE TITLE
drawUpToMeasureNumber causes errors when the slur is not finished

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#838]
![image](https://user-images.githubusercontent.com/56290540/88262031-5fda6b80-cd02-11ea-83fc-0a9e20aab743.png)

when the slur is over the measure and break it with "drawUpToMeasureNumber" option (in example it will be '2')

This causes errors below.
![1](https://user-images.githubusercontent.com/56290540/88262172-a4fe9d80-cd02-11ea-88d7-be3c62cacec4.png)

**Comment by sschmidTU** [comment]
(@anita2822 check in MusicSheetCalculator.calculateLyricExtend(), check if the variable on which .Measures is accessed is undefined. If it is, make that evaluation undefined, e.g. `ParentStaffLine?.Measures` will return undefined if ParentStaffLine is undefined. this will prevent the error)

**Comment by sschmidTU** [comment]
@djae88 do you have a sample to test this on?

**Comment by djae88** [comment]
@sschmidTU I'm sorry I'm late, here is test sample xml!
[[Sample] Eric Benet - Hurricane.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5035529/Sample.Eric.Benet.-.Hurricane.zip)

**Comment by djae88** [comment]
I figured out something for myself and I think I was wrong
The error did not go away even if I disabled the slur 
but there was no error when disable the `<extend/> `
![image](https://user-images.githubusercontent.com/56290540/89853114-871ead00-dbcb-11ea-8378-2e67a6416359.png)
http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#CT-MusicXML-extend.htm?Highlight=extend
http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-lyric.htm?Highlight=extend

I'm not sure yet, so I haven't changed the title
When this became clear, You'd better change the title

Best wishes

**Comment by sschmidTU** [comment]
This is fixed on the current develop, not sure what exactly fixed it (or when that happened).
![image](https://user-images.githubusercontent.com/33069673/90277758-6faf2080-de66-11ea-8cc6-ec6d1a487bac.png)

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/90279212-11d00800-de69-11ea-9331-c49a77c88d81.png)

I forgot for a moment that this only happened when `osmd.setOptions({drawUpToMeasureNumber: 2})`.
