### ISSUE TITLE
Showing Cursor in Raw Javascript Usage Example

### ISSUE THREAD

**Issue by mehra71** [opensheetmusicdisplay/opensheetmusicdisplay#840]
Hello,

I know this is not an issue and is just a question, but I did not find the answer in the documentations.
I am trying to show the cursor on the OSMD Raw Javascript Usage Example, but I can not make it work.
I tried adding this code to the indexHTTHServer.html, but that did not work:

```
var cursor = new Cursor('osmdCanvas', openSheetMusicDisplay);
cursor.show();
```

Here is the full code:

```
<html>
<head>
	<title>OSMD Raw Javascript Usage Example</title>
</head>
<body>

<script src="opensheetmusicdisplay.min.js"></script> 
<div id="osmdCanvas"/>

<script>
  var openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdCanvas");

  openSheetMusicDisplay.load("Saltarello_sample.musicxml").then(
    function() {
		openSheetMusicDisplay.zoom = 0.65;
		
		var cursor = new Cursor('osmdCanvas', openSheetMusicDisplay);
		cursor.show();

        openSheetMusicDisplay.render();
    }
  );
</script>

</body>
</html>
```

Any help would be really appreciated.

**Comment by sschmidTU** [comment]
You definitely need to show the cursor after OSMD has rendered. Before that, there's nothing to show the cursor on.

**Comment by mehra71** [comment]
Thank you for your answer.
I tried this code, but the cursor is still not visible:

```
openSheetMusicDisplay.render();
		
var cursor = new Cursor('osmdCanvas', openSheetMusicDisplay);
cursor.show();

```

**Comment by sschmidTU** [comment]
Ah, a cursor should be automatically created by OSMD, so you don't need to create one yourself.
So try removing the new cursor line and instead after osmd.render() do osmd.cursor.show().

**Comment by mehra71** [comment]
Works now. Thank you.
