### ISSUE TITLE
Music sheet doesn't end at the right end of the line

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#842]
![image](https://user-images.githubusercontent.com/56290540/88879420-2dca8b80-d265-11ea-8242-0b6671dd0666.png)
↑ OSMD Demo

Music sheet must end at the right end of the line (in common)
but in OSMD, if there's not enough notes or lyrics in the system, 
sheet doesn't end at the right end of the line

using `newSystemFromXML: true` doesn't work when there's no measure anymore in the next line(system)

If making it work even when it's last, will save me a lot!
Thanks :)

**Comment by bneumann** [comment]
Should work with the PR:

![image](https://user-images.githubusercontent.com/2605131/89122080-c6127b80-d4c4-11ea-8854-5b0dc771a2bf.png)

You need to set the "StretchLastSystemLine" option to true as in the screenshot. Default is the current behaviour

**Comment by sschmidTU** [comment]
PR is merged.

Note that this can also be fixed by a JustifiedMusicSystemBuilder. (justification = blocksatz)

**Comment by sschmidTU** [comment]
renamed StretchLastSystemLine to stretchLastSystemLine in OSMDOptions (consistency) (though it's uppercase in EngravingRules).

**Comment by djae88** [comment]
Great work! This saved my day!
