### ISSUE TITLE
Bug about the display of ties of chords

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#844]
I found that the ties of the chords with multiple sustains has wrong displays , just like the following pic shows:
![image](https://user-images.githubusercontent.com/50696364/88889300-79376680-d272-11ea-94d0-e51f1fa3b757.png)
[tie_test.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4999277/tie_test.musicxml.zip)

**Comment by bneumann** [comment]
There we go:

![image](https://user-images.githubusercontent.com/2605131/89121573-3bc81880-d4c0-11ea-9ef8-efa58790c1d4.png)

**Comment by JanvyHung** [comment]
bravo!👍&nbsp;

--------------原始邮件--------------
发件人："Benjamin Giesinger "<notifications@github.com&gt;;
发送时间：2020年8月2日(星期天) 晚上7:01
收件人："opensheetmusicdispla" <opensheetmusicdisplay@noreply.github.com&gt;;
抄送："黄天晟 "<tiansheng.huang@musetk.com&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [opensheetmusicdisplay/opensheetmusicdisplay] Bug about the display of ties of chords (#844)
-----------------------------------

 

 
There we go:
