### ISSUE TITLE
Scrolling to the cursor does not work on demo page

### ISSUE THREAD

**Issue by mehra71** [opensheetmusicdisplay/opensheetmusicdisplay#849]
Hello,

On release of the version 0.7.1 it's written that the cursor auto scrolls down the page. The video on this page shows that the auto scrolling works fine on the demo page:

https://opensheetmusicdisplay.org/2019/08/27/osmd-0-7-1-with-its-brand-new-features/

But the the scrolling does not work on the demo page now:

https://opensheetmusicdisplay.github.io/demo/

Which release is used in the demo page use? Does the latest release (0.8.3) support the scrolling option?

**Comment by sschmidTU** [comment]
You have to set the option to enable that behavior:
```js
osmd.setOptions({followCursor: true});
```
Also, at the moment, this only works by clicking on Next in our GUI or by calling `osmd.cursor.next()` in the console, not sure why.

You can check the version by typing `osmd.Version` in the console. The demo uses the last released version (or master branch tag).
