### ISSUE TITLE
Accessing <text/> SVG elements for tablature notes

### ISSUE THREAD

**Issue by MilesMorel** [opensheetmusicdisplay/opensheetmusicdisplay#850]
In the SVG there is no distinction between <text> elements that are tab notes, and <text> elements that are measure numbers or other text labels. This makes note highlighting for guitar tablature pretty complex.

If the <text> elements in the SVG had classnames like other types of notes (.vf-stavenote), it could be achieved easily. Could OSMD please add a classnames to tab notes like ".osmd-tabnote" or ".vf-tabstavenote" for example? 

Or perhaps there is another way to reliably access the list of tab note svg elements that I missed?

**Comment by sschmidTU** [comment]
This needs to be adjusted in Vexflow.
I patched it in manually:
![image](https://user-images.githubusercontent.com/33069673/89210388-4ff33f00-d5c0-11ea-8ebc-f8f710458ef1.png)

this is tabnotejs:draw() (i added the two lines with comments):
```js
  draw() {
    this.checkContext();

    if (!this.stave) {
      throw new Vex.RERR('NoStave', "Can't draw without a stave.");
    }

    if (this.ys.length === 0) {
      throw new Vex.RERR('NoYValues', "Can't draw note without Y values.");
    }

    this.setRendered();
    const render_stem = this.beam == null && this.render_options.draw_stem;

    this.context.openGroup('tabnote', null, { pointerBBox: true }); // added for osmd#850
    this.drawPositions();
    this.drawStemThrough();

    const stem_x = this.getStemX();

    this.stem.setNoteHeadXBounds(stem_x, stem_x);

    if (render_stem) {
      this.context.openGroup('stem', null, { pointerBBox: true });
      this.stem.setContext(this.context).draw();
      this.context.closeGroup();
    }

    this.drawFlag();
    this.drawModifiers();
    this.context.closeGroup(); // added for osmd#850
  }
```

I can patch this in manually for the next release.
I'll add a pull request to Vexflow so it's in their next version (though we can't yet use vexflow 3.x because of formatting).

**Comment by sschmidTU** [comment]
This is now built in to the new OSMD 0.8.4.
This still needs to be patched in manually by the one building OSMD, if using Vexflow 1.2.93, but at least i added the patch files to the repository in `src/VexFlowPatch/`.

**Comment by MilesMorel** [comment]
Thank you so much! You're the best!!
