### ISSUE TITLE
About the position of the staffentries 

### ISSUE THREAD

**Issue by JanvyHung** [opensheetmusicdisplay/opensheetmusicdisplay#854]
I found that the  positions of the staffentries , which in the measures with a clef in the end, have a little offset . It just like the example shows. Could you modify the wrong positions of these staffentries to align with the notes? 
![image](https://user-images.githubusercontent.com/50696364/89283862-74aeeb80-d680-11ea-87e6-ece8e66f6553.png)

**Comment by conde2** [comment]
I have the same issue.

**Comment by sschmidTU** [comment]
Sample?
I think this was fixed.
I can't reproduce this with a simple sample.
<img width="325" alt="image" src="https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/assets/33069673/332883a5-6fad-44ff-9126-61a72b7a32c9">
[test_staffentry_xpos_clef.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12651973/test_staffentry_xpos_clef.txt)
