### ISSUE TITLE
when webview load osmd,prompt Buffer 12 not found.

### ISSUE THREAD

**Issue by ifredom** [opensheetmusicdisplay/opensheetmusicdisplay#856]
when i use  webview load osmd for render, it Will prompt me `Buffer 12 not found.`

![image](https://user-images.githubusercontent.com/13759936/89504882-55889900-d7fb-11ea-801b-6a46b580c187.png)

**Comment by sschmidTU** [comment]
That is strange, i haven't seen that message before, and i don't know why it would say "buffer 12".
Does OSMD still load and render? It looks like this is just an info message. In that case, i'd ignore it.

**Comment by ifredom** [comment]
osmd will load and render, this warning is very annoying~~~
