### ISSUE TITLE
Issue with GetNearestNote when using mouse-click coordinates

### ISSUE THREAD

**Issue by nitzanrh** [opensheetmusicdisplay/opensheetmusicdisplay#857]
HI guys,

I'm trying to implement some sort of clicking behaviour with OSMD (highlighting measures / notes when clicked)
Here is my code:

    function printMousePos(event) {
        let units = opensheetmusicdisplay.unitInPixels;
        let xpos = event.clientX / units;
        let ypos = event.clientY / units;

        let clickPointF2D = {x: xpos, y: ypos};
        let maxDist = {x: 5, y: 5};
        console.log(osmd.GraphicSheet.GetNearestNote(clickPointF2D, maxDist));
    }

This code is being called after loading XML file and calling osmd.render()

However regardless which values I put into clickPointF2D or MaxDist (real mouse click or random integers), I don't get any values from GetNearestNote

I've lookied into issue #504 but still haven't managed to solve this issue.

Any help would be appreciated 👍
Nitzan

**Comment by sschmidTU** [comment]
I guess you have to convert from SVG coordinates to screen coordinates first by creating the inverse of this function, [see here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/504#issuecomment-581110586):
```js
static domToSvg(svg, point) {
		var pt = svg.createSVGPoint();
		pt.x = point.x;
		pt.y = point.y;
		var sp = pt.matrixTransform(svg.getScreenCTM().inverse());		
			return {
				x: sp.x,
				y: sp.y
		};
```

To test your OSMD coordinates, you can use `VexFlowMusicSheetDrawer.DrawOverlayLine`, [see here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/651#issuecomment-577800543).

**Comment by fredmeister77** [comment]
We've actually had to do this very behavior as part of this feature: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/tree/feat/text/comment

Check out OSMDAnnotationsUIHandler, specifically 'listenForClick()'

This functionality will change/be refactored so can't be relied on to exist in this form, but this might work for you for what you need.

**Comment by sschmidTU** [comment]
This should be a relatively permanent link to the OSMDAnnotationsUIHandler at that commit state:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/da0a0a787ce5a84554ec33192a8fe88c6bc37b74/src/MusicalScore/Graphical/Annotations/OSMDAnnotationsUIHandler.ts

here are some relevant methods:
```typescript
    private listenForClick(): void {
        const self: OSMDAnnotationsUIHandler = this;
        this.container.onmousedown = (clickEvent: MouseEvent) => {
            self.container.onmousedown = undefined;
            const clickLocation: PointF2D = new PointF2D(clickEvent.pageX, clickEvent.pageY);
            const sheetLocation: PointF2D = self.getOSMDCoordinates(clickLocation);
            const nearestVoiceEntry: GraphicalVoiceEntry = self.aManager.getNearestVoiceEntry(sheetLocation);
            self.showCommentBox(clickLocation, sheetLocation, nearestVoiceEntry);
            self.showUI(clickLocation, sheetLocation, nearestVoiceEntry);
        };
    }

    public getOSMDCoordinates(clickLocation: PointF2D): PointF2D {
        const sheetX: number = (clickLocation.x - this.container.offsetLeft) / 10;
        const sheetY: number = (clickLocation.y - this.container.offsetTop) / 10;
        return new PointF2D(sheetX, sheetY);
    }

    public getAbsolutePageCoordinates(sheetLocation: PointF2D): PointF2D {
        const x: number = (sheetLocation.x * 10 + this.container.offsetLeft);
        const y: number = (sheetLocation.y * 10 + this.container.offsetTop);
        return new PointF2D(x, y);
    }
```

thanks @fredmeister77 for the hint!

**Comment by nitzanrh** [comment]
Thank you all for the prompt comments 👍 
> I guess you have to convert from SVG coordinates to screen coordinates first by creating the inverse of this function, [see here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/504#issuecomment-581110586):
> 
> ```js
> static domToSvg(svg, point) {
> 		var pt = svg.createSVGPoint();
> 		pt.x = point.x;
> 		pt.y = point.y;
> 		var sp = pt.matrixTransform(svg.getScreenCTM().inverse());		
> 			return {
> 				x: sp.x,
> 				y: sp.y
> 		};
> ```
> 
> (if you do and you've tested it, kindly share, then i could directly put them into OSMD)
> 
> (note:)
> 
> > SVG elements are in viewbox space, but mouse events are in client (screen) space. To convert between, them you need to use something like this on results from getBoundingClientRect (dom space) and inverse on coordinates from svg elements:
> 
> To test your OSMD coordinates, you can use `VexFlowMusicSheetDrawer.DrawOverlayLine` (`osmd.Drawer.DrawOverLayLine()`), [see here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/651#issuecomment-577800543).


I see what you mean regarding the conversion, however my concern is that regardless which values I use with GetNearestNote, I don't get any values.
Example:

        let maxDist = {x: 5, y: 5};
        for (let x = 0; x < 1000; x++) {
            for (let y = 0; y < 1000; y++ ) {
                const clickPointF2D = {x: x, y: y};
                console.log(osmd.GraphicSheet.GetNearestNote(clickPointF2D, maxDist));
            }
        }

This logs 1mil undefined. 
This leads to think that either:
A. There is something wrong with the way I set up OSMD (not sure why as all other functions are working fine; cursor etc.), or 
B. GetNearestNote expects some sort of float, or any values that are not between 1-1000, or
C. There is something broken with GetNearestNote





> This should be a relatively permanent link to the OSMDAnnotationsUIHandler at that commit state:
> https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/da0a0a787ce5a84554ec33192a8fe88c6bc37b74/src/MusicalScore/Graphical/Annotations/OSMDAnnotationsUIHandler.ts
> 
> here are some relevant methods:
> 
> ```ts
>     private listenForClick(): void {
>         const self: OSMDAnnotationsUIHandler = this;
>         this.container.onmousedown = (clickEvent: MouseEvent) => {
>             self.container.onmousedown = undefined;
>             const clickLocation: PointF2D = new PointF2D(clickEvent.pageX, clickEvent.pageY);
>             const sheetLocation: PointF2D = self.getOSMDCoordinates(clickLocation);
>             const nearestVoiceEntry: GraphicalVoiceEntry = self.aManager.getNearestVoiceEntry(sheetLocation);
>             self.showCommentBox(clickLocation, sheetLocation, nearestVoiceEntry);
>             self.showUI(clickLocation, sheetLocation, nearestVoiceEntry);
>         };
>     }
> 
>     public getOSMDCoordinates(clickLocation: PointF2D): PointF2D {
>         const sheetX: number = (clickLocation.x - this.container.offsetLeft) / 10;
>         const sheetY: number = (clickLocation.y - this.container.offsetTop) / 10;
>         return new PointF2D(sheetX, sheetY);
>     }
> 
>     public getAbsolutePageCoordinates(sheetLocation: PointF2D): PointF2D {
>         const x: number = (sheetLocation.x * 10 + this.container.offsetLeft);
>         const y: number = (sheetLocation.y * 10 + this.container.offsetTop);
>         return new PointF2D(x, y);
>     }
> ```
> 
> thanks @fredmeister77 for the hint!

Thanks for mentioning this. 
I'm actually working with the min.js file (un-minified of course) and not with the TS code (just because of my lack of good knowledge of handling TS and some experience with JS).
I'm working with version 0.8.3-release, and I can't find any mentions of listenForClick(). Do i need to manually build the JS file from the TS files in order to have access to it?

Cheers

**Comment by fredmeister77** [comment]
Ah! I forgot, I did have to do some fixing on that method as well (GetNearestNote). So you won't find any of the code linked above in the current release, it's a branch that I still have in development.

I will follow up later today or tomorrow with some more info on the fix. I am not at a computer at the moment.

**Comment by joshstovall** [comment]
I ran into some trouble with this, and getting the correct position while `osmd.Zoom` is not set to `1.0`.  Here is my work around, a slight change to the `getOSMDCoordinates` function. Be sure to divide by the `osmd.Zoom` to make it work.

```js
function getOSMDCoordinates (clickLocation) {
    const sheetX = (clickLocation.x  - this.container.offsetLeft) / 10 / osmd.Zoom;
    const sheetY = (clickLocation.y  - this.container.offsetTop) / 10 / osmd.Zoom;
    return new PointF2D(sheetX, sheetY);
}
```
Now it works perfectly. Spent some time figuring this out, it was a big headace while troubleshooting. Hopefully an update to OSMD could fix this in the future, maybe adding this `x / 10 / osmd.Zoom` logic to the `GetNearestNote()` function?
