### ISSUE TITLE
Rendering Text for Fingerings

### ISSUE THREAD

**Issue by mdubey96** [opensheetmusicdisplay/opensheetmusicdisplay#858]
Hey all,

I am having an issue with rendering text for fingerings on guitar music.
The two main issues are:
1. The letter "p" (used to stand for thumb) is always bolded to look like the dynamic "piano"
2. The spacing of the text ends up being in conflict with other types of text. I have tried changing the other text to various other "text types" (i.e. staff, system, etc.) but this still occurs.

<img width="308" alt="Screen Shot 2020-08-06 at 11 13 18 AM" src="https://user-images.githubusercontent.com/13424775/89567960-d33eab80-d7df-11ea-9fa6-1d8a06ed38b7.png">

Let me know if you know of any workarounds for these issues or if they are already resolved.

Best,

Mohit

**Comment by sschmidTU** [comment]
can you share an xml sample? 1-2 measures would be enough.
Since p is a guitar-only fingering, we haven't specifically supported yet. Can't you use 0?

**Comment by mdubey96** [comment]
Sure thing: here's the xml I was using.
Regarding fingerings, the standard is p, i, m, a for the right hand - 0 (or numbers in general) are not used.

[Ex 38.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5037581/Ex.38.xml.zip)

**Comment by sschmidTU** [comment]
This should be fixed now.
![image](https://user-images.githubusercontent.com/33069673/141302731-c6fa2a20-9f0c-4c7b-ae51-b814775cc14e.png)

It looks like `<words>text</words>` never has instantaneous dynamics like `p` or `sf`, those would be in `dynamics`, so we can disable the istantaneous dynamics detection in this case. Basically, the p was detected as a *piano* dynamic.
