### ISSUE TITLE
Is the 'lyricsYOffsetToStaffHeight' working?

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#865]
![image](https://user-images.githubusercontent.com/56290540/90038628-99e6ce00-dd00-11ea-97ce-57cb8e773b04.png)
↑ `openSheetMusicDisplay.EngravingRules.lyricsYOffsetToStaffHeight = 0;`

![image](https://user-images.githubusercontent.com/56290540/90038691-ad923480-dd00-11ea-8717-f0535f2a0205.png)
↑ `openSheetMusicDisplay.EngravingRules.lyricsYOffsetToStaffHeight = 20;`

I wanted to give more space between staff and lyric
and I found the 'lyricsYOffsetToStaffHeight but it didn't work ( I set this option before osmd.render)

If this option works well, What did I miss?

**Comment by sschmidTU** [comment]
Fixed. Yes, we did not use this EngravingRule before.

Keep in mind this is in OSMD units, so an offset of 20 would be 200 pixels.

This is offset 2:
![image](https://user-images.githubusercontent.com/33069673/90041390-83715000-dcc9-11ea-85d8-2f6a037cfad4.png)

This is offset 0 (default):
![image](https://user-images.githubusercontent.com/33069673/90041455-984de380-dcc9-11ea-96a7-729f60fbe215.png)
