### ISSUE TITLE
Some ornaments don't display properly (Mordent, glissando, wavy-line)

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#866]
![ornaments](https://user-images.githubusercontent.com/56290540/90046843-f6031f80-dd0b-11ea-94bc-5836b804c164.png)
↑ Finale

![osmd](https://user-images.githubusercontent.com/56290540/90046910-1501b180-dd0c-11ea-9aea-1f7901ccb461.png)
↑ OSMD

↓ XML code
![glissando and slide](https://user-images.githubusercontent.com/56290540/90047319-b2f57c00-dd0c-11ea-9fac-06de0f502c38.png)

![mordent and trill](https://user-images.githubusercontent.com/56290540/90050127-bdb21000-dd10-11ea-9a5b-5d4baecfd50c.png)

I could find Information about these ornaments in the xml chord
But glissando and slide are not showing
and mordent show inverted-mordent and inverted-mordent show mordent
and mordent placement didn't work
and the trill has wavy line but does not shown it

**Comment by sschmidTU** [comment]
can you share the sample again?

The ornaments that aren't showing aren't implemented yet (gliss wavy and straight, trill wavy line).

For the placement of the first movement, we can see if we can take it from the XML.

By the way, it's weird that Finale shows the inverted mordent without a vertical line through (and vice versa for mordent), an inverted mordent should have the vertical line.
https://dictionary.onmusic.org/terms/1804-inverted_mordent#:~:text=%5BEnglish%5D,ending%20on%20the%20main%20note.
![image](https://user-images.githubusercontent.com/33069673/90050307-4c556b80-dcd6-11ea-8fe9-36e6a93dd5a3.png)

**Comment by sschmidTU** [comment]
Glissandos already have an issue: #344
wavy-line issue: #657
(no samples there though)

**Comment by djae88** [comment]
Oh, I forgot to attach the file
[Ornaments test.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5064773/Ornaments.test.zip)

**Comment by djae88** [comment]
I just found about that mordent so I edited first comment
![image](https://user-images.githubusercontent.com/56290540/90050914-d8d14f80-dd11-11ea-8f87-82b26ccdcf52.png)
In Sibelius 
they say Inverted one has vertical-line through
So I thought OSMD was wrong

**Comment by djae88** [comment]
http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-inverted-mordent.htm
![image](https://user-images.githubusercontent.com/56290540/90051317-7a58a100-dd12-11ea-9c64-68f94028cc03.png)

Oh I just found about Inverted-mordent in MusicXML document

'm not a musician, I'm a programmer, so this kind of problem is confusing. Haha...

**Comment by sschmidTU** [comment]
Ah, yes, this seems to be the modern default, which changed in the 19th century.

> The precise meaning of mordent has changed over the years. In the Baroque period, a mordent was a lower mordent and an upper mordent was a pralltriller or schneller. In the 19th century, however, the name mordent was generally applied to what is now called the upper mordent, and the lower mordent became known as an inverted mordent.

https://en.wikipedia.org/wiki/Mordent

In any case, what's important is how MusicXML defines it, so we'll use that. Thanks for the hint!

**Comment by sschmidTU** [comment]
Actually, Vexflow got it "wrong", they aren't using the MusicXML definition, but the baroque one. So we'll just switch the Vexflow mordents we use.

**Comment by djae88** [comment]
I'm the one thanking you!
I hope to be a contributor someday but
I'm not very good at programming, My limit is to report like this
So thank you so much for answering me right away

**Comment by sschmidTU** [comment]
No problem. Good feedback is also worth a lot!

**Comment by djae88** [comment]
By the way I just read about 
Glissandos already have an issue: #344
wavy-line issue: #657
and I'm little worried that those issues were written quite a long time ago
So Can you give me a rough idea of when this will be implemented?

**Comment by sschmidTU** [comment]
What we implement is always a question of priorities. If you look at the issue list, you'll see that we have enough to do for quite a while. But if you look at the closed issues and commits, you'll also see that we get many things done all the time.

So, the question is, how relevant is this (and how difficult to implement?
I haven't seen that many scores using these features, except for the wavy-line maybe.
On the other hand, if they're implemented in Vexflow, they should be easy to add to OSMD.

Would you consider this important to you, more than many other issues?

**Comment by djae88** [comment]
I'm making a personal project with OSMD, and My Friends are music sheet writers
So I'm not very sure about difficult things about music, I asked them about this and they answered that
these features are often used in wind instrument and string instrument scores (like Saxophones and Violins)
I think It might not be used in recent songs but it seems quite common in classical music.
I hope this will be fixed while I'm looking for it, but I completely respect your choice.

**Comment by sschmidTU** [comment]
It looks like Vexflow can't put ornaments below the staffline yet. (at least in version 1.2.93)
But the placement code is now in OSMD.

The glissandi are already in Vexflow, so they should be relatively easy to implement.
As for the wavy trill lines, we may implement them soon anyways.

**Comment by sschmidTU** [comment]
the rest of the issues have their own issue (see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/866#issuecomment-673039481), closing as duplicate.
Mordent was fixed.
