### ISSUE TITLE
The 'double barline' not showing 

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#868]
![sibelius](https://user-images.githubusercontent.com/56290540/90245474-b6544900-de6d-11ea-8522-e90d874be23e.png)
↑ Sibelius

![image](https://user-images.githubusercontent.com/56290540/90245397-8f961280-de6d-11ea-925b-a38665482f02.png)
↑ OSMD

![image](https://user-images.githubusercontent.com/56290540/90245572-e4d22400-de6d-11ea-895f-92ed946a75e5.png)
↑ XML has infomation about barline.

musicXML Document about barline : 
http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#CT-MusicXML-barline.htm?Highlight=barline

Sample XML :
[Double Barline test.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5074363/Double.Barline.test.zip)

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/90260955-92344000-de4c-11ea-8d23-6a65895b9494.png)
