### ISSUE TITLE
In the tension chord, sus4 displayed as add4

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#873]
![image](https://user-images.githubusercontent.com/56290540/90471817-155dda80-e15a-11ea-88d1-5f8181fff6d3.png)
↑ Sibelius

![image](https://user-images.githubusercontent.com/56290540/90471773-ffe8b080-e159-11ea-8e59-4a4a99bf4db2.png)
↑ OSMD

in XML code
![image](https://user-images.githubusercontent.com/56290540/90471871-31fa1280-e15a-11ea-988b-82515e0a1793.png)
↑ Triad chord

![image](https://user-images.githubusercontent.com/56290540/90471943-5950df80-e15a-11ea-86f7-a121e895baf1.png)
↑ Tension chord

in Triad chord, It's easy to define with `<kind>suspended-fourth</kind>`
But, The Tension chord can't define with kind tag, So It's set up with `<degree>`
and I think OSMD dropped the subtract when it read `<degree>` .

**Comment by djae88** [comment]
I just found another similar problem about displaying Cmmaj9
![image](https://user-images.githubusercontent.com/56290540/90491394-d55b1f80-e17a-11ea-9b68-167fc4684bde.png)
↑ Sibelius
![image](https://user-images.githubusercontent.com/56290540/90491368-cc6a4e00-e17a-11ea-9f76-d81b8375d400.png)
↑ OSMD

mmaj7 chord is defined in musicxml as `<kind>major-minor</kind>`

but mmaj9 is not defined in musicxml So in Xml
![image](https://user-images.githubusercontent.com/56290540/90492011-a5f8e280-e17b-11ea-8609-0ebf5586ea19.png)
So OSMD read this Xml and literally display it

In this case, there is nothing wrong with the meaning but it makes chord name too long
So I have to fix it manually with `staffEntries[0].graphicalChordContainers[0].graphicalLabel.TextLines[0].text`
and It's little annoying
I think this case is a low priority So it's okay to put this off
But if it's not difficult to fix this one while you're fixing problem above, 
consider this one too, will be great help.
Thanks

**Comment by sschmidTU** [comment]
@djae88 can you share the samples again?

**Comment by djae88** [comment]
Oh, I always forgot.
Here's the sample xml
[sus4 test.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5093411/sus4.test.zip)
[Cmmaj9 test.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5093413/Cmmaj9.test.zip)

**Comment by infojunkie** [comment]
Maybe related: https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/930

**Comment by sschmidTU** [comment]
fixed in #933.

![image](https://user-images.githubusercontent.com/33069673/105731578-d6655980-5f2f-11eb-9836-df260ed8129c.png)
![image](https://user-images.githubusercontent.com/33069673/105731635-e41adf00-5f2f-11eb-951e-3bf3492045a8.png)
