### ISSUE TITLE
In the pick up measure, rest note displayed as whole rest note

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#874]
### pick up measure with rest note
![image](https://user-images.githubusercontent.com/56290540/90478458-231a5c80-e168-11ea-83d5-4b6114942f2a.png)
↑ Sibelius
![image](https://user-images.githubusercontent.com/56290540/90478916-d5eaba80-e168-11ea-92ab-7abf80ce5d59.png)
↑ OSMD

in this case, You may wonder if this is necessary but if the chord goes in from the second measure, it is necessary

### pick up measure with note
![image](https://user-images.githubusercontent.com/56290540/90479695-08e17e00-e16a-11ea-8a15-dcbf50153db3.png)
↑ Sibelius
![image](https://user-images.githubusercontent.com/56290540/90479709-0f6ff580-e16a-11ea-9277-fd111de4bc50.png)
↑ OSMD

It's working fine (I think making the pick up measure bigger seems to be another problem)

### pick up measure in sheet with 3 staves
![image](https://user-images.githubusercontent.com/56290540/90480969-fcf6bb80-e16b-11ea-8d13-099273786f7c.png)
↑ Sibelius
![image](https://user-images.githubusercontent.com/56290540/90481104-2b749680-e16c-11ea-8572-5bdb236ff754.png)
↑ OSMD

Xml files
[pick up measure(rest start).zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5088763/pick.up.measure.rest.start.zip)
[pick up measure(note start).zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5088764/pick.up.measure.note.start.zip)
[pick up measure(in sheet with 3 staves).zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5088765/pick.up.measure.in.sheet.with.3.staves.zip)

Best wishes

**Comment by sschmidTU** [comment]
Fixed in f1478a6e52c34b4ea3710be1cec197c3e445981f.

![image](https://user-images.githubusercontent.com/33069673/91209967-d35e0700-e70c-11ea-9db9-ab3359aa7da9.png)

Pickup measures were also merged into multiple rest measures, fixed now:
![image](https://user-images.githubusercontent.com/33069673/91210028-e83a9a80-e70c-11ea-9e36-cbbf435705c8.png)
