### ISSUE TITLE
How re-render the display based on key

### ISSUE THREAD

**Issue by dwarka-code** [opensheetmusicdisplay/opensheetmusicdisplay#886]
Current if i load XML it start with default key D but i want to switch it to E and render the display with this key

**Comment by ifredom** [comment]
change options, then  call render function

**Comment by sschmidTU** [comment]
This is called Transposing. Duplicate of #733 .

**Comment by dwarka-code** [comment]
guys can you give simple code how I can change the key and render based on key

**Comment by sschmidTU** [comment]
The OSMD Transposition plugin is now integrated into OSMD, see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/733#issuecomment-823530818.
(currently on the develop branch, will be released in the next OSMD version after 0.9.5)
