### ISSUE TITLE
render() running async and returning a promise?

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#892]
Hello currently the osmd.render() seems to not run async is it possible to run it async ?

Would be good if this function returns a promise telling when it has finished.

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/cb0012e0ad691eac30c1823c259f29ac033ba6fc/src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts#L186

**Comment by sschmidTU** [comment]
Why do you need it to be async? It's sync, so you can just execute it, and in the next line of code you know it's done.
If you still need it, you can write your own async function that executes render and returns Promise.resolve({}) after that.

**Comment by conde2** [comment]
You are right, I can wrap it around a promise, I was thinking to implement it while sending a progressbar of how much has loaded.
