### ISSUE TITLE
Is "No Key Signature" mode available when OSMD loads the musicxmlfile?

### ISSUE THREAD

**Issue by lianusmusic** [opensheetmusicdisplay/opensheetmusicdisplay#894]
My question is: I would need to display the sheet music with no Key signature, and the accidentals shown in the staff. Is this possible?
Thanks

**Comment by sschmidTU** [comment]
Not right now. This would need to be implemented as an option.
You can of course modify the MusicXML to not contain these things.

**Comment by sschmidTU** [comment]
@lianusmusic this is now supported as an option:
`osmd.rules.RenderKeySignatures = false;`

Mozart - An Chloe sample:
![image](https://user-images.githubusercontent.com/33069673/105765810-3d4b3880-5f59-11eb-89f3-9c39259ede8e.png)
