### ISSUE TITLE
Slur and beam overlap problem

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#895]
I found that when the lyrics were on the note, the slur is placed on top.
Even when the stem is up and there's beam.
And It causes overlapping problem

![image](https://user-images.githubusercontent.com/56290540/95038804-09c67300-070a-11eb-988f-7c7a0d1a7b3f.png)
(The first measure has lyrics and second measure has no lyrics)
[test slur placement.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5325210/test.slur.placement.zip)

I think it'll be solved if set it up in the same location
or take the slur direction from the XML will be great too. (for anyone who wants to put a slur on top of the beam. )

**Comment by sschmidTU** [comment]
It looks like for the placement it can be both `orientation="over/under"` or `placement="above/below"`.

https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-slur.htm

It looks like this would be solved by implementing #827 (slur placement).

**Comment by sschmidTU** [comment]
This is working as intended.
The XML has `orientation="over"` for the slurs. If you change it to `under`, the placement will be swapped.

Also, you can use `osmd.EngravingRules.SlurPlacementUseSkyBottomLine = true` to prevent overlaps for cases like this
(or apparently render twice, after which the skyline has been updated).
