### ISSUE TITLE
Iterator clone possibility to set endTimeStamp

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#896]
Hello,
I'm trying to see if the next note on the Staff has the same halfTone from the previous note.
I managed doing it creating an iterator from the current iterator and moving it to the next note sequence
```
    const iterator = this.osmd.cursor.Iterator.clone(this.osmd.cursor.Iterator.currentTimeStamp);
    iterator.moveToNext();
```

But I need to do it on every note, and cloning the iterator clones the entire piece, what is very time/processing expensive, I would like to be able to just clone 2 measures. So what I suggest is beign able to set endTimeStamp when cloning a iterator

OBS: there is no notesUnderCursor method like for MusicPartManagerIterator, not a problem because I can use CurrentVoiceEntries, but would be easier if it does have a notesUnderCursor method.

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/341341be81b3967f2b6be0a34b7ed07123465154/src/MusicalScore/MusicParts/MusicPartManagerIterator.ts#L20

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/341341be81b3967f2b6be0a34b7ed07123465154/src/MusicalScore/MusicParts/MusicPartManagerIterator.ts#L135

**Comment by conde2** [comment]
Forgot to say that I noticed a bug when using
```
    const test = this.osmd.cursor.Iterator.clone();
    console.log(test.currentTimeStamp);
```

It does not work as expected, it always set to the timestamp 0.

That is why I had to do this.osmd.cursor.Iterator.clone(this.osmd.cursor.Iterator.currentTimeStamp);

**Comment by sschmidTU** [comment]
The bug where clone() without arguments didn't set the startTimeStamp is now fixed.

For the endTimeStamp and clone performance, I pushed setting the endTimeStamp on the branch feat/iteratorEndTimeStamp.
But i'm not sure this will affect performance, because there isn't much in clone() that is performance intensive, and moveToNext() should be unaffected.
But you can try this build and see if the imperformance is improved:
[opensheetmusicdisplay.min.js_endTimeStamp_branch.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5336637/opensheetmusicdisplay.min.js_endTimeStamp_branch.zip)
You can check iterator.endTimeStamp there.
```js
const newIterator = osmd.cursor.Iterator.clone(undefined, osmd.cursor.Iterator.endTimeStamp)
console.log(newIterator.endTimeStamp)
```

**Comment by conde2** [comment]
I will check as soon as possible, my concern was this

```
            do {
                this.moveToNext();
            } while ((!this.currentVoiceEntries || this.currentTimeStamp.lt(startTimestamp)) && !this.endReached);
```

before having the endTimeStamp, when performing a clone() the this.endReached was only beign reached after this.moveToNext(); run the entire score.

Please correct me if I'm wrong, I'm learning the code, so maybe I'm saying something stupid.

**Comment by conde2** [comment]
Thanks, will check this as soon as possible.

**Comment by sschmidTU** [comment]
Ah, actually the endTimeStamp won't really have an effect in the clone function, unless it's smaller than the smartTimeStamp (which doesn't make sense).
```js
while ((someBool || this.currentTimeStamp.lt(startTimestamp)) && someOtherBool
```
Here only `this.currentTimeStamp.lt(startTimestamp)` is relevant, because as soon as it becomes false, which is when we are past the startTimestamp, the whole expression is false, and the while loop stops anyways.
This basically just moves the current time stamp to the start time stamp and stops there.
So the endTimeStamp is unnecessary for this purpose.

**Comment by sschmidTU** [comment]
![image](https://user-images.githubusercontent.com/33069673/95260755-8ac85c00-0829-11eb-9edc-14b2cfc56b29.png)

**Comment by sschmidTU** [comment]
So, cloning the iterator does not clone the entire piece, it keeps the same MusicPartManager object which already existed, which has the entire piece as having the mapping when to jump from each repetition etc.
Have you tried this and had bad performance?
What may still affect the performance is going to the startTimeStamp, we're iterating from the start of the piece through every note until we get to the startTimeStamp, so maybe that's what could be improved for performance, being able to start at a certain measure or something.

**Comment by conde2** [comment]
You are totally right, I didn't see the check for startTimeStamp I was looking only for the EndReached so I thought the cursor was going to move the entire score until reach the startTimeStamp.

Will make more investigations tomorrow on what is causing the performance issue on my code, maybe is something I'm doing wrong.

I'm still learning about how OSMD is structured, but enjoying it very much. Thanks for all the help, maybe I can contribute writing some snippets for the wiki, if it is needed.

**Comment by conde2** [comment]
Here is my code to detect if the next note has the same half tone from the previous note

```
    if (this.osmd.cursor.Iterator.EndReached) {
      return;
    }

    const cursor = this.osmd.cursor.Iterator.clone(this.osmd.cursor.Iterator.currentTimeStamp);
    const startMeasure = cursor.CurrentMeasureIndex;

    let needReduction = false;
    let maxAttemps = 50;
    while(!(cursor.EndReached || needReduction || cursor.CurrentMeasureIndex > startMeasure || maxAttemps <= 0)) {
      cursor.moveToNext();

      needReduction = cursor.CurrentVoiceEntries.some( (voice) => {
        return voice.Notes.some( (nextNote) => {
          if (nextNote.halfTone === note.halfTone) {
            return true;
          }
          return false;
        });
      });

      maxAttemps -= 1;
    }
```

**Comment by conde2** [comment]
Today I was able to test it better and seems that the problem was with my code, sorry for that.
The good news is that my tests showed that cloning the iterator has very little impact in the performance

```
    const previousTimestamp = + new Date();
    this.osmd.cursor.Iterator.clone(this.osmd.cursor.Iterator.currentTimeStamp);
    console.log("Time spent: ", +new Date() - previousTimestamp + "ms");
```

The tests showed me delays from 0ms to 3ms, the 3ms was when reaching a long repetition, but nothing to worry.
I will close the issue as the clone bug is solved and there is no problems with the performance.
