### ISSUE TITLE
Height does not update properly when options drawComposer: false

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#898]
I noticed that the canvas size is considering the height of Composer even if I start OSMD with drawComposer disabled

You can see in the images that the canvas wasnt "pushed up"

```
.score {
    height: 100%;
    margin: 0 10px;
}
```

```
  <div id="osmd-container" class="score"></div>
```

```
    this.osmd = new OpenSheetMusicDisplay(container, {
      autoResize: true,
      drawFingerings: true,
      drawTitle: false,
      drawSubtitle: false,
      drawPartNames: false,
      drawCredits: false,
      drawComposer: false,
      drawLyricist: false,
      renderSingleHorizontalStaffline: true,
      disableCursor: false,
      followCursor: true
    });
```

Also tried, but still have a gap in top

```
      drawingParameters: DrawingParametersEnum.compacttight,
```
![Captura de tela de 2020-10-08 16-35-31](https://user-images.githubusercontent.com/2137569/95505168-5321f700-0984-11eb-855e-3dd37623b71e.png)
![Captura de tela de 2020-10-08 16-35-05](https://user-images.githubusercontent.com/2137569/95505171-53ba8d80-0984-11eb-8a17-386321a1a51a.png)

**Comment by conde2** [comment]
Tried it in the OSMD demo, after learned from your tutorial how to use it (very useful)

![Uploading Captura de tela de 2020-10-08 17-10-15.png…]()

**Comment by sschmidTU** [comment]
Fixed, for the most part.

```js
osmd.rules.CompactMode = true
osmd.setOptions({
  drawCredits: false
})
```
![image](https://user-images.githubusercontent.com/33069673/95891757-cf05b000-0d85-11eb-85fa-ae2c71e7a165.png)

One little bug remains: If you first set the PageTopMargin to 0 and render, and then do the above, the extra top margin remains forever (unless you reload the piece, not just rerender).
Not sure why, this would need some extra looking into.

As long as you set compact mode (or `setOptions({drawingParameters: "compacttight"})`) etc. before rendering, this should work now.

**Comment by conde2** [comment]
```
osmd.rules.CompactMode = true
osmd.setOptions({
  drawCredits: false
})
```

Should I use like this or 

```
setOptions({drawingParameters: "compacttight"})
```

because rules is private in OSMD

```
Property 'rules' is private and only accessible within class 'OpenSheetMusicDisplay'.ts(2341)
```

https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/ecee3b4034c7c848a60229bfdaca4a8259547117/src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts#L80

**Comment by sschmidTU** [comment]
Right, the public getter for rules is EngravingRules. It's just faster to type rules in the console.
