### ISSUE TITLE
Problems with npm test

### ISSUE THREAD

**Issue by lpeppe** [opensheetmusicdisplay/opensheetmusicdisplay#90]
Hello,

first of all I want to thank you for this awesome project. I'm having a very annoying problem and I can't figure out how to solve it. I cloned the git repository in a folder on my local server, I executed npm install, but when I do npm test I get this error message:

![capture](https://cloud.githubusercontent.com/assets/16524788/20485234/f53f0b3c-affa-11e6-8d4d-561da60e2779.PNG)

Any idea how to solve it? It's driving me crazy...

**Comment by sebastianhaas** [comment]
I can't really tell the reason of the tests failing in your case unless you provide the full test log. If you could post it here, I might be able to find out the actual problem.

However, what are you trying to do in the long run? If you just want to use OSMD in your own projects, you probably don't need to run unit tests. Are you able to run `grunt build:demo` without errors?

**Comment by lpeppe** [comment]
[log.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/603808/log.txt)

Thanks for the fast reply. I need to integrate OSMD in another website for an university project. When I try to open the index.html file in the demo folder this is what I get.

![image](https://cloud.githubusercontent.com/assets/16524788/20486042/7d8840be-affe-11e6-9ff4-0dbd01c57a97.png)

**Comment by sebastianhaas** [comment]
You want to use the demo under `build/demo` not, `demo` on root. It's a bit counterintuitive I admit.

Please let me know if that worked for you! Also, if you intent to use it in your own website, you may want to use `grunt build:dist` to produce `build/osmd.min.js` (or `build/osmd.js`) which you can include in your page then.

**Comment by lpeppe** [comment]
Thanks a lot man, it worked like a charm! So I have to include only osmd.min.js in my website? Sorry but I'm very new to web development :D

**Comment by sebastianhaas** [comment]
You probably want to include OSMD using a basic tag like so:
```html
<script src="osmd-debug.js"></script>
```

You can then add custom JS to fire up a OSMD instance and load a music sheet. Basically you need to attach OSMD to a `div` on your page, like so
```
OSMD = new opensheetmusicdisplay.OSMD(yourdiv);
OSMD.load(yoursheet);
OSMD.render();
```

But just take a look at how it's done in the [demo page](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/master/demo/demo.js).

Re the test error, I think this is something we have to fix on our side, but since it's not a problem to you anymore I will continue dealing with it in a separate issue.

**Comment by lpeppe** [comment]
Awesome! Thanks a lot again 👍
