### ISSUE TITLE
Accidental not preserved within measure

### ISSUE THREAD

**Issue by infojunkie** [opensheetmusicdisplay/opensheetmusicdisplay#903]
The attached score [ya-labesyn.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5388249/ya-labesyn.zip) uses F half-sharp throughout. Here is the score rendered in Musescore:
![Musescore](https://user-images.githubusercontent.com/92977/96193436-0185e900-0efd-11eb-9414-75435881c583.png)

However, when dropping onto https://opensheetmusicdisplay.github.io/demo/, I get the following:
![OSMD](https://user-images.githubusercontent.com/92977/96193515-2bd7a680-0efd-11eb-8b5e-94b080bea4b8.png)

The difference is that the subsequent F's in a measure are rendered as natural, even though the MusicXML file does not specify any accidental for them. One would expect those notes to keep the same accidental as the first F.

**Comment by sschmidTU** [comment]
Fixed. Thanks for the report!

![image](https://user-images.githubusercontent.com/33069673/98159543-12fb5900-1edd-11eb-9555-1e8a0d6a90b6.png)

New test sample for quarter accidentals added:
![image](https://user-images.githubusercontent.com/33069673/98159472-f828e480-1edc-11eb-993e-522495b34b4f.png)
