### ISSUE TITLE
Background color doesn't fill the page for zoom < 1

### ISSUE THREAD

**Issue by MilesMorel** [opensheetmusicdisplay/opensheetmusicdisplay#904]
I've been playing with exporting osmd scores and I noticed that when the zoom is less than 1, the page background color doesn't fill the printed page.

**Comment by MilesMorel** [comment]
In case anyone else is running into this, I was able to export from the svg backend instead, prepending the svg with a white rectangle to fill the background. It's a hacky workaround, but it got the job done.

**Comment by sschmidTU** [comment]
Ah, this seems like a bug for zoom < 1, that should be fixed.
But good to know there's a workaround for SVG (not for Canvas though).

Actually we didn't have a way to create a background color for SVG yet, filling a white rectangle may be a good idea, at least for a temporary solution.

**Comment by sschmidTU** [comment]
I tried to reproduce this just now, but couldn't.
In our demo, I set the zoom level to 0.5 and renderer to canvas before rendering the score.
Left is with `pageBackgroundColor = '#FFFFFF'` and right is on default settings:
![image](https://user-images.githubusercontent.com/33069673/98153463-839d7800-1ed3-11eb-83c9-90f97cc5729e.png)

**Comment by sschmidTU** [comment]
Well, when debugging i see that the rectangle wasn't big enough for SVG (also it had a greyish border).
Strangely that doesn't happen when i'm not debugging.
Anyways, this should be fixed now, could you try it @MilesMorel ?

What you can do to test this in the demo:
in index.js replace `zoom = 1.0` with `zoom = 0.5`,
and put `pageBackgroundColor = "#FFFFFF";` before the OSMD object is created (new open...).

**Comment by MilesMorel** [comment]
Ok thank you for checking it out and sorry it wasn't repro'd (although I guess that's not bad news!). It sounds like my issue was implementation specific. I'm really tight on time right now but I'll try to get in there and confirm this week. Thanks again 🙏
