### ISSUE TITLE
How To Interrogate Sheet Music Without HTML Container

### ISSUE THREAD

**Issue by loganknecht** [opensheetmusicdisplay/opensheetmusicdisplay#906]
# Gratitude

Hey all! Thank you so much for this library! I cannot express how amazing it is!

# Situation

I'm in a situation where I need to know information about the `music xml` file provided, and I don't necessarily need to render it. 

The data I'm looking to extract is information like

- Sheet Music Title
- Sheet Music Measures
- etc.

# Previous Attempts

I tried to make 2 components that both used `Open Sheet Music Display` but that didn't work because only one instance can be used on the page.

I tried to rely on pulling information from the original instance, but I can't because sometimes the component that it's being used in does not get rendered, which means the logic for using it will never execute.

# Request For Guidance

So I have to ask. How can I interrogate the `sheet music xml` file for the information I need that doesn't involve creating an `OSMD` object?

Is it something like the `load` function but external?
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts#L89

If so can you provide a code snippet or guidance on how to achieve this?

**Comment by loganknecht** [comment]
Wow! Did you know you all write some amazing code?

I did some light hacking and came up with this!
```typescript
import {
    EngravingRules,
    IXmlElement,
    MXLHelper,
    MusicSheet,
    MusicSheetReader
} from "opensheetmusicdisplay";

// -----------------------------------------------------------------------------
// Hacking Helpers
// -----------------------------------------------------------------------------
// Lightly modified from the source code
// Grabbed from here:
// https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts#L89
export function createMusicSheetFromLink(content: string | Document): Promise<MusicSheet> {
    const url_timeout = 5000;
    // Warning! This function is asynchronous! No error handling is done here.
    // this.reset();
    console.log("typeof content: " + typeof content);
    if (typeof content === "string") {
        const str: string = content as string;
        //     const self: OpenSheetMusicDisplay = this;
        //     // console.log("substring: " + str.substr(0, 5));
        if (str.substr(0, 4) === "\x50\x4b\x03\x04") {
            console.log("[OSMD] This is a zip file, unpack it first: " + str);
            // This is a zip file, unpack it first
            return MXLHelper.MXLtoXMLstring(str).then(
                (x: string) => {
                    return createMusicSheetFromLink(x);
                },
                (err: any) => {
                    console.log(err);
                    throw new Error("OpenSheetMusicDisplay: Invalid MXL file");
                }
            ) as Promise<MusicSheet>;
        }
        // Javascript loads strings as utf-16, which is wonderful BS if you want to parse UTF-8 :S
        if (str.substr(0, 3) === "\uf7ef\uf7bb\uf7bf") {
            console.log("[OSMD] UTF with BOM detected, truncate first three bytes and pass along: " + str);
            // UTF with BOM detected, truncate first three bytes and pass along
            return createMusicSheetFromLink(str.substr(3));
        }
        let trimmedStr: string = str;
        if (/^\s/.test(trimmedStr)) {
            // only trim if we need to. (end of string is irrelevant)
            trimmedStr = trimmedStr.trim(); // trim away empty lines at beginning etc
        }
        if (trimmedStr.substr(0, 6).includes("<?xml")) {
            // first character is sometimes null, making first five characters '<?xm'.
            console.log("[OSMD] Finally parsing XML content, length: " + trimmedStr.length);
            // Parse the string representing an xml file
            const parser: DOMParser = new DOMParser();
            content = parser.parseFromString(trimmedStr, "application/xml");
        } else if (trimmedStr.length < 2083) {
            // TODO do proper URL format check
            console.log("[OSMD] Retrieve the file at the given URL: " + trimmedStr);
            // Assume now "str" is a URL
            // Retrieve the file at the given URL
            return AJAX.ajax(trimmedStr, url_timeout).then(
                (s: string) => {
                    return createMusicSheetFromLink(s);
                },
                (exc: Error) => {
                    throw exc;
                }
            );
        } else {
            console.error("[OSMD] osmd.load(string): Could not process string. Did not find <?xml at beginning.");
        }
    }

    if (!content || !(content as any).nodeName) {
        return Promise.reject(new Error("OpenSheetMusicDisplay: The document which was provided is invalid"));
    }
    const xmlDocument: Document = content as Document;
    const xmlDocumentNodes: NodeList = xmlDocument.childNodes;
    console.log("[OSMD] load(), Document url: " + xmlDocument.URL);

    let scorePartwiseElement: null | Element = null;
    for (let i: number = 0, length: number = xmlDocumentNodes.length; i < length; i += 1) {
        const node: Node = xmlDocumentNodes[i];
        if (node.nodeType === Node.ELEMENT_NODE && node.nodeName.toLowerCase() === "score-partwise") {
            scorePartwiseElement = node as Element;
            break;
        }
    }
    if (scorePartwiseElement === null || scorePartwiseElement === undefined) {
        console.error("Could not parse MusicXML, no valid partwise element found");
        return Promise.reject(new Error("OpenSheetMusicDisplay: Document is not a valid 'partwise' MusicXML"));
    }
    const engraving_rules = new EngravingRules();
    const score: IXmlElement = new IXmlElement(scorePartwiseElement);
    const reader: MusicSheetReader = new MusicSheetReader(undefined, engraving_rules);
    const new_music_sheet: MusicSheet = reader.createMusicSheet(score, "Untitled Score");
    if (new_music_sheet === undefined) {
        // error loading sheet, probably already logged, do nothing
        return Promise.reject(new Error("given music sheet was incomplete or could not be loaded."));
    }
    console.log(`[OSMD] Loaded sheet ${new_music_sheet.TitleString} successfully.`);

    // this.needBackendUpdate = true;
    // this.updateGraphic();

    return Promise.resolve(new_music_sheet);
}

// Class with helper methods to handle asynchronous JavaScript requests
// Taken directly from
// https://raw.githubusercontent.com/opensheetmusicdisplay/opensheetmusicdisplay/develop/src/OpenSheetMusicDisplay/AJAX.ts
export class AJAX {
    /**
     * Retrieve the content of the file at url
     * @param url
     * @returns {any}
     */
    public static ajax(url: string, timeout: number = 9000): Promise<string> {
        let xhttp: XMLHttpRequest;
        const mimeType: string = url.indexOf(".mxl") > -1 ? "text/plain; charset=x-user-defined" : "application/xml";
        if (XMLHttpRequest) {
            xhttp = new XMLHttpRequest();
        } else if (ActiveXObject) {
            // for IE<7
            xhttp = new ActiveXObject("Microsoft.XMLHTTP");
        } else {
            return Promise.reject(new Error("XMLHttp not supported."));
        }
        xhttp.timeout = timeout;
        return new Promise((resolve: (value: string) => void, reject: (error: any) => void) => {
            xhttp.onreadystatechange = () => {
                if (xhttp.readyState === XMLHttpRequest.DONE) {
                    if (xhttp.status === 200) {
                        resolve(xhttp.responseText);
                    } else if (xhttp.status === 0 && xhttp.responseText) {
                        resolve(xhttp.responseText);
                    } else {
                        //reject(new Error("AJAX error: '" + xhttp.statusText + "'"));
                        reject(new Error("Could not retrieve requested URL " + xhttp.status));
                    }
                }
            };
            xhttp.ontimeout = (e) => {
                // For IE and node
                reject(new Error("Server request Timeout"));
            };
            xhttp.overrideMimeType(mimeType);
            xhttp.open("GET", url, true);
            xhttp.send();
        });
    }
}

```
And it seems to work like the `load()` function in the `OSMD` class works, but instead it gives me JUST the `MusicSheet` object which lets me do some light interrogation about the piece!

I'd love to see something like this included as maybe a static function in the `OSMD`!

What do you folks all think about that idea?
@sschmidTU @sebastianhaas @matt-uib ?

I'd be more than happy to make the merge request!

**Comment by sschmidTU** [comment]
Hey, cool that you already got something to work!
But can't you just call osmd.load() and then access osmd.Sheet?
Instances of OSMD should be independent in the recent versions of OSMD since we made EngravingRules not static anymore.

**Comment by loganknecht** [comment]
@sschmidTU 

Above I stated

> I tried to make 2 components that both used Open Sheet Music Display but that didn't work because only one instance can be used on the page.
>
> I tried to rely on pulling information from the original instance, but I can't because sometimes the component that it's being used in does not get rendered, which means the logic for using it will never execute.

The issue for me is that because of implementation, I can't have 2 `osmd` containers together because only one is rendered. Additionally the one that is rendered is not displayed on the page until several interactions later, which means I can't call `osmd.load` because the rendered component isn't available to stand itself up.

My goal is simply to interrogate the sheet music BEFORE loading or rendering it. Because of that having access to the `MusicSheet` object is more than sufficient to solve the problem.

This is why I opted for this solution. I also believe this would be a VERY helpful statistic interface as it would allow other users to work around the same roadblock I'm experiencing, which is

1. Not displaying the rendered element
2. Cannot have access to the rendered screen
3. It also helps with performance since the only thing being processed is the music and none of the rendering overhead is required. 

@sschmidTU Please consider this request! 😄

**Comment by sschmidTU** [comment]
Yes, I read that, but i guess i don't understand your issue, why you "can't have 2 osmd containers together because only one is rendered".
You just need to make an extra OSMD object e.g. `osmdInfo`, make it load() the same score, then access `osmdInfo.Sheet`.
The only problem you could have is not having an extra HTMLElement (div) container for the extra `osmdInfo` object, but you should simply be able to make one that you won't use.

If you don't call osmd.render(), you don't need access to the rendered screen.

**Comment by loganknecht** [comment]
Okay that makes sense @sschmidTU!

I may be missing something. But, when I tried it I was having issues because I was obligated to initialize the `OSMD` object with a reference to the container it would be rendered to
```typescript
<div id="osmdContainer"/>
<script src="opensheetmusicdisplay.min.js"></script>
<script>
  var openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");
  openSheetMusicDisplay.setOptions({
    backend: "svg",
    drawTitle: true,
    // drawingParameters: "compacttight" // don't display title, composer etc., smaller margins
  });
  openSheetMusicDisplay
    .load("http://downloads2.makemusic.com/musicxml/MozaVeilSample.xml")
    .then(
      function() {
        openSheetMusicDisplay.render();
      }
    );
</script>
```

If I have two different OSMD objects, both that require a container element, only one of them can be selected to render in.

Can you provide an example of what you're advocating for as I'm having a bit of a tough time imagining its implementation.

**Comment by sschmidTU** [comment]
```typescript
<div id="osmdContainer"/>
<div id="osmdInfoContainerNoRender" style="display: none">
<script src="opensheetmusicdisplay.min.js"></script>
<script>
  var osmdInfo = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdInfoContainerNoRender");
  osmdInfo.load("http://downloads2.makemusic.com/musicxml/MozaVeilSample.xml").then(function() {
	console.log("osmdInfo: Sheet Title: " + osmdInfo.Sheet.Title); // example
  });

  var openSheetMusicDisplay = new opensheetmusicdisplay.OpenSheetMusicDisplay("osmdContainer");
  openSheetMusicDisplay.setOptions({
    backend: "svg",
    drawTitle: true,
    // drawingParameters: "compacttight" // don't display title, composer etc., smaller margins
  });
  openSheetMusicDisplay
    .load("http://downloads2.makemusic.com/musicxml/MozaVeilSample.xml")
    .then(
      function() {
        openSheetMusicDisplay.render();
      }
    );
</script>
```
[indexFetchFromURL_osmdInfo.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5424606/indexFetchFromURL_osmdInfo.zip)

![image](https://user-images.githubusercontent.com/33069673/96909502-68c41000-149e-11eb-9193-626f88466f05.png)

You can actually execute this html with Chrome in the [plain javascript usage example project](https://github.com/opensheetmusicdisplay/RawJavascript-usage-example) if you install a CORS allowing extension:
https://chrome.google.com/webstore/detail/moesif-origin-cors-change/digfbfaphojjndkpccljibejjbppifbc?hl=en-US

Just turn the CORS extension off again after you use it, because CORS is unsafe.

**Comment by loganknecht** [comment]
Well. @sschmidTU I feel sillier in my solution now.

Thanks for the example. I can confirm it worked, just as amazingly as you suggested.

❤️ ❤️ ❤️ ❤️ ❤️ 

Thank you for continuing to be such a pleasure to interact with, and hopefully others will find this issue if they have the same question!

**Comment by loganknecht** [comment]
Hey @sschmidTU 

Sorry to raise a dead thread on this, but I seem to be having an issue reproducing this.

I have a setup that mirrors what you suggested. Albeit, it's a little different for data management reasons.

I have two elements that are using `OSMD` and their implementation is the same. Except one has an error.
I am using the idea you provided of `display: none` to not render the element so it can be interrogated, however when I do that I am given this error.
![image](https://user-images.githubusercontent.com/1308524/115348449-7f0a0a80-a167-11eb-8872-adc48dca5a22.png)

This issue is completely resolved though if I do not use the `display: none` approach you've advised. So I am under the impression that this is an issue with DOM visibility because of the suggestions to use `display: none`

Can you provide any thoughts on this? I'm genuinely not sure what to do on account that I'm following your directions and keep hitting this bug.

**Comment by loganknecht** [comment]
The alternative solution was to style as 

```
{
    height: "0px",
    overflow-x: "auto"
}
```
