### ISSUE TITLE
Flat beams with drum notation wrong beamY

### ISSUE THREAD

**Issue by bergcussion** [opensheetmusicdisplay/opensheetmusicdisplay#907]
Hi, I have a question with a special snare-notation (derived from old french and Basel Drumming.  The notation is a single line notation with notes above the line as right hand and the notes beneath the line as left hand. I need flat beams with a flat_beam-offset. So far I managed to make OSMD to display flat beams bei editing the file VexFlowMeasure.ts in the method finalzeBeams() in line 828 with two lines

```ts
(<any>vfBeam).render_options.flat_beams = true;
(<any>vfBeam).render_options.flat_beam_offset = 180;
```

Is this the right place to do it or do you have a better solution ?

The problem is, that it seems that beamY is not calculated correctly. It seems that the beamsY value missing an offset to the actual y-Position where the notation begins. 

In the file beams.js in the method getBeamYToDraw() i commented out line 616 
```ts
beamY = this.render_options.flat_beam_offset;
```

then the beamY is correct beams are displayed correctly, but without the flat_beam_offset. I'd like to display it with the offset.

Do have any suggestion where to set the right beamY offset.
Thank you for your help

Attachment: zip file with xml file
Best regards from Rosenheim, Bavaria

[Siebener Endstreich_testFlam.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5414120/Siebener.Endstreich_testFlam.zip)

![Screenshot (20)](https://user-images.githubusercontent.com/70834541/96688476-818ad380-1381-11eb-99a7-4380fa4453f8.png)
![Screenshot (22)](https://user-images.githubusercontent.com/70834541/96688503-88b1e180-1381-11eb-9309-028d6ba17f29.png)

**Comment by sschmidTU** [comment]
The unconnected stems should be fixed now.
![image](https://user-images.githubusercontent.com/33069673/98268396-c1120c00-1f8c-11eb-9903-5e470306fc2a.png)
![image](https://user-images.githubusercontent.com/33069673/98287813-3211ed80-1fa6-11eb-81c0-94ce09b8e12b.png)
Apparently combining beams and tuplets can be problematic, for now we have to activate autoStemBeam here.

Also, I added the EngravingRules `FlatBeams`, `FlatBeamOffset`, and `FlatBeamOffsetPerBeam`.

`FlatBeamsOffset` is applied once, and `FlatBeamOffsetPerBeam` per beam.

so e.g. this (recommended for longer stems):
```js
osmd.EngravingRules.FlatBeams = true;
osmd.EngravingRules.FlatBeamOffset = 30;
osmd.EngravingRules.FlatBeamOffsetPerBeam = 10;
```
![image](https://user-images.githubusercontent.com/33069673/98287440-ac8e3d80-1fa5-11eb-8d91-38e0007fd83e.png)


or just this:
```js
osmd.EngravingRules.FlatBeams = true;
osmd.EngravingRules.FlatBeamOffset = 0;
osmd.EngravingRules.FlatBeamOffsetPerBeam = 10;
```
![image](https://user-images.githubusercontent.com/33069673/98287813-3211ed80-1fa6-11eb-81c0-94ce09b8e12b.png)

**Comment by bergcussion** [comment]
Hi, thank you for your quick response. Thats already much better. I'm struggling with stem directions because I want to set the stem direction to down regardless the automatic change on a certain note height. Do you have any quick suggestions, other issues or info on that. Thanks in advance
Bernhard from bergcussion in bavaria

**Comment by sschmidTU** [comment]
@bergcussion To set the stem directions down, you should set them to down in your MusicXML. (it's x in Musescore)
I guess you can also set the stem directions after osmd.load() and before osmd.render(), though i'd advise to change the xml instead. Is that how you want to do it? Then you need to set `note.StemDirectionXml = 1` for downwards (0 is upwards).
