### ISSUE TITLE
javascript client side validator for musicxml files?

### ISSUE THREAD

**Issue by happypennygames** [opensheetmusicdisplay/opensheetmusicdisplay#908]
Hi,

Would you mind commenting on if/how validation of a musicxml file is done?  
Use case: loading musicxml files from untrusted sources aka "users". Thus, both security concerns and general formatting for actually working properly are needed as checks. The validation must also be self contained ie. client side, offline.

I have to also load, parse, and render musicxml files for my application, and it wasn't clear if omsd handles this or not, by validating against the musicxml schema.
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/tree/develop/src/Common/FileIO

Disclosure:  I did look into just using osmd for my application, but in the end, it made sense for now to write my own rendering system.  That being said, I think this is great, general endeavor, and wish you the best.

**Comment by infojunkie** [comment]
As per [#905], I validate locally using:
```
$ xmllint --schema /path/to/musicxml-3.1/schema/musicxml.xsd music-file-to-validate.xml --noout
```
using the official [MusicXML Schema](https://www.musicxml.com/for-developers/musicxml-xsd/) - with a [patch that fixes an XSD issue](https://github.com/w3c/musicxml/pull/284).

Once you patch the MusicXML XSD, you can also use it with an [online XML validator](http://xmlvalidator.new-studio.org/) (using the Schema option).

Hope this helps.

**Comment by happypennygames** [comment]
Thanks!  I see the actual change is called out clearly in the commits part of the issue:
https://github.com/w3c/musicxml/pull/284/commits/aa5cf7c7a245ca4ae36095c2b4d4dbbe9cef78ff
I will give a try using this xmllint js library I found - assuming that's what you use: https://github.com/kripken/xml.js
