### ISSUE TITLE
Couple of bugs with grace notes (used in a drum/percussion context)

### ISSUE THREAD

**Issue by nitzanrh** [opensheetmusicdisplay/opensheetmusicdisplay#909]
Hi guys,

A couple of bug reports concerning grace notes (used in a drum/percussion context):
1. When a couple of grace notes are attached as 8th notes, they appear well if the note is on the beat. However when attached to the 2nd 8th note of the beat the beaming doesn't quite work as it should.
2. When a couple of grace notes are attached as 8th notes and are connected with a slur, the slur appears on the 1st grace note rather than the 2nd.

Attached screenshots from the OSMD demo and a different xml render app, as well as the MXL file.
Cheers!

![osmd](https://user-images.githubusercontent.com/13316019/97478619-dd44f600-1959-11eb-9b21-f2f961f84696.png)
![different](https://user-images.githubusercontent.com/13316019/97478616-dc13c900-1959-11eb-88d1-d7956d8de1cc.png)
[Lesson 4.mxl.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5454037/Lesson.4.mxl.zip)

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/97767347-d7970e00-1b1b-11eb-80a4-574e12e6474a.png)

Nested beams should be fully supported/fixed now.

**Comment by sschmidTU** [comment]
About the slurs on grace notes being on the wrong notes, that will be hard to fix for now,
because Vexflow only allows slurs either on all grace notes or none, right now, unfortunately.
