### ISSUE TITLE
Notes misaligned after hidden dotted rest

### ISSUE THREAD

**Issue by pjcdawkins** [opensheetmusicdisplay/opensheetmusicdisplay#910]
OSMD version: 0.8.6

XML: https://fourscoreandmore.org/apps/download/scores/chorales/J_S_Bach_BWV_2_6-cut2-fromATB-exercise.xml?download=1
(raw: [J_S_Bach_BWV_2_6-cut2-fromATB-exercise.xml.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5457550/J_S_Bach_BWV_2_6-cut2-fromATB-exercise.xml.txt))

Displayed with OSMD: https://fourscoreandmore.org/apps/score/chorales/J_S_Bach_BWV_2_6-cut2-fromATB-exercise.xml
![Screenshot from 2020-10-29 15-38-20](https://user-images.githubusercontent.com/1465106/97596628-d15e4000-19fc-11eb-8e3f-e543aba579be.png)
(super impressed with the OSMD project by the way!)

As you can see the harmony in parts 2-4 (measures 2, 4) is misaligned after the rests, resulting in unusual chords for Bach.

Desired behaviour (displayed with MuseScore):
![Screenshot from 2020-10-29 15-37-32](https://user-images.githubusercontent.com/1465106/97596504-b12e8100-19fc-11eb-92cb-dfceb3624042.png)

The rests are created with music21 in @MarkGotham's script here: https://github.com/fourscoreandmore/fourscoreandmore.org/blob/0626d13a235c7b468bf9eeb9551e59a224b953c5/cut-outs-backend/app/TheoryExercises.py#L68

and it seems they look like this

```xml
      <forward>
        <duration>30240</duration>
      </forward>
```

**Comment by pjcdawkins** [comment]
I'm not certain it's only with dotted rests, but it seems that way based on a few other scores, and I wondered if it's a similar problem to #484

**Comment by sschmidTU** [comment]
Interesting. This doesn't happen if you remove the pickup measure, so i don't think it's related to issue 484,
probably an error in Vexflow's formatter.js.
![image](https://user-images.githubusercontent.com/33069673/97787044-f646e480-1baf-11eb-98b5-722594198621.png)
[J_S_Bach_BWV_2_6-cut2-fromATB-exercise_pickup_measure_removed.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5469606/J_S_Bach_BWV_2_6-cut2-fromATB-exercise_pickup_measure_removed.zip)

**Comment by pjcdawkins** [comment]
Thanks @sschmidTU

I updated dependencies including OSMD 0.8.6 -> 1.3.1 and Vexflow 3.0.0 > 3.0.1, and the issue is fixed -

https://fourscoreandmore.org/apps/score/chorales/J_S_Bach_BWV_2_6-cut2-fromATB-exercise.xml

<img width="778" alt="Screenshot 2021-12-05 at 09 05 34" src="https://user-images.githubusercontent.com/1465106/144740453-31fb9271-7b56-4eac-be6c-0b21b12c6bb4.png">

**Comment by sschmidTU** [comment]
Oh nice, this was fixed by https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1062#issuecomment-924419798. Dots weren't calculated correctly for ghost notes.
