### ISSUE TITLE
Hide measures that includes invisible notes.

### ISSUE THREAD

**Issue by Coulometer** [opensheetmusicdisplay/opensheetmusicdisplay#913]
![stave](https://user-images.githubusercontent.com/1932719/97844902-ca9a3a80-1d26-11eb-8b27-2468d37792b3.png)

There is a musicxml that includes two parts. One of parts includes invisible notes, is that possible that I can hide this part? Thanks.

**Comment by sschmidTU** [comment]
```js
osmd.load(mySheet);
osmd.Sheet.Instruments[1].Visible = false;
osmd.render();
```

Not your use case, but to check programmatically if the instrument has no notes (doesn't address invisible notes):
`osmd.Sheet.Instruments[1].Voices[0].voiceEntries.length === 0`

To check for all invisible notes programmatically, something like this:
```js
let allInvisible = true;
for (const voice of osmd.Sheet.Instruments[0].Voices) {
  for (const voiceEntry of voice.VoiceEntries)
    for (const note of voiceEntry.Notes) {
      if (note.PrintObject) { //visible
        allInvisible = false;
        break;
       }
     }
  }
}
if (allInvisible) {
  osmd.Sheet.Instruments[1].Visible = false;
}
```
