### ISSUE TITLE
Demo Print to PDF broken 

### ISSUE THREAD

**Issue by SevenBlocks** [opensheetmusicdisplay/opensheetmusicdisplay#914]
In the current code base and also the 0.8.6 demo fix release the "Print to PDF" button in the demo is broken. There is a javascript import error at this line:

```
function createPdf(pdfName) {
        if (openSheetMusicDisplay.backendType !== BackendType.SVG) {
```

error:
```

Uncaught TypeError: Cannot read property 'SVG' of undefined
    at createPdf (index.js:808)
    at HTMLDivElement.printPdfBtn.onclick (index.js:371)
```

The import 
`import { OpenSheetMusicDisplay, BackendType } from '../src/OpenSheetMusicDisplay/OpenSheetMusicDisplay';`

results in BackEndType being undefined.

It works in the 0.8.2demofix release, so something broke after that.

**Comment by sschmidTU** [comment]
Oops! Fixed.

I think BackendType may have moved inside OSMD,
and we didn't get a linter warning for the broken import inside the demo.js javascript,
which would probably need a configuration update.
