### ISSUE TITLE
Upgrade VexFlow to 3.x

### ISSUE THREAD

**Issue by infojunkie** [opensheetmusicdisplay/opensheetmusicdisplay#915]
Sincerely sorry to be making this tedious request, but it would be great to support the latest VexFlow releases. They have added SMuFL support among many other fixes and features since 1.2.93. Maybe this issue can be used to list all the problems with upgrading?

**Comment by sschmidTU** [comment]
Hi, don't worry, it would be nice to upgrade to Vexflow 3.x.
I collected all the problems I found with Vexflow 3.x here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/706#issuecomment-617360976
Admittedly, that's an obscure location, so it's nice to have a titled thread like this.

The main issue is the formatter, it makes some big mistakes that make 1.2.93 much better for us for now, layout wise.
We could make a release with Vexflow 3.x though, it's easy to change, just ̀`npm install vexflow@3.0.9` and `npm run build`.

3.0.9 example:
![image](https://user-images.githubusercontent.com/33069673/79995288-56e5be00-84b7-11ea-8984-403986448430.png)
(there's a measure end barline right before the last 16th, the notes overflow into the next measure)

**Comment by cedvdb** [comment]
@sschmidTU Sorry for chiming out of nowhere but what's the difference between this lib and vexflow ?

**Comment by sschmidTU** [comment]
@cedvdb as written in the description, OSMD renders MusicXML files using Vexflow. Vexflow can render all kinds of music notation via Javascript, but you can't just give it a MusicXML, you have to add all elements like staves and notes by hand (mostly).
