### ISSUE TITLE
SystemComposerDistance doesn't work for multiple lines

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#917]
osmd.rules.SystemComposerDistance works well when there's only one line.
But it doesn't work on multiple lines.

![One line at SystemComposerDistance 10](https://user-images.githubusercontent.com/56290540/99789784-7b496c00-2b66-11eb-8e83-4cca731e08d5.png)
A line with SystemComposerDistance : 10

![Multiple lines](https://user-images.githubusercontent.com/56290540/99789949-bba8ea00-2b66-11eb-9496-cca86dcf03e7.png)
Multiple lines with SystemComposerDistance : 10
(there was no change in other values)

[A line.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5572897/A.line.zip)
[Multiple lines.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5572898/Multiple.lines.zip)

**Comment by sschmidTU** [comment]
![image](https://user-images.githubusercontent.com/33069673/100138717-bd3c2000-2e8e-11eb-8ac0-a66da5f4f4e6.png)

(`osmd.EngravingRules.TitleBottomDistance = 3`)

**Comment by sschmidTU** [comment]
@djae88 thanks for the report and samples!
