### ISSUE TITLE
Rehearsal directions not handled

### ISSUE THREAD

**Issue by infojunkie** [opensheetmusicdisplay/opensheetmusicdisplay#919]
As per the [attached file](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5604977/bolivia.zip), the measure directive 
```
      <direction placement="above">
        <direction-type>
          <rehearsal>Section name</rehearsal>
        </direction-type>
      </direction>
```
is not handled. Would be great to process it :pray:

**Comment by infojunkie** [comment]
For reference, [this is how MuseScore renders the same file](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5604988/bolivia.pdf).

**Comment by infojunkie** [comment]
For context, I am working on a web-based leadsheet renderer and accompaniment generator. I am currently completing the first part, an [iReal Pro-to-MusicXML converter](https://github.com/infojunkie/ireal-musicxml). I am planning to use OSMD for the sheet rendering. If you are interested in this use-case, I would be glad to collaborate to flag (and eventually help fixing) all the expected features that OSMD would need to render typical leadsheets.

**Comment by infojunkie** [comment]
If you're interested to see how OSMD renders the iReal Pro 1350 jazz standards, please [check out this demo](https://ethereum.karimratib.me:8082/).

**Comment by massimobio** [comment]
Any word on wether the `rehearsal` tag will be supported?
It's commonly used in lead sheets and contemporary music with a large bold font and an outline box to demarcate sections.
<img width="269" alt="Screen Shot 2020-12-26 at 2 28 44 PM" src="https://user-images.githubusercontent.com/240599/103157976-de8e7580-4786-11eb-8d67-1b744ef2a2fc.png">

**Comment by sschmidTU** [comment]
Yes, rehearsal tags are decently common and important, that would be a great addition.
Actually Vexflow has them built in, so it should be relatively easy to implement:
![image](https://user-images.githubusercontent.com/33069673/103949299-566f7f00-513b-11eb-96b0-bf22e0810687.png)

There is `stave.setSection`, which simply does `stave.modifiers.push(new StaveSection(section, this.x, y))`.
There don't seem to be layouting and collision checks for StaveSections in Vexflow, so we probably need to do this on our own with our SkyLine, that's the only issue. Though for a first version even just StaveSections with a manual y offset for StaveSections (in a modifiable EngravingRule) would probably be a worthy addition overall.

**Comment by infojunkie** [comment]
Thanks for your reply. Maybe it would be worth filing a VexFlow issue to this effect?

**Comment by sschmidTU** [comment]
I don't think a Vexflow issue just for this would be the way to go, since Vexflow doesn't have collision checks for anything above or below the staff, it would need a system for all of that.
We already check for placement and collision for many such elements like measure numbers and lyrics, so doing likewise for rehearsal directions in OSMD should be the way to go.

**Comment by benwinkelman** [comment]
I'm also hoping to see rehearsal marks supported in OSMD, so this is encouraging!

**Comment by sschmidTU** [comment]
Done.

![image](https://user-images.githubusercontent.com/33069673/106054317-1e30e000-60ec-11eb-8150-c9377df55292.png)
![image](https://user-images.githubusercontent.com/33069673/106054346-2c7efc00-60ec-11eb-9f50-d9502e89fcab.png)

Samples:
[test_rehearsal_marks_2_samples.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5883053/test_rehearsal_marks_2_samples.zip)
(added to our test samples: `test/data/test_rehearsal_marks*.musicxml`)

new EngravingRules:
```js
osmd.rules.RenderRehearsalMarks = true; // default
osmd.rules.RehearsalMarkXOffset = 0; // default: avoid collision with metronome number
osmd.rules.RehearsalMarkYOffset = 0; // default: avoid collision with chord symbols
osmd.rules.RehearsalMarkFontSize = 10; // vexflow default: 12, too big with chord symbols
```
