### ISSUE TITLE
StaveRepetitions wrong x positions (D.S., To Coda, etc)

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#920]
Already fixed.

Before:
![image](https://user-images.githubusercontent.com/33069673/100479575-e65aeb80-30ee-11eb-9194-5e128e902306.png)

After:
![image](https://user-images.githubusercontent.com/33069673/100479128-929bd280-30ed-11eb-8289-18d386a8bd34.png)

[test_staverepetitions_coda_etc.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5609339/test_staverepetitions_coda_etc.musicxml.zip)

MuseScore (3.5.2) doesn't render this very well by the way:
![image](https://user-images.githubusercontent.com/33069673/100480059-7c434600-30f0-11eb-9ca5-17a08aa436c4.png)

The issue was a few NaNs in Vexflow from undefined measurements (x/y values), i added safeguards against those to our Vexflow patch.
Also, `TO_CODA` didn't exist as a `Vex.Flow.Repetition.type` (in `staverepetition.js`), added that to the patch as well.
Also new EngravingRule `RepetitionSymbolsYOffset`.

**Comment by sschmidTU** [comment]
`D.S. al Coda` wrongly recognized as `D.S.` fixed as well now.

![image](https://user-images.githubusercontent.com/33069673/100484391-866b4180-30fc-11eb-80ac-f7bea3e01e81.png)

The problem was that the D.S. al coda was recognized as D.S., because it was written 'al Coda' instead of 'al coda', and we didn't have an ignore case option in the regexes. This is fixed now.

**Comment by matt-uib** [comment]
But the musescore rendering has the right order of the symbols and also the better x positioning. Coda must come after d.s. al coda. There must be still something quite wrong here.

**Comment by sschmidTU** [comment]
Ah, true, the D.S. al Coda should be in measure 3, as it is in the MusicXML.
I'll see what's wrong there. The x values may still be wrong, even if they aren't NaN anymore.

**Comment by sschmidTU** [comment]
- [ ] Also we can tell Vexflow to write the 'To Coda' at the end of the measure instead of the beginning.

**Comment by matt-uib** [comment]
Yes right! That shall be at the end.
Also it is better to put the coda into a new system, to not have the ds al coda and the coda sign too close to each other. At least I have often seen it in the next system..

**Comment by sschmidTU** [comment]
To Coda right positioning and D.S. al Coda positioning should be fixed now:
![image](https://user-images.githubusercontent.com/33069673/101059905-15f67180-358f-11eb-968a-3f56cb5bd9d5.png)

**Comment by djae88** [comment]
The position of the 'to coda' moves to the left depending on the size of the sheet
![to coda getting further](https://user-images.githubusercontent.com/56290540/101600804-2b601580-3a3f-11eb-8fb8-dd12fcb5e79b.png)
So in a really big sheet, it's also at the beginning.
how about fix it at the end like 'D.S.alcoda'?

**Comment by sschmidTU** [comment]
This should be finally fixed now:
![image](https://user-images.githubusercontent.com/33069673/105094438-92440600-5aa4-11eb-9543-b199895bb02f.png)

![image](https://user-images.githubusercontent.com/33069673/105094392-83f5ea00-5aa4-11eb-8e8f-770dabebbe2a.png)

These test samples are added to our tests, see `test/data/test_staverepetitions_coda_etc*`.

@djae88 As you suggested, 'To Coda' is now fixed to the end of the measure.
There was actually another error where the To Coda was attributed to the wrong measure (1 instead of 2), see above commit 9643493.

**Comment by sschmidTU** [comment]
Fixed all right-oriented repetitions (backwards jumps) to be near the end of the measure.
before:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/33069673/199829924-7660255a-d54e-48d5-b3e5-f3d0f9f2fffe.png">

after:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/33069673/199829961-7b4d207a-5f5f-4558-a1e3-145b6a9af063.png">

before:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/33069673/199830029-e7f943cf-f5a6-41ce-be4a-2d2845d10a5a.png">

after:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/33069673/199830069-4a994f91-142c-4ccf-b5e9-7f4ae25f6d40.png">

before:
<img width="206" alt="image" src="https://user-images.githubusercontent.com/33069673/199829666-737317a5-6d3a-42cf-9085-a159053e8393.png">

after:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/33069673/199829609-ffd75824-b215-4ced-999c-d37115c5fc5a.png">

before (Coda_Left):
<img width="199" alt="image" src="https://user-images.githubusercontent.com/33069673/199830324-ff0fb0a4-7636-46e4-a8be-d0441add6c92.png">

after:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/33069673/199830362-e01c9007-4710-498b-9884-ab5bf7b750b6.png">

(Coda (left) was turned to TO_CODA because of checks in the RepetitionInstructionReader that tried to balance Coda and To Coda occurences)

samples (all  repetition types):
[repetition_types_all_code_DaCapo_DalSegno_etc.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9932864/repetition_types_all_code_DaCapo_DalSegno_etc.zip)

Running visual regression tests in #1265.
