### ISSUE TITLE
Is it possible to use a different font to display the sheetmusic?

### ISSUE THREAD

**Issue by bmjcmj** [opensheetmusicdisplay/opensheetmusicdisplay#924]
Hello.
My question is in the issue title, I mean the musical font to display sheetmusic themselves
I found similar questions here, but they were asked a long time ago. Maybe something has changed in the new versions of Open Sheet Music Display?
If not, maybe there are some solutions how to change the code before build so that the new font can be loaded into project?

**Comment by sschmidTU** [comment]
```js
osmd.EngravingRules.DefaultFontFamily = "Times New Roman";
```
Feel free to choose another font that's available in the browser.

**Comment by bmjcmj** [comment]
> ```js
> osmd.EngravingRules.DefaultFontFamily = "Times New Roman";
> ```
> 
> Feel free to choose another font that's available in the browser.

Thanks for the answer, but maybe I was wrongly expressed in the question - I mean the musical font

**Comment by sschmidTU** [comment]
This is not possible in the current version of OSMD because we still use Vexflow 1.2.93.
You can install Vexflow 3.0.9+ and then change `osmd.EngravingRules.DefaultVexFlowNoteFont`, the standard is `gonville`.
We don't yet use Vexflow 3.0+ because the formatter makes some big errors from time to time like overlapping notes into the next measure.

**Comment by bmjcmj** [comment]
> This is not possible in the current version of OSMD because we still use Vexflow 1.2.93.
> You can install Vexflow 3.0.9+ and then change `osmd.EngravingRules.DefaultVexFlowNoteFont`, the standard is `gonville`.
> We don't yet use Vexflow 3.0+ because the new formatter makes some big errors from time to time like overlapping notes into the next measure.

Thank you!
You mean I must install Vexflow 3.0.9 in the "opensheetmusicdisplay/node_modules/vexflow" and then start build OSMD into the project?

**Comment by sschmidTU** [comment]
Yes, i believe that should work. The current OSMD comes with Vexflow 3.0.9 support if it's installed.

**Comment by bmjcmj** [comment]
I dont't know why, but this is not working:

> You mean I must install Vexflow 3.0.9 in the "opensheetmusicdisplay/node_modules/vexflow" and then start build OSMD into the project?

**Comment by bmjcmj** [comment]
`osmd.EngravingRules.DefaultFontFamily = "Arial"` - It certainly works
`osmd.EngravingRules.DefaultVexFlowNoteFont = "Petaluma"` - but this setting doesn't change anything.
I installed a new VexFlow in node_modules, deleted the "build" folder and rerun "build" from the command line, then I included a new osmd.min.js file into project

**Comment by sschmidTU** [comment]
Ah, actually osmd doesn't yet set the vexflow note font if it isn't Gonville (or Bravura, which is the new vexflow default in 3.0.x).
I just added support for Petaluma in 3c5c1d1c0a6a3ad400a104c385af5a43d6d17548.
If you want to add it yourself, add this line in VexFlowMusicSheetCalculator (see commit above):
`Vex.Flow.DEFAULT_FONT_STACK = [Vex.Flow.Fonts?.Petaluma, Vex.Flow.Fonts?.Bravura, Vex.Flow.Fonts?.Gonville]; // order of preference`

**Comment by bmjcmj** [comment]
> Ah, actually osmd doesn't yet set the vexflow note font if it isn't Gonville (or Bravura, which is the new vexflow default in 3.0.x).
> I just added support for Petaluma in [3c5c1d1](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/commit/3c5c1d1c0a6a3ad400a104c385af5a43d6d17548).
> If you want to add it yourself, add this line in VexFlowMusicSheetCalculator (see commit above):
> `(Vex.Flow as any).DEFAULT_FONT_STACK = [(Vex.Flow as any).Fonts?.Petaluma, (Vex.Flow as any).Fonts?.Gonville, (Vex.Flow as any).Fonts?.Bravura]; // order of preference`

Wow, it's very good that you added the commit so fast! I will tested this..
Also I find this - https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/597
I found this because I was looking for something like "how to change the length of the bar", 
because the chords overlapped each other.
As I understand it, this problem has not been resolved yet?

**Comment by sschmidTU** [comment]
Yes, if the problem were resolved, the issue would be closed.

**Comment by sschmidTU** [comment]
We have many different issues we can work on, so we always have to prioritize and see what's reasonable to do next.

**Comment by bmjcmj** [comment]
By the way, last commit is working, now I can change the music font.
Thank you again for your responsiveness.



> We have many different issues we can work on, so we always have to prioritize and see what's reasonable to do next.

Is this change planned for new versions or someone working on this?
I think this problem occurs quite often and not only for me

**Comment by bmjcmj** [comment]
And maybe OSMD have an option like what I wrote above - "how to change the length of the bar" ?

**Comment by bmjcmj** [comment]
or changing the distance between notes

**Comment by sschmidTU** [comment]
Changing the length of a bar would indeed be a nice option, maybe as a multiplier.
Changing the distance between notes is probably not possible, because it's handled by the Vexflow formatter.

**Comment by bmjcmj** [comment]
> Changing the length of a bar would indeed be a nice option, maybe as a multiplier.
> Changing the distance between notes is probably not practical, because it's handled by the Vexflow formatter.

I noticed some difference in how the vexflow and osmd notes are formed, check this:
![image](https://user-images.githubusercontent.com/76438270/102810982-19d32200-43de-11eb-8622-e6aafa770ba6.png)

as if the notes are more compact... Sometimes is a not a problem, but sometimes it's look like this
![image](https://user-images.githubusercontent.com/76438270/102811246-80584000-43de-11eb-9995-ab1ee58ef4f6.png)

Maybe I missed some option what can manage it?

**Comment by sschmidTU** [comment]
That's mostly just the measure width, you can change osmd.zoom.
Though first, if the notes are too compact for you, you can change this:
```js
osmd.rules.VoiceSpacingMultiplierVexflow = 0.85; // change to 1
osmd.rules.VoiceSpacingAddendVexflow = 3.0; // 3.0 is fine, but you can try 4.0
```

**Comment by bmjcmj** [comment]
> That's mostly just the measure width, you can change osmd.zoom.
> Though first, if the notes are too compact for you, you can change this:
> 
> ```js
> osmd.rules.VoiceSpacingMultiplierVexflow = 0.85; // change to 1
> osmd.rules.VoiceSpacingAddendVexflow = 3.0; // 3.0 is fine, but you can try 4.0
> ```

Thank you, this working, also it can indirectly fix the problem with overlapping chords

**Comment by bmjcmj** [comment]
And about zoom, you mean this?
https://opensheetmusicdisplay.github.io/classdoc/classes/opensheetmusicdisplay.html#zoom

How to use this?
If I set the `osmd.zoom = 1.2`, nothing change.

Sorry for the many questions, but I hope this thread will help many others to find answers to some questions

**Comment by sschmidTU** [comment]
You have to call `osmd.render()` again after render option changes.

**Comment by bmjcmj** [comment]
> You have to call `osmd.render()` again after render option changes.

Of course, I did that, but I understood what was the matter: I call `osmd.zoom = 1.2` before `osmd.load()`, but if i do it like this:

```
osmd.load(xml_string).then(function() {     
        osmd.zoom = 1.2;
        osmd.render();
```

All working

**Comment by sschmidTU** [comment]
Oh, right, `load()` resets the zoom in `reset()`. Maybe that should be changed.
But until then, set the zoom after `load()` and before `render()`.

**Comment by bmjcmj** [comment]
And the last of my questions...
It's possible to use chord symbols with OSMD?
In last versions of VexFlow is availible something like this instead of "Cmaj/F":
![image](https://user-images.githubusercontent.com/76438270/102822095-c5d23880-43f1-11eb-892f-6fb8205719f7.png)

**Comment by sschmidTU** [comment]
the Vexflow chord symbols are not yet available for chords.
However you can set the text for the chords we do support in EngravingRules:
`public setChordSymbolLabelText(key: ChordSymbolEnum, value: string)`
For ChordSymbolEnum, see here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/src/MusicalScore/VoiceData/ChordSymbolContainer.ts#L138

For font sizes, there's LyricsHeight, SheetTitleHeight and ChordSymbolTextHeight in EngravingRules.

If you want to change so many things, i would suggest you take a closer look at EngravingRules and OSMDOptions.
