### ISSUE TITLE
Updating the index.ts in the Common folder?

### ISSUE THREAD

**Issue by jasyip** [opensheetmusicdisplay/opensheetmusicdisplay#926]
Not everything in the Common/DataObjects folder is exported in Common/index.ts (only Fraction and Pitch are explicitly exported, while the others are not since * was not used). Is it possible for Common/index.ts to be updated to include every class in Common/DataObjects ?

**Comment by sschmidTU** [comment]
Yes, this looks like an oversight. The exports are added now. Thanks for the hint!
