### ISSUE TITLE
Discord Link

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#927]
Hi guys, I'm very happy for supporting your project, as I said before, the project is really amazing.
I'm looking for the discord link but couldn't find it anywhere, what is the best way to get support from the team, and have access to all the cool new features?

Thanks!

**Comment by sschmidTU** [comment]
Hey conde2, thank you so much for your support! <3
We are getting the discord channel right now, hopefully we can send out the link later today!
We are also preparing the audio player sponsor build, i assume that's part of what you were asking for.

**Comment by sschmidTU** [comment]
@conde2 I sent out an update email through Github Sponsors containing the discord link, did you get it?
I'll post the invite link publicly here once the sponsors are in and we're sure everything is set up correctly :)

**Comment by conde2** [comment]
I manage to join the discord, looks like it is working well. My nickname there is Conde2, see you there.

**Comment by sschmidTU** [comment]
The Discord link is now public:
http://osmd.org/discord

Feel free to share! See you in the chatroom!
