### ISSUE TITLE
cursor.next() should skip notes in hidden parts

### ISSUE THREAD

**Issue by sschmidTU** [opensheetmusicdisplay/opensheetmusicdisplay#929]
when some parts (instruments) are not rendered at all, it doesn't make sense to advance to subdivisions (smaller notes) in the  hidden part, which don't exist in any rendered part.
This makes the cursor appear not to move when executing cursor.next().

need to respect hidden parts in MusicPartManagerIterator.recursiveMove() (currentVoiceEntryIndex++).

**Comment by sschmidTU** [comment]
Fixed.
Using `moveToNextVisibleVoiceEntry` was indeed the solution.

A good test case is our default Beethoven Geliebte sample, call this in the console:
```js
osmd.sheet.instruments[1].Visible = false
```
then re-render, show the cursor and advance through the score.

Previously, the cursor would stay on the dotted quarter note after `cursor.next()`, because there is a quarter note in the hidden part. But now, when the piano part is hidden, it advances to the next visible voice entry.
![image](https://user-images.githubusercontent.com/33069673/104324781-2849c080-54e8-11eb-8091-f166709693c9.png)
Of course, when the piano part is not hidden, it still advances to the next note in the piano.

**Comment by hallvors** [comment]
Thank you very much for answering questions and a quick bugfix! :)
