### ISSUE TITLE
Chord symbols overlap with notes above stave.

### ISSUE THREAD

**Issue by benwinkelman** [opensheetmusicdisplay/opensheetmusicdisplay#934]
I'd like to add my support for the idea of developing a collision detection and spacing method for chord symbols. 

In the first example the chord symbols overlap with most notes above the stave. 
In the second example I set the Y offset higher with `osmd.EngravingRules.ChordSymbolYOffset = 4.0;`. This avoids most collisions but it sets the chord symbol position too high. Most scores in the app I'm building don't have notes above the stave, so in those cases it will look a bit odd to have the chord symbols this high. 

![Notes above stave overlapping with chord symbols](https://user-images.githubusercontent.com/74516489/104479762-ccd40d00-5591-11eb-83b0-952e99c06735.png)

![Chord symbols Yoffset = 4 0](https://user-images.githubusercontent.com/74516489/104479820-de1d1980-5591-11eb-82b8-2e084a6d79b1.png)

**Comment by sschmidTU** [comment]
Absolutely, this will be a great improvement.
Note that we have a Skyline and Bottomline system, which tells us the highest points for a given x where we draw something.
That makes it relatively easy to place ChordSymbols above the Skyline, then update the Skyline, as is the usual process. So, complex collision detection is probably not needed for now.

**Comment by massimobio** [comment]
I'm running into this issue as well.
@sschmidTU is your note intended as a workaround that can be implemented on the user side or is it an idea about how to fix the issue in OSMD?

**Comment by ryohorie** [comment]
I also want this issue to be solved.

**Comment by sschmidTU** [comment]
@massimobio it's an idea to fix this in OSMD, but you can also use it as a user-side workaround theoretically, by getting the skyline values, then setting `EngravingRules.ChordSymbolYOffset` (then re-rendering).

**Comment by massimobio** [comment]
I finally got around to trying to solve this.
I made a function to try and read the slyLineMin but no matter which chart I test, I always get a return value of -4.2
I tried charts with notes with charts mostly on the staff and charts with nigh notes that collide with the chords symbols.
I tried using other measures in `var measure = graphic.findGraphicalMeasure(0, 0);`.
I call this method on completion of score rendering.
```JS
function getSkyLineMin() {
    var graphic = this.osmd.GraphicSheet;
    var measure = graphic.findGraphicalMeasure(0, 0);
    var staffLine = measure.ParentStaffLine;
    var skyBottomLineCalculator = staffLine.SkyBottomLineCalculator;
    var skyLineMin = skyBottomLineCalculator.getSkyLineMin();
    return skyLineMin;
}
```

Any ideas on why this is not working?

**Comment by sschmidTU** [comment]
skyLineMin is the minimum value over the whole skyline (the whole staffline).
Check `skyBottomLineCalculator.getSkyLineMinAtPoint()` or `getSkyLineMinInRange()` etc.

**Comment by massimobio** [comment]
Maybe I'm misunderstanding but wouldn't I need the max skyline over the whole staff line?
With that number I could set the EngravingRules.ChordSymbolYOffset.

**Comment by sschmidTU** [comment]
I just tried this and it seems to work fine to me. Not sure what's happening on your end.
![image](https://user-images.githubusercontent.com/33069673/118884824-3d4fb980-b8f7-11eb-8c9f-597ac43328ec.png)
You could try to check `ParentStaffLine.PositionAndShape.BorderTop` instead, which is set to skylineMin at some point.

**Comment by massimobio** [comment]
Very strange. Maybe something is different with single staff?
<img width="1087" alt="Screen Shot 2021-05-19 at 5 36 49 PM" src="https://user-images.githubusercontent.com/240599/118887953-095d9f80-b8c9-11eb-86c9-0a8627b6050b.png">

**Comment by sschmidTU** [comment]
What do you mean, single staff? I don't see a difference for single staff scores.
![image](https://user-images.githubusercontent.com/33069673/118888352-d385de80-b8fb-11eb-909e-eb2e79bf3468.png)

Maybe you're checking too early, before the score has finished rendering?

**Comment by massimobio** [comment]
Ok, I just tried some completely different scores and I get different values for skyLineMin. Something is off with this set of scores I'm using. I will investigate. Thank you for your help and prompt replies.

**Comment by VirusPae** [comment]
우리는 이렇게 수정해 보았습니다.
-> MusicSheetCalculator.ts
![11](https://user-images.githubusercontent.com/88708065/128954758-66193dab-d548-4d87-99ae-ab29d12e2114.PNG)
![12](https://user-images.githubusercontent.com/88708065/128954796-204d9e8b-17ea-4352-a944-44526710964d.PNG)

-> GraphicalMusicSheet.ts
![13](https://user-images.githubusercontent.com/88708065/128954813-315a1502-d8cc-4fb4-b158-f9c3f9eb5dbb.PNG)

-> EngravingRules.ts
![04](https://user-images.githubusercontent.com/88708065/128954828-8c9df93a-3b48-48a2-92cd-9155548a3422.PNG)


우리는 prepareGraphicalMusicSheet() 함수의 실행위치를 변경하여 처리하였습니다. 
이런 변경이 다른 기능에 영향을 미치는지는 모두 검증하지 못했지만. 
현재 우리는  잘 사용하고 있습니다.

**Comment by sschmidTU** [comment]
@VirusPae please write in English.

**Comment by sschmidTU** [comment]
Chord symbol overlap is now fixed, symbols are positioned above the skyline (highest colliding point):
![image](https://user-images.githubusercontent.com/33069673/141322852-b5d531f3-53b5-4cec-9aa1-5ad4f583077c.png)

You can also align the y positions of the chord symbols, either per measure or per staffline:
![image](https://user-images.githubusercontent.com/33069673/141322662-9fbab4b4-1ebf-4b83-913e-9f379edfdb8d.png)
![image](https://user-images.githubusercontent.com/33069673/141322958-0b694e2d-379b-4430-950e-6eb0d33f7a29.png)

```js
osmd.rules.ChordSymbolYAlignment = true;
osmd.rules.ChordSymbolYAlignmentScope = "measure"; // or "staffline"
// YOffset is mostly not needed anymore:
osmd.rules.ChordSymbolYOffset = 0.1;
```

Implementation is similar as in #1081, which made it much easier to implement now.

**Comment by sschmidTU** [comment]
It looks like staffline alignment scope should be the standard, as the measure wise alignment scope with its ups and dows of positioning looks a bit unattractive to me in the visual diffs of our samples:
![image](https://user-images.githubusercontent.com/33069673/141326479-96e5f611-8fcd-4cd5-b355-8277840753d9.png)

measure wise:
![image](https://user-images.githubusercontent.com/33069673/141326529-b0dee27f-361a-4fd4-841c-b3f4b438100d.png)

staffline wise alignment looks much better, and basically doesn't use more space except maybe potentially for the composer label in some cases

This sample has actually only 1 pixel more height with staffline alignment than with measuer alignment. (997 vs 996)

**Comment by sschmidTU** [comment]
Also, by the way, all GraphicalLabels now have their SVG Node as an accessor, so you can manipulate it live and e.g. change the chord text via SVG without re-rendering the whole sheet:
```js
const chordSVG = osmd.graphic.MeasureList[0][0].staffEntries[0].graphicalChordContainers[0].GraphicalLabel.SVGNode;
chordSVG.children[0].textContent = 'C7';
```
![image](https://user-images.githubusercontent.com/33069673/141333474-3fba312f-8883-435d-8f8a-86eb1755906a.png)
