### ISSUE TITLE
Pickup bar notes justified too far left

### ISSUE THREAD

**Issue by jnpdx** [opensheetmusicdisplay/opensheetmusicdisplay#938]
When rendering something with a pickup bar with one quarter note, that quarter note is justified to the left of the pickup bar instead of to the right.
<img width="995" alt="Screen Shot 2021-01-14 at 12 29 04 PM" src="https://user-images.githubusercontent.com/50815/104655504-a508a600-5672-11eb-866a-fea0882b67b9.png">

You can test this on the demo site with the attached MusicXML file.
[PickupBar.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5817247/PickupBar.zip)

The two options I see to solving this are making the width of the pickup bar smaller so that justification of the note(s) is irrelevant or shifting the notes to the right.

I'm happy to look into submitting a PR for this if someone can direct me towards where to look to adjust things.

**Comment by sschmidTU** [comment]
I could have sworn we already had an issue for this.
For the layouting, it seems like Vexflow isn't getting the right rhythm, it should be given a 1/4 rhythm basically for your example.
But that should only make the note be positioned differently, in the center of the measure i guess.
Making the measure smaller is an excellent idea. You just have to check that you still respect the `measure.beginInstructionWidth`.

@jnpdx  If you could help out with a PR, that would be fantastic!
A pickup measure is identified by `SourceMeasure.ImplicitMeasure = true`.
For setting the measure with, you should mostly be looking at `MusicSystemBuilder`, specifically around the `buildMusicSystems()` and `addMeasureToSystem()` methods.
Maybe the default initial width we give to measures is too large for small pickup measures.

**Comment by sschmidTU** [comment]
@jnpdx Are you (still) working on this? I'm looking for last features to add to the new release, and this would be nice one. Maybe i can also find the improvement quickly myself.

**Comment by jnpdx** [comment]
@sschmidTU Hi Simon -- I'm working on this project as part of a contract with a company and they haven't allotted any more hours to work on it at this time. I'd still be open to working on it, it just might not happen immediately. Let me know if you decide to address it yourself or not.

**Comment by sschmidTU** [comment]
@jnpdx no problem, thanks for the response!
I'm currently looking at it and it my be a quick fix, fingers crossed!

**Comment by sschmidTU** [comment]
Fixed.

before:
![image](https://user-images.githubusercontent.com/33069673/105399868-7a938b80-5c24-11eb-8b95-8a86e3b6f41d.png)
after:
![image](https://user-images.githubusercontent.com/33069673/105399556-1375d700-5c24-11eb-9c97-02cc43f6bd2b.png)

**Comment by sschmidTU** [comment]
I discovered a further issue that will need cleanup after this commit:
maxStaffEntries were only considered for the top measure (e.g. voice in voice+piano scores).
The length should be scaled according to the maxStaffEntries across all instruments.
But this will influence spacing for all multi instrument scores, so it will be in a separate commit.

**Comment by sschmidTU** [comment]
A couple more before/after comparisons:

![image](https://user-images.githubusercontent.com/33069673/105399693-4324df00-5c24-11eb-8f72-d37a8eedfc0d.png)
![image](https://user-images.githubusercontent.com/33069673/105399720-4c15b080-5c24-11eb-882f-33617565c2ae.png)

![image](https://user-images.githubusercontent.com/33069673/105400172-e118a980-5c24-11eb-8af9-88ff15940818.png)
![image](https://user-images.githubusercontent.com/33069673/105400422-31900700-5c25-11eb-835d-cee509e0f507.png)

![image](https://user-images.githubusercontent.com/33069673/105400499-4b314e80-5c25-11eb-862f-005fae25865d.png)
![image](https://user-images.githubusercontent.com/33069673/105400063-b9c1dc80-5c24-11eb-96fc-ab16ea25a852.png)

sample diffs, just for the pickup measure changes:
[diff_pickup_measure_width.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5851604/diff_pickup_measure_width.zip)

**Comment by jnpdx** [comment]
Thank you for taking a look at this. It's interesting to look at the commits to see how it was achieved. Hopefully I'll be able to dig more into how the system works and be a contributor in the future.

**Comment by sschmidTU** [comment]
The pickup measures are now also widened per accidental, as these are basically as wide as notes, and weren't accounted for:
(before/after)
<img src="https://user-images.githubusercontent.com/33069673/105400063-b9c1dc80-5c24-11eb-96fc-ab16ea25a852.png" height="170">
<img src="https://user-images.githubusercontent.com/33069673/105717190-20464380-5f20-11eb-8a2d-68099a2c415f.png" height="170">

with many accidentals:
<img src="https://user-images.githubusercontent.com/33069673/105717561-921e8d00-5f20-11eb-94e9-6ca20efdda65.png" height="170">
<img src="https://user-images.githubusercontent.com/33069673/105717343-4e2b8800-5f20-11eb-97b3-491e82faab99.png" height="170">

This may be a good idea for all measures, not just pickup measures,
and fix some issues with note overlaps and some measures being shortened too much by our spacing.
But this will need a readjustment of our spacing variables, with more tightening, but added space for accidentals and staff entries.
