### ISSUE TITLE
Segno and Coda make slurs and lyrics position wrong

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#939]
![sdfsf](https://user-images.githubusercontent.com/56290540/104690440-c8515500-5747-11eb-9382-f7e2f4cec85c.png)

[Segno and Coda make slurs and lyrics position wrong.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5818868/Segno.and.Coda.make.slurs.and.lyrics.position.wrong.zip)

**Comment by sschmidTU** [comment]
Fixed.

See #920 and commit 9643493.

![image](https://user-images.githubusercontent.com/33069673/105094392-83f5ea00-5aa4-11eb-8e8f-770dabebbe2a.png)

Test sample added to our tests: `test/data/test_staverepetitions_coda_etc_positioning.musicxml`.

Thank you @djae88 for the report(s) and sample(s), very helpful! :)
