### ISSUE TITLE
lyrics with space/elision not rendered correctly

### ISSUE THREAD

**Issue by kochchy** [opensheetmusicdisplay/opensheetmusicdisplay#941]
when there is lyrics like this, osmd renders only the first element text ingoring the elision and second text element
```
    <lyric default-y="-81" number="1">
          <syllabic>single</syllabic>
          <text>„V </text>
          <elision> </elision>
          <syllabic>single</syllabic>
          <text>Bo</text>
        </lyric>
        
```
musescore:
![image](https://user-images.githubusercontent.com/4039441/104913094-697d1d00-598d-11eb-9aa6-585541599207.png)
osdm:
![image](https://user-images.githubusercontent.com/4039441/104913152-7dc11a00-598d-11eb-83fa-72d4e7a1b1bc.png)

**Comment by sschmidTU** [comment]
@kochchy could you share the sample? A 1-2 measure extract would be fine.
Thanks for reporting!

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/105071631-269e7080-5a85-11eb-9da5-0c889b727a47.png)

Recreated basic one measure sample:
lyrics_space_test.musicxml.zip

By the way, relevant MusicXML documentation:
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-lyric.htm
