### ISSUE TITLE
The DTD Format Issue

### ISSUE THREAD

**Issue by kevoo** [opensheetmusicdisplay/opensheetmusicdisplay#942]
Do you support the document type of midixml? I really hope to use this tool, but currently we can convert midi to midixml.dtd format xml, but there is no way to convert it to partwise.dtd format.

**Comment by sschmidTU** [comment]
OSMD can't read MIDI, it's also a format that's not made for being displayed, but for being played back.
Usually MIDI files displayed as sheet music look strange and not remotely how a human would write it.

If you still want to display midi files, you need to find a converter from midi to musicxml or midixml to musicxml.
Here's one from midi to musicxml:
https://github.com/kaibadash/midi2musicxml

This seems to be able to convert from midixml to midi (Windows):
https://sourceforge.net/projects/midiklavar/

Here's a stackoverflow question which only finds an online converter from midi to musicxml:
https://stackoverflow.com/questions/61969365/convert-midi-to-musicxml-based-on-scheme-midixml-dtd

**Comment by sschmidTU** [comment]
Feel free to comment even if the issue is closed.

**Comment by kevoo** [comment]
Ok , thanks for your suggestion
