### ISSUE TITLE
Automatic Scroll while Cursor is working

### ISSUE THREAD

**Issue by lianusmusic** [opensheetmusicdisplay/opensheetmusicdisplay#943]
Hello, I would Like to know if there is any _automatic scroll_ code to add to the cursor 

I am testing to move with the setTimeout since I am hooking it to an audio file. 
But when scores are long, cursor disappear

this is only my testing code I wonder If I can add anything to make the cursor scroll down when it gets to the end of the page
Thank you
    osmd.render();
    osmd.cursor.show();
    setTimeout(function(){ osmd.cursor.hide();osmd.cursor.next(); }, 1000);
    setTimeout(function(){ osmd.cursor.show();osmd.cursor.next(); }, 2000);
    setTimeout(function(){ osmd.cursor.next(); }, 3000);
    setTimeout(function(){ osmd.cursor.next(); }, 4000);

**Comment by sschmidTU** [comment]
This sounds like `osmd.FollowCursor = true` to me. Scrolling on `cursor.next()`, right?

**Comment by lianusmusic** [comment]
Thank you very much. worked perfect.

**Comment by pokemon963** [comment]
Hi, I want to do a similar thing too. It works when I use osmd.cursor.next. However, when I am advancing the cursor as my audio is playing, it would only scroll the cursor into view when I pause the audio and I am not sure why.

This is a segment of my code when advancing my cursor when the audio is playing:

```
if ((audioTime >= textTime) && (audioTime < nextTextTime)) {
              console.log(textfile_list[index][1]);
              // console.log(audioTime);

              const targetFraction = new opensheetmusicdisplay.Fraction((measure - 1) * score_numerator, score_denominator).Add(new opensheetmusicdisplay.Fraction(numerator, denominator));
              // const targetFraction = new opensheetmusicdisplay.Fraction((denominator * (measure - 1)) + numerator, denominator); // computes for position
              osmd.cursor.iterator = new opensheetmusicdisplay.MusicPartManagerIterator(osmd.Sheet, targetFraction);
              osmd.cursor.update(); // updates cursor
            }
```
