### ISSUE TITLE
Modifier/Accidental attached to wrong note

### ISSUE THREAD

**Issue by MarcinKarpeta** [opensheetmusicdisplay/opensheetmusicdisplay#944]
Hi,
 we have noticed that sometimes when we have chord in xml written from 'top to bottom' we get modifier attached to wrong note. Minimal example below:
 
 OSMD:
![image](https://user-images.githubusercontent.com/51373818/105344436-392ebc00-5be3-11eb-8b86-637ae4d7a2cf.png)

for xml 
[minimal_broken_chord.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5848899/minimal_broken_chord.zip)
. The modifier should be on upper note:

![image](https://user-images.githubusercontent.com/51373818/105344913-de499480-5be3-11eb-83a0-fe73ba9f176a.png)

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/105387214-993e5600-5c15-11eb-97a1-04d5071eb441.png)

Sample added to our test samples in `test/data/`:
[test_sorted_notes_chord_vexflow_keys_order.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5850980/test_sorted_notes_chord_vexflow_keys_order.musicxml.zip)

Thanks for the report and great minimal sample!

**Comment by MarcinKarpeta** [comment]
Perfect! Thank you for so quick response!
