### ISSUE TITLE
Stem direction wrong when notes beamed

### ISSUE THREAD

**Issue by Sterv** [opensheetmusicdisplay/opensheetmusicdisplay#945]
Expected Output (from Sibelius):
<img width="436" alt="sibelius-beamed-notes-bug" src="https://user-images.githubusercontent.com/15314701/105505009-6daf8000-5c96-11eb-972f-d28e761ec89e.png">

OSMD Output:
<img width="405" alt="osmd-beamed-notes-bug" src="https://user-images.githubusercontent.com/15314701/105505016-6f794380-5c96-11eb-97d4-d517849fbee7.png">

In the .musicxml file, there are` <stem>up</stem> `tags nested in each `<note></note>`.

File:
[beamed-notes-stem-direction-example.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5856570/beamed-notes-stem-direction-example.zip)

**Comment by sschmidTU** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/33069673/105523098-49779180-5cde-11eb-8b54-e0707e19d670.png)

By the way, see `EngravingRules.PercussionOneLineCutoff` for rendering drum scores on one line.
By default, drum scores with less than 3 unique note positions are rendered on one line.

visual diffs (all positive changes):
test_drum_tuplet_beams_measure1.musicxml_1 1.18534
test_drum_tuplet_flat_beams_Siebener_Endstreich_testFlam.musicxml_1 0.244955
MuzioClementi_SonatinaOpus36No1_Part2.xml_1 0.192433
test_percussion_beamed_notes_tuplet_stem_direction.musicxml_1 0.15122

diff images:
[visualdiff_stem_directions.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5857473/visualdiff_stem_directions.zip)

**Comment by Sterv** [comment]
Thanks so much!

It seems that, OSMD automatically places notes when it renders a single line notation? I need the note placement to match my XML file. Is that possible?

Expected Output (from Sibelius):
![Screen Shot 2021-01-25 at 2 20 43 PM](https://user-images.githubusercontent.com/15314701/105755065-cc842c00-5f18-11eb-80f7-add6f3f894c3.png)

OSMD Output: 
![Screen Shot 2021-01-25 at 2 23 01 PM](https://user-images.githubusercontent.com/15314701/105755103-d9088480-5f18-11eb-9e81-4d0ea7614dd7.png)

**Comment by sschmidTU** [comment]
@Sterv i added a new option to use the positioning (display step) given in the XML:
`osmd.rules.PercussionOneLineUseXMLDisplayStep = true;`

I haven't tried this with larger scores because i don't have a larger sample where this info is given in the XML,
could you provide a slightly larger extract or sample or check that it works correctly?

**Comment by sschmidTU** [comment]
There is also a new EngravingRule `osmd.rules.PercussionOneLineXMLDisplayStepOctaveOffset`,
since unfortunately it seems the octave offset is not the same between different samples.

**Comment by Sterv** [comment]
Of course. Thanks so much for your help.

When I added a second note directly on the line:

Expected Output (from Sibelius):
<img width="871" alt="Screen Shot 2021-01-25 at 6 23 11 PM" src="https://user-images.githubusercontent.com/15314701/105778494-82ac3d80-5f3a-11eb-924b-a9c424120757.png">

OSMD Output:
<img width="260" alt="Screen Shot 2021-01-25 at 6 23 28 PM" src="https://user-images.githubusercontent.com/15314701/105778535-922b8680-5f3a-11eb-9bf8-420038bf62dd.png">

[two-notes.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5870208/two-notes.musicxml.zip)

**Comment by sschmidTU** [comment]
@Sterv Fixed:
![image](https://user-images.githubusercontent.com/33069673/105779588-f700d400-5f6e-11eb-903b-deef15c1b665.png)

There was one condition missing where the setting wasn't applied.
Of course, the XML says exactly where the notes should be (D and E),
though positioning them correctly when Vexflow is set to display a single line is a bit tricky (`Pitch.stepFromNoteEnum`).

This barely didn't make it into OSMD 0.9.0, which i just released, but it will be in the next version!

**Comment by Sterv** [comment]
Thanks so much. Here's another one that does not match my Sibelius file:

Expected Output (from Sibelius):
<img width="773" alt="Screen Shot 2021-01-25 at 6 39 57 PM" src="https://user-images.githubusercontent.com/15314701/105779639-c6a04200-5f3c-11eb-8f53-5ac9d7138099.png">

OSMD Output:
<img width="430" alt="Screen Shot 2021-01-25 at 6 38 50 PM" src="https://user-images.githubusercontent.com/15314701/105779683-dddf2f80-5f3c-11eb-9406-92db95868f90.png">

[gankogui-bug.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5870256/gankogui-bug.zip)

**Comment by Sterv** [comment]
Thank you, will report on any issues if I find them!

**Comment by sschmidTU** [comment]
Ah, this is an issue with the octave offset, it works with `osmd.rules.PercussionOneLineXMLDisplayStepOctaveOffset = 1`:
![image](https://user-images.githubusercontent.com/33069673/105779946-b786b780-5f6f-11eb-93c2-1e795e9d6f8e.png)

@Sterv could you make a sample file that is basically a C major scale going from C to the next C?
That would be great for testing the octave shift.

I know where to apply the solution, but i'm not quite sure about the specific values.

**Comment by sschmidTU** [comment]
(MuseScore doesn't export `displayStep`, and it also doesn't display the sample correctly:)
![image](https://user-images.githubusercontent.com/33069673/105781913-b5bef300-5f73-11eb-9b34-f1bf0496c242.png)

Unfortunately i don't have access to Sibelius currently.

**Comment by Sterv** [comment]
Sorry I keep deleting comments. I figured out the solution right after I posted the comment  :P 

Here's C4 to C5.
[c4-c5.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5870421/c4-c5.zip)

Please let me know if there's more I can do.

**Comment by sschmidTU** [comment]
I think I found the bug and solution.
When we shift the note by 3 notes to correct the placement, we sometimes have to shift the octave as well of course.

@Sterv Thanks for the sample, that's great, but it's F3 to F4, right? Not C4 to C5.
At least that's what the MusicXML says as well. It may be that Sibelius sometimes exports incorrectly, but i think this really should be F3 to F4, right?

![image](https://user-images.githubusercontent.com/33069673/105784360-ef462d00-5f78-11eb-8e96-310f43240716.png)

Anyways, no problem, shortly before you wrote I managed to get a C scale by editing your earlier XML:
![image](https://user-images.githubusercontent.com/33069673/105784412-0c7afb80-5f79-11eb-9b52-0c61447ff1e0.png)
`test_percussiononelineusexmldisplaystep_octave.musicxml`

Your earlier gankogui sample now also displays correctly (as well as the two notes sample):
![image](https://user-images.githubusercontent.com/33069673/105784484-346a5f00-5f79-11eb-96db-4d7174b596f8.png)

**Comment by sschmidTU** [comment]
@Sterv the full fix is now released in OSMD 0.9.1!
I couldn't stand looking at the 1 hour old 0.9.0 anymore after i fixed this and one other big issue (#747) ;)

**Comment by Sterv** [comment]
Awesome, thanks so much.

The notes in the exported .musicxml does not match the pitch names in Sibelius. Here's a gif demonstrating that bug:
![sibelius-export-bug](https://user-images.githubusercontent.com/15314701/105898135-16d3de80-5fe7-11eb-92df-3c74e5fd1322.gif)

**Comment by sschmidTU** [comment]
Yes, that's weird. Maybe the unpitched pitches for drums in MusicXML follow special rules?
The display seems identical to the new display in OSMD, so this may all work as intended.
