### ISSUE TITLE
Multiple voice position issue

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#947]
![image](https://user-images.githubusercontent.com/56290540/105666409-80d38180-5f1c-11eb-9fe1-52540126dfc3.png)
↑ Sibelius

![image](https://user-images.githubusercontent.com/56290540/105666388-76b18300-5f1c-11eb-92d5-0dc17564e084.png)
↑ OSMD
[Multiple voice position issue.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5864567/Multiple.voice.position.issue.zip)

first,
there are two voices here.
It's been sorted out in the stem direction
If it's the same note, it's like the first one comes first and second one comes later in the order of the voices
but when the first note(first voice) has dot, OSMD doesn't seem to consider about it and I think that's why there's an overlap.
![sdfsfds](https://user-images.githubusercontent.com/56290540/105666827-749bf400-5f1d-11eb-943f-69db14f5371a.png)

and 
OSMD shows two note in the same position and this makes the sheet quite messy.
![image](https://user-images.githubusercontent.com/56290540/105667579-df99fa80-5f1e-11eb-9328-9d94b32b411e.png)

and I found that 
MusicXML has double stem document
http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-stem.htm
adding double stem property to OSMD or
like Sibelius, export XML as up&down but display as a double stem (exclude when dot)
will be also a good way.

Best Wishes

**Comment by sschmidTU** [comment]
Fixed. (first sample)
![image](https://user-images.githubusercontent.com/33069673/126008316-1de93b47-362b-4b24-a61e-2a00a943240a.png)
The second sample should also be fixed, but you can share it here or via Discord and we can take a look.
