### ISSUE TITLE
Chord symbols center align option?

### ISSUE THREAD

**Issue by djae88** [opensheetmusicdisplay/opensheetmusicdisplay#948]
![image](https://user-images.githubusercontent.com/56290540/105815441-3e7e7300-5ff6-11eb-89b2-8d4167725f20.png)

After updating OSMD recently, 
I noticed that the chord symbols were changed to left alignment
So I tried to adapt myself to this
But I'm used to the center alignment, so I tried to go back
But I couldn't find that option

Something like "LyricsAlignmentStandard"
"ChordsAlignmentStandard" option will be good way for people like me

Best Wishes

**Comment by sschmidTU** [comment]
Yes, this was changed in #928.
I added EngravingRules for this that you can change:
```js
osmd.rules.ChordSymbolTextAlignment = CenterBottom; // 5, new default is LeftBottom (2)
osmd.rules.ChordSymbolRelativeXOffset = 0.0; // new default is -1.0
```
