### ISSUE TITLE
Grace Note Fingerings, String Numbers (Violin)

### ISSUE THREAD

**Issue by jmorag** [opensheetmusicdisplay/opensheetmusicdisplay#949]
First of all, thank you very much for fixing #878. It's been very helpful to be able to insert fingerings on grace notes. Before, I was re-writing pieces without grace notes in order to be able to do that. It got ugly.... Anyway, my application also needs to display string numbers. So far, I've been doing that by hacking in lyrics, but that gets complicated with grace notes and multiple voices. It would be preferable if string numbers were natively supported by OSMD. Keeping with the ysaye example from #878,  Musescore renders 
![image](https://user-images.githubusercontent.com/24941170/105945704-cb93ed00-6033-11eb-9f5b-877cbd72898b.png)
whereas OSMD renders
![image](https://user-images.githubusercontent.com/24941170/105945856-17df2d00-6034-11eb-8221-c26f37a275b7.png)
(ignore the blue note at the end, I manually colored that in the svg for unrelated reasons).

Here's the updated file [test_grace_note_fingerings_and_strings_Ysaye_excerpt.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5877839/test_grace_note_fingerings_and_strings_Ysaye_excerpt.txt)

This came up a while ago in https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/711. Since then, I've made some progress on the live-editing front. You can see the results at https://open-strings.com. It allows users to upload and edit fingerings and even infers fingerings if you ask it to. Live editing of fingerings in OSMD is accomplished by this [pile of hacks](https://github.com/jmorag/open-strings/blob/master/static/js/fingeringeditor.js) that operate directly on the SVG in lieu of proper re-rendering at the Vexflow level. I doubt any of that code would be useful to upstream but if you think it could be helpful I can work on integrating it into OSMD proper.

**Comment by sschmidTU** [comment]
Done.

![image](https://user-images.githubusercontent.com/33069673/106046664-dbb6d580-60e2-11eb-8aa8-ec6d9a3b2a9c.png)

New EngravingRule:
```js
osmd.rules.StringNumberOffsetY = 0.0; // default, try 5.0 (vexflow units / pixels)
```

**Comment by jmorag** [comment]
Thanks for getting to this so quickly @sschmidTU! It doesn't seem to work for chords, though.
OSMD
![image](https://user-images.githubusercontent.com/24941170/106395944-fcc54200-63d2-11eb-8ea7-6c82f3e2761e.png)
MuseScore
![image](https://user-images.githubusercontent.com/24941170/106395986-3ac26600-63d3-11eb-9680-ca4f9e5505df.png)
XML
[Sibelius_violin_concerto_excerpt.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5900520/Sibelius_violin_concerto_excerpt.zip)

**Comment by sschmidTU** [comment]
Ah, it's just that it doesn't display multiple string numbers on chords, right? Or any other issues?
Should be relatively simple to fix.

**Comment by jmorag** [comment]
I added a couple extra strings in multiple voices for better test coverage.
![image](https://user-images.githubusercontent.com/24941170/106396105-f08db480-63d3-11eb-9d3f-b4ebd1975a71.png)

[Sibelius_violin_concerto_excerpt.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5900527/Sibelius_violin_concerto_excerpt.zip)

**Comment by jmorag** [comment]
That's right, only the bottom string gets displayed.

**Comment by jmorag** [comment]
Multiple voices are displayed fine, it's just the chords. Still good to have the extra test coverage though.
![image](https://user-images.githubusercontent.com/24941170/106396177-54b07880-63d4-11eb-87bc-46171419c156.png)
