### ISSUE TITLE
Autogenerated MultiRestMeasures don't account for chords

### ISSUE THREAD

**Issue by jasyip** [opensheetmusicdisplay/opensheetmusicdisplay#955]
Let's say I have 3 measures that are only just rests. If the second measure has a different chord than the first one, (assuming the third measure doesn't have its own chord,) it should be just measure 1 itself and a multi rest measure of measures 2 and 3.

I can try my best to make a pull request since I'm not busy.

Edit: Here's another example (look at measures 178-179)

MuseScore: 
![image](https://user-images.githubusercontent.com/24887120/106559531-59f7eb00-64da-11eb-8abd-cb50f44b23de.png)

OSMD:
![image](https://user-images.githubusercontent.com/24887120/106559554-67ad7080-64da-11eb-9da9-aad4d4755c93.png)

**Comment by sschmidTU** [comment]
Yes, chords should be respected in `SourceMeasure.canBeReducedToMultiRest()`.
@jasyip if you could try to fix this in a PR, that would be great!

**Comment by sschmidTU** [comment]
Also, please share a musicxml sample (zipped) in this issue.

**Comment by sschmidTU** [comment]
Fixed.
Multiple rest measures are now not generated when there are chord symbols (over full rests) in measures.

![image](https://user-images.githubusercontent.com/33069673/122062556-ce7b5880-cdef-11eb-8b59-3032d7d9b6a0.png)

sample:
[chord_symbols_multirest_test.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6655995/chord_symbols_multirest_test.musicxml.zip)
Added to test samples.
