### ISSUE TITLE
How to improve render speed in Android

### ISSUE THREAD

**Issue by nitzanrh** [opensheetmusicdisplay/opensheetmusicdisplay#956]
Hi there,

I'm working on a mobile app using OSMD which implements pinch-zoom.
On my iPhone 11 the pinch zoom works flawlessly, however on my Xiaomi A3(running Android 10) it takes a couple of seconds to re-render the XML file after the pinch zoom is finished (the XML file is about 60 measures long).

I'm aware that OSMD mobile performance is not a priority, and obviously the iPhone is a MUCH stronger device than the Xiaomi, however I was wondering if there is any way to reduce the rendering time on older/weaker devices.

Cheers,
Nitzan

**Comment by DavidQinqianWu** [comment]
well, I sitll think the best way to optimize the rendering time is you
pre-render the musicXML, science the OSMD render it by SVG file, so you can
save it as the svg file, then use the <g> tag to do the self-fitting of
each different devices

nitzanrh <notifications@github.com> 于2021年2月2日周二 下午4:25写道：

**Comment by nitzanrh** [comment]
Hi David,

If I understand you correctly, you're suggesting to use a SVG file and scale it according to the screen size, correct?
The problem I anticipate is that this wouldn't re-arrange the measures inside the system according to their size.
For example:
If at zoom=1 there is 1 measure per system, at zoom=0.5 you would have 2 measures per system, each half the size.
Does that make sense?
If I rescale the SVG file I would still have the same number of measures per system, only smaller. Or am I missing something?

Cheers,
Nitzan

**Comment by sschmidTU** [comment]
> If I rescale the SVG file I would still have the same number of measures per system, only smaller.

Yes. You would have to give the correct dimensions you want to the OSMD SVG export (`generateImages_browserless.js`). Then if you want to adjust the dimensions, you have to render again.
More information on SVG/PNG export:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/670#issuecomment-760427003

(we should make a wiki page for exporting)

as for performance, there isn't much you as a user can do except reducing the resolution and then scaling, we're looking into performance improvements on OSMD's side, see #937.

You could try `compacttight` mode, maybe not rendering the title, composer etc. helps.
`osmd.setOptions(drawingParameters: "compacttight")`

**Comment by nitzanrh** [comment]
Hi @sschmidTU, thanks for your response :)

I understand, it seems like this is something you guys are looking into.
In the meantime I will just add a loading indicator over the score, just to make the UI more appealing. 

Appreciate your great work :)

**Comment by nitzanrh** [comment]
@sschmidTU I wonder if there is any way to reduce the calls to getImageData?
currently SkyLineBottomCalc draw every measure onto the canvas, then getting the data for every measure. Is it possible to draw all the measures onto the canvas and then calling getImageData once?

**Comment by sschmidTU** [comment]
I don't think the per measure calls are a problem, since we only get the image data for each measure, and that canvas is restricted to the measure's width and height. It may be that it would be slightly more efficient to draw all the measures at once, but then we would basically need our complete layouting in the SkyBottomLineCalculator.
But there are some other angles we could try as well.

**Comment by sschmidTU** [comment]
Note that we recently improved the render speed in our early access sponsor build. This should at some point come to main OSMD too, though we still need to fix some issues with the visual regression tests.

**Comment by sschmidTU** [comment]
If you use fingerings, render speed should also be increased now, see #1081.
Other than that, there as not much actionable specific to this issue that we can do, except general performance improvements. There has been some useful discussion here though.
