### ISSUE TITLE
How is Vex.Flow.SVGContext imported

### ISSUE THREAD

**Issue by jasyip** [opensheetmusicdisplay/opensheetmusicdisplay#958]
At MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts , it seems that using `Vex.Flow.SVGContext` only needs `import Vex from "vexflow";` and works successfully.

However, in https://github.com/0xfe/vexflow/blob/master/src/index.js , I do not see SVGContext exported anywhere. I tried importing SVGContext the same way as this project does in my personal project and I get an error.

How is this project able to successfully do so?

**Comment by sschmidTU** [comment]
I'm not sure, it should be exported by vexflow even if it's not in the index.ts, maybe by the webpack settings in `gruntfile.js`.
In the vexflow-debug.js, you'll find this:
```js
/* harmony import */ var _svgcontext__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./svgcontext */ "./src/svgcontext.js");
```
and this:
```js
/***/ "./src/svgcontext.js":
/*!***************************!*\
  !*** ./src/svgcontext.js ***!
  \***************************/
/*! exports provided: SVGContext */
/***/ (function(module, __webpack_exports__, __webpack_require__) {
```

Are you using Typescript? Maybe you need this in your tsconfig.json:
`esModuleInterop = true`

Otherwise, i would suggest asking in the Vexflow discussions maybe, as this is a Vexflow issue, not an OSMD issue.

**Comment by jasyip** [comment]
So, `src/MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts` does `import Vex from "vexflow";` , which seems normal when trying to import anything from VexFlow. Then it references SVGContext with `Vex.Flow.SVGContext` and works no problem. I do it the exact the same way as this project does in my own project with the content of the file here:

```
import Vex from "vexflow";

export class ImcorviseSVGContext extends Vex.Flow.SVGContext
{ 
    public openGroup(cls: string, id: string, attrs) : HTMLElement
    {
        const group = this.create('g');
        this.groups.push(group);
        this.parent.appendChild(group);
        this.parent = group;
        if (cls) 
        {
            group.setAttribute('class', Vex.Prefix(cls));   
        }
        if (id)
        {
            group.setAttribute('id', Vex.Prefix(id));
        }
        return group;
    }
}
```

And I get this error (meaning that it is unable to properly reference SVGContext:
```
Uncaught TypeError: Super expression must either be null or a function
    _inherits src.e31bb0bc.js:28004
    ImcorviseSVGContext src.e31bb0bc.js:28026
    parcelRequire<["Graphical/ImcorviseSVGContext.ts"]< ImcorviseSVGContext.ts:3
```

My project can be visited here: https://github.com/jasyip/imcorvise
My project uses parceljs as a bundler, but I can try switching to webpack to see if it makes a difference
And here is the contents of its `tsconfig.json`:
```
{
    "compilerOptions":
    {
        "target": "es2017",
        "esModuleInterop": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "noUnusedLocals": true,
        "outDir": "dist",
        "declaration": true,
        "sourceMap": true,
        "typeRoots": ["./node_modules/@types"]
    },
    "exclude":
    [
        "node_modules",
        "dist",
        "demo",
        "build"
    ]
}
```

I appreciate the help you have given me so far! Thanks!

**Comment by sschmidTU** [comment]
Have you tried these things?
https://stackoverflow.com/questions/44008340/typescript-extend-class-with-imported-class
either check the export order, or, what's maybe more likely to work, import SVGContext directly.

**Comment by sschmidTU** [comment]
Also check these:
https://stackoverflow.com/questions/30116430/reactjs-giving-error-uncaught-typeerror-super-expression-must-either-be-null-or
https://stackoverflow.com/questions/44958392/super-expression-must-either-be-null-or-a-function-not-object

**Comment by jasyip** [comment]
I actually just solved the problem. I did `import { SVGContext } from "vexflow/src/svgcontext";`

Thank you for the links and help you provided!
