### ISSUE TITLE
Slurs/ Fingerings

### ISSUE THREAD

**Issue by jekeough** [opensheetmusicdisplay/opensheetmusicdisplay#962]
I am running into an issue where slurs are flipped to the bottom of notes when I have fingerings in for piano.
This is what it looks like in sibelius:
![Screen Shot 2021-02-08 at 5 36 56 PM](https://user-images.githubusercontent.com/78770780/107304410-d8521100-6a35-11eb-91ae-73dfd922be6b.jpg)
This is how it appears in osmd:
![Screen Shot 2021-02-08 at 5 37 04 PM](https://user-images.githubusercontent.com/78770780/107304424-e011b580-6a35-11eb-8b7a-161f6cce4943.jpg)

The issue is that it looks a little weird to have the slurs on the opposite side of the notehead, and it seems to make the slurs a lot larger than the original in some cases.  Hoping there is a way to fix this.  Thank you!

**Comment by sschmidTU** [comment]
It seems like Sibelius exports it incorrectly in this case.
Can you share a sample/extract as MusicXML (zipped)?
I'm guessing it'll say `<placement>below</placement>` for your sample.

You can also try `osmd.rules.SlurPlacementFromXML = false`, in which case it should place the slurs above the notes, but it will also not respect any other slur placements given in your XML(s).

**Comment by jekeough** [comment]
Hi Simon,

Thank you so much!  Yeah I have definitely been having issues with
certain things when exporting xml files.  I have been finding some
resolutions through exporting from different notation programs.  Attached
below is an example from both sibelius and musescore(MS).  The one from
sibelius displays with the slurs underneath, and the one from musescore
displays them above the staff.  However, both of them seem to warp the
slurs' height depending on the length.  Do you have any thoughts on this?

Best regards,

Jack

**Comment by jekeough** [comment]
sschmidTU,

Here is a file with the slur height issue zipped.  Sorry I forgot to zip the first files I sent.
[Chopin_TroisNouvellesEtudes_No.1 copy.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5962509/Chopin_TroisNouvellesEtudes_No.1.copy.xml.zip)
Here is how it looks in Sibelius:
<img width="549" alt="Screen Shot 2021-02-10 at 4 39 18 PM" src="https://user-images.githubusercontent.com/78770780/107591065-aa4c0880-6bbe-11eb-9722-98356f1aeb7e.png">
Here is how it appears in osmd:
<img width="1063" alt="Screen Shot 2021-02-10 at 4 39 37 PM" src="https://user-images.githubusercontent.com/78770780/107591089-b46e0700-6bbe-11eb-8a96-c2f3446dc054.png">

Thanks!

**Comment by Sterv** [comment]
Just tested the file @jekeough uploaded with this commit.

Before commit:
<img width="1389" alt="Screen Shot 2021-02-16 at 4 33 19 PM" src="https://user-images.githubusercontent.com/15314701/108124334-0efedb80-7075-11eb-9249-659b095b1b39.png">

After commit
<img width="1226" alt="Screen Shot 2021-02-16 at 4 33 24 PM" src="https://user-images.githubusercontent.com/15314701/108124650-73219f80-7075-11eb-9fcb-94a574168249.png">

The slur placement matches the XML, but the curve is further from the stave. Is there anyway to control that?

**Comment by sschmidTU** [comment]
@Sterv you're right, that was a separate issue, fixed in #971.

![image](https://user-images.githubusercontent.com/33069673/108401699-e6194a80-721c-11eb-8911-ec462ad6bffd.png)

Will be released in OSMD 0.9.3 very soon (hopefully today).

**Comment by Sterv** [comment]
Thank you!
