### ISSUE TITLE
Regression: single-line staves note placement is below the staff line

### ISSUE THREAD

**Issue by jnpdx** [opensheetmusicdisplay/opensheetmusicdisplay#963]
In a recent version (although I'm not sure *exactly* which one), there's been a regression that causes notation on single-line staves to appear below the line rather than on it.

<img width="735" alt="Screen Shot 2021-02-08 at 9 36 30 PM" src="https://user-images.githubusercontent.com/50815/107320537-b7011d00-6a55-11eb-9017-ac3266bd7e98.png">

[1 - Quarter March.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5949111/1.-.Quarter.March.xml.zip)

I've attached an XML file that demonstrates this.

This can be experienced on both the current `develop` branch and on the OSMD demo page.

**Comment by sschmidTU** [comment]
Did you try this?
```js
osmd.rules.PercussionOneLineUseXMLDisplayStep = false;
```

By default, OSMD reads the placement from the XML, if it was given as one line in the XML as well.

**Comment by jnpdx** [comment]
Great -- didn't know about that option (and, hadn't had to use it before, for some reason). Thank you for the clarification!

**Comment by sschmidTU** [comment]
Yes, the option is new, since only now we can detect whether the XML gives the placement for one-line scores and read it :)
