### ISSUE TITLE
how to get bpm in different measurements

### ISSUE THREAD

**Issue by 99003486** [opensheetmusicdisplay/opensheetmusicdisplay#973]
I can get the first BPM,it is OK, but when I try to get different BPM to calculate the time for notes at each measurements, I use sourceMeasure.tempoInBPM, it seems lt always equals 0. I can use the first BPM to calcualte but what if the song change its BPM at different measurments? the musicxml I use actaully contains different BPM for different measurements. it uses \<sound tempo="71"\> tag , yes, I can use code to get the BPM from musicxml file to calculate, but if OSMD can do it for me that would be great.

**Comment by 99003486** [comment]
I found that if the \<note\> tag inside \<sound temp="55"\> tag, OSMD can't list it out.

**Comment by lianusmusic** [comment]
Hi!, when you say you get the BPM from the XML, do you use it to move the cursor? would you share the script for that case? thanks

**Comment by 99003486** [comment]
I tried to play music meanwhile the note shows different color(red), for one speed music it works OK now. but if the speed changes, it doesn't work. I tried to get the BPM from the xml, but OSMD did not list the music note which inside the /<sound temp='xx'/>tag, so I can get the BPM but since it misses notes, so it is wrong already.

**Comment by sschmidTU** [comment]
That's weird, i've never seen a `note` inside a `sound` element.
It's not MusicXML-compliant either:
https://usermanuals.musicxml.com/MusicXML/Content/EL-MusicXML-sound_1.htm
