### ISSUE TITLE
Defining BPM value for Cursor

### ISSUE THREAD

**Issue by lianusmusic** [opensheetmusicdisplay/opensheetmusicdisplay#975]
Hello OSMD ,
I work linking audios,  with the display, so I have a question 

a) Is possible to define a tempo (BPM number value) for the cursor movement.?
b)  if I can set up it manually. where should I define that.?
c)Would I be able to change that value several times in the same file defining measure position (because I work with rubato music) 

Thank you very much. in Advance

**Comment by lianusmusic** [comment]
I apologizes if I made the question in the wrong section. I know this is not an issue, this is a question. Thanks again

**Comment by sschmidTU** [comment]
@lianusmusic sorry for the late answer. You can't play the cursor with a certain BPM in the base OSMD (you would have to implement that functionality yourself), though you can do it in our audio player. It's currently in early access, so it's not completely finished, but already works quite well, it's accessible as an OSMD sponsor (on github), see the button at the top.
