### ISSUE TITLE
How to change specific note's NoteheadColor without re-render entire music sheet?

### ISSUE THREAD

**Issue by qky1412** [opensheetmusicdisplay/opensheetmusicdisplay#976]

**Comment by sschmidTU** [comment]
This is not currently possible without a re-render from OSMD itself.
You can get the SVGElement and modify the `fill` value of the `path` node:
![image](https://user-images.githubusercontent.com/33069673/109029814-8232ce00-76c3-11eb-8ee2-513f43fbca6c.png)

to get the SVGElement (`vf-stavenote`):
`document.getElementById(graphicalnote.getSVGId())`

**Comment by sschmidTU** [comment]
Even easier than `document.getElementById(graphicalnote.getSVGId())`: `graphicalnote.getSVGElement()`
(updated above comment)

**Comment by qky1412** [comment]
Thx! But I just found out that 'GraphicalNote' notes under graphicalVoiceEntries don't have getSVGId() or getSVGElement() functions, the npm version is 0.9.4.

**Comment by qky1412** [comment]
But I did find vfnote in GraphicalNote

**Comment by sschmidTU** [comment]
GraphicalNote does have these methods if you cast it to `VexFlowGraphicalNote` (`graphicalVoiceEntry.notes[0] as VexFlowGraphicalNote`). All our GraphicalNotes are VexFlowGraphicalNotes.

**Comment by qky1412** [comment]
> GraphicalNote does have these methods if you cast it to `VexFlowGraphicalNote` (`graphicalVoiceEntry.notes[0] as VexFlowGraphicalNote`). All our GraphicalNotes are VexFlowGraphicalNotes.

Thx again!
