### ISSUE TITLE
Modifidation of Array.prototype in ColectionUtil.ts breaks other libraries

### ISSUE THREAD

**Issue by brice81** [opensheetmusicdisplay/opensheetmusicdisplay#980]
Hello,

The ColectionUtil.ts module is modifying the Array.prototype, which breaks other libraries (in my case pdf.js). In particular, it prevents some ways of walking throw array elements to work properly.

The joined patch solves the issue.

Regards,
Brice

[patch.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6073728/patch.zip)

**Comment by sschmidTU** [comment]
Will look at the patch, sounds good!
I currently can't imagine the issue though, we only modify the Array prototype if the function we need doesn't exist on it yet, so i don't understand how it could cause a problem for other libraries, unless they are exploring the prototype functions and using those that don't usually exist.

**Comment by brice81** [comment]
To be honest with you, I am not a javascript guru and when I encountered the error, I did not understood how your code could have broken pdf.js library.
I googled with the error message I got, and I found the following question on stack-overflow. I followed the proposed solution to get rid of my problem : 
https://stackoverflow.com/questions/37912320/array-prototype-causing-error

**Comment by sschmidTU** [comment]
Thanks for the link and reference, sounds reasonable, patch is applied to develop! (+ reformatting and comment)
Maybe this solves issues for other people/imports as well.

**Comment by sschmidTU** [comment]
Apparently you should add `writable: true` in `defineProperty()` to ensure compatibility with other libraries modifying the prototype, see #1288.
