### ISSUE TITLE
autoGenerateMutipleRestMeasuresFromRestMeasures does not work with hidden instruments

### ISSUE THREAD

**Issue by brice81** [opensheetmusicdisplay/opensheetmusicdisplay#981]
Hello,

autoGenerateMutipleRestMeasuresFromRestMeasures  is only applied if all instruments are at rest in the measures (which for me is fine). But when we display a partition in which we hide some instruments (osmd.sheet.Instruments[x].Visible = false), the instrument seems to be taken into account.

So, for example, if you have a score with two instruments, and you force the first one to be not displayed in the score with above line of code,  the measures at rest of the printed score will only be properly managed if first instrument is also at rest on same measures.

Currently, I workaround this problem by patching XML file to remove the instruments from file before rendering it. But it would be nice if library could manage it without modifying input file.

Many thanks in advance,
Brice

**Comment by sschmidTU** [comment]
Fixed.
You just need to run `osmd.updateGraphic()` after changing visibility on instruments.

Sample + sample code:
[test_autoMultiRest_invisible_instrument2_double_multirest.musicxml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6078818/test_autoMultiRest_invisible_instrument2_double_multirest.musicxml.zip)
```js
// osmd.load()
osmd.sheet.instruments[2].Visible = false;
osmd.sheet.instruments[3].Visible = false;
osmd.updateGraphic();
osmd.render();
```

all instruments visible:
![image](https://user-images.githubusercontent.com/33069673/109865333-34d6d380-7c64-11eb-925c-48e9032c77ed.png)

instruments with index 2,3 invisible:
![image](https://user-images.githubusercontent.com/33069673/109865017-db6ea480-7c63-11eb-9fca-585712be08e6.png)

There is currently an issue where if you make instruments invisible so they get a multirest, then make them visible again, they keep the multi rest. In these cases, just reload and re-render the whole sheet, which is almost as fast anyways.
