### ISSUE TITLE
Add a mechanism to get and modify XML between load and render ?

### ISSUE THREAD

**Issue by brice81** [opensheetmusicdisplay/opensheetmusicdisplay#982]
Hello,

I was forced to implement some modifications to XML input before performing rendering of the score, and I did not find any way to do it with proposed API.

One possibility would have to do it completely outside the library, before loading the document, but in this case, I would have to care of special input format (zipped, etc.). 

I slightly modified the library with joined patch to be able to retrieve the xml (and modify it) during the loading process. 

Maybe would it be useful for others ?

Regards,
Brice
[0003-Added-mechanism-to-get-and-patch-XML-before-insertio.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6073770/0003-Added-mechanism-to-get-and-patch-XML-before-insertio.zip)

**Comment by sschmidTU** [comment]
Great idea, thanks!
I renamed the function from `OnXML` to `OnXMLRead` and added the function type.
This will be released in OSMD 0.9.5 very soon (probably today).
