### ISSUE TITLE
API for part / instrument / stave selection

### ISSUE THREAD

**Issue by fheyen** [opensheetmusicdisplay/opensheetmusicdisplay#987]
Is there an easy way to select one or more parts, instruments, or staves to display, instead of showing all?
I carefully looked at all options and did not find anything there.

Since I did not find anything else, I'm thinking about a workaround similar to the one in issue #925, but I guess that this is a feature that many others would find useful as well, so there should be no workaround necessary.

If there is something like what I'm looking for, could you make it more prominent in the API and documentation (e.g. your demo)?

Thank you very much for the awesome library!

**Comment by sschmidTU** [comment]
This should be easy, if i understand you correctly:
`osmd.sheet.Instruments[2].Visible = false`
see https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/981#issuecomment-790025087:
![image](https://user-images.githubusercontent.com/33069673/109879198-93f11400-7c75-11eb-886b-3ae89c643998.png)

(note that `instruments[2]` means index 2, or the 3rd instrument from above)

**Comment by sschmidTU** [comment]
Yeah, it's probably a good idea to make this feature more prominent, i'll see for a good place to put it in the Wiki etc.

**Comment by sschmidTU** [comment]
I've put this info in the "Exploring the Demo" section in the Wiki for now:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Exploring-the-Demo#part-selection-not-rendering-individual-partsinstruments

**Comment by fheyen** [comment]
Wow thank you for the very fast reply! I was really close to the solution, but tried `osmd.sheet.Instruments = osmd.sheet.Instruments.slice(0, 2)` i.e. re-assigning the array (which obviously did not work) before deciding to create this issue.

Personally I'm fine with this solution, but I propose to mention it or this issue in the [getting started](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Getting-Started) as well, since it seems like a basic feature to me.

**Comment by fheyen** [comment]
For completeness: Is there anything like this for selecting parts and staves? Although I'm not sure this is necessary in common use cases...

**Comment by sschmidTU** [comment]
I've mentioned and linked it at the bottom of Getting Started as well now, though the start of the Getting Started page does mention that for learning OSMD you should check out the Exploring the Demo page ;)

**Comment by sschmidTU** [comment]
This is selecting parts (= setting instrument visible/invisible). Do you mean measures?

**Comment by fheyen** [comment]
I mean there could be a Piano part with two staves (left and right hand) and you would want to select only the right hand stave, is this handled as two different instruments in OSMD or how would I select the stave?

**Comment by sschmidTU** [comment]
Not rendering parts of instruments (e.g. only piano right hand) is not possible right now, i think. That might need far more complex changes.

**Comment by fheyen** [comment]
Ok, I guess there is always the workaround to split it into two instruments..
But since that use case might be rare, I suppose implementing something complex here would not be necessary.
Thanks again for the help!
