### ISSUE TITLE
Repetition symbol x position.

### ISSUE THREAD

**Issue by ryohorie** [opensheetmusicdisplay/opensheetmusicdisplay#990]
The repetition symbols(D.C., D.S.) are shifted to the right.
MuseScore
<img width="926" alt="スクリーンショット 2021-03-08 10 01 07" src="https://user-images.githubusercontent.com/1633183/110261883-3f42f580-7ff5-11eb-9e5d-21dc4fa598fa.png">
OSMD
<img width="878" alt="スクリーンショット 2021-03-08 10 02 25" src="https://user-images.githubusercontent.com/1633183/110261951-6f8a9400-7ff5-11eb-823d-d9ad5e667bc9.png">

**Comment by sschmidTU** [comment]
can you share a sample? (zipped)
also, make sure the symbols are in the correct measure in the musicxml. often music programs export musicxml incorrectly.

**Comment by ryohorie** [comment]
[0114-You Are The Sunshine Of My Life.xml.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6112225/0114-You.Are.The.Sunshine.Of.My.Life.xml.zip)

I also checked on the demo site.
https://opensheetmusicdisplay.github.io/demo/

And, I also checked the musicxml with text editor.
D.C is above 33th measure. (in 32nd measure)
<img width="391" alt="スクリーンショット 2021-03-10 9 42 17" src="https://user-images.githubusercontent.com/1633183/110558067-2e28ee80-8185-11eb-9556-3884bf383c53.png">
but osmd show at 33th measure on the demo site.
<img width="251" alt="スクリーンショット 2021-03-10 9 43 20" src="https://user-images.githubusercontent.com/1633183/110558298-9546a300-8185-11eb-9a44-d92b99c09ceb.png">

**Comment by ryohorie** [comment]
Thank you so much!
