### ISSUE TITLE
Huge gaps between staffs for tablature in any non-endless page size

### ISSUE THREAD

**Issue by SevenBlocks** [opensheetmusicdisplay/opensheetmusicdisplay#992]
When viewing guitar tab with any page size other than endless mode, there are huge gaps between staffs, usually putting just one staff per page.

Example with letter portrait page size. [test_tab.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6124637/test_tab.zip)
![large_gaps](https://user-images.githubusercontent.com/8278755/110824706-2716e480-8248-11eb-9b83-3dfd579c4c30.png)

**Comment by sschmidTU** [comment]
That's weird. Are you sure you haven't enabled page breaks (`osmd.rules.NewPageAtXMLNewPageAttribute`)?
It's probably a different issue anyways though. Would be interesting to check the bounding boxes of the system etc.

**Comment by SevenBlocks** [comment]
@sschmidTU I built the demo to check that it wasn't anything I was doing and it still showed up in the demo. It doesn't happen with standard sheet music, only with tablature.

**Comment by SevenBlocks** [comment]
Do you know what determines the spacing between staffs? Is it the `MusicSheetCalculator` or a Vex Flow property of a `Staff` object or something else?

**Comment by sschmidTU** [comment]
It's mostly the bounding boxes of the systems.
There's also spacing variables like `osmd.rules.MinimumDistanceBetweenSystems`, but that's only a few note lines wide, that's not the cause of this.

**Comment by SevenBlocks** [comment]
I think I found a bug. The SkyBottomLineCalculator is computing NaNs for `mBottomLine`, because `unitInPixels` is undefined [here](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/1d3e18ff0700d8755703d57ade36c577805282eb/src/MusicalScore/Graphical/SkyBottomLineCalculator.ts#L152):

`this.mBottomLine = this.mBottomLine.map(v => (v - Math.min(...this.mBottomLine)) / unitInPixels + this.StaffLineParent.BottomLineOffset);`

**Comment by sschmidTU** [comment]
Are you sure about that? `unitInPixels` is a static import, i don't know how that could happen.
```js
export const unitInPixels: number = 10; // definition in VexFlowMusicSheetDrawer
```

**Comment by SevenBlocks** [comment]
Those are the values I saw when I stepped through with the debugger:
![nan](https://user-images.githubusercontent.com/8278755/110855363-13c94080-826b-11eb-8228-8f05bc4776a5.png)

**Comment by sschmidTU** [comment]
Yes, it seems that can happen sometimes with the skyline, but that's not from unitInPixels.
But still, this looks very helpful, if it's the location where the error comes from!

**Comment by SevenBlocks** [comment]
Oh, you're right. It's actually because mBottomLine already has some NaN values in the array.

**Comment by SevenBlocks** [comment]
I was able to fix it by adding a check to fix tmpBottomLine:

```
for (let idx: number = 0; idx < tmpBottomLine.length; idx++) {
    if (tmpBottomLine[idx] === undefined) {
        tmpBottomLine[idx] = Math.max(this.findPreviousValidNumber(idx, tmpBottomLine), this.findNextValidNumber(idx, tmpBottomLine));
    }
}
```

**Comment by sschmidTU** [comment]
Hey, sounds great! So this fixes the issue?
Will check this soon and apply the patch if it fixes the issue (and visual regression tests pass etc).

**Comment by SevenBlocks** [comment]
Yes, that fixes the bug, so this issue can be closed after tests, etc.

**Comment by sschmidTU** [comment]
Cool, will check, thanks for the fix!

**Comment by sschmidTU** [comment]
Fixed, thanks again for the hint!
