### ISSUE TITLE
Elements wrong positioning D.C al Fine / Fine  and fingerings with placement

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#993]
I noticed that if the xml has any placement the OSMD display it wrong, should be good a option to disable the placements from XML and let OSMD handles everything.

OSMD Version: 0.9.5 (Sponsor Extended)

```xml
        <notations>
          <technical>
            <fingering placement="below">1</fingering>
            </technical>
          </notations>
```
Also notice that the D.C al Fine and Fine is right shifted

```xml
      <direction placement="above">
        <direction-type>
          <words relative-y="20.00">D.C. al Fine</words>
          </direction-type>
        <sound dacapo="yes"/>
        </direction>
```

OSMD:
![image](https://user-images.githubusercontent.com/2137569/111076098-b2eb7380-84c9-11eb-9a65-d4ade0ab89ac.png)

MUSESCORE

![image](https://user-images.githubusercontent.com/2137569/111076213-2e4d2500-84ca-11eb-85fc-eca52b735516.png)

I'm attaching the music xml file, but please do not save it for future test cases.
[LARGO 1.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6137085/LARGO.1.zip)

**Comment by sschmidTU** [comment]
You can now set `osmd.rules.FingeringPositionFromXML = false`.

![image](https://user-images.githubusercontent.com/33069673/111374616-9c961100-869d-11eb-8aba-f25b381696fd.png)

The Fine and D.C. al Fine shifting is a different issue, i opened a new one for it, #996.
