### ISSUE TITLE
Wrong Fingerings Positioning with Articulation marks

### ISSUE THREAD

**Issue by conde2** [opensheetmusicdisplay/opensheetmusicdisplay#994]
Fingerings positioning not accounting for Articulation marks

Tested with:

Accent
Marcato
Staccato

![image](https://user-images.githubusercontent.com/2137569/111077610-5a6ba480-84d0-11eb-9f0b-5cb0f8298e0f.png)
![image](https://user-images.githubusercontent.com/2137569/111077629-70796500-84d0-11eb-9b40-368bc4bdefef.png)

**Comment by sschmidTU** [comment]
Fixed by #1081.

![image](https://user-images.githubusercontent.com/33069673/141295913-b2256a10-41ce-4733-a82c-3223074d265a.png)
[test_fingering_articulation_collision.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7520298/test_fingering_articulation_collision.zip)
