### ISSUE TITLE
got this error GraphicalVoiceEntry.ts:49:38

### ISSUE THREAD

**Issue by 99003486** [opensheetmusicdisplay/opensheetmusicdisplay#995]
[187.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6138897/187.zip)

I found serval times for this error when I tried to convert musicxml files. I have already converted about 150 files, have found about 3 that doesn't work, all files I used are all from midi files which converted by cakewalk, do not know where the file is different. 
Uncaught (in promise) TypeError: e.sourceNote.Pitch is undefined
    sortForVexflow GraphicalVoiceEntry.ts:49
    sortForVexflow GraphicalVoiceEntry.ts:48
    StaveNote VexFlowConverter.ts:201
    graphicalMeasureCreatedCalculations VexFlowMeasure.ts:1149
    graphicalMeasureCreatedCalculations VexFlowMusicSheetCalculator.ts:521
    handleStaffEntries MusicSheetCalculator.ts:2378
    prepareGraphicalMusicSheet MusicSheetCalculator.ts:257
    initialize MusicSheetCalculator.ts:120
    <anonymous> GraphicalMusicSheet.ts:40
    updateGraphic OpenSheetMusicDisplay.ts:180
    load OpenSheetMusicDisplay.ts:170
    success indexhttp.html:64

GraphicalVoiceEntry.ts:49:38

**Comment by sschmidTU** [comment]
fixed, score renders now.

![image](https://user-images.githubusercontent.com/33069673/111361784-5d13f880-868e-11eb-8a8c-2dd422025d6c.png)
